'use strict';
const assert=require('node:assert/strict');
const cp=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'../../..');
const CAP='docs/digital_twin/mcft/cap_08';
const PATHS={authority:`${CAP}/GEOX-MCFT-CAP-08-S6-SINGLE-RUN-DATABASE-EXECUTION-IMPLEMENTATION-AUTHORITY-V1.json`,effect:`${CAP}/GEOX-MCFT-CAP-08-S6-FINAL-FORMAL-RUN-ORCHESTRATOR-EFFECTIVENESS-AUTHORITY-V1.json`,orchestrator:`${CAP}/GEOX-MCFT-CAP-08-S6-FINAL-FORMAL-RUN-ORCHESTRATOR-IMPLEMENTATION-V1.json`,run:`${CAP}/GEOX-MCFT-CAP-08-24-TICK-RUN-CONTRACT-V1.json`,s6:`${CAP}/GEOX-MCFT-CAP-08-S6-CONTRACT-V1.json`,dataset:`${CAP}/GEOX-MCFT-CAP-08-S5-REPLAY-DATASET-V2-EFFECTIVENESS-AUTHORITY-V1.json`};
function read(p){return JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));}
function git(...a){return cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();}
function loadSingleRunHarnessContractsV1({localReplay=process.env.MCFT_LOCAL_REPLAY==='1'}={}){const authority=read(PATHS.authority),effect=read(PATHS.effect),orchestrator=read(PATHS.orchestrator),run=read(PATHS.run),s6=read(PATHS.s6),dataset=read(PATHS.dataset);assert.equal(authority.record_status,'SINGLE_RUN_DATABASE_EXECUTION_HARNESS_IMPLEMENTATION_AUTHORIZED');assert.equal(authority.execution_constraints.single_run_database_execution_authorized,false);assert.equal(authority.execution_constraints.database_execution_workflow_authorized,false);assert.equal(effect.record_status,'FINAL_FORMAL_RUN_ORCHESTRATOR_IMPLEMENTED_EFFECTIVE');assert.equal(orchestrator.record_status,'ORCHESTRATOR_IMPLEMENTED_NOT_EFFECTIVE');assert.equal(run.tick_ids.length,24);assert.deepEqual(run.post_run_phases,['G00','G01','G02']);assert.equal(s6.formal_run_contract.slice_acceptance_object_reuse_forbidden,true);if(!localReplay){const exact={authority:'e517aa42b51557d7ced75db92ff4c104945ecc36',effect:'05ca47c17e9700dfdee042ae396395494d099fc7',orchestrator:'c5d1232bcb1810a3ebd0898c213578ca49d0cd1d',run:'7a5feecbdb204c8fdf8c21ee8ea66576133c17dd',s6:'47ff4215d711b229604b29ce6c663e62b59efc39',dataset:'b7baa289daf9f391f0b200d77c6d7ee7f18e7252'};for(const [k,v] of Object.entries(exact))assert.equal(git('rev-parse',`HEAD:${PATHS[k]}`),v,`HARNESS_AUTHORITY_BLOB_DRIFT:${k}`);}return{authority,effect,orchestrator,run,s6,dataset};}
module.exports={ROOT,CAP,PATHS,loadSingleRunHarnessContractsV1};
