'use strict';
const assert=require('node:assert/strict');
const {loadSingleRunHarnessContractsV1}=require('./contract_loader_v1.cjs');
const {buildSingleRunExecutionSpecV1}=require('./execution_spec_v1.cjs');
const {validateHarnessPortsV1}=require('./port_contract_v1.cjs');
const {invokeDirectMaterializerV1}=require('./materializer_adapter_v1.cjs');
const {buildCanonicalReceiptManifestV1}=require('./receipt_manifest_v1.cjs');
const {readExactReceiptObjectsV1}=require('./closure_readback_adapter_v1.cjs');
const {buildFinalClosureDatabaseSourceV1,rejectIneligibleDatabaseSourceV1}=require('./database_source_adapter_v1.cjs');
const {executeRecoveryVectorsV1}=require('./recovery_execution_adapter_v1.cjs');
const {executeCompleteCap07ReadbackV1}=require('./cap07_readback_execution_adapter_v1.cjs');
const {producePerRunWitnessBundleV1}=require('./witness_execution_adapter_v1.cjs');
function compileSingleRunHarnessV1(input){const contracts=loadSingleRunHarnessContractsV1();const spec=buildSingleRunExecutionSpecV1({...input,contracts});return{schema_version:'geox_mcft_cap08_s6_single_run_harness_compilation_v1',spec,port_names:['freshDatabase','materializer','closureReader','recovery','cap07Reader','artifactWriter'],database_execution_authorized:false,run_executed:false,hard_acceptance_eligible:false};}
async function executeSingleRunDatabaseHarnessV1({input,ports,executionAuthority}){validateHarnessPortsV1(ports);const compilation=compileSingleRunHarnessV1(input),spec=compilation.spec;assert.equal(executionAuthority?.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED','DATABASE_EXECUTION_AUTHORITY_REQUIRED');assert.equal(executionAuthority.exact_subject_sha,spec.exact_subject_sha,'EXECUTION_AUTHORITY_SUBJECT');await ports.freshDatabase.assertFreshDisposable({spec});const materialized=await invokeDirectMaterializerV1(ports.materializer,spec,executionAuthority);const receiptManifest=buildCanonicalReceiptManifestV1(spec,materialized.canonical_receipts);const readback=await readExactReceiptObjectsV1(ports.closureReader,spec,receiptManifest);const recovery=await executeRecoveryVectorsV1(ports.recovery,spec,executionAuthority);const cap07=await executeCompleteCap07ReadbackV1(ports.cap07Reader,spec,executionAuthority);assert.equal(cap07.product_read_write_delta,0);const source=rejectIneligibleDatabaseSourceV1(buildFinalClosureDatabaseSourceV1({spec,receiptManifest,readback,operationalEvents:materialized.operational_events,databaseInstanceDigest:materialized.database_instance_digest,artifactRef:materialized.artifact_ref,artifactDigest:materialized.artifact_digest,selectorSnapshot:materialized.selector_snapshot,executionAuthority,synthetic:false}));const witnessBundle=producePerRunWitnessBundleV1({spec,source,artifactRef:materialized.artifact_ref,artifactDigest:materialized.artifact_digest,synthetic:false});const artifact=await ports.artifactWriter.writeBundle({spec,receiptManifest,recovery,cap07,source,witnessBundle});return{schema_version:'geox_mcft_cap08_s6_single_run_database_execution_result_v1',status:'PASS',spec,receiptManifest,recovery,cap07,source,witnessBundle,artifact,hard_acceptance_eligible:true};}
function executeWithoutAuthorityV1(){throw new Error('SINGLE_RUN_DATABASE_EXECUTION_NOT_AUTHORIZED');}
module.exports={compileSingleRunHarnessV1,executeSingleRunDatabaseHarnessV1,executeWithoutAuthorityV1};
