'use strict';
const assert=require('node:assert/strict');
const {loadSingleRunHarnessContractsV1}=require('./contract_loader_v1.cjs');
const {buildSingleRunExecutionSpecV1}=require('./execution_spec_v1.cjs');
const {invokeDirectMaterializerV1}=require('./materializer_adapter_v1.cjs');
const {buildCanonicalReceiptManifestV1}=require('./receipt_manifest_v1.cjs');
const {readExactReceiptObjectsV1}=require('./closure_readback_adapter_v1.cjs');
const {executeRecoveryVectorsV1}=require('./recovery_execution_adapter_v1.cjs');
const {executeCompleteCap07ReadbackV1}=require('./cap07_readback_execution_adapter_v1.cjs');
const {buildFinalClosureDatabaseSourceV1}=require('./database_source_adapter_v1.cjs');
const {producePerRunWitnessBundleV1}=require('./witness_execution_adapter_v1.cjs');
const {validateHarnessPortsV1}=require('./port_contract_v1.cjs');
async function executeSingleRunDatabaseHarnessV1({input,ports,executionAuthority}){validateHarnessPortsV1(ports);const contracts=loadSingleRunHarnessContractsV1();const unboundSpec=buildSingleRunExecutionSpecV1({contracts,...input});assert.equal(executionAuthority?.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED','DATABASE_EXECUTION_AUTHORITY_REQUIRED');assert.equal(executionAuthority.exact_subject_sha,unboundSpec.exact_subject_sha,'EXECUTION_AUTHORITY_SUBJECT');await ports.freshDatabase.assertFreshDisposable({spec:unboundSpec});const materialized=await invokeDirectMaterializerV1(ports.materializer,unboundSpec,executionAuthority);const spec=materialized.bound_spec;const receiptManifest=buildCanonicalReceiptManifestV1(spec,materialized.result.canonical_receipts);const readback=await readExactReceiptObjectsV1(ports.closureReader,spec,receiptManifest);const recovery=await executeRecoveryVectorsV1(ports.recovery,spec,executionAuthority);const cap07=await executeCompleteCap07ReadbackV1(ports.cap07Reader,spec,executionAuthority);assert.equal(cap07.product_read_write_delta,0);const source=buildFinalClosureDatabaseSourceV1({spec,receiptManifest,readback,operationalEvents:materialized.result.operational_events,databaseInstanceDigest:materialized.result.database_instance_digest,artifactRef:materialized.result.artifact_ref,artifactDigest:materialized.result.artifact_digest,selectorSnapshot:materialized.result.selector_snapshot,executionAuthority});const witnesses=producePerRunWitnessBundleV1({spec,source,artifactRef:materialized.result.artifact_ref,artifactDigest:materialized.result.artifact_digest,synthetic:false});assert.equal(witnesses.witness_count,22);assert.ok(witnesses.witnesses.every(w=>w.status==='PASS'&&w.hard_acceptance_eligible===true));const artifact=await ports.artifactWriter.writeBundle({spec,materializer_plan:materialized.plan,materialization:materialized.result,receipt_manifest:receiptManifest,readback,recovery,cap07,source,witness_bundle:witnesses});return{schema_version:'geox_mcft_cap08_s6_single_run_database_harness_result_v2',status:'PASS',exact_subject_sha:spec.exact_subject_sha,run_label:spec.run_label,formal_run_id:spec.formal_run_id,operational_run_instance_id:spec.operational_run_instance_id,lineage_id:spec.lineage_id,revision_id:spec.revision_id,canonical_identity_binding:spec.canonical_identity_binding,database_instance_digest:materialized.result.database_instance_digest,canonical_receipt_count:receiptManifest.receipt_count,recovery_vector_count:recovery.results.length,cap07_surface_count:cap07.surface_definition_count,cap07_request_variant_count:cap07.request_variant_count,per_run_witness_count:witnesses.witness_count,artifact_ref:artifact.artifact_ref,artifact_digest:artifact.artifact_digest,hard_acceptance_eligible:true};}
module.exports={executeSingleRunDatabaseHarnessV1};
