'use strict';
const assert=require('node:assert/strict');
const {loadSingleRunHarnessContractsV1}=require('./contract_loader_v1.cjs');
const {buildSingleRunExecutionSpecV1}=require('./execution_spec_v1.cjs');
const {buildDirectMaterializerPlanV1}=require('./materializer_adapter_v1.cjs');
const {buildCanonicalReceiptManifestV1}=require('./receipt_manifest_v1.cjs');
const {exactReceiptReadSqlV1,readExactReceiptObjectsV1}=require('./closure_readback_adapter_v1.cjs');
const {buildFinalClosureDatabaseSourceV1,rejectIneligibleDatabaseSourceV1}=require('./database_source_adapter_v1.cjs');
const {producePerRunWitnessBundleV1}=require('./witness_execution_adapter_v1.cjs');
const {syntheticReceiptsV1,syntheticSelectorSnapshotV1,fakePoolV1,hash}=require('./synthetic_fixture_v1.cjs');
async function runSyntheticDataAcceptanceV1(subject){const contracts=loadSingleRunHarnessContractsV1({localReplay:true});const spec=buildSingleRunExecutionSpecV1({contracts,runLabel:'RUN_A',operationalRunInstanceId:'synthetic-harness-a-0001',exactSubjectSha:subject});assert.equal(spec.phase_count,28);assert.ok(spec.phases.every(x=>['E','H','A','B','G','C','D','F'].every(p=>x.providers_enabled.includes(p))));const materializer=buildDirectMaterializerPlanV1(spec);assert.equal(materializer.strategy,'DIRECT_PRODUCT_SERVICE_ASSEMBLY');assert.equal(materializer.forbidden_acceptance_promotions.length,3);const receipts=syntheticReceiptsV1(spec),manifest=buildCanonicalReceiptManifestV1(spec,receipts);assert.equal(manifest.receipt_count,153);assert.equal(manifest.oracle_counts.RUNTIME_TICK,24);assert.equal(manifest.oracle_counts.FORECAST_RESIDUAL,24);assert.equal(manifest.oracle_counts.MODEL_ACTIVATION,0);const pool=fakePoolV1(receipts),readback=await readExactReceiptObjectsV1(pool,spec,manifest);assert.equal(pool.calls,1);assert.equal(/count\s*\(/i.test(exactReceiptReadSqlV1()),false);const source=buildFinalClosureDatabaseSourceV1({spec,receiptManifest:manifest,readback,operationalEvents:[{phase_id:'B00',event_ref:'event-1'}],databaseInstanceDigest:hash('db'),artifactRef:'synthetic://artifact',artifactDigest:hash('artifact'),selectorSnapshot:syntheticSelectorSnapshotV1(spec),synthetic:true});assert.equal(source.classification,'SYNTHETIC_CONTRACT_FIXTURE');assert.equal(source.canonical_readback_verified,true);assert.equal(source.hard_acceptance_source_eligible,false);assert.equal(source.slice_acceptance_object_reuse_count,0);assert.equal(source.cross_run_stitching_count,0);const witnesses=producePerRunWitnessBundleV1({spec,source,artifactRef:'synthetic://artifact',artifactDigest:hash('artifact'),synthetic:true});assert.equal(witnesses.witness_count,22);assert.equal(witnesses.object_set_count,22);assert.equal(witnesses.hard_acceptance_eligible,false);assert.throws(()=>rejectIneligibleDatabaseSourceV1(source),/FINAL_FORMAL_CLOSURE_SOURCE_V1/);return{spec,receipts,canonical_receipt_count:manifest.receipt_count,exact_ref_query_count:pool.calls,per_run_witness_count:witnesses.witness_count,proof_object_set_count:witnesses.object_set_count};}
module.exports={runSyntheticDataAcceptanceV1};
