'use strict';
const assert=require('node:assert/strict');
const {loadSingleRunHarnessContractsV1}=require('./contract_loader_v1.cjs');
const {buildSingleRunExecutionSpecV1}=require('./execution_spec_v1.cjs');
const {buildDirectMaterializerPlanV1,bindMaterializedCanonicalIdentityV1}=require('./materializer_adapter_v1.cjs');
const {buildCanonicalReceiptManifestV1}=require('./receipt_manifest_v1.cjs');
const {exactReceiptReadSqlV1,readExactReceiptObjectsV1}=require('./closure_readback_adapter_v1.cjs');
const {buildFinalClosureDatabaseSourceV1,rejectIneligibleDatabaseSourceV1}=require('./database_source_adapter_v1.cjs');
const {producePerRunWitnessBundleV1}=require('./witness_execution_adapter_v1.cjs');
const {bindSyntheticProductIdentityV1,syntheticReceiptsV1,syntheticSelectorSnapshotV1,fakePoolV1,hash}=require('./synthetic_fixture_v1.cjs');
async function runSyntheticDataAcceptanceV1(subject){const contracts=loadSingleRunHarnessContractsV1({localReplay:true});const unbound=buildSingleRunExecutionSpecV1({contracts,runLabel:'RUN_A',operationalRunInstanceId:'synthetic-harness-a-0001',exactSubjectSha:subject});assert.equal(unbound.phase_count,28);assert.equal(unbound.lineage_id,null);assert.equal(unbound.revision_id,null);assert.equal(unbound.canonical_identity_binding,'MATERIALIZER_BOUND_PRODUCT_A0_IDENTITY');const expected=bindSyntheticProductIdentityV1(unbound);const selectorSnapshot=syntheticSelectorSnapshotV1(expected);const receipts=syntheticReceiptsV1(expected,selectorSnapshot);const materialization={lineage_id:expected.lineage_id,revision_id:expected.revision_id,canonical_receipts:receipts};const spec=bindMaterializedCanonicalIdentityV1(unbound,materialization);assert.deepEqual(spec,expected);assert.ok(spec.phases.every(x=>['E','H','A','B','G','C','D','F'].every(p=>x.providers_enabled.includes(p))));const materializer=buildDirectMaterializerPlanV1(unbound);assert.equal(materializer.strategy,'DIRECT_PRODUCT_SERVICE_ASSEMBLY');assert.equal(materializer.canonical_identity_binding,'MATERIALIZER_BOUND_PRODUCT_A0_IDENTITY');const manifest=buildCanonicalReceiptManifestV1(spec,receipts);assert.equal(manifest.receipt_count,153);assert.equal(manifest.oracle_counts.RUNTIME_TICK,24);assert.equal(manifest.oracle_counts.FORECAST_RESIDUAL,24);assert.equal(manifest.oracle_counts.MODEL_ACTIVATION,0);const pool=fakePoolV1(receipts),readback=await readExactReceiptObjectsV1(pool,spec,manifest);assert.equal(pool.calls,1);assert.equal(/count\s*\(/i.test(exactReceiptReadSqlV1()),false);const source=buildFinalClosureDatabaseSourceV1({spec,receiptManifest:manifest,readback,operationalEvents:[{phase_id:'B00',event_ref:'event-1'}],databaseInstanceDigest:hash('db'),artifactRef:'synthetic://artifact',artifactDigest:hash('artifact'),selectorSnapshot,synthetic:true});assert.equal(source.classification,'SYNTHETIC_CONTRACT_FIXTURE');assert.equal(source.canonical_readback_verified,true);assert.equal(source.hard_acceptance_source_eligible,false);const witnesses=producePerRunWitnessBundleV1({spec,source,artifactRef:'synthetic://artifact',artifactDigest:hash('artifact'),synthetic:true});assert.equal(witnesses.witness_count,22);assert.equal(witnesses.object_set_count,22);assert.equal(witnesses.hard_acceptance_eligible,false);assert.throws(()=>rejectIneligibleDatabaseSourceV1(source),/FINAL_FORMAL_CLOSURE_SOURCE_V1/);return{spec,receipts,unbound_lineage_id:unbound.lineage_id,unbound_revision_id:unbound.revision_id,bound_lineage_id:spec.lineage_id,bound_revision_id:spec.revision_id,canonical_identity_binding:spec.canonical_identity_binding,canonical_receipt_count:manifest.receipt_count,exact_ref_query_count:pool.calls,per_run_witness_count:witnesses.witness_count,proof_object_set_count:witnesses.object_set_count};}
module.exports={runSyntheticDataAcceptanceV1};
