#!/usr/bin/env node
const assert=require('assert'); const { Client }=require('pg');
const base=process.env.BASE_URL||process.env.THREE_SURFACE_BASE_URL||'http://127.0.0.1:3001'; const token=process.env.GEOX_EXECUTOR_ACCEPTANCE_TOKEN||process.env.GEOX_ACCEPTANCE_TOKEN||''; const approver=process.env.GEOX_APPROVER_ONLY_TOKEN||''; const clientTok=process.env.GEOX_CLIENT_TOKEN||'';
const scope={tenant_id:process.env.GEOX_TENANT_ID||'tenantA',project_id:process.env.GEOX_PROJECT_ID||'projectA',group_id:process.env.GEOX_GROUP_ID||'groupA'}; const field_id=process.env.THREE_SURFACE_FIELD_ID||'field_demo_001'; const prefix='h43_evidence_artifact_from_as_executed_acceptance_'; const ts=Date.now();
async function post(tok, body){ const res=await fetch(`${base}/api/v1/evidence-artifacts/from-as-executed`,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${tok}`},body:JSON.stringify(body)}); let json=null; try{json=await res.json()}catch{} return {status:res.status,json}; }
function body(extra={}){return {...scope, field_id, zone_id:'zoneA', as_executed_id:`${prefix}asexec_${ts}${extra.suffix||''}`, task_id:`${prefix}task_${ts}${extra.suffix||''}`, receipt_id:`${prefix}receipt_${ts}${extra.suffix||''}`, operation_plan_id:`${prefix}op_${ts}${extra.suffix||''}`, operator_id:`${prefix}operator`, idempotency_key:`${prefix}idem_${ts}${extra.suffix||''}`, materialization_reason:'materialize execution evidence pointers', ...extra};}
async function seed(db,b, refs={}){await db.query(`INSERT INTO as_executed_record_v1 (as_executed_id,tenant_id,project_id,group_id,field_id,task_id,receipt_id,prescription_id,planned,executed,evidence_refs,receipt_refs,log_refs) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9::jsonb,'{}'::jsonb,$10::jsonb,$11::jsonb,$12::jsonb)`,[b.as_executed_id,b.tenant_id,b.project_id,b.group_id,b.field_id,b.task_id,b.receipt_id,b.operation_plan_id,JSON.stringify({operation_plan_id:b.operation_plan_id}),JSON.stringify(refs.evidence_refs??[{kind:'image',ref:`s3://formal/${prefix}${ts}.jpg`}]),JSON.stringify(refs.receipt_refs??[{kind:'receipt',ref:`fact://${b.receipt_id}`}]),JSON.stringify(refs.log_refs??[{kind:'log',ref:`log://${prefix}${ts}`}])]);}
(async()=>{const db=new Client({connectionString:process.env.DATABASE_URL}); await db.connect(); try{
  const b=body(); await seed(db,b); const before=Number((await db.query(`SELECT count(*) c FROM facts WHERE record_json::jsonb->>'type'='evidence_artifact_v1' AND record_json::text LIKE $1`,[`%${prefix}%`])).rows[0].c);
  const res=await post(token,b); assert.equal(res.status,200,JSON.stringify(res)); assert.equal(res.json.status,'EVIDENCE_ARTIFACTS_RECORDED'); assert.equal(res.json.acceptance_created,false); assert.equal(res.json.roi_created,false); assert.equal(res.json.field_memory_created,false);
  const arts=(await db.query(`SELECT record_json::jsonb AS r FROM facts WHERE record_json::jsonb->>'type'='evidence_artifact_v1' AND record_json::text LIKE $1`,[`%${prefix}%`])).rows.map(x=>x.r.payload); assert(arts.length-before>=3,'at least three artifacts created'); assert(arts.some(a=>a.summary.pointer_source==='evidence_ref')); assert(arts.some(a=>a.summary.pointer_source==='receipt_ref')); assert(arts.some(a=>a.summary.pointer_source==='log_ref')); for(const a of arts){assert.equal(a.source,'AS_EXECUTED_RECORD_V1'); assert.equal(a.source_lane,'FORMAL_OPERATION'); assert.equal(a.formal_eligible,true); assert.equal(a.evidence_level,'FORMAL'); for(const k of ['success','failure','effectiveness','yield','profit']) assert(!(k in a),`artifact contains ${k}`);}
  const subs=await db.query(`SELECT count(*) c FROM facts WHERE record_json::jsonb->>'type'='operator_as_executed_evidence_artifact_submission_v1' AND record_json::text LIKE $1`,[`%${prefix}%`]); assert(Number(subs.rows[0].c)>=1,'submission fact created');
  const dup=await post(token,b); assert.equal(dup.json.status,'REJECTED_DUPLICATE'); const afterDup=Number((await db.query(`SELECT count(*) c FROM facts WHERE record_json::jsonb->>'type'='evidence_artifact_v1' AND record_json::text LIKE $1`,[`%${prefix}%`])).rows[0].c); assert.equal(afterDup,arts.length,'duplicate creates no artifacts');
  const missing=await post(token,body({suffix:'missing'})); assert.equal(missing.json.status,'REJECTED_AS_EXECUTED_NOT_FOUND'); const sm=body({suffix:'scope'}); await seed(db,sm); const scopeResp=await post(token,{...sm, field_id:'wrong_field'}); assert.equal(scopeResp.json.status,'REJECTED_SCOPE_MISMATCH'); const none=body({suffix:'none'}); await seed(db,none,{evidence_refs:[],receipt_refs:[],log_refs:[]}); assert.equal((await post(token,none)).json.status,'REJECTED_NO_EVIDENCE_POINTERS'); const dev=body({suffix:'dev'}); await seed(db,dev,{evidence_refs:[{kind:'image',ref:'dev://flight-table/demo'}],receipt_refs:[],log_refs:[]}); assert.equal((await post(token,dev)).json.status,'REJECTED_DEV_EVIDENCE_NOT_FORMAL'); if(approver) assert([401,403].includes((await post(approver,body({suffix:'approver'}))).status)); if(clientTok) assert([401,403].includes((await post(clientTok,body({suffix:'client'}))).status));
  for(const t of ['acceptance_result_v1','water_response_verification_v1','roi_ledger_v1','field_memory_v1']) assert.equal(Number((await db.query(`SELECT count(*) c FROM facts WHERE record_json::jsonb->>'type'=$1 AND record_json::text LIKE $2`,[t,`%${prefix}%`])).rows[0].c),0,`no ${t}`);
  console.log(JSON.stringify({ok:true, status:res.json.status, artifacts:arts.length},null,2));
} finally { await db.query(`DELETE FROM facts WHERE record_json::text LIKE $1 OR fact_id LIKE $2`,[`%${prefix}%`,`${prefix}%`]); await db.query(`DELETE FROM as_applied_map_v1 WHERE as_applied_id LIKE $1 OR task_id LIKE $1 OR receipt_id LIKE $1`,[`${prefix}%`]); await db.query(`DELETE FROM as_executed_record_v1 WHERE as_executed_id LIKE $1 OR task_id LIKE $1 OR receipt_id LIKE $1`,[`${prefix}%`]); await db.end(); }} )().catch(e=>{console.error(e);process.exit(1)});
