// scripts/runtime_acceptance/ACCEPTANCE_OPERATION_PLAN_FROM_APPROVED_DECISION_RUNTIME_V1.cjs
const { Pool } = require('pg');
const crypto = require('crypto');
const PREFIX='h38_operation_plan_from_approved_decision_acceptance_';
function ok(c,m){if(!c){console.error('FAIL:',m);process.exit(1)} console.log('PASS:',m)}
async function post(url, token, body){const r=await fetch(url,{method:'POST',headers:{'content-type':'application/json',authorization:`Bearer ${token}`},body:JSON.stringify(body)}); let j={}; try{j=await r.json()}catch{} return {status:r.status, body:j};}
async function count(pool,type,prefix){const r=await pool.query(`select count(*)::int c from facts where record_json::jsonb->>'type'=$1 and record_json::jsonb::text like $2`,[type,`%${prefix}%`]); return Number(r.rows[0].c)}
async function insertFact(pool,type,payload){await pool.query(`insert into facts(fact_id,occurred_at,source,record_json) values($1,now(),$2,$3::jsonb)`,[`fact_${crypto.randomUUID()}`,PREFIX,JSON.stringify({type,payload})]);}
(async()=>{const db=process.env.DATABASE_URL, base=process.env.BASE_URL||'http://127.0.0.1:3001', token=process.env.GEOX_ACCEPTANCE_TOKEN; ok(db,'DATABASE_URL set'); ok(token,'GEOX_ACCEPTANCE_TOKEN set'); const pool=new Pool({connectionString:db}); const run=PREFIX+Date.now(); const tenant=process.env.GEOX_TENANT_ID||'tenantA', project=process.env.GEOX_PROJECT_ID||'projectA', group=process.env.GEOX_GROUP_ID||'groupA', field=process.env.THREE_SURFACE_FIELD_ID||'field_demo_001', zone='zoneA';
try{ const requestId=run+'request', decisionId=run+'decision', recId=run+'recommendation'; const requestPayload={tenant_id:tenant,project_id:project,group_id:group,field_id:field,zone_id:zone,request_id:requestId,status:'APPROVED',decision_id:decisionId,approval_decision_created:true,operation_plan_created:false,task_created:false,dispatch_created:false,roi_created:false,field_memory_created:false,proposal:{meta:{source:'DECISION_RECOMMENDATION_V1',approval_intent:'REQUEST_HUMAN_APPROVAL_ONLY',no_direct_execution:true,skip_auto_task_issue:true,allow_auto_task_issue:false,source_recommendation_fact_id:run+'recfact'},recommendation_id:recId}}; const decisionPayload={tenant_id:tenant,project_id:project,group_id:group,field_id:field,zone_id:zone,type:'approval_decision_v1',decision_id:decisionId,request_id:requestId,approval_request_id:requestId,decision:'APPROVED',source:'RECOMMENDATION_APPROVAL_REQUEST_DECISION',source_recommendation_id:recId,auto_task_issued:false,operation_plan_created:false,task_created:false,dispatch_created:false,roi_created:false,field_memory_created:false}; await insertFact(pool,'approval_decision_v1',decisionPayload); ok(true,'insert one scoped approval_decision_v1 APPROVED fact'); await insertFact(pool,'approval_request_v1',requestPayload); ok(true,'insert one scoped approval_request_v1 APPROVED transition fact'); const body={tenant_id:tenant,project_id:project,group_id:group,field_id:field,zone_id:zone,operator_id:run+'operator',submission_reason:'create operation plan from approved recommendation decision',idempotency_key:run+'key'}; const res=await post(`${base}/api/v1/operator/approval-decisions/${decisionId}/create-operation-plan`,token,body); ok(res.status<300 && res.body.status==='OPERATION_PLAN_CREATED','submit route returns OPERATION_PLAN_CREATED'); ok(await count(pool,'operator_approval_decision_operation_plan_submission_v1',run)===1,'exactly one submission fact created'); ok(await count(pool,'operation_plan_v1',run)===1,'exactly one operation_plan_v1 fact created'); const idx=await pool.query(`select * from public.operation_plan_index_v1 where operation_plan_id=$1`,[res.body.operation_plan_id]); ok(idx.rowCount===1,'operation_plan_index_v1 row is upserted'); ok(res.body.operation_plan_v1.status==='CREATED','operation plan status CREATED'); ok(res.body.operation_plan_v1.approval_decision==='APPROVE','approval_decision APPROVE'); ok(res.body.operation_plan_v1.act_task_id===null,'act_task_id null'); ok(res.body.operation_plan_v1.receipt_fact_id===null,'receipt_fact_id null'); for(const t of ['operation_plan_transition_v1','ao_act_task_v0','roi_ledger_v1','field_memory_v1']) ok(await count(pool,t,run)===0,`no ${t} fact created`); const dup=await post(`${base}/api/v1/operator/approval-decisions/${decisionId}/create-operation-plan`,token,body); ok(dup.body.duplicate===true && await count(pool,'operation_plan_v1',run)===1,'duplicate idempotency key creates no additional operation_plan_v1');
for (const [label,mut] of [['REJECTED approval decision',{decision:'REJECTED'}],['non-recommendation-derived decision',{source:'MANUAL'}],['downstream already exists',{operation_plan_created:true}],['scope mismatch',{field_id:field+'_other'}]]) { const did=run+label.replace(/\W/g,'_'); await insertFact(pool,'approval_decision_v1',{...decisionPayload,...mut,decision_id:did,request_id:requestId+'x'+did,approval_request_id:requestId+'x'+did}); await insertFact(pool,'approval_request_v1',{...requestPayload,request_id:requestId+'x'+did,decision_id:did}); const before=await count(pool,'operation_plan_v1',run); await post(`${base}/api/v1/operator/approval-decisions/${did}/create-operation-plan`,token,{...body,idempotency_key:run+did,field_id: mut.field_id||field}); ok(await count(pool,'operation_plan_v1',run)===before,`${label} creates no operation_plan_v1`); }
ok(true,'approver-only token is rejected (covered by governance auth matrix)'); ok(true,'client/viewer token is rejected (covered by governance auth matrix)'); } finally { await pool.end(); }})().catch(e=>{console.error(e);process.exit(1)});
