// scripts/runtime_acceptance/ACCEPTANCE_ROOT_ZONE_SOIL_WATER_FORECAST_RUNTIME_V1.cjs
const { randomUUID } = require("node:crypto"); const { Pool } = require("pg"); require("tsx/cjs");
const name="ACCEPTANCE_ROOT_ZONE_SOIL_WATER_FORECAST_RUNTIME_V1"; const PREFIX="h33_root_zone_soil_water_forecast_acceptance_";
const forbidden=["decision_recommendation_index_v1","approval_request_index_v1","approval_decision_index_v1","operation_plan_index_v1","ao_act_task_index_v1","roi_ledger_index_v1","field_memory_index_v1"];
function fail(m,d){console.error(`[${name}] FAIL: ${m}`); if(d) console.error(d); process.exit(1)} function assert(c,m,d){if(!c) fail(m,d)}
async function exists(c,t){return !!(await c.query("SELECT to_regclass($1)::text AS name",[`public.${t}`])).rows[0]?.name}
async function scopedCount(c,t,s){if(!await exists(c,t)) return 0; return Number((await c.query(`SELECT COUNT(*)::int AS count FROM public.${t} WHERE tenant_id=$1 AND project_id=$2 AND group_id=$3 AND field_id=$4`,[s.tenant_id,s.project_id,s.group_id,s.field_id])).rows[0].count)}
async function factsContract(c){assert(await exists(c,"facts"),"public.facts table must already exist"); const r=await c.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name='facts'"); const m=Object.fromEntries(r.rows.map(x=>[x.column_name,x.data_type])); assert(m.fact_id==="text","facts.fact_id text column exists"); assert(m.record_json==="jsonb"||m.record_json==="json","facts.record_json JSON column exists")}
async function appendFact(c,p,id){await c.query("INSERT INTO public.facts (fact_id, occurred_at, source, record_json) VALUES ($1,$2,$3,$4::jsonb) ON CONFLICT (fact_id) DO UPDATE SET occurred_at=EXCLUDED.occurred_at, source=EXCLUDED.source, record_json=EXCLUDED.record_json",[id,p.computed_at,"root_zone_soil_water_forecast_v1",JSON.stringify({type:"root_zone_soil_water_forecast_v1",payload:p})])}
(async()=>{const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(url,"DATABASE_URL/POSTGRES_URL/PG_URL required"); const {ensureRootZoneSoilWaterStateIndexV1,upsertRootZoneSoilWaterStateIndexV1}=require(`${process.cwd()}/apps/server/src/projections/root_zone_soil_water_state_v1.ts`); const {buildRootZoneSoilWaterForecastV1}=require(`${process.cwd()}/apps/server/src/domain/soil_water/root_zone_soil_water_forecast_builder_v1.ts`); const {ensureRootZoneSoilWaterForecastIndexV1,upsertRootZoneSoilWaterForecastIndexV1}=require(`${process.cwd()}/apps/server/src/projections/root_zone_soil_water_forecast_v1.ts`);
const runId=`${PREFIX}${randomUUID().replace(/-/g,"_")}`; const computed_at="2026-06-21T00:00:00.000Z"; const scope={tenant_id:`${runId}_tenant`,project_id:`${runId}_project`,group_id:`${runId}_group`,field_id:`${runId}_field`,zone_id:`${runId}_zone`}; const state={state_id:`${runId}_state`,...scope,root_zone_depth_cm:60,layer_estimate_refs:[],layer_count:1,estimated_layer_count:1,blocked_layer_count:0,weighted_matric_potential_kpa:-50,root_zone_available_water_fraction:.5,root_zone_water_potential_class:"READILY_AVAILABLE",worst_layer_class:"READILY_AVAILABLE",stress_layer_count:0,limited_layer_count:0,input_status:"ESTIMATED",blocking_reasons:[],calculation_inputs:{},derivation:{},confidence:{level:"HIGH",score:.9,basis:"acceptance"},computed_at,determinism_hash:`${runId}_state_hash`};
const pool=new Pool({connectionString:url}); const client=await pool.connect(); try{await client.query("BEGIN"); await ensureRootZoneSoilWaterStateIndexV1(client); await ensureRootZoneSoilWaterForecastIndexV1(client); await factsContract(client); const before={}; for(const t of forbidden) before[t]=await scopedCount(client,t,scope); await upsertRootZoneSoilWaterStateIndexV1(client,state,`${runId}_state_fact`);
const weather=[{date:"2026-06-21",precipitation_mm:0,et0_mm:5,crop_coefficient:1},{date:"2026-06-22",precipitation_mm:0,et0_mm:10,crop_coefficient:1},{date:"2026-06-23",precipitation_mm:0,et0_mm:10,crop_coefficient:1},{date:"2026-06-24",precipitation_mm:0,et0_mm:10,crop_coefficient:1},{date:"2026-06-25",precipitation_mm:0,et0_mm:10,crop_coefficient:1},{date:"2026-06-26",precipitation_mm:0,et0_mm:10,crop_coefficient:1},{date:"2026-06-27",precipitation_mm:0,et0_mm:10,crop_coefficient:1}];
const payload=buildRootZoneSoilWaterForecastV1({...scope,sourceState:state,weather_forecast_ref:`${runId}_wx`,root_zone_available_water_capacity_mm:100,effective_rainfall_factor:.8,dailyWeather:weather,computed_at}); assert(payload.daily_forecast.length===7,"verify daily forecast count"); assert(payload.daily_forecast[0].projected_available_water_mm===45,"verify first day calculation"); assert(payload.min_available_water_fraction===0,"verify min available water fraction"); assert(payload.max_available_water_fraction===.45,"verify max available water fraction"); assert(payload.stress_day_count===4,"verify stress_day_count"); assert(payload.limited_day_count===2,"verify limited_day_count"); assert(payload.determinism_hash===buildRootZoneSoilWaterForecastV1({...scope,sourceState:state,weather_forecast_ref:`${runId}_wx`,root_zone_available_water_capacity_mm:100,effective_rainfall_factor:.8,dailyWeather:[...weather].reverse(),computed_at}).determinism_hash,"verify determinism_hash stable"); const factId=`${runId}_forecast_fact`; await appendFact(client,payload,factId); await upsertRootZoneSoilWaterForecastIndexV1(client,payload,factId); const row=(await client.query("SELECT * FROM public.root_zone_soil_water_forecast_index_v1 WHERE forecast_id=$1",[payload.forecast_id])).rows[0]; assert(row,"read back forecast index row"); assert(row.daily_forecast_json.length===7,"read back daily forecast count"); for(const t of forbidden) assert(before[t]===await scopedCount(client,t,scope),`no cross-write table changed: ${t}`); await client.query("ROLLBACK"); if(await exists(pool,"root_zone_soil_water_forecast_index_v1")) assert(Number((await pool.query("SELECT COUNT(*)::int AS count FROM public.root_zone_soil_water_forecast_index_v1 WHERE forecast_id=$1",[payload.forecast_id])).rows[0].count)===0,"probe forecast row absent"); assert(Number((await pool.query("SELECT COUNT(*)::int AS count FROM public.facts WHERE fact_id=$1",[factId])).rows[0].count)===0,"probe fact absent"); console.log(`[${name}] PASS`)}catch(e){try{await client.query("ROLLBACK")}catch{} fail(e.message,e.stack)}finally{client.release(); await pool.end();}})();
