// scripts/runtime_acceptance/ACCEPTANCE_ROOT_ZONE_SOIL_WATER_STATE_RUNTIME_V1.cjs
const { randomUUID }=require("node:crypto"); const {Pool}=require("pg"); require("tsx/cjs");
const name="ACCEPTANCE_ROOT_ZONE_SOIL_WATER_STATE_RUNTIME_V1"; const PREFIX="h32_root_zone_soil_water_state_acceptance_";
const forbidden=["decision_recommendation_index_v1","approval_request_index_v1","approval_decision_index_v1","operation_plan_index_v1","ao_act_task_index_v1","roi_ledger_index_v1","field_memory_index_v1"];
function fail(m,d){console.error(`[${name}] FAIL: ${m}`); if(d) console.error(d); process.exit(1)} function assert(c,m,d){if(!c) fail(m,d)}
async function exists(c,t){return Boolean((await c.query("SELECT to_regclass($1)::text name",[`public.${t}`])).rows[0].name)}
async function count(c,t,scope){ if(!(await exists(c,t))) return 0; const r=await c.query(`SELECT COUNT(*)::int count FROM public.${t} WHERE tenant_id=$1 AND project_id=$2 AND group_id=$3 AND field_id=$4`,[scope.tenant_id,scope.project_id,scope.group_id,scope.field_id]); return r.rows[0].count; }
async function facts(c){ await c.query(`CREATE TABLE IF NOT EXISTS public.facts (fact_id text PRIMARY KEY, occurred_at timestamptz NOT NULL DEFAULT now(), source text NOT NULL, record_json jsonb NOT NULL)`)}
(async()=>{ const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(url,"DATABASE_URL/POSTGRES_URL/PG_URL required");
const {ensureSoilWaterPotentialEstimateIndexV1,upsertSoilWaterPotentialEstimateIndexV1}=require(`${process.cwd()}/apps/server/src/projections/soil_water_potential_estimate_v1.ts`);
const {buildRootZoneSoilWaterStateV1}=require(`${process.cwd()}/apps/server/src/domain/soil_water/root_zone_soil_water_state_builder_v1.ts`);
const {ensureRootZoneSoilWaterStateIndexV1,upsertRootZoneSoilWaterStateIndexV1}=require(`${process.cwd()}/apps/server/src/projections/root_zone_soil_water_state_v1.ts`);
const runId=`${PREFIX}${randomUUID().replace(/-/g,"_")}`; const computed_at="2026-06-21T00:00:00.000Z"; const scope={tenant_id:`${runId}_tenant`,project_id:`${runId}_project`,group_id:`${runId}_group`,field_id:`${runId}_field`,zone_id:`${runId}_zone`};
const layer=(n,depth,mp,awf)=>({estimate_id:`${runId}_layer_${n}`, ...scope, layer_depth_cm:depth, source_window_id:null, source_profile_id:null, observed_theta:null, theta_unit:"m3_m3", normalized_theta_m3_m3:null, matric_potential_kpa:mp, matric_potential_class: mp >= -10 ? "SATURATED_OR_NEAR_SATURATED" : mp >= -60 ? "READILY_AVAILABLE" : mp >= -200 ? "LIMITED_AVAILABLE" : "STRESS", available_water_fraction:awf, root_zone_weight:1, input_status:"ESTIMATED", blocking_reasons:[], hydraulic_profile_ref:null, data_quality_ref:null, evidence_refs:[], calculation_inputs:{}, derivation:{}, confidence:{level:"HIGH",score:0.9,basis:"acceptance"}, computed_at, determinism_hash:`${runId}_hash_${n}`});
const pool=new Pool({connectionString:url}); const client=await pool.connect();
try{ await client.query("BEGIN"); await facts(client); await ensureSoilWaterPotentialEstimateIndexV1(client); await ensureRootZoneSoilWaterStateIndexV1(client); const before={}; for(const t of forbidden) before[t]=await count(client,t,scope);
const layers=[layer(20,20,-20,0.8),layer(40,40,-70,0.4),layer(60,60,-100,0.2)]; for(const l of layers) await upsertSoilWaterPotentialEstimateIndexV1(client,l,`${l.estimate_id}_fact`);
const payload=buildRootZoneSoilWaterStateV1({...scope,root_zone_depth_cm:60,layerEstimates:layers,computed_at}); assert(payload.weighted_matric_potential_kpa===-63.333333,"verify weighted result",JSON.stringify(payload)); assert(payload.root_zone_water_potential_class==="LIMITED_AVAILABLE","verify class"); assert(payload.determinism_hash===buildRootZoneSoilWaterStateV1({...scope,root_zone_depth_cm:60,layerEstimates:[layers[2],layers[0],layers[1]],computed_at}).determinism_hash,"verify stable determinism_hash");
const factId=`${runId}_state_fact`; await client.query(`INSERT INTO public.facts (fact_id,occurred_at,source,record_json) VALUES ($1,$2,'root_zone_soil_water_state_v1',$3::jsonb)`,[factId,payload.computed_at,JSON.stringify({type:"root_zone_soil_water_state_v1",payload})]); await upsertRootZoneSoilWaterStateIndexV1(client,payload,factId);
const row=(await client.query("SELECT * FROM public.root_zone_soil_water_state_index_v1 WHERE state_id=$1",[payload.state_id])).rows[0]; assert(row && Number(row.weighted_matric_potential_kpa)===-63.333333,"read back index row"); for(const t of forbidden) assert(before[t]===await count(client,t,scope),`no cross-write table changed: ${t}`);
await client.query("ROLLBACK"); for(const [t,col,val] of [["root_zone_soil_water_state_index_v1","state_id",payload.state_id],["soil_water_potential_estimate_index_v1","tenant_id",scope.tenant_id]]) if(await exists(pool,t)){ const r=await pool.query(`SELECT COUNT(*)::int count FROM public.${t} WHERE ${col}=$1`,[val]); assert(r.rows[0].count===0,`${t} probe rows absent after rollback`)} if(await exists(pool,"facts")){ const r=await pool.query("SELECT COUNT(*)::int count FROM public.facts WHERE fact_id=$1",[factId]); assert(r.rows[0].count===0,"fact probe absent after rollback")}
console.log(`[${name}] PASS`);
}catch(e){try{await client.query("ROLLBACK")}catch{} fail(e.message,e.stack)} finally{client.release(); await pool.end()}})();
