"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),fs=require("node:fs"),path=require("node:path"),os=require("node:os"),cp=require("node:child_process");
const {buildArm,effectivePolicy,verifyOwnerBinding}=require("./MCFT_CAP_09_AM22_START_CHAIN_V2.cjs");
const {LEGACY,canonical,digest}=require("./MCFT_CAP_09_FORMAL_ARM_RETIREMENT_GUARD_V1.cjs");
const {verifyExecutionQualification}=require("./MCFT_CAP_09_AM22_EXECUTION_QUALIFICATION_V2.cjs");
const {preparationCommands,a0Commands,runStep}=require("./RUN_MCFT_CAP_09_AM22_CUTOVER_ARM_A0_V2.cjs");
let cases=0;const check=fn=>{fn();cases++;},hash="sha256:"+"b".repeat(64),subject="a".repeat(40);
const c={subject_sha:subject,epoch_id:"am22_unit_epoch",current_crop_authority_sha256:hash,qualified_envelope_sha256:hash,retirement_receipt_sha256:hash,clock:{database_now_utc:"2026-10-08T05:30:00.000Z",a0:"2026-10-08T06:00:00.000Z",o00:"2026-10-08T07:00:00.000Z",o23:"2026-10-09T06:00:00.000Z"}};
const store={transaction_read_only:true,formal_database_name:LEGACY.database,all_table_rows_zero:true,public_base_table_count:29,public_routine_count:2};
const h5={status:"PASS",deployment_subject_sha:subject,formal_v5_arm_ready:true,exact_one_live_fenced_owner_per_runtime_role_reverified:true};
const handoff={schema_version:"geox_mcft_cap09_formal_v5_evidence_runtime_handoff_authority_v2",deployment_subject_sha:subject,activation_fence_time:"2026-10-08T05:30:00.000Z",formal_a0_logical_time:c.clock.a0,formal_o00_logical_time:c.clock.o00,formal_o23_logical_time:c.clock.o23};
check(()=>{const arm=buildArm(c,store,handoff,h5,"2026-10-08T05:35:00.000Z");const {arm_identity_hash,...body}=arm;assert.equal(arm_identity_hash,digest(body));assert.equal(arm.arm_issuer,"AM22_V2");assert.equal(arm.fixed_36_hour_lead_used,false);assert.equal(arm.readiness_deadline,arm.a0);});
for(const bad of [{...h5,status:"FAIL"},{...h5,deployment_subject_sha:"f".repeat(40)},{...h5,exact_one_live_fenced_owner_per_runtime_role_reverified:false}])check(()=>assert.throws(()=>buildArm(c,store,handoff,bad,"2026-10-08T05:35:00.000Z"),/FRESH_H5_REQUIRED/));
for(const bad of [{...handoff,schema_version:"geox_mcft_cap09_formal_v5_evidence_runtime_handoff_authority_v1"},{...handoff,formal_a0_logical_time:"2026-10-10T05:00:00.000Z"}])check(()=>assert.throws(()=>buildArm(c,store,bad,h5,"2026-10-08T05:35:00.000Z"),/V2_HANDOFF_CLOCK_MISMATCH/));
for(const bad of [{...store,all_table_rows_zero:false},{...store,transaction_read_only:false},{...store,public_base_table_count:28}])check(()=>assert.throws(()=>buildArm(c,bad,handoff,h5,"2026-10-08T05:35:00.000Z"),/FRESH_PRISTINE_STORE_REQUIRED/));
for(const now of ["2026-10-08T05:20:00.000Z","2026-10-08T06:00:00.000Z"])check(()=>assert.throws(()=>buildArm(c,store,handoff,h5,now),/SAME_UTC_HOUR_CUTOVER_ARM_REQUIRED/));
const pair=crypto.generateKeyPairSync("ed25519"),other=crypto.generateKeyPairSync("ed25519");
const root={execution_qualification_rule:"DETACHED_ED25519_EXACT_MAIN_HOST_IMAGE_EVIDENCE_V2",execution_qualification_signing_public_key_pem:pair.publicKey.export({type:"spki",format:"pem"}),production_start_authorized:false};
const body={schema_version:"geox_mcft_cap09_am22_detached_execution_qualification_v2",status:"PASS",synthetic:false,issued_at_database_utc:"2026-10-08T05:00:00.000Z",expires_at_database_utc:"2026-10-09T05:00:00.000Z",complete_pre_a0_measurement_qualified:true,new_handoff_arm_a0_chain_qualified:true,qualified_subject_sha:subject,qualified_host_id:LEGACY.host,qualified_image_id:hash,qualified_envelope_sha256:hash,approved_current_crop_authority_sha256:hash,production_start_authorized:true};
const cert={...body,signature_base64:crypto.sign(null,Buffer.from(canonical(body)),pair.privateKey).toString("base64")};
check(()=>assert.equal(verifyExecutionQualification(root,cert,"2026-10-08T05:30:00.000Z").production_start_authorized,false));
for(const bad of [{...cert,qualified_subject_sha:"f".repeat(40)},{...cert,signature_base64:""}])check(()=>assert.throws(()=>verifyExecutionQualification(root,bad,"2026-10-08T05:30:00.000Z"),/SIGNATURE_INVALID/));
check(()=>assert.throws(()=>verifyExecutionQualification({...root,execution_qualification_signing_public_key_pem:other.publicKey.export({type:"spki",format:"pem"})},cert,"2026-10-08T05:30:00.000Z"),/SIGNATURE_INVALID/));
for(const now of ["2026-10-08T04:59:59.000Z","2026-10-09T05:00:00.000Z"])check(()=>assert.throws(()=>verifyExecutionQualification(root,cert,now),/CERTIFICATE_FUTURE_OR_EXPIRED/));
check(()=>assert.throws(()=>verifyExecutionQualification({...root,execution_qualification_signing_public_key_pem:null},cert,"2026-10-08T05:30:00.000Z"),/GOVERNED_PUBLIC_KEY_REQUIRED/));
check(()=>assert.throws(()=>effectivePolicy(),/EFFECTIVE_PRODUCTION_QUALIFICATION_REQUIRED/));
const binding={subject_sha:subject,host_id:LEGACY.host,image_id:hash};
const t={status:"PASS",container_running:true,container_image_id:hash,expected_host_id:LEGACY.host};
const role={t1:t,t2:t,renewal:{status:"PASS",same_effective_owner:true,same_container_instance:true,same_image_id:true}};
const owner={status:"PASS",subject_main_sha:subject,actual_host_id:LEGACY.host,authorized_image_id:hash,blockers:[],evidence_runtime:role,twin_runtime_scheduler:role};
check(()=>assert.equal(verifyOwnerBinding(owner,binding),owner));
check(()=>assert.throws(()=>verifyOwnerBinding({...owner,authorized_image_id:"sha256:"+"f".repeat(64)},binding),/LIVE_OWNER_EXECUTION_BINDING_MISMATCH/));
check(()=>assert.throws(()=>verifyOwnerBinding({...owner,evidence_runtime:{...role,renewal:{...role.renewal,same_effective_owner:false}}},binding),/LIVE_OWNER_RENEWAL_REQUIRED/));
check(()=>assert.deepEqual(preparationCommands("input","rearm","out").map(x=>path.basename(x.file)),["RUN_MCFT_CAP_09_PRODUCTION_RUNTIME_OWNER_CUTOVER_V2.cjs","ASSEMBLE_MCFT_CAP_09_FORMAL_V5_ARM_V2.cjs","RUN_MCFT_CAP_09_FORMAL_V5_SCHEMA_ACL_MATERIALIZATION_V1.ts"]));
check(()=>assert.deepEqual(a0Commands("out").map(x=>path.basename(x.file)),["RUN_MCFT_CAP_09_FORMAL_V5_A0_PRODUCTION_REPLAY_PROMOTION_V2.cjs","RUN_MCFT_CAP_09_FORMAL_V5_A0_BOOTSTRAP_V2.cjs"]));
check(()=>{const source=fs.readFileSync(path.join(__dirname,"RUN_MCFT_CAP_09_PRODUCTION_RUNTIME_OWNER_CUTOVER_V2.cjs"),"utf8");assert.ok(!source.includes('"build","geox-mcft-cap09-evidence-runtime-v1"'));assert.ok(!source.includes('"down"'));assert.match(source,/"--pull","never"/);});
for(const file of ["RUN_MCFT_CAP_09_PRODUCTION_RUNTIME_OWNER_CUTOVER_V2.cjs","ASSEMBLE_MCFT_CAP_09_FORMAL_V5_ARM_V2.cjs","RUN_MCFT_CAP_09_AM22_CUTOVER_ARM_A0_V2.cjs","RUN_MCFT_CAP_09_AM22_EVIDENCE_OWNER_ENTRY_V2.cjs"]){check(()=>{const result=cp.spawnSync(process.execPath,[path.join(__dirname,file)],{encoding:"utf8"});assert.notEqual(result.status,0);assert.match(result.stderr,/EFFECTIVE_PRODUCTION_QUALIFICATION_REQUIRED/);});}
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),"am22-chain-unit-"));
try{fs.writeFileSync(path.join(tmp,"unit.started.json"),"{}");check(()=>assert.throws(()=>runStep({file:path.join(tmp,"unit.cjs"),args:[]},tmp,100),/PARTIAL_OR_PRIOR_OPERATION/));}finally{fs.rmSync(tmp,{recursive:true,force:true});}
const gov=require("../governance_acceptance/VERIFY_MCFT_CAP_09_AM22_START_CHAIN_ENGINEERING_ONLY_V2.cjs");
const after=JSON.parse(fs.readFileSync(path.join(__dirname,"../../",gov.QCP),"utf8"));
const before=structuredClone(after);before.checks.pop();delete before.dependency_resolvers.AM22_START_CHAIN_ENGINEERING_ONLY_V2;
const p=JSON.parse(fs.readFileSync(path.join(__dirname,"../../",gov.POLICY),"utf8"));
const mutable=[gov.QCP,gov.PRIOR,gov.RETIRE,gov.BOUNDARY],changes=gov.PATHS.map(rel=>({rel,status:mutable.includes(rel)?"M":"A"}));
check(()=>gov.validateBoundary(changes,p,before,after));
check(()=>assert.throws(()=>gov.validateBoundary([...changes,{rel:"unknown/provider.ts",status:"A"}],p,before,after),/UNKNOWN_PATH/));
check(()=>assert.throws(()=>gov.validateBoundary([...changes,{rel:gov.POLICY,status:"M"}],p,before,after),/UNKNOWN_PATH/));
check(()=>assert.throws(()=>gov.validateBoundary(changes,{...p,production_start_authorized:true},before,after),/AUTHORITY_ESCALATION/));
check(()=>{const altered=structuredClone(after);altered.checks[0].owner="changed";assert.throws(()=>gov.validateBoundary(changes,p,before,altered),/PREDECESSOR_QCP_CHANGED/);});
check(()=>{const altered=structuredClone(after);altered.dependency_resolvers.AM22_START_CHAIN_ENGINEERING_ONLY_V2.paths.push("unknown.ts");assert.throws(()=>gov.validateBoundary(changes,p,before,altered),/RESOLVER_CHANGED/);});
console.log(JSON.stringify({status:"PASS",cases,unit_fixtures_only:true,real_host_cutover:false,real_host_full_preparation_measurement:false,production_database_write_count:0,service_stop_count:0,a0_execution:false}));
