import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";

import { PostgresPfe14Mcft09OperationalReadApiV1 } from "../../apps/server/src/services/pfe14_mcft09_operational_read_api_v1.js";
import type { McftFieldTwinReadApiV1 } from "../../apps/server/src/services/mcft_field_twin_read_api_v1.js";
import type { CanonicalReplayEvidenceRecordV1, NextTickReadPortV1, PersistedNextTickSnapshotV1, TwinScopeKeyV1 } from "../../apps/server/src/runtime/twin_runtime/ports.js";

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../..");
const OUT=path.join(ROOT,"acceptance-output/PFE14_CLASS_B_NARROW_PROVIDER_DB_RESULT.json");
const SOURCE="pfe14_class_b_narrow_provider_acceptance";
const scope:TwinScopeKeyV1={tenant_id:"tenantA",project_id:"projectA",group_id:"groupA",field_id:"fieldA",season_id:"seasonA",zone_id:"zoneA"};
type RT="soil_moisture_observation_v1"|"observed_rainfall_v1"|"historical_et0_estimate_v1";
const sha=(value:unknown)=>`sha256:${crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex")}`;
const eventField=(type:RT)=>type==="soil_moisture_observation_v1"?"observed_at":"interval_end";
function evidence(id:string,type:RT,event:string,options:{ingested?:string;available?:string;origin?:string}={}):CanonicalReplayEvidenceRecordV1 { const ingested=options.ingested??event; return {...scope,dataset_id:"pfe14_class_b_narrow_provider_v1",source_record_id:id,source_record_hash:sha({id,type,event}),record_type:type,binding_id:`binding:${type}`,origin_source_kind:"CONTROLLED_DATABASE_EVIDENCE",origin_source_id:options.origin??`source:${type}`,epistemic_class:type==="historical_et0_estimate_v1"?"ESTIMATED":"OBSERVED",available_to_runtime_at:options.available??ingested,role_time:{[eventField(type)]:event,ingested_at:ingested},quality:{status:"PASS"},source_payload:{acceptance:true},canonical_payload:{value:1,record_type:type},source_unit:"unitless",canonical_unit:"unitless",conversion_rule:{rule_id:"IDENTITY_V1"},limitations:[]} as CanonicalReplayEvidenceRecordV1; }
async function insertEvidence(pool:Pool,factId:string,record:CanonicalReplayEvidenceRecordV1){await pool.query(`INSERT INTO facts(fact_id,occurred_at,source,record_json) VALUES($1,$2::timestamptz,$3,$4::jsonb)`,[factId,record.available_to_runtime_at,SOURCE,JSON.stringify({type:record.record_type,payload:record})]);}
async function reset(pool:Pool){await pool.query("DROP SCHEMA public CASCADE");await pool.query("CREATE SCHEMA public");await pool.query(fs.readFileSync(path.join(ROOT,"docker/postgres/init/001_schema.sql"),"utf8"));await pool.query(fs.readFileSync(path.join(ROOT,"apps/server/db/migrations/2026_08_06_mcft_cap_09_s3_persistent_sequential_scheduler.sql"),"utf8"));}
async function seed(pool:Pool){
  await pool.query(`INSERT INTO twin_shadow_online_scheduler_cursor_v1 (tenant_id,project_id,group_id,field_id,season_id,zone_id,schedule_start_logical_time,next_slot_index,next_slot_id,next_logical_time,last_terminal_slot_id,last_terminal_logical_time,last_fencing_token) VALUES ($1,$2,$3,$4,$5,$6,'2026-08-05T00:00:00.000Z',11,'O11','2026-08-05T11:00:00.000Z','O10','2026-08-05T10:00:00.000Z',11)`,Object.values(scope));
  for(let i=0;i<=10;i++){const id=`O${String(i).padStart(2,"0")}`;const time=`2026-08-05T${String(i).padStart(2,"0")}:00:00.000Z`;const state=i===10?"DEGRADED":"COMPLETED";await pool.query(`INSERT INTO twin_shadow_online_scheduler_slot_v1 (tenant_id,project_id,group_id,field_id,season_id,zone_id,slot_id,logical_time,scheduler_wall_clock_observed_at,interval_seconds,state,lease_owner,fencing_token,idempotency_key,claimed_at,tick_ref,health_ref,terminal_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::timestamptz,$8::timestamptz,3600,$9,'writer-a',$10,$11,$8::timestamptz,$12,$13,($8::timestamptz + interval '5 minutes'))`,[...Object.values(scope),id,time,state,i+1,`idem-${id}`,`tick:${id}`,`health:${id}`]);}
  const rows:Array<[string,CanonicalReplayEvidenceRecordV1]>=[["f01",evidence("soil-0910","soil_moisture_observation_v1","2026-08-05T09:10:00.000Z",{ingested:"2026-08-05T09:11:00.000Z"})],["f02",evidence("rain-0930","observed_rainfall_v1","2026-08-05T09:30:00.000Z",{ingested:"2026-08-05T09:31:00.000Z"})],["f03",evidence("et0-0945","historical_et0_estimate_v1","2026-08-05T09:45:00.000Z",{ingested:"2026-08-05T09:46:00.000Z"})]]; for(const [id,record] of rows) await insertEvidence(pool,id,record);
}
function snapshot(status:"COMPLETED"|"BLOCKED"):PersistedNextTickSnapshotV1 { return {active_lineage_ref:"lineage:1",checkpoint:{object_id:"checkpoint:1"} as any,previous_posterior:{object_id:"state:1"} as any,previous_forecast_result:{object_id:"forecast:1",payload:{status}} as any,runtime_config:{object_id:"config:1"} as any,reality_binding:{binding_id:"binding:1",determinism_hash:"sha256:binding",geometry_semantic_hash:"sha256:geometry",scope,root_zone_definition:{}}} as PersistedNextTickSnapshotV1; }
const nextTick=(value:PersistedNextTickSnapshotV1|null):NextTickReadPortV1=>({readPersistedNextTickSnapshot:async(input)=>assert.deepEqual(input,scope)||value} as NextTickReadPortV1);
function runtime(scenario:"TRUE"|"FALSE"|"NULL"):Pick<McftFieldTwinReadApiV1,"readRuntime"> { return {readRuntime:async()=>scenario==="TRUE"?{scenario_source_forecast:{attachment_status:"ATTACHED_EXACT",reason_code:null,item:{object_ref:"forecast:1"}},latest_successful_forecast:{attachment_status:"ATTACHED_EXACT",reason_code:null,item:{object_ref:"forecast:1"}}}:scenario==="FALSE"?{scenario_source_forecast:{attachment_status:"ABSENT_OPTIONAL_DOMAIN",reason_code:"NO_SCENARIO_SOURCE_FORECAST_IN_SCOPE",item:null},latest_successful_forecast:{attachment_status:"ABSENT_OPTIONAL_DOMAIN",reason_code:"NO_SUCCESSFUL_FORECAST_IN_SCOPE",item:null}}:{scenario_source_forecast:{attachment_status:"ABSENT_OPTIONAL_DOMAIN",reason_code:"NO_SCENARIO_SOURCE_FORECAST_IN_SCOPE",item:null},latest_successful_forecast:{attachment_status:"ATTACHED_EXACT",reason_code:null,item:{object_ref:"forecast:1"}}}}; }
async function main(){if(process.env.PFE14_CLASS_B_NARROW_PROVIDER_DESTRUCTIVE_ACCEPTANCE!=="1")throw new Error("SET_PFE14_CLASS_B_NARROW_PROVIDER_DESTRUCTIVE_ACCEPTANCE_1");const url=process.env.DATABASE_URL;if(!url)throw new Error("DATABASE_URL_REQUIRED");const pool=new Pool({connectionString:url});try{await reset(pool);await seed(pool);const factsBefore=Number((await pool.query("SELECT count(*)::int n FROM facts")).rows[0].n);const slotsBefore=Number((await pool.query("SELECT count(*)::int n FROM twin_shadow_online_scheduler_slot_v1")).rows[0].n);
  const completed=await new PostgresPfe14Mcft09OperationalReadApiV1(pool,undefined,nextTick(snapshot("COMPLETED")),runtime("TRUE")).readOperationalSummary({scope}); assert.equal(completed.operational_status.runtime_degradation_status,"DEGRADED"); assert.deepEqual(completed.operational_status.degradation_reason_codes,["SCHEDULER_LAG"]); assert.equal(completed.operational_status.forecast_status,"COMPLETED"); assert.equal(completed.operational_status.scenario_source_eligible,true); assert(completed.slot_window); assert.equal(completed.slot_window.entries.length,24); assert.equal(completed.slot_window.schedule_start_logical_time,"2026-08-05T00:00:00.000Z"); assert.equal(completed.slot_window.entries[0].state,"COMPLETED"); assert.equal(completed.slot_window.entries[10].state,"DEGRADED"); assert.equal(completed.slot_window.entries[11].state,"NOT_MATERIALIZED"); assert.equal(completed.slot_window.entries[23].state,"NOT_MATERIALIZED"); assert.equal(completed.slot_window.entries[11].logical_time,"2026-08-05T11:00:00.000Z");
  const blocked=await new PostgresPfe14Mcft09OperationalReadApiV1(pool,undefined,nextTick(snapshot("BLOCKED")),runtime("FALSE")).readOperationalSummary({scope}); assert.equal(blocked.operational_status.forecast_status,"BLOCKED"); assert.equal(blocked.operational_status.scenario_source_eligible,false);
  const ambiguous=await new PostgresPfe14Mcft09OperationalReadApiV1(pool,undefined,nextTick(snapshot("COMPLETED")),runtime("NULL")).readOperationalSummary({scope}); assert.equal(ambiguous.operational_status.scenario_source_eligible,null);
  const unavailable=await new PostgresPfe14Mcft09OperationalReadApiV1(pool,undefined,nextTick(null),runtime("NULL")).readOperationalSummary({scope}); assert.equal(unavailable.operational_status.runtime_degradation_status,"UNAVAILABLE"); assert.deepEqual(unavailable.operational_status.degradation_reason_codes,["CHECKPOINT_NOT_ESTABLISHED"]); assert.equal(unavailable.operational_status.forecast_status,null);
  assert.equal(Number((await pool.query("SELECT count(*)::int n FROM facts")).rows[0].n),factsBefore); assert.equal(Number((await pool.query("SELECT count(*)::int n FROM twin_shadow_online_scheduler_slot_v1")).rows[0].n),slotsBefore);
  const output={status:"PASS",acceptance_mode:"REAL_POSTGRESQL_CLASS_B_NARROW_OPERATIONAL_PROVIDER",fixed_24_slot_window_verified:true,absent_slot_state:"NOT_MATERIALIZED",degradation_server_verdict_verified:true,forecast_status_verified:true,scenario_source_eligibility_true_false_null_verified:true,canonical_write_performed:false,scheduler_mutation_performed:false}; fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(output,null,2)+"\n");console.log(JSON.stringify(output,null,2));}finally{await pool.end();}}
main().catch((error)=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify({status:"FAIL",error:String((error as Error)?.message??error)},null,2)+"\n");console.error(error);process.exitCode=1;});
