import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import {MCFT_CAP09_EVIDENCE_PRODUCER_LEASE_CONTRACT_ID_V1,type EvidenceProducerLeaseClaimV1,type EvidenceRuntimeScopeV1} from "../../apps/server/src/external_evidence/mcft_cap09_evidence_runtime_persistence_v1.js";
import {ProductionEvidenceProviderAttemptFenceFactoryV1} from "../../apps/server/src/external_evidence/mcft_cap09_production_provider_attempt_fence_v1.js";
import type {ProductionEvidenceSourceDecisionV1} from "../../apps/server/src/external_evidence/mcft_cap09_production_evidence_source_planner_v1.js";
const OUT=path.resolve("acceptance-output/MCFT_CAP_09_PRODUCTION_PROVIDER_ATTEMPT_FENCE_V1_RESULT.json");
const SCOPE:EvidenceRuntimeScopeV1={tenant_id:"t",project_id:"p",group_id:"g",field_id:"f",season_id:"s",zone_id:"z"},REQUESTED="2026-09-02T19:00:00.000Z",TARGET="2026-09-02T20:00:00.000Z";
function claim():EvidenceProducerLeaseClaimV1{return {lease_contract_id:MCFT_CAP09_EVIDENCE_PRODUCER_LEASE_CONTRACT_ID_V1,scope:{...SCOPE},lease_owner:"owner",fencing_token:7n,acquired_at:REQUESTED,expires_at:"2026-09-02T19:10:00.000Z",heartbeat_at:REQUESTED,database_now:REQUESTED};}
function action(operation:Extract<ProductionEvidenceSourceDecisionV1,{status:"ACTION"}>["operation"]):ProductionEvidenceSourceDecisionV1{return {source_family:operation.kind==="KBS_RAW_HOURLY_PUBLICATION_CYCLE"?"KBS_RAW_HOURLY":operation.kind==="KBS_SOIL_CURRENT_ACQUIRE"?"KBS_SOIL":"GFS_BUNDLE",status:"ACTION",authority_ref:"authority://fixture",operation};}
async function main():Promise<void>{
 let pollMode:"CLAIMED"|"NOT_DUE"="CLAIMED",gfsMode:"CLAIMED"|"NOT_DUE"|"ATTEMPT_BUDGET_EXHAUSTED"|"MISSED_WINDOW"="CLAIMED",completedTargets:string[]=[];const pollSources:string[]=[],gfsWindows:string[]=[];
 const factory=new ProductionEvidenceProviderAttemptFenceFactoryV1({activation_fence_time:"2026-09-02T17:00:00.000Z",
  source_poll_schedule:{async readSourcePollSchedule(){return null;},async claimPollBeforeProviderFetch(input){pollSources.push(input.source_family);const schedule={schedule_contract_id:"MCFT_CAP09_EVIDENCE_SOURCE_POLL_SCHEDULE_V1" as const,scope:{...SCOPE},source_family:input.source_family,last_poll_started_at:input.requested_at,next_poll_eligible_at:"2026-09-02T19:15:00.000Z",writer_lease_owner:input.claim.lease_owner,writer_fencing_token:input.claim.fencing_token};return pollMode==="CLAIMED"?{status:"CLAIMED" as const,schedule,provider_request_authorized:true as const,database_write_count:1 as const}:{status:"NOT_DUE" as const,schedule,provider_request_authorized:false as const,database_write_count:0 as const};}},
  gfs_target_pair_history:{async readGfsTargetPairHistory(){return {reader_id:"MCFT_CAP09_GFS_TARGET_PAIR_HISTORY_READER_V1",pairs:completedTargets.map((target,index)=>({target_logical_time:target,cycle_issued_at:"2026-09-02T18:00:00.000Z",weather_fact_id:"weather-"+index,future_et0_fact_id:"et0-"+index})),partial_targets:[],canonical_fact_read_count:completedTargets.length*2};}},
  gfs_retry_schedule:{async readGfsRetrySchedule(){return null;},async claimGfsAttemptBeforeProviderFetch(input){gfsWindows.push(input.due_window_start+"|"+input.due_window_end_exclusive);const schedule={schedule_contract_id:"MCFT_CAP09_GFS_RETRY_SCHEDULE_V1" as const,scope:{...SCOPE},target_logical_time:input.target_logical_time,attempt_count:1,last_attempt_started_at:input.requested_at,next_attempt_eligible_at:"2026-09-02T19:01:00.000Z",writer_lease_owner:input.claim.lease_owner,writer_fencing_token:input.claim.fencing_token};if(gfsMode==="CLAIMED")return {status:"CLAIMED" as const,schedule,provider_request_authorized:true as const,database_write_count:1 as const};if(gfsMode==="NOT_DUE")return {status:"NOT_DUE" as const,schedule,provider_request_authorized:false as const,database_write_count:0 as const};if(gfsMode==="ATTEMPT_BUDGET_EXHAUSTED")return {status:"ATTEMPT_BUDGET_EXHAUSTED" as const,schedule,provider_request_authorized:false as const,database_write_count:0 as const};return {status:"MISSED_WINDOW" as const,schedule,provider_request_authorized:false as const,database_write_count:0 as const};}}
 });
 const kbs=factory.buildForDecision(action({kind:"KBS_RAW_HOURLY_PUBLICATION_CYCLE",requested_at:REQUESTED,observed_pair_state:"PAIRED",paired_contiguous_through:"2026-09-02T18:00:00.000Z",pair_skew_seconds:0,bindable_to_current_cycle_service:true}));assert(kbs);assert.equal((await kbs.claimBeforeProviderFetch({claim:claim()})).status,"AUTHORIZED");
 const soil=factory.buildForDecision(action({kind:"KBS_SOIL_CURRENT_ACQUIRE",requested_at:REQUESTED,latest_observed_event_time:null,bindable_to_current_work_item_factory:true}));assert(soil);assert.equal((await soil.claimBeforeProviderFetch({claim:claim()})).status,"AUTHORIZED");assert.deepEqual(pollSources,["KBS_RAW_HOURLY","KBS_SOIL"]);
 const gd=action({kind:"GFS_BUNDLE_ACQUIRE",target_logical_time:TARGET,requested_at:REQUESTED,due_window_start:"2026-09-02T18:50:00.000Z",due_window_end_exclusive:"2026-09-02T19:30:00.000Z",max_attempts_per_target_window:3,retry_minimum_interval_seconds:60,bindable_to_current_work_item_factory:true});
 const gf=factory.buildForDecision(gd);assert(gf);assert.equal((await gf.claimBeforeProviderFetch({claim:claim()})).status,"AUTHORIZED");assert.deepEqual(gfsWindows,["2026-09-02T18:50:00.000Z|2026-09-02T19:30:00.000Z"]);
 completedTargets=[TARGET];const beforeStaleRecheckWrites=gfsWindows.length;assert.equal((await factory.buildForDecision(gd)!.claimBeforeProviderFetch({claim:claim()})).status,"NOT_DUE");assert.equal(gfsWindows.length,beforeStaleRecheckWrites);completedTargets=[];
 pollMode="NOT_DUE";const st=factory.buildForDecision(action({kind:"KBS_SOIL_CURRENT_ACQUIRE",requested_at:REQUESTED,latest_observed_event_time:null,bindable_to_current_work_item_factory:true}));assert(st);assert.equal((await st.claimBeforeProviderFetch({claim:claim()})).status,"NOT_DUE");
 gfsMode="NOT_DUE";assert.equal((await factory.buildForDecision(gd)!.claimBeforeProviderFetch({claim:claim()})).status,"NOT_DUE");
 gfsMode="ATTEMPT_BUDGET_EXHAUSTED";await assert.rejects(()=>factory.buildForDecision(gd)!.claimBeforeProviderFetch({claim:claim()}),/GFS_ATTEMPT_BUDGET_EXHAUSTED/);
 gfsMode="MISSED_WINDOW";await assert.rejects(()=>factory.buildForDecision(gd)!.claimBeforeProviderFetch({claim:claim()}),/GFS_MISSED_WINDOW/);
 const partial=factory.buildForDecision(action({kind:"GFS_PARTIAL_PAIR_REHYDRATE",requested_at:REQUESTED,target_logical_time:TARGET,cycle_key:"20260902t180000z",cycle_issued_at:"2026-09-02T18:00:00.000Z",available_role:"WEATHER",partial_progress:{cycle_key:"20260902t180000z",cycle_issued_at:"2026-09-02T18:00:00.000Z",state:"PARTIAL",weather:null,future_et0:null,paired_valid_from:null},bindable_to_current_cycle_service:true}));assert.equal(partial,null);
 const source=fs.readFileSync(path.resolve("apps/server/src/external_evidence/mcft_cap09_production_provider_attempt_fence_v1.ts"),"utf8");for(const x of ["Date.now","process.env","fetch(","RuntimeTickCursor"])assert.equal(source.includes(x),false);
 const proof={status:"PASS",kbs_raw_poll_claim_bound:true,kbs_soil_poll_claim_bound:true,gfs_retry_claim_bound:true,gfs_due_window_forwarded_without_replanning:true,source_poll_not_due_zero_provider_authorization:true,gfs_retry_not_due_zero_provider_authorization:true,gfs_after_lease_canonical_exact_target_recheck_zero_retry_write:true,gfs_attempt_budget_exhaustion_fail_closed:true,gfs_missed_window_fail_closed:true,gfs_partial_retained_rehydration_consumes_provider_attempt_budget:false,provider_request_count:0,production_runtime_start:false};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(proof,null,2)+"\n");console.log(JSON.stringify(proof,null,2));
}
main().catch(e=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify({status:"FAIL",error:e instanceof Error?e.message:String(e)},null,2)+"\n");console.error(e);process.exitCode=1;});
