// scripts/runtime_acceptance/ACCEPTANCE_SOIL_WATER_POTENTIAL_ESTIMATE_RUNTIME_V1.cjs
const { randomUUID } = require('node:crypto'); const { Pool } = require('pg'); require('tsx/cjs');
const NAME='ACCEPTANCE_SOIL_WATER_POTENTIAL_ESTIMATE_RUNTIME_V1';
function assert(c,m,d){ if(!c){ throw new Error(m+(d?` ${JSON.stringify(d)}`:'')); } }
async function exists(c,t){ const q=await c.query('SELECT to_regclass($1)::text name',[`public.${t}`]); return Boolean(q.rows[0]?.name); }
async function count(c,t,where,params){ if(!await exists(c,t)) return 0; const q=await c.query(`SELECT COUNT(*)::int count FROM public.${t} WHERE ${where}`,params); return Number(q.rows[0]?.count||0); }
async function ensureFacts(c){ await c.query(`CREATE TABLE IF NOT EXISTS public.facts (fact_id text PRIMARY KEY, occurred_at timestamptz NOT NULL DEFAULT now(), source text NOT NULL, record_json jsonb NOT NULL)`); }
async function ensureWindow(c){ await c.query(`CREATE TABLE IF NOT EXISTS public.soil_moisture_sensing_window_index_v1 (tenant_id text NOT NULL, project_id text NOT NULL, group_id text NOT NULL, field_id text NOT NULL, window_id text NOT NULL, device_id text, metric text, window_start timestamptz, window_end timestamptz, expected_interval_ms integer, expected_points integer, actual_points integer, coverage_ratio numeric, max_gap_ms integer, quality_status text, confidence_json jsonb, summary_json jsonb, config_snapshot_json jsonb, evidence_refs_json jsonb, source_fact_ids_json jsonb, source_observation_ids_json jsonb, source_fact_id text, created_at timestamptz, updated_at timestamptz, PRIMARY KEY (tenant_id, window_id), UNIQUE (tenant_id, project_id, group_id, field_id, window_id))`); }
(async()=>{ const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(url,'DATABASE_URL/POSTGRES_URL/PG_URL required');
const { buildSoilWaterPotentialEstimateV1, ingestSoilWaterPotentialEstimateV1 } = require(process.cwd()+'/apps/server/src/projections/soil_water_potential_estimate_v1.ts');
const { upsertSoilHydraulicProfileIndexV1 } = require(process.cwd()+'/apps/server/src/projections/soil_hydraulic_profile_v1.ts');
const { mapSoilMoistureSensingWindowIndexV1Row } = require(process.cwd()+'/apps/server/src/projections/soil_moisture_sensing_window_v1.ts');
const pool=new Pool({connectionString:url}); const client=await pool.connect(); const run='h31_'+randomUUID(); const scope={tenant_id:'tenantA',project_id:'projectA',group_id:'groupA',field_id:`${run}_field`,zone_id:`${run}_zone`,layer_depth_cm:30};
try{ await client.query('BEGIN'); await ensureFacts(client); await ensureWindow(client);
const forbidden=['decision_recommendation_index_v1','approval_request_index_v1','approval_decision_index_v1','operation_plan_index_v1','ao_act_task_index_v1','roi_ledger_index_v1','field_memory_index_v1']; const before={}; for(const t of forbidden) before[t]=await count(client,t,'tenant_id=$1 AND project_id=$2 AND group_id=$3 AND field_id=$4',[scope.tenant_id,scope.project_id,scope.group_id,scope.field_id]);
const now='2026-06-21T00:00:00.000Z'; const profile={...scope,profile_id:`${run}_profile`,texture_class:'loam',theta_r:0.08,theta_s:0.43,alpha_per_kpa:0.035,n:1.56,m:1-1/1.56,parameter_source:'MANUAL',calibration_status:'UNVERIFIED',confidence_level:'LOW',confidence_score:0.4,evidence_refs:[`${run}_profile_ev`],created_at:now}; await upsertSoilHydraulicProfileIndexV1(client,profile,`${run}_profile_fact`);
const windowId=`${run}_window`; await client.query(`INSERT INTO public.soil_moisture_sensing_window_index_v1(tenant_id,project_id,group_id,field_id,window_id,device_id,metric,window_start,window_end,expected_interval_ms,expected_points,actual_points,coverage_ratio,max_gap_ms,quality_status,confidence_json,summary_json,config_snapshot_json,evidence_refs_json,source_fact_ids_json,source_observation_ids_json,source_fact_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,'device_h31','soil_vwc_percent',$6,$6,900000,4,4,1,0,'PASS',$7::jsonb,$8::jsonb,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13,$6,$6) ON CONFLICT (tenant_id, window_id) DO UPDATE SET summary_json=EXCLUDED.summary_json, quality_status=EXCLUDED.quality_status`,[scope.tenant_id,scope.project_id,scope.group_id,scope.field_id,windowId,now,JSON.stringify({level:'HIGH'}),JSON.stringify({last_value:28}),JSON.stringify({}),JSON.stringify([`${run}_window_ev`]),JSON.stringify([`${run}_window_fact`]),JSON.stringify([`${run}_obs`]),`${run}_source_fact`]);
const row=(await client.query('SELECT * FROM public.soil_moisture_sensing_window_index_v1 WHERE tenant_id=$1 AND window_id=$2',[scope.tenant_id,windowId])).rows[0]; const sensingWindow=mapSoilMoistureSensingWindowIndexV1Row(row);
const estimate=buildSoilWaterPotentialEstimateV1({...scope,sensingWindow,hydraulicProfile:profile,computed_at:now}); const estimate2=buildSoilWaterPotentialEstimateV1({...scope,sensingWindow,hydraulicProfile:profile,computed_at:'2030-01-01T00:00:00.000Z'});
assert(estimate.input_status==='ESTIMATED','output has input_status ESTIMATED',estimate); assert(Number.isFinite(estimate.matric_potential_kpa)&&estimate.matric_potential_kpa<0,'finite negative matric potential',estimate); assert(estimate.determinism_hash===estimate2.determinism_hash,'stable determinism_hash');
await ingestSoilWaterPotentialEstimateV1(client,estimate); const found=await client.query('SELECT * FROM public.soil_water_potential_estimate_index_v1 WHERE estimate_id=$1',[estimate.estimate_id]); assert(found.rowCount===1,'can append fact and upsert index');
for(const t of forbidden){ const after=await count(client,t,'tenant_id=$1 AND project_id=$2 AND group_id=$3 AND field_id=$4',[scope.tenant_id,scope.project_id,scope.group_id,scope.field_id]); assert(after===before[t],`no rows created in ${t}`,{before:before[t],after}); }
await client.query('ROLLBACK'); const hp=await pool.query('SELECT COUNT(*)::int count FROM public.soil_hydraulic_profile_index_v1 WHERE profile_id=$1',[profile.profile_id]).catch(()=>({rows:[{count:0}]})); assert(Number(hp.rows[0].count)===0,'rollback removes probe writes');
console.log(`[${NAME}] PASS`);
} catch(e){ try{ await client.query('ROLLBACK'); }catch(_){} throw e; } finally{ client.release(); await pool.end(); }
})().catch(e=>{ console.error(`[${NAME}] FAIL`); console.error(e.stack||e); process.exit(1); });
