#!/usr/bin/env node
const { randomUUID } = require('crypto'); const { Pool } = require('pg');
const BASE=String(process.env.GEOX_BASE_URL||process.env.BASE_URL||'http://127.0.0.1:3001').replace(/\/$/,'');
const TENANT=process.env.TENANT_ID||'tenantA', PROJECT=process.env.PROJECT_ID||'projectA', GROUP=process.env.GROUP_ID||'groupA';
const RUN='h30_'+randomUUID(), FIELD=RUN+'_field', SET=RUN+'_scenario_set', OPTION='irrigate_22mm', REC=RUN+'_rec_seed', APPROVAL=RUN+'_approval', PLAN=RUN+'_plan', TASK=RUN+'_task', RECEIPT=RUN+'_receipt';
const assert=(c,m,d)=>{if(!c)throw new Error(m+(d?' '+JSON.stringify(d):''));};
async function table(pool,t){const q=await pool.query('SELECT to_regclass($1)::text name',[`public.${t}`]); return !!q.rows[0].name;}
async function factCount(pool){const q=await pool.query('SELECT COUNT(*)::int count FROM facts WHERE source=$1 OR fact_id LIKE $2',['decision_to_delivery_e2e_seed',RUN+'%']); return +q.rows[0].count;}
async function insertFact(pool,suffix,type,payload,i){await pool.query(`INSERT INTO facts(fact_id,occurred_at,source,record_json) VALUES($1,NOW()+($2||' seconds')::interval,$3,$4::jsonb) ON CONFLICT(fact_id) DO UPDATE SET occurred_at=EXCLUDED.occurred_at,source=EXCLUDED.source,record_json=EXCLUDED.record_json`,[`${RUN}_${suffix}`,String(i),'decision_to_delivery_e2e_seed',JSON.stringify({type,schema_version:'1',payload})]);}
async function seed(pool){const now=new Date().toISOString(); await pool.query(`INSERT INTO field_index_v1(tenant_id,field_id,name,area_ha,status,created_ts_ms,updated_ts_ms) VALUES($1,$2,$3,1.2,'ACTIVE',$4,$4) ON CONFLICT DO NOTHING`,[TENANT,FIELD,'H30 Three Surface Field',Date.now()]);
 const scope={tenant_id:TENANT,project_id:PROJECT,group_id:GROUP,field_id:FIELD,season_id:RUN+'_season'};
 await pool.query(`INSERT INTO irrigation_scenario_set_index_v1(scenario_set_id,tenant_id,project_id,group_id,field_id,season_id,baseline_water_state,baseline_soil_moisture_percent,target_min_soil_moisture_percent,target_max_soil_moisture_percent,net_irrigation_mm,gross_irrigation_requirement_mm,options_json,recommended_option_id,input_refs_json,evidence_refs_json,derivation_json,quality_json,confidence_json,source_fact_id,created_at,updated_at) VALUES($1,$2,$3,$4,$5,$6,'MODERATE_DEFICIT',18,24,32,22,24,$7::jsonb,$8,$9::jsonb,$10::jsonb,$11::jsonb,$12::jsonb,$13::jsonb,$14,$15,$15) ON CONFLICT (scenario_set_id) DO UPDATE SET options_json=EXCLUDED.options_json,updated_at=EXCLUDED.updated_at`,[SET,TENANT,PROJECT,GROUP,FIELD,scope.season_id,JSON.stringify([{option_id:'no_action',label:'No action',risk_delta:'baseline'},{option_id:OPTION,label:'Irrigate 22mm',amount_mm:22,risk_delta:'LOWER_DEFICIT_RISK'}]),OPTION,JSON.stringify({}),JSON.stringify([RUN+'_ev']),JSON.stringify({source:'seed'}),JSON.stringify({status:'PASS'}),JSON.stringify({level:'HIGH'}),RUN+'_scenario_fact',now]);
 await insertFact(pool,'workspace','operator_field_twin_workspace_v1',{...scope,status:'ACTIVE',water_state:'MODERATE_DEFICIT'},1);
 await insertFact(pool,'evidence_quality','operator_field_twin_evidence_quality_v1',{...scope,quality_status:'SUFFICIENT',evidence_refs:[RUN+'_ev']},2);
 await insertFact(pool,'submission_seed','operator_scenario_recommendation_submission_v1',{...scope,scenario_set_id:SET,option_id:OPTION,recommendation_id:REC,amount_mm:22,submitted_at:now},3);
 await insertFact(pool,'rec_seed','decision_recommendation_v1',{...scope,recommendation_id:REC,recommendation_type:'IRRIGATION',action_summary:'Irrigate 22mm',amount_mm:22,human_approval_required:true,evidence_refs:[RUN+'_ev']},4);
 await insertFact(pool,'approval','approval_request_v1',{...scope,recommendation_id:REC,request_id:APPROVAL,approval_request_id:APPROVAL,status:'APPROVED'},5);
 await insertFact(pool,'approval_decision','approval_decision_v1',{...scope,recommendation_id:REC,request_id:APPROVAL,decision_id:RUN+'_decision',decision:'APPROVED'},6);
 await insertFact(pool,'plan','operation_plan_v1',{...scope,recommendation_id:REC,approval_request_id:APPROVAL,operation_plan_id:PLAN,act_task_id:TASK,action_type:'IRRIGATION',status:'READY'},7);
 await insertFact(pool,'task','ao_act_task_v0',{...scope,recommendation_id:REC,operation_plan_id:PLAN,act_task_id:TASK,status:'DISPATCHED',action_type:'IRRIGATION'},8);
 await insertFact(pool,'receipt','ao_act_receipt_v1',{...scope,operation_plan_id:PLAN,act_task_id:TASK,receipt_id:RECEIPT,status:'SUCCEEDED',logs_refs:[RUN+'_log'],metrics:[{key:'applied_mm',value:22}]},9);
 await insertFact(pool,'as_executed','as_executed_record_v1',{...scope,operation_plan_id:PLAN,act_task_id:TASK,receipt_id:RECEIPT,applied_mm:22},10);
 await insertFact(pool,'artifact','evidence_artifact_v1',{...scope,operation_plan_id:PLAN,act_task_id:TASK,kind:'field_photo',uri:'s3://acceptance/'+RUN},11);
 await insertFact(pool,'acceptance','acceptance_result_v1',{...scope,operation_plan_id:PLAN,act_task_id:TASK,acceptance_id:RUN+'_acceptance',verdict:'PASS',missing_evidence:[],formal:true},12);
 await insertFact(pool,'roi','roi_ledger_v1',{...scope,operation_id:PLAN,recommendation_id:REC,water_saved_mm:2},13);
 if(await table(pool,'field_memory_v1')) await pool.query(`INSERT INTO field_memory_v1(memory_id,tenant_id,project_id,group_id,field_id,operation_id,recommendation_id,memory_type,memory_lane,trust_level,customer_visible_memory,learning_eligible,summary_text,evidence_refs,occurred_at) VALUES($1,$2,$3,$4,$5,$6,$7,'FIELD_RESPONSE_MEMORY','ACCEPTED','HIGH',true,false,'H30 field response memory',$8::jsonb,NOW()) ON CONFLICT DO NOTHING`,[RUN+'_memory',TENANT,PROJECT,GROUP,FIELD,PLAN,REC,JSON.stringify([RUN+'_ev'])]).catch(()=>{});
}
async function cleanup(pool){await pool.query('DELETE FROM facts WHERE source=$1 OR fact_id LIKE $2',['decision_to_delivery_e2e_seed',RUN+'%']).catch(()=>{}); await pool.query('DELETE FROM field_index_v1 WHERE tenant_id=$1 AND field_id=$2',[TENANT,FIELD]).catch(()=>{}); await pool.query('DELETE FROM irrigation_scenario_set_index_v1 WHERE scenario_set_id=$1',[SET]).catch(()=>{}); await pool.query('DELETE FROM field_memory_v1 WHERE memory_id=$1',[RUN+'_memory']).catch(()=>{});}
async function get(p){const r=await fetch(BASE+p,{headers:{accept:'application/json'}}); const j=await r.json().catch(()=>null); assert(r.ok,'HTTP failed '+p,{status:r.status,body:j}); return j;}
async function postSubmit(){const r=await fetch(`${BASE}/api/v1/operator/twin/fields/${FIELD}/scenarios/${SET}/options/${OPTION}/submit-recommendation`,{method:'POST',headers:{'content-type':'application/json',accept:'application/json'},body:JSON.stringify({tenant_id:TENANT,project_id:PROJECT,group_id:GROUP,operator_id:'h30_operator',idempotency_key:RUN+'_submit'})}); const j=await r.json().catch(()=>null); assert(r.ok,'submit failed',j); return j;}
(async()=>{const cs=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(cs,'DATABASE_URL/POSTGRES_URL/PG_URL required'); const pool=new Pool({connectionString:cs}); try{assert(await table(pool,'facts'),'facts table required'); await cleanup(pool); await seed(pool); const before=await factCount(pool); const twin=await get(`/api/v1/operator/twin/fields/${FIELD}?tenant_id=${TENANT}&project_id=${PROJECT}&group_id=${GROUP}`); assert(twin.source==='operator_field_twin_workspace_api'&&twin.dataScope==='OFFICIAL_OPERATOR_TWIN_API','operator twin envelope',twin); const sc=await get(`/api/v1/operator/twin/fields/${FIELD}/scenarios?tenant_id=${TENANT}&project_id=${PROJECT}&group_id=${GROUP}`); assert(JSON.stringify(sc).includes('no_action'),'no_action baseline missing'); const sub=await postSubmit(); assert(sub.operator_scenario_recommendation_submission_v1?.approval_created===false && sub.operator_scenario_recommendation_submission_v1?.operation_plan_created===false && sub.operator_scenario_recommendation_submission_v1?.task_created===false,'submit crossed write boundary',sub); const afterSubmit=await factCount(pool); assert(afterSubmit===before+2,'submit must add exactly two recommendation facts',{before,afterSubmit}); const sum=await get(`/api/v1/customer/fields/${FIELD}/confirmed-twin-summary?tenant_id=${TENANT}&project_id=${PROJECT}&group_id=${GROUP}`); assert(sum.surface==='CUSTOMER'&&sum.dataScope==='OFFICIAL_CUSTOMER_DELIVERY_PORTAL','customer summary envelope',sum); assert(JSON.stringify(sum).includes(REC)||JSON.stringify(sum).includes('recommendation'),'summary cannot read recommendation'); assert(!JSON.stringify(sum).includes('options_json')&&!JSON.stringify(sum).includes(OPTION),'customer summary leaked scenario options'); const rep=await get(`/api/v1/reports/operation/${PLAN}?tenant_id=${TENANT}&project_id=${PROJECT}&group_id=${GROUP}`); assert(JSON.stringify(rep).includes(PLAN)&&JSON.stringify(rep).includes(TASK),'operation report chain missing'); const ops=await get('/api/v1/admin/operations'); assert(ops.surface==='ADMIN'&&ops.writeReady===false,'admin operations read boundary',ops); const ev=await get('/api/v1/admin/evidence'); assert(ev.surface==='ADMIN'&&ev.writeReady===false,'admin evidence read boundary',ev); const dash=await get('/api/v1/admin/dashboard'); assert(dash.surface==='ADMIN'&&dash.dataScope==='INTERNAL_ADMIN_CONTROL_PLANE','admin dashboard envelope',dash); assert(await factCount(pool)===afterSubmit,'customer/admin GET must not write facts'); console.log('[decision-to-delivery-e2e] PASS');} finally{await cleanup(pool); await pool.end();}})().catch(e=>{console.error('[decision-to-delivery-e2e] FAIL'); console.error(e.stack||e); process.exit(1);});
