import assert from "node:assert/strict";import fs from "node:fs";import path from "node:path";
import {MCFT_CAP09_SEPARATE_PRODUCTION_RUNTIME_START_AUTHORITY_CLASS_V1} from "../../apps/server/src/external_evidence/mcft_cap09_production_evidence_acquisition_horizon_v1.js";
import {ProductionEvidenceHostPlannerV1} from "../../apps/server/src/external_evidence/mcft_cap09_production_evidence_host_planner_v1.js";
import type {EvidenceSourceSpecificProgressV1,GfsCyclePairProgressV1} from "../../apps/server/src/external_evidence/mcft_cap09_evidence_source_progress_v1.js";
import type {EvidenceSourcePollScheduleSnapshotV1} from "../../apps/server/src/external_evidence/mcft_cap09_evidence_source_poll_schedule_v1.js";
const OUT=path.resolve("acceptance-output/MCFT_CAP_09_PRODUCTION_EVIDENCE_HOST_PLANNER_V1_RESULT.json");
const SCOPE={tenant_id:"t",project_id:"p",group_id:"g",field_id:"f",season_id:"s",zone_id:"z"},FENCE="2026-09-02T18:00:00.000Z",A0="2026-09-02T20:00:00.000Z";
let now="2026-09-02T19:00:00.000Z",paired:GfsCyclePairProgressV1[]=[],completed:string[]=[],rawNext:string|null=null,soilNext:string|null=null;const selected:string[]=[];
function progress():EvidenceSourceSpecificProgressV1{return {reader_id:"MCFT_CAP09_EVIDENCE_SOURCE_PROGRESS_READER_V1",kbs_raw_hourly:{state:"ABSENT",rainfall:null,historical_et0:null,paired_contiguous_through:null,pair_skew_seconds:null},gfs_bundle:{cycles:paired,complete_pair_count:paired.filter(x=>x.state==="PAIRED").length,partial_pair_count:0},kbs_soil:{latest:null}};}
function sched(source:"KBS_RAW_HOURLY"|"KBS_SOIL",next:string|null):EvidenceSourcePollScheduleSnapshotV1|null{return next?{schedule_contract_id:"MCFT_CAP09_EVIDENCE_SOURCE_POLL_SCHEDULE_V1",scope:{...SCOPE},source_family:source,last_poll_started_at:FENCE,next_poll_eligible_at:next,writer_lease_owner:"owner",writer_fencing_token:1n}:null;}
const planner=new ProductionEvidenceHostPlannerV1({scope:SCOPE,runtime_start_authority:{authority_class:MCFT_CAP09_SEPARATE_PRODUCTION_RUNTIME_START_AUTHORITY_CLASS_V1,authority_ref:"authority://runtime-start",activation_fence_time:FENCE,formal_a0_authority_ref:"authority://formal-a0",formal_a0_logical_time:A0},planning_clock:{now:()=>now},progress_reader:{async readProgress(){return progress();}},source_poll_schedule:{async readSourcePollSchedule(input){return sched(input.source_family,input.source_family==="KBS_RAW_HOURLY"?rawNext:soilNext);}},gfs_target_pair_history:{async readGfsTargetPairHistory(){return {reader_id:"MCFT_CAP09_GFS_TARGET_PAIR_HISTORY_READER_V1",pairs:completed.map((target,index)=>({target_logical_time:target,cycle_issued_at:"2026-09-02T18:00:00.000Z",weather_fact_id:"weather-"+index,future_et0_fact_id:"et0-"+index})),partial_targets:[],canonical_fact_read_count:completed.length*2};}},source_plan_executor:{buildAttempt(d){selected.push(d.source_family+":"+d.operation.kind);return {attempt_id:"a:"+selected.length,attempt_kind:d.operation.kind==="KBS_RAW_HOURLY_PUBLICATION_CYCLE"?"KBS_RAW_HOURLY_PUBLICATION_CYCLE":d.operation.kind==="GFS_PARTIAL_PAIR_REHYDRATE"?"GFS_PARTIAL_PAIR_REHYDRATION":"CANONICAL_WORK_ITEM_CYCLE",async execute(){throw new Error("QUALIFICATION_EXECUTION_FORBIDDEN");}};}}});
async function main(){
 let a=await planner.nextAttemptPlan({cycle_attempt:0,successful_cycle_count:0,consecutive_failure_count:0,previous_result:null});assert(a&&!("status" in a));assert.equal(selected.at(-1),"GFS_BUNDLE:GFS_BUNDLE_ACQUIRE");
 paired=[{cycle_key:"20260902t180000z",cycle_issued_at:"2026-09-02T18:00:00.000Z",state:"PAIRED",weather:null,future_et0:null,paired_valid_from:"2026-09-02T23:00:00.000Z"}];completed=[A0];now="2026-09-02T19:01:00.000Z";
 a=await planner.nextAttemptPlan({cycle_attempt:1,successful_cycle_count:1,consecutive_failure_count:0,previous_result:null});assert(a&&!("status" in a));assert.equal(selected.at(-1),"KBS_SOIL:KBS_SOIL_CURRENT_ACQUIRE");
 soilNext="2026-09-02T19:06:00.000Z";
 a=await planner.nextAttemptPlan({cycle_attempt:2,successful_cycle_count:2,consecutive_failure_count:0,previous_result:null});assert(a&&!("status" in a));assert.equal(selected.at(-1),"KBS_RAW_HOURLY:KBS_RAW_HOURLY_PUBLICATION_CYCLE");
 rawNext="2026-09-02T19:16:00.000Z";
 a=await planner.nextAttemptPlan({cycle_attempt:3,successful_cycle_count:3,consecutive_failure_count:0,previous_result:null});assert.deepEqual(a,{status:"NOT_DUE"});
 now="2026-09-02T20:30:00.000Z";await assert.rejects(()=>planner.nextAttemptPlan({cycle_attempt:4,successful_cycle_count:3,consecutive_failure_count:0,previous_result:null}),/GFS_MISSED_WINDOW/);
 const source=fs.readFileSync(path.resolve("apps/server/src/external_evidence/mcft_cap09_production_evidence_host_planner_v1.ts"),"utf8");for(const x of ["process.env","Date.now","fetch(","RuntimeTickCursor","INSERT INTO","UPDATE ","DELETE FROM"])assert.equal(source.includes(x),false);
 const proof={status:"PASS",explicit_runtime_start_authority_required:true,explicit_formal_a0_required:true,gfs_selected_first_under_hard_deadline:true,soil_selected_after_gfs_not_due:true,daily_batch_selected_after_soil_throttled:true,all_not_due_returns_host_not_due:true,gfs_missed_window_fail_closed:true,durable_state_replanned_each_attempt:true,canonical_gfs_target_history_drives_progression:true,cursor_cycle_summary_not_hourly_completion_authority:true,provider_request_count:0,database_write_count:0,runtime_tick_cursor_access:false,production_entrypoint_bound:false,runtime_process_start:false};fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(proof,null,2)+"\n");console.log(JSON.stringify(proof,null,2));
}
main().catch(e=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify({status:"FAIL",error:e instanceof Error?e.message:String(e)},null,2)+"\n");console.error(e);process.exitCode=1;});
