// scripts/runtime_acceptance/ACCEPTANCE_RECOMMENDATION_APPROVAL_DECISION_RUNTIME_V1.cjs
const assert = require('node:assert/strict'); const crypto = require('node:crypto'); const { Pool } = require('pg');
const RUN=`h37_recommendation_approval_decision_acceptance_${Date.now()}_${crypto.randomUUID().slice(0,8)}`; const DB=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; const BASE=process.env.BASE_URL||'http://127.0.0.1:3001';
const ADMIN=process.env.GEOX_ACCEPTANCE_TOKEN||'set-via-env-or-external-secret-file-admin'; const APPROVER=process.env.GEOX_APPROVER_ACCEPTANCE_TOKEN||'set-via-env-or-external-secret-file-approver'; const OPERATOR='set-via-env-or-external-secret-file-pdi-writeonly'; const CLIENT='set-via-env-or-external-secret-file-client'; const TENANT=process.env.GEOX_TENANT_ID||'tenantA', PROJECT=process.env.GEOX_PROJECT_ID||'projectA', GROUP=process.env.GEOX_GROUP_ID||'groupA', FIELD=process.env.THREE_SURFACE_FIELD_ID||'field_demo_001';
function auth(t){return {authorization:`Bearer ${t}`,'content-type':'application/json'}} function reqId(n){return `${RUN}_${n}`}
async function post(id, body, token=APPROVER){ const r=await fetch(`${BASE}/api/v1/operator/approval-requests/${encodeURIComponent(id)}/decision`,{method:'POST',headers:auth(token),body:JSON.stringify(body)}); return {status:r.status,json:await r.json().catch(()=>null)}; }
async function insert(pool,id,patch={}){ const payload={tenant_id:TENANT,project_id:PROJECT,group_id:GROUP,field_id:FIELD,zone_id:'zoneA',request_id:id,approval_request_id:id,status:'PENDING',actor_id:`issuer_${RUN}`,token_id:`tok_issuer_${RUN}`,proposal:{issuer:{id:`issuer_${RUN}`},meta:{source:'DECISION_RECOMMENDATION_V1',approval_intent:'REQUEST_HUMAN_APPROVAL_ONLY',no_direct_execution:true,skip_auto_task_issue:true,allow_auto_task_issue:false,approval_decision_created:false,operation_plan_created:false,task_created:false,dispatch_created:false,roi_created:false,field_memory_created:false,recommendation_id:`rec_${id}`,source_submission_id:`sub_${id}`}},...patch}; await pool.query('INSERT INTO facts(fact_id,occurred_at,source,record_json) VALUES($1,NOW(),$2,$3::jsonb)',[`fact_${id}`,RUN,JSON.stringify({type:'approval_request_v1',payload})]); return payload; }
async function count(pool,type){ const r=await pool.query("SELECT count(*)::int n FROM facts WHERE record_json->>'type'=$1 AND record_json::text LIKE $2",[type,`%${RUN}%`]); return Number(r.rows[0].n); }
async function cleanup(pool){ await pool.query('DELETE FROM facts WHERE source=$1 OR record_json::text LIKE $2',[RUN,`%${RUN}%`]).catch(()=>{}); }
(async()=>{ assert(DB,'DATABASE_URL required'); const pool=new Pool({connectionString:DB}); try{ await cleanup(pool);
  const baseBody={tenant_id:TENANT,project_id:PROJECT,group_id:GROUP,field_id:FIELD,zone_id:'zoneA',approver_id:`approver_${RUN}`,decision:'APPROVED',decision_reason:'approved for controlled irrigation execution planning',idempotency_key:`${RUN}_key`};
  await insert(pool,reqId('approve')); let out=await post(reqId('approve'),baseBody); assert.equal(out.json.status,'DECISION_RECORDED'); assert.equal(await count(pool,'operator_recommendation_approval_decision_submission_v1'),1); assert.equal(await count(pool,'approval_decision_v1'),1); assert.equal(await count(pool,'approval_request_v1'),2);
  for (const t of ['operation_plan_v1','operation_plan_transition_v1','ao_act_task_v0','roi_ledger_v1','field_memory_v1']) assert.equal(await count(pool,t),0,`${t} absent`);
  out=await post(reqId('approve'),baseBody); assert.equal(out.json.status,'REJECTED_DUPLICATE'); assert.equal(await count(pool,'approval_decision_v1'),1);
  await insert(pool,reqId('reject')); out=await post(reqId('reject'),{...baseBody,decision:'REJECTED',idempotency_key:`${RUN}_reject`}); assert.equal(out.json.status,'DECISION_RECORDED'); assert.equal(out.json.decision,'REJECTED'); assert.equal(await count(pool,'approval_decision_v1'),2);
  const cases=[['nonpending',{status:'APPROVED'},'REJECTED_APPROVAL_REQUEST_NOT_PENDING',{}],['nonderived',{proposal:{meta:{}}},'REJECTED_NOT_RECOMMENDATION_DERIVED',{}],['scope',{},'REJECTED_APPROVAL_REQUEST_NOT_FOUND',{field_id:`${FIELD}_other`}],['self',{},'REJECTED_SELF_APPROVAL',{approver_id:`issuer_${RUN}`}]];
  for (const [n,patch,exp,bpatch] of cases){ await insert(pool,reqId(n),patch); const before=await count(pool,'approval_decision_v1'); out=await post(reqId(n),{...baseBody,...bpatch,idempotency_key:`${RUN}_${n}`}); assert.equal(out.json.status,exp,n); assert.equal(await count(pool,'approval_decision_v1'),before,n+' no decision'); }
  await insert(pool,reqId('operator_auth')); let before=await count(pool,'approval_decision_v1'); out=await post(reqId('operator_auth'),{...baseBody,idempotency_key:`${RUN}_operator_auth`},OPERATOR); assert(out.status===403 || out.status===401, 'operator token rejected'); assert.equal(await count(pool,'approval_decision_v1'),before);
  await insert(pool,reqId('client_auth')); before=await count(pool,'approval_decision_v1'); out=await post(reqId('client_auth'),{...baseBody,idempotency_key:`${RUN}_client_auth`},CLIENT); assert(out.status===403 || out.status===401, 'client token rejected'); assert.equal(await count(pool,'approval_decision_v1'),before);
  out=await post(reqId('missing'),{...baseBody,decision:'BAD',idempotency_key:`${RUN}_bad`}); assert.equal(out.json.status,'REJECTED_INVALID_INPUT'); out=await post(reqId('missing'),{...baseBody,decision_reason:'',idempotency_key:`${RUN}_noreason`}); assert.equal(out.json.status,'REJECTED_INVALID_INPUT');
  await cleanup(pool); console.log('ACCEPTANCE_RECOMMENDATION_APPROVAL_DECISION_RUNTIME_V1 passed');
 } finally{ await pool.end(); }})().catch(e=>{console.error(e); process.exit(1)});
