#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const AUTH=JSON.parse(fs.readFileSync(path.join(ROOT,'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-ENVIROWEATHER-METEOGRAM-SOURCE-QUALIFICATION-V1.json'),'utf8'));
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA4_ENVIROWEATHER_METEOGRAM_SOURCE_QUALIFICATION_RESULT.json');
const SUBJECT_SHA=process.env.MCFT_SUBJECT_SHA||'';
const PRIVATE_ROOT=fs.mkdtempSync(path.join(os.tmpdir(),'mcft-cap09-ea4-ew-meteogram-'));
const sha256=(input)=>`sha256:${crypto.createHash('sha256').update(input).digest('hex')}`;
const requireCondition=(ok,code)=>{if(!ok)throw new Error(code)};
const write=(value)=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,`${JSON.stringify(value,null,2)}\n`,'utf8')};
const text=(value)=>String(value??'').trim();

function directUrl(){const now=new Date(),date=`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,'0')}-${String(now.getUTCDate()).padStart(2,'0')}`,url=new URL(AUTH.provider_binding_candidate.source_page);url.searchParams.set('duration','24');url.searchParams.set('run','1');url.searchParams.set('selectDate',date);url.searchParams.set('selectedStation','kbs');url.searchParams.set('units','us');return url.toString()}
function finite(value){if(value===null||value===undefined||text(value)==='')return null;const raw=text(value).replace(/,/g,'');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw))return null;const n=Number(raw);return Number.isFinite(n)?n:null}
function timestampClass(raw){const v=text(raw);if(/Z$/i.test(v))return'EXPLICIT_Z';if(/[+-]\d{2}:?\d{2}$/.test(v))return'EXPLICIT_OFFSET';if(/^\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}/.test(v)||/^\d{1,2}\/\d{1,2}\/\d{4}\s+\d{1,2}:\d{2}/.test(v))return'NAIVE_DATE_TIME';return'UNKNOWN'}
function naiveUtc(raw){const v=text(raw);let m=v.match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?/);if(m)return Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+(m[6]||0));m=v.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2})(?::(\d{2}))?/);if(m)return Date.UTC(+m[3],+m[1]-1,+m[2],+m[4],+m[5],+(m[6]||0));return null}
function tzOffset(utcMs,timeZone){const parts=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(utcMs)),map=Object.fromEntries(parts.filter((x)=>x.type!=='literal').map((x)=>[x.type,x.value]));return Date.UTC(+map.year,+map.month-1,+map.day,+map.hour,+map.minute,+map.second)-utcMs}
function naiveDetroit(raw){const n=naiveUtc(raw);if(n===null)return null;let guess=n;for(let i=0;i<2;i+=1)guess=n-tzOffset(guess,'America/Detroit');return guess}
function chooseParser(rows){const classes=[...new Set(rows.map((row)=>timestampClass(row.datetime)))];if(classes.every((x)=>['EXPLICIT_Z','EXPLICIT_OFFSET'].includes(x)))return{class:'PROVIDER_EXPLICIT_OFFSET',parse:(raw)=>{const ms=Date.parse(text(raw));return Number.isFinite(ms)?ms:null}};if(classes.length===1&&classes[0]==='NAIVE_DATE_TIME')return{class:'PROVIDER_NAIVE_REQUIRES_AMERICA_DETROIT_BINDING',parse:naiveDetroit};return{class:`UNRESOLVED_MIXED:${classes.join(',')}`,parse:()=>null}}
function retainBeforeParse(body,identity){const digest=sha256(body),file=path.join(PRIVATE_ROOT,`${crypto.createHash('sha256').update(identity).digest('hex')}.raw`);fs.writeFileSync(file,body);const reread=fs.readFileSync(file);requireCondition(sha256(reread)===digest,'EA4EW_RAW_RETENTION_DIGEST_MISMATCH');requireCondition(reread.length===body.length,'EA4EW_RAW_RETENTION_BYTE_MISMATCH');return{sha256:digest,bytes:body.length,private_retention_verified:true,raw_body_uploaded:false}}
function safeHeader(entry){if(!entry||typeof entry!=='object')return null;const allowed=['name','header','extraText','formatIn','type','displayIn'];return Object.fromEntries(allowed.filter((key)=>entry[key]!==undefined).map((key)=>[key,typeof entry[key]==='string'?entry[key].slice(0,200):entry[key]]))}
function gapStats(times){const sorted=[...new Set(times)].sort((a,b)=>a-b),gaps=[];for(let i=1;i<sorted.length;i+=1)gaps.push((sorted[i]-sorted[i-1])/60000);return{distinct_count:sorted.length,min_gap_minutes:gaps.length?Math.min(...gaps):null,max_gap_minutes:gaps.length?Math.max(...gaps):null,all_gaps_5m:gaps.length>0&&gaps.every((x)=>Math.abs(x-5)<1e-9),all_gaps_60m:gaps.length>0&&gaps.every((x)=>Math.abs(x-60)<1e-9)}}
function fieldSummary(rows,field){const raw=rows.map((x)=>x[field]),nonnull=raw.filter((x)=>x!==null&&x!==undefined&&text(x)!==''),numeric=nonnull.map(finite).filter((x)=>x!==null);return{row_count:rows.length,nonnull_count:nonnull.length,numeric_count:numeric.length,null_or_empty_count:rows.length-nonnull.length,non_numeric_nonempty_count:nonnull.length-numeric.length,value_type_set:[...new Set(nonnull.map((x)=>typeof x))].sort()}}
function estimated(metadata,family,field){return Boolean(metadata?.EstimatedData?.[family]?.[field])}
function invalidSummary(metadata,family,field){const node=metadata?.InvalidData?.[family]?.[field],list=Array.isArray(node?.list)?node.list:[];return{present:Boolean(node),entry_count:list.length,list_sha256:sha256(Buffer.from(JSON.stringify(list)))}}
function invalidOverlap(metadata,family,field,start,end){if(!Number.isFinite(start)||!Number.isFinite(end))return null;const list=metadata?.InvalidData?.[family]?.[field]?.list;if(!Array.isArray(list))return 0;const tokens=new Set();for(let t=start;t<=end;t+=86400000){const d=new Date(t),y=d.getUTCFullYear(),m=String(d.getUTCMonth()+1).padStart(2,'0'),day=String(d.getUTCDate()).padStart(2,'0');for(const token of[`${y}-${m}-${day}`,`${m}/${day}/${y}`,`${+m}/${+day}/${y}`])tokens.add(token)}return list.filter((entry)=>[...tokens].some((token)=>String(entry).includes(token))).length}
function termsTokens(value){const lower=value.toLowerCase(),keys=['data','use','copyright','permission','commercial','redistribut','warranty','liability','research','education'];return Object.fromEntries(keys.map((key)=>[key,lower.includes(key)]))}

let browser;
const result={schema_version:'geox_mcft_cap09_ea4_enviroweather_meteogram_source_qualification_result_v1',status:'FAIL',subject_sha:SUBJECT_SHA||null,database_write_count:0,formal_evidence_write_count:0,public_raw_numeric_value_emission_count:0,raw_body_uploaded:false,source_substitution_authorized:false,ea5_authorized:false};
try{
 requireCondition(/^[0-9a-f]{40}$/.test(SUBJECT_SHA),'EA4EW_EXACT_SUBJECT_SHA_REQUIRED');browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'en-US',timezoneId:'UTC',acceptDownloads:false}),page=await context.newPage();let captured=null;
 const tasks=[];page.on('response',(response)=>{const task=(async()=>{const url=new URL(response.url());if(url.hostname!==AUTH.provider_binding_candidate.api_host||url.pathname!==AUTH.provider_binding_candidate.api_path||response.status()!==200)return;if(!AUTH.provider_binding_candidate.required_query_keys.every((key)=>text(url.searchParams.get(key))))return;const body=await response.body(),receipt=retainBeforeParse(body,`${url.hostname}${url.pathname}|${url.search}`),parsed=JSON.parse(body.toString('utf8')),rows=parsed?.data?.Table;if(!Array.isArray(rows)||rows.length<2)return;if(!captured||body.length>captured.body_bytes)captured={url,parsed,receipt,body_bytes:body.length}})();tasks.push(task);task.catch(()=>{})});
 const pageResponse=await page.goto(directUrl(),{waitUntil:'domcontentloaded',timeout:60000});requireCondition(pageResponse&&pageResponse.status()>=200&&pageResponse.status()<400,'EA4EW_SOURCE_PAGE_FAILED');await page.waitForTimeout(18000);await Promise.allSettled(tasks);requireCondition(captured,'EA4EW_NO_COMPLETE_RUN_RESPONSE');
 const{url,parsed,receipt}=captured,query=Object.fromEntries(AUTH.provider_binding_candidate.required_query_keys.map((key)=>[key,url.searchParams.get(key)]));requireCondition(query.selectedStation==='kbs'&&query.duration==='24','EA4EW_QUERY_SCOPE_DRIFT');const stationText=JSON.stringify(parsed?.metadata?.Station??parsed?.metadata??'').toLowerCase();requireCondition(AUTH.provider_binding_candidate.station_identity_patterns.some((value)=>stationText.includes(value.toLowerCase())),'EA4EW_STATION_IDENTITY_NOT_PROVEN');
 const rows=parsed.data.Table,headers=Array.isArray(parsed?.data?.TableHeaders)?parsed.data.TableHeaders:[],rainHeader=headers.find((x)=>x?.name===AUTH.provider_binding_candidate.rain_field),solarHeader=headers.find((x)=>x?.name===AUTH.provider_binding_candidate.solar_field);requireCondition(rainHeader&&solarHeader,'EA4EW_TARGET_HEADER_METADATA_REQUIRED');
 const parser=chooseParser(rows),parsedRows=rows.map((row)=>({row,time:parser.parse(row.datetime)})),timestampParsedCount=parsedRows.filter((x)=>Number.isFinite(x.time)).length,timestampClasses=[...new Set(rows.map((row)=>timestampClass(row.datetime)))];
 const violations=[];if(timestampParsedCount!==rows.length)violations.push(`TIMESTAMP_PARSE_COUNT:${timestampParsedCount}/${rows.length}`);if(parser.class==='PROVIDER_NAIVE_REQUIRES_AMERICA_DETROIT_BINDING')violations.push('TIMESTAMP_TIMEZONE_AUTHORITY_REQUIRES_AMENDMENT_BINDING');if(parser.class.startsWith('UNRESOLVED_'))violations.push(parser.class);
 const validRows=parsedRows.filter((x)=>Number.isFinite(x.time)),now=Date.now(),forecastRaw=parsed?.data?.DD_forecastDate,forecastBoundary=forecastRaw?parser.parse(forecastRaw):null,observedUpper=Number.isFinite(forecastBoundary)?Math.min(now+5*60000,forecastBoundary-1):now+5*60000,observedRows=validRows.filter((x)=>x.time<=observedUpper);
 const rainField=fieldSummary(observedRows.map((x)=>x.row),'pcpn_us'),solarField=fieldSummary(observedRows.map((x)=>x.row),'srad_hourly_standard');const rain=observedRows.map((x)=>({time:x.time,value:finite(x.row.pcpn_us)})).filter((x)=>x.value!==null),solar=observedRows.map((x)=>({time:x.time,value:finite(x.row.srad_hourly_standard)})).filter((x)=>x.value!==null);
 if(rain.length===0)violations.push('RAIN_NO_NUMERIC_VALUES');if(solar.length===0)violations.push('SOLAR_NO_NUMERIC_VALUES');if(rain.some((x)=>x.value<0))violations.push('RAIN_NEGATIVE_VALUE');if(solar.some((x)=>x.value<0))violations.push('SOLAR_NEGATIVE_VALUE');
 const commonEnd=rain.length&&solar.length?Math.min(Math.max(...rain.map((x)=>x.time)),Math.max(...solar.map((x)=>x.time))):null,windowStart=Number.isFinite(commonEnd)?commonEnd-24*3600000:null,rainWindow=Number.isFinite(commonEnd)?rain.filter((x)=>x.time>=windowStart&&x.time<=commonEnd):[],solarWindow=Number.isFinite(commonEnd)?solar.filter((x)=>x.time>=windowStart&&x.time<=commonEnd):[],rainGrid=gapStats(rainWindow.map((x)=>x.time)),solarGrid=gapStats(solarWindow.map((x)=>x.time)),latestAge=Number.isFinite(commonEnd)?(now-commonEnd)/3600000:null;
 const rainEstimated=estimated(parsed.metadata,'fivemin','pcpn')||estimated(parsed.metadata,'hourly','pcpn'),solarEstimated=estimated(parsed.metadata,'hourly','srad'),rainInvalid=invalidSummary(parsed.metadata,'fivemin','pcpn'),solarInvalid=invalidSummary(parsed.metadata,'hourly','srad'),rainInvalidOverlap=invalidOverlap(parsed.metadata,'fivemin','pcpn',windowStart,commonEnd),solarInvalidOverlap=invalidOverlap(parsed.metadata,'hourly','srad',windowStart,commonEnd);
 if(rainEstimated)violations.push('RAIN_PROVIDER_ESTIMATED');if(solarEstimated)violations.push('SOLAR_PROVIDER_ESTIMATED');if(Number.isFinite(latestAge)&&(latestAge<-.1||latestAge>AUTH.technical_qualification_requirements.latest_observed_target_max_age_hours))violations.push(`LATEST_TARGET_AGE_HOURS:${latestAge.toFixed(3)}`);if(Number.isFinite(commonEnd)){if(!rainGrid.all_gaps_5m||rainGrid.distinct_count<289)violations.push(`RAIN_24H_GRID:${JSON.stringify(rainGrid)}`);if(!solarGrid.all_gaps_60m||solarGrid.distinct_count<25)violations.push(`SOLAR_24H_GRID:${JSON.stringify(solarGrid)}`);if(rainInvalidOverlap>0)violations.push(`RAIN_INVALID_METADATA_OVERLAP:${rainInvalidOverlap}`);if(solarInvalidOverlap>0)violations.push(`SOLAR_INVALID_METADATA_OVERLAP:${solarInvalidOverlap}`)}else violations.push('COMMON_24H_TARGET_WINDOW_UNAVAILABLE');
 let terms={link_found:false,url:null,response_status:null,sha256:null,bytes:null,semantic_tokens:{},public_raw_redistribution_authorized:false,commercial_reuse_rights_established:false,legal_opinion_claimed:false};const termsLink=page.getByRole('link',{name:/Terms of Agreement/i}).first();if(await termsLink.count()){const href=await termsLink.getAttribute('href');if(href){const termsUrl=new URL(href,AUTH.provider_binding_candidate.source_page).toString(),resp=await context.request.get(termsUrl,{timeout:30000}),body=await resp.text(),final=new URL(resp.url());terms={link_found:true,url:final.origin+final.pathname,response_status:resp.status(),sha256:sha256(Buffer.from(body)),bytes:Buffer.byteLength(body),semantic_tokens:termsTokens(body),public_raw_redistribution_authorized:false,commercial_reuse_rights_established:false,legal_opinion_claimed:false}}}if(!terms.link_found||terms.response_status!==200)violations.push('TERMS_PAGE_NOT_REPROVED');
 const qualified=violations.length===0;Object.assign(result,{status:'PASS',qualification_status:qualified?'QUALIFIED':'REJECTED',decision:qualified?AUTH.live_qualification.success_decision:AUTH.live_qualification.failure_decision,probe_observed_at_utc:new Date(now).toISOString(),source_identity:{host:url.hostname,path:url.pathname,method:'GET',duration:query.duration,selectedStation:query.selectedStation,resultModelCode:query.resultModelCode,resultModelId:query.resultModelId,stationCode:query.stationCode,stationId:query.stationId,stationType:query.stationType,units:query.units,query_key_names:AUTH.provider_binding_candidate.required_query_keys},raw_retention:receipt,station_identity_proven:true,table:{row_count:rows.length,timestamp_policy:parser.class,timestamp_format_classes:timestampClasses,timestamp_parsed_count:timestampParsedCount,forecast_boundary_present:Number.isFinite(forecastBoundary),forecast_boundary_utc:Number.isFinite(forecastBoundary)?new Date(forecastBoundary).toISOString():null},header_metadata:{rain:safeHeader(rainHeader),solar:safeHeader(solarHeader)},field_diagnostics:{rain:rainField,solar:solarField},observed_candidate:{common_end_utc:Number.isFinite(commonEnd)?new Date(commonEnd).toISOString():null,window_start_utc:Number.isFinite(windowStart)?new Date(windowStart).toISOString():null,latest_target_age_hours:Number.isFinite(latestAge)?Number(latestAge.toFixed(3)):null,rain:{numeric_count_24h:rainWindow.length,grid:rainGrid,sequence_sha256:rainWindow.length?sha256(Buffer.from(JSON.stringify(rainWindow.map((x)=>[new Date(x.time).toISOString(),String(x.value)])))):null,estimated_by_provider:rainEstimated,invalid_metadata:rainInvalid,invalid_window_overlap_count:rainInvalidOverlap},solar:{numeric_count_24h:solarWindow.length,grid:solarGrid,sequence_sha256:solarWindow.length?sha256(Buffer.from(JSON.stringify(solarWindow.map((x)=>[new Date(x.time).toISOString(),String(x.value)])))):null,estimated_by_provider:solarEstimated,invalid_metadata:solarInvalid,invalid_window_overlap_count:solarInvalidOverlap}},terms,violations,source_substitution_authorized:false,source_architecture_amendment_required:true,ea5_authorized:false,database_write_count:0,formal_evidence_write_count:0,public_raw_numeric_value_emission_count:0,raw_body_uploaded:false});write(result);console.log(JSON.stringify({status:'PASS',qualification_status:result.qualification_status,decision:result.decision,field_diagnostics:result.field_diagnostics,age_hours:result.observed_candidate.latest_target_age_hours,rain_grid:rainGrid,solar_grid:solarGrid,violations},null,2));await context.close();
}catch(error){result.error=`${error.name||'Error'}:${error.message||String(error)}`;write(result);console.error(result.error);process.exitCode=1}finally{await browser?.close()}
