#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const CONFIG=JSON.parse(fs.readFileSync(path.join(ROOT,'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-LATEST-OBSERVATIONS-SOLAR-DISCOVERY-V1.json'),'utf8'));
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA4_LATEST_OBSERVATIONS_SOLAR_DISCOVERY_RESULT.json'),SUBJECT_SHA=process.env.MCFT_SUBJECT_SHA||'';
const sha256=(input)=>`sha256:${crypto.createHash('sha256').update(input).digest('hex')}`,normalize=(v)=>String(v||'').toLowerCase().replace(/[^a-z0-9%/+.-]+/g,' ').replace(/\s+/g,' ').trim(),write=(v)=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,`${JSON.stringify(v,null,2)}\n`,'utf8')};
function reqIdentity(request,phase){const u=new URL(request.url()),keys=[...new Set([...u.searchParams.keys()])].sort();return{phase,host:u.hostname,path:u.pathname,method:request.method(),query_key_names:keys,query_value_presence:Object.fromEntries(keys.map((k)=>[k,(u.searchParams.get(k)||'').trim()?'NONEMPTY':'EMPTY'])),query_values_emitted:false,canonical_request_identity_sha256:sha256(`${request.method()} ${request.url()}`)}}
function schema(json){const paths=new Set(),tokens=new Set(),shapes=new Set(),lex=CONFIG.approved_metadata_lexicon.map(normalize),add=(x)=>{const n=normalize(x);for(const t of lex)if(n.includes(t))tokens.add(t)};function scan(v,p,d=0){if(d>14)return;const name=p.join('.')||'$';if(Array.isArray(v)){const f=v[0],kind=Array.isArray(f)?`array:${f.length}`:f===null?'null':typeof f;shapes.add(`${name}|len=${v.length}|item=${kind}`);for(let i=0;i<Math.min(v.length,80);i++)scan(v[i],[...p,'[]'],d+1);return}if(v&&typeof v==='object'){for(const[k,c]of Object.entries(v)){paths.add([...p,k].join('.'));add(k);scan(c,[...p,k],d+1)}return}if(typeof v==='string'){add(v);const t=v.trim();if(t.length>1&&t.length<5_000_000&&/^[\[{]/.test(t)){try{paths.add(`${name}.<embedded_json>`);scan(JSON.parse(t),[...p,'<embedded_json>'],d+1)}catch{}}if(/<(?:table|tr|th|td)\b/i.test(v)){paths.add(`${name}.<embedded_html_table>`);add(v.replace(/<[^>]+>/g,' '))}}}scan(json,[]);return{root_kind:Array.isArray(json)?'array':json===null?'null':typeof json,schema_key_paths:[...paths].sort().slice(0,420),array_shapes:[...shapes].sort().slice(0,220),approved_metadata_tokens:[...tokens].sort(),raw_numeric_observation_values_emitted:false,unfiltered_string_values_emitted:false}}
function signals(e){const corpus=normalize([e.request.path,...(e.schema?.schema_key_paths||[]),...(e.schema?.approved_metadata_tokens||[])].join(' ')),has=(p)=>p.some((x)=>corpus.includes(normalize(x)));return{solar:has(CONFIG.capability_patterns.solar),hourly:has(CONFIG.capability_patterns.hourly),subhourly:has(CONFIG.capability_patterns.subhourly),observed:has(CONFIG.capability_patterns.observed),estimated:has(CONFIG.capability_patterns.estimated),invalid:has(CONFIG.capability_patterns.invalid)}}
async function selectKbs(page){const selects=page.locator('select');for(let i=0;i<await selects.count();i++){const s=selects.nth(i),opts=await s.locator('option').evaluateAll((nodes)=>nodes.map((n)=>({value:n.value,text:n.textContent||''}))),match=opts.find((o)=>normalize(o.value)==='kbs'||/hickory corners|kellogg biological|\bkbs\b/i.test(o.text));if(match){await s.selectOption(match.value);await page.waitForTimeout(6000);return{found:true,method:'native_select'}}}return{found:false,method:null}}
let browser,phase='initial';const evidence=new Map(),tasks=[];
try{
 if(!/^[0-9a-f]{40}$/.test(SUBJECT_SHA))throw new Error('EA4LO_EXACT_SUBJECT_SHA_REQUIRED');browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'en-US',timezoneId:'UTC',acceptDownloads:false}),page=await context.newPage();page.on('response',(response)=>{const task=(async()=>{let u;try{u=new URL(response.url())}catch{return}if(!CONFIG.allowed_response_hosts.includes(u.hostname))return;const ct=String(response.headers()['content-type']||'').toLowerCase();if(!ct.includes('json'))return;const r=reqIdentity(response.request(),phase),key=`${r.phase}|${r.host}|${r.path}|${r.method}|${r.query_key_names.join(',')}`,body=await response.body();let parsed=null,parse_status='JSON_CONTENT_TYPE_NON_JSON_BODY';try{parsed=schema(JSON.parse(body.toString('utf8')));parse_status='JSON_PARSED'}catch{}const e={request:r,response_status:response.status(),content_type:ct.split(';')[0],response_body_sha256:sha256(body),response_bytes:body.length,parse_status,schema:parsed,raw_body_persisted:false,raw_numeric_observation_values_emitted:false};e.capability_signals=signals(e);evidence.set(key,e)})();tasks.push(task);task.catch(()=>{})});
 const response=await page.goto(CONFIG.source_page,{waitUntil:'domcontentloaded',timeout:60000});if(!response||response.status()<200||response.status()>=400)throw new Error('EA4LO_SOURCE_PAGE_FAILED');await page.waitForTimeout(10000);const selection=await selectKbs(page);phase='kbs_selected';if(selection.found)await page.waitForTimeout(10000);await Promise.allSettled(tasks);
 const responses=[...evidence.values()].sort((a,b)=>`${a.request.phase}|${a.request.host}|${a.request.path}`.localeCompare(`${b.request.phase}|${b.request.host}|${b.request.path}`)),api=responses.filter((x)=>x.request.host==='api.enviroweather.msu.edu'),solar=api.filter((x)=>x.capability_signals.solar);
 if(!api.length)throw new Error('EA4LO_NO_FIRST_PARTY_API_RESPONSE');const result={schema_version:'geox_mcft_cap09_ea4_latest_observations_solar_discovery_result_v1',status:'PASS',subject_sha:SUBJECT_SHA,source_page:CONFIG.source_page,target_station_slug:'kbs',kbs_selection:selection,retrieved_at:new Date().toISOString(),first_party_json_response_count:responses.length,api_response_count:api.length,responses,capability_summary:{solar_candidate_endpoint_count:solar.length,solar_signal_present:solar.length>0,hourly_signal_present:api.some((x)=>x.capability_signals.hourly),subhourly_signal_present:api.some((x)=>x.capability_signals.subhourly),observed_signal_present:api.some((x)=>x.capability_signals.observed),estimated_signal_present:api.some((x)=>x.capability_signals.estimated),invalid_or_qc_signal_present:api.some((x)=>x.capability_signals.invalid)},discovery_creates_solar_source_authority:false,solar_qualified:false,query_values_emitted:false,raw_numeric_observation_values_emitted:false,raw_response_body_persisted:false,rendered_dom_persisted:false,download_clicked:false,database_write_count:0,formal_evidence_write_count:0,formal_window_started:false,ea5_authorized:false};write(result);console.log(JSON.stringify({status:'PASS',api:api.length,selection,capability_summary:result.capability_summary},null,2));await context.close();
}catch(error){write({schema_version:'geox_mcft_cap09_ea4_latest_observations_solar_discovery_result_v1',status:'FAIL',subject_sha:SUBJECT_SHA,error:error instanceof Error?error.message:String(error),query_values_emitted:false,raw_numeric_observation_values_emitted:false,raw_response_body_persisted:false,database_write_count:0,formal_evidence_write_count:0,formal_window_started:false});console.error(`EA4LO_FAIL:${error instanceof Error?error.message:String(error)}`);process.exitCode=1}finally{await browser?.close()}
