#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';

const ROOT=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const AUTH=JSON.parse(fs.readFileSync(path.join(ROOT,'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-ENVIROWEATHER-RAIN-ONLY-QUALIFICATION-V1.json'),'utf8'));
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA4_ENVIROWEATHER_RAIN_ONLY_QUALIFICATION_RESULT.json');
const SUBJECT_SHA=process.env.MCFT_SUBJECT_SHA||'';
const PRIVATE_ROOT=fs.mkdtempSync(path.join(os.tmpdir(),'mcft-cap09-ew-rain-'));
const sha256=(input)=>`sha256:${crypto.createHash('sha256').update(input).digest('hex')}`;
const requireCondition=(ok,code)=>{if(!ok)throw new Error(code)};
const text=(v)=>String(v??'').trim();
const write=(value)=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,`${JSON.stringify(value,null,2)}\n`,'utf8')};

function directUrl(){const now=new Date(),date=`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,'0')}-${String(now.getUTCDate()).padStart(2,'0')}`,url=new URL(AUTH.source_candidate.source_page);url.searchParams.set('duration','24');url.searchParams.set('run','1');url.searchParams.set('selectDate',date);url.searchParams.set('selectedStation','kbs');url.searchParams.set('units','us');return url.toString()}
function finite(v){if(v===null||v===undefined||text(v)==='')return null;const raw=text(v).replace(/,/g,'');if(!/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(raw))return null;const n=Number(raw);return Number.isFinite(n)?n:null}
function naiveUtc(raw){const v=text(raw);let m=v.match(/^(\d{4})-(\d{2})-(\d{2})[ T](\d{2}):(\d{2})(?::(\d{2}))?/);if(m)return Date.UTC(+m[1],+m[2]-1,+m[3],+m[4],+m[5],+(m[6]||0));m=v.match(/^(\d{1,2})\/(\d{1,2})\/(\d{4})\s+(\d{1,2}):(\d{2})(?::(\d{2}))?/);if(m)return Date.UTC(+m[3],+m[1]-1,+m[2],+m[4],+m[5],+(m[6]||0));return null}
function tzOffset(utcMs,timeZone){const p=new Intl.DateTimeFormat('en-US',{timeZone,year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hourCycle:'h23'}).formatToParts(new Date(utcMs)),m=Object.fromEntries(p.filter((x)=>x.type!=='literal').map((x)=>[x.type,x.value]));return Date.UTC(+m.year,+m.month-1,+m.day,+m.hour,+m.minute,+m.second)-utcMs}
function parseCandidateDetroit(raw){const n=naiveUtc(raw);if(n===null)return null;let guess=n;for(let i=0;i<2;i++)guess=n-tzOffset(guess,'America/Detroit');return guess}
function retainBeforeParse(body,identity){const digest=sha256(body),file=path.join(PRIVATE_ROOT,`${crypto.createHash('sha256').update(identity).digest('hex')}.raw`);fs.writeFileSync(file,body);const reread=fs.readFileSync(file);requireCondition(sha256(reread)===digest,'EA4RAIN_RAW_RETENTION_DIGEST_MISMATCH');requireCondition(reread.length===body.length,'EA4RAIN_RAW_RETENTION_BYTES_MISMATCH');return{sha256:digest,bytes:body.length,private_retention_verified:true,raw_body_uploaded:false}}
function gapStats(times){const sorted=[...new Set(times)].sort((a,b)=>a-b),gaps=[];for(let i=1;i<sorted.length;i++)gaps.push((sorted[i]-sorted[i-1])/60000);return{distinct_count:sorted.length,min_gap_minutes:gaps.length?Math.min(...gaps):null,max_gap_minutes:gaps.length?Math.max(...gaps):null,all_gaps_5m:gaps.length>0&&gaps.every((x)=>Math.abs(x-5)<1e-9)}}
function safeHeader(h){if(!h||typeof h!=='object')return null;const keys=['name','header','extraText','formatIn','type','displayIn'];return Object.fromEntries(keys.filter((k)=>h[k]!==undefined).map((k)=>[k,typeof h[k]==='string'?h[k].slice(0,200):h[k]]))}
function estimated(metadata){return Boolean(metadata?.EstimatedData?.fivemin?.pcpn)||Boolean(metadata?.EstimatedData?.hourly?.pcpn)}
function invalidList(metadata){const list=metadata?.InvalidData?.fivemin?.pcpn?.list;return Array.isArray(list)?list:[]}
function dateTokens(ms){const d=new Date(ms),y=d.getUTCFullYear(),m=String(d.getUTCMonth()+1).padStart(2,'0'),day=String(d.getUTCDate()).padStart(2,'0');return[`${y}-${m}-${day}`,`${m}/${day}/${y}`,`${+m}/${+day}/${y}`]}
function invalidOverlap(list,start,end){const tokens=new Set();for(let t=start;t<=end;t+=86400000)for(const token of dateTokens(t))tokens.add(token);return list.filter((entry)=>[...tokens].some((token)=>String(entry).includes(token))).length}
function termsTokens(body){const lower=body.toLowerCase(),keys=['data','use','copyright','permission','commercial','redistribut','warranty','liability','research','education'];return Object.fromEntries(keys.map((k)=>[k,lower.includes(k)]))}

let browser;
const result={schema_version:'geox_mcft_cap09_ea4_enviroweather_rain_only_qualification_result_v1',status:'FAIL',subject_sha:SUBJECT_SHA||null,database_write_count:0,formal_evidence_write_count:0,public_raw_numeric_value_emission_count:0,raw_body_uploaded:false,source_substitution_authorized:false,ea5_authorized:false};
try{
 requireCondition(/^[0-9a-f]{40}$/.test(SUBJECT_SHA),'EA4RAIN_EXACT_SUBJECT_SHA_REQUIRED');browser=await chromium.launch({headless:true});const context=await browser.newContext({locale:'en-US',timezoneId:'UTC',acceptDownloads:false}),page=await context.newPage();let captured=null;const tasks=[];
 page.on('response',(response)=>{const task=(async()=>{const url=new URL(response.url());if(url.hostname!==AUTH.source_candidate.api_host||url.pathname!==AUTH.source_candidate.api_path||response.status()!==200)return;const required=['duration','resultModelCode','resultModelId','selectDate','selectedStation','stationCode','stationId','stationType','units'];if(!required.every((key)=>text(url.searchParams.get(key))))return;const body=await response.body(),receipt=retainBeforeParse(body,`${url.hostname}${url.pathname}|${url.search}`),parsed=JSON.parse(body.toString('utf8')),rows=parsed?.data?.Table;if(!Array.isArray(rows)||rows.length<2)return;if(!captured||body.length>captured.body_bytes)captured={url,parsed,receipt,body_bytes:body.length}})();tasks.push(task);task.catch(()=>{})});
 const pageResponse=await page.goto(directUrl(),{waitUntil:'domcontentloaded',timeout:60000});requireCondition(pageResponse&&pageResponse.status()>=200&&pageResponse.status()<400,'EA4RAIN_SOURCE_PAGE_FAILED');await page.waitForTimeout(18000);await Promise.allSettled(tasks);requireCondition(captured,'EA4RAIN_NO_COMPLETE_RUN_RESPONSE');
 const{url,parsed,receipt}=captured,rows=parsed.data.Table,headers=Array.isArray(parsed?.data?.TableHeaders)?parsed.data.TableHeaders:[],header=headers.find((x)=>x?.name==='pcpn_us');requireCondition(header,'EA4RAIN_HEADER_REQUIRED');const headerSafe=safeHeader(header);requireCondition(/\bin\.?\b/i.test(String(headerSafe.extraText||'').replace(/&nbsp;/gi,' ')),'EA4RAIN_PROVIDER_UNIT_NOT_INCH');
 requireCondition(url.searchParams.get('selectedStation')==='kbs'&&url.searchParams.get('stationCode')==='kbs'&&url.searchParams.get('stationId')==='61'&&url.searchParams.get('resultModelCode')==='meteogram'&&url.searchParams.get('resultModelId')==='101','EA4RAIN_SOURCE_IDENTITY_DRIFT');const stationText=JSON.stringify(parsed?.metadata?.Station??parsed?.metadata??'').toLowerCase();requireCondition(['hickory corners','kellogg','kbs'].some((x)=>stationText.includes(x)),'EA4RAIN_STATION_IDENTITY_NOT_PROVEN');
 const parsedRows=rows.map((row)=>({row,time:parseCandidateDetroit(row.datetime)}));requireCondition(parsedRows.every((x)=>Number.isFinite(x.time)),'EA4RAIN_NAIVE_TIMESTAMP_PARSE_FAILED');const now=Date.now(),forecastRaw=parsed?.data?.DD_forecastDate,forecastBoundary=forecastRaw?parseCandidateDetroit(forecastRaw):null,observedUpper=Number.isFinite(forecastBoundary)?Math.min(now+5*60000,forecastBoundary-1):now+5*60000,observed=parsedRows.filter((x)=>x.time<=observedUpper),rain=observed.map((x)=>({time:x.time,value:finite(x.row.pcpn_us)})).filter((x)=>x.value!==null);
 const violations=[];if(rain.length===0)violations.push('RAIN_NO_NUMERIC_VALUES');if(rain.some((x)=>x.value<0))violations.push('RAIN_NEGATIVE_VALUE');const latest=rain.length?Math.max(...rain.map((x)=>x.time)):null,windowStart=Number.isFinite(latest)?latest-24*3600000:null,window=Number.isFinite(latest)?rain.filter((x)=>x.time>=windowStart&&x.time<=latest):[],grid=gapStats(window.map((x)=>x.time)),age=Number.isFinite(latest)?(now-latest)/3600000:null;
 if(!Number.isFinite(age)||age<-.1||age>AUTH.qualification_requirements.latest_observed_max_age_hours)violations.push(`LATEST_OBSERVED_RAIN_AGE_HOURS:${Number.isFinite(age)?age.toFixed(3):'NA'}`);if(grid.distinct_count!==AUTH.qualification_requirements.rain_24h_distinct_points_required||!grid.all_gaps_5m)violations.push(`RAIN_24H_GRID:${JSON.stringify(grid)}`);const providerEstimated=estimated(parsed.metadata);if(providerEstimated)violations.push('RAIN_PROVIDER_ESTIMATED');const invalid=invalidList(parsed.metadata),overlap=Number.isFinite(windowStart)&&Number.isFinite(latest)?invalidOverlap(invalid,windowStart,latest):null;if(overlap!==0)violations.push(`RAIN_INVALID_METADATA_OVERLAP:${overlap}`);
 const converted=window.map((x)=>[new Date(x.time).toISOString(),Number((x.value*AUTH.source_candidate.conversion_factor).toFixed(12))]),convertedHash=converted.length?sha256(Buffer.from(JSON.stringify(converted))):null,sourceHash=window.length?sha256(Buffer.from(JSON.stringify(window.map((x)=>[new Date(x.time).toISOString(),String(x.value)])))):null;
 let terms={response_status:null,sha256:null,bytes:null,public_raw_redistribution_authorized:false,commercial_reuse_rights_established:false,legal_opinion_claimed:false};const termsResponse=await context.request.get(AUTH.use_policy_boundary.terms_page,{timeout:30000});const termsBody=await termsResponse.text();terms={response_status:termsResponse.status(),sha256:sha256(Buffer.from(termsBody)),bytes:Buffer.byteLength(termsBody),semantic_tokens:termsTokens(termsBody),public_raw_redistribution_authorized:false,commercial_reuse_rights_established:false,legal_opinion_claimed:false};if(terms.response_status!==200)violations.push('TERMS_PAGE_NOT_REPROVED');
 const technicallyPass=violations.length===0;Object.assign(result,{status:'PASS',qualification_status:technicallyPass?'TECHNICALLY_QUALIFIED_PENDING_TIMEZONE_BINDING':'REJECTED',decision:technicallyPass?AUTH.adjudication.pass_decision:AUTH.adjudication.reject_decision,probe_observed_at_utc:new Date(now).toISOString(),source_identity:{host:url.hostname,path:url.pathname,method:'GET',selectedStation:url.searchParams.get('selectedStation'),stationCode:url.searchParams.get('stationCode'),stationId:url.searchParams.get('stationId'),resultModelCode:url.searchParams.get('resultModelCode'),resultModelId:url.searchParams.get('resultModelId'),duration:url.searchParams.get('duration'),units:url.searchParams.get('units')},raw_retention:receipt,station_identity_proven:true,header_metadata:headerSafe,timestamp_policy:{provider_class:'NAIVE_DATE_TIME',candidate_timezone:'America/Detroit',candidate_timezone_is_authority:false,explicit_timezone_binding_required:true,silent_utc_interpretation_performed:false},forecast_boundary_candidate_utc:Number.isFinite(forecastBoundary)?new Date(forecastBoundary).toISOString():null,rain_candidate:{row_count:rows.length,observed_numeric_count:rain.length,window_start_candidate_utc:Number.isFinite(windowStart)?new Date(windowStart).toISOString():null,window_end_candidate_utc:Number.isFinite(latest)?new Date(latest).toISOString():null,latest_observed_age_hours:Number.isFinite(age)?Number(age.toFixed(3)):null,grid,provider_estimated:providerEstimated,invalid_metadata_entry_count:invalid.length,invalid_metadata_sha256:sha256(Buffer.from(JSON.stringify(invalid))),invalid_window_overlap_count:overlap,source_sequence_sha256:sourceHash,canonical_mm_sequence_sha256:convertedHash,conversion_rule_id:AUTH.source_candidate.conversion_rule_id,conversion_factor:AUTH.source_candidate.conversion_factor,missing_rain_treated_as_zero:false,silent_imputation_performed:false,negative_clipping_performed:false},terms,violations,source_substitution_authorized:false,timezone_authority_created:false,source_architecture_amendment_required:true,ea5_authorized:false,database_write_count:0,formal_evidence_write_count:0,public_raw_numeric_value_emission_count:0,raw_body_uploaded:false});write(result);console.log(JSON.stringify({status:'PASS',qualification_status:result.qualification_status,decision:result.decision,age_hours:result.rain_candidate.latest_observed_age_hours,grid,violations,source_substitution_authorized:false,ea5_authorized:false},null,2));await context.close();
}catch(error){result.error=`${error.name||'Error'}:${error.message||String(error)}`;write(result);console.error(result.error);process.exitCode=1}finally{await browser?.close()}
