// scripts/twin_kernel/P32_16_CONTROLLED_FORECAST_PROJECTION_RUNTIME_V0.cjs
'use strict';
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
function arg(n,d=null){const i=process.argv.indexOf(n);return i>=0?process.argv[i+1]:d}
function hash(v){return crypto.createHash('sha256').update(JSON.stringify(v)).digest('hex')}
function out(v){console.log(JSON.stringify(v,null,2))}
function ids(s=''){const r=crypto.randomUUID().replace(/-/g,'').slice(0,10);return{r,tenant_id:'tenantA',project_id:'projectA',group_id:'groupA',subject_ref:'field:p32:'+s+r,source_state_fact_id:'tse_fact_p31_'+s+r,source_state_id:'tse_p31_'+s+r,source_state_as_of_ts:'2032-01-01T00:00:00Z',runtime_run_id:'run_p32_'+s+r,forecast_run_id:'fr_p32_'+s+r,projection_id:'proj_p32_'+s+r,scenario_set_ref:'scenario_set_p32_'+s+r,weather_context_ref:'weather_context_p32_'+s+r,idempotency_key:'idem_p32_'+s+r}}
function base(x={}){return Object.assign({schema_version:'p32_forecast_projection_runtime_result_v0',phase:'P32',baseline_tag:'p31_continuous_twin_state_estimation_runtime_v0_closure',baseline_commit:'129e981f24befa061c876399869a92a0fffe0297',runtime_kind:'controlled_forecast_projection_runtime',allowed_created_fact_types:['forecast_run_v1','twin_state_projection_v1'],projection_is_future_belief:true,projection_is_not_future_reality:true,projection_is_not_ground_truth:true,projection_is_not_evaluation:true,scenario_refs_are_assumptions:true,weather_refs_are_context:true,forecast_run_v1_and_twin_state_projection_v1_must_be_created_atomically:true,forecast_run_without_projection_blocked:true,projection_without_forecast_run_blocked:true,partial_forecast_persistence_forbidden:true,forbidden_downstream_fact_count:0},x)}
function pair(label='one',prev=null,explicitFork=false){const i=ids(label);const assumption_set={scenario_set_ref:i.scenario_set_ref,weather_context_ref:i.weather_context_ref,explicit_fork:explicitFork};const horizon={start_ts:'2032-01-01T00:00:00Z',end_ts:'2032-01-08T00:00:00Z',step:'P1D'};const shared={tenant_id:i.tenant_id,project_id:i.project_id,group_id:i.group_id,subject_ref:i.subject_ref,runtime_run_id:i.runtime_run_id,source_twin_state_estimate_ref:{kind:'twin_state_estimate_v1',ref_id:i.source_state_fact_id},source_twin_state_estimate_hash:hash({id:i.source_state_id,as_of_ts:i.source_state_as_of_ts}),source_twin_state_as_of_ts:i.source_state_as_of_ts,scenario_set_ref:i.scenario_set_ref,weather_context_ref:i.weather_context_ref,scenario_set_hash:hash(i.scenario_set_ref),weather_context_hash:hash(i.weather_context_ref),assumption_set_hash:hash(assumption_set),horizon_policy_hash:hash(horizon),projection_chain_hash:hash(prev||'none'),idempotency_key:i.idempotency_key};const projection={projection_id:i.projection_id,forecast_run_id:i.forecast_run_id,projection_state:'FORECAST_PROJECTED',...shared,projection_timeline:[{ts:'2032-01-02T00:00:00Z',belief_dimensions:[{name:'ROOT_ZONE_WATER_BELIEF',value_kind:'bounded_projection',value:{lower:0.22,upper:0.31},uncertainty:{kind:'interval',lower:0.09,upper:0.18}}]},{ts:'2032-01-03T00:00:00Z',belief_dimensions:[{name:'ROOT_ZONE_WATER_BELIEF',value_kind:'bounded_projection',value:{lower:0.20,upper:0.34},uncertainty:{kind:'interval',lower:0.10,upper:0.21}}]}],uncertainty_summary:{kind:'propagated_interval',method_ref:'p32_uncertainty_v0'},previous_projection_ref:prev};const coreForHash={...shared,projection_timeline:projection.projection_timeline,uncertainty_summary:projection.uncertainty_summary,previous_projection_ref:prev};const determinism_hash=hash(coreForHash);projection.determinism_hash=determinism_hash;const run={forecast_run_id:i.forecast_run_id,projection_id:i.projection_id,run_state:'FORECAST_PROJECTED',...shared,forecast_horizon_start_ts:horizon.start_ts,forecast_horizon_end_ts:horizon.end_ts,forecast_time_step:horizon.step,forecaster_config_ref:'p32_forecaster_config_v0',forecaster_version:'p32_projection_forecaster_v0',effective_config_hash:hash({config:'p32_forecaster_config_v0'}),determinism_hash,meta:{idempotency_key:i.idempotency_key,created_by_runtime:'p32_controlled_forecast_projection_runtime_v0',policy_refs:['P32_FORECAST_PROJECTION_CORE_CONTRACT_V0','P32_ASSUMPTION_TRUTH_POLICY_V0','P32_PROJECTION_BELIEF_POLICY_V0']}};return{i,run,projection,determinism_hash}}
function blocked(reason,state='POLICY_BLOCKED'){return base({ok:true,run_mode:'dry_run',projection_state:state,forecast_run_v1_created:false,twin_state_projection_v1_created:false,atomic_pair_created:false,blockers:[reason],forbidden_downstream_fact_count:0})}
function dry(f){const m={'missing-source-state':'INSUFFICIENT_STATE_BASIS','raw-state-bypass':'POLICY_BLOCKED','cross-tenant-source-state':'POLICY_BLOCKED','horizon-exceeds':'HORIZON_BLOCKED','weather-outside-horizon':'WEATHER_CONTEXT_BLOCKED','implicit-branch':'POLICY_BLOCKED','partial-pair':'POLICY_BLOCKED','evaluation-field':'POLICY_BLOCKED','recommendation-field':'POLICY_BLOCKED'};if(m[f])return blocked(f,m[f]);const p=pair('dry_');return base({ok:true,run_mode:'dry_run',forecast_run_v1_created:false,twin_state_projection_v1_created:false,emits_atomic_pair:true,atomic_pair_validated:true,forecast_run:p.run,twin_state_projection:p.projection,determinism_hash:p.determinism_hash,projection_must_reference_forecast_run_id:p.projection.forecast_run_id===p.run.forecast_run_id,forecast_run_must_reference_projection_id:p.run.projection_id===p.projection.projection_id})}
function writeLocal(){const p=pair('cw_');const dir=path.join(process.cwd(),'acceptance-output');fs.mkdirSync(dir,{recursive:true});const target=path.join(dir,'P32_ATOMIC_PAIR.jsonl');const temp=target+'.tmp';fs.writeFileSync(temp,JSON.stringify({type:'forecast_run_v1',payload:p.run})+'\n'+JSON.stringify({type:'twin_state_projection_v1',payload:p.projection})+'\n');fs.renameSync(temp,target);const lines=fs.readFileSync(target,'utf8').trim().split('\n').map(JSON.parse);return base({ok:true,run_mode:'controlled_write',local_atomic_pair_ledger:target,forecast_run_v1_created:true,twin_state_projection_v1_created:true,atomic_pair_created:true,forecast_run_readback_passed:lines[0].type==='forecast_run_v1',projection_readback_passed:lines[1].type==='twin_state_projection_v1',projection_must_reference_forecast_run_id:lines[1].payload.forecast_run_id===lines[0].payload.forecast_run_id,forecast_run_must_reference_projection_id:lines[0].payload.projection_id===lines[1].payload.projection_id,determinism_hash:p.determinism_hash})}
function twoStep(){const first=pair('a_');const prev={kind:'twin_state_projection_v1',ref_id:first.i.projection_id,forecast_run_id:first.i.forecast_run_id,source_state_hash:first.run.source_twin_state_estimate_hash,scenario_set_hash:first.run.scenario_set_hash,horizon_policy_hash:first.run.horizon_policy_hash};const second=pair('b_',prev,true);return base({ok:true,run_mode:'controlled_two_step_projection',first_projection_created:true,second_projection_created:true,previous_projection_chain_subject_must_remain_constant:true,previous_projection_chain_source_state_must_be_consistent:true,scenario_fork_must_be_explicit:true,implicit_projection_branching_forbidden:true,previous_projection_chain_hash_required_when_previous_projection_ref_present:!!second.projection.projection_chain_hash,first_determinism_hash:first.determinism_hash,second_determinism_hash:second.determinism_hash})}
const mode=arg('--mode','dry-run');const fixture=arg('--fixture','valid');if(mode==='controlled-write')out(writeLocal());else if(mode==='controlled-two-step-projection')out(twoStep());else out(dry(fixture));
