// scripts/twin_kernel/P33_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs'),cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P33_15_CONTROLLED_PROJECTION_USE_ACTIVATION_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const B='p32_controlled_twin_forecast_projection_runtime_v0_governance_correction_v2',C='938680917f1f0c5d9a1978df464971f524fd7add';
const c=J('docs/twin_kernel/P33_PROJECTION_USE_ACTIVATION_CONTRACT_V0.json'),as=J('docs/twin_kernel/P33_PROJECTION_USE_ACTIVATION_SCHEMA_V0.json'),ps=J('docs/twin_kernel/P33_ACTIVE_PROJECTION_POINTER_SCHEMA_V0.json'),sp=J('docs/twin_kernel/P33_SOURCE_PROJECTION_PAIR_BOUNDARY_POLICY_V0.json'),sc=J('docs/twin_kernel/P33_ACTIVATION_SCOPE_POLICY_V0.json'),ap=J('docs/twin_kernel/P33_ATOMIC_ACTIVATION_POINTER_POLICY_V0.json'),au=J('docs/twin_kernel/P33_AUTHORIZATION_HUMAN_GATE_POLICY_V0.json'),ip=J('docs/twin_kernel/P33_IDEMPOTENCY_POLICY_V0.json'),dp=J('docs/twin_kernel/P33_DETERMINISM_POLICY_V0.json'),chp=J('docs/twin_kernel/P33_POINTER_CHAIN_POLICY_V0.json'),ep=J('docs/twin_kernel/P33_EXPIRY_USE_WINDOW_POLICY_V0.json'),ih=J('docs/twin_kernel/P33_ASSUMPTION_HORIZON_INHERITANCE_POLICY_V0.json'),na=J('docs/twin_kernel/P33_NO_ACCURACY_NO_CALIBRATION_POLICY_V0.json'),nd=J('docs/twin_kernel/P33_NO_RECOMMENDATION_NO_ACTION_NO_MODEL_ACTIVATION_POLICY_V0.json');
const d1=R([]),d2=R([]),cw=R(['--mode','controlled-write']),chain=R(['--mode','controlled-two-step-pointer-chain']);
const F=new Set(['accuracy','accuracy_score','forecast_accuracy','forecast_error','prediction_error','error_rate','correctness','correctness_claim','backtest_result','calibration_result','residual','residual_error','score','ranking_score','best_projection','preferred_projection','recommended_projection','recommended_action','next_action','operator_instruction','operation_plan','model_update','model_activation','learning_signal','training_signal','roi_success','effect_attribution']);
function noF(v,k=''){if(k==='policy_refs')return true;if(F.has(k))return false;if(Array.isArray(v))return v.every(x=>noF(x));if(v&&typeof v==='object')return Object.entries(v).every(([a,b])=>noF(b,a));return true}
const bx=f=>R(['--fixture',f]).activation_state;
const tests=[
['P33_00_baseline_is_p32_governance_correction_v2',c.baseline_tag===B&&c.baseline_commit===C&&c.forbidden_baseline_tag==='p32_controlled_twin_forecast_projection_runtime_v0_closure'],
['P33_00_p32_non_persisted_boundary_inherited',c.source_storage_boundary.p32_facts_table_forecast_pair_not_claimed&&c.persistence_boundary.facts_table_persistence_not_claimed&&c.persistence_boundary.database_persistence_not_claimed&&c.persistence_boundary.server_endpoint_not_claimed&&c.persistence_boundary.db_migration_not_claimed],
['P33_01_only_activation_and_pointer_allowed',JSON.stringify(c.allowed_created_fact_types)===JSON.stringify(['projection_use_activation_v1','active_projection_pointer_v1'])],
['P33_02_activation_schema',as.required_fields.includes('projection_use_activation_id')&&as.required_fields.includes('source_p32_pair_ref')&&as.required_fields.includes('determinism_hash')&&as.target_payload_allowed_activation_states[0]==='PROJECTION_ACTIVATED_FOR_USE'],
['P33_03_pointer_append_only_schema',ps.active_projection_pointer_v1_is_append_only_use_pointer&&ps.active_projection_pointer_v1_is_not_mutable_current_state&&ps.active_projection_pointer_v1_is_not_accuracy_selection],
['P33_04_storage_mode_boundary',JSON.stringify(sp.source_projection_pair_storage_mode_allowed)===JSON.stringify(['p32_local_atomic_pair_ledger_ref','p32_controlled_fixture_pair_ref'])&&sp.p33_must_not_require_persisted_p32_forecast_facts&&d1.source_pair_storage_mode==='p32_controlled_fixture_pair_ref'&&cw.source_pair_storage_mode==='p32_local_atomic_pair_ledger_ref'],
['P33_04_bypass_blocked',bx('raw-evidence-bypass')==='POLICY_BLOCKED'&&bx('manual-projection')==='POLICY_BLOCKED'],
['P33_04_missing_mismatch_cross_tenant_blocked',bx('missing-forecast-run')==='MISSING_FORECAST_RUN'&&bx('missing-twin-state-projection')==='MISSING_TWIN_STATE_PROJECTION'&&bx('pair-mismatch')==='PROJECTION_PAIR_MISMATCH'&&bx('cross-tenant')==='CROSS_TENANT_BLOCKED'],
['P33_04_source_not_projected_blocked',bx('source-not-projected')==='SOURCE_PROJECTION_NOT_PROJECTED'],
['P33_05_atomic_policy',ap.projection_use_activation_v1_and_active_projection_pointer_v1_must_be_created_atomically&&ap.activation_without_pointer_blocked&&ap.pointer_without_activation_blocked&&cw.atomic_activation_pointer_pair_created],
['P33_05_local_ledger_only',ap.local_atomic_activation_pointer_ledger_only&&ap.facts_table_persistence_not_claimed&&ap.database_persistence_not_claimed&&ap.server_endpoint_not_claimed&&ap.db_migration_not_claimed&&cw.local_atomic_activation_pointer_ledger.endsWith('P33_ATOMIC_ACTIVATION_POINTER.jsonl')],
['P33_06_scope_policy',sc.allowed_activation_scopes.includes(d1.activation_scope)&&sc.forbidden_activation_scopes.includes('recommendation_context')&&bx('forbidden-scope')==='POLICY_BLOCKED'],
['P33_07_authorization_gate',au.authorization_ref_required&&au.human_gate_ref_required&&au.authorization_missing_blocks_activation&&bx('authorization-missing')==='AUTHORIZATION_MISSING'],
['P33_08_idempotency_duplicate_policy',ip.idempotency_key_required&&ip.same_activation_scope_duplicate_blocked&&bx('duplicate-scope')==='DUPLICATE_ACTIVATION_SCOPE_BLOCKED'&&d1.idempotency_key===d2.idempotency_key],
['P33_09_determinism_stable',dp.determinism_hash_required&&dp.determinism_hash_must_be_stable_for_same_source_pair_scope_and_policy&&d1.determinism_hash===d2.determinism_hash],
['P33_10_pointer_chain_append_only',chp.new_active_projection_supersedes_previous_pointer_by_append_only_chain&&chain.new_active_projection_supersedes_previous_pointer_by_append_only_chain&&chain.previous_pointer_payload_must_not_be_mutated&&chain.previous_pointer_scope_must_match_current_scope&&chain.previous_pointer_subject_must_match_current_subject&&chain.previous_pointer_tenant_project_group_must_match],
['P33_11_expiry_use_window',ep.activation_use_window_must_be_within_or_equal_projection_horizon_policy&&ep.expired_projection_must_not_be_activated&&bx('horizon-outside')==='HORIZON_SCOPE_BLOCKED'&&bx('expired-projection')==='EXPIRED_PROJECTION_BLOCKED'],
['P33_12_inheritance_policy',ih.scenario_set_hash_must_be_inherited_from_p32_pair&&ih.assumption_set_hash_must_be_inherited_from_p32_pair&&ih.horizon_policy_hash_must_be_inherited_from_p32_pair&&ih.p33_must_not_recompute_projection&&bx('assumption-scope')==='ASSUMPTION_SCOPE_BLOCKED'],
['P33_13_no_accuracy_calibration',na.forecast_accuracy_review_forbidden&&na.forecast_accuracy_score_forbidden&&na.backtest_result_forbidden&&na.calibration_result_forbidden&&bx('accuracy-language')==='ACCURACY_LANGUAGE_BLOCKED'],
['P33_14_no_downstream',nd.projection_activation_must_not_create_downstream_facts&&bx('recommendation-language')==='RECOMMENDATION_LANGUAGE_BLOCKED'&&bx('action-language')==='ACTION_LANGUAGE_BLOCKED'&&bx('model-activation-language')==='MODEL_ACTIVATION_LANGUAGE_BLOCKED'],
['P33_15_runner_modes_pass',d1.ok&&cw.ok&&chain.ok],
['P33_15_runner_output_fields',!!d1.runtime_run_id&&!!d1.projection_use_activation_id&&!!d1.active_projection_pointer_id&&!!d1.activation_scope_hash&&!!d1.source_p32_pair_ref&&!!d1.source_projection_pair_hash&&!!d1.effective_config_hash&&!!d1.determinism_hash&&!!d1.idempotency_key],
['P33_16_blocked_states_create_no_targets',R(['--fixture','accuracy-language']).projection_use_activation_v1_created===false&&R(['--fixture','action-language']).active_projection_pointer_v1_created===false],
['P33_16_no_implicit_ranking',dp.latest_projection_is_not_automatically_active&&dp.lowest_uncertainty_projection_is_not_automatically_active&&bx('latest-auto-active')==='IMPLICIT_RANKING_BLOCKED'&&bx('lowest-uncertainty-auto-active')==='IMPLICIT_RANKING_BLOCKED'&&bx('implicit-ranking')==='IMPLICIT_RANKING_BLOCKED'],
['P33_17_controlled_write_readback_atomic_refs',cw.projection_use_activation_v1_created&&cw.active_projection_pointer_v1_created&&cw.activation_readback_passed&&cw.pointer_readback_passed&&cw.pointer_must_reference_activation_id&&cw.activation_must_reference_pointer_id],
['P33_17_no_forbidden_downstream_facts_or_fields',d1.forbidden_downstream_fact_count===0&&cw.forbidden_downstream_fact_count===0&&chain.forbidden_downstream_fact_count===0&&noF(d1.projection_use_activation)&&noF(d1.active_projection_pointer)],
['P33_18_completion_review_ready',fs.existsSync('docs/tasks/P33-Controlled-Twin-Projection-Use-Activation-Gate-v0.md')&&fs.existsSync('scripts/twin_kernel/P33_15_CONTROLLED_PROJECTION_USE_ACTIVATION_RUNNER_V0.cjs')&&fs.existsSync('docs/twin_kernel/P33_PROJECTION_USE_ACTIVATION_COMPLETION_REVIEW_V0.json')]
];
const failed=tests.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P33_ALL_ACCEPTANCE',phase:'P33',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:tests.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:d1.determinism_hash,controlled_write_determinism_hash:cw.determinism_hash,first_pointer_chain_hash:chain.first_pointer_chain_hash,second_pointer_chain_hash:chain.second_pointer_chain_hash},null,2));
if(!ok)process.exit(1);
