// scripts/twin_kernel/P40_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs'),cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P40_20_CONTROLLED_PRODUCTION_TWIN_RUNTIME_SCHEDULER_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const c=J('docs/twin_kernel/P40_PRODUCTION_TWIN_RUNTIME_SCHEDULER_CONTRACT_V0.json');
const r=J('docs/twin_kernel/P40_PRODUCTION_TWIN_RUNTIME_SCHEDULER_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-runtime-chain']);
const checks=[];
const ck=(n,v)=>checks.push([n,!!v]);
ck('baseline',c.baseline_tag==='p39_model_version_candidate_shadow_activation_gate_v0_closure'&&c.baseline_commit==='5e4fa5aead5fa5d3cd1b460130703b3168e3f9e7');
ck('allowed_types',JSON.stringify(c.allowed_created_fact_types)===JSON.stringify(['twin_runtime_schedule_v1','twin_runtime_tick_v1','twin_runtime_cycle_v1','runtime_cycle_readback_v1']));
ck('stage_valid',(r.completion_status==='implementation_ready_for_review'&&r.final_closure_status==='not_started')||(r.completion_status==='complete'&&r.final_closure_status==='final_tag_main_verified'&&r.final_commit==='6f82fa55bffc6a09b49d04837c35818910ff4dcd'));
ck('deterministic',dry.determinism_hash===dry2.determinism_hash);
ck('dry_no_targets',dry.twin_runtime_schedule_v1_created===false&&dry.twin_runtime_tick_v1_created===false&&dry.twin_runtime_cycle_v1_created===false&&dry.runtime_cycle_readback_v1_created===false);
ck('write_targets',wr.twin_runtime_schedule_v1_created===true&&wr.twin_runtime_tick_v1_created===true&&wr.twin_runtime_cycle_v1_created===true&&wr.runtime_cycle_readback_v1_created===true);
ck('step_order',wr.cycle_step_order.join('>')==='resolve_input_window>attempt_state_estimate>attempt_forecast>attempt_previous_forecast_residual_check>write_cycle_readback');
ck('deferred_boundaries',wr.forecast_step_status==='STEP_BLOCKED_BY_MISSING_GATE'&&wr.previous_forecast_residual_check_step_status==='STEP_DEFERRED_TO_P43');
ck('chains',ch.runtime_chains_are_append_only===true&&ch.previous_runtime_schedule_payload_must_not_be_mutated===true&&ch.previous_runtime_cycle_readback_payload_must_not_be_mutated===true);
ck('no_downstream',dry.forbidden_downstream_fact_count===0&&wr.forbidden_downstream_fact_count===0&&ch.forbidden_downstream_fact_count===0);
const failed=checks.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P40_ALL_ACCEPTANCE',phase:'P40',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:checks.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_runtime_chain_hash:ch.first_runtime_schedule_chain_hash,second_runtime_chain_hash:ch.second_runtime_schedule_chain_hash},null,2));
if(!ok)process.exit(1);
