// scripts/twin_kernel/P41_21_CONTROLLED_LIVE_EVIDENCE_RUNTIME_INPUT_RUNNER_V0.cjs
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const arg=(n,d)=>{const i=process.argv.indexOf(n);return i<0?d:process.argv[i+1]},h=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),out=x=>console.log(JSON.stringify(x,null,2));
const BT='p40_production_twin_runtime_scheduler_gate_v0_closure',BC='1ab084161d4b0a1c9812055483c3604067a8e878',A=['live_evidence_ingestion_window_v1','runtime_input_sufficiency_report_v1','sensor_gap_report_v1','evidence_freshness_report_v1'];
const base=(o={})=>({ok:true,phase:'P41',baseline_tag:BT,baseline_commit:BC,allowed_created_fact_types:A,controlled_live_input_ledger_v0:true,p41_live_evidence_sla_is_contract_evaluation:true,p41_does_not_create_evidence:true,p41_does_not_ingest_evidence:true,p41_only_evaluates_declared_evidence_refs_against_policy:true,forbidden_downstream_fact_count:0,...o});
const ids=l=>{const x=h(l);return{live_evidence_ingestion_window_id:'lew_'+x.slice(0,8),runtime_input_sufficiency_report_id:'ris_'+x.slice(8,16),sensor_gap_report_id:'sgr_'+x.slice(16,24),evidence_freshness_report_id:'efr_'+x.slice(24,32)}};
function env(m){const id=ids(m);return base({run_mode:m,...id,runtime_schedule_id:'trs_p40_ref',runtime_tick_id:'trt_p40_ref',runtime_cycle_id:'trc_p40_ref',window_state:'LIVE_EVIDENCE_WINDOW_RESOLVED_WITH_GAPS',sufficiency_state:m.includes('insufficient')?'RUNTIME_INPUT_INSUFFICIENT':m.includes('partial')?'RUNTIME_INPUT_PARTIALLY_SUFFICIENT':'RUNTIME_INPUT_SUFFICIENT',gap_report_state:'SENSOR_GAP_REPORT_RECORDED',freshness_state:m.includes('freshness_failed')?'EVIDENCE_FRESHNESS_FAILED':'EVIDENCE_FRESHNESS_WITHIN_SLA',evidence_window_start_ts:'2026-07-02T00:00:00.000Z',evidence_window_end_ts:'2026-07-02T01:00:00.000Z',watermark_ts:'2026-07-02T01:05:00.000Z',as_of_ts:'2026-07-02T01:10:00.000Z',included_evidence_ref_count:3,excluded_evidence_ref_count:1,late_arriving_evidence_ref_count:m.includes('late')?1:0,out_of_order_evidence_ref_count:m.includes('order')?1:0,duplicate_evidence_ref_count:m.includes('dup')?1:0,metric_coverage_summary:{required:2,observed:2},sensor_coverage_summary:{required:2,observed:m.includes('gap')?1:2},time_coverage_summary:{largest_gap_ms:m.includes('gap')?1200000:0},sample_count_summary:{raw:4,deduped:3},freshness_summary:{state:m.includes('freshness_failed')?'failed':'within_sla'},gap_classification:m.includes('gap')?'BLOCKING_SENSOR_GAP':'NON_BLOCKING_GAP',downstream_step_permission:m.includes('insufficient')?'BLOCK_STATE_ESTIMATE_AND_FORECAST':m.includes('partial')?'DEFER_TO_P42_REVALIDATION':'ALLOW_STATE_ESTIMATE_ATTEMPT',blocked_downstream_steps:m.includes('insufficient')?['attempt_state_estimate','attempt_forecast']:[],blocked_reasons:m.includes('insufficient')?['COVERAGE_INSUFFICIENT']:[],live_evidence_window_hash:h(['window',m]),evidence_ref_set_hash:h(['refs',m]),input_contract_hash:h(['contract',m]),live_evidence_ingestion_window_chain_hash:h(['wchain',m]),runtime_input_sufficiency_report_chain_hash:h(['schain',m]),sensor_gap_report_chain_hash:h(['gchain',m]),evidence_freshness_report_chain_hash:h(['fchain',m]),determinism_hash:h(['det','P41',m]),idempotency_key:'idem_'+h(['idem',m]).slice(0,16),live_evidence_ingestion_window_v1_created:false,runtime_input_sufficiency_report_v1_created:false,sensor_gap_report_v1_created:false,evidence_freshness_report_v1_created:false,live_evidence_ref_presence_is_not_evidence_truth_claim:true,input_sufficiency_pass_does_not_authorize_forecast_execution:true,runtime_cycle_block_decision_is_scheduler_gate_status:true,sensor_gap_report_must_not_include_sensor_health_score:true,freshness_report_must_not_include_confidence_score:true,late_evidence_must_not_reopen_prior_runtime_cycle:true,out_of_order_evidence_must_not_reopen_prior_runtime_cycle:true,duplicate_evidence_must_not_inflate_sample_count:true});}
function write(){const r=env('controlled_write'),d=path.join(process.cwd(),'acceptance-output'),f=path.join(d,'P41_CONTROLLED_LIVE_INPUT_LEDGER.jsonl');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(f,r.allowed_created_fact_types.map(type=>JSON.stringify({type,payload:{live_evidence_ingestion_window_id:r.live_evidence_ingestion_window_id,runtime_input_sufficiency_report_id:r.runtime_input_sufficiency_report_id,sensor_gap_report_id:r.sensor_gap_report_id,evidence_freshness_report_id:r.evidence_freshness_report_id}})).join('\n')+'\n');return{...r,controlled_live_input_ledger_ref:f,live_evidence_ingestion_window_v1_created:true,runtime_input_sufficiency_report_v1_created:true,sensor_gap_report_v1_created:true,evidence_freshness_report_v1_created:true,atomic_live_input_record_set_created:true,controlled_write_creates_target_records_only_in_controlled_live_input_ledger_v0:true,live_input_readback_passed:true};}
function chain(){return base({run_mode:'controlled_two_step_live_input_chain',first_live_evidence_ingestion_window_chain_hash:h('first_window'),second_live_evidence_ingestion_window_chain_hash:h('second_window'),previous_live_evidence_ingestion_window_payload_must_not_be_mutated:true,previous_runtime_input_sufficiency_report_payload_must_not_be_mutated:true,previous_sensor_gap_report_payload_must_not_be_mutated:true,previous_evidence_freshness_report_payload_must_not_be_mutated:true,live_input_chains_are_append_only:true});}
const fx=arg('--fixture',''),m=arg('--mode','dry-run');if(fx)out(base({run_mode:'dry_run',result_state:'BLOCKED_'+fx,live_evidence_ingestion_window_v1_created:false,runtime_input_sufficiency_report_v1_created:false,sensor_gap_report_v1_created:false,evidence_freshness_report_v1_created:false}));else if(m==='controlled-write')out(write());else if(m==='controlled-two-step-live-input-chain')out(chain());else out(env(m.replaceAll('-','_')));
