// scripts/twin_kernel/P41_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs'),cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P41_21_CONTROLLED_LIVE_EVIDENCE_RUNTIME_INPUT_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const c=J('docs/twin_kernel/P41_LIVE_EVIDENCE_RUNTIME_INPUT_CONTRACT_V0.json');
const r=J('docs/twin_kernel/P41_LIVE_EVIDENCE_RUNTIME_INPUT_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),cw=R(['--mode','controlled-window']),cs=R(['--mode','controlled-sufficiency']),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-live-input-chain']);
const checks=[];
const ck=(n,v)=>checks.push([n,!!v]);
ck('baseline',c.baseline_tag==='p40_production_twin_runtime_scheduler_gate_v0_closure'&&c.baseline_commit==='1ab084161d4b0a1c9812055483c3604067a8e878');
ck('allowed_types',JSON.stringify(c.allowed_created_fact_types)===JSON.stringify(['live_evidence_ingestion_window_v1','runtime_input_sufficiency_report_v1','sensor_gap_report_v1','evidence_freshness_report_v1']));
ck('stage_valid',(r.completion_status==='implementation_ready_for_review'&&r.final_closure_status==='not_started')||(r.completion_status==='complete'&&r.final_closure_status==='final_tag_main_verified'&&r.final_commit==='649988feac9d57bd929d2b13137a5e2ec8c0f903'));
ck('deterministic',dry.determinism_hash===dry2.determinism_hash);
ck('dry_no_targets',dry.live_evidence_ingestion_window_v1_created===false&&dry.runtime_input_sufficiency_report_v1_created===false&&dry.sensor_gap_report_v1_created===false&&dry.evidence_freshness_report_v1_created===false);
ck('envelope_modes_no_targets',cw.live_evidence_ingestion_window_v1_created===false&&cs.runtime_input_sufficiency_report_v1_created===false);
ck('write_targets',wr.live_evidence_ingestion_window_v1_created===true&&wr.runtime_input_sufficiency_report_v1_created===true&&wr.sensor_gap_report_v1_created===true&&wr.evidence_freshness_report_v1_created===true);
ck('write_atomic',wr.atomic_live_input_record_set_created===true&&wr.controlled_write_creates_target_records_only_in_controlled_live_input_ledger_v0===true);
ck('chains',ch.live_input_chains_are_append_only===true&&ch.previous_live_evidence_ingestion_window_payload_must_not_be_mutated===true&&ch.previous_evidence_freshness_report_payload_must_not_be_mutated===true);
ck('no_downstream',dry.forbidden_downstream_fact_count===0&&wr.forbidden_downstream_fact_count===0&&ch.forbidden_downstream_fact_count===0);
const failed=checks.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P41_ALL_ACCEPTANCE',phase:'P41',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:checks.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_window_determinism_hash:cw.determinism_hash,controlled_sufficiency_determinism_hash:cs.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_live_input_chain_hash:ch.first_live_evidence_ingestion_window_chain_hash,second_live_input_chain_hash:ch.second_live_evidence_ingestion_window_chain_hash},null,2));
if(!ok)process.exit(1);
