// scripts/twin_kernel/P42_21_CONTROLLED_ACTIVE_TWIN_FORECAST_LOOP_RUNNER_V0.cjs
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const arg=(n,d)=>{const i=process.argv.indexOf(n);return i<0?d:process.argv[i+1]},h=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex'),out=x=>console.log(JSON.stringify(x,null,2));
const BT='p41_live_evidence_ingestion_sla_runtime_input_contract_v0_closure',BC='8326cf87fb01f7377a8b55d784ffa9027fbd725b',A=['active_twin_forecast_run_v1','active_twin_prediction_v1','forecast_horizon_v1','scenario_projection_v1'];
const base=(o={})=>({ok:true,phase:'P42',baseline_tag:BT,baseline_commit:BC,allowed_created_fact_types:A,controlled_active_forecast_ledger_v0:true,p42_is_controlled_active_forecast_record_gate:true,p42_is_not_background_forecast_loop:true,p42_is_not_daemon:true,p42_is_not_server_runtime_loop:true,p42_is_not_production_forecast_api:true,p41_sufficiency_pass_is_necessary_not_sufficient_for_p42_forecast:true,p42_does_not_validate_or_grant_activation_status:true,p42_consumes_active_ref_as_declared_input_only:true,forbidden_downstream_fact_count:0,...o});
const ids=l=>{const x=h(l);return{active_twin_forecast_run_id:'afr_'+x.slice(0,8),active_twin_prediction_id:'atp_'+x.slice(8,16),forecast_horizon_id:'fho_'+x.slice(16,24),scenario_projection_id:'scp_'+x.slice(24,32)}};
function env(m){const id=ids(m);return base({run_mode:m,...id,runtime_schedule_id:'trs_p40_ref',runtime_tick_id:'trt_p40_ref',runtime_cycle_id:'trc_p40_ref',source_live_evidence_ingestion_window_id:'lew_p41_ref',source_runtime_input_sufficiency_report_id:'ris_p41_ref',source_sensor_gap_report_id:'sgr_p41_ref',source_evidence_freshness_report_id:'efr_p41_ref',active_state_estimate_ref:'ase_controlled_fixture_ref',active_runtime_estimator_config_ref:'aec_controlled_fixture_ref',active_runtime_model_ref:'arm_controlled_fixture_ref',forecast_run_state:m.includes('partial')?'ACTIVE_TWIN_FORECAST_RUN_COMPLETED_WITH_LIMITATIONS':'ACTIVE_TWIN_FORECAST_RUN_COMPLETED',prediction_state:'ACTIVE_TWIN_PREDICTION_RECORDED',forecast_horizon_state:m.includes('truncated')?'FORECAST_HORIZON_TRUNCATED_BY_POLICY':'FORECAST_HORIZON_REGISTERED',scenario_projection_state:'SCENARIO_PROJECTION_RECORDED',forecast_horizon_start_ts:'2026-07-02T02:00:00.000Z',forecast_horizon_end_ts:'2026-07-02T08:00:00.000Z',forecast_horizon_duration_ms:21600000,forecast_horizon_step_ms:3600000,prediction_metric_ref_count:2,scenario_count:m.includes('scenario')?2:1,prediction_values_hash:h(['values',m]),prediction_uncertainty_hash:h(['uncertainty',m]),scenario_projection_values_hash:h(['scenario',m]),forecast_scope_hash:h(['scope',m]),p41_input_contract_hash:h(['p41',m]),active_state_estimate_hash:h(['state',m]),active_runtime_estimator_config_hash:h(['config',m]),active_runtime_model_hash:h(['model',m]),eligible_as_future_residual_monitoring_input_ref:true,eligible_as_future_residual_monitoring_input_ref_is_only_future_eligibility_marker:true,eligible_as_future_residual_monitoring_input_ref_does_not_create_p43_monitor:true,not_sufficient_to_create_residual:true,not_sufficient_to_create_drift_signal:true,not_sufficient_to_create_recommendation:true,not_sufficient_to_update_model:true,active_twin_forecast_run_chain_hash:h(['rchain',m]),active_twin_prediction_chain_hash:h(['pchain',m]),forecast_horizon_chain_hash:h(['hchain',m]),scenario_projection_chain_hash:h(['schain',m]),effective_config_hash:h(['effective',m]),determinism_hash:h(['det','P42',m]),idempotency_key:'idem_'+h(['idem',m]).slice(0,16),active_twin_forecast_run_v1_created:false,active_twin_prediction_v1_created:false,forecast_horizon_v1_created:false,scenario_projection_v1_created:false,active_twin_prediction_v1_must_not_be_indexed_as_evidence:true,scenario_projection_must_not_rank_scenarios:true,prediction_uncertainty_is_not_confidence_score:true,forecast_horizon_blocked_by_policy_is_not_operator_alert:true});}
function write(){const r=env('controlled_write'),d=path.join(process.cwd(),'acceptance-output'),f=path.join(d,'P42_CONTROLLED_ACTIVE_FORECAST_LEDGER.jsonl');fs.mkdirSync(d,{recursive:true});fs.writeFileSync(f,r.allowed_created_fact_types.map(type=>JSON.stringify({type,payload:{active_twin_forecast_run_id:r.active_twin_forecast_run_id,active_twin_prediction_id:r.active_twin_prediction_id,forecast_horizon_id:r.forecast_horizon_id,scenario_projection_id:r.scenario_projection_id}})).join('\n')+'\n');return{...r,controlled_active_forecast_ledger_ref:f,active_twin_forecast_run_v1_created:true,active_twin_prediction_v1_created:true,forecast_horizon_v1_created:true,scenario_projection_v1_created:true,atomic_active_forecast_record_set_created:true,controlled_write_creates_target_records_only_in_controlled_active_forecast_ledger_v0:true,active_forecast_readback_passed:true};}
function chain(){return base({run_mode:'controlled_two_step_forecast_chain',first_active_twin_forecast_run_chain_hash:h('first_run'),second_active_twin_forecast_run_chain_hash:h('second_run'),previous_active_twin_forecast_run_payload_must_not_be_mutated:true,previous_active_twin_prediction_payload_must_not_be_mutated:true,previous_forecast_horizon_payload_must_not_be_mutated:true,previous_scenario_projection_payload_must_not_be_mutated:true,active_forecast_chains_are_append_only:true});}
const fx=arg('--fixture',''),m=arg('--mode','dry-run');if(fx)out(base({run_mode:'dry_run',result_state:'BLOCKED_'+fx,active_twin_forecast_run_v1_created:false,active_twin_prediction_v1_created:false,forecast_horizon_v1_created:false,scenario_projection_v1_created:false}));else if(m==='controlled-write')out(write());else if(m==='controlled-two-step-forecast-chain')out(chain());else out(env(m.replaceAll('-','_')));
