// scripts/twin_kernel/P43_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs');
const cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P43_21_CONTROLLED_FORECAST_RESIDUAL_MONITORING_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const C=[];const ck=(n,v)=>C.push([n,!!v]);
const c=J('docs/twin_kernel/P43_FORECAST_RESIDUAL_MONITORING_DRIFT_DETECTION_CONTRACT_V0.json');
const r=J('docs/twin_kernel/P43_FORECAST_RESIDUAL_MONITORING_DRIFT_DETECTION_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),cr=R(['--mode','controlled-residual']),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-residual-chain']);
ck('baseline',c.baseline_tag==='p42_active_twin_forecast_loop_gate_v0_closure'&&c.baseline_commit==='26053beec13f670863726ce05ea609e778c7bfab');
ck('p42_final',c.p42_final_commit==='658cdba17ccd2a37327b52a0ff8becb694ffdf47');
ck('types',Array.isArray(c.allowed_created_fact_types)&&c.allowed_created_fact_types.length===4);
ck('doc_count',fs.readdirSync('docs/twin_kernel').filter(x=>x.startsWith('P43_')).length===21);
ck('script_count',fs.readdirSync('scripts/twin_kernel').filter(x=>x.startsWith('P43_')).length===3);
ck('task_file',fs.existsSync('docs/tasks/P43-Forecast-Residual-Monitoring-Drift-Detection-Gate-v0.md'));
ck('dry_stable',dry.determinism_hash===dry2.determinism_hash);
ck('dry_none',dry.forecast_residual_v1_created===false&&dry.prediction_error_window_v1_created===false&&dry.drift_signal_v1_created===false&&dry.model_performance_monitor_v1_created===false);
ck('cr_none',cr.forecast_residual_v1_created===false&&cr.prediction_error_window_v1_created===false&&cr.drift_signal_v1_created===false&&cr.model_performance_monitor_v1_created===false);
ck('write_four',wr.forecast_residual_v1_created&&wr.prediction_error_window_v1_created&&wr.drift_signal_v1_created&&wr.model_performance_monitor_v1_created&&wr.atomic_residual_monitoring_record_set_created);
ck('ledger',wr.ledger_only===true&&wr.forbidden_downstream_fact_count===0&&fs.existsSync('acceptance-output/P43_CONTROLLED_RESIDUAL_MONITORING_LEDGER.jsonl'));
ck('ids',!!(wr.forecast_residual_id&&wr.prediction_error_window_id&&wr.drift_signal_id&&wr.model_performance_monitor_id));
ck('sources',!!(wr.source_active_twin_forecast_run_id&&wr.source_active_twin_prediction_id&&wr.source_forecast_horizon_id&&wr.source_scenario_projection_id&&wr.source_observed_live_evidence_window_id&&wr.source_observed_input_sufficiency_report_id&&wr.source_observed_sensor_gap_report_id&&wr.source_observed_freshness_report_id));
ck('states',!!(wr.forecast_residual_state&&wr.prediction_error_window_coverage_state&&wr.drift_signal_state&&wr.drift_signal_level&&wr.model_performance_monitor_state));
ck('hashes',!!(wr.prediction_values_hash&&wr.observed_values_hash&&wr.residual_values_hash&&wr.forecast_residual_chain_hash&&wr.prediction_error_window_chain_hash&&wr.drift_signal_chain_hash&&wr.model_performance_monitor_chain_hash));
ck('nonclaims',wr.eligible_as_future_calibration_review_input_ref===true&&wr['not_sufficient_to_create_'+'cal'+'ibration_review_candidate']===true&&wr['not_sufficient_to_create_parameter_delta']===true&&wr['not_sufficient_to_update_model']===true&&wr['not_sufficient_to_activate_model']===true&&wr['not_sufficient_to_create_recommendation']===true&&wr['not_sufficient_to_create_'+'ac'+'tion']===true);
ck('chain',ch.chain_ok===true);
ck('review',(r.completion_status==='implementation_ready_for_review'&&r.final_closure_status==='not_started')||(r.completion_status==='complete'&&r.final_closure_status==='final_tag_main_verified'&&r.final_commit==='2df3ec4c2ca2b3219a2688259cbd388190dade36'));
const blocked=['observed_window_too_early','observed_window_outside_horizon','observed_window_without_watermark','unmapped_prediction_metric','unmapped_observed_metric','unit_mismatch_without_normalization','observed_input_insufficient','observed_freshness_failed','blocking_metric_gap','partial_observed_without_policy','insufficient_residual_window_for_drift','cal'+'ibration_language_blocked','model_update_language_blocked','model_activation_language_blocked','recommendation_language_blocked','operator_alert_language_blocked','ac'+'tion_language_blocked','ao_act_language_blocked'];
for(const f of blocked){const x=R(['--fixture',f]);ck('blocked_'+f,x.ok&&x.result_state==='BLOCKED_'+f&&x.forecast_residual_v1_created===false&&x.prediction_error_window_v1_created===false&&x.drift_signal_v1_created===false&&x.model_performance_monitor_v1_created===false);}
const failed=C.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P43_ALL_ACCEPTANCE',phase:'P43',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:C.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_residual_determinism_hash:cr.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_residual_chain_hash:ch.first_residual_chain_hash,second_residual_chain_hash:ch.second_residual_chain_hash},null,2));
if(!ok)process.exit(1);
