// scripts/twin_kernel/P44_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs');
const cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P44_21_CONTROLLED_MODEL_ACTIVATION_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const C=[];const ck=(n,v)=>C.push([n,!!v]);
const c=J('docs/twin_kernel/P44_CALIBRATION_PROMOTION_ACTIVE_MODEL_ACTIVATION_CONTRACT_V0.json');
const r=J('docs/twin_kernel/P44_CALIBRATION_PROMOTION_ACTIVE_MODEL_ACTIVATION_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),rev=R(['--mode','controlled-activation-review']),ptr=R(['--mode','controlled-pointer-switch']),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-activation-chain']);
const none=x=>x.model_activation_review_v1_created===false&&x.model_activation_plan_v1_created===false&&x.active_model_version_v1_created===false&&x.active_estimator_config_v1_created===false&&x.runtime_model_activation_v1_created===false&&x.model_activation_rollback_plan_v1_created===false;
ck('baseline',c.baseline_tag==='p43_forecast_residual_monitoring_drift_detection_gate_v0_closure'&&c.baseline_commit==='3157aedb6c0b03b90bd04ee083908c190af41286');
ck('allowed_types',Array.isArray(c.allowed_created_fact_types)&&c.allowed_created_fact_types.length===6);
ck('doc_count',fs.readdirSync('docs/twin_kernel').filter(x=>x.startsWith('P44_')).length===21);
ck('script_count',fs.readdirSync('scripts/twin_kernel').filter(x=>x.startsWith('P44_')).length===3);
ck('task_file',fs.existsSync('docs/tasks/P44-Calibration-Promotion-Active-Model-Activation-Gate-v0.md'));
ck('dry_stable',dry.determinism_hash===dry2.determinism_hash);
ck('dry_none',none(dry));
ck('review_none',none(rev));
ck('pointer_none',none(ptr));
ck('write_review',wr.model_activation_review_v1_created===true);
ck('write_plan',wr.model_activation_plan_v1_created===true);
ck('write_model',wr.active_model_version_v1_created===true);
ck('write_config',wr.active_estimator_config_v1_created===true);
ck('write_runtime',wr.runtime_model_activation_v1_created===true);
ck('write_rollback',wr.model_activation_rollback_plan_v1_created===true);
ck('write_atomic',wr.atomic_model_activation_record_set_created===true);
ck('ledger',wr.ledger_only===true&&fs.existsSync('acceptance-output/P44_CONTROLLED_MODEL_ACTIVATION_LEDGER.jsonl'));
ck('ledger_rows',fs.readFileSync('acceptance-output/P44_CONTROLLED_MODEL_ACTIVATION_LEDGER.jsonl','utf8').trim().split('\n').length===6);
ck('ids',!!(wr.model_activation_review_id&&wr.model_activation_plan_id&&wr.active_model_version_id&&wr.active_estimator_config_id&&wr.runtime_model_activation_id&&wr.model_activation_rollback_plan_id));
ck('p39_sources',!!(wr.source_estimator_model_version_candidate_id&&wr.source_shadow_estimator_config_id&&wr.source_shadow_forecast_run_id&&wr.source_shadow_model_evaluation_id));
ck('p43_sources',!!(wr.source_forecast_residual_id&&wr.source_prediction_error_window_id&&wr.source_drift_signal_id&&wr.source_model_performance_monitor_id));
ck('previous_refs',!!(wr.previous_active_model_version_ref&&wr.previous_active_estimator_config_ref&&wr.previous_runtime_model_activation_ref));
ck('pointer_refs',!!(wr.active_model_pointer_before_ref&&wr.active_model_pointer_after_ref&&wr.active_config_pointer_before_ref&&wr.active_config_pointer_after_ref));
ck('states',!!(wr.activation_review_state&&wr.activation_plan_state&&wr.active_model_version_state&&wr.active_estimator_config_state&&wr.runtime_model_activation_state&&wr.rollback_plan_state));
ck('scope_hashes',!!(wr.activation_scope_hash&&wr.activation_review_hash&&wr.p39_candidate_record_set_hash&&wr.p43_monitoring_record_set_hash&&wr.previous_active_record_set_hash));
ck('window_canary',!!(wr.activation_window_start_ts&&wr.activation_window_end_ts&&wr.canary_enabled===true));
ck('future_p42',wr.eligible_for_future_p42_runtime_forecast_ref===true);
ck('nonclaim_reco',wr.not_sufficient_to_create_recommendation===true);
ck('nonclaim_action',wr['not_sufficient_to_create_'+'ac'+'tion']===true);
ck('nonclaim_roi',wr.not_sufficient_to_create_roi===true);
ck('nonclaim_memory',wr.not_sufficient_to_create_field_memory===true);
ck('chain_review',!!wr.model_activation_review_chain_hash);
ck('chain_plan',!!wr.model_activation_plan_chain_hash);
ck('chain_model',!!wr.active_model_version_chain_hash);
ck('chain_config',!!wr.active_estimator_config_chain_hash);
ck('chain_runtime',!!wr.runtime_model_activation_chain_hash);
ck('chain_rollback',!!wr.model_activation_rollback_plan_chain_hash);
ck('chain_mode',ch.chain_ok===true&&ch.previous_records_unchanged===true);
ck('forbidden_zero',wr.forbidden_downstream_fact_count===0);
ck('review_stage',r.completion_status==='implementation_ready_for_review'&&r.final_closure_status==='not_started');
const blocked=['missing_p39_candidate_record_set','missing_p43_monitoring_record_set','missing_previous_active_record_set','candidate_not_registered','shadow_config_missing','shadow_forecast_missing','shadow_evaluation_missing','shadow_evaluation_not_eligible','candidate_hash_mismatch','p43_residual_missing','p43_drift_signal_missing','p43_monitor_missing','p43_monitoring_hash_mismatch','missing_previous_active_model_ref','missing_previous_active_config_ref','missing_previous_runtime_activation_ref','missing_model_activation_authorization','missing_human_model_activation_approval','human_approval_scope_mismatch','human_approval_expired','missing_rollback_plan','missing_rollback_authorization','rollback_target_previous_active_missing','rollback_window_missing','missing_activation_scope_policy','global_activation_blocked','cross_tenant_activation_blocked','subject_scope_expansion_blocked','missing_activation_window_policy','unbounded_activation_window_blocked','activation_before_approval_blocked','missing_canary_policy','missing_pointer_switch_policy','non_atomic_pointer_switch_blocked','missing_runtime_compatibility_policy','incompatible_estimator_family','incompatible_config_namespace','missing_runtime_consumption_ref','auto_activation_language_blocked','best_model_language_blocked','model_superiority_language_blocked','calibration_execution_language_blocked','training_language_blocked','parameter_delta_language_blocked','recommendation_language_blocked','ac'+'tion_language_blocked','ao_act_language_blocked','roi_language_blocked','effect_attribution_language_blocked','field_memory_language_blocked','learning_language_blocked','implicit_latest_candidate_lookup_blocked','implicit_latest_drift_lookup_blocked','implicit_best_model_selection_blocked','implicit_active_pointer_lookup_blocked'];
for(const f of blocked){const x=R(['--fixture',f]);ck('blocked_'+f,x.ok&&x.result_state==='BLOCKED_'+f&&none(x));}
const failed=C.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P44_ALL_ACCEPTANCE',phase:'P44',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:C.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_review_determinism_hash:rev.determinism_hash,controlled_pointer_determinism_hash:ptr.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_activation_chain_hash:ch.first_activation_chain_hash,second_activation_chain_hash:ch.second_activation_chain_hash},null,2));
if(!ok)process.exit(1);
