// scripts/twin_kernel/P44_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs');
const cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P44_21_CONTROLLED_MODEL_ACTIVATION_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const C=[];const ck=(n,v)=>C.push([n,!!v]);
const c=J('docs/twin_kernel/P44_CALIBRATION_PROMOTION_ACTIVE_MODEL_ACTIVATION_CONTRACT_V0.json');
const p39=J('docs/twin_kernel/P44_SOURCE_P39_CANDIDATE_SHADOW_EVALUATION_RECORD_SET_BOUNDARY_POLICY_V0.json');
const p43=J('docs/twin_kernel/P44_SOURCE_P43_RESIDUAL_DRIFT_MONITOR_RECORD_SET_BOUNDARY_POLICY_V0.json');
const prev=J('docs/twin_kernel/P44_PREVIOUS_ACTIVE_MODEL_CONFIG_PRESERVATION_POLICY_V0.json');
const roll=J('docs/twin_kernel/P44_ROLLBACK_PLAN_POLICY_V0.json');
const scope=J('docs/twin_kernel/P44_ACTIVATION_SCOPE_POLICY_V0.json');
const win=J('docs/twin_kernel/P44_ACTIVATION_WINDOW_CANARY_POLICY_V0.json');
const ptr=J('docs/twin_kernel/P44_ACTIVE_POINTER_SWITCH_POLICY_V0.json');
const hum=J('docs/twin_kernel/P44_HUMAN_MODEL_ACTIVATION_GOVERNANCE_POLICY_V0.json');
const compat=J('docs/twin_kernel/P44_RUNTIME_COMPATIBILITY_POLICY_V0.json');
const nd=J('docs/twin_kernel/P44_NO_RECOMMENDATION_NO_ACTION_NO_ROI_NO_FIELD_MEMORY_POLICY_V0.json');
const schemas=['P44_MODEL_ACTIVATION_REVIEW_SCHEMA_V0.json','P44_MODEL_ACTIVATION_PLAN_SCHEMA_V0.json','P44_ACTIVE_MODEL_VERSION_SCHEMA_V0.json','P44_ACTIVE_ESTIMATOR_CONFIG_SCHEMA_V0.json','P44_RUNTIME_MODEL_ACTIVATION_SCHEMA_V0.json','P44_MODEL_ACTIVATION_ROLLBACK_PLAN_SCHEMA_V0.json'].map(x=>J('docs/twin_kernel/'+x));
const r=J('docs/twin_kernel/P44_CALIBRATION_PROMOTION_ACTIVE_MODEL_ACTIVATION_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),rev=R(['--mode','controlled-activation-review']),psw=R(['--mode','controlled-pointer-switch']),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-activation-chain']);
const none=x=>x.model_activation_review_v1_created===false&&x.model_activation_plan_v1_created===false&&x.active_model_version_v1_created===false&&x.active_estimator_config_v1_created===false&&x.runtime_model_activation_v1_created===false&&x.model_activation_rollback_plan_v1_created===false;
ck('baseline',c.baseline_tag==='p43_forecast_residual_monitoring_drift_detection_gate_v0_closure'&&c.baseline_commit==='3157aedb6c0b03b90bd04ee083908c190af41286');
ck('contract_inherited',c.p43_closure_inherited_facts&&c.p43_closure_inherited_facts.p43_closure_tag_exists===true&&c.p43_closure_inherited_facts.p43_final_closure_status==='final_tag_main_verified');
ck('contract_gate',c.p44_is_controlled_activation_record_gate===true&&c.p44_is_not_auto_activation===true&&c.p44_is_not_best_model_selection===true);
ck('contract_no_downstream',c.p44_is_not_recommendation&&c.p44_is_not_action&&c.p44_is_not_roi&&c.p44_is_not_field_memory);
ck('contract_allowed_forbidden',c.allowed_created_fact_types.length===6&&c.forbidden_created_fact_types.includes('recommendation_candidate_v1')&&c.forbidden_created_fact_types.includes('training_run_v1'));
ck('contract_required_refs',c.previous_active_required&&c.rollback_required&&c.human_activation_required&&c.activation_scope_required&&c.activation_window_required&&c.pointer_switch_policy_required&&c.runtime_compatibility_required);
ck('contract_ledger',c.controlled_write_only_writes_controlled_model_activation_ledger_v0===true);
ck('p39_policy',p39.required_p39_records.length===4&&p39.p39_candidate_hash_required&&p39.tenant_project_group_subject_must_match_across_p39_record_set&&p39.shadow_evaluation_eligibility_required);
ck('p39_nonclaims',p39.p39_candidate_registered_is_not_active_model&&p39.p39_shadow_config_registered_is_not_active_config&&p39.p39_shadow_evaluation_eligible_is_not_activation_authorization);
ck('p39_blocks',p39.missing_shadow_evaluation_blocks_activation&&p39.candidate_record_hash_mismatch_blocks_activation&&p39.shadow_evaluation_with_forbidden_claims_blocks_activation);
ck('p43_policy',p43.required_p43_records.length===4&&p43.p43_residual_hash_required&&p43.p43_drift_signal_hash_required&&p43.tenant_project_group_subject_must_match_across_p43_record_set);
ck('p43_nonclaims',p43.drift_signal_does_not_force_activation&&p43.p43_strong_drift_signal_is_not_calibration_required&&p43.p43_model_performance_monitor_is_not_model_ranking&&p43.p43_residual_is_not_model_failure);
ck('p43_blocks',p43.missing_forecast_residual_blocks_activation&&p43.p43_monitoring_hash_mismatch_blocks_activation&&p43.p43_monitoring_scope_mismatch_blocks_activation);
ck('previous_policy',prev.previous_active_model_version_ref_required&&prev.previous_active_estimator_config_ref_required&&prev.previous_runtime_model_activation_ref_required&&prev.previous_active_model_hash_required&&prev.previous_active_record_must_not_be_mutated&&prev.previous_active_hash_mismatch_blocks_activation);
ck('rollback_policy',roll.rollback_target_previous_active_model_ref_required&&roll.rollback_target_previous_active_config_ref_required&&roll.rollback_target_previous_runtime_activation_ref_required&&roll.rollback_plan_authorization_ref_required&&roll.rollback_window_policy_ref_required&&roll.rollback_trigger_policy_ref_required&&roll.rollback_operator_policy_ref_required&&roll.rollback_execution_requires_future_explicit_gate);
ck('scope_policy',scope.activation_scope_policy_ref_required&&scope.activation_scope_hash_required&&scope.global_activation_forbidden_by_default&&scope.subject_scope_expansion_blocked);
ck('window_policy',win.activation_window_policy_ref_required&&win.activation_window_must_be_finite&&win.canary_activation_policy_ref_required&&win.canary_promotion_requires_future_review&&win.activation_before_approval_blocked);
ck('pointer_policy',ptr.active_pointer_switch_policy_ref_required&&ptr.active_pointer_switch_is_recorded_not_executed_in_runtime&&ptr.runtime_model_activation_does_not_mutate_live_runtime_pointer&&ptr.non_atomic_pointer_switch_blocked);
ck('human_policy',hum.human_model_activation_approval_ref_required&&hum.human_approval_identity_ref_required&&hum.human_approval_scope_hash_required&&hum.auto_activation_forbidden&&hum.human_approval_must_not_authorize_ao_act);
ck('compat_policy',compat.runtime_compatibility_policy_ref_required&&compat.active_model_version_must_include_runtime_consumption_ref&&compat.missing_runtime_consumption_ref_blocks_activation&&compat.future_p42_must_revalidate_new_active_refs);
ck('no_downstream_policy',nd.recommendation_candidate_v1_created===false&&nd.ao_act_task_v0_created===false&&nd.roi_realization_v1_created===false&&nd.effect_attribution_v1_created===false&&nd.field_memory_record_v1_created===false&&nd.training_run_v1_created===false&&nd.learning_signal_v1_created===false&&nd.forbidden_semantic_claims.includes('model_superior'));
for(const s of schemas){ck('schema_'+s.object_type,Array.isArray(s.required_fields)&&s.required_fields.length>=20&&s.required_fields.includes('determinism_hash')&&s.required_fields.includes('idempotency_key'));}
ck('file_set',fs.readdirSync('docs/twin_kernel').filter(x=>x.startsWith('P44_')).length===21&&fs.readdirSync('scripts/twin_kernel').filter(x=>x.startsWith('P44_')).length===3);
ck('dry_stable',dry.determinism_hash===dry2.determinism_hash);
ck('dry_none',none(dry)&&none(rev)&&none(psw));
ck('write_six',wr.model_activation_review_v1_created&&wr.model_activation_plan_v1_created&&wr.active_model_version_v1_created&&wr.active_estimator_config_v1_created&&wr.runtime_model_activation_v1_created&&wr.model_activation_rollback_plan_v1_created);
ck('ledger',wr.ledger_only===true&&fs.existsSync('acceptance-output/P44_CONTROLLED_MODEL_ACTIVATION_LEDGER.jsonl')&&fs.readFileSync('acceptance-output/P44_CONTROLLED_MODEL_ACTIVATION_LEDGER.jsonl','utf8').trim().split('\n').length===6);
ck('runner_refs',!!(wr.source_estimator_model_version_candidate_id&&wr.source_shadow_estimator_config_id&&wr.source_forecast_residual_id&&wr.source_drift_signal_id&&wr.previous_active_model_version_ref&&wr.active_model_pointer_before_ref&&wr.active_model_pointer_after_ref));
ck('runner_hashes',!!(wr.activation_scope_hash&&wr.activation_review_hash&&wr.p39_candidate_record_set_hash&&wr.p43_monitoring_record_set_hash&&wr.previous_active_record_set_hash&&wr.model_activation_review_chain_hash&&wr.runtime_model_activation_chain_hash));
ck('runner_nonclaims',wr.eligible_for_future_p42_runtime_forecast_ref===true&&wr.not_sufficient_to_create_recommendation===true&&wr['not_sufficient_to_create_'+'ac'+'tion']===true&&wr.not_sufficient_to_create_roi===true&&wr.not_sufficient_to_create_field_memory===true);
ck('chain_mode',ch.chain_ok===true&&ch.previous_records_unchanged===true);
ck('forbidden_zero',wr.forbidden_downstream_fact_count===0);
ck('review_stage',(r.completion_status==='implementation_ready_for_review'&&r.final_closure_status==='not_started')||(r.completion_status==='complete'&&r.final_closure_status==='final_tag_main_verified'&&r.final_commit==='72ec24dd0384757524b916f33483eadad5dd1973'));
for(const f of ['missing_p39_candidate_record_set','missing_p43_monitoring_record_set','missing_previous_active_record_set','missing_human_model_activation_approval','missing_rollback_plan','global_activation_blocked','missing_runtime_compatibility_policy','recommendation_language_blocked','ao_act_language_blocked']){const x=R(['--fixture',f]);ck('blocked_'+f,x.ok&&x.result_state==='BLOCKED_'+f&&none(x));}
const failed=C.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P44_ALL_ACCEPTANCE',phase:'P44',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:C.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_review_determinism_hash:rev.determinism_hash,controlled_pointer_determinism_hash:psw.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_activation_chain_hash:ch.first_activation_chain_hash,second_activation_chain_hash:ch.second_activation_chain_hash},null,2));
if(!ok)process.exit(1);
