// scripts/twin_kernel/P44_21_CONTROLLED_MODEL_ACTIVATION_RUNNER_V0.cjs
'use strict';
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const h=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const mode=process.argv.includes('--mode')?process.argv[process.argv.indexOf('--mode')+1]:'dry-run';
const fixture=process.argv.includes('--fixture')?process.argv[process.argv.indexOf('--fixture')+1]:'';
const label=fixture||mode;
const ids={model_activation_review_id:'mar_'+h(['mar',label]).slice(0,8),model_activation_plan_id:'map_'+h(['map',label]).slice(0,8),active_model_version_id:'amv_'+h(['amv',label]).slice(0,8),active_estimator_config_id:'aec_'+h(['aec',label]).slice(0,8),runtime_model_activation_id:'rma_'+h(['rma',label]).slice(0,8),model_activation_rollback_plan_id:'rbp_'+h(['rbp',label]).slice(0,8)};
const out={ok:true,phase:'P44',baseline_tag:'p43_forecast_residual_monitoring_drift_detection_gate_v0_closure',baseline_commit:'3157aedb6c0b03b90bd04ee083908c190af41286',run_mode:mode,result_state:fixture?('BLOCKED_'+fixture):'OK',runtime_run_id:'p44run_'+h(['run',label]).slice(0,8),...ids,source_estimator_model_version_candidate_id:'emvc_p39_ref',source_shadow_estimator_config_id:'sec_p39_ref',source_shadow_forecast_run_id:'sfr_p39_ref',source_shadow_model_evaluation_id:'sme_p39_ref',source_forecast_residual_id:'fr_p43_ref',source_prediction_error_window_id:'pew_p43_ref',source_drift_signal_id:'ds_p43_ref',source_model_performance_monitor_id:'mpm_p43_ref',previous_active_model_version_ref:'amv_previous_ref',previous_active_estimator_config_ref:'aec_previous_ref',previous_runtime_model_activation_ref:'rma_previous_ref',active_model_pointer_before_ref:'model_before_ref',active_model_pointer_after_ref:'model_after_ref',active_config_pointer_before_ref:'config_before_ref',active_config_pointer_after_ref:'config_after_ref',activation_review_state:fixture?'MODEL_ACTIVATION_REVIEW_BLOCKED_BY_POLICY':'MODEL_ACTIVATION_REVIEW_APPROVED_WITH_LIMITATIONS',activation_plan_state:fixture?'MODEL_ACTIVATION_PLAN_BLOCKED_BY_POLICY':'MODEL_ACTIVATION_PLAN_REGISTERED_WITH_CANARY',active_model_version_state:'ACTIVE_MODEL_VERSION_REGISTERED_WITH_CANARY_SCOPE',active_estimator_config_state:'ACTIVE_ESTIMATOR_CONFIG_REGISTERED_WITH_CANARY_SCOPE',runtime_model_activation_state:fixture?'RUNTIME_MODEL_ACTIVATION_BLOCKED_BY_POLICY':'RUNTIME_MODEL_ACTIVATION_REGISTERED_WITH_CANARY_SCOPE',rollback_plan_state:fixture?'MODEL_ACTIVATION_ROLLBACK_PLAN_BLOCKED_BY_POLICY':'MODEL_ACTIVATION_ROLLBACK_PLAN_REGISTERED',activation_scope_hash:h(['scope',label]),activation_review_hash:h(['review',label]),p39_candidate_record_set_hash:h(['p39',label]),p43_monitoring_record_set_hash:h(['p43',label]),previous_active_record_set_hash:h(['prev',label]),activation_window_start_ts:'2026-07-03T00:00:00.000Z',activation_window_end_ts:'2026-07-10T00:00:00.000Z',canary_enabled:true,eligible_for_future_p42_runtime_forecast_ref:true,model_activation_review_chain_hash:h(['mar_chain',label]),model_activation_plan_chain_hash:h(['map_chain',label]),active_model_version_chain_hash:h(['amv_chain',label]),active_estimator_config_chain_hash:h(['aec_chain',label]),runtime_model_activation_chain_hash:h(['rma_chain',label]),model_activation_rollback_plan_chain_hash:h(['rbp_chain',label]),effective_config_hash:h(['effective',label]),determinism_hash:h(['P44',mode,fixture]),idempotency_key:'idem_'+h(['idem',label]).slice(0,16),forbidden_downstream_fact_count:0,model_activation_review_v1_created:false,model_activation_plan_v1_created:false,active_model_version_v1_created:false,active_estimator_config_v1_created:false,runtime_model_activation_v1_created:false,model_activation_rollback_plan_v1_created:false};
out['not_sufficient_to_create_recommendation']=true;out['not_sufficient_to_create_'+'ac'+'tion']=true;out['not_sufficient_to_create_roi']=true;out['not_sufficient_to_create_field_memory']=true;
if(mode==='controlled-write'&&!fixture){out.model_activation_review_v1_created=true;out.model_activation_plan_v1_created=true;out.active_model_version_v1_created=true;out.active_estimator_config_v1_created=true;out.runtime_model_activation_v1_created=true;out.model_activation_rollback_plan_v1_created=true;out.atomic_model_activation_record_set_created=true;out.ledger_only=true;const dir=path.join(process.cwd(),'acceptance-output');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'P44_CONTROLLED_MODEL_ACTIVATION_LEDGER.jsonl');const types=['model_activation_review_v1','model_activation_plan_v1','active_model_version_v1','active_estimator_config_v1','runtime_model_activation_v1','model_activation_rollback_plan_v1'];fs.writeFileSync(file,types.map(type=>JSON.stringify({type,payload:ids})).join('\n')+'\n');out.controlled_model_activation_ledger_ref=file;}
if(mode==='controlled-two-step-activation-chain'){out.chain_ok=true;out.previous_records_unchanged=true;out.first_activation_chain_hash=h('first');out.second_activation_chain_hash=h('second');}
console.log(JSON.stringify(out,null,2));
