// scripts/twin_kernel/P45_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs');
const cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P45_20_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const C=[];const ck=(n,v)=>C.push([n,!!v]);
const c=J('docs/twin_kernel/P45_POST_ACTIVATION_RUNTIME_OBSERVABILITY_ROLLBACK_READINESS_CONTRACT_V0.json');
const p44=J('docs/twin_kernel/P45_SOURCE_P44_ACTIVATION_RECORD_SET_BOUNDARY_POLICY_V0.json');
const rs=J('docs/twin_kernel/P45_RUNTIME_CONSUMPTION_SOURCE_BOUNDARY_POLICY_V0.json');
const scope=J('docs/twin_kernel/P45_RUNTIME_CONSUMPTION_SCOPE_POLICY_V0.json');
const nyc=J('docs/twin_kernel/P45_NOT_YET_CONSUMED_ACTIVATION_READBACK_POLICY_V0.json');
const sw=J('docs/twin_kernel/P45_ACTIVATION_SCOPE_WINDOW_READBACK_POLICY_V0.json');
const can=J('docs/twin_kernel/P45_ACTIVATION_CANARY_READBACK_POLICY_V0.json');
const rb=J('docs/twin_kernel/P45_ROLLBACK_READINESS_POLICY_V0.json');
const p46=J('docs/twin_kernel/P45_P46_FUTURE_RECOMMENDATION_CONTEXT_ELIGIBILITY_BOUNDARY_POLICY_V0.json');
const idem=J('docs/twin_kernel/P45_IDEMPOTENCY_POLICY_V0.json');
const det=J('docs/twin_kernel/P45_DETERMINISM_POLICY_V0.json');
const chain=J('docs/twin_kernel/P45_APPEND_ONLY_OBSERVABILITY_CHAIN_POLICY_V0.json');
const nd=J('docs/twin_kernel/P45_NO_ROLLBACK_EXECUTION_NO_MODEL_UPDATE_NO_RECOMMENDATION_NO_ACTION_POLICY_V0.json');
const schemas=['P45_RUNTIME_ACTIVATION_OBSERVABILITY_REPORT_SCHEMA_V0.json','P45_ACTIVE_MODEL_RUNTIME_CONSUMPTION_SNAPSHOT_SCHEMA_V0.json','P45_ACTIVATION_SCOPE_WINDOW_READBACK_SCHEMA_V0.json','P45_ACTIVATION_CANARY_READBACK_SCHEMA_V0.json','P45_ACTIVATION_ROLLBACK_READINESS_REPORT_SCHEMA_V0.json'].map(x=>J('docs/twin_kernel/'+x));
const r=J('docs/twin_kernel/P45_POST_ACTIVATION_RUNTIME_OBSERVABILITY_ROLLBACK_READINESS_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),obs=R(['--mode','controlled-observability']),con=R(['--mode','controlled-consumption-readback']),rr=R(['--mode','controlled-rollback-readiness']),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-observability-chain']);
const none=x=>x.runtime_activation_observability_report_v1_created===false&&x.active_model_runtime_consumption_snapshot_v1_created===false&&x.activation_scope_window_readback_v1_created===false&&x.activation_canary_readback_v1_created===false&&x.activation_rollback_readiness_report_v1_created===false;
ck('baseline',c.baseline_tag==='p44_calibration_promotion_active_model_activation_gate_v0_closure'&&c.baseline_commit==='01f09751c7caace409a0d53459a7fcf56378fdb7');
ck('contract_inherited',c.p44_closure_inherited_facts&&c.p44_closure_inherited_facts.p44_closure_tag_exists===true);
ck('contract_gate',c.p45_is_controlled_post_activation_observability_record_gate&&c.observed_runtime_consumption_is_readback_sample_not_runtime_truth&&c.p44_runtime_model_activation_is_pointer_switch_intent_not_live_pointer_mutation);
ck('contract_types',c.allowed_created_fact_types.length===5&&c.forbidden_created_fact_types.includes('runtime_model_update_v1')&&c.forbidden_created_fact_types.includes('ao_act_task_v0'));
ck('contract_ledger',c.controlled_write_only_writes_controlled_post_activation_observability_ledger_v0===true);
ck('contract_no_services',c.operator_alert_v1_created===false&&c.runtime_observability_service_deployed===false&&c.background_observability_daemon_created===false);
ck('p44_source_policy',p44.required_p44_records.length===6&&p44.p45_must_not_create_p44_activation_records&&p44.p44_activation_record_set_not_approved_blocks_p45);
ck('runtime_source_policy',rs.runtime_consumption_refs_must_be_pointer_only&&rs.runtime_consumption_active_model_ref_must_match_p44_active_model_pointer_after_ref&&rs.runtime_consumption_observation_is_not_runtime_truth);
ck('scope_policy',scope.cross_tenant_consumption_blocked&&scope.subject_scope_expansion_blocked&&scope.active_model_ref_mismatch_recorded_as_policy_mismatch);
ck('not_yet_consumed_policy',nyc.not_yet_consumed_mode_allowed&&nyc.not_yet_consumed_mode_creates_all_five_records_atomically&&nyc.not_yet_consumed_mode_is_not_failure);
ck('scope_window_policy',sw.activation_scope_hash_must_match_p44&&sw.activation_scope_window_readback_v1_is_not_active_pointer_mutation);
ck('canary_policy',can.canary_readback_does_not_promote_canary&&can.activation_canary_readback_v1_is_not_model_success);
ck('readiness_policy',rb.rollback_readiness_verified_does_not_execute_rollback&&rb.rollback_execution_requires_future_explicit_gate&&rb.previous_active_record_mutation_detected_blocks_p45);
ck('future_policy',p46.eligible_as_future_recommendation_context_ref_is_only_future_eligibility_marker&&p46.future_p46_must_revalidate_all_p45_records);
ck('idempotency_policy',idem.idempotency_key_required&&idem.same_activation_same_consumption_scope_duplicate_observability_blocked);
ck('determinism_policy',det.determinism_hash_required&&det.implicit_latest_activation_lookup_forbidden&&det.implicit_live_pointer_lookup_forbidden);
ck('chain_policy',chain.runtime_activation_observability_report_chain_hash_required&&chain.activation_rollback_readiness_report_chain_hash_required);
ck('no_downstream_policy',nd.runtime_model_update_v1_created===false&&nd.recommendation_candidate_v1_created===false&&nd.ao_act_task_v0_created===false&&nd.roi_realization_v1_created===false&&nd.learning_signal_v1_created===false&&nd.forbidden_downstream_fact_count_must_be_zero===true);
for(const s of schemas){ck('schema_'+s.object_type,Array.isArray(s.required_fields)&&s.required_fields.length>=25&&s.required_fields.includes('determinism_hash')&&s.required_fields.includes('idempotency_key')&&s.required_fields.some(x=>x.endsWith('chain_hash')));}
ck('file_set',fs.existsSync('docs/tasks/P45-Post-Activation-Runtime-Observability-Rollback-Readiness-Gate-v0.md')&&fs.readdirSync('docs/twin_kernel').filter(x=>x.startsWith('P45_')).length===20&&fs.readdirSync('scripts/twin_kernel').filter(x=>x.startsWith('P45_')).length===3);
ck('dry_stable',dry.determinism_hash===dry2.determinism_hash);
ck('zero_modes',none(dry)&&none(obs)&&none(con)&&none(rr));
ck('write_five',wr.runtime_activation_observability_report_v1_created&&wr.active_model_runtime_consumption_snapshot_v1_created&&wr.activation_scope_window_readback_v1_created&&wr.activation_canary_readback_v1_created&&wr.activation_rollback_readiness_report_v1_created);
ck('ledger',wr.ledger_only===true&&fs.existsSync('acceptance-output/P45_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_LEDGER.jsonl')&&fs.readFileSync('acceptance-output/P45_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_LEDGER.jsonl','utf8').trim().split('\n').length===5);
ck('runner_refs',!!(wr.source_model_activation_review_id&&wr.source_runtime_model_activation_id&&wr.source_model_activation_rollback_plan_id&&wr.expected_active_model_ref&&wr.expected_active_config_ref));
ck('runner_hashes',!!(wr.activation_scope_hash&&wr.activation_window_hash&&wr.runtime_consumption_scope_hash&&wr.p44_activation_record_set_hash&&wr.rollback_readiness_hash));
ck('runner_nonclaims',wr.eligible_as_future_recommendation_context_ref===true&&wr.not_sufficient_to_create_recommendation===true&&wr['not_sufficient_to_create_'+'ac'+'tion']===true&&wr.not_sufficient_to_create_rollback_execution===true&&wr.not_sufficient_to_create_roi===true&&wr.not_sufficient_to_create_field_memory===true);
ck('chain_mode',ch.chain_ok===true&&ch.previous_records_unchanged===true);
ck('forbidden_zero',wr.forbidden_downstream_fact_count===0);
ck('review_stage',r.completion_status==='implementation_ready_for_review'&&r.final_closure_status==='not_started');
for(const f of ['missing_p44_activation_record_set','p44_activation_record_set_mismatch','runtime_consumption_ref_not_pointer_only','cross_tenant_consumption_blocked','previous_active_record_mutation_detected','rollback_execution_language_blocked','model_update_language_blocked','recommendation_language_blocked','ao_act_language_blocked','duplicate_observability_scope_blocked','implicit_latest_activation_lookup_blocked','implicit_live_pointer_lookup_blocked']){const x=R(['--fixture',f]);ck('blocked_'+f,x.ok&&x.result_state==='BLOCKED_'+f&&none(x));}
const failed=C.filter(([,ok])=>!ok).map(([n])=>n),ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P45_ALL_ACCEPTANCE',phase:'P45',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:C.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_observability_determinism_hash:obs.determinism_hash,controlled_consumption_readback_determinism_hash:con.determinism_hash,controlled_rollback_readiness_determinism_hash:rr.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_observability_chain_hash:ch.first_observability_chain_hash,second_observability_chain_hash:ch.second_observability_chain_hash},null,2));
if(!ok)process.exit(1);
