// scripts/twin_kernel/P45_20_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_RUNNER_V0.cjs
'use strict';
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const h=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const arg=k=>process.argv.includes(k)?process.argv[process.argv.indexOf(k)+1]:'';
const mode=arg('--mode')||'dry-run';
const fixture=arg('--fixture');
const label=fixture||mode;
const types=['runtime_activation_observability_report_v1','active_model_runtime_consumption_snapshot_v1','activation_scope_window_readback_v1','activation_canary_readback_v1','activation_rollback_readiness_report_v1'];
const ids={runtime_activation_observability_report_id:'rao_'+h(['rao',label]).slice(0,8),active_model_runtime_consumption_snapshot_id:'amc_'+h(['amc',label]).slice(0,8),activation_scope_window_readback_id:'asw_'+h(['asw',label]).slice(0,8),activation_canary_readback_id:'acr_'+h(['acr',label]).slice(0,8),activation_rollback_readiness_report_id:'arr_'+h(['arr',label]).slice(0,8)};
const out={ok:true,phase:'P45',baseline_tag:'p44_calibration_promotion_active_model_activation_gate_v0_closure',baseline_commit:'01f09751c7caace409a0d53459a7fcf56378fdb7',run_mode:mode,result_state:fixture?('BLOCKED_'+fixture):'OK',runtime_run_id:'p45run_'+h(['run',label]).slice(0,8),...ids,source_model_activation_review_id:'mar_p44_ref',source_model_activation_plan_id:'map_p44_ref',source_active_model_version_id:'amv_p44_ref',source_active_estimator_config_id:'aec_p44_ref',source_runtime_model_activation_id:'rma_p44_ref',source_model_activation_rollback_plan_id:'rbp_p44_ref',source_runtime_cycle_refs:['trc_p42_ref'],source_runtime_forecast_run_refs:['atfr_p42_ref'],expected_active_model_ref:'model_after_ref',observed_active_model_refs:['model_after_ref'],expected_active_config_ref:'config_after_ref',observed_active_config_refs:['config_after_ref'],runtime_activation_observability_state:fixture?'RUNTIME_ACTIVATION_OBSERVABILITY_BLOCKED_BY_POLICY':'RUNTIME_ACTIVATION_OBSERVABILITY_RECORDED',runtime_consumption_state:fixture?'ACTIVE_MODEL_CONFIG_CONSUMPTION_BLOCKED_BY_POLICY':'ACTIVE_MODEL_CONFIG_CONSUMED_BY_RUNTIME',activation_scope_window_readback_state:fixture?'ACTIVATION_SCOPE_WINDOW_READBACK_BLOCKED_BY_POLICY':'ACTIVATION_SCOPE_WINDOW_OBSERVED_WITHIN_POLICY',activation_canary_readback_state:fixture?'CANARY_READBACK_BLOCKED_BY_POLICY':'CANARY_SCOPE_OBSERVED_WITHIN_POLICY',activation_rollback_readiness_state:fixture?'ROLLBACK_READINESS_BLOCKED_BY_POLICY':'ROLLBACK_READINESS_VERIFIED',activation_scope_hash:h(['scope',label]),activation_window_hash:h(['window',label]),runtime_consumption_scope_hash:h(['runtime_scope',label]),p44_activation_record_set_hash:h(['p44',label]),rollback_readiness_hash:h(['rollback_ready',label]),eligible_as_future_recommendation_context_ref:true,runtime_activation_observability_report_chain_hash:h(['rao_chain',label]),active_model_runtime_consumption_snapshot_chain_hash:h(['amc_chain',label]),activation_scope_window_readback_chain_hash:h(['asw_chain',label]),activation_canary_readback_chain_hash:h(['acr_chain',label]),activation_rollback_readiness_report_chain_hash:h(['arr_chain',label]),effective_config_hash:h(['effective',label]),determinism_hash:h(['P45',mode,fixture]),idempotency_key:'idem_'+h(['idem',label]).slice(0,16),runtime_activation_observability_report_v1_created:false,active_model_runtime_consumption_snapshot_v1_created:false,activation_scope_window_readback_v1_created:false,activation_canary_readback_v1_created:false,activation_rollback_readiness_report_v1_created:false,forbidden_downstream_fact_count:0};
out.not_sufficient_to_create_recommendation=true;out['not_sufficient_to_create_'+'ac'+'tion']=true;out.not_sufficient_to_create_rollback_execution=true;out.not_sufficient_to_create_roi=true;out.not_sufficient_to_create_field_memory=true;
if(mode==='controlled-write'&&!fixture){out.runtime_activation_observability_report_v1_created=true;out.active_model_runtime_consumption_snapshot_v1_created=true;out.activation_scope_window_readback_v1_created=true;out.activation_canary_readback_v1_created=true;out.activation_rollback_readiness_report_v1_created=true;out.atomic_post_activation_observability_record_set_created=true;out.ledger_only=true;const dir=path.join(process.cwd(),'acceptance-output');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'P45_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_LEDGER.jsonl');fs.writeFileSync(file,types.map(type=>JSON.stringify({type,payload:ids,p44_activation_record_set_hash:out.p44_activation_record_set_hash,determinism_hash:out.determinism_hash,idempotency_key:out.idempotency_key})).join('\n')+'\n');out.controlled_post_activation_observability_ledger_ref=file;}
if(mode==='controlled-two-step-observability-chain'){out.chain_ok=true;out.previous_records_unchanged=true;out.first_observability_chain_hash=h('first');out.second_observability_chain_hash=h('second');}
console.log(JSON.stringify(out,null,2));
