// scripts/twin_kernel/P45_ALL_ACCEPTANCE_CHECK.cjs
'use strict';
const fs=require('node:fs');
const cp=require('node:child_process');
const J=p=>JSON.parse(fs.readFileSync(p,'utf8'));
const R=a=>JSON.parse(cp.execFileSync(process.execPath,['scripts/twin_kernel/P45_20_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_RUNNER_V0.cjs',...a],{encoding:'utf8'}));
const c=J('docs/twin_kernel/P45_POST_ACTIVATION_RUNTIME_OBSERVABILITY_ROLLBACK_READINESS_CONTRACT_V0.json');
const r=J('docs/twin_kernel/P45_POST_ACTIVATION_RUNTIME_OBSERVABILITY_ROLLBACK_READINESS_COMPLETION_REVIEW_V0.json');
const dry=R([]),dry2=R([]),wr=R(['--mode','controlled-write']),ch=R(['--mode','controlled-two-step-observability-chain']);
const checks=[];const ck=(n,v)=>checks.push([n,!!v]);
ck('baseline',c.baseline_commit==='01f09751c7caace409a0d53459a7fcf56378fdb7');
ck('closure_review',r.completion_status==='complete'&&r.final_commit==='364ba6dba1aa3360676e73d285e26a8ada7781ce');
ck('allowed_five',Array.isArray(c.allowed_created_fact_types)&&c.allowed_created_fact_types.length===5);
ck('dry_stable',dry.determinism_hash===dry2.determinism_hash);
ck('write_five',wr.runtime_activation_observability_report_v1_created&&wr.active_model_runtime_consumption_snapshot_v1_created&&wr.activation_scope_window_readback_v1_created&&wr.activation_canary_readback_v1_created&&wr.activation_rollback_readiness_report_v1_created);
ck('ledger',wr.ledger_only===true&&fs.existsSync('acceptance-output/P45_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_LEDGER.jsonl')&&fs.readFileSync('acceptance-output/P45_CONTROLLED_POST_ACTIVATION_OBSERVABILITY_LEDGER.jsonl','utf8').trim().split('\n').length===5);
ck('chain',ch.chain_ok===true&&ch.previous_records_unchanged===true);
ck('zero_downstream',wr.forbidden_downstream_fact_count===0);
const failed=checks.filter(x=>!x[1]).map(x=>x[0]);
const ok=failed.length===0;
console.log(JSON.stringify({ok,acceptance:'P45_ALL_ACCEPTANCE',phase:'P45',baseline_tag:c.baseline_tag,baseline_commit:c.baseline_commit,assertion_count:checks.length,failed_assertion_count:failed.length,failed_assertions:failed,dry_run_determinism_hash:dry.determinism_hash,controlled_write_determinism_hash:wr.determinism_hash,first_observability_chain_hash:ch.first_observability_chain_hash,second_observability_chain_hash:ch.second_observability_chain_hash},null,2));
if(!ok)process.exit(1);
