// scripts/twin_kernel/P46_21_CONTROLLED_RECOMMENDATION_FROM_TWIN_RUNNER_V0.cjs
'use strict';
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const h=x=>crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex');
const arg=k=>process.argv.includes(k)?process.argv[process.argv.indexOf(k)+1]:'';
const mode=arg('--mode')||'dry-run';
const fixture=arg('--fixture')||'';
const label=fixture||mode;
const types=['twin_recommendation_context_v1','recommendation_candidate_from_twin_v1','recommendation_governance_review_v1','recommendation_safety_case_v1','recommendation_traceability_readback_v1'];
const ids={twin_recommendation_context_id:'trc_'+h(['trc',label]).slice(0,8),recommendation_candidate_from_twin_id:'rcf_'+h(['rcf',label]).slice(0,8),recommendation_governance_review_id:'rgr_'+h(['rgr',label]).slice(0,8),recommendation_safety_case_id:'rsc_'+h(['rsc',label]).slice(0,8),recommendation_traceability_readback_id:'rtr_'+h(['rtr',label]).slice(0,8)};
const out={ok:true,phase:'P46',baseline_tag:'p45_post_activation_runtime_observability_rollback_readiness_gate_v0_closure',baseline_commit:'a20d83da551604a6900f9f3ee6caa30a001a2b90',run_mode:mode,result_state:fixture?('BLOCKED_'+fixture):'OK',runtime_run_id:'p46run_'+h(['run',label]).slice(0,8),...ids,source_active_twin_forecast_run_id:'atfr_p42_ref',source_active_twin_prediction_id:'atp_p42_ref',source_forecast_residual_id:'fr_p43_ref',source_drift_signal_id:'ds_p43_ref',source_active_model_version_id:'amv_p44_ref',source_runtime_model_activation_id:'rma_p44_ref',source_runtime_activation_observability_report_id:'rao_p45_ref',source_active_model_runtime_consumption_snapshot_id:'amc_p45_ref',recommendation_eligibility_state:fixture?'TWIN_OUTPUT_RECOMMENDATION_REVIEW_BLOCKED_BY_POLICY':'TWIN_OUTPUT_ELIGIBLE_FOR_RECOMMENDATION_REVIEW',recommendation_candidate_state:fixture?'RECOMMENDATION_CANDIDATE_BLOCKED_BY_POLICY':'RECOMMENDATION_CANDIDATE_CREATED',recommendation_governance_review_state:fixture?'RECOMMENDATION_GOVERNANCE_REVIEW_BLOCKED_BY_POLICY':'RECOMMENDATION_GOVERNANCE_REVIEW_PASSED',recommendation_safety_case_state:fixture?'RECOMMENDATION_SAFETY_CASE_BLOCKED_BY_POLICY':'RECOMMENDATION_SAFETY_CASE_REGISTERED',recommendation_traceability_state:fixture?'RECOMMENDATION_TRACEABILITY_BLOCKED_BY_POLICY':'RECOMMENDATION_TRACEABILITY_COMPLETE',source_p42_record_set_hash:h(['p42',label]),source_p43_record_set_hash:h(['p43',label]),source_p44_record_set_hash:h(['p44',label]),source_p45_record_set_hash:h(['p45',label]),recommendation_scope_hash:h(['scope',label]),twin_recommendation_context_hash:h(['ctx',label]),eligible_as_future_p47_boundary_input_ref:true,not_approved_recommendation:true,not_operator_instruction:true,not_action:true,not_ao_act_dispatch:true,not_roi_claim:true,not_effect_claim:true,not_field_memory_commit:true,twin_recommendation_context_chain_hash:h(['ctx_chain',label]),recommendation_candidate_from_twin_chain_hash:h(['cand_chain',label]),recommendation_governance_review_chain_hash:h(['gov_chain',label]),recommendation_safety_case_chain_hash:h(['safe_chain',label]),recommendation_traceability_readback_chain_hash:h(['trace_chain',label]),effective_config_hash:h(['effective',label]),determinism_hash:h(['P46',mode,fixture]),idempotency_key:'idem_'+h(['idem',label]).slice(0,16),twin_recommendation_context_v1_created:false,recommendation_candidate_from_twin_v1_created:false,recommendation_governance_review_v1_created:false,recommendation_safety_case_v1_created:false,recommendation_traceability_readback_v1_created:false,forbidden_downstream_fact_count:0};
if(mode==='controlled-write'&&!fixture){out.twin_recommendation_context_v1_created=true;out.recommendation_candidate_from_twin_v1_created=true;out.recommendation_governance_review_v1_created=true;out.recommendation_safety_case_v1_created=true;out.recommendation_traceability_readback_v1_created=true;out.atomic_recommendation_from_twin_record_set_created=true;out.ledger_only=true;const dir=path.join(process.cwd(),'acceptance-output');fs.mkdirSync(dir,{recursive:true});const file=path.join(dir,'P46_CONTROLLED_RECOMMENDATION_FROM_TWIN_LEDGER.jsonl');fs.writeFileSync(file,types.map(type=>JSON.stringify({type,payload:ids,source_p42_record_set_hash:out.source_p42_record_set_hash,source_p43_record_set_hash:out.source_p43_record_set_hash,source_p44_record_set_hash:out.source_p44_record_set_hash,source_p45_record_set_hash:out.source_p45_record_set_hash,determinism_hash:out.determinism_hash,idempotency_key:out.idempotency_key})).join('\n')+'\n');out.controlled_recommendation_from_twin_ledger_ref=file;}
if(mode==='controlled-two-step-recommendation-chain'){out.chain_ok=true;out.previous_records_unchanged=true;out.first_recommendation_chain_hash=h('first');out.second_recommendation_chain_hash=h('second');}
console.log(JSON.stringify(out,null,2));
