-- Ensure report projections can rely on decision_recommendation_v1.payload.summary
-- even when the canonical human explanation is written under payload.explain.human.
-- This keeps existing report aggregation compatible with formal recommendation facts
-- generated by controlled pilot and production decision chains.

CREATE OR REPLACE FUNCTION normalize_decision_recommendation_summary_v1()
RETURNS trigger AS $$
DECLARE
  human text;
BEGIN
  IF NEW.record_json IS NOT NULL
     AND NEW.record_json->>'type' = 'decision_recommendation_v1'
     AND NULLIF(BTRIM(COALESCE(NEW.record_json#>>'{payload,summary}', '')), '') IS NULL
     AND NULLIF(BTRIM(COALESCE(NEW.record_json#>>'{payload,explain,human}', '')), '') IS NOT NULL
  THEN
    human := BTRIM(NEW.record_json#>>'{payload,explain,human}');
    NEW.record_json := jsonb_set(NEW.record_json, '{payload,summary}', to_jsonb(human), true);
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS facts_decision_recommendation_summary_normalize_v1 ON facts;

CREATE TRIGGER facts_decision_recommendation_summary_normalize_v1
BEFORE INSERT OR UPDATE OF record_json ON facts
FOR EACH ROW
EXECUTE FUNCTION normalize_decision_recommendation_summary_v1();

UPDATE facts
   SET record_json = jsonb_set(
     record_json,
     '{payload,summary}',
     to_jsonb(BTRIM(record_json#>>'{payload,explain,human}')),
     true
   )
 WHERE record_json->>'type' = 'decision_recommendation_v1'
   AND NULLIF(BTRIM(COALESCE(record_json#>>'{payload,summary}', '')), '') IS NULL
   AND NULLIF(BTRIM(COALESCE(record_json#>>'{payload,explain,human}', '')), '') IS NOT NULL;
