export type ApiRouteInventoryAudienceV1 = "customer" | "operator" | "admin" | "internal" | "legacy" | "system";
export type ApiRouteInventoryBoundaryV1 = "official" | "compat" | "debug" | "internal";
export type ApiRouteInventoryPathMatchV1 = "exact" | "group";

export type ApiRouteInventoryEntryV1 = {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "ANY";
  route_path: string;
  route_group: string;
  path_match: ApiRouteInventoryPathMatchV1;
  owner: string;
  audience: ApiRouteInventoryAudienceV1;
  boundary: ApiRouteInventoryBoundaryV1;
  guarded_projection: boolean;
  customer_navigation_allowed: boolean;
  fallback_allowed: boolean;
  write_requires_backend_validation: boolean;
  audit_required: boolean;
};

export const API_ROUTE_INVENTORY: ApiRouteInventoryEntryV1[] = [
  {
    id: "customer-dashboard-aggregate-v1",
    method: "GET",
    route_path: "/api/v1/reports/customer-dashboard/aggregate",
    route_group: "customer-reports.dashboard",
    path_match: "exact",
    owner: "reporting-service",
    audience: "customer",
    boundary: "official",
    guarded_projection: true,
    customer_navigation_allowed: true,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "customer-field-report-v1",
    method: "GET",
    route_path: "/api/v1/reports/field/:field_id",
    route_group: "customer-reports.field",
    path_match: "exact",
    owner: "reporting-service",
    audience: "customer",
    boundary: "official",
    guarded_projection: true,
    customer_navigation_allowed: true,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "customer-operation-report-v1",
    method: "GET",
    route_path: "/api/v1/reports/operation/:operation_id",
    route_group: "customer-reports.operation",
    path_match: "exact",
    owner: "reporting-service",
    audience: "customer",
    boundary: "official",
    guarded_projection: true,
    customer_navigation_allowed: true,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "sensing-raw-samples-write-v1",
    method: "POST",
    route_path: "/api/v1/sensing/raw-samples",
    route_group: "sensing.raw-samples",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "sensing-raw-samples-read-v1",
    method: "GET",
    route_path: "/api/v1/sensing/raw-samples",
    route_group: "sensing.raw-samples",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "sensing-series-v1",
    method: "GET",
    route_path: "/api/v1/sensing/series",
    route_group: "sensing.series",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "ao-sense-task-create-v1",
    method: "POST",
    route_path: "/api/v1/sense/task",
    route_group: "ao-sense.task",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "ao-sense-receipt-create-v1",
    method: "POST",
    route_path: "/api/v1/sense/receipt",
    route_group: "ao-sense.receipt",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "ao-sense-tasks-list-v1",
    method: "GET",
    route_path: "/api/v1/sense/tasks",
    route_group: "ao-sense.task",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "ao-sense-receipts-list-v1",
    method: "GET",
    route_path: "/api/v1/sense/receipts",
    route_group: "ao-sense.receipt",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "ao-sense-next-task-v1",
    method: "GET",
    route_path: "/api/v1/sense/next-task",
    route_group: "ao-sense.task",
    path_match: "exact",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "ao-act-actions-group-v1",
    method: "ANY",
    route_path: "/api/v1/actions/*",
    route_group: "ao-act.actions",
    path_match: "group",
    owner: "act-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "approvals-group-v1",
    method: "ANY",
    route_path: "/api/v1/approvals/*",
    route_group: "approvals",
    path_match: "group",
    owner: "approval-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "recommendations-group-v1",
    method: "ANY",
    route_path: "/api/v1/recommendations/*",
    route_group: "recommendations",
    path_match: "group",
    owner: "decision-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "devices-group-v1",
    method: "ANY",
    route_path: "/api/v1/devices/*",
    route_group: "devices",
    path_match: "group",
    owner: "executor-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "alerts-group-v1",
    method: "ANY",
    route_path: "/api/v1/alerts/*",
    route_group: "alerts",
    path_match: "group",
    owner: "operator-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "skills-group-v1",
    method: "ANY",
    route_path: "/api/v1/skills/*",
    route_group: "skills",
    path_match: "group",
    owner: "decision-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "field-programs-group-v1",
    method: "ANY",
    route_path: "/api/v1/field-programs/*",
    route_group: "field-programs",
    path_match: "group",
    owner: "decision-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "admin-internal-group-v1",
    method: "ANY",
    route_path: "/api/admin/*",
    route_group: "admin.internal",
    path_match: "group",
    owner: "admin-service",
    audience: "admin",
    boundary: "internal",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "debug-internal-group-v1",
    method: "ANY",
    route_path: "/api/debug/*",
    route_group: "debug.internal",
    path_match: "group",
    owner: "admin-service",
    audience: "internal",
    boundary: "debug",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "health-system-v1",
    method: "GET",
    route_path: "/api/health",
    route_group: "health",
    path_match: "exact",
    owner: "admin-service",
    audience: "system",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: false,
  },
];
