export type ApiRouteInventoryAudienceV1 = "customer" | "operator" | "admin" | "internal" | "legacy" | "system";
export type ApiRouteInventoryBoundaryV1 = "official" | "compat" | "debug" | "internal";

export type ApiRouteInventoryEntryV1 = {
  id: string;
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE" | "ANY";
  path_prefix: string;
  owner: string;
  audience: ApiRouteInventoryAudienceV1;
  boundary: ApiRouteInventoryBoundaryV1;
  guarded_projection: boolean;
  customer_navigation_allowed: boolean;
  fallback_allowed: boolean;
  write_requires_backend_validation: boolean;
  audit_required: boolean;
};

export const API_ROUTE_INVENTORY: ApiRouteInventoryEntryV1[] = [
  {
    id: "customer-reports-official-v1",
    method: "GET",
    path_prefix: "/api/v1/reports",
    owner: "reporting-service",
    audience: "customer",
    boundary: "official",
    guarded_projection: true,
    customer_navigation_allowed: true,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: true,
  },
  {
    id: "ao-act-actions-v1",
    method: "ANY",
    path_prefix: "/api/v1/actions",
    owner: "act-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "approvals-v1",
    method: "ANY",
    path_prefix: "/api/v1/approvals",
    owner: "approval-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "recommendations-v1",
    method: "ANY",
    path_prefix: "/api/v1/recommendations",
    owner: "decision-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "sensing-fact-envelope-v1",
    method: "ANY",
    path_prefix: "/api/v1/sensing",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "ao-sense-v1",
    method: "ANY",
    path_prefix: "/api/v1/sense",
    owner: "facts-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "devices-v1",
    method: "ANY",
    path_prefix: "/api/v1/devices",
    owner: "executor-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "alerts-v1",
    method: "ANY",
    path_prefix: "/api/v1/alerts",
    owner: "operator-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "skills-v1",
    method: "ANY",
    path_prefix: "/api/v1/skills",
    owner: "decision-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "field-programs-v1",
    method: "ANY",
    path_prefix: "/api/v1/field-programs",
    owner: "decision-service",
    audience: "operator",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "admin-internal-v1",
    method: "ANY",
    path_prefix: "/api/admin",
    owner: "admin-service",
    audience: "admin",
    boundary: "internal",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "debug-internal-v1",
    method: "ANY",
    path_prefix: "/api/debug",
    owner: "admin-service",
    audience: "internal",
    boundary: "debug",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: true,
    audit_required: true,
  },
  {
    id: "health-system-v1",
    method: "GET",
    path_prefix: "/api/health",
    owner: "admin-service",
    audience: "system",
    boundary: "official",
    guarded_projection: false,
    customer_navigation_allowed: false,
    fallback_allowed: false,
    write_requires_backend_validation: false,
    audit_required: false,
  },
];
