import type { FastifyInstance } from "fastify";
import type { Pool } from "pg";
import { enforceRouteRoleAuth } from "../auth/route_role_authz.js";
import { buildGuardedOperationReportV1 } from "../projections/guarded_operation_report_projector_v1.js";
import { projectOperationStateV1, type OperationStateV1 } from "../projections/operation_state_v1.js";
import { customerOperationListTrustFromGuardedReportV1, isCustomerVisibleGuardedOperationReportV1 } from "../projections/report_dashboard_v1.js";
import { filterByCustomerScope, isFieldAllowedByCustomerScope, resolveCustomerScope, type CustomerScopeV1 } from "../services/customer/customer_scope_v1.js";
import { projectReportV1 } from "./reports_v1.js";

type TenantTriple = { tenant_id: string; project_id: string; group_id: string };
type ProjectionSource = "GUARDED_REPORT" | "STATE_FALLBACK_LIMITED";
type DataTrustStatusV1 = "FORMAL" | "LIMITED";
type TrustFields = { projection_source: ProjectionSource; fallback_limited: boolean; customer_visible_eligible: boolean; blocking_reasons: string[]; data_trust_status: DataTrustStatusV1; data_trust_text: string };
type CustomerReportListItem = { report_id?: string | null; report_type: "OVERVIEW" | "FIELD" | "OPERATION" | "EVIDENCE_VALUE"; title: string; subtitle?: string | null; href?: string | null; field_id?: string | null; field_name?: string | null; operation_id?: string | null; operation_title?: string | null; updated_at?: string | null; status_text?: string | null; capability_status?: "AVAILABLE" | "PENDING" | "UNAVAILABLE"; data_trust_status: DataTrustStatusV1; data_trust_text: string };
type CustomerOperationListItem = TrustFields & { operation_id: string; operation_plan_id: string | null; field_id: string | null; field_name: string | null; title: string | null; customer_title: string | null; operation_type: string | null; final_status: string | null; acceptance_status: string | null; evidence_status: string | null; evidence_summary_status: string | null; updated_at: string | null; executed_at: string | null; };
type CustomerFieldListItem = TrustFields & { field_id: string; field_name: string | null; risk_level: "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN"; risk_reasons: string[]; updated_at: string | null; crop_name: string | null; stage_name: string | null; recent_operation_id: string | null; recent_operation_title: string | null; open_alerts_count: number; pending_acceptance_count: number; };
type FieldGeometryStatus = "AVAILABLE" | "MISSING" | "INVALID";
type CustomerFieldGeometryResponse = { field_id: string; geometry_status: FieldGeometryStatus; geometry_format: "GEOJSON"; geometry: Record<string, unknown> | null; area_mu?: number | null; centroid?: { lat: number; lng: number } | null; updated_at: string | null; };

const LIMITED_TRUST_TEXT = "有限记录";
const FORMAL_TRUST_TEXT = "可信价值记录";
const STATE_FALLBACK_TRUST: TrustFields = { projection_source: "STATE_FALLBACK_LIMITED", fallback_limited: true, customer_visible_eligible: false, blocking_reasons: ["state_fallback_limited_not_customer_official"], data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT };

function safeJsonParse(raw: unknown): unknown | null { if (raw == null) return null; if (typeof raw === "string") { try { return JSON.parse(raw); } catch { return null; } } return raw; }
function readCoordinates(node: unknown, out: Array<{ lat: number; lng: number }>): void { if (!Array.isArray(node) || node.length === 0) return; if (node.length >= 2 && typeof node[0] === "number" && typeof node[1] === "number") { const lng = Number(node[0]); const lat = Number(node[1]); if (Number.isFinite(lat) && Number.isFinite(lng)) out.push({ lat, lng }); return; } for (const child of node) readCoordinates(child, out); }
function normalizeGeometry(raw: unknown): Record<string, unknown> | null { if (!raw || typeof raw !== "object") return null; const obj = raw as Record<string, unknown>; if (typeof obj.type !== "string") return null; if (obj.type === "Feature") { const featureGeometry = normalizeGeometry(obj.geometry); if (!featureGeometry) return null; return { type: "Feature", properties: typeof obj.properties === "object" && obj.properties != null ? obj.properties : {}, geometry: featureGeometry }; } if (obj.type === "FeatureCollection") { const features = Array.isArray(obj.features) ? obj.features : []; return { type: "FeatureCollection", features: features.map((x) => normalizeGeometry(x)).filter(Boolean) }; } if (!("coordinates" in obj)) return null; return { type: obj.type, coordinates: obj.coordinates as unknown }; }
function geometryCentroid(geometry: Record<string, unknown> | null): { lat: number; lng: number } | null { if (!geometry) return null; const coords: Array<{ lat: number; lng: number }> = []; const geoType = String(geometry.type ?? "").toUpperCase(); if (geoType === "FEATURE") return geometryCentroid((geometry.geometry as Record<string, unknown>) ?? null); if (geoType === "FEATURECOLLECTION") { for (const feature of (Array.isArray(geometry.features) ? geometry.features : [])) { const c = geometryCentroid(feature as Record<string, unknown>); if (c) coords.push(c); } } else readCoordinates((geometry as any).coordinates, coords); if (!coords.length) return null; const sums = coords.reduce((acc, point) => ({ lat: acc.lat + point.lat, lng: acc.lng + point.lng }), { lat: 0, lng: 0 }); return { lat: Number((sums.lat / coords.length).toFixed(6)), lng: Number((sums.lng / coords.length).toFixed(6)) }; }
function toRiskLevel(value: unknown): "HIGH" | "MEDIUM" | "LOW" | "UNKNOWN" { const v = String(value ?? "").trim().toUpperCase(); if (v === "HIGH" || v === "MEDIUM" || v === "LOW") return v; return "UNKNOWN"; }
function toIsoFromMs(ms: unknown): string | null { const n = Number(ms ?? 0); return Number.isFinite(n) && n > 0 ? new Date(n).toISOString() : null; }
function operationIdOf(state: any): string { return String(state.operation_id ?? state.operation_plan_id ?? "").trim(); }
function stateUpdatedAt(state: any): string | null { const updatedTs = Number(state.updated_at ?? 0); const timelineTs = Math.max(...(Array.isArray(state.timeline) ? state.timeline : []).map((item: any) => Number(item.ts ?? 0)).filter((n: number) => Number.isFinite(n) && n > 0), 0); return toIsoFromMs(updatedTs || timelineTs); }
function limitedFinalStatusFromState(): string { return "LIMITED_STATE"; }
function limitedAcceptanceStatusFromState(): string { return "NEEDS_REVIEW"; }
function limitedEvidenceStatusFromState(): string { return "LIMITED_STATE"; }
function formalPendingAcceptanceFromState(): number { return 0; }
function limitedSubtitle(text: string): string { return `${text}；当前数据可信级别为有限记录，不代表正式经营结论`; }
function textOrNull(value: unknown): string | null { const text = String(value ?? "").trim(); return text || null; }
function guardedTrustFields(report: any): TrustFields { const trust = customerOperationListTrustFromGuardedReportV1(report); return trust.projection_source === "GUARDED_REPORT" && trust.customer_visible_eligible === true && isCustomerVisibleGuardedOperationReportV1(report) ? { projection_source: "GUARDED_REPORT", fallback_limited: false, customer_visible_eligible: true, blocking_reasons: [], data_trust_status: "FORMAL", data_trust_text: FORMAL_TRUST_TEXT } : STATE_FALLBACK_TRUST; }
function operationTypeFromReportOrState(report: any, state: any): string | null { return textOrNull(report?.operation_type ?? report?.operation_plan?.operation_type ?? report?.operation_plan?.action_type ?? state?.action_type); }
function operationTitleFromReportOrState(report: any, state: any): string | null { return textOrNull(report?.customer_title ?? report?.operation_title) ?? (operationTypeFromReportOrState(report, state) ? `${operationTypeFromReportOrState(report, state)}作业` : null); }
function customerOperationFromStateFallback(state: any, fieldNameById: Map<string, string | null>): CustomerOperationListItem | null { const operationId = operationIdOf(state); if (!operationId) return null; const fieldId = String(state.field_id ?? "").trim() || null; const operationType = String(state.action_type ?? "").trim() || null; const executedTs = Number(state.execution_finished_at ?? state.execution_started_at ?? 0); return { ...STATE_FALLBACK_TRUST, operation_id: operationId, operation_plan_id: String(state.operation_plan_id ?? "").trim() || null, field_id: fieldId, field_name: fieldId ? (fieldNameById.get(fieldId) ?? null) : null, title: operationType ? `${operationType}作业` : null, customer_title: operationType ? `${operationType}作业` : null, operation_type: operationType, final_status: limitedFinalStatusFromState(), acceptance_status: limitedAcceptanceStatusFromState(), evidence_status: limitedEvidenceStatusFromState(), evidence_summary_status: limitedEvidenceStatusFromState(), updated_at: stateUpdatedAt(state), executed_at: toIsoFromMs(executedTs) }; }
function customerOperationFromGuardedReport(report: any, state: any, fieldNameById: Map<string, string | null>): CustomerOperationListItem | null { const trust = guardedTrustFields(report); if (trust.projection_source !== "GUARDED_REPORT") return null; const identifiers = report?.identifiers ?? {}; const operationId = textOrNull(identifiers.operation_id ?? identifiers.operation_plan_id ?? state?.operation_id ?? state?.operation_plan_id); if (!operationId) return null; const fieldId = textOrNull(identifiers.field_id ?? state?.field_id); const operationType = operationTypeFromReportOrState(report, state); const title = operationTitleFromReportOrState(report, state); const evidenceStatus = textOrNull(report?.evidence?.evidence_status ?? report?.formal_scenario?.evidence_status); return { ...trust, operation_id: operationId, operation_plan_id: textOrNull(identifiers.operation_plan_id ?? state?.operation_plan_id), field_id: fieldId, field_name: fieldId ? (fieldNameById.get(fieldId) ?? null) : null, title, customer_title: title, operation_type: operationType, final_status: textOrNull(report?.execution?.final_status), acceptance_status: textOrNull(report?.acceptance?.status), evidence_status: evidenceStatus, evidence_summary_status: textOrNull(report?.evidence_pack_summary?.status ?? evidenceStatus), updated_at: textOrNull(report?.generated_at) ?? stateUpdatedAt(state), executed_at: textOrNull(report?.execution?.execution_finished_at ?? report?.execution?.execution_started_at ?? report?.receipt?.submitted_at) }; }
async function buildGuardedCustomerOperationItem(params: { pool: Pool; tenant: TenantTriple; state: OperationStateV1; fieldNameById: Map<string, string | null> }): Promise<CustomerOperationListItem | null> { try { const report = await projectReportV1({ pool: params.pool, tenant: params.tenant, operationState: params.state }); const guarded = await buildGuardedOperationReportV1({ pool: params.pool, report }); return customerOperationFromGuardedReport(guarded, params.state, params.fieldNameById) ?? customerOperationFromStateFallback(params.state, params.fieldNameById); } catch { return customerOperationFromStateFallback(params.state, params.fieldNameById); } }

async function queryFieldRows(pool: Pool, tenant: TenantTriple, scope: CustomerScopeV1): Promise<Array<{ field_id: string; name: string | null; area_ha: number | null }>> { if (scope.scope_mode === "DENIED") return []; const params: any[] = [tenant.tenant_id]; const fieldSql = scope.can_preview_all_fields ? "" : " AND field_id = ANY($2::text[])"; if (!scope.can_preview_all_fields) params.push(scope.allowed_field_ids); const q = await pool.query(`SELECT field_id, name, area_ha FROM field_index_v1 WHERE tenant_id = $1${fieldSql} ORDER BY field_id ASC`, params).catch(() => ({ rows: [] as any[] })); return (q.rows ?? []).map((row: any) => ({ field_id: String(row.field_id ?? "").trim(), name: String(row.name ?? "").trim() || null, area_ha: Number.isFinite(Number(row.area_ha)) ? Number(row.area_ha) : null })).filter((row) => row.field_id); }
async function queryFieldNameMap(pool: Pool, tenant: TenantTriple, fieldIds: string[]): Promise<Map<string, string | null>> { if (fieldIds.length === 0) return new Map(); const q = await pool.query(`SELECT field_id, name FROM field_index_v1 WHERE tenant_id = $1 AND field_id = ANY($2::text[])`, [tenant.tenant_id, fieldIds]).catch(() => ({ rows: [] as any[] })); const map = new Map<string, string | null>(); for (const row of q.rows ?? []) { const fieldId = String((row as any).field_id ?? "").trim(); if (fieldId) map.set(fieldId, String((row as any).name ?? "").trim() || null); } return map; }
async function queryOpenAlertCountByField(pool: Pool, tenant: TenantTriple, fieldIds: string[]): Promise<Map<string, number>> { if (fieldIds.length === 0) return new Map(); const q = await pool.query(`SELECT field_id, SUM(cnt)::bigint AS count FROM (SELECT e.object_id AS field_id, COUNT(*)::bigint AS cnt FROM alert_event_index_v1 e WHERE e.tenant_id = $1 AND e.status IN ('OPEN','ACKED') AND e.object_type = 'FIELD' AND e.object_id = ANY($2::text[]) GROUP BY e.object_id UNION ALL SELECT b.field_id AS field_id, COUNT(*)::bigint AS cnt FROM alert_event_index_v1 e JOIN device_binding_index_v1 b ON b.tenant_id = e.tenant_id AND b.device_id = e.object_id WHERE e.tenant_id = $1 AND e.status IN ('OPEN','ACKED') AND e.object_type = 'DEVICE' AND b.field_id = ANY($2::text[]) GROUP BY b.field_id) t GROUP BY field_id`, [tenant.tenant_id, fieldIds]).catch(() => ({ rows: [] as any[] })); const map = new Map<string, number>(); for (const row of q.rows ?? []) { const fieldId = String((row as any).field_id ?? "").trim(); if (fieldId) map.set(fieldId, Number((row as any).count ?? 0)); } return map; }
function scopeFromRequest(req: any, reply: any): { auth: any; tenant: TenantTriple; scope: CustomerScopeV1 } | null { const auth = enforceRouteRoleAuth(req, reply, "summary"); if (!auth) return null; return { auth, tenant: { tenant_id: String(auth.tenant_id), project_id: String(auth.project_id), group_id: String(auth.group_id) }, scope: resolveCustomerScope(auth) }; }

export function registerCustomerV1Routes(app: FastifyInstance, pool: Pool): void {
  app.get("/api/v1/customer/reports", async (req, reply) => {
    const ctx = scopeFromRequest(req, reply); if (!ctx) return;
    const generatedAt = new Date().toISOString();
    const states = filterByCustomerScope(await projectOperationStateV1(pool, ctx.tenant), ctx.scope, (state) => (state as any).field_id);
    const fieldRows = await queryFieldRows(pool, ctx.tenant, ctx.scope);
    const fieldIds = fieldRows.length ? fieldRows.map((x) => x.field_id) : Array.from(new Set(states.map((state: any) => String(state.field_id ?? "").trim()).filter(Boolean)));
    const fieldNameById = new Map(fieldRows.map((row) => [row.field_id, row.name] as const));
    for (const [fieldId, name] of await queryFieldNameMap(pool, ctx.tenant, fieldIds)) if (!fieldNameById.has(fieldId)) fieldNameById.set(fieldId, name);
    const reports: CustomerReportListItem[] = [{ report_type: "OVERVIEW", title: "经营总览报告", subtitle: limitedSubtitle("基于当前客户驾驶舱可见数据生成"), href: "/customer/export", updated_at: generatedAt, status_text: "可导出", capability_status: "AVAILABLE", data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT }];
    for (const fieldId of fieldIds.slice(0, 20)) reports.push({ report_type: "FIELD", title: `${fieldNameById.get(fieldId) ?? "地块"} · 地块报告`, subtitle: limitedSubtitle("基于当前可见地块数据生成"), href: `/customer/fields/${encodeURIComponent(fieldId)}`, field_id: fieldId, field_name: fieldNameById.get(fieldId) ?? null, updated_at: generatedAt, status_text: "可查看", capability_status: "AVAILABLE", data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT });
    const operationSeen = new Set<string>();
    for (const state of states) { const operationId = operationIdOf(state); if (!operationId || operationSeen.has(operationId)) continue; operationSeen.add(operationId); const fieldId = String((state as any).field_id ?? "").trim() || null; const operationTitle = String((state as any).action_type ?? "").trim() || "作业"; reports.push({ report_type: "OPERATION", title: `${operationTitle} · 作业报告`, subtitle: limitedSubtitle("基于当前近期作业生成，状态需以受保护作业报告为准"), href: `/customer/operations/${encodeURIComponent(operationId)}`, operation_id: operationId, operation_title: operationTitle, field_id: fieldId, field_name: fieldId ? (fieldNameById.get(fieldId) ?? null) : null, updated_at: stateUpdatedAt(state) ?? generatedAt, status_text: "需复核", capability_status: "PENDING", data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT }); if (operationSeen.size >= 30) break; }
    reports.push({ report_type: "EVIDENCE_VALUE", title: "证据与价值报告", subtitle: "证据包生成能力待接入；当前数据可信级别为有限记录，不代表正式经营结论", href: null, updated_at: generatedAt, status_text: "数据不足", capability_status: "PENDING", data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT });
    return reply.send({ ok: true, source: "customer_reports_api", dataScope: "customer_report_center_v1", projection_source: "STATE_FALLBACK_LIMITED", fallback_limited: true, customer_visible_eligible: false, data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT, blocking_reasons: STATE_FALLBACK_TRUST.blocking_reasons, generated_at: generatedAt, scope: ctx.scope, report_count: reports.length, reports });
  });

  app.get("/api/v1/customer/operations", async (req, reply) => {
    const ctx = scopeFromRequest(req, reply); if (!ctx) return;
    const states = filterByCustomerScope(await projectOperationStateV1(pool, ctx.tenant), ctx.scope, (state) => (state as any).field_id);
    const fieldIds = Array.from(new Set(states.map((state: any) => String(state.field_id ?? "").trim()).filter(Boolean)));
    const fieldNameById = await queryFieldNameMap(pool, ctx.tenant, fieldIds);
    const operations = (await Promise.all(states.map((state: OperationStateV1) => buildGuardedCustomerOperationItem({ pool, tenant: ctx.tenant, state, fieldNameById })))).filter((item): item is CustomerOperationListItem => item != null).sort((a, b) => Date.parse(b.updated_at ?? "") - Date.parse(a.updated_at ?? ""));
    const hasFormalOperation = operations.some((item) => item.projection_source === "GUARDED_REPORT" && item.customer_visible_eligible === true);
    return reply.send({ ok: true, source: "customer_operations_api", dataScope: "customer_operations_v1", projection_source: hasFormalOperation ? "GUARDED_REPORT" : "STATE_FALLBACK_LIMITED", fallback_limited: !hasFormalOperation, customer_visible_eligible: hasFormalOperation, data_trust_status: hasFormalOperation ? "FORMAL" : "LIMITED", data_trust_text: hasFormalOperation ? FORMAL_TRUST_TEXT : LIMITED_TRUST_TEXT, blocking_reasons: hasFormalOperation ? [] : STATE_FALLBACK_TRUST.blocking_reasons, generated_at: new Date().toISOString(), scope: ctx.scope, operation_count: operations.length, operations });
  });

  app.get("/api/v1/customer/fields/:fieldId/geometry", async (req, reply) => {
    const ctx = scopeFromRequest(req, reply); if (!ctx) return;
    const fieldId = String((req.params as any)?.fieldId ?? "").trim();
    if (!fieldId) return reply.code(404).send({ ok: false, error: "NOT_FOUND" });
    if (!isFieldAllowedByCustomerScope(ctx.scope, fieldId)) return reply.code(404).send({ ok: false, error: "NOT_FOUND" });
    const fieldQ = await pool.query(`SELECT field_id, area_ha FROM field_index_v1 WHERE tenant_id = $1 AND field_id = $2 LIMIT 1`, [ctx.tenant.tenant_id, fieldId]);
    if (fieldQ.rowCount === 0) return reply.code(404).send({ ok: false, error: "NOT_FOUND" });
    const geoQ = await pool.query(`SELECT polygon_geojson_json AS geojson, updated_ts_ms FROM field_polygon_v1 WHERE tenant_id = $1 AND field_id = $2 LIMIT 1`, [ctx.tenant.tenant_id, fieldId]);
    const raw = safeJsonParse(geoQ.rows?.[0]?.geojson ?? null); const geometry = normalizeGeometry(raw); const areaHa = Number(fieldQ.rows?.[0]?.area_ha ?? NaN);
    const payload: CustomerFieldGeometryResponse = { field_id: fieldId, geometry_status: geometry ? "AVAILABLE" : (raw == null ? "MISSING" : "INVALID"), geometry_format: "GEOJSON", geometry, area_mu: Number.isFinite(areaHa) ? Number((areaHa * 15).toFixed(4)) : null, centroid: geometryCentroid(geometry), updated_at: toIsoFromMs(geoQ.rows?.[0]?.updated_ts_ms ?? 0) };
    return reply.send({ ok: true, source: "customer_fields_geometry_api", dataScope: "customer_fields_geometry_v1", scope: ctx.scope, ...payload });
  });

  app.get("/api/v1/customer/fields", async (req, reply) => {
    const ctx = scopeFromRequest(req, reply); if (!ctx) return;
    const states = filterByCustomerScope(await projectOperationStateV1(pool, ctx.tenant), ctx.scope, (state) => (state as any).field_id);
    const fieldRows = await queryFieldRows(pool, ctx.tenant, ctx.scope);
    const stateFieldIds = Array.from(new Set(states.map((state: any) => String(state.field_id ?? "").trim()).filter(Boolean)));
    const fieldIds = fieldRows.length ? fieldRows.map((row) => row.field_id) : stateFieldIds;
    const fieldNameById = new Map(fieldRows.map((row) => [row.field_id, row.name] as const));
    for (const [fieldId, name] of await queryFieldNameMap(pool, ctx.tenant, fieldIds)) if (!fieldNameById.has(fieldId)) fieldNameById.set(fieldId, name);
    const openAlertsByField = await queryOpenAlertCountByField(pool, ctx.tenant, fieldIds);
    const byField = new Map<string, { latestTs: number; latestOperationId: string | null; pendingAcceptanceCount: number; riskLevel: string; riskReasons: string[] }>();
    for (const state of states) {
      const fieldId = String((state as any).field_id ?? "").trim(); if (!fieldId) continue;
      const latestTs = Math.max(Number((state as any).updated_at ?? 0), Number((state as any).last_event_ts ?? 0), ...(Array.isArray((state as any).timeline) ? (state as any).timeline.map((item: any) => Number(item.ts ?? 0)) : []));
      const existing = byField.get(fieldId);
      const pending = formalPendingAcceptanceFromState();
      const riskLevel = String((state as any).risk?.level ?? (state as any).risk_level ?? "UNKNOWN");
      const riskReasons = Array.isArray((state as any).risk?.reasons) ? (state as any).risk.reasons.map((x: unknown) => String(x ?? "").trim()).filter(Boolean) : [];
      if (!existing) byField.set(fieldId, { latestTs, latestOperationId: operationIdOf(state) || null, pendingAcceptanceCount: pending, riskLevel, riskReasons });
      else { existing.pendingAcceptanceCount += pending; if (latestTs > existing.latestTs) { existing.latestTs = latestTs; existing.latestOperationId = operationIdOf(state) || null; existing.riskLevel = riskLevel; existing.riskReasons = riskReasons; } }
    }
    const fields: CustomerFieldListItem[] = fieldIds.map((fieldId) => { const agg = byField.get(fieldId); return { ...STATE_FALLBACK_TRUST, field_id: fieldId, field_name: fieldNameById.get(fieldId) ?? null, risk_level: toRiskLevel(agg?.riskLevel), risk_reasons: agg?.riskReasons ?? [], updated_at: toIsoFromMs(agg?.latestTs ?? 0), crop_name: null, stage_name: null, recent_operation_id: agg?.latestOperationId ?? null, recent_operation_title: null, open_alerts_count: Number(openAlertsByField.get(fieldId) ?? 0), pending_acceptance_count: Number(agg?.pendingAcceptanceCount ?? 0) }; });
    return reply.send({ ok: true, source: "customer_fields_api", dataScope: "customer_fields_v1", projection_source: "STATE_FALLBACK_LIMITED", fallback_limited: true, customer_visible_eligible: false, data_trust_status: "LIMITED", data_trust_text: LIMITED_TRUST_TEXT, blocking_reasons: STATE_FALLBACK_TRUST.blocking_reasons, generated_at: new Date().toISOString(), scope: ctx.scope, field_count: fields.length, fields });
  });
}
