const fs = require('node:fs');
const assert = require('node:assert/strict');
const json = (p) => JSON.parse(fs.readFileSync(p,'utf8'));
const q = json('docs/frontend-productization/PFE-14-EVIDENCE-HEALTH-PRODUCTIZATION-QUALIFICATION-V1.json');
const candidate = json('docs/frontend-productization/PFE-14-EVIDENCE-HEALTH-PRODUCTIZATION-CANDIDATE-V1.json');
const authority = json('docs/frontend-productization/PFE-14-CURRENT-AUTHORITY.json');
const classBQualification = fs.existsSync('docs/frontend-productization/PFE-14-CLASS-B-OPERATIONAL-PROJECTION-QUALIFICATION-V1.json') ? json('docs/frontend-productization/PFE-14-CLASS-B-OPERATIONAL-PROJECTION-QUALIFICATION-V1.json') : null;
assert.equal(q.record_status,'EVIDENCE_HEALTH_PRODUCTIZATION_QUALIFIED_CLASS_B_ADJUDICATION_AUTHORIZED_S4_NOT_EFFECTIVE');
assert.equal(q.qualified_subject_sha,'9e6a60db8885d1d9e4ce73cb9b2cfe84b4970e5e');
assert.equal(q.focused_run_id,31602800157);
assert.equal(q.cap07_lifecycle_run_id,31602800202);
assert.equal(q.standard_ci_run_id,31602800138);
assert.equal(q.frontend_runtime_page_audit_pass,true);
assert.equal(q.full_acceptance_pass,true);
assert.equal(q.commercial_mvp0_release_gate_pass,true);
assert.equal(q.protected_main_merge_claimed,false);
assert.equal(q.evidence_health_productization_qualified,true);
assert.equal(candidate.record_status,'IMPLEMENTED_CANDIDATE_NOT_EFFECTIVE');
assert.equal(candidate.pfe14_s4_effective,false);
assert.equal(q.class_b_projection_adjudication.authorized_next_candidate,true);
assert.equal(q.class_b_projection_adjudication.implementation_authorized,false);
assert.equal(q.class_b_field_implementation_authorized,false);
assert.equal(q.class_c_field_implementation_authorized,false);
assert.equal(q.pfe14_s4_effective,false);
const classBAction='PFE_14_ADJUDICATE_CLASS_B_OPERATIONAL_PRODUCT_PROJECTION';
const providerAction='PFE_14_IMPLEMENT_NARROW_CLASS_B_DEGRADATION_FORECAST_SLOT_PROVIDER';
assert.ok([classBAction,providerAction].includes(authority.first_legal_next_action),'UNRECOGNIZED_EVIDENCE_HEALTH_QUALIFICATION_SUCCESSOR');
assert.equal(authority.evidence_health_productization_qualified,true);
assert.equal(authority.evidence_health_productization_proof.subject_sha,q.qualified_subject_sha);
assert.equal(authority.evidence_health_productization_proof.all_pass,true);
assert.equal(authority.evidence_health_productization_proof.merged_to_protected_main,false);
if (authority.first_legal_next_action===providerAction) {
  assert(classBQualification,'CLASS_B_QUALIFICATION_REQUIRED');
  assert.equal(classBQualification.qualified_subject_sha,'d3bb7a4ff8509899981b41efe724a2c6b74540f5');
  assert.equal(classBQualification.focused_run_id,31607280419);
  assert.equal(classBQualification.standard_ci_run_id,31607280420);
  assert.equal(authority.class_b_operational_projection_adjudication_proof.all_pass,true);
  assert.equal(authority.class_b_operational_projection_adjudication_proof.merged_to_protected_main,false);
}
assert.equal(authority.class_b_operational_extension_implementation_authorized,false);
assert.equal(authority.class_c_field_implementation_authorized,false);
assert.equal(authority.shadow_online_label_authorized,false);
assert.equal(authority.authoritative_runtime_context_authorized,false);
assert.equal(authority.s4_effective,false);
console.log(JSON.stringify({status:'PASS',qualification:'PFE-14-EVIDENCE-HEALTH-PRODUCTIZATION-QUALIFICATION-V1',qualified_subject_sha:q.qualified_subject_sha,evidence_health_productization_qualified:true,historical_qualification_proof_bound:true,pfe14_s4_effective:false,next_action:authority.first_legal_next_action},null,2));