const fs=require('node:fs'); const assert=require('node:assert/strict'); const read=(p)=>fs.readFileSync(p,'utf8'); const json=(p)=>JSON.parse(read(p));
const authority=json('docs/frontend-productization/PFE-14-CURRENT-AUTHORITY.json');
const adjudication=json('docs/frontend-productization/PFE-14-S4-PRODUCT-COMPLETENESS-ADJUDICATION-V1.json');
const candidate=json('docs/frontend-productization/PFE-14-STATE-FORECAST-PRODUCTIZATION-CANDIDATE-V1.json');
const qualification=json('docs/frontend-productization/PFE-14-STATE-FORECAST-PRODUCTIZATION-QUALIFICATION-V1.json');
const page=read('apps/web/src/features/operator/fieldRuntime/McftCanonicalFieldRuntimeRoutePage.tsx'); const panels=read('apps/web/src/features/operator/fieldRuntime/Pfe14StateForecastProductPanels.tsx');
const candidateAction='PFE_14_PRODUCTIZE_CURRENT_CANONICAL_STATE_AND_FORECAST_WITHOUT_NEW_DATA_FIELDS';
const evidenceAction='PFE_14_PRODUCTIZE_CURRENT_EVIDENCE_AND_RUNTIME_HEALTH_WITHOUT_NEW_DATA_FIELDS';
const classBAction='PFE_14_ADJUDICATE_CLASS_B_OPERATIONAL_PRODUCT_PROJECTION';
const providerAction='PFE_14_IMPLEMENT_NARROW_CLASS_B_DEGRADATION_FORECAST_SLOT_PROVIDER';
assert.ok([candidateAction,evidenceAction,classBAction,providerAction].includes(authority.first_legal_next_action),'UNRECOGNIZED_STATE_FORECAST_STAGE');
assert.equal(authority.state_forecast_current_canonical_productization_authorized,true); assert.equal(authority.state_forecast_new_backend_fields_authorized,false); assert.equal(authority.state_forecast_payload_inference_authorized,false); assert.equal(authority.shadow_online_label_authorized,false); assert.equal(authority.authoritative_runtime_context_authorized,false); assert.equal(authority.s4_effective,false);
if (authority.first_legal_next_action!==candidateAction) { assert.equal(qualification.qualified_subject_sha,'dfa68752d41bfcd6be9d5da763370dc78d9f4f38'); assert.equal(qualification.focused_run_id,31600089263); assert.equal(qualification.cap07_lifecycle_run_id,31600089325); assert.equal(qualification.standard_ci_run_id,31600089223); assert.equal(qualification.protected_main_merge_claimed,false); assert.equal(authority.state_forecast_productization_proof.subject_sha,qualification.qualified_subject_sha); assert.equal(authority.state_forecast_productization_proof.all_pass,true); assert.equal(authority.state_forecast_productization_proof.merged_to_protected_main,false); }
if (authority.first_legal_next_action===providerAction) { assert.equal(authority.class_b_operational_projection_adjudication_proof.subject_sha,'d3bb7a4ff8509899981b41efe724a2c6b74540f5'); assert.equal(authority.class_b_operational_projection_adjudication_proof.all_pass,true); assert.equal(authority.class_b_operational_projection_adjudication_proof.merged_to_protected_main,false); }
assert.equal(adjudication.state_forecast_productization.authorized_next_candidate,true); assert.equal(candidate.record_status,'IMPLEMENTED_CANDIDATE_NOT_EFFECTIVE'); assert.equal(candidate.route_delta,0); assert.equal(candidate.api_client_delta,0); assert.equal(candidate.backend_delta,0); assert.equal(candidate.database_delta,0); assert.equal(candidate.payload_parsing_added,false); assert.equal(candidate.payload_inference_added,false); assert.equal(candidate.synthetic_values_added,false); assert.equal(candidate.scenario_eligibility_inferred_from_attachment,false); assert.equal(candidate.pfe14_s4_effective,false);
assert(page.includes('Pfe14StateProductPanel')); assert(page.includes('Pfe14ForecastProductPanel')); assert(page.includes('<dd>READ_ONLY_DETERMINISTIC_REPLAY</dd>')); for (const x of ['page.items','item.logical_time','item.attachment_status','runtime.current_tick_forecast_result','runtime.latest_successful_forecast','runtime.scenario_source_forecast','State ≠ Sensor Reading','Forecast is not Fact.','Forecast is not Recommendation.','Forecast is not Action.','<details']) assert(panels.includes(x),`PFE14_STATE_FORECAST_REQUIRED:${x}`); for (const x of ['fetch(','readMcft','Date.now(','Date.parse(','new Date(','SHADOW_ONLINE','runtime_mode','tenant_sample','field_sample','season_sample','zone_sample']) assert(!panels.includes(x),`PFE14_STATE_FORECAST_FORBIDDEN:${x}`);
console.log(JSON.stringify({status:'PASS',candidate:'PFE-14-STATE-FORECAST-PRODUCTIZATION-CANDIDATE-V1',historical_candidate_proof_bound:authority.first_legal_next_action!==candidateAction,pfe14_s4_effective:false,next_action:authority.first_legal_next_action},null,2));