'use strict';

// scripts/h53/DERIVE_H53_3_FORECAST_SCENARIO_V1.cjs
// Purpose: derive H53.3 forecast and scenario from H53.2 WaterStressState.
// Boundary: writes forecast/scenario only; no recommendation or control-chain records.

const crypto = require('node:crypto');
const { Client } = require('pg');

const DB = process.env.DATABASE_URL || 'postgres://landos:landos_pwd@127.0.0.1:5433/landos';
const SRC = 'H53_3_FORECAST_SCENARIO_DERIVATION_V1';
const VER = 'h53.3.v1';
const S2 = 'H53_2_WATER_STRESS_STATE_DERIVATION_V1';
const V2 = 'h53.2.v1';
const AT = '2026-06-26T00:00:00.000Z';
const S = { tenant_id:'tenantA', project_id:'projectA', group_id:'groupA', field_id:'field_c8_demo' };

function a(x){return process.argv.includes(x)}
function num(x){const n=Number(x);return Number.isFinite(n)?n:null}
function clamp(x,l,h){return Math.max(l,Math.min(h,x))}
function h(x){return crypto.createHash('sha256').update(JSON.stringify(x)).digest('hex')}
function fail(error,details={}){console.error(JSON.stringify({ok:false,derivation:'DERIVE_H53_3_FORECAST_SCENARIO_V1',error,details},null,2));process.exit(1)}
function val(x){return typeof x==='object'&&x!==null?JSON.stringify(x):x}
async function cols(c,t){const r=await c.query("select column_name from information_schema.columns where table_schema='public' and table_name=$1",[t]);return new Set(r.rows.map(row=>row.column_name))}
async function state(c){const r=await c.query(`select fact_id,record_json::jsonb as record_json,record_json::jsonb->'payload' as payload_json from facts where source=$1 and record_json::jsonb->>'type'='water_state_estimate_v1' and record_json::jsonb#>>'{payload,derivation_version}'=$2 and record_json::jsonb#>>'{payload,tenant_id}'=$3 and record_json::jsonb#>>'{payload,project_id}'=$4 and record_json::jsonb#>>'{payload,group_id}'=$5 and record_json::jsonb#>>'{payload,field_id}'=$6 and record_json::jsonb#>>'{payload,source_input_role}'='CURRENT_STATE_INPUT' order by occurred_at desc,fact_id desc limit 1`,[S2,V2,S.tenant_id,S.project_id,S.group_id,S.field_id]);if(!r.rows.length)fail('H53_2_CURRENT_STATE_MISSING');return r.rows[0]}
function st(f){return f<0.35?'STRESS':f<0.55?'LIMITED_AVAILABLE':f<0.85?'ADEQUATE':'WET'}
function base(p){const sm=num(p.latest_soil_moisture_percent);if(sm===null)fail('SOIL_MOISTURE_MISSING');const r=num(p.rainfall_forecast_mm_72h)||0,e=num(p.et0_mm_72h)||0;let f=clamp(sm/30,0.05,0.98);return Array.from({length:7},(_,d)=>{const rain=d<3?r/3:0,et=d<3?e/3:e/3,net=rain-et,mm=clamp(f*100+net,0,100);f=mm/100;return{day_index:d,precipitation_mm:+rain.toFixed(2),et0_mm:+et.toFixed(2),net_water_change_mm:+net.toFixed(2),projected_available_water_mm:+mm.toFixed(2),projected_available_water_fraction:+f.toFixed(4),forecast_water_status:st(f)}})}
function opt(id,label,b,mm,day){let carry=0;const proj=b.map(row=>{const add=row.day_index===day?mm*0.8:0,raw=row.projected_available_water_mm+carry+add,m=clamp(raw,0,100),delta=m-row.projected_available_water_mm;carry=Math.max(0,delta);return{...row,water_add_mm:row.day_index===day?mm:0,baseline_available_water_mm:row.projected_available_water_mm,projected_available_water_mm:+m.toFixed(2),projected_available_water_fraction:+(m/100).toFixed(4),delta_vs_baseline_mm:+delta.toFixed(2),delta_vs_baseline_fraction:+(delta/100).toFixed(4),forecast_water_status:st(m/100),bound_applied:raw>100?'UPPER_BOUND':'NONE'}});const bs=b.filter(x=>x.forecast_water_status==='STRESS').length,ss=proj.filter(x=>x.forecast_water_status==='STRESS').length;return{option_id:id,label,amount_mm:mm,scheduled_day:day,water_events:mm>0?[{day_index:day,amount_mm:mm}]:[],daily_projection:proj,min_available_water_fraction:Math.min(...proj.map(x=>x.projected_available_water_fraction)),stress_day_count:ss,risk_delta:ss-bs,confidence:{level:'MEDIUM',score:0.72},recommendation_selected:false,approval_created:false,operation_plan_created:false,task_created:false}}
function rec(row){const p=row.payload_json||row.record_json.payload||{},b=base(p),fh=h({VER,S,state:row.fact_id,b}),fid=`rzf_h53_3_${fh.slice(0,16)}`;const forecast={type:'root_zone_soil_water_forecast_v1',payload:{...S,forecast_id:fid,zone_id:'zone_c8_demo_root_zone',source_state_id:p.estimate_id,source_state_ref:row.fact_id,weather_forecast_ref:p.source_weather_forecast_id,baseline_mode:'NO_NEW_ACTION',horizon_days:7,root_zone_depth_cm:60,root_zone_available_water_capacity_mm:100,initial_available_water_fraction:clamp((num(p.latest_soil_moisture_percent)||0)/30,0.05,0.98),daily_forecast:b,min_available_water_fraction:Math.min(...b.map(x=>x.projected_available_water_fraction)),max_available_water_fraction:Math.max(...b.map(x=>x.projected_available_water_fraction)),first_stress_date:b.find(x=>x.forecast_water_status==='STRESS')?.day_index??null,stress_day_count:b.filter(x=>x.forecast_water_status==='STRESS').length,limited_day_count:b.filter(x=>x.forecast_water_status==='LIMITED_AVAILABLE').length,forecast_status:'ESTIMATED',blocking_reasons:[],calculation_inputs:{source_state_fact_id:row.fact_id,water_balance_72h_mm:p.water_balance_72h_mm},derivation:{derivation_version:VER,source:SRC,no_recommendation_created:true},confidence:{level:'MEDIUM',score:0.72},computed_at:AT,derivation_version:VER,determinism_hash:fh,evidence_refs:[{kind:'state_estimate',ref_id:row.fact_id,schema_ref:'water_state_estimate_v1'}]}};const options=[opt('NO_ACTION','No new water action',b,0,null),opt('ADD_10MM_DAY0','Add 10 mm on day 0',b,10,0),opt('ADD_20MM_DAY0','Add 20 mm on day 0',b,20,0),opt('DELAY_3_DAYS_THEN_ADD_20MM','Delay 3 days, then add 20 mm',b,20,3)];const sh=h({VER,fid,options}),sid=`scn_h53_3_${sh.slice(0,16)}`;const scenario={type:'irrigation_scenario_set_v1',payload:{...S,scenario_set_id:sid,source_forecast_id:fid,input_status:'COMPARABLE',no_action_baseline_present:true,options,selected_option_id:null,recommendation_created:false,approval_created:false,operation_plan_created:false,task_created:false,derivation_version:VER,derivation_source:SRC,computed_at:AT,determinism_hash:sh,evidence_refs:[{kind:'forecast',ref_id:fid,schema_ref:'root_zone_soil_water_forecast_v1'}]}};return{forecast,scenario}}
async function fact(c,id,r){await c.query('insert into facts (fact_id,occurred_at,source,record_json) values ($1,$2,$3,$4::jsonb) on conflict do nothing',[id,AT,SRC,JSON.stringify(r)])}
async function idx(c,t,row){const cs=await cols(c,t);if(!cs.size)return{skipped:true};const ks=Object.keys(row).filter(k=>cs.has(k));await c.query(`insert into ${t} (${ks.join(',')}) values (${ks.map((_,i)=>`$${i+1}`).join(',')}) on conflict do nothing`,ks.map(k=>val(row[k])));return{skipped:false,columns:ks}}
async function apply(r){const c=new Client({connectionString:DB});await c.connect();try{await c.query('BEGIN');const f=r.forecast.payload.forecast_id,s=r.scenario.payload.scenario_set_id;await fact(c,f,r.forecast);const fi=await idx(c,'root_zone_soil_water_forecast_index_v1',{...r.forecast.payload,daily_forecast_json:r.forecast.payload.daily_forecast,blocking_reasons_json:r.forecast.payload.blocking_reasons,calculation_inputs_json:r.forecast.payload.calculation_inputs,derivation_json:r.forecast.payload.derivation,confidence_json:r.forecast.payload.confidence,source_fact_id:f,updated_at:AT});await fact(c,s,r.scenario);const si=await idx(c,'irrigation_scenario_set_index_v1',{...r.scenario.payload,options_json:r.scenario.payload.options,source_fact_id:s,generated_at:AT});await c.query('COMMIT');return{forecast_fact_id:f,scenario_fact_id:s,forecast_index:fi,scenario_index:si}}catch(e){await c.query('ROLLBACK');throw e}finally{await c.end()}}
(async()=>{const dry=a('--dry-run')||!a('--apply'),c=new Client({connectionString:DB});await c.connect();let sr;try{sr=await state(c)}finally{await c.end()}const r=rec(sr),res=dry?null:await apply(r);console.log(JSON.stringify({ok:true,derivation:'DERIVE_H53_3_FORECAST_SCENARIO_V1',dry_run:dry,source:SRC,forecast:r.forecast.payload,scenario:r.scenario.payload,write_result:res},null,2))})().catch(e=>fail(e.message));
