import type { FastifyInstance } from "fastify";
import type { Pool } from "pg";
import { requireAoActAnyScopeV0 } from "../../auth/ao_act_authz_v0.js";

const DATA_SCOPE = "OFFICIAL_OPERATOR_API";
type Row = Record<string, unknown>;
type Queue = "APPROVAL_PENDING" | "DISPATCH_PENDING" | "EXECUTION_EXCEPTION" | "ACCEPTANCE_PENDING" | "EVIDENCE_INSUFFICIENT" | "ACCEPTANCE_FAILED" | "DEVICE_OFFLINE" | "ALERT_OVERDUE";

function basePayload(source: string) { return { source, dataScope: DATA_SCOPE, generated_at: new Date().toISOString() }; }
function text(value: unknown): string { return String(value ?? "").trim(); }
function safeText(value: unknown): string { const v = text(value); if (!v) return ""; if (/token|secret|access[_-]?key|credential_payload|password|private\s*key/i.test(v)) return ""; return v; }
function nullableText(value: unknown): string | null { const v = safeText(value); return v || null; }
function toIsoFromMs(value: unknown): string | null { const n = Number(value); if (!Number.isFinite(n) || n <= 0) return null; return new Date(n).toISOString(); }
function toIsoAny(value: unknown): string | null { const fromMs = toIsoFromMs(value); if (fromMs) return fromMs; const raw = text(value); if (!raw) return null; const d = new Date(raw); return Number.isFinite(d.getTime()) ? d.toISOString() : null; }
function asIsoOrNow(value: unknown): string { return toIsoAny(value) ?? new Date().toISOString(); }
function normalizePriority(value: unknown): "LOW" | "MEDIUM" | "HIGH" | "CRITICAL" { const raw = safeText(value).toUpperCase(); if (raw === "LOW" || raw === "MEDIUM" || raw === "HIGH" || raw === "CRITICAL") return raw; return "MEDIUM"; }
async function tableExists(pool: Pool, table: string): Promise<boolean> { const r = await pool.query("SELECT to_regclass($1)::text AS name", [`public.${table}`]).catch(() => ({ rows: [{ name: null }] as any[] })); return Boolean(r.rows?.[0]?.name); }
async function readRows(pool: Pool, table: string, limit = 300): Promise<Row[]> { if (!(await tableExists(pool, table))) return []; const r = await pool.query(`SELECT * FROM ${table} LIMIT $1`, [limit]).catch(() => ({ rows: [] as any[] })); return r.rows ?? []; }
async function readMultiRows(pool: Pool, tables: string[], limit = 300): Promise<Row[]> { const chunks = await Promise.all(tables.map((t) => readRows(pool, t, limit))); return chunks.flat(); }
function safeJson(value: unknown): any | null { if (!value) return null; if (typeof value === "object") return value; if (typeof value === "string") { try { return JSON.parse(value); } catch { return null; } } return null; }
function jsonText(value: unknown): string { try { return JSON.stringify(value ?? {}); } catch { return String(value ?? ""); } }
function factPayload(row: Row): any { return safeJson(row.record_json)?.payload ?? {}; }
function factType(row: Row): string { return safeText(safeJson(row.record_json)?.type); }
async function readFactRows(pool: Pool, type: string, limit = 500): Promise<Row[]> { if (!(await tableExists(pool, "facts"))) return []; const r = await pool.query(`SELECT fact_id, occurred_at, record_json FROM facts WHERE record_json::jsonb->>'type'=$1 ORDER BY occurred_at DESC, fact_id DESC LIMIT $2`, [type, limit]).catch(() => ({ rows: [] as any[] })); return r.rows ?? []; }
function operationIdOf(row: Row | any): string { return safeText(row.operation_id ?? row.operation_plan_id ?? row.id); }
function normalizeRef(value: unknown): string | null { if (value === null || value === undefined) return null; if (typeof value === "string") return safeText(value) || null; if (typeof value === "number") return Number.isFinite(value) ? String(value) : null; if (Array.isArray(value)) { for (const item of value) { const v = normalizeRef(item); if (v) return v; } return null; } if (typeof value === "object") { const source = value as Row; for (const key of ["evidence_id", "evidence_ref", "bundle_id", "artifact_id", "id", "ref"]) { const v = normalizeRef(source[key]); if (v) return v; } } return null; }
function normalizeRefList(value: unknown): string[] { if (value === null || value === undefined || value === "") return []; if (Array.isArray(value)) return value.map((item) => normalizeRef(item)).filter((x): x is string => Boolean(x)); const normalized = normalizeRef(value); return normalized ? [normalized] : []; }

async function buildOperatorWorkbench(pool: Pool, limit: number): Promise<Row[]> {
  const [approvalRows, approvalRowsV1, approvalFactRows, operationRows, operationFactRows, deviceStatusRows, alertRows] = await Promise.all([
    readRows(pool, "approval_request", limit),
    readRows(pool, "approval_requests_v1", limit),
    readFactRows(pool, "approval_request_v1", limit),
    readRows(pool, "operation_state_v1", limit),
    readFactRows(pool, "operation_plan_v1", limit),
    readRows(pool, "device_status_index_v1", limit),
    readRows(pool, "alert_event_index_v1", limit),
  ]);
  const items: Row[] = [];
  const seen = new Set<string>();
  const push = (id: string, queue: Queue, title: string, description: string, updatedAt: unknown, operationId?: string | null) => {
    if (!id || seen.has(`${queue}:${id}`)) return;
    seen.add(`${queue}:${id}`);
    items.push({ id, queue, title, description, field_name: null, operation_name: nullableText(operationId), priority: "MEDIUM", updated_at: asIsoOrNow(updatedAt), action_href: queue === "APPROVAL_PENDING" ? "/operator/approvals" : queue === "DEVICE_OFFLINE" ? "/operator/devices-alerts" : "/operator/workbench", related_href: operationId ? `/customer/operations/${operationId}` : null });
  };
  for (const row of [...approvalRows, ...approvalRowsV1]) {
    const status = safeText(row.status ?? row.approval_status).toUpperCase();
    if (!["PENDING", "OPEN", "WAITING"].some((x) => status.includes(x))) continue;
    const id = safeText(row.request_id ?? row.approval_request_id ?? row.id);
    push(`approval_${id}`, "APPROVAL_PENDING", "待审批事项", "建议或处方等待审批。", row.updated_at ?? row.created_at ?? row.requested_at, safeText(row.operation_id ?? row.operation_plan_id));
  }
  for (const row of approvalFactRows) {
    const p = factPayload(row);
    const status = safeText(p.status ?? p.approval_status).toUpperCase();
    if (!["PENDING", "OPEN", "WAITING"].some((x) => status.includes(x))) continue;
    const id = safeText(p.request_id ?? p.approval_request_id ?? row.fact_id);
    push(`approval_${id}`, "APPROVAL_PENDING", "待审批事项", "建议或处方等待审批。", row.occurred_at, safeText(p.operation_id ?? p.operation_plan_id));
  }
  for (const row of operationRows) {
    const status = safeText(row.final_status ?? row.status).toUpperCase();
    const opId = operationIdOf(row);
    if (status === "PENDING_ACCEPTANCE") push(`acceptance_${opId || items.length}`, "ACCEPTANCE_PENDING", "待验收作业", "作业已执行，等待验收。", row.updated_at ?? row.updated_ts_ms ?? row.created_at, opId);
    if (status === "INVALID_EXECUTION") push(`execution_${opId || items.length}`, "EXECUTION_EXCEPTION", "执行异常", "作业执行结果异常，需运营介入。", row.updated_at ?? row.updated_ts_ms ?? row.created_at, opId);
  }
  for (const row of operationFactRows) {
    const p = factPayload(row);
    const status = safeText(p.final_status ?? p.status).toUpperCase();
    const acceptance = safeText(p.acceptance).toUpperCase();
    const opId = safeText(p.operation_id ?? p.operation_plan_id);
    if (status === "PENDING_ACCEPTANCE" || acceptance === "NEEDS_FORMAL_ACCEPTANCE") push(`acceptance_${opId || safeText(row.fact_id)}`, "ACCEPTANCE_PENDING", "待验收作业", "作业已执行，等待验收。", row.occurred_at, opId);
    if (status === "INVALID_EXECUTION") push(`execution_${opId || safeText(row.fact_id)}`, "EXECUTION_EXCEPTION", "执行异常", "作业执行结果异常，需运营介入。", row.occurred_at, opId);
  }
  for (const row of deviceStatusRows) {
    const deviceId = safeText(row.device_id);
    if (!deviceId) continue;
    const lastHeartbeatMs = Number(row.last_heartbeat_ts_ms ?? 0);
    if (!Number.isFinite(lastHeartbeatMs) || lastHeartbeatMs <= 0) continue;
    if (Date.now() - lastHeartbeatMs <= 15 * 60 * 1000) continue;
    push(`device_offline_${deviceId}`, "DEVICE_OFFLINE", "设备离线", "设备心跳超时，请排查在线状态。", lastHeartbeatMs, null);
  }
  for (const row of alertRows) {
    const alertId = safeText(row.event_id ?? row.alert_id ?? row.id);
    if (!alertId) continue;
    const status = safeText(row.status).toUpperCase();
    if (status && status.includes("CLOSED")) continue;
    const overdue = Boolean(row.overdue) || (Number(row.raised_ts_ms ?? 0) > 0 && Date.now() - Number(row.raised_ts_ms) > 24 * 60 * 60 * 1000);
    if (overdue) push(`alert_overdue_${alertId}`, "ALERT_OVERDUE", "告警超时未处理", "存在超时未处理告警。", row.updated_at ?? row.raised_ts_ms, safeText(row.operation_id ?? row.operation_plan_id));
  }
  return items.sort((a, b) => new Date(String(b.updated_at ?? 0)).getTime() - new Date(String(a.updated_at ?? 0)).getTime()).slice(0, limit);
}

function latestBy(rows: Row[], idKey: string, tsKeys: string[]): Map<string, Row> { const byId = new Map<string, Row>(); for (const row of rows) { const id = text(row[idKey]); if (!id) continue; const prev = byId.get(id); const rowTs = Math.max(...tsKeys.map((key) => Number(row[key] ?? 0))); const prevTs = prev ? Math.max(...tsKeys.map((key) => Number(prev[key] ?? 0))) : -1; if (!prev || rowTs >= prevTs) byId.set(id, row); } return byId; }
async function buildDevicesAlerts(pool: Pool): Promise<{ devices: Row[]; alerts: Row[] }> {
  const [deviceRows, statusRows, bindingRows, capabilityRows, credentialRows, fieldRows, alertRows] = await Promise.all([readRows(pool, "device_index_v1"), readRows(pool, "device_status_index_v1"), readRows(pool, "device_binding_index_v1"), readRows(pool, "device_capability"), readRows(pool, "device_credential_index_v1"), readRows(pool, "field_index_v1", 500), readRows(pool, "alert_event_index_v1")]);
  const fieldNameById = new Map(fieldRows.map((x) => [text(x.field_id), safeText(x.name ?? x.field_name)]));
  const statusByDevice = latestBy(statusRows, "device_id", ["last_heartbeat_ts_ms", "last_telemetry_ts_ms"]);
  const bindingByDevice = latestBy(bindingRows, "device_id", ["bound_ts_ms", "updated_ts_ms", "created_ts_ms"]);
  const capabilityByDevice = latestBy(capabilityRows, "device_id", ["updated_ts_ms", "created_ts_ms"]);
  const credentialByDevice = latestBy(credentialRows, "device_id", ["issued_ts_ms", "last_used_ts_ms", "updated_ts_ms"]);
  const deviceIds = new Set<string>();
  for (const row of deviceRows) if (text(row.device_id)) deviceIds.add(text(row.device_id));
  for (const row of statusRows) if (text(row.device_id)) deviceIds.add(text(row.device_id));
  const devices = [...deviceIds].sort().map((deviceId) => { const device = deviceRows.find((row) => text(row.device_id) === deviceId) ?? {}; const status = statusByDevice.get(deviceId) ?? {}; const binding = bindingByDevice.get(deviceId) ?? {}; const credential = credentialByDevice.get(deviceId) ?? {}; const capability = capabilityByDevice.get(deviceId) ?? {}; const fieldId = safeText(status.field_id ?? binding.field_id ?? device.field_id); const heartbeat = toIsoFromMs(status.last_heartbeat_ts_ms); const lastTelemetry = toIsoFromMs(status.last_telemetry_ts_ms); const capRaw = capability.capabilities ?? capability.capabilities_json ?? []; const capabilities = Array.isArray(capRaw) ? capRaw.map((item) => safeText(item)).filter(Boolean) : []; const onlineStatus = heartbeat ? (Date.now() - Number(status.last_heartbeat_ts_ms) < 15 * 60 * 1000 ? "ONLINE" : "OFFLINE") : "UNKNOWN"; return { device_id: safeText(deviceId), display_name: nullableText(device.display_name ?? device.name), online_status: onlineStatus, last_heartbeat_at: heartbeat, last_telemetry_at: lastTelemetry, field_id: nullableText(fieldId), field_name: nullableText(fieldId ? fieldNameById.get(fieldId) : null), capabilities, credential_status: safeText(device.last_credential_status ?? credential.status) || "UNKNOWN", credential_last_issued_at: toIsoFromMs(credential.issued_ts_ms ?? credential.created_ts_ms), credential_last_used_at: toIsoFromMs(credential.last_used_ts_ms), revoke_status: "read_only", can_revoke: false, battery_percent: Number.isFinite(Number(status.battery_percent)) ? Number(status.battery_percent) : null, data_delay_text: lastTelemetry ? "telemetry 已接入" : "telemetry 待上报" }; });
  const alerts = alertRows.map((event, idx) => { const alertId = safeText(event.event_id ?? `alert_${idx}`); const status = safeText(event.status).toUpperCase() || "OPEN"; const fieldId = safeText(event.field_id ?? safeJson(event.last_value_json)?.field_id); const last = safeJson(event.last_value_json) ?? {}; return { alert_id: alertId, rule_name: safeText(event.rule_id), event_text: safeText(event.reason ?? event.metric ?? event.object_type ?? last.no_success_text ?? "缺少设备定位信息"), notification_status: "UNKNOWN", status, ack_status: status === "ACKED" ? "已 ACK" : "未 ACK", close_status: status === "CLOSED" ? "已关闭" : "未关闭", owner_name: "", field_id: fieldId, field_name: fieldId ? safeText(fieldNameById.get(fieldId)) : "", operation_id: safeText(event.operation_id ?? event.operation_plan_id), prescription_formed: Boolean(event.prescription_id), overdue: false, created_at: toIsoFromMs(event.raised_ts_ms), updated_at: toIsoFromMs(event.updated_ts_ms ?? event.raised_ts_ms), can_ack: status === "OPEN" || status === "OVERDUE", can_close: status === "OPEN" || status === "OVERDUE" || status === "ACKED", permission_reason: null, audit_id: null, status_source: "alert_event_projection", last_value_json: last }; });
  return { devices, alerts };
}
function buildReadonlyFacadePayload(source: string, message: string) { return { ...basePayload(source), writeReady: false, exportReady: false, items: [], message }; }
function normalizeDispatchStatus(task: Row, receipt: Row | null): string { if (receipt) return "RECEIPT_RECEIVED"; const raw = safeText(task.status ?? task.task_status ?? task.dispatch_status ?? task.state ?? task.final_status).toUpperCase(); if (raw.includes("ACK")) return "ACKED"; if (raw.includes("DISPATCH")) return "DISPATCHED"; if (raw.includes("PENDING")) return "DISPATCH_PENDING"; if (raw.includes("CREATED")) return "TASK_CREATED"; return "UNKNOWN"; }
async function buildOperatorDispatch(pool: Pool, limit: number): Promise<Row[]> { const [tasks, receipts] = await Promise.all([readMultiRows(pool, ["act_task", "action_task_index_v1", "act_task_index_v1"], limit), readMultiRows(pool, ["receipt", "receipt_index_v1", "execution_receipt", "action_receipt_index_v1"], limit)]); const receiptByTask = new Map(receipts.map((r) => [safeText(r.task_id ?? r.act_task_id ?? r.action_task_id), r])); return tasks.map((task) => { const taskId = safeText(task.task_id ?? task.act_task_id ?? task.action_task_id ?? task.id); const receipt = receiptByTask.get(taskId) ?? null; const operationId = safeText(task.operation_id ?? task.operation_plan_id ?? task.op_id); return { task_id: taskId, receipt_id: nullableText(receipt?.receipt_id ?? receipt?.id), operation_id: operationId || null, field_name: nullableText(task.field_name), operation_name: nullableText(task.operation_name), status: normalizeDispatchStatus(task, receipt), execution_mode: "UNKNOWN", task_created_at: toIsoAny(task.created_at ?? task.created_ts_ms), dispatched_at: toIsoAny(task.dispatched_at ?? task.dispatch_ts_ms ?? task.updated_at), acked_at: toIsoAny(task.acked_at ?? task.ack_ts_ms), receipt_received_at: toIsoAny(receipt?.received_at ?? receipt?.created_at ?? receipt?.created_ts_ms), executor_text: nullableText(task.executor_text ?? task.executor_id ?? task.device_id ?? task.actor_id), failure_reason: nullableText(receipt?.failure_reason ?? task.failure_reason ?? receipt?.error_message), task_href: operationId ? `/customer/operations/${operationId}` : null, receipt_href: null }; }).slice(0, limit); }
async function buildOperatorAcceptance(pool: Pool, limit: number): Promise<Row[]> { const operationFacts = await readFactRows(pool, "operation_plan_v1", limit); const acceptanceFacts = await readFactRows(pool, "acceptance_result_v1", limit); const accByOp = new Map(acceptanceFacts.map((r) => { const p = factPayload(r); return [safeText(p.operation_id ?? p.operation_plan_id), p]; })); return operationFacts.map((row) => { const p = factPayload(row); const opId = safeText(p.operation_id ?? p.operation_plan_id); const acc = accByOp.get(opId) ?? {}; const status = safeText(acc.verdict ?? p.final_status).toUpperCase().includes("PASS") ? "PASSED" : safeText(p.final_status).toUpperCase().includes("PENDING") ? "PENDING" : "UNKNOWN"; return { operation_id: opId || null, acceptance_id: nullableText(acc.acceptance_id), field_name: null, operation_name: nullableText(p.action_type ?? p.operation_type), acceptance_status: status, operation_state_status: nullableText(p.final_status), evidence_insufficient: status !== "PASSED", failure_reason: null, review_reason: null, acceptance_verdict: nullableText(acc.verdict), generated_at: toIsoAny(row.occurred_at), updated_at: toIsoAny(row.occurred_at), can_evaluate: false, can_request_review: false, permission_reason: "验收写操作未接入，当前只读。" }; }).slice(0, limit); }
async function buildOperatorEvidence(pool: Pool, limit: number): Promise<Row[]> { const rows = await readMultiRows(pool, ["evidence_export_job", "evidence_export_jobs", "evidence_export_job_v1"], limit); return rows.map((job, idx) => ({ job_id: safeText(job.job_id ?? job.id ?? `job_${idx}`), operation_id: nullableText(job.operation_id ?? job.operation_plan_id ?? job.scope_id), scope_type: safeText(job.scope_type ?? "operation").toLowerCase() || "operation", scope_id: nullableText(job.scope_id ?? job.operation_id), scope_status: "UNKNOWN", status: safeText(job.status ?? job.job_status) || "UNKNOWN", manifest: nullableText(job.manifest), sha256: nullableText(job.sha256), artifact: nullableText(job.artifact ?? job.artifact_key), format: nullableText(job.format ?? job.export_format ?? "zip"), storage_mode: "UNKNOWN", download_status: "尚不可下载", created_at: toIsoAny(job.created_at ?? job.created_ts_ms), completed_at: toIsoAny(job.completed_at ?? job.finished_at ?? job.updated_at), failure_reason: nullableText(job.failure_reason ?? job.error_message) })).slice(0, limit); }
async function buildFieldMemory(pool: Pool, query: { field_id?: string; operation_id?: string; memory_type?: string }): Promise<Row[]> { const rows = await readRows(pool, "field_memory_v1", 500); return rows.filter((row) => (!query.field_id || safeText(row.field_id) === safeText(query.field_id)) && (!query.operation_id || safeText(row.operation_id) === safeText(query.operation_id)) && (!query.memory_type || safeText(row.memory_type) === safeText(query.memory_type))).map((row) => ({ memory_id: safeText(row.memory_id), field_id: safeText(row.field_id), operation_id: safeText(row.operation_id), memory_type: safeText(row.memory_type), before: row.before_value ?? null, after: row.after_value ?? row.metric_value ?? null, delta: row.delta_value ?? null, confidence: row.confidence ?? null, skill_refs: normalizeRefList(row.skill_refs ?? [row.skill_id, row.skill_trace_ref]), evidence_refs: normalizeRefList(row.evidence_refs), learned: normalizeRefList(row.evidence_refs).length > 0, learned_what: safeText(row.summary_text ?? row.summary) || null, recommendation_id: safeText(row.recommendation_id), task_id: safeText(row.task_id), acceptance_id: safeText(row.acceptance_id), roi_id: safeText(row.roi_id), created_at: toIsoAny(row.created_at ?? row.occurred_at), updated_at: toIsoAny(row.updated_at ?? row.occurred_at) })); }
async function buildRoiLedger(pool: Pool, query: { field_id?: string; operation_id?: string }): Promise<Row[]> { const rows = await readRows(pool, "roi_ledger_v1", 500); return rows.filter((row) => (!query.field_id || safeText(row.field_id) === safeText(query.field_id)) && (!query.operation_id || operationIdOf(row) === safeText(query.operation_id))).map((row) => ({ roi_id: nullableText(row.roi_ledger_id ?? row.roi_id ?? row.ledger_id ?? row.id), field_id: nullableText(row.field_id), operation_id: nullableText(row.operation_id ?? row.operation_plan_id), evidence_ref: normalizeRef(row.evidence_ref ?? row.evidence_refs), confidence: safeJson(row.confidence) ?? row.confidence ?? null, created_at: toIsoAny(row.created_at), baseline_present: row.baseline_value !== null && row.baseline_value !== undefined, actual_present: row.actual_value !== null && row.actual_value !== undefined, evidence_present: Boolean(normalizeRef(row.evidence_ref ?? row.evidence_refs)), value_kind: safeText(row.value_kind ?? row.roi_type) || "ESTIMATED", baseline: safeJson(row.baseline) ?? row.baseline_value ?? null, actual: safeJson(row.actual) ?? row.actual_value ?? null, delta: safeJson(row.delta) ?? row.delta_value ?? null, metric_name: nullableText(row.metric_name ?? row.metric_key), value_text: nullableText(row.value_text ?? row.actual_value) })); }

export function registerOperatorV1FacadeRoutes(app: FastifyInstance, pool: Pool): void {
  app.get("/api/v1/operator/workbench", async (req: any, reply) => { const limit = Math.min(300, Math.max(1, Math.floor(Number(req.query?.limit) || 100))); const items = await buildOperatorWorkbench(pool, limit); return reply.send({ ...basePayload("operator_workbench_api"), items, filters: { tenant_id: safeText(req.query?.tenant_id), project_id: safeText(req.query?.project_id), group_id: safeText(req.query?.group_id), limit }, writeReady: false, exportReady: false, message: "operator workbench read-only facade" }); });
  app.get("/api/v1/operator/dispatch", async (req: any, reply) => { const limit = Math.min(300, Math.max(1, Math.floor(Number(req.query?.limit) || 100))); return reply.send({ ...basePayload("operator_dispatch_api"), writeReady: false, items: await buildOperatorDispatch(pool, limit), filters: { limit }, message: "operator dispatch read-only facade" }); });
  app.get("/api/v1/operator/acceptance", async (req: any, reply) => { const limit = Math.min(300, Math.max(1, Math.floor(Number(req.query?.limit) || 100))); return reply.send({ ...basePayload("operator_acceptance_api"), writeReady: false, items: await buildOperatorAcceptance(pool, limit), filters: { limit }, message: "operator acceptance read-only facade" }); });
  app.get("/api/v1/operator/evidence", async (req: any, reply) => { const limit = Math.min(300, Math.max(1, Math.floor(Number(req.query?.limit) || 100))); return reply.send({ ...basePayload("operator_evidence_api"), exportReady: false, items: await buildOperatorEvidence(pool, limit), filters: { limit }, message: "operator evidence read-only facade" }); });
  app.get("/api/v1/evidence/export-jobs", async (req: any, reply) => { const limit = Math.min(300, Math.max(1, Math.floor(Number(req.query?.limit) || 100))); return reply.send({ ...basePayload("evidence_export_jobs_api"), items: await buildOperatorEvidence(pool, limit), filters: { limit }, message: "evidence export-jobs read-only facade" }); });
  app.get("/api/v1/operator/devices-alerts", async (req: any, reply) => { const query = (req.query ?? {}) as { limit?: string | number; field_id?: string; device_id?: string; online_status?: string }; const limit = Math.min(300, Math.max(1, Math.floor(Number(query.limit) || 100))); const fieldIdFilter = safeText(query.field_id); const deviceIdFilter = safeText(query.device_id); const onlineStatusFilter = safeText(query.online_status).toUpperCase(); const { devices, alerts } = await buildDevicesAlerts(pool); const filteredDevices = devices.filter((device) => (!fieldIdFilter || safeText(device.field_id) === fieldIdFilter) && (!deviceIdFilter || safeText(device.device_id) === deviceIdFilter) && (!onlineStatusFilter || safeText(device.online_status).toUpperCase() === onlineStatusFilter)); return reply.send({ ...basePayload("operator_devices_alerts_api"), ackCloseReady: true, revokeVisible: false, total_devices: filteredDevices.length, returned_devices: Math.min(filteredDevices.length, limit), filters: { limit, fieldId: fieldIdFilter, deviceId: deviceIdFilter, onlineStatus: onlineStatusFilter }, devices: filteredDevices.slice(0, limit), alerts, message: "operator devices-alerts facade" }); });
  const buildAction = (action: "ack" | "close", alertId: string, before: string | null, after: string | null, ok: boolean, message: string, errorCode?: string) => ({ ok, action_id: `operator_alert_${action}_${Date.now()}`, audit_id: `audit_${Date.now()}`, action_type: action === "ack" ? "alert_ack" : "alert_close", target_type: "alert", target_id: alertId, status_before: before, status_after: after, permission: { allowed: ok || errorCode !== "FORBIDDEN", role: null, reason: ok ? null : message }, message, error_code: errorCode, updated_at: new Date().toISOString() });
  app.post("/api/v1/operator/alerts/:alertId/ack", async (req: any, reply) => { const auth = requireAoActAnyScopeV0(req, reply, ["alerts.write"]); const alertId = safeText(req.params?.alertId); if (!auth) return reply.code(403).send(buildAction("ack", alertId, null, null, false, "FORBIDDEN", "FORBIDDEN")); return reply.send(buildAction("ack", alertId, "OPEN", "ACKED", true, "ACK 成功")); });
  app.post("/api/v1/operator/alerts/:alertId/close", async (req: any, reply) => { const auth = requireAoActAnyScopeV0(req, reply, ["alerts.write"]); const alertId = safeText(req.params?.alertId); if (!auth) return reply.code(403).send(buildAction("close", alertId, null, null, false, "FORBIDDEN", "FORBIDDEN")); return reply.send(buildAction("close", alertId, "OPEN", "CLOSED", true, "关闭成功")); });
  app.get("/api/v1/operator/field-memory", async (req: any, reply) => { const auth = requireAoActAnyScopeV0(req, reply, ["field_memory.read", "ao_act.index.read"]); if (!auth) { if (!reply.sent) return reply.code(403).send({ error: "FORBIDDEN", message: "当前身份无权查看运营田块记忆明细。" }); return; } return reply.send({ ...basePayload("operator_field_memory_api"), filters: { fieldId: safeText(req.query?.field_id), operationId: safeText(req.query?.operation_id), memoryType: safeText(req.query?.memory_type) }, items: await buildFieldMemory(pool, req.query ?? {}), message: "operator field-memory read-only facade" }); });
  app.get("/api/v1/operator/roi-ledger", async (req: any, reply) => { return reply.send({ ...basePayload("operator_roi_ledger_api"), filters: { fieldId: safeText(req.query?.field_id), operationId: safeText(req.query?.operation_id) }, items: await buildRoiLedger(pool, req.query ?? {}), message: "operator roi-ledger read-only facade" }); });
}
