#!/usr/bin/env node
'use strict';
const {buildSyntheticPerRunSourceV1}=require('../../governance_acceptance/mcft_cap08_s6_witness/synthetic_fixture_v1.cjs');
const {sha}=require('./identity_v1.cjs');
function makeMember(plan,role,type,ref,phase,time){return{formal_run_id:plan.formal_run_id,...plan.scope,lineage_id:plan.lineage_id,revision_id:plan.revision_id,member_role:role,object_type:type,object_ref:ref,object_hash:`sha256:${sha({type,ref,phase,time})}`,phase_id:phase,logical_time:time};}
function buildSyntheticOrchestratorInputV1(plan){const base=buildSyntheticPerRunSourceV1({exact_subject_sha:plan.exact_subject_sha,run_label:plan.run_label,formal_run_id:plan.formal_run_id,operational_run_instance_id:plan.operational_run_instance_id,...plan.scope,lineage_id:plan.lineage_id,revision_id:plan.revision_id,artifact_digest:`sha256:${sha(`artifact-${plan.run_label}`)}`,object_set_ref:`urn:synthetic:${plan.run_label}`});const members=[];members.push(makeMember(plan,'BOOTSTRAP_ROOT','twin_runtime_lineage_v1',`LINEAGE-${plan.formal_run_id}`,'B00','2026-06-01T00:00:00.000Z'));members.push(makeMember(plan,'BOOTSTRAP_STATE','twin_state_estimate_v1','STATE-B00','B00','2026-06-01T00:00:00.000Z'));for(let i=0;i<24;i++){const t=`T${String(i).padStart(2,'0')}`,time=`2026-06-01T${String(i).padStart(2,'0')}:00:00.000Z`;members.push(makeMember(plan,'RUNTIME_TICK','twin_runtime_tick_v1',`TICK-${t}`,t,time),makeMember(plan,'POSTERIOR_STATE','twin_state_estimate_v1',`STATE-${t}`,t,time),makeMember(plan,'FORECAST_RUN','twin_forecast_run_v1',`FORECAST-${t}`,t,time),makeMember(plan,'SCENARIO_SET','twin_scenario_set_v1',`SCENARIO-${t}`,t,time));}for(let i=1;i<=24;i++){const id=String(i).padStart(2,'0'),phase=i===1?'T16':i===24?'G00':`T${id}`,time=`2026-06-02T${String(i%24).padStart(2,'0')}:00:00.000Z`;members.push(makeMember(plan,'FORECAST_VERIFICATION_OBSERVATION','forecast_verification_observation_v1',`FVO-${id}`,phase,time),makeMember(plan,'FORECAST_RESIDUAL','twin_forecast_residual_v1',`R-${id}`,phase,time));}members.push(makeMember(plan,'DECISION_RECORD','twin_decision_v1','DECISION-T05','T05','2026-06-01T05:00:00.000Z'),makeMember(plan,'APPROVAL_ASSERTION','approval_assertion_v1','APPROVAL-1','T06','2026-06-01T06:00:00.000Z'),makeMember(plan,'APPROVED_PLAN','approved_plan_v1','PLAN-1','T06','2026-06-01T06:00:00.000Z'),makeMember(plan,'EXECUTION_RECEIPT','execution_receipt_v1','RECEIPT-1','T07','2026-06-01T07:00:00.000Z'),makeMember(plan,'ACTION_FEEDBACK','twin_action_feedback_v1','FEEDBACK-1','T08','2026-06-01T08:00:00.000Z'),makeMember(plan,'CALIBRATION_CANDIDATE','twin_calibration_candidate_v1','CANDIDATE-1','G01','2026-06-02T01:00:00.000Z'),makeMember(plan,'SHADOW_EVALUATION','twin_shadow_evaluation_v1','SHADOW-1','G02','2026-06-02T02:00:00.000Z'));
 const events=plan.phases.flatMap((p,pi)=>p.phase_order.map((phase,sequence)=>({run_label:plan.run_label,formal_run_id:plan.formal_run_id,operational_run_instance_id:plan.operational_run_instance_id,phase_id:p.phase_id,phase,sequence,event_ref:`EVENT-${pi}-${sequence}`})));
 return{selectorData:base,canonicalMembers:members,events,databaseInstanceDigest:`sha256:${sha(`database-${plan.run_label}`)}`,artifactRef:`synthetic://orchestrator/${plan.run_label}`,artifactDigest:`sha256:${sha(`artifact-${plan.run_label}`)}`};}
module.exports={buildSyntheticOrchestratorInputV1};
