import React from "react";
import { Link } from "react-router-dom";
import { fetchDevices, type DeviceListItem } from "../lib/api";

function readToken(): string { try { return localStorage.getItem("geox_ao_act_token") || "geox_dev_MqF24b9NHfB6AkBNjKJaxP_T0CnL0XZykhdmSyoQvg4"; } catch { return "geox_dev_MqF24b9NHfB6AkBNjKJaxP_T0CnL0XZykhdmSyoQvg4"; } }
function fmtTs(v: number | null | undefined): string { return typeof v === "number" && Number.isFinite(v) && v > 0 ? new Date(v).toLocaleString("zh-CN", { hour12: false }) : "-"; }

export default function DevicesPage(): React.ReactElement {
  const [token, setToken] = React.useState<string>(() => readToken());
  const [items, setItems] = React.useState<DeviceListItem[]>([]);
  const [status, setStatus] = React.useState<string>("正在准备设备中心...");
  const [busy, setBusy] = React.useState<boolean>(false);
  function persistToken(next: string): void { setToken(next); try { localStorage.setItem("geox_ao_act_token", next); } catch {} }
  async function refresh(): Promise<void> { setBusy(true); setStatus("正在读取设备列表..."); try { const nextItems = await fetchDevices(token); setItems(nextItems); setStatus(`已加载 ${nextItems.length} 台设备。`); } catch (e: any) { setStatus(`读取失败：${e?.message || String(e)}`); } finally { setBusy(false); } }
  React.useEffect(() => { void refresh(); }, []);
  return (<div className="consolePage"><section className="hero card compactHero"><div><div className="eyebrow">Devices · Sprint D2</div><h2 className="heroTitle">设备中心</h2><p className="heroText">设备列表页现在作为“接入与执行控制台”的入口：从列表进入详情后，可查看接入信息、凭据摘要、最近命令与设备回执。</p></div><div className="heroActions"><button className="btn primary" onClick={() => void refresh()} disabled={busy}>刷新设备</button></div></section><div className="summaryGrid"><div className="metricCard card"><div className="metricLabel">设备总数</div><div className="metricValue">{items.length}</div><div className="metricHint">当前租户已注册设备</div></div><div className="metricCard card"><div className="metricLabel">在线设备</div><div className="metricValue">{items.filter((x) => x.connection_status === "ONLINE").length}</div><div className="metricHint">最近 15 分钟心跳</div></div><div className="metricCard card"><div className="metricLabel">已绑定田块</div><div className="metricValue">{items.filter((x) => !!x.field_id).length}</div><div className="metricHint">具备 field 归属</div></div><div className="metricCard card"><div className="metricLabel">页面状态</div><div className="metricValue">{status.includes("失败") ? "异常" : "正常"}</div><div className="metricHint">{status}</div></div></div><section className="card sectionBlock"><div className="sectionHeader"><div><div className="sectionTitle">设备列表</div><div className="sectionDesc">展示设备绑定、心跳、最新遥测等运营摘要，帮助快速定位问题设备与未绑定设备；点击后进入 D2 设备控制台详情。</div></div></div><label className="field">访问令牌<input className="input" value={token} onChange={(e) => persistToken(e.target.value)} /></label><div className="list modernList">{items.map((item) => (<Link key={item.device_id} className="infoCard linkCard" to={`/devices/${encodeURIComponent(item.device_id)}`}><div className="jobTitleRow"><div><div className="title">{item.display_name || item.device_id}</div><div className="metaText">{item.device_id}</div></div><div className={`pill tone-${item.connection_status === "ONLINE" ? "ok" : "warn"}`}>{item.connection_status}</div></div><div className="meta wrapMeta"><span>田块：{item.field_id || "未绑定"}</span><span>最新心跳：{fmtTs(item.last_heartbeat_ts_ms)}</span><span>最新遥测：{fmtTs(item.last_telemetry_ts_ms)}</span><span>电量：{typeof item.battery_percent === "number" ? `${item.battery_percent}%` : "-"}</span><span>固件：{item.fw_ver || "-"}</span></div></Link>))}{!items.length ? <div className="emptyState">当前还没有可展示的设备。可先通过 acceptance 或 API 注册设备。</div> : null}</div></section></div>);
}
