#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),c=require('node:crypto'),x=require('node:child_process'),f=require('node:fs'),p=require('node:path');
const R=p.resolve(__dirname,'../..'),B='19f75275a223caa5196982344be57c871e7755d2',O=p.join(R,'acceptance-output/MCFT_CAP_08_S6_PRE_CANDIDATE_GOVERNANCE_RESULT.json'),D='docs/digital_twin/mcft/cap_08/';
const P={r:'docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json',b:D+'GEOX-MCFT-CAP-08-S6-CHANGED-FILE-BOUNDARY-V1.json',s:D+'GEOX-MCFT-CAP-08-S6-DELIVERY-STATUS-V1.json',c:D+'GEOX-MCFT-CAP-08-S6-CONTRACT-V1.json',p:D+'GEOX-MCFT-CAP-08-S6-PREDECESSOR-CONSUMPTION-V1.json',v:D+'GEOX-MCFT-CAP-08-S6-REVIEW-POLICY-V1.json',w:D+'GEOX-MCFT-CAP-08-S6-WORKFLOW-DECLARATION-V1.json',t:D+'GEOX-MCFT-CAP-08-TASK.md',h:D+'GEOX-MCFT-CAP-08-TASK-v0.3.5-HISTORICAL-FULL.md'};
const g=(...z)=>x.execFileSync('git',z,{cwd:R,encoding:'utf8'}).trim(),j=q=>JSON.parse(f.readFileSync(p.join(R,q),'utf8')),out=q=>{f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(q,null,2)+'\n')};
function k(q){if(Array.isArray(q))return'['+q.map(k).join(',')+']';if(q&&typeof q==='object')return'{'+Object.keys(q).sort().map(z=>JSON.stringify(z)+':'+k(q[z])).join(',')+'}';return JSON.stringify(q)}function hash(q){q=structuredClone(q);delete q.semantic_digest;return'sha256:'+c.createHash('sha256').update(k(q)).digest('hex')}
try{const b=String(process.env.MCFT_BASE_SHA||B).trim();a.equal(b,B);a.equal(g('merge-base',b,'HEAD'),b);a.equal(g('diff','--check',b+'...HEAD'),'');const [r,n,s,m,e,v,w]=[P.r,P.b,P.s,P.c,P.p,P.v,P.w].map(j),z=g('diff','--name-only',b+'...HEAD').split(/\r?\n/).filter(Boolean).sort();
 a.deepEqual(z,[...n.changed_files].sort());a.equal(z.length,9);a.equal(n.base_sha,b);a.equal(n.changed_file_count,9);for(const q of ['runtime_source_file_count','runtime_acceptance_file_count','database_migration_file_count','route_file_count','web_file_count'])a.equal(n[q],0);a.equal(n.candidate_declaration_present,false);a.equal(n.s6_candidate_implemented,false);a.equal(n.independent_review_required,true);a.equal(n.independent_review_waived,false);a.equal(z.some(q=>q.startsWith('apps/server/')||q.startsWith('apps/web/')||q.includes('migration')||q.includes('scheduler')||q.includes('model_activation')),false);
 a.equal(g('rev-parse','HEAD:'+P.t),'a24114ff629560345b3bd3cda6b4024b9f3d61e4');a.equal(g('rev-parse','HEAD:'+P.h),'ab4f4e7d9d3978ac3be979583cda4ccdc94a2fb6');a.equal(g('rev-parse','HEAD:'+P.t),g('rev-parse',b+':'+P.t));
 a.equal(m.semantic_digest,hash(m));a.equal(m.semantic_digest,'sha256:c288a987b007eccc25a22f117eb1d9b53e8f551a9566ce322674a1bd082657ab');a.deepEqual(m.required_phase_order,['resolve','E','H','A','B','G','C','barrier']);a.equal(m.formal_run_contract.run_count,2);a.deepEqual(m.formal_run_contract.run_ids,['RUN_A','RUN_B']);a.equal(m.formal_run_contract.fresh_database_per_run,true);a.equal(m.formal_run_contract.same_deterministic_formal_run_id,true);a.equal(m.formal_run_contract.different_operational_run_instance_id,true);a.deepEqual(m.formal_run_contract.all_providers_enabled_from_start,['E','H','A','B','G','C','D','F']);a.deepEqual({residual:m.closure_cardinality.forecast_residual,calibration:m.closure_cardinality.calibration_case,holdout:m.closure_cardinality.holdout_case,candidate:m.closure_cardinality.calibration_candidate,shadow:m.closure_cardinality.shadow_evaluation,activation:m.closure_cardinality.model_activation},{residual:24,calibration:16,holdout:8,candidate:1,shadow:1,activation:0});a.equal(m.recovery_contract.fresh_process_restart_required,true);a.equal(m.recovery_contract.post_commit_response_loss_recovery_required,true);a.equal(m.recovery_contract.extreme_pointer_loss_rebuild_required,true);a.equal(m.hard_acceptance_contract.ledger_item_count,24);a.equal(m.read_model_contract.cap07_get_surface_count,10);a.equal(m.read_model_contract.product_read_write_delta,0);a.equal(m.review_contract.independent_review_required,true);a.equal(m.review_contract.verified_second_github_account_required,true);a.equal(m.review_contract.waiver_authorized,false);a.equal(m.retention_contract.level,'R2');a.equal(m.retention_contract.days,730);a.equal(m.successor_boundary.mcft_cap_09_authorized,false);a.equal(m.implementation_authorized,false);a.equal(m.candidate_declaration_authorized,false);a.equal(m.mcft_cap_08_complete,false);
 a.equal(s.record_status,'PRE_REGISTERED_FINAL_CLOSURE_STATUS_SEED');a.equal(s.s6_candidate_implemented,false);a.equal(s.implementation_authorized,false);a.equal(s.independent_review_required,true);a.equal(s.independent_review_satisfied,false);a.equal(s.independent_review_performed,false);a.equal(s.independent_review_waived,false);a.equal(s.verified_second_github_account_required,true);a.equal(s.candidate_merge_requires_independent_review,true);a.equal(s.exact_sha_attestation_requires_independent_review,true);a.equal(s.required_closure_retention_level,'R2');a.equal(s.required_closure_retention_days,730);a.equal(s.mcft_cap_08_complete,false);a.equal(s.mcft_cap_09_status_seed_present,false);a.equal(s.mcft_cap_09_registry_rule_present,false);a.equal(s.mcft_cap_09_authorized,false);
 a.equal(e.record_status,'PRE_REGISTERED_AWAITING_S5_EXACT_SHA_EFFECTIVENESS');a.equal(e.required_effective_status,'S5_RESIDUAL_CALIBRATION_SHADOW_IMPLEMENTED_EFFECTIVE');a.equal(e.required_effective_next_slice,'S6');a.equal(e.required_artifact_readback,true);a.equal(e.source_merge_subject_sha,null);a.equal(e.predecessor_effectiveness_satisfied,false);a.equal(e.implementation_entry_authorized,false);
 a.equal(v.independent_review_required,true);a.equal(v.independent_review_satisfied,false);a.equal(v.independent_review_performed,false);a.equal(v.independent_review_waived,false);a.equal(v.waiver_authorized,false);a.equal(v.verified_second_github_account_required,true);a.equal(v.reviewer_must_differ_from_candidate_author,true);a.equal(v.reviewer_account_type_required,'User');a.equal(v.bot_review_forbidden,true);a.equal(v.review_state_required,'APPROVED');a.equal(v.review_must_target_exact_s6_candidate_head,true);a.equal(v.required_before_candidate_merge,true);a.equal(v.required_before_exact_sha_attestation,true);
 a.equal(w.governance_workflow.candidate_declaration_expected,false);a.equal(w.candidate_workflow.present_in_governance_pr,false);a.equal(w.candidate_workflow.fresh_database_run_count,2);a.equal(w.candidate_workflow.requires_exact_head_independent_approval,true);a.equal(w.exact_sha_workflow.retention_level,'R2');a.equal(w.exact_sha_workflow.retention_days,730);
 const br=JSON.parse(g('show',b+':'+P.r)),tc=structuredClone(r),tb=structuredClone(br);for(const q of [tc,tb]){delete q.authority_set_revision;delete q.authority_set_change_id;delete q.capabilities}a.deepEqual(tc,tb);for(const l of ['MCFT-CAP-06','MCFT-CAP-07'])a.deepEqual(r.capabilities.find(q=>q.capability_line===l),br.capabilities.find(q=>q.capability_line===l));const cc=structuredClone(r.capabilities.find(q=>q.capability_line==='MCFT-CAP-08')),bc=br.capabilities.find(q=>q.capability_line==='MCFT-CAP-08');cc.authoritative_candidate_status_paths=cc.authoritative_candidate_status_paths.filter(q=>q!==P.s);cc.candidate_transition_fields=cc.candidate_transition_fields.filter(q=>!(q.status_file===P.s&&q.field_path==='s6_candidate_implemented'));a.deepEqual(cc,bc);a.equal(r.registry_revision,'1.1');a.equal(r.authority_set_revision,'1.4');a.equal(r.authority_set_change_id,'MCFT-CAP-08.S6-PRE-CANDIDATE-REGISTRATION');const c8=r.capabilities.find(q=>q.capability_line==='MCFT-CAP-08'),rules=c8.candidate_transition_fields.filter(q=>q.status_file===P.s&&q.field_path==='s6_candidate_implemented');a.equal(c8.authoritative_candidate_status_paths.includes(P.s),true);a.equal(rules.length,1);a.deepEqual(rules[0].allowed_candidate_values,[true]);a.equal(rules[0].focused_workflow,'mcft-cap-08-s6-final-closure');a.equal(rules[0].standard_workflow,'ci');a.equal(rules[0].predecessor_effective_evidence_required,true);a.equal(rules[0].independent_review_required,true);a.equal(r.capabilities.some(q=>q.capability_line==='MCFT-CAP-09'),false);a.equal(k(r).includes('MCFT-CAP-09'),false);a.equal(z.map(q=>f.readFileSync(p.join(R,q),'utf8')).join('\n').includes(['MCFT','CANDIDATE','DECLARATION','V2'].join('_')),false);
 const q={schema_version:'geox_mcft_cap08_s6_pre_candidate_governance_result_v1',status:'PASS',base_sha:b,subject_sha:g('rev-parse','HEAD'),changed_file_count:z.length,registry_revision:r.registry_revision,authority_set_revision:r.authority_set_revision,contract_semantic_digest:m.semantic_digest,s6_candidate_implemented:false,independent_review_required:true,independent_review_waived:false,runtime_source_delta:0,candidate_declaration_present:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};out(q);console.log(JSON.stringify(q))}catch(e){out({schema_version:'geox_mcft_cap08_s6_pre_candidate_governance_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});throw e}
