#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');const cp=require('node:child_process');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'../..');const BASE='8dca45a90f3f614e73fbae581545add63e7a51b1';const p=(n)=>`docs/digital_twin/mcft/cap_08/${n}`;
const F={taskbook:p('GEOX-MCFT-CAP-08-TASK.md'),status:p('GEOX-MCFT-CAP-08-S4-DELIVERY-STATUS-V1.json'),implementation:p('GEOX-MCFT-CAP-08-S4-IMPLEMENTATION-V1.json'),boundary:p('GEOX-MCFT-CAP-08-S4-CANDIDATE-CHANGED-FILE-BOUNDARY-V1.json'),contract:p('GEOX-MCFT-CAP-08-S4-CONTRACT-V1.json'),review:p('GEOX-MCFT-CAP-08-S4-REVIEW-POLICY-V1.json'),waiver:p('GEOX-MCFT-CAP-08-INTERIM-OWNER-REVIEW-WAIVER-V1.json'),s5Status:p('GEOX-MCFT-CAP-08-S5-DELIVERY-STATUS-V1.json'),s5Contract:p('GEOX-MCFT-CAP-08-S5-CONTRACT-V1.json'),registry:'docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json',focused:'.github/workflows/mcft-cap-08-s4-late-evidence-append-forward.yml',exact:'.github/workflows/mcft-cap-08-s4-exact-sha-attestation.yml'};
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S4_BOUNDARY_RESULT.json');const git=(...a)=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();const json=(f)=>JSON.parse(fs.readFileSync(path.join(ROOT,f),'utf8'));const text=(f)=>fs.readFileSync(path.join(ROOT,f),'utf8');const write=(v)=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,`${JSON.stringify(v,null,2)}\n`)};
function commit(v,c){const s=String(v||'').trim();assert.match(s,/^[0-9a-f]{40}$/,c);return git('rev-parse',`${s}^{commit}`)}
try{
 const base=commit(process.env.MCFT_BASE_SHA,'S4_FORMAL_BASE_SHA_INVALID');assert.equal(base,BASE,'S4_FORMAL_BASE_MISMATCH');assert.equal(git('merge-base',base,'HEAD'),base,'S4_FORMAL_BASE_NOT_ANCESTOR');assert.equal(git('diff','--check',`${base}...HEAD`),'','S4_FORMAL_DIFF_CHECK_FAILED');
 const status=json(F.status),implementation=json(F.implementation),boundary=json(F.boundary),contract=json(F.contract),review=json(F.review),waiver=json(F.waiver),s5Status=json(F.s5Status),s5Contract=json(F.s5Contract),registry=json(F.registry);const taskbookBlob=git('rev-parse',`HEAD:${F.taskbook}`);const raw=git('diff','--name-only',`${base}...HEAD`);const actual=raw?raw.split(/\r?\n/).filter(Boolean).sort():[];
 assert.equal(taskbookBlob,git('rev-parse',`${base}:${F.taskbook}`),'S4_TASKBOOK_DRIFT');assert.equal(contract.semantic_digest,'sha256:03d1b613b135dbf04b02fd9d314ac517458642b0652522d5fa03973f1a538371');
 assert.equal(status.record_status,'FORMAL_S4_CANDIDATE_IMPLEMENTED_NOT_EFFECTIVE');assert.equal(status.s4_candidate_implemented,true);assert.equal(status.implementation_authorized,true);assert.equal(status.bounded_canonical_transaction_authorized,true);assert.equal(status.runtime_source_authorized,false);assert.equal(status.formal_correction_count,1);assert.equal(status.corrected_canonical_object_count,5);assert.equal(status.first_write_delta_expected,7);assert.equal(status.completed_rerun_write_delta_expected,0);assert.equal(status.latest_pointer_delta_expected,0);assert.equal(status.fault_stage_count_expected,5);assert.equal(status.corruption_case_count_expected,5);assert.equal(status.fvo16_ordinary_state_assimilation_count_expected,0);assert.deepEqual(status.residual_obligations_pending,['R-01','R-16']);
 for(const k of ['independent_review_required','independent_review_satisfied','independent_review_performed','technical_gate_relaxation','retroactive_exact_head_approval_claim_allowed'])assert.equal(status[k],false,`S4_STATUS_EXPECTED_FALSE:${k}`);assert.equal(status.independent_review_waived,true);assert.equal(status.final_s6_independent_review_required,true);assert.equal(status.s4_effective,false);assert.equal(status.s5_authorized,false);assert.equal(status.production_runtime_source_authorized,false);
 assert.equal(implementation.schema_version,'geox_mcft_cap08_s4_implementation_v1');assert.equal(implementation.trusted_base_sha,base);assert.equal(implementation.taskbook_blob_sha,taskbookBlob);assert.equal(implementation.machine_contract_semantic_digest,contract.semantic_digest);assert.equal(implementation.development_subject.head_sha,'2785a22d8219d6c336ab9a7f8d70c6363a7b2cf6');assert.equal(implementation.development_subject.workflow_run_id,30148102969);assert.equal(implementation.development_subject.artifact_id,8616704277);assert.equal(implementation.s3_predecessor_authority.merge_subject_sha,'bcffb63003667ebc5f60ef4aa83c8243f99c5917');assert.equal(implementation.s3_predecessor_authority.semantic_artifact_digest,'sha256:bbfcd8553550dc5c33f36f6f2646a3fe56803318f8f9b9d8c15f03ec751af691');assert.equal(implementation.s3_predecessor_authority.readback_verified,true);assert.equal(implementation.s3_predecessor_authority.locked_version_delete_denied,true);assert.equal(implementation.source_manifest.file_count,7);assert.equal(implementation.acceptance_manifest.file_count,3);assert.equal(implementation.canonical_transaction.first_write_delta,7);assert.equal(implementation.canonical_transaction.completed_rerun_write_delta,0);assert.equal(implementation.development_proof.vector_count,12);assert.equal(implementation.development_proof.corruption_case_count,5);assert.equal(implementation.review_policy.mode,'OWNER_WAIVED_DEFERRED_TO_S6');assert.equal(implementation.review_policy.final_s6_independent_review_required,true);
 assert.equal(boundary.changed_file_count,18);assert.equal(boundary.changed_file_count,boundary.changed_files.length);assert.deepEqual(actual,[...boundary.changed_files].sort(),'S4_FORMAL_CHANGED_FILE_BOUNDARY_MISMATCH');assert.deepEqual({workflows:boundary.workflow_file_count,runtime:boundary.runtime_source_file_count,ssot:boundary.candidate_ssot_file_count,governance:boundary.governance_acceptance_file_count,acceptance:boundary.runtime_acceptance_file_count},{workflows:2,runtime:7,ssot:3,governance:3,acceptance:3});assert.equal(boundary.development_only_file_count,0);for(const f of boundary.development_only_files)assert.equal(actual.includes(f),false,`S4_DEVELOPMENT_ONLY_FORBIDDEN:${f}`);
 for(const [file,blob] of Object.entries(implementation.source_manifest.blob_shas))assert.equal(git('rev-parse',`HEAD:${file}`),blob,`S4_SOURCE_BLOB_MISMATCH:${file}`);for(const [file,blob] of Object.entries(implementation.acceptance_manifest.blob_shas))assert.equal(git('rev-parse',`HEAD:${file}`),blob,`S4_ACCEPTANCE_BLOB_MISMATCH:${file}`);
 assert.equal(s5Status.record_status,'PRE_REGISTERED_SUCCESSOR_STATUS_SEED');assert.equal(s5Status.s5_candidate_implemented,false);assert.equal(s5Status.implementation_authorized,false);assert.equal(s5Contract.record_status,'FROZEN_PRE_CANDIDATE_MACHINE_CONTRACT');assert.equal(git('rev-parse',`HEAD:${F.s5Status}`),'fb536951061934f16f1fded2d920cca4649c8314');assert.equal(git('rev-parse',`HEAD:${F.s5Contract}`),'ff682f21692859c8121c89611cec561ff491cfb8');for(const f of [F.s5Status,F.s5Contract,F.registry,F.contract,F.review,F.waiver])assert.equal(git('rev-parse',`HEAD:${f}`),git('rev-parse',`${base}:${f}`),`S4_BASE_GOVERNANCE_DRIFT:${f}`);
 const cap08=registry.capabilities.find(e=>e.capability_line==='MCFT-CAP-08');assert.ok(cap08,'S4_CAP08_REGISTRY_MISSING');const rules=cap08.candidate_transition_fields.filter(e=>e.status_file===F.s5Status&&e.field_path==='s5_candidate_implemented');assert.equal(rules.length,1,'S4_S5_REGISTRY_RULE_CARDINALITY');assert.equal(rules[0].focused_workflow,'mcft-cap-08-s5-residual-calibration-shadow');
 assert.equal(review.independent_review_required,false);assert.equal(review.independent_review_satisfied,false);assert.equal(review.independent_review_performed,false);assert.equal(review.independent_review_waived,true);assert.equal(review.technical_gate_relaxation,false);assert.equal(review.final_closure_review.independent_review_required,true);assert.equal(waiver.policy_id,'MCFT-CAP-08-S3-S5-INTERIM-OWNER-REVIEW-WAIVER-V1');
 const forbidden=actual.filter(f=>f.startsWith('apps/server/db/migrations/')||f.startsWith('apps/server/src/routes/')||f.startsWith('apps/web/')||f.startsWith('docker/postgres/init/')||f.includes('scheduler')||f.includes('model_activation'));assert.deepEqual(forbidden,[],'S4_FORMAL_FORBIDDEN_FILE_BOUNDARY');
 const focused=text(F.focused),exact=text(F.exact);for(const token of ['ACCEPTANCE_MCFT_CAP_08_S4_BOUNDARY.cjs','ACCEPTANCE_MCFT_CAP_08_LATE_CORRECTION_MATH.ts','ACCEPTANCE_MCFT_CAP_08_S4_APPEND_FORWARD_DB.ts','mcft_cap08_s4_artifact_finalize.cjs'])assert.ok(focused.includes(token),`S4_FOCUSED_MISSING:${token}`);for(const token of ['ACCEPTANCE_MCFT_CAP_08_S4_EXACT_SHA_ATTESTATION.cjs','ACCEPTANCE_MCFT_CAP_08_S4_BOUNDARY.cjs','ACCEPTANCE_MCFT_CAP_08_S4_APPEND_FORWARD_DB.ts','mcft_cap08_s4_artifact_finalize.cjs','mcft_attestation_retention_store_v1.cjs'])assert.ok(exact.includes(token),`S4_EXACT_MISSING:${token}`);
 const result={schema_version:'geox_mcft_cap08_s4_boundary_result_v1',status:'PASS',classification:'FORMAL_S4_CANDIDATE_MODE',base_sha:base,candidate_sha:git('rev-parse','HEAD'),candidate_tree_sha:git('rev-parse','HEAD^{tree}'),taskbook_blob_sha:taskbookBlob,machine_contract_digest:contract.semantic_digest,changed_file_count:actual.length,changed_files:actual,source_manifest_file_count:7,acceptance_manifest_file_count:3,review_mode:'OWNER_WAIVED_DEFERRED_TO_S6',independent_review_required:false,independent_review_satisfied:false,independent_review_performed:false,independent_review_waived:true,technical_gate_relaxation:false,final_s6_independent_review_required:true,s4_candidate_implemented:true,s4_effective:false,s5_authorized:false,production_runtime_source_authorized:false};write(result);console.log(JSON.stringify(result));
}catch(error){write({schema_version:'geox_mcft_cap08_s4_boundary_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1;}
