#!/usr/bin/env node
'use strict';
const cp=require('node:child_process');const fs=require('node:fs');const path=require('node:path');
const ROOT=path.resolve(__dirname,'../..');
const BASE='9a7e61bc306161c256a43469ab37185c524d1cd8';
const S5_ROUTING='56aacb93e9f97ed0fad43e6a001df28593341565';
const S4_SUBJECT='6a4138e77fe6b838bc0f552a0bc5e2ceb84c026f',S4_RUN=31108834682,S4_ARTIFACT=8970768718,S4_DIGEST='sha256:64e14355edad6e2711cdde26cc3ac2bd6c7795c7e64439b194679350ce7cc80c';
const S2_SUBJECT='a4db631f5bab234d9a6f7c25607f4fd027d224a1',S2_RUN=31151549954,S2_ARTIFACT=8983485729,S2_DIGEST='sha256:e99cbe0961e47a2b59261a8e16512bef2a10b8168bf5609907b95afcff387543';
const FILES=['.github/workflows/mcft-cap-09-s5-shadow-online-canonical-integration.yml','apps/server/src/runtime/twin_runtime/postgres_cap04_shadow_online_canonical_tick_adapter_v1.ts','apps/server/src/runtime/twin_runtime/postgres_frozen_shadow_online_evidence_source_v1.ts','apps/server/src/runtime/twin_runtime/postgres_read_only_execution_evidence_adapter_v1.ts','apps/server/src/runtime/twin_runtime/shadow_online_canonical_integration_service_v1.ts','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-DELIVERY-STATUS-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-HARD-ACCEPTANCE-EVIDENCE-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-PREDECESSOR-ATTESTATION-CONSUMPTION-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-SHADOW-ONLINE-CANONICAL-INTEGRATION-CANDIDATE-BOUNDARY-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-SHADOW-ONLINE-CANONICAL-INTEGRATION-CANDIDATE-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-SHADOW-ONLINE-CANONICAL-INTEGRATION-CONFIG-V1.json','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S5_SHADOW_ONLINE_CANONICAL_INTEGRATION.cjs','scripts/runtime_acceptance/ACCEPTANCE_MCFT_CAP_09_S5_SHADOW_ONLINE_CANONICAL_INTEGRATION_DB.ts'];
const FROZEN=['docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-TASK.md','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-STAGE-1B-SCOPE-CONTRACT-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-REGISTRY-REGISTRATION-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-REGISTRY-REGISTRATION-BOUNDARY-V1.json','.github/workflows/mcft-cap-09-s2-registry-registration.yml','.github/workflows/mcft-cap-09-s2-exact-sha-attestation.yml','apps/server/src/runtime/twin_runtime/postgres_evidence_ingress_adapter_v1.ts','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_EXACT_SHA_ATTESTATION_V1.cjs','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_REGISTRY_CROSS_LIFECYCLE_REPAIR.cjs','scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_classifier_v1.cjs','scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_router_v1.cjs'];
const FALSE=['implementation_authorized','runtime_source_authorized','live_ingestion_authorized','background_scheduler_authorized','canonical_write_authorized','public_http_writer_authorized','model_activation_authorized','controlled_action_authorized'];
const git=(...a)=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim(),must=(v,c)=>{if(!v)throw new Error(c)},read=p=>fs.readFileSync(path.join(ROOT,p),'utf8'),json=p=>JSON.parse(read(p)),same=(a,b)=>JSON.stringify([...a].sort())===JSON.stringify([...b].sort());
function has(src,tokens,p){for(const t of tokens)must(src.includes(t),`${p}:${t}`)}
function out(v){fs.mkdirSync(path.join(ROOT,'acceptance-output'),{recursive:true});fs.writeFileSync(path.join(ROOT,'acceptance-output/MCFT_CAP_09_S5_GOVERNANCE_ACCEPTANCE_RESULT.json'),JSON.stringify(v,null,2)+'\n')}
function verifyAuthority(dir,attName,locName,subject,digest,prefix){must(dir,`${prefix}_DIR_REQUIRED`);const att=JSON.parse(fs.readFileSync(path.join(ROOT,dir,attName),'utf8')),loc=JSON.parse(fs.readFileSync(path.join(ROOT,dir,locName),'utf8'));must(att.status==='PASS'&&att.subject_sha===subject&&att.semantic_artifact_digest===digest,`${prefix}_ATTESTATION_REQUIRED`);must(loc.retention_level==='R2'&&loc.semantic_artifact_digest===digest&&loc.readback_verified===true&&loc.locked_version_delete_denied===true,`${prefix}_R2_REQUIRED`);return att}
try{
  const base=process.env.MCFT_BASE_SHA;must(base===BASE,'EXACT_PROTECTED_MAIN_BASE_REQUIRED');must(git('rev-list','--count',`${base}..HEAD`)==='1','ONE_COMMIT_REQUIRED');
  const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean);must(same(changed,FILES),'EXACT_THIRTEEN_FILE_S5_BOUNDARY_REQUIRED');must(!changed.some(f=>f.includes('/migrations/')||f.includes('/routes/')||/server\.(ts|js)$/.test(f)),'MIGRATION_ROUTE_OR_SERVER_WIRING_FORBIDDEN');
  for(const file of FROZEN)must(git('rev-parse',`${base}:${file}`)===git('rev-parse',`HEAD:${file}`),`FROZEN_CONTROL_PLANE_DRIFT:${file}`);
  const status=json('docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-DELIVERY-STATUS-V1.json');must(status.status==='S5_CANDIDATE_IMPLEMENTED_NOT_EFFECTIVE'&&status.s5_registry_registration_implemented===true&&status.s5_candidate_implemented===true&&status.candidate_declaration_present===true&&status.externally_effective===false,'S5_STATUS_REQUIRED');must(status.candidate_base_main_sha===BASE,'S5_STATUS_BASE_REQUIRED');must(status.s4_effective_subject_sha===S4_SUBJECT&&status.corrected_s2_effective_subject_sha===S2_SUBJECT,'S5_AUTHORITY_SUBJECT_BINDINGS_REQUIRED');must(status.corrected_s2_exact_sha_r2_run_id===S2_RUN&&status.corrected_s2_exact_sha_artifact_id===S2_ARTIFACT&&status.corrected_s2_semantic_artifact_digest===S2_DIGEST,'S2_EFFECTIVE_BINDING_REQUIRED');must(status.s5_registry_registration_merge_sha==='ecb23638cd35824db93b81c4c8bca27e7736696d'&&status.s5_candidate_routing_merge_sha===S5_ROUTING,'S5_REGISTRY_ROUTING_BINDING_REQUIRED');for(const field of FALSE)must(status[field]===false,`S5_AUTHORITY_MUST_REMAIN_FALSE:${field}`);
  const boundary=json('docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-SHADOW-ONLINE-CANONICAL-INTEGRATION-CANDIDATE-BOUNDARY-V1.json');must(boundary.base_main_sha===BASE&&boundary.file_count===13&&boundary.runtime_source_delta===4&&same(boundary.files,FILES),'S5_BOUNDARY_REQUIRED');for(const field of ['migration_delta','route_delta','server_startup_wiring_delta','background_scheduler_delta','public_http_writer_delta','g_write_delta','action_creation_delta','authority_expansion_delta'])must(boundary[field]===0,`S5_BOUNDARY_ZERO_REQUIRED:${field}`);must(boundary.corrected_s2_authority_consumption_delta===1,'S2_CONSUMPTION_DELTA_REQUIRED');
  const predecessor=json('docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-PREDECESSOR-ATTESTATION-CONSUMPTION-V1.json');must(predecessor.predecessor_effective_subject_sha===S4_SUBJECT&&predecessor.predecessor_exact_sha_r2_run_id===S4_RUN&&predecessor.predecessor_exact_sha_artifact_id===S4_ARTIFACT&&predecessor.predecessor_semantic_artifact_digest===S4_DIGEST,'S4_PREDECESSOR_BINDING_REQUIRED');must(predecessor.candidate_base_main_sha===BASE,'S5_PREDECESSOR_BASE_REQUIRED');const support=predecessor.supporting_corrected_s2_authority;must(support?.subject_sha===S2_SUBJECT&&support.exact_sha_r2_run_id===S2_RUN&&support.artifact_id===S2_ARTIFACT&&support.semantic_artifact_digest===S2_DIGEST&&support.canonical_epistemic_compatibility_effective===true,'CORRECTED_S2_SUPPORT_REQUIRED');
  const s4=verifyAuthority(process.env.MCFT_CAP09_S4_EFFECTIVE_ARTIFACT_DIR,'MCFT_CAP_09_S4_EXACT_SHA_ATTESTATION.json','MCFT_CAP_09_S4_ATTESTATION_RETENTION_LOCATOR.json',S4_SUBJECT,S4_DIGEST,'S4');
  const s2=verifyAuthority(process.env.MCFT_CAP09_S2_CORRECTED_EFFECTIVE_ARTIFACT_DIR,'MCFT_CAP_09_S2_EXACT_SHA_ATTESTATION.json','MCFT_CAP_09_S2_ATTESTATION_RETENTION_LOCATOR.json',S2_SUBJECT,S2_DIGEST,'S2');
  must(s2.effective_authority?.s2_canonical_epistemic_compatibility_effective===true&&s2.effective_authority?.effective_frontier==='S5_REVALIDATION'&&s2.effective_authority?.s5_candidate_revalidation_authorized===true,'S2_S5_REVALIDATION_AUTHORITY_REQUIRED');must(s4.effective_authority?.s4_restart_backfill_stale_detection_effective!==false,'S4_EFFECTIVE_AUTHORITY_REQUIRED');
  const adapter=read('apps/server/src/runtime/twin_runtime/postgres_cap04_shadow_online_canonical_tick_adapter_v1.ts');has(adapter,['Cap04ForecastScenarioSingleTickServiceV1','PostgresFrozenShadowOnlineEvidenceSourceV1','PostgresReadOnlyExecutionEvidenceAdapterV1','S5_RESIDUAL_PORT_OVERRIDE_PAIR_REQUIRED','CAP05_FORECAST_RESIDUAL_MATCH_NOT_FOUND','S5_C_RESIDUAL_TRUSTWORTHY_H_REQUIRED','scheduler_fencing_token','g_write_count: 0'],'S5_ADAPTER_TOKEN');
  const h=read('apps/server/src/runtime/twin_runtime/postgres_read_only_execution_evidence_adapter_v1.ts');has(h,['implements ExecutionFeedbackPortV1','PostgresActionFeedbackTickSourceV1','selectCap05ActionFeedbackForTickV1','validateCap05ActionFeedbackV1','trustworthy:'],'S5_H_TOKEN');for(const token of ['INSERT INTO','UPDATE ','DELETE FROM','commitCanonicalObject','buildCap05ActionFeedbackV1'])must(!h.includes(token),`S5_H_WRITE_FORBIDDEN:${token}`);
  has(read('apps/server/src/runtime/twin_runtime/postgres_frozen_shadow_online_evidence_source_v1.ts'),['FrozenShadowOnlineEvidenceV1','source_record_id','source_record_hash','S5_FROZEN_EVIDENCE'],'S5_FROZEN_SOURCE');has(read('apps/server/src/runtime/twin_runtime/shadow_online_canonical_integration_service_v1.ts'),['recoverOrClaimOldestDueSlot','executeOneTick','recordTerminalResult','NO_CANONICAL_TICK'],'S5_INTEGRATION');has(read('.github/workflows/mcft-cap-09-s5-shadow-online-canonical-integration.yml'),['8970768718','8983485729','S5_CAP05_NO_MATCH_TARGET_OBSERVATION_REQUIRED','S5_CAP05_NO_MATCH_ZERO_HISTORICAL_FORECAST_REQUIRED','MCFT_CAP_09_S5_FOCUSED_ACCEPTANCE_RESULT.json'],'S5_WORKFLOW');
  const db=read('scripts/runtime_acceptance/ACCEPTANCE_MCFT_CAP_09_S5_SHADOW_ONLINE_CANONICAL_INTEGRATION_DB.ts');has(db,['runCap04DatabaseScenarioV1("completed")','runCap04DatabaseScenarioV1("blocked")','runCap05NoResidualIntegrationV1()','CAP05_NO_MATCH_CURRENT_OBSERVATION_TARGET_TIME_REQUIRED','CAP05_NO_MATCH_MUST_START_WITH_ZERO_POSTGRES_FORECAST_PROJECTIONS','NO_ELIGIBLE_HISTORICAL_FORECAST','runPositiveResidualCompositionV1()','S5_RESIDUAL_PORT_OVERRIDE_PAIR_REQUIRED'],'S5_DB');
  const hard=json('docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-HARD-ACCEPTANCE-EVIDENCE-V1.json');must(hard.required_proofs?.cap05_no_match_exact_target_observation_proven===true&&hard.required_proofs?.cap05_no_match_zero_historical_forecast_projection_before_tick===true&&hard.required_proofs?.production_runtime_fixture_normalization===false,'S5_HARD_NO_MATCH_PROOF_REQUIRED');
  const candidate=json('docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-SHADOW-ONLINE-CANONICAL-INTEGRATION-CANDIDATE-V1.json');must(candidate.candidate_base_main_sha===BASE&&candidate.external_effectiveness===false&&JSON.stringify(candidate.implementation.canonical_families)===JSON.stringify(['A','B','C','F'])&&candidate.supporting_corrected_s2_authority?.semantic_artifact_digest===S2_DIGEST,'S5_CANDIDATE_BINDING_REQUIRED');must(candidate.forbidden.g_decision_creation===true&&candidate.forbidden.action_creation===true,'S5_FORBIDDEN_G_ACTION_REQUIRED');
  const result={schema_version:'geox_mcft_cap09_s5_governance_acceptance_result_v3',status:'PASS',base_sha:base,head_sha:git('rev-parse','HEAD'),changed_files:[...FILES].sort(),predecessor_subject_sha:S4_SUBJECT,predecessor_exact_sha_r2_run_id:S4_RUN,predecessor_exact_sha_artifact_id:S4_ARTIFACT,predecessor_semantic_artifact_digest:S4_DIGEST,corrected_s2_subject_sha:S2_SUBJECT,corrected_s2_exact_sha_r2_run_id:S2_RUN,corrected_s2_exact_sha_artifact_id:S2_ARTIFACT,corrected_s2_semantic_artifact_digest:S2_DIGEST,corrected_s2_r2_consumed:true,cap05_no_match_exact_target_observation_guard:true,cap05_no_match_zero_historical_forecast_projection_guard:true,exact_thirteen_file_boundary:true,runtime_source_delta:4,migration_delta:0,g_write_count:0,action_creation_count:0,execution_feedback_port_read_only:true,external_effectiveness:false,first_legal_next_action:'RUN_FOCUSED_AND_STANDARD_CANDIDATE_ACCEPTANCE'};out(result);console.log(JSON.stringify(result,null,2));
}catch(error){const failure={status:'FAIL',error:String(error?.message??error)};out(failure);console.error(error);process.exitCode=1}
