#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),BASE='a1b91054a6a9ed1a04fc8e901767580ba7165f56';
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_RUN_A_MATERIALIZER_AUTHORITY_BINDING_CORRECTION_RESULT.json');
const F=[
'.github/workflows/mcft-cap-08-s6-run-a-materializer-authority-binding-correction.yml',
'.github/workflows/mcft-cap-08-s6-single-run-database-execution.yml',
'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-BOOTSTRAP-CORRECTED-FORMAL-RUN-A-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',
'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-RUN-A-MATERIALIZER-AUTHORITY-BINDING-CORRECTION-BOUNDARY-V1.json',
'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-RUN-A-MATERIALIZER-AUTHORITY-BINDING-FAILURE-SETTLEMENT-V1.json',
'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_RUN_A_MATERIALIZER_AUTHORITY_BINDING_CORRECTION_V1.cjs',
'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/direct_materializer_v1.cjs',
'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/fresh_database_v1.cjs',
'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/index_v1.cjs',
'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs'];
const P={wf:F[0],dbwf:F[1],auth:F[2],boundary:F[3],settlement:F[4],validator:F[5],direct:F[6],fresh:F[7],bundle:F[8],identity:F[9],adapter:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/materializer_adapter_v1.cjs',harness:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/harness_v1.cjs',entry:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/workflow_entrypoint_v1.ts',loader:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/contract_loader_v1.cjs',contract:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/port_contract_v1.cjs',gate:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs'};
const X={run:30749559715,subject:'0187c6ad375c4752b67b58259878dfa552384571',op:'MCFT-CAP-08-S6-FORMAL-RUN-A-20260802-REPLACEMENT-004',actual:'geox_mcft_cap08_s6_run_a_30749559715',expected:'geox_mcft_cap08_s6_run_a_replacement_004_30749559715',blobs:{wf:'8c303f8554e54955a8cf862146ae6a8847442dd1',dbwf:'2371b3797999f61f55c58551b85c59279eb2f0a2',auth:'2c19e7be380bf8c677f1b7590dc8314145a18c97',settlement:'023644ac441dbb2e43b1042f5453619c065fbcfc',direct:'8369efaf8e8be1279f33196d1dcf743612b72852',fresh:'275a9140243c4f29d343fb61fadf9e5998c08928',bundle:'065b2da057a663ef0700003312e9f04a15d4a875',identity:'4862f8e6b34aecba488db91e543d51ac83ffb719'},protected:{adapter:'ef4831dd32069be4976785e16d90bc7a262bf00d',harness:'1833c793a10bba383f54200a35cb3f8912b60b94',entry:'4b68df5cb74b445301e4554ef3fe160ed9c14500',loader:'27903ddc8566505053e3e6ccf4e8d08dfc576869',contract:'1f7b4a8aaac0a2db2e9ec6826672dd1a3a341681'}};
function git(...a){return execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim()}
function txt(p){return fs.readFileSync(path.join(ROOT,p),'utf8')}
function json(p){return JSON.parse(txt(p))}
function canon(v){if(Array.isArray(v))return`[${v.map(canon).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function digest(v){const c=structuredClone(v);delete c.semantic_digest;return`sha256:${crypto.createHash('sha256').update(canon(c)).digest('hex')}`}
function write(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,`${JSON.stringify(v,null,2)}\n`)}
async function main(){
 const base=String(process.env.MCFT_BASE_SHA||BASE).trim();assert.equal(base,BASE,'EXACT_BASE_MAIN_SHA');assert.equal(git('merge-base',base,'HEAD'),base);assert.equal(git('diff','--check',`${base}...HEAD`),'');
 const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(changed,[...F].sort(),'EXACT_CHANGED_FILE_BOUNDARY');
 const a=json(P.auth),s=json(P.settlement),b=json(P.boundary);assert.equal(a.semantic_digest,digest(a));assert.equal(s.semantic_digest,digest(s));assert.equal(b.semantic_digest,digest(b));
 assert.equal(a.record_status,'SINGLE_FINAL_FORMAL_RUN_AUTHORITY_CONSUMED_MATERIALIZER_AUTHORITY_BINDING_FAILURE');assert.equal(a.authority_consumed,true);assert.equal(a.single_use_contract.dispatch_count_consumed,1);assert.equal(a.single_use_contract.rerun_authorized,false);assert.equal(a.workflow_dispatch_execution_authorized,false);assert.equal(a.final_formal_run_execution_authorized,false);assert.equal(a.replacement_authority_issued,false);assert.equal(a.consumption_evidence.github_workflow_run_id,X.run);assert.equal(a.consumption_evidence.actual_database_name,X.actual);assert.equal(a.consumption_evidence.expected_database_name,X.expected);
 assert.equal(s.failed_dispatch.github_workflow_run_id,X.run);assert.equal(s.failed_dispatch.github_run_attempt,1);assert.equal(s.failed_dispatch.exact_subject_sha,X.subject);assert.equal(s.failed_dispatch.operational_run_instance_id,X.op);assert.equal(s.workflow_evidence.fresh_postgresql_bootstrap_status,'PASS');assert.equal(s.database_evidence.database_dropped,true);assert.equal(s.database_evidence.product_chain_entered,false);assert.equal(s.failure_classification.code,'FORMAL_MATERIALIZER_AUTHORITY_ARGUMENT_DROPPED');assert.equal(s.failure_classification.formal_result_emitted,false);assert.equal(s.authority_disposition.authority_consumed,true);assert.equal(s.authority_disposition.rerun_authorized,false);assert.equal(s.run_b_state.dispatch_authorized,false);
 assert.equal(b.base_main_sha,BASE);assert.equal(b.changed_file_count,10);assert.deepEqual([...b.changed_files].sort(),[...F].sort());assert.equal(b.failed_workflow_run_id,X.run);assert.equal(b.database_execution_performed_in_correction,false);assert.equal(b.workflow_dispatch_performed_in_correction,false);assert.equal(b.replacement_authority_present,false);assert.equal(b.run_b_dispatch_authorized,false);
 const {validateExecutionAuthorityV1}=require(path.join(ROOT,P.gate));assert.throws(()=>validateExecutionAuthorityV1(a,{exactSubjectSha:X.subject,runLabel:'RUN_A',operationalRunInstanceId:X.op}),/record_status|strictly equal/);
 for(const [k,v] of Object.entries(X.blobs))assert.equal(git('rev-parse',`HEAD:${P[k]}`),v,`CORRECTED_BLOB:${k}`);for(const [k,v] of Object.entries(X.protected))assert.equal(git('rev-parse',`HEAD:${P[k]}`),v,`PROTECTED_BLOB:${k}`);
 const d=txt(P.direct),f=txt(P.fresh),i=txt(P.bundle),w=txt(P.dbwf),id=txt(P.identity),ad=txt(P.adapter);
 assert.match(ad,/executeDirectFormalRun\(\{spec,plan\}\)/);assert.doesNotMatch(d,/executeDirectFormalRun\(spec,executionAuthority\)/);assert.match(d,/executeDirectFormalRun\(\{\s*spec,\s*plan\s*\}\)/);assert.match(d,/assertFormalMaterializerAuthorityV1\(authority,\s*spec\)/);assert.match(i,/validateFactoryAuthorityV1/);assert.match(i,/createDirectMaterializerV1\(\{ root, pool, adminPool, shared, authority \}\)/);assert.match(f,/FRESH_DISPOSABLE_DATABASE_IDENTITY_MISMATCH/);assert.match(w,/database_identity_v1\.cjs/);assert.doesNotMatch(w,/label="\$\(printf/);assert.match(id,/physical_name_template/);
 const synthetic=structuredClone(a);synthetic.record_status='SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED';synthetic.evidence_class='FINAL_FORMAL_EVIDENCE_ELIGIBLE_AFTER_TERMINAL_SUCCESS';synthetic.authority_consumed=false;synthetic.single_run_database_execution_authorized=true;synthetic.database_execution_workflow_authorized=true;synthetic.workflow_dispatch_execution_authorized=true;synthetic.final_formal_run_execution_authorized=true;
 const {materializePhysicalDatabaseNameV1}=require(path.join(ROOT,P.identity));assert.equal(materializePhysicalDatabaseNameV1(synthetic,String(X.run)),X.expected);assert.throws(()=>materializePhysicalDatabaseNameV1(synthetic,''),/GITHUB_RUN_ID_REQUIRED/);
 const {validateFactoryAuthorityV1}=require(path.join(ROOT,P.bundle));assert.equal(validateFactoryAuthorityV1({authority:synthetic,exactSubjectSha:X.subject,runLabel:'RUN_A',operationalRunInstanceId:X.op}),synthetic);assert.throws(()=>validateFactoryAuthorityV1({authority:a,exactSubjectSha:X.subject,runLabel:'RUN_A',operationalRunInstanceId:X.op}),/FORMAL_PORT_BUNDLE_AUTHORITY_REQUIRED|strictly equal/);
 const {createDirectMaterializerV1}=require(path.join(ROOT,P.direct));let calls=0;const spec={exact_subject_sha:X.subject,run_label:'RUN_A',operational_run_instance_id:X.op,formal_run_id:'formal_run_static_probe',lineage_id:null,revision_id:null},plan={strategy:'DIRECT_PRODUCT_SERVICE_ASSEMBLY',formal_run_id:spec.formal_run_id};const port=createDirectMaterializerV1({root:ROOT,pool:{},adminPool:{},shared:{},authority:synthetic,runProductChainV1:async()=>{calls++;return{status:'STATIC_PROBE'}},buildMaterializationOutputV1:async x=>x.context});assert.equal((await port.executeDirectFormalRun({spec,plan})).status,'STATIC_PROBE');assert.equal(calls,1);const rejected=createDirectMaterializerV1({root:ROOT,pool:{},adminPool:{},shared:{},authority:a,runProductChainV1:async()=>{calls++;return{}},buildMaterializationOutputV1:async()=>({})});await assert.rejects(()=>rejected.executeDirectFormalRun({spec,plan}),/DATABASE_EXECUTION_AUTHORITY_REQUIRED/);assert.equal(calls,1);
 assert.equal(changed.some(p=>p.startsWith('apps/server/')||p.startsWith('apps/web/')||/migration/i.test(p)),false);assert.equal(changed.some(p=>/AUTHORITY-CANDIDATE|AUTHORITY-EFFECTIVENESS/i.test(p)),false);
 const r={schema_version:'geox_mcft_cap08_s6_run_a_materializer_authority_binding_correction_result_v1',status:'PASS',base_main_sha:base,exact_head_sha:git('rev-parse','HEAD'),failed_workflow_run_id:X.run,authority_consumed:true,consumed_authority_gate_rejected:true,database_bootstrap_status:'PASS',product_chain_entered:false,formal_result_emitted:false,materializer_authority_binding_preflight:'PASS',database_identity_materialization_preflight:'PASS',exact_database_identity_rejection_preflight:'PASS',product_runtime_source_changed:false,database_migration_changed:false,database_execution_performed_in_correction:false,workflow_dispatch_performed_in_correction:false,replacement_authority_present:false,run_b_dispatch_authorized:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};write(r);console.log(JSON.stringify(r,null,2));
}
main().catch(e=>{write({schema_version:'geox_mcft_cap08_s6_run_a_materializer_authority_binding_correction_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});throw e});
