#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),f=require('node:fs'),p=require('node:path'),c=require('node:child_process');
const R=p.resolve(__dirname,'../..'),O=p.join(R,'acceptance-output/MCFT_CAP_08_S2_EXACT_SHA_ATTESTATION_RESULT.json'),MARK='MCFT_CANDIDATE_DECLARATION_V2',STATUS='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S2-DELIVERY-STATUS-V1.json';
const git=(...x)=>c.execFileSync('git',x,{cwd:R,encoding:'utf8'}).trim(),req=(x,l)=>{const v=String(x||'').trim();if(!/^[0-9a-f]{40}$/i.test(v))throw new Error(`${l}_INVALID:${v}`);return git('rev-parse',`${v}^{commit}`)},write=x=>{f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(x,null,2)+'\n')};
function marker(body){const m=String(body||'').match(/<!--\s*MCFT_CANDIDATE_DECLARATION_V2\s*\n([\s\S]*?)-->/);if(!m)throw new Error('DECLARATION_MISSING');const r={};for(const raw of m[1].split(/\r?\n/)){const line=raw.trim();if(!line)continue;const at=line.indexOf('=');if(at<1)throw new Error(`DECLARATION_LINE_INVALID:${line}`);r[line.slice(0,at).trim()]=line.slice(at+1).trim()}return r}
async function api(q){const r=await fetch(`https://api.github.com${q}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'geox-cap08-s2-attestation'}});if(!r.ok)throw new Error(`GITHUB_API:${r.status}:${q}:${(await r.text()).slice(0,300)}`);return r.json()}
(async()=>{try{const subject=req(process.env.MCFT_SUBJECT_SHA,'SUBJECT');a.equal(git('rev-parse','HEAD'),subject);const parents=git('rev-list','--parents','-n','1',subject).split(/\s+/);a.equal(parents.length,3,'TWO_PARENT_MERGE_REQUIRED');const bh=req(parents[1],'BASE_PARENT'),ch=req(parents[2],'CANDIDATE_PARENT'),ct=git('rev-parse',`${ch}^{tree}`),mt=git('rev-parse',`${subject}^{tree}`);a.equal(ct,mt,'CANDIDATE_MERGE_TREE_DELTA_NONZERO');const repo=String(process.env.GITHUB_REPOSITORY||'');a.match(repo,/^[^/]+\/[^/]+$/);const pulls=await api(`/repos/${repo}/commits/${subject}/puls`),merged=pulls.filter(x=>x.imerge_commit_sha===subject&&x.merged_at);a.equal(merged.length,1,'MERGED_PR_CARDINALITY');const pr=merged[0],d=marker(pr.body);a.equal(req(pr.head.sha,'PR_HEAD'),ch);a.equal(req(pr.base.sha,'PR_BASE'),bh);a.equal(d.capability_line,'MCFT-CAP-08');a.equal(d.slice_id,'MCFT-CAP-08.S2');a.equal(d.status_file,STATUS);a.equal(d.candidate_field,'s2_candidate_implemented');a.equal(d.candidate_value,'true');a.equal(d.focused_workflow,'mcft-cap-08-s2-forcing-state-forecast');a.equal(d.standard_workflow,'ci');a.equal(req(d.candidate_head,'DECLARATION_HEAD'),ch);a.equal(req(d.base_head,'DECLARATION_BASE'),bh);
 const paths=String(d.semantic_snapshot_files||'').split(',').filter(Boolean),blobs=String(d.semantic_snapshot_blobs||'').split(',').filter(Boolean);a.equal(paths.length,blobs.length);a.ok(paths.length>=4);for(let n=0;n<paths.length;n++)a.equal(git('rev-parse',`${ch}:${paths[n]}`),blobs[n],`SEMANTIC_SNAPSHOT_BLOB_MISMATCH:${paths[n]}`);
 const runs=await api(`/repos/${repo}/actions/runs?head_sha=${ch}&event=pull_request&per_page=100`),success=name=>runs.workflow_runs.filter(x=>x.name===name&&x.head_sha===ch&&x.conclusion==='success').sort((l,r)=>String(r.created_at).localeCompare(String(l.created_at)));a.ok(success('mcft-cap-08-s2-forcing-state-forecast').length>=1,'FOCUSED_SUCCESS_REQUIRED');a.ok(success('ci').length>=1,'STANDARD_SUCCESS_REQUIRED');const s=JSON.parse(f.readFileSync(p.join(R,STATUS),'utf8'));a.equal(s.s2_candidate_implemented,true);a.equal(s.independent_review_satisfied,false);a.equal(s.independent_review_waived,true);a.equal(s.effectiveness_condition,'PRESENT_ON_MAIN_AND_EXACT_SHA_ATTESTATION_PASS');a.equal(s.effective_status_when_attested,'S2_FORCING_EVIDENCE_STATE_FORECAST_IMPLEMENTED_EFFECTIVE');a.equal(s.effective_next_slice_when_attested,'S3');a.equal(s.production_runtime_source_authorized,false);a.equal(s.s3_authorized,false);
 const out={schema_version:'geox_mcft_cap08_s2_exact_sha_attestation_result_v1',status:'PASS',capability_line_id:'MCFT-CAP-08',slice_id:'MCFT-CAP-08.S2',subject_sha:subject,subject_commit:subject,base_head_sha:bh,candidate_head_sha:ch,candidate_tree_sha:ct,merge_commit_sha:subject,merge_tree_sha:mt,candidate_to_merge_tree_delta:0,attested_tree_sha:mt,pr_number:pr.number,focused_workflow_run_id:success('mcft-cap-08-s2-forcing-state-forecast')[0].id,standard_workflow_run_id:success('ci')[0].id,effective_delivery_frontier_projection:{effective_status:'S2_FORCING_EVIDENCE_STATE_FORECAST_IMPLEMENTED_EFFECTIVE',effective_next_slice:'S3'},effective_authority_projection:{formal_forcing_evidence_state_forecast_authorized:true,production_runtime_source_authorized:false,decision_action_feedback_authorized:false,late_append_forward_authorized:false,residual_calibration_shadow_authorized:false,model_activation_authorized:false,mcft_cap_09_authorized:false}};write(out);console.log(JSON.stringify(out));}catch(e){write({schema_version:'geox_mcft_cap08_s2_exact_sha_attestation_result_v1',status:'FAIL',error:e.message});console.error(e);process.exitCode=1}})();
