// scripts/governance_acceptance/ACCEPTANCE_ROOT_ZONE_SOIL_WATER_FORECAST_SCHEMA_MIGRATION_V1.cjs
const fs = require("node:fs"); const { Pool } = require("pg");
const name="ACCEPTANCE_ROOT_ZONE_SOIL_WATER_FORECAST_SCHEMA_MIGRATION_V1"; const MIGRATION_PATH="apps/server/db/migrations/2026_06_21_root_zone_soil_water_forecast_v1.sql"; const TABLE="root_zone_soil_water_forecast_index_v1"; const PROBE="h33_root_zone_soil_water_forecast_acceptance_schema_probe";
const cols="forecast_id tenant_id project_id group_id field_id zone_id source_state_id source_state_ref weather_forecast_ref baseline_mode horizon_days root_zone_depth_cm root_zone_available_water_capacity_mm initial_available_water_fraction initial_weighted_matric_potential_kpa daily_forecast_json min_available_water_fraction max_available_water_fraction first_stress_date stress_day_count limited_day_count forecast_status blocking_reasons_json calculation_inputs_json derivation_json confidence_json determinism_hash source_fact_id computed_at updated_at".split(" ");
const jsonb=["daily_forecast_json","blocking_reasons_json","calculation_inputs_json","derivation_json","confidence_json"]; const indexes=["idx_root_zone_soil_water_forecast_index_v1_scope_latest","idx_root_zone_soil_water_forecast_index_v1_field_latest","idx_root_zone_soil_water_forecast_index_v1_source_state"];
function fail(m,d){console.error(`[${name}] FAIL: ${m}`); if(d) console.error(d); process.exit(1)} function assert(c,m,d){if(!c) fail(m,d)}
async function exists(c,t){return !!(await c.query("SELECT to_regclass($1)::text AS name",[`public.${t}`])).rows[0]?.name}
async function schema(c){assert(await exists(c,TABLE),"table exists after migration inside transaction"); const r=await c.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name=$1",[TABLE]); const m=Object.fromEntries(r.rows.map(x=>[x.column_name,x.data_type])); for(const col of cols) assert(m[col],`required column exists: ${col}`); for(const col of jsonb) assert(m[col]==="jsonb",`JSONB column is JSONB: ${col}`); const ir=await c.query("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND tablename=$1",[TABLE]); const names=ir.rows.map(x=>x.indexname); for(const i of indexes) assert(names.includes(i),`required index exists: ${i}`)}
(async()=>{assert(fs.existsSync(MIGRATION_PATH),"migration file exists"); const sql=fs.readFileSync(MIGRATION_PATH,"utf8"); const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(url,"DATABASE_URL/POSTGRES_URL/PG_URL required"); const pool=new Pool({connectionString:url}); const client=await pool.connect(); try{await client.query("BEGIN"); await client.query(sql); await client.query(sql); await schema(client); await client.query(`INSERT INTO public.${TABLE} (forecast_id,tenant_id,project_id,group_id,field_id,zone_id,source_state_id,source_state_ref,baseline_mode,horizon_days,root_zone_depth_cm,root_zone_available_water_capacity_mm,stress_day_count,limited_day_count,forecast_status,determinism_hash,computed_at) VALUES ($1,'t','p','g','f','z','s','s','NO_NEW_ACTION',0,60,100,0,0,'ESTIMATED','h','2026-06-21T00:00:00Z')`,[PROBE]); assert((await client.query(`SELECT COUNT(*)::int AS count FROM public.${TABLE} WHERE forecast_id=$1`,[PROBE])).rows[0].count===1,"probe row can be inserted"); await client.query("ROLLBACK"); if(await exists(pool,TABLE)){assert((await pool.query(`SELECT COUNT(*)::int AS count FROM public.${TABLE} WHERE forecast_id=$1`,[PROBE])).rows[0].count===0,"rollback removes probe row")} console.log(`[${name}] PASS`)}catch(e){try{await client.query("ROLLBACK")}catch{} fail(e.message,e.stack)}finally{client.release(); await pool.end();}})();
