#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const cp=require('node:child_process');
const {compileOneRunArtifactsV1,compileSyntheticOneRunV1,executeDatabaseRunV1,compareRunsV1,finalizeLedgerV1}=require('../runtime_acceptance/mcft_cap08_s6_final_formal_run/orchestrator_v1.cjs');
const {rejectSliceAcceptanceSourceV1}=require('../runtime_acceptance/mcft_cap08_s6_final_formal_run/source_v1.cjs');
const ROOT=path.resolve(__dirname,'../..');
const B='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FINAL-FORMAL-RUN-ORCHESTRATOR-BOUNDARY-V1.json';
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_FINAL_FORMAL_RUN_ORCHESTRATOR_RESULT.json');
function read(p){return JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));}function git(...a){return cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();}function write(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n');}
try{const local=process.env.MCFT_LOCAL_REPLAY==='1',b=read(B),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim();if(!local){assert.equal(git('merge-base',base,'HEAD'),base);assert.equal(git('diff','--check',`${base}...HEAD`),'');assert.deepEqual(git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),[...b.changed_files].sort());}
 assert.equal(b.changed_file_count,16);assert.equal(b.product_runtime_source_file_count,0);assert.equal(b.database_migration_file_count,0);assert.equal(b.route_or_web_file_count,0);assert.equal(b.database_execution_workflow_count,0);assert.equal(b.cross_run_comparator_file_count,0);assert.equal(b.finalizer_file_count,0);
 const subject=local?'1'.repeat(40):git('rev-parse','HEAD');const a=compileSyntheticOneRunV1({runLabel:'RUN_A',operationalRunInstanceId:'synthetic-run-a-0001',exactSubjectSha:subject});const c=compileSyntheticOneRunV1({runLabel:'RUN_B',operationalRunInstanceId:'synthetic-run-b-0001',exactSubjectSha:subject});
 assert.equal(a.plan.formal_run_id,c.plan.formal_run_id);assert.notEqual(a.plan.operational_run_instance_id,c.plan.operational_run_instance_id);assert.notEqual(a.operational_event_manifest.database_instance_digest,c.operational_event_manifest.database_instance_digest);assert.equal(a.plan.phases.length,28);assert.deepEqual(a.plan.phases.map(x=>x.phase_id),['B00',...Array.from({length:24},(_,i)=>`T${String(i).padStart(2,'0')}`),'G00','G01','G02']);assert.ok(a.plan.phases.every(x=>['E','H','A','B','G','C','D','F'].every(p=>x.providers_enabled.includes(p))));
 assert.equal(a.recovery_plan.vectors.length,7);assert.equal(a.recovery_plan.silent_repair_forbidden,true);assert.equal(a.recovery_plan.vectors.find(v=>v.vector_id==='T11_PRECOMMIT_ROLLBACK').expected.failed_attempt_canonical_write_delta,0);assert.equal(a.recovery_plan.vectors.find(v=>v.vector_id==='T12_POSTCOMMIT_RESPONSE_LOSS').expected.original_commit_completed,true);assert.equal(a.cap07_readback_plan.surface_count,10);assert.equal(a.cap07_readback_plan.surfaces.find(x=>x.name==='model-governance').query_variants.length,2);assert.ok(a.cap07_readback_plan.surfaces.filter(x=>x.paginated).every(x=>x.pagination_policy==='FETCH_UNTIL_NEXT_CURSOR_NULL'));assert.equal(a.witness_bundle.witness_count,22);assert.equal(a.witness_bundle.object_set_count,22);assert.ok(a.witness_bundle.witnesses.every(w=>w.object_set_ref.startsWith('urn:sha256:')));assert.ok(new Set(a.witness_bundle.witnesses.map(w=>w.object_set_ref)).size>=15);assert.ok(a.witness_bundle.witnesses.every(w=>w.status==='CONTRACT_TEST_PASS'&&w.hard_acceptance_eligible===false));assert.equal(a.closure_member_manifest.members.some(m=>Object.hasOwn(m,'operational_run_instance_id')),false);assert.equal(a.closure_member_manifest.members.find(m=>m.object_ref==='FVO-01').phase_id,'T16');assert.equal(a.source.provenance.global_table_count_used,false);assert.equal(a.source.provenance.slice_acceptance_object_reuse_count,0);assert.equal(a.source.provenance.closure_member_manifest_ref,`urn:sha256:${a.closure_member_manifest.manifest_digest.slice(7)}`);assert.equal(a.operational_event_manifest.exact_subject_sha,subject);assert.equal(a.operational_event_manifest.tenant_id,a.plan.scope.tenant_id);assert.throws(()=>compileOneRunArtifactsV1({runLabel:'RUN_A',operationalRunInstanceId:'real-run-a-0001',exactSubjectSha:subject,input:{},synthetic:false}),/DATABASE_EXECUTION_AUTHORITY_REQUIRED/);
 assert.throws(executeDatabaseRunV1,/NOT_AUTHORIZED/);assert.throws(compareRunsV1,/NOT_AUTHORIZED/);assert.throws(finalizeLedgerV1,/NOT_AUTHORIZED/);assert.throws(()=>rejectSliceAcceptanceSourceV1({slice_acceptance_only:true}),/FORBIDDEN/);assert.throws(()=>rejectSliceAcceptanceSourceV1({final_formal_run_id:null}),/FORBIDDEN/);
 const files=b.changed_files.filter(f=>f.includes('final_formal_run'));const text=files.filter(f=>fs.existsSync(path.join(ROOT,f))).map(f=>fs.readFileSync(path.join(ROOT,f),'utf8')).join('\n');const haPattern=new RegExp(['H','A','-','\\d','{2}'].join(''),'g');assert.equal((text.match(haPattern)||[]).length,0,'HANDWRITTEN_HA_ID');
 const result={schema_version:'geox_mcft_cap08_s6_final_formal_run_orchestrator_result_v1',status:'PASS',subject_sha:local?'LOCAL_REPLAY':subject,base_sha:local?'LOCAL_REPLAY':base,changed_file_count:b.changed_file_count,compiled_run_plan_count:2,phase_count_per_run:28,same_formal_run_id:true,different_operational_run_instance_id:true,different_database_instance_digest:true,recovery_vector_count:7,cap07_surface_count:10,pagination_until_cursor_null:true,closure_manifest_member_count:a.closure_member_manifest.member_count,per_run_witness_count:22,proof_object_set_count:a.witness_bundle.object_set_count,unique_object_set_ref_count:new Set(a.witness_bundle.witnesses.map(w=>w.object_set_ref)).size,synthetic_witness_hard_acceptance_eligible_count:0,database_execution_authorized:false,run_a_executed:false,run_b_executed:false,cross_run_comparator_implemented:false,finalizer_present:false,dual_run_ci_authorized:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};write(result);console.log(JSON.stringify(result,null,2));}
catch(e){write({schema_version:'geox_mcft_cap08_s6_final_formal_run_orchestrator_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1;}
