// scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_04_S10A_FINALIZATION_CANDIDATE.cjs
// Purpose: validate the governance-only S10A candidate, S9 merged-effective evidence, pending claims, exact boundary, and downstream locks.
'use strict';
const cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path'); const ROOT=path.resolve(__dirname,'../..'); const BASE='a6a07840efe080198233b39ec9a31d26c2e3f4f9',S9='MCFT-CAP-04.CLOSURE-CANDIDATE-V1',S10='MCFT-CAP-04.FINALIZATION-MAIN-VERIFICATION-V1'; const MODE=process.argv.includes('--postmerge')?'postmerge':'final'; const files=["docs/digital_twin/GEOX-DT-02-MCFT-IMPLEMENTATION-MAP.md","docs/digital_twin/GEOX-MCFT-VERTICAL-CAPABILITY-LINE-MATRIX.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-AUTHORIZATION-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-DELIVERY-SLICE-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE-RECORD.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-FINALIZATION-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-FINALIZATION.md","scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_04_S10A_FINALIZATION_CANDIDATE.cjs"]; let pass=0,fail=0;
const check=(v,m)=>{if(v){pass++;console.log('PASS '+m)}else{fail++;console.error('FAIL '+m)}}; const git=a=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim(); const j=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8')); const exact=(a,b,m)=>check(JSON.stringify([...(a||[])].sort())===JSON.stringify([...(b||[])].sort()),m);
for(const f of files) check(fs.existsSync(path.join(ROOT,f)),'file exists '+f); const a=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-AUTHORIZATION-STATUS.json'); const d=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-DELIVERY-SLICE-STATUS.json'); const c=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE-STATUS.json'); const r=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE-RECORD.json'); const f=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-FINALIZATION-STATUS.json'); const s9=d.slices.find(x=>x.delivery_slice_id===S9),s10=d.slices.find(x=>x.delivery_slice_id===S10);
check(a.active_delivery_slice_id===S10,'auth active S10'); check(a.runtime_source_authorized===false,'Runtime source unauthorized'); exact(a.exact_changed_file_boundary,files,'auth boundary exact'); check(s9.status==='MERGED_EFFECTIVE','S9 merged effective'); check(s9.effectiveness_condition_satisfied===true,'S9 effectiveness true'); check(s9.merge_commit===BASE,'S9 merge exact'); check(s9.postmerge_workflow_run===29258021682,'S9 postmerge Gate exact');
check(s10.status==='S10A_CANDIDATE','S10A candidate'); check(s10.current_lifecycle_stage==='S10A_CANDIDATE','lifecycle S10A'); check(s10.closure_effective===false,'S10A closure ineffective'); check(s10.capability_complete===false,'S10A capability incomplete'); check(s10.pending_completion_claims.length===24,'24 pending claims'); exact(s10.effective_completion_claims,[],'zero effective claims');
check(c.status!=='COMPLETE'&&c.implementation_status!=='COMPLETE','closure status not complete'); check(c.closure_effective===false&&c.capability_status==='NOT_COMPLETE','closure remains ineffective'); check(r.status!=='COMPLETE'&&r.capability_complete===false,'record remains incomplete'); check(f.lifecycle_stage==='S10A_CANDIDATE','finalization stage S10A'); check(f.status!=='COMPLETE'&&f.implementation_status!=='COMPLETE','finalization not complete'); check(f.s10a_effectiveness_condition_satisfied===false,'S10A effectiveness false premerge'); check(f.s10b_authorized===false&&f.s10c_authorized===false,'S10B/S10C blocked'); check(f.successor_authorized===false&&d.successor_authorized===false,'CAP05 unauthorized');
const tracked=git(['diff','--name-only',BASE]).split(/\r?\n/).filter(Boolean),untracked=git(['ls-files','--others','--exclude-standard']).split(/\r?\n/).filter(Boolean),changed=[...new Set([...tracked,...untracked])].sort(); exact(changed,files,'exact changed files'); for(const x of changed){check(!x.startsWith('apps/server/src/'),'no Runtime source '+x);check(!x.startsWith('apps/server/db/migrations/'),'no migration '+x);check(!x.startsWith('apps/web/'),'no web '+x);check(!x.startsWith('.github/workflows/'),'no workflow '+x)}
if(MODE==='postmerge'){check(git(['branch','--show-current'])==='main','postmerge on main');check(git(['rev-parse','HEAD'])===git(['rev-parse','origin/main']),'postmerge main equals origin/main')} console.log('MCFT-CAP-04 S10A '+MODE+': '+pass+' PASS, '+fail+' FAIL'); if(fail)process.exit(1);
