#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),{execFileSync:E}=require('node:child_process');
const R=P.resolve(__dirname,'../..'),B='0ef5db98aee3b54257bbd404fa1e57daa34957f7',S='ce9d6b4df8c708c0d4a99bb24846e1bc44b3cf59';
const OP='MCFT-CAP-08-S6-FORMAL-RUN-A-20260804-REPLACEMENT-011',DB='MCFT-CAP-08-S6-FORMAL-DB-A-20260804-REPLACEMENT-011';
const W='.github/workflows/mcft-cap-08-s6-merged-main-qualified-run-a-authority-candidate.yml';
const D='docs/digital_twin/mcft/cap_08/',CA=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-FORMAL-RUN-A-AUTHORITY-CANDIDATE-V1.json',O=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-RUN-A-AUTHORITY-OBJECT-SET-V1.json',I=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-RUN-A-AUTHORITY-ISSUANCE-V1.json',BD=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-RUN-A-AUTHORITY-BOUNDARY-V1.json',Q=D+'GEOX-MCFT-CAP-08-S6-EXACT-PATH-DEVELOPMENT-REHEARSAL-OBJECT-SET-V1.json',OLD=D+'GEOX-MCFT-CAP-08-S6-FVO17-FORECAST-BINDING-CORRECTED-FORMAL-RUN-A-AUTHORITY-CANDIDATE-V1.json';
const V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_MERGED_MAIN_QUALIFIED_RUN_A_AUTHORITY_CANDIDATE_V1.cjs',H='docs/handoff/GEOX-MCFT-CAP-08-S6-HANDOFF.md',OUT=P.join(R,'acceptance-output/MCFT_CAP_08_S6_MERGED_MAIN_QUALIFIED_RUN_A_AUTHORITY_CANDIDATE_RESULT.json');
const CH=[W,CA,O,I,BD,V].sort(),MX=['CJS_MODULE_LOADING','PORT_EXPORT_IMPORT_BINDING','FRESH_BOOTSTRAP_FACTS','AUTHORITY_ARGUMENT_TRANSPORT','PHYSICAL_DATABASE_IDENTITY','T16_S4_T17_INTERLEAVE','T17_GUARD_ACL','EXECUTION_PHASE_ORDER','STATE_PROJECTION_CANONICAL_PAYLOAD','CANONICAL_RECEIPT_CARDINALITY_153','OPERATIONAL_EVENT_CARDINALITY_224','FVO10_CANONICAL_ALIAS','FVO17_CORRECTED_FORECAST_BINDING','EXACT_WITNESS_PRODUCERS_22','RESTART_READ_CONTINUITY','DATABASE_CLEAN_DROP'];
const g=(...x)=>E('git',x,{cwd:R,encoding:'utf8'}).trim(),t=x=>F.readFileSync(P.join(R,x),'utf8'),j=x=>JSON.parse(t(x));
const can=x=>Array.isArray(x)?'['+x.map(can).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+can(x[k])).join(',')+'}':JSON.stringify(x);
const sem=x=>{x=structuredClone(x);delete x.semantic_digest;return'sha256:'+C.createHash('sha256').update(can(x)).digest('hex')};
const save=x=>{F.mkdirSync(P.dirname(OUT),{recursive:true});F.writeFileSync(OUT,JSON.stringify(x,null,2)+'\n')};
try{
 const base=String(process.env.MCFT_BASE_SHA||B).trim();A.equal(base,B);A.equal(g('merge-base',B,'HEAD'),B);A.equal(g('rev-list','--count',B+'..HEAD'),'1');A.equal(g('diff','--check',B+'...HEAD'),'');
 A.deepEqual(g('diff','--name-only',B+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),CH);A.deepEqual(g('diff','--name-only',S+'...'+B).split(/\r?\n/).filter(Boolean),[H]);
 const c=j(CA),o=j(O),i=j(I),b=j(BD),q=j(Q),old=j(OLD);for(const x of[c,o,i,b,q])A.equal(x.semantic_digest,sem(x),x.schema_version);
 const blobs={candidate:g('rev-parse','HEAD:'+CA),objectSet:g('rev-parse','HEAD:'+O),issuance:g('rev-parse','HEAD:'+I),boundary:g('rev-parse','HEAD:'+BD),qualified:g('rev-parse','HEAD:'+Q)};
 A.equal(blobs.qualified,g('rev-parse',S+':'+Q));A.equal(blobs.qualified,g('rev-parse',B+':'+Q));A.equal(blobs.qualified,'dca4c8b35e2b9c4635f2b1b2e82fff23a8247c0e');
 A.equal(q.record_status,'EXACT_PATH_DEVELOPMENT_REHEARSAL_OBJECT_SET_FROZEN');A.equal(q.object_count,56);
 const sets=[q.exact_control_plane_object_set,q.exact_database_bootstrap_object_set,q.exact_product_object_set,q.exact_port_bundle_object_set,q.exact_harness_object_set,q.protected_invariant_object_set];A.equal(sets.reduce((n,x)=>n+Object.keys(x).length,0),56);
 for(const set of sets)for(const[p,sha]of Object.entries(set))for(const ref of[S,B,'HEAD'])A.equal(g('rev-parse',ref+':'+p),sha,'EXECUTION_BLOB:'+ref+':'+p);
 A.equal(c.record_status,'FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORITY_CANDIDATE_NOT_EFFECTIVE');A.equal(c.authority_class,'FINAL_FORMAL_RUN_ONLY');A.equal(c.base_governance_main_sha,B);A.equal(c.exact_subject_sha,S);A.equal(c.authorized_run_label,'RUN_A');A.equal(c.operational_run_instance_id,OP);
 A.equal(c.logical_database_identity.identity_id,DB);A.equal(c.logical_database_identity.physical_name_template,'geox_mcft_cap08_s6_run_a_replacement_011_<github_run_id>');A.equal(c.logical_database_identity.reusable,false);A.equal(c.single_use_contract.max_dispatch_count,1);A.equal(c.single_use_contract.github_run_attempt_required,1);A.equal(c.single_use_contract.rerun_authorized,false);A.equal(c.sequence_contract.run_b_remains_blocked,true);A.ok(Object.values(c.authorization_state).every(x=>x===false));
 A.equal(c.object_set_manifest_ref.blob_sha,blobs.objectSet);A.equal(c.object_set_manifest_ref.object_count,56);A.equal(c.qualification_provenance.workflow_run_id,30837192005);A.equal(c.qualification_provenance.integration_qualification_artifact_id,8865385476);A.equal(c.qualification_provenance.difference_count,0);A.equal(c.qualification_provenance.formal_authority_predecessor_satisfied,true);
 A.equal(o.record_status,'MERGED_MAIN_QUALIFIED_RUN_A_AUTHORITY_OBJECT_SET_FROZEN');A.equal(o.object_count,56);A.equal(o.qualified_execution_manifest_ref.blob_sha,blobs.qualified);A.equal(o.governance_main_delta_proof.qualified_execution_object_delta,0);A.deepEqual(o.required_regression_matrix,MX);A.equal(o.formal_authority_effective,false);
 A.equal(i.candidate.blob_sha,blobs.candidate);A.equal(i.object_set.blob_sha,blobs.objectSet);A.equal(i.qualification.difference_count,0);A.equal(i.activation.authority_effective,false);A.equal(i.activation.database_execution_authorized,false);A.equal(i.activation.workflow_dispatch_authorized,false);
 A.equal(b.changed_file_count,6);A.deepEqual([...b.changed_files].sort(),CH);A.equal(b.candidate_authority_blob_sha,blobs.candidate);A.equal(b.object_set_blob_sha,blobs.objectSet);A.equal(b.object_set_count,56);A.equal(b.candidate_runtime_gate_eligible,false);A.equal(b.database_execution_performed,false);A.equal(b.workflow_dispatch_performed,false);
 A.equal(old.operational_run_instance_id,'MCFT-CAP-08-S6-FORMAL-RUN-A-20260802-REPLACEMENT-010');A.equal(old.authorization_state.authority_effective,false);A.equal(old.authorization_state.workflow_dispatch_performed,false);
 const gate=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs')),input={exactSubjectSha:S,runLabel:'RUN_A',operationalRunInstanceId:OP};
 A.throws(()=>gate.validateExecutionAuthorityV1(c,input),/SINGLE_RUN_DATABASE_EXECUTION_REQUIRED|EXECUTION_AUTHORITY_RECORD_STATUS/);
 const e=structuredClone(c);Object.assign(e,{record_status:'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED',evidence_class:'FINAL_FORMAL_EVIDENCE_ELIGIBLE_AFTER_TERMINAL_SUCCESS',expires_at:'2099-08-07T18:00:00.000Z',single_run_database_execution_authorized:true,database_execution_workflow_authorized:true,workflow_dispatch_execution_authorized:true,final_formal_run_execution_authorized:true,hard_acceptance_eligible:true,s6_candidate_evidence_eligible:true,dual_run_ci_authorized:false,cross_run_comparator_authorized:false,final_ledger_settlement_authorized:false});gate.validateExecutionAuthorityV1(e,input);
 const id=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs'));A.equal(id.materializePhysicalDatabaseNameV1(e,'30850000011'),'geox_mcft_cap08_s6_run_a_replacement_011_30850000011');
 const wf=t(W);A.doesNotMatch(wf,/workflow_dispatch:|postgres:|psql|DATABASE_URL/i);A.match(wf,/Validate merged-main qualified 56-object formal RUN_A candidate/);
 const r={schema_version:'geox_mcft_cap08_s6_merged_main_qualified_run_a_authority_candidate_result_v1',status:'PASS',base_governance_main_sha:B,exact_head_sha:g('rev-parse','HEAD'),exact_subject_sha:S,object_count:56,qualified_execution_object_delta:0,merged_main_qualification_run_id:30837192005,integration_artifact_id:8865385476,operational_run_instance_id:OP,logical_database_identity:DB,candidate_runtime_gate_eligible:false,database_execution_performed:false,workflow_dispatch_performed:false,run_b_dispatch_authorized:false};save(r);console.log(JSON.stringify(r,null,2));
}catch(error){save({schema_version:'geox_mcft_cap08_s6_merged_main_qualified_run_a_authority_candidate_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1}
