#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),BASE='b77531284ebda6c4819b78a3ee7dd2262c7a909b',WORKFLOW='.github/workflows/mcft-cap-08-s6-formal-cross-run-comparator-execution.yml',CONTROL='scripts/runtime_acceptance/mcft_cap08_s6_formal_comparator/formal_comparator_execution_control_v1.cjs',CONTRACT='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-EXECUTION-WORKFLOW-V1.json',BOUNDARY='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-EXECUTION-WORKFLOW-BOUNDARY-V1.json',VALIDATOR='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_FORMAL_CROSS_RUN_COMPARATOR_EXECUTION_WORKFLOW_V1.cjs',CHANGED=[WORKFLOW,CONTROL,CONTRACT,BOUNDARY,VALIDATOR].sort(),OUTPUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_FORMAL_CROSS_RUN_COMPARATOR_EXECUTION_WORKFLOW_RESULT.json');
const git=(...a)=>execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim(),read=p=>fs.readFileSync(path.join(ROOT,p),'utf8'),json=p=>JSON.parse(read(p));
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function digest(v){const c=structuredClone(v);delete c.semantic_digest;return`sha256:${crypto.createHash('sha256').update(canonical(c)).digest('hex')}`}
function save(v){fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,`${JSON.stringify(v,null,2)}\n`)}
try{
 const base=String(process.env.MCFT_BASE_SHA||BASE).trim();assert.equal(base,BASE);assert.equal(git('merge-base',BASE,'HEAD'),BASE);assert.equal(git('rev-list','--count',`${BASE}..HEAD`),'1');assert.equal(git('diff','--check',`${BASE}...HEAD`),'');assert.deepEqual(git('diff','--name-only',`${BASE}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),CHANGED);
 const c=json(CONTRACT),b=json(BOUNDARY),w=read(WORKFLOW),ctl=read(CONTROL);assert.equal(c.semantic_digest,digest(c));assert.equal(b.semantic_digest,digest(b));assert.equal(git('rev-parse',`HEAD:${WORKFLOW}`),c.workflow.blob_sha);assert.equal(git('rev-parse',`HEAD:${CONTROL}`),c.execution_control.blob_sha);assert.equal(c.formal_comparator_execution_performed,false);assert.equal(b.formal_comparator_execution_performed,false);assert.equal(b.changed_file_count,5);assert.deepEqual([...b.changed_files].sort(),CHANGED);
 for(const m of ['workflow_dispatch:','exact_subject_sha:','comparator_execution_id:','execution_authority_path:',"if: github.event_name == 'workflow_dispatch'","if: github.event_name != 'workflow_dispatch'",'Gate effective single-use comparator authority before artifact transport','Download exact settled Formal RUN_A artifact','Download exact settled Formal RUN_B artifact','Audit exact formal input runs and artifact digests','Execute formal cross-run comparator exactly once','Upload one formal comparator artifact only','retention-days: 365'])assert.ok(w.includes(m),`MISSING:${m}`);
 for(const m of ["assert.equal(a.record_status,'FORMAL_CROSS_RUN_COMPARATOR_AUTHORIZED')","assert.equal(Number(process.env.GITHUB_RUN_ATTEMPT),1)"])assert.ok(ctl.includes(m),`CONTROL:${m}`);
 assert.ok(w.includes('scripts/runtime_acceptance/mcft_cap08_s6_formal_comparator/formal_comparator_execution_control_v1.cjs'),'WORKFLOW_CONTROL_PATH');
 assert.equal(w.includes('\n  push:'),false);const j=w.slice(w.indexOf('  execute-formal-comparator-once:'));assert.ok(j.indexOf('Gate effective single-use comparator authority before artifact transport')<j.indexOf('Download exact settled Formal RUN_A artifact'));assert.ok(j.indexOf('Audit exact formal input runs and artifact digests')<j.indexOf('Execute formal cross-run comparator exactly once'));
 const r={schema_version:'geox_mcft_cap08_s6_formal_cross_run_comparator_execution_workflow_qualification_result_v1',status:'PASS',evidence_class:'NON_FORMAL_WORKFLOW_QUALIFICATION',base_main_sha:BASE,exact_head_sha:git('rev-parse','HEAD'),workflow_blob_sha:c.workflow.blob_sha,execution_control_blob_sha:c.execution_control.blob_sha,formal_comparator_execution_performed:false,next_legal_action:'ISSUE_REPLACEMENT_FORMAL_COMPARATOR_AUTHORITY_CANDIDATE_WITH_EXECUTION_WORKFLOW'};save(r);console.log(JSON.stringify(r,null,2));
}catch(e){save({schema_version:'geox_mcft_cap08_s6_formal_cross_run_comparator_execution_workflow_qualification_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1}
