#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),P=require('node:child_process'),F=require('node:fs'),X=require('node:path');
const R=X.resolve(__dirname,'../..'),D='docs/digital_twin/mcft/cap_08',Q=X.join(R,'acceptance-output/MCFT_CAP_08_S6_RUN_A_QUALIFICATION_BOOTSTRAP_FRESHNESS_CORRECTION_RESULT.json');
const p={f:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-V4-BOOTSTRAP-FRESHNESS-FAILURE-V1.json`,c:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-BOOTSTRAP-FRESHNESS-CORRECTION-V1.json`,b:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-BOOTSTRAP-FRESHNESS-CORRECTION-BOUNDARY-V1.json`,fresh:'scripts/runtime_acceptance/mcft_cap08_s6_run_a_qualification_ports/fresh_database_v1.cjs',index:'scripts/runtime_acceptance/mcft_cap08_s6_run_a_qualification_ports/index_v1.cjs',old:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/fresh_database_v1.cjs',historical:'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_RUN_A_QUALIFICATION_PORT_BINDING_CORRECTION.cjs',wf:'.github/workflows/mcft-cap-08-s6-run-a-qualification-bootstrap-freshness-correction.yml'};
const read=x=>JSON.parse(F.readFileSync(X.join(R,x),'utf8')),txt=x=>F.readFileSync(X.join(R,x),'utf8'),git=(...a)=>P.execFileSync('git',a,{cwd:R,encoding:'utf8'}).trim();
const canon=v=>Array.isArray(v)?`[${v.map(canon).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`:JSON.stringify(v);
const sd=v=>{const x=structuredClone(v);delete x.semantic_digest;return`sha256:${C.createHash('sha256').update(canon(x)).digest('hex')}`};
const out=v=>{F.mkdirSync(X.dirname(Q),{recursive:true});F.writeFileSync(Q,JSON.stringify(v,null,2)+'\n')};
function pools(values){return{pool:{query:async()=>({rows:[{database_name:'geox_mcft_cap08_s6_run_a_qual_006',user_name:'geox_mcft_cap08_runner_v1'}]})},adminPool:{query:async sql=>{const s=String(sql);if(s.includes('FROM public.facts f LEFT JOIN'))return{rows:[{n:values.missing}]};if(s.includes('strpos(record_json'))return{rows:[{n:values.identity}]};if(s.includes('twin_fact_visibility_index_v1'))return{rows:[{n:values.visibility}]};if(s.includes('twin_fact_visibility_epoch_v1 WHERE status'))return{rows:[{n:values.epochs}]};if(s.includes('FROM public.facts'))return{rows:[{n:values.facts}]};const r=['twin_active_lineage_index_v1','twin_runtime_checkpoint_latest_index_v1','twin_state_latest_index_v1','twin_forecast_result_latest_index_v1','twin_scenario_latest_index_v1'].find(x=>s.includes(x));if(r)return{rows:[{n:values[r]||0}]};throw new Error(`UNEXPECTED_QUERY:${s}`)}}};}
(async()=>{try{
 const f=read(p.f),c=read(p.c),b=read(p.b),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha);
 A.equal(base,b.base_main_sha);A.equal(git('merge-base',base,'HEAD'),base);A.equal(git('diff','--check',`${base}...HEAD`),'');
 const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();A.deepEqual(changed,[...b.changed_files].sort());A.equal(changed.length,8);for(const v of[f,c,b])A.equal(v.semantic_digest,sd(v));
 A.equal(f.workflow_run_id,30616284792);A.equal(f.authority_job_status,'PASS');A.equal(f.first_failure_code,'DATABASE_NOT_FRESH');A.equal(f.database_bootstrap_status,'PASS');A.equal(f.database_drop_status,'PASS');A.equal(f.qualification_result_generated,false);A.equal(f.operational_instance_reusable,false);A.equal(f.bootstrap_baseline_evidence.fact_count,11);A.equal(f.bootstrap_baseline_evidence.visibility_row_count,11);
 A.equal(git('rev-parse',`${base}:${p.old}`),'95d6d2e7179df06aa728df4a4fde0ab7fc2a788c');A.equal(git('rev-parse',`HEAD:${p.old}`),'95d6d2e7179df06aa728df4a4fde0ab7fc2a788c');A.equal(git('rev-parse',`HEAD:${p.fresh}`),'6850c56a45b123481e11f9335bbbb582aac09651');A.equal(git('rev-parse',`HEAD:${p.index}`),'257e8b8a0aabe05b92d94106dcb887a8de095d0e');A.equal(git('rev-parse',`${base}:${p.historical}`),'539b15ce1274399cd556b9a723dabd7fcb9b7508');A.equal(git('rev-parse',`HEAD:${p.historical}`),'bd5dd3cabf544a2a1fa25be1d91a1278c4ff35c3');A.match(txt(p.historical),/SUCCESSOR_BOOTSTRAP_FRESHNESS_CORRECTION/);
 const fresh=txt(p.fresh),index=txt(p.index);A.match(fresh,/EXPECTED_BOOTSTRAP_FACT_COUNT_V1=11/);A.match(fresh,/QUALIFICATION_RUN_IDENTITY_FACT_NOT_FRESH/);A.match(index,/createQualificationFreshDatabasePortV1/);A.doesNotMatch(index,/createFreshDatabasePortV1/);
 const mod=require(X.join(R,p.fresh)),spec={operational_run_instance_id:'MCFT-CAP-08-S6-RUN-A-QUAL-20260731-006',exact_subject_sha:'a'.repeat(40),formal_run_id:'formal_run_test'},good={facts:11,epochs:1,visibility:11,missing:0,identity:0};
 const ok=await mod.createQualificationFreshDatabasePortV1(pools(good)).assertFreshDisposable({spec});A.equal(ok.fresh,true);A.equal(ok.bootstrap_fact_count,11);
 for(const [bad,code] of [[{...good,facts:12},'BOOTSTRAP_FACT_BASELINE_DRIFT'],[{...good,epochs:2},'BOOTSTRAP_ACTIVE_VISIBILITY_EPOCH_DRIFT'],[{...good,visibility:10},'BOOTSTRAP_VISIBILITY_BASELINE_DRIFT'],[{...good,missing:1},'BOOTSTRAP_FACT_VISIBILITY_INCOMPLETE'],[{...good,twin_active_lineage_index_v1:1},'QUALIFICATION_RUNTIME_RELATION_NOT_FRESH'],[{...good,identity:1},'QUALIFICATION_RUN_IDENTITY_FACT_NOT_FRESH']]){await A.rejects(()=>mod.createQualificationFreshDatabasePortV1(pools(bad)).assertFreshDisposable({spec}),new RegExp(code));}
 const wf=txt(p.wf);A.match(wf,/pull_request:/);for(const x of[/workflow_dispatch:/,/services:\s*\n\s*postgres:/,/DATABASE_URL/])A.doesNotMatch(wf,x);A.equal(b.product_runtime_source_file_count,0);A.equal(b.formal_port_bundle_file_count,0);A.equal(b.database_execution_performed,false);
 const z={schema_version:'geox_mcft_cap08_s6_run_a_qualification_bootstrap_freshness_correction_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:8,failed_workflow_run_id:f.workflow_run_id,bootstrap_fact_count:11,visibility_count:11,positive_vector_count:1,negative_vector_count:6,qualification_fresh_port_blob_sha:'6850c56a45b123481e11f9335bbbb582aac09651',qualification_port_bundle_blob_sha:'257e8b8a0aabe05b92d94106dcb887a8de095d0e',database_execution_performed:false,workflow_dispatch_performed:false,run_a_qualification_completed:false};out(z);console.log(JSON.stringify(z,null,2));
}catch(e){out({schema_version:'geox_mcft_cap08_s6_run_a_qualification_bootstrap_freshness_correction_result_v1',status:'FAIL',error:e instanceof Error?e.stack||e.message:String(e)});console.error(e);process.exitCode=1;}})();
