#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const cp=require('node:child_process');
const fs=require('node:fs');
const path=require('node:path');
const BASE='3169b3cc3fc9b490bdf43e3ca9ebc41fab5ff80c';
const BASE_REGISTRY_BLOB='fd056c666821c02b43815e01265af0bd14d2be7e';
const TARGET_REGISTRY_BLOB='767d7a8c2ab65e4bd6fb212bb2c38a4bbc40ff25';
const S4_SUBJECT='6a4138e77fe6b838bc0f552a0bc5e2ceb84c026f';
const S4_RUN=31108834682;
const S4_ARTIFACT=8970768718;
const S4_DIGEST='sha256:64e14355edad6e2711cdde26cc3ac2bd6c7795c7e64439b194679350ce7cc80c';
const REGISTRY='docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json';
const STATUS='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-DELIVERY-STATUS-V1.json';
const BOUNDARY='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-REGISTRY-REGISTRATION-BOUNDARY-V1.json';
const RECORD='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-REGISTRY-REGISTRATION-V1.json';
const WORKFLOW='.github/workflows/mcft-cap-09-s5-registry-registration.yml';
const VALIDATOR='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S5_REGISTRY_REGISTRATION.cjs';
const CLASSIFIER='scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_classifier_v1.cjs';
const ROUTER='scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_router_v1.cjs';
const CROSS='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_REGISTRY_CROSS_LIFECYCLE_REPAIR.cjs';
const S2_WORKFLOW='.github/workflows/mcft-cap-09-s2-registry-registration.yml';
const FILES=[".github/workflows/mcft-cap-09-s2-registry-registration.yml", ".github/workflows/mcft-cap-09-s5-registry-registration.yml", "docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json", "docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-DELIVERY-STATUS-V1.json", "docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-REGISTRY-REGISTRATION-BOUNDARY-V1.json", "docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S5-REGISTRY-REGISTRATION-V1.json", "scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_REGISTRY_CROSS_LIFECYCLE_REPAIR.cjs", "scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S5_REGISTRY_REGISTRATION.cjs", "scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_classifier_v1.cjs", "scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_router_v1.cjs"].sort();
const OUTPUT='acceptance-output/MCFT_CAP_09_S5_REGISTRY_REGISTRATION_RESULT.json';
const FROZEN=[
'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-TASK.md',
'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-STAGE-1B-SCOPE-CONTRACT-V1.json',
'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S4-DELIVERY-STATUS-V1.json',
'.github/workflows/mcft-cap-09-s4-exact-sha-attestation.yml',
'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S4_EXACT_SHA_ATTESTATION_V1.cjs',
'apps/server/src/runtime/twin_runtime/postgres_expired_slot_recovery_adapter_v1.ts',
'apps/server/src/runtime/twin_runtime/restart_backfill_stale_detection_service_v1.ts'
];
const git=(...args)=>cp.execFileSync('git',args,{encoding:'utf8'}).trim();
const readJson=(p)=>JSON.parse(fs.readFileSync(p,'utf8'));
const must=(v,c)=>{if(!v)throw new Error(c);};
const same=(a,b,c)=>{try{assert.deepEqual(a,b);}catch{throw new Error(c);}};
const write=(v)=>{fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(v,null,2)+'\n');};
function artifact(name){const root=path.resolve(process.env.MCFT_CAP09_S4_EFFECTIVE_ARTIFACT_DIR||'acceptance-input/cap09-s4-effective');const stack=[root];while(stack.length){const d=stack.pop();if(!d||!fs.existsSync(d))continue;for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())stack.push(f);else if(e.name===name)return f;}}throw new Error('ARTIFACT_MISSING:'+name);}
function falseAuthorities(v,p){for(const k of ['implementation_authorized','runtime_source_authorized','live_ingestion_authorized','background_scheduler_authorized','canonical_write_authorized','public_http_writer_authorized','model_activation_authorized','controlled_action_authorized'])must(v[k]===false,p+':'+k);}
async function pr(n){must(process.env.GITHUB_TOKEN&&process.env.GITHUB_REPOSITORY,'GITHUB_ENV_REQUIRED');const r=await fetch('https://api.github.com/repos/'+process.env.GITHUB_REPOSITORY+'/pulls/'+n,{headers:{Authorization:'Bearer '+process.env.GITHUB_TOKEN,Accept:'application/vnd.github+json','User-Agent':'geox-cap09-s5-registry'}});const b=await r.text();must(r.ok,'GITHUB_API_'+r.status+':'+b.slice(0,300));return JSON.parse(b);}
(async()=>{try{const base=process.env.MCFT_BASE_SHA;const head=git('rev-parse','HEAD');must(base===BASE,'EXACT_S5_REGISTRATION_BASE_REQUIRED');must(git('rev-list','--count',base+'..HEAD')==='1','ONE_COMMIT_REQUIRED');const changed=git('diff','--name-only',base+'...HEAD').split(/\r?\n/).filter(Boolean).sort();same(changed,FILES,'EXACT_TEN_FILE_S5_REGISTRATION_BOUNDARY_REQUIRED');const marker=['MCFT','CANDIDATE','DECLARATION','V2'].join('_');must(!git('diff','--unified=0',base+'...HEAD').includes(marker),'CANDIDATE_DECLARATION_FORBIDDEN');must(git('rev-parse',base+':'+REGISTRY)===BASE_REGISTRY_BLOB,'BASE_REGISTRY_BLOB_REQUIRED');must(git('rev-parse','HEAD:'+REGISTRY)===TARGET_REGISTRY_BLOB,'TARGET_REGISTRY_BLOB_REQUIRED');for(const f of FROZEN)must(git('rev-parse',base+':'+f)===git('rev-parse','HEAD:'+f),'FROZEN_BLOB_DRIFT:'+f);must(!changed.some(f=>f.startsWith('apps/')||f.startsWith('packages/')||f.includes('/migrations/')),'RUNTIME_OR_MIGRATION_FORBIDDEN');must(cp.spawnSync('git',['merge-base','--is-ancestor',S4_SUBJECT,base]).status===0,'S4_SUBJECT_ANCESTRY_REQUIRED');
const att=readJson(artifact('MCFT_CAP_09_S4_EXACT_SHA_ATTESTATION.json'));const loc=readJson(artifact('MCFT_CAP_09_S4_ATTESTATION_RETENTION_LOCATOR.json'));must(att.status==='PASS'&&att.subject_sha===S4_SUBJECT,'S4_ATTESTATION_IDENTITY');must(att.capability_line_id==='MCFT-CAP-09'&&att.slice_id==='MCFT-CAP-09.S4','S4_ATTESTATION_NAMESPACE');must(att.semantic_artifact_digest===S4_DIGEST,'S4_SEMANTIC_DIGEST');must(att.effective_authority?.s4_restart_backfill_stale_detection_effective===true,'S4_NOT_EFFECTIVE');must(att.effective_authority?.effective_next_slice==='S5','S4_NEXT_SLICE');must(att.effective_authority?.s5_registry_registration_authorized===true,'S5_REGISTRATION_NOT_AUTHORIZED');must(att.effective_authority?.s5_authorized_scope==='SHADOW_ONLINE_CANONICAL_INTEGRATION_ONLY','S5_SCOPE');falseAuthorities(att.effective_authority,'S4_EFFECTIVE_AUTHORITY');must(loc.semantic_artifact_digest===S4_DIGEST&&loc.retention_level==='R2'&&loc.readback_verified===true&&loc.locked_version_delete_denied===true,'S4_R2_LOCATOR');must(Date.parse(loc.retain_until)>=Date.now()+729*86400000,'S4_R2_RETENTION_WINDOW');
const before=JSON.parse(git('show',base+':'+REGISTRY));const after=readJson(REGISTRY);must(after.authority_set_revision==='1.12'&&after.authority_set_change_id==='MCFT-CAP-09.S5-TRANSITION-REGISTRATION','REGISTRY_TARGET_REVISION');for(const id of ['MCFT-CAP-06','MCFT-CAP-07','MCFT-CAP-08'])same(after.capabilities.find(e=>e.capability_line===id),before.capabilities.find(e=>e.capability_line===id),'PREDECESSOR_REGISTRY_DRIFT:'+id);const b09=before.capabilities.find(e=>e.capability_line==='MCFT-CAP-09');const a09=after.capabilities.find(e=>e.capability_line==='MCFT-CAP-09');must(b09&&a09,'CAP09_REGISTRY_ENTRY');same(a09.authoritative_candidate_status_paths,[...b09.authoritative_candidate_status_paths,STATUS],'S5_STATUS_PATH_APPEND_ONLY');const rule={status_file:STATUS,field_path:'s5_candidate_implemented',allowed_candidate_values:[true],focused_workflow:'mcft-cap-09-s5-shadow-online-canonical-integration',standard_workflow:'ci',predecessor_effective_evidence_required:true};same(a09.candidate_transition_fields,[...b09.candidate_transition_fields,rule],'S5_RULE_APPEND_ONLY');same(a09.deferred_status_paths,b09.deferred_status_paths.filter(v=>v!==STATUS),'S5_DEFERRED_PATH_REMOVAL_ONLY');for(const k of Object.keys(b09))if(!['authoritative_candidate_status_paths','candidate_transition_fields','deferred_status_paths'].includes(k))same(a09[k],b09[k],'CAP09_REGISTRY_FIELD_DRIFT:'+k);falseAuthorities(a09,'REGISTRY_AUTHORITY');
const status=readJson(STATUS),boundary=readJson(BOUNDARY),record=readJson(RECORD);must(status.status==='REGISTRY_REGISTERED_NOT_CANDIDATE'&&status.s5_registry_registration_implemented===true&&status.s5_candidate_implemented===false,'S5_STATUS_NON_CANDIDATE');must(status.candidate_declaration_present===false&&status.externally_effective===false,'S5_STATUS_NON_EFFECTIVE');must(status.registry_rule_present===true&&status.authorized_s5_scope==='SHADOW_ONLINE_CANONICAL_INTEGRATION_ONLY','S5_STATUS_SCOPE');must(status.s4_effective_subject_sha===S4_SUBJECT&&status.s4_exact_sha_r2_run_id===S4_RUN&&status.s4_exact_sha_artifact_id===S4_ARTIFACT&&status.s4_semantic_artifact_digest===S4_DIGEST,'S5_STATUS_S4_BINDING');falseAuthorities(status,'S5_STATUS_AUTHORITY');must(boundary.base_main_sha===BASE&&boundary.changed_file_count===10,'BOUNDARY_BASE_COUNT');same(boundary.changed_files.sort(),FILES,'BOUNDARY_FILES');must(boundary.candidate_transition===false&&boundary.candidate_declaration===false&&boundary.registry_delta===1&&boundary.runtime_source_delta===0,'BOUNDARY_DELTAS');must(record.base_registry_blob_sha===BASE_REGISTRY_BLOB&&record.target_registry_blob_sha===TARGET_REGISTRY_BLOB,'RECORD_REGISTRY_BLOBS');must(record.target_authority_set_revision==='1.12'&&record.target_authority_set_change_id==='MCFT-CAP-09.S5-TRANSITION-REGISTRATION','RECORD_TARGET');must(record.candidate_transition_performed===false&&record.candidate_declaration_present===false&&record.same_pr_registry_registration_cannot_authorize_candidate===true,'RECORD_NON_CANDIDATE');falseAuthorities(record,'S5_RECORD_AUTHORITY');
for(const [file,tokens] of [[CLASSIFIER,['s5-registry-registration','S5_REGISTRATION_FILES']],[ROUTER,['s5-registry-registration','--s5-registration-route-only']],[CROSS,['S5_REGISTRATION_FILES','--s5-registration-route-only']],[S2_WORKFLOW,['s5-registry-registration','--s5-registration-route-only']]]){const text=fs.readFileSync(file,'utf8');for(const t of tokens)must(text.includes(t),'ROUTING_TOKEN:'+file+':'+t);}
if(process.env.MCFT_EVENT_NAME==='pull_request'){const p=await pr(Number(process.env.MCFT_PR_NUMBER));must(p.head.sha===head&&p.base.sha===base,'PR_EXACT_SHA_BINDING');must(!String(p.body||'').includes('<!-- '+marker),'PR_CANDIDATE_DECLARATION_FORBIDDEN');}
const result={schema_version:'geox_mcft_cap09_s5_registry_registration_result_v1',status:'PASS',base_sha:base,head_sha:head,changed_files:FILES,s4_effective_subject_sha:S4_SUBJECT,s4_exact_sha_r2_run_id:S4_RUN,s4_exact_sha_artifact_id:S4_ARTIFACT,s4_semantic_artifact_digest:S4_DIGEST,target_authority_set_revision:'1.12',target_registry_blob_sha:TARGET_REGISTRY_BLOB,s5_status_path_registered:true,s5_transition_rule_registered:true,candidate_transition:false,candidate_declaration_present:false,runtime_source_delta:0,externally_effective:false,first_legal_next_action:'MCFT_CAP_09_S5_SHADOW_ONLINE_CANONICAL_INTEGRATION_CANDIDATE'};write(result);console.log(JSON.stringify(result,null,2));}catch(e){const failure={status:'FAIL',error:String(e instanceof Error?e.message:e)};write(failure);console.error(JSON.stringify(failure,null,2));process.exitCode=1;}})();
