#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'../..'),OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_AUTHORITY_RECONCILIATION_RESULT.json');
const BASE='dfda2dd55e140313598dbc2fcbc9176c8891f465',PR0='ade35875ff6f5ef92ec76f04ab9fc302c57f700e',INVALID='71d607cd887833ff0062a54983c4b43895d47966';
const read=p=>fs.readFileSync(path.join(ROOT,p),'utf8'),json=p=>JSON.parse(read(p)),sha=p=>'sha256:'+crypto.createHash('sha256').update(fs.readFileSync(path.join(ROOT,p))).digest('hex');
const checks=[];const check=(name,fn)=>{fn();checks.push({name,status:'PASS'});};const write=v=>{fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n');};
try{
 const a=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-CURRENT-AUTHORITY-V1.json'),r=json('docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json'),c=r.capabilities.find(x=>x.capability_line==='MCFT-CAP-08');
 check('CONDITIONAL_NON_EFFECTIVE_AUTHORITY',()=>{assert.equal(a.status,'AUTHORIZATION_CANDIDATE_NOT_EFFECTIVE');assert.equal(a.pr_0_protected_merge_sha,PR0);assert.equal(a.pr_1_base_sha,BASE);assert.equal(a.invalidated_candidate_sha,INVALID);for(const k of ['implementation_authorized','runtime_source_authorized','bounded_replay_runner_authorized','bounded_canonical_transaction_authorized','production_runtime_source_authorized_when_attested','postmerge_ssot_writeback_allowed','mcft_cap_09_authorized'])assert.equal(a[k],false,k);});
 check('REGISTRY_PR1_AND_S1_RULES',()=>{assert.ok(c);const pr1=c.candidate_transition_fields.find(x=>x.field_path==='status'&&x.status_file.endsWith('CURRENT-AUTHORITY-V1.json'));const s1=c.candidate_transition_fields.find(x=>x.field_path==='s1_candidate_implemented');assert.deepEqual(pr1.allowed_candidate_values,['AUTHORIZATION_CANDIDATE_NOT_EFFECTIVE']);assert.equal(pr1.focused_workflow,'mcft-cap-08-authority-reconciliation');assert.deepEqual(s1.allowed_candidate_values,[true]);});
 check('TASKBOOK_V038_SPLIT_PROGRESS_BOUNDARY',()=>{const t=read('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-TASK.md');assert.match(t,/v0\.3\.8/);assert.match(t,/44 文件/);assert.match(t,/effective Freeze Gate completion: \*\*2 \/ 17\*\*/);assert.match(t,/dedicated fresh PostgreSQL database/i);assert.equal(t.includes('blocked until PR-0 protected merge'),false);});
 check('DIGEST_CHAIN',()=>{const m=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-RESOLVED-MANIFEST-V1.json');const expected={taskbook_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-TASK.md'),resolved_manifest_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-RESOLVED-MANIFEST-V1.json'),changed_file_boundary_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-CHANGED-FILE-BOUNDARY-V1.json'),writer_authority_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-WRITER-AUTHORITY-V1.json'),platform_bootstrap_source_digest:sha('apps/server/src/infra/mcft_cap08_database_platform_bootstrap_v1.ts'),progress_recovery_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-PROGRESS-RECOVERY-ADJUDICATION-V1.json'),
progress_query_catalog_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-PROGRESS-QUERY-CATALOG-V1.json'),
progress_witness_catalog_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-PROGRESS-WITNESS-CATALOG-V1.json'),late_correction_test_vectors_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-LATE-CORRECTION-TEST-VECTORS-V1.json'),schema_privilege_digest_policy_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-SCHEMA-PRIVILEGE-DIGEST-POLICY-V1.json'),workflow_declaration_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-WORKFLOW-DECLARATION-V1.json'),pr1_effectiveness_contract_digest:sha('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-PR1-EFFECTIVENESS-CONTRACT-V1.json')};assert.equal(m.taskbook_digest,expected.taskbook_digest);for(const [k,v] of Object.entries(expected))assert.equal(a[k],v,k);});
 check('RUN_CONTRACT_CARDINALITIES',()=>{const x=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-24-TICK-RUN-CONTRACT-V1.json');assert.equal(x.tick_ids.length,24);assert.equal(x.due_obligations.length,25);assert.equal(x.residual_cardinality,24);assert.equal(x.calibration_window.length,16);assert.equal(x.holdout_window.length,8);assert.deepEqual(x.required_canonical_progress_fields,['formal_run_id','phase_id','transaction_family','obligation_id']);});
 check('WRITER_EFFECTIVE_GRAPH',()=>{const x=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-WRITER-AUTHORITY-V1.json');assert.equal(x.database_class,'DEDICATED_FRESH_CAP08_DATABASE');assert.equal(Object.keys(x.relation_privileges).length,30);assert.deepEqual(x.role_memberships,[]);assert.deepEqual(x.roles_allowed_to_assume_runner,[]);assert.equal(x.public_database_effective_privileges.CONNECT,false);assert.equal(x.legacy_login_role_target_database_privileges.geox_runtime_v1.CONNECT,false);});
 check('PROGRESS_25_EXCLUSIVE_STATES',()=>{const x=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-PROGRESS-RECOVERY-ADJUDICATION-V1.json'),q=json(x.query_catalog_ref),w=json(x.witness_catalog_ref);assert.equal(x.state_count,25);assert.equal(x.states.length,25);assert.equal(new Set(x.states.map(s=>s.state_id)).size,25);assert.equal(q.query_count,6);assert.equal(Object.keys(q.query_catalog).length,6);assert.equal(w.state_count,25);assert.equal(Object.keys(w.witnesses).length,25);assert.equal(x.query_catalog_digest,sha(x.query_catalog_ref));assert.equal(x.witness_catalog_digest,sha(x.witness_catalog_ref));assert.equal(x.state_defaults.zero_write_assertion,true);for(const s of x.states)if(s.state_id!=='FAILED_CLOSED_CONFLICT')assert.match(s.completion_predicate,/^conflict = false AND /);});
 check('LATE_VECTORS_AND_FULL_POSTERIOR',()=>{const x=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-LATE-CORRECTION-TEST-VECTORS-V1.json'),m=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-LATE-CORRECTION-MATH-V1.json');assert.equal(x.vector_count,12);assert.ok(x.vectors.find(v=>v.id==='INTERMEDIATE_ORDINARY_ASSIMILATION'));assert.equal(m.transport_method,'DETERMINISTIC_PAIRED_FULL_POSTERIOR_TRANSITION_SENSITIVITY_V1');});
 check('WORKFLOW_EXACT_SUBJECT_AND_20_SNAPSHOTS',()=>{const x=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-WORKFLOW-DECLARATION-V1.json'),y=read('.github/workflows/mcft-cap-08-exact-sha-attestation.yml');assert.equal(x.semantic_snapshot_file_count,20);assert.equal(x.global_planning_write_required,false);assert.match(y,/Checkout exact subject SHA/);assert.match(y,/ref: \$\{\{ inputs\.subject_sha \|\| github\.sha \}\}/);assert.equal(y.includes('with: { ref: main'),false);});
 check('EXACT_44_FILE_BOUNDARY',()=>{const b=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-CHANGED-FILE-BOUNDARY-V1.json');assert.equal(b.changed_file_count,44);assert.equal(b.changed_files.length,44);for(const p of ['docs/digital_twin/GEOX-DIGITAL-TWIN-MASTER-TASK-LINE.md','docs/digital_twin/GEOX-DT-02-MCFT-IMPLEMENTATION-MAP.md','docs/digital_twin/GEOX-MCFT-VERTICAL-CAPABILITY-LINE-MATRIX.json','package.json'])assert.equal(b.changed_files.includes(p),false);});
 const result={schema_version:'geox_mcft_cap08_authority_reconciliation_result_v2',status:'PASS',check_count:checks.length,checks,runtime_domain_code_delta:0,business_schema_migration_delta:0,canonical_runtime_data_delta:0,pr_1_base_sha:BASE};write(result);console.log(JSON.stringify(result));
}catch(e){const result={schema_version:'geox_mcft_cap08_authority_reconciliation_result_v2',status:'FAIL',check_count:checks.length,checks,error:e instanceof Error?e.message:String(e)};write(result);console.error(result.error);process.exitCode=1;}
