#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),c=require('node:child_process'),f=require('node:fs'),p=require('node:path');
const R=p.resolve(__dirname,'../..'),O=p.join(R,'acceptance-output/MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION_RESULT.json'),CORE=p.join(__dirname,'ACCEPTANCE_MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION_CORE.cjs');
const BASE='d5e31c20c356816294b6a902b27ed8dcbe79c42d',BOUNDARY='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-REGISTRY-CONTROL-PLANE-REPAIR-BOUNDARY-V1.json';
const EXACT=['.github/workflows/mcft-cap-09-registry-control-plane-repair.yml',BOUNDARY,'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION.cjs','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION_CORE.cjs','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_REGISTRY_CONTROL_PLANE_REPAIR.cjs','scripts/governance_acceptance/MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1.cjs','scripts/governance_acceptance/MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1_CORE.cjs'].sort();
const g=x=>c.execFileSync('git',x,{cwd:R,encoding:'utf8'}).trim(),same=(x,y)=>{try{a.deepEqual(x,y);return true}catch{return false}},write=v=>{f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(v,null,2)+'\n')};
function exact(){const b=String(process.env.MCFT_BASE_SHA||''),h=String(process.env.MCFT_CANDIDATE_SHA||g(['rev-parse','HEAD']));if(b!==BASE)return false;const s=g(['diff','--name-only',b+'...'+h]),files=s?s.split(/\r?\n/).filter(Boolean).sort():[];if(!same(files,EXACT))return false;const q=JSON.parse(g(['show',h+':'+BOUNDARY]));a.equal(q.change_class,'MCFT_CAP_09_REGISTRY_CONTROL_PLANE_REPAIR');a.equal(q.changed_file_count,7);a.deepEqual(q.changed_files,EXACT);a.equal(q.registry_delta,0);a.equal(q.candidate_transition,false);a.equal(q.runtime_source_delta,0);const z={schema_version:'geox_mcft_cap08_s2_pre_candidate_foundation_lifecycle_result_v5',status:'PASS',classification:'REGISTRY_CONTROL_PLANE_REPAIR_MODE',base_sha:b,candidate_sha:h,changed_file_count:files.length,changed_files:files,historical_foundation_reexecution:false,successor_regression_freeze_bypass:false,registry_delta:0,candidate_transition:false,s2_effective:false,s3_authorized:false};write(z);console.log(JSON.stringify(z));return true}
try{if(!exact())require(CORE)}catch(e){write({schema_version:'geox_mcft_cap08_s2_pre_candidate_foundation_lifecycle_result_v5',status:'FAIL',error:e.message});console.error(e);process.exitCode=1}
