#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.resolve(__dirname,'../..'),CAP='docs/digital_twin/mcft/cap_08';
const P={a:`${CAP}/GEOX-MCFT-CAP-08-S6-EXACT-OBJECT-SET-REF-RECONCILIATION-AUTHORITY-V1.json`,i:`${CAP}/GEOX-MCFT-CAP-08-S6-EXACT-OBJECT-SET-REF-RECONCILIATION-IMPLEMENTATION-V1.json`,b:`${CAP}/GEOX-MCFT-CAP-08-S6-EXACT-OBJECT-SET-REF-RECONCILIATION-BOUNDARY-V1.json`,o:'scripts/runtime_acceptance/mcft_cap08_s6_final_formal_run/object_set_v1.cjs',f:'scripts/governance_acceptance/mcft_cap08_s6_witness/synthetic_fixture_v1.cjs',s:'scripts/runtime_acceptance/mcft_cap08_s6_final_formal_run/synthetic_adapter_v1.cjs'};
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_EXACT_OBJECT_SET_REF_RECONCILIATION_RESULT.json');
const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8')),git=(...a)=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();
function canon(v){if(Array.isArray(v))return`[${v.map(canon).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function sd(v){v=structuredClone(v);delete v.semantic_digest;return`sha256:${crypto.createHash('sha256').update(canon(v)).digest('hex')}`}
function write(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n')}
try{
 const a=read(P.a),i=read(P.i),b=read(P.b),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim();
 assert.equal(base,b.base_main_sha,'BASE_SHA_DRIFT');assert.equal(git('merge-base',base,'HEAD'),base,'BASE_NOT_ANCESTOR');assert.equal(git('diff','--check',`${base}...HEAD`),'','DIFF_CHECK');
 const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(changed,[...b.changed_files].sort(),'CHANGED_FILE_BOUNDARY');assert.equal(changed.length,b.changed_file_count,'CHANGED_FILE_COUNT');
 for(const v of [a,i,b])assert.equal(v.semantic_digest,sd(v),'SEMANTIC_DIGEST');assert.equal(a.record_status,'EXACT_OBJECT_SET_REF_RECONCILIATION_AUTHORIZED');assert.equal(i.record_status,'EXACT_OBJECT_SET_REF_RECONCILIATION_IMPLEMENTED_NOT_EFFECTIVE');
 for(const p of [P.o,P.f,P.s])cp.execFileSync('node',['--check',p],{cwd:ROOT,stdio:'pipe'});
 const {refsForV1}=require(path.join(ROOT,P.o)),{buildSyntheticOrchestratorInputV1}=require(path.join(ROOT,P.s));
 const ids=['B00',...Array.from({length:24},(_,n)=>`T${String(n).padStart(2,'0')}`),'G00','G01','G02'];
 const plan={exact_subject_sha:'1'.repeat(40),run_label:'RUN_A',formal_run_id:'cap08_s6_exact_ref_contract_test',operational_run_instance_id:'exact-ref-contract-test-run-a',scope:{tenant_id:'tenantA',project_id:'projectA',group_id:'groupA',field_id:'fieldA',season_id:'seasonA',zone_id:'zoneA'},lineage_id:'lineageA',revision_id:'revisionA',phases:ids.map(phase_id=>({phase_id,phase_order:['E','H','A','B','G','C','D','F']}))};
 const x=buildSyntheticOrchestratorInputV1(plan),src=x.selectorData;src.closure_member_manifest={members:x.canonicalMembers};assert.equal(x.canonicalMembers.length,153,'CLOSURE_MEMBER_COUNT');
 const refs=id=>refsForV1({object_set_id:id},src),boot=refs('PER_RUN_BOOTSTRAP_TICK_PHASE_MEMBERS'),decision=refs('PER_RUN_DECISION_ACTION_MEMBERS'),late=refs('PER_RUN_LATE_APPEND_FORWARD_MEMBERS'),residual=refs('PER_RUN_RESIDUAL_MEMBERS');
 assert.deepEqual(boot,[src.sequence.bootstrap_root_ref,...src.sequence.tick_member_refs].sort(),'BOOTSTRAP_TICK_EXACT_REFS');assert.ok(decision.includes(src.decision_action.t08_state_ref),'T08_STATE_EXACT_REF');assert.deepEqual(late,[src.late_append_forward.source_observation_ref,src.late_append_forward.corrected_state_ref,src.late_append_forward.t17_state_ref].sort(),'LATE_EXACT_REFS');assert.deepEqual(residual,src.residuals.map(v=>v.object_ref).sort(),'RESIDUAL_EXACT_REFS');
 assert.equal(src.sequence.tick_ids.some((v,n)=>v===src.sequence.tick_member_refs[n]),false,'TICK_LOGICAL_REF_COLLISION');assert.equal(src.residuals.some(v=>v.residual_id===v.object_ref),false,'RESIDUAL_LOGICAL_REF_COLLISION');assert.equal(boot.some(v=>/^TICK-T\d{2}$/.test(v)),false,'LOGICAL_TICK_ALIAS');assert.equal(residual.some(v=>/^R-\d{2}$/.test(v)),false,'LOGICAL_RESIDUAL_ALIAS');
 const source=fs.readFileSync(path.join(ROOT,P.o),'utf8');for(const forbidden of ['`LINEAGE-${source.provenance.formal_run_id}`','`TICK-${t}`',"'STATE-T08'","'STATE-T16'","'STATE-T17'",'source.residuals.map((x)=>x.residual_id)'])assert.equal(source.includes(forbidden),false,`LOGICAL_ALIAS_SELECTOR:${forbidden}`);
 const workflows=['.github/workflows/mcft-cap-08-s6-final-formal-run-orchestrator.yml','.github/workflows/mcft-cap-08-s6-witness-producers.yml'].map(p=>fs.readFileSync(path.join(ROOT,p),'utf8'));for(const w of workflows){assert.ok(w.includes("base='${{ github.event.pull_request.base.sha }}'"),'CURRENT_PR_BASE_CLASSIFIER');assert.ok(w.includes('EXACT_REF_RECONCILIATION'),'RECONCILIATION_MODE')};assert.ok(workflows[1].includes("MCFT_LOCAL_REPLAY: '1'"),'WITNESS_LOCAL_REPLAY');
 for(const p of ['scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_FINAL_FORMAL_RUN_ORCHESTRATOR.cjs','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_WITNESS_PRODUCERS.cjs'])cp.execFileSync('node',[p],{cwd:ROOT,stdio:'pipe',env:{...process.env,MCFT_LOCAL_REPLAY:'1'}});
 const result={schema_version:'geox_mcft_cap08_s6_exact_object_set_ref_reconciliation_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:changed.length,closure_member_count:153,exact_ref_selector_classes:4,successor_workflow_classifier_count:2,synthetic_orchestrator_regression:'PASS',synthetic_witness_producer_regression:'PASS',logical_identity_semantics_preserved:true,logical_alias_as_canonical_ref_count:0,product_runtime_source_file_count:0,database_execution:false,run_a_executed:false,run_b_executed:false,final_ledger_settlement:false,s6_candidate_implemented:false};write(result);console.log(JSON.stringify(result,null,2));
}catch(e){write({schema_version:'geox_mcft_cap08_s6_exact_object_set_ref_reconciliation_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1}
