#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),{execFileSync:E,spawnSync:S}=require('node:child_process');
const R=P.resolve(__dirname,'../..'),B='4959f5e97b1acea3b0906100ae2f353d352e4d8e',CH='f5c5ab35dd4f2e1e462d8aff2ee955d6ef569176',SUB='ce9d6b4df8c708c0d4a99bb24846e1bc44b3cf59',EXEC='MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-20260804-REPLACEMENT-001';
const W='.github/workflows/mcft-cap-08-s6-formal-cross-run-comparator-replacement-001-authority-effectiveness.yml',CA='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-CANDIDATE-V1.json',O='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-OBJECT-SET-V1.json',SUP='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-SUPERSESSION-V1.json',EA='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',ER='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-EFFECTIVENESS-V1.json',EB='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-EFFECTIVENESS-BOUNDARY-V1.json',V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_FORMAL_CROSS_RUN_COMPARATOR_REPLACEMENT_001_AUTHORITY_EFFECTIVENESS_V1.cjs',CONTROL='scripts/runtime_acceptance/mcft_cap08_s6_formal_comparator/formal_comparator_execution_control_v1.cjs',OUT=P.join(R,'acceptance-output/MCFT_CAP_08_S6_FORMAL_COMPARATOR_REPLACEMENT_001_AUTHORITY_EFFECTIVENESS_RESULT.json'),FILES=[W,EA,ER,EB,V].sort();
const g=(...x)=>E('git',x,{cwd:R,encoding:'utf8'}).trim(),t=x=>F.readFileSync(P.join(R,x),'utf8'),j=x=>JSON.parse(t(x));const can=x=>Array.isArray(x)?'['+x.map(can).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+can(x[k])).join(',')+'}':JSON.stringify(x);const sem=x=>{x=structuredClone(x);delete x.semantic_digest;return'sha256:'+C.createHash('sha256').update(can(x)).digest('hex')};const save=x=>{F.mkdirSync(P.dirname(OUT),{recursive:true});F.writeFileSync(OUT,JSON.stringify(x,null,2)+'\n')};
try{
 const base=String(process.env.MCFT_BASE_SHA||B).trim();A.equal(base,B);A.equal(g('merge-base',B,'HEAD'),B);A.equal(g('rev-list','--count',B+'..HEAD'),'1');A.equal(g('diff','--check',B+'...HEAD'),'');A.deepEqual(g('diff','--name-only',B+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),FILES);A.equal(g('diff','--name-only',CH+'...'+B),'');
 const e=j(EA),r=j(ER),b=j(EB),c=j(CA),o=j(O),sup=j(SUP);for(const x of[e,r,b,c,o,sup])A.equal(x.semantic_digest,sem(x),x.schema_version);
 const blobs={effective:g('rev-parse','HEAD:'+EA),record:g('rev-parse','HEAD:'+ER),boundary:g('rev-parse','HEAD:'+EB),candidate:g('rev-parse','HEAD:'+CA),objects:g('rev-parse','HEAD:'+O),supersession:g('rev-parse','HEAD:'+SUP),workflow:g('rev-parse','HEAD:'+W),control:g('rev-parse','HEAD:'+CONTROL)};
 A.equal(blobs.effective,'c2df7c3da181ff231931a66c7f6c6b2312b7015a');A.equal(blobs.record,'7d862055af2af71fd5f2c9ef20008874dc91e47c');A.equal(blobs.boundary,'70196e331a76f80eea45ce53615505654b98a078');A.equal(blobs.candidate,'dffb2a6df42c4a0860f461761f1cf3e2d360c8ac');A.equal(blobs.objects,'57d7817bc60074baee4ca3bd71c21e9bb5dab3b2');A.equal(blobs.supersession,'1cb00a089a2e9085bf941d15df8b4add66a699d5');A.equal(blobs.workflow,'24879ede338908a1680de80c370497d2a6f28583');A.equal(blobs.control,'f6e1673681f734474340c1a1ffab79be60892a7a');
 A.equal(g('rev-parse',CH+':'+CA),blobs.candidate);A.equal(g('rev-parse',B+':'+CA),blobs.candidate);A.equal(g('rev-parse',B+':'+O),blobs.objects);A.equal(g('rev-parse',B+':'+SUP),blobs.supersession);A.equal(o.object_count,12);for(const item of o.objects)for(const ref of[B,'HEAD'])A.equal(g('rev-parse',ref+':'+item.path),item.blob_sha,'OBJECT:'+item.role+':'+ref);
 A.equal(c.authority_effective,false);A.equal(c.comparator_execution_authorized,false);A.equal(sup.predecessor.effectiveness_authorized,false);A.equal(sup.replacement.authority_effective,false);
 A.equal(e.schema_version,'geox_mcft_cap08_s6_formal_cross_run_comparator_authority_v1');A.equal(e.record_status,'FORMAL_CROSS_RUN_COMPARATOR_AUTHORIZED');A.equal(e.exact_subject_sha,SUB);A.equal(e.comparator_execution_id,EXEC);A.equal(e.authority_effective,true);A.equal(e.comparator_execution_authorized,true);A.equal(e.maximum_execution_count,1);A.equal(e.required_execution_attempt,1);A.equal(e.rerun_authorized,false);A.equal(e.duplicate_execution_authorized,false);A.equal(e.authority_reuse_authorized,false);A.equal(e.candidate_head_sha,CH);A.equal(e.candidate_merge_sha,B);A.equal(e.candidate_to_merge_file_delta,0);A.equal(e.candidate_authority_ref.blob_sha,blobs.candidate);A.equal(e.object_set_manifest_ref.blob_sha,blobs.objects);A.equal(e.supersession_ref.blob_sha,blobs.supersession);A.equal(e.workflow_dispatch_performed,false);A.equal(e.formal_comparator_executed,false);A.equal(e.formal_comparator_evidence_created,false);A.equal(e.explicit_one_shot_execution_approval_required,true);
 A.equal(r.production_gate_eligible,true);A.equal(r.effective_authority.blob_sha,blobs.effective);A.equal(r.workflow_dispatch_performed,false);A.equal(r.formal_comparator_execution_performed,false);A.equal(r.explicit_one_shot_execution_approval_required,true);A.equal(b.new_file_count,5);A.equal(b.modified_file_count,0);A.deepEqual([...b.changed_files].sort(),FILES);A.equal(b.workflow_dispatch_performed,false);A.equal(b.formal_comparator_execution_performed,false);
 const gate=S(process.execPath,[P.join(R,CONTROL),'gate'],{encoding:'utf8',env:{...process.env,GITHUB_EVENT_NAME:'workflow_dispatch',GITHUB_RUN_ATTEMPT:'1',MCFT_EXECUTION_AUTHORITY_PATH:P.join(R,EA),MCFT_EXACT_SUBJECT_SHA:SUB,MCFT_COMPARATOR_EXECUTION_ID:EXEC}});A.equal(gate.status,0,gate.stderr);A.match(gate.stdout,/MCFT_CAP08_FORMAL_COMPARATOR_AUTHORITY=/);const denied=S(process.execPath,[P.join(R,CONTROL),'gate'],{encoding:'utf8',env:{...process.env,GITHUB_EVENT_NAME:'workflow_dispatch',GITHUB_RUN_ATTEMPT:'1',MCFT_EXECUTION_AUTHORITY_PATH:P.join(R,CA),MCFT_EXACT_SUBJECT_SHA:SUB,MCFT_COMPARATOR_EXECUTION_ID:EXEC}});A.notEqual(denied.status,0);
 const wf=t(W);A.doesNotMatch(wf,/workflow_dispatch:|actions\/download-artifact|Execute formal cross-run comparator|gh workflow run|postgres:|psql/i);A.match(wf,/Validate Replacement-001 formal comparator authority effectiveness/);
 const result={schema_version:'geox_mcft_cap08_s6_formal_cross_run_comparator_replacement_001_authority_effectiveness_result_v1',status:'PASS',evidence_class:'NON_EXECUTION_AUTHORITY_EFFECTIVENESS_EVIDENCE',base_main_sha:B,exact_head_sha:g('rev-parse','HEAD'),exact_subject_sha:SUB,candidate_head_sha:CH,candidate_merge_sha:B,candidate_to_merge_file_delta:0,object_count:12,effective_authority_blob_sha:blobs.effective,comparator_execution_id:EXEC,authority_effective:true,comparator_execution_authorized:true,workflow_dispatch_performed:false,formal_comparator_execution_performed:false,formal_comparator_evidence_created:false,explicit_one_shot_execution_approval_required:true,next_legal_action:'REQUEST_EXPLICIT_ONE_SHOT_FORMAL_CROSS_RUN_COMPARATOR_EXECUTION_AUTHORIZATION'};save(result);console.log(JSON.stringify(result,null,2));
}catch(error){save({schema_version:'geox_mcft_cap08_s6_formal_cross_run_comparator_replacement_001_authority_effectiveness_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1}
