#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),X=require('node:child_process');
const R=process.cwd(),O=P.join(R,'acceptance-output');
const S='a2e23b47abaf571489458363de48f428262b5f31',B='b3f095be7f808611f1388c3e31ecff29325a7f99',H='fe68f7505b8d25d5198e2ca6664bebbce06f453a',T='e132ef6075e225a2349a93fd988aeb2f7b90e9e1',PR=2884,FR=31032249204,CI=31032249190,FA=8941151054,FD='sha256:cb97de7c7b2077a931458a022be61b6ce6501799247ca983895e31709b817ab1';
const W='.github/workflows/mcft-cap-09-s2-exact-sha-attestation.yml',V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_EXACT_SHA_ATTESTATION_V1.cjs',Q=[W,V].sort();
const f=['.github/workflows/mcft-cap-09-s2-database-evidence-ingress.yml','apps/server/src/runtime/twin_runtime/postgres_evidence_ingress_adapter_v1.ts','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S2-DATABASE-EVIDENCE-INGRESS-CANDIDATE-BOUNDARY-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S2-DATABASE-EVIDENCE-INGRESS-CANDIDATE-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S2-DATABASE-EVIDENCE-INGRESS-CONFIG-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S2-DELIVERY-STATUS-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S2-HARD-ACCEPTANCE-EVIDENCE-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S2-PREDECESSOR-ATTESTATION-CONSUMPTION-V1.json','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_DATABASE_EVIDENCE_INGRESS.cjs','scripts/runtime_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_DATABASE_EVIDENCE_INGRESS.ts'];
const b=['dbce1dc1187c1b7b8eb5dadc6efd25187b89eaf9','df5a7cf70bc0c2e3c7de29e82f6b76af4ad673df','66d5cc1425839b13fd99861b37bbd000c46598f5','765ece35d5d4de37b1d31f641f5da481f89dae46','951e06f1517f911aa5a9fb1e2d9915181e23a2e8','93af094c6fae6c5a7584e32e27c57e1535a24d8a','e464f3c8a9190b3ee066506748918ed65f5ee556','f82277b4a8f663f87f70110e6179b5a073f20fed','47846a0345e0d07c7dc29f93b462e2b45258d069','62ceaf8a0f0751416ac97b8b3cc73d68069aea12'];
const g=(...a)=>X.execFileSync('git',a,{cwd:R,encoding:'utf8'}).trim(),canon=v=>Array.isArray(v)?`[${v.map(canon).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`:JSON.stringify(v),ok=(x,m)=>{if(!x)throw Error(m)},eq=(x,y,m)=>{try{A.deepEqual(x,y)}catch{throw Error(m)}},d=(x,y)=>g('diff','--name-only',`${x}...${y}`).split(/\r?\n/).filter(Boolean).sort(),w=(n,x)=>{F.mkdirSync(O,{recursive:true});F.writeFileSync(P.join(O,n),JSON.stringify(x,null,2)+'\n')};
async function api(e){const r=await fetch(`https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}${e}`,{headers:{Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28'}}),t=await r.text();ok(r.ok,`API_${r.status}:${t.slice(0,100)}`);return t?JSON.parse(t):{}}
function dec(t){const m=['MCFT','CANDIDATE','DECLARATION','V2'].join('_'),a=String(t).split(`<!-- ${m}\n`);ok(a.length===2,'DECL');const z={};for(const l of a[1].split('-->')[0].trim().split(/\r?\n/)){const i=l.indexOf('=');z[l.slice(0,i)]=l.slice(i+1)}return z}
function ctl(){const h=g('rev-parse','HEAD'),base=process.env.MCFT_BASE_SHA;ok(base===S,'BASE');eq(d(base,h),Q,'FILES');ok(+g('rev-list','--count',`${base}..${h}`)===1,'COMMITS');const s=F.readFileSync(W,'utf8'),v=F.readFileSync(V,'utf8'),m=['MCFT','CANDIDATE','DECLARATION','V2'].join('_');ok(!s.includes(m)&&!v.includes(m),'MARKER');for(const x of ['name: mcft-cap-09-s2-exact-sha-attestation','push:','branches: [main]',S,'--attest','mcft-cap-09/s2-exact-sha-attestation','MCFT_SEMANTIC_DIGEST_POLICY: CANONICAL_SORTED_KEYS_V1'])ok(s.includes(x),'WF');ok(v.includes('semantic_artifact_digest')&&v.includes('canon(semantic)'),'DIGEST');for(const x of f)ok(g('rev-parse',`${S}:${x}`)===g('rev-parse',`${h}:${x}`),'DRIFT');w('MCFT_CAP_09_S2_EXACT_SHA_CONTROL_PLANE_RESULT.json',{status:'PASS',change_class:'MCFT_CAP_09_S2_EXACT_SHA_R2_CONTROL_PLANE_CANDIDATE',base_sha:base,head_sha:h,changed_files:Q,attestation_subject_sha:S,semantic_digest_policy:'CANONICAL_SORTED_KEYS_V1',external_effectiveness:false,runtime_source_delta:0,registry_delta:0,taskbook_delta:0,first_legal_next_action:'PROTECTED_MERGE_TRIGGERS_S2_EXACT_SHA_R2_ATTESTATION'})}
async function att(){ok(process.env.MCFT_SUBJECT_SHA===S,'SUBJECT');const c=g('rev-parse','HEAD');eq(g('rev-list','--parents','-n','1',S).split(/\s+/),[S,B,H],'PARENTS');ok(g('rev-parse',`${H}^{tree}`)===T&&g('rev-parse',`${S}^{tree}`)===T,'TREE');eq(d(B,H),[...f].sort(),'CANDIDATE');eq(d(S,c),Q,'CONTROL');for(let i=0;i<f.length;i++){ok(g('rev-parse',`${H}:${f[i]}`)===b[i],'HBLOB');ok(g('rev-parse',`${S}:${f[i]}`)===b[i],'MBLOB')}
 const ps=await api(`/commits/${S}/pulls`),p=ps.find(x=>x.number===PR&&x.merge_commit_sha===S&&x.head?.sha===H&&x.base?.sha===B);ok(p,'PR');const x=dec(p.body),sn=[f[1],f[2],f[3],f[4],f[5],f[6],f[7],f[8],f[9]];ok(x.slice_id==='MCFT-CAP-09.S2'&&x.status_file===f[5]&&x.candidate_field==='s2_candidate_implemented'&&x.candidate_value==='true'&&x.candidate_head===H&&x.base_head===B,'DECL_BIND');eq(x.semantic_snapshot_files.split(','),sn,'SNAP_FILES');eq(x.semantic_snapshot_blobs.split(','),sn.map(y=>b[f.indexOf(y)]),'SNAP_BLOBS');
 const r=await api(`/actions/runs/${FR}`),aa=(await api(`/actions/runs/${FR}/artifacts?per_page=100`)).artifacts.filter(y=>y.id===FA&&y.name===`mcft-cap-09-s2-database-evidence-${H}`&&!y.expired);ok(r.head_sha===H&&r.conclusion==='success'&&aa.length===1&&aa[0].digest===FD,'FOCUSED');const ci=await api(`/actions/runs/${CI}`),js=await api(`/actions/runs/${CI}/jobs?per_page=100`);ok(ci.head_sha===H&&ci.conclusion==='success','CI');for(const n of ['build-test','acceptance'])ok(js.jobs.some(y=>y.name===n&&y.conclusion==='success'),'JOB');
 const e={schema_version:'geox_mcft_cap09_s2_exact_sha_r2_attestation_v1',status:'PASS',capability_line_id:'MCFT-CAP-09',slice_id:'MCFT-CAP-09.S2',subject_sha:S,merge_commit_sha:S,base_main_sha:B,candidate_pr_number:PR,candidate_head_sha:H,candidate_tree_sha:T,merge_tree_sha:T,candidate_to_merge_tree_delta:0,control_plane_merge_sha:c,control_plane_changed_files:Q,candidate_focused_workflow_run_id:FR,candidate_focused_artifact_id:FA,candidate_focused_artifact_digest:FD,standard_ci_run_id:CI,s2_effectiveness_resolution:{protected_merge_verified:true,exact_merge_subject_verified:true,candidate_tree_equals_merge_tree:true,declaration_snapshot_verified:true,repository_facts_envelope_bound:true,six_key_scope_sql_verified:true,type_aware_role_time_verified:true,open_start_closed_end_window_verified:true,read_only_transaction_verified:true,duplicate_identity_conflict_fail_closed:true,future_forcing_known_at_boundary_verified:true,real_postgresql_acceptance_pass:true,focused_workflow_pass:true,standard_ci_pass:true},effective_authority:{s0_authorization_effective:true,s1_adapter_contracts_effective:true,s2_database_evidence_ingress_effective:true,effective_status:'IN_PROGRESS',effective_next_slice:'S3',s3_registry_registration_authorized:true,s3_candidate_declaration_authorized:true,s3_candidate_declaration_requires_registry_registration:true,s3_authorized_scope:'PERSISTENT_SEQUENTIAL_SCHEDULER_ONLY',implementation_authorized:false,runtime_source_authorized:false,live_ingestion_authorized:false,background_scheduler_authorized:false,canonical_write_authorized:false,public_http_writer_authorized:false,model_activation_authorized:false,controlled_action_authorized:false},retention_contract:{level:'R2',days:730,upload_readback_required:true,locked_version_delete_denied_required:true},first_legal_next_action:'MCFT_CAP_09_S3_REGISTRY_REGISTATION',postmerge_ssot_writeback:false,nonclaims:['NO_S3_IMPLEMENTATION_BEFORE_REGISTRY_AND_CANDIDATE','NO_LIVE_DEVICE_GATEWAY','NO_BACKGROUND_SCHEDULER_YET','NO_CANONICAL_WRITE','NO_MODEL_ACTIVATION','NO_CONTROLLED_ACTION','NO_MCFT_CAR_09_COMPLETION']};const semantic={...e};e.semantic_artifact_digest='sha256:'+C.createHash('sha256').update(canon(semantic)).digest('hex');w('MCFT_CAP_09_S2_EXACT_SHA_ATTESTATION.json',e);console.log(JSON.stringify({status:'PASS',subject_sha:S,s2_database_evidence_ingress_effective:true,first_legal_next_action:e.first_legal_next_action},null,2))}
(async()=>{const m=process.argv[2];try{if(m==='--control-plane-candidate')ctl();else if(m==='--attest')await att();else throw Error('MODE')}catch(e){const z={status:'FAIL',mode:m||null,error:String(e.message||e)};w(m==='--attest'?'MCFT_CAP_09_S2_EXACT_SHA_ATTESTATION.json':'MCFT_CAP_09_S2_EXACT_SHA_CONTROL_PLANE_RESULT.json',z);console.error(JSON.stringify(z,null,2));process.exitCode=1}})();
