#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..');
const BASE='d676aacc7d2227609daa2ed97a6ce572e05cc754';
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_MATERIALIZER_BOUND_RUN_A_AUTHORITY_CANDIDATE_RESULT.json');
const CANDIDATE='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-MATERIALIZER-BOUND-FORMAL-RUN-A-AUTHORITY-CANDIDATE-V1.json';
const OBJECTS='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-MATERIALIZER-BOUND-RUN-A-AUTHORITY-OBJECT-SET-V1.json';
const BOUNDARY='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-MATERIALIZER-BOUND-RUN-A-AUTHORITY-BOUNDARY-V1.json';
const ISSUANCE='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-MATERIALIZER-BOUND-RUN-A-AUTHORITY-ISSUANCE-V1.json';
const WORKFLOW='.github/workflows/mcft-cap-08-s6-materializer-bound-run-a-authority-candidate.yml';
const VALIDATOR='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_MATERIALIZER_BOUND_RUN_A_AUTHORITY_CANDIDATE_V1.cjs';
const CHANGED=[WORKFLOW,CANDIDATE,BOUNDARY,ISSUANCE,OBJECTS,VALIDATOR].sort();
const OP='MCFT-CAP-08-S6-FORMAL-RUN-A-20260802-REPLACEMENT-005';
const DBID='MCFT-CAP-08-S6-FORMAL-DB-A-20260802-REPLACEMENT-005';
const DBNAME='geox_mcft_cap08_s6_run_a_replacement_005_30760000005';
function git(...a){return execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim()}
function text(p){return fs.readFileSync(path.join(ROOT,p),'utf8')}
function json(p){return JSON.parse(text(p))}
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function semantic(v){const c=structuredClone(v);delete c.semantic_digest;return`sha256:${crypto.createHash('sha256').update(canonical(c)).digest('hex')}`}
function save(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n')}
function effective(candidate){const a=structuredClone(candidate);a.record_status='SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED';a.evidence_class='FINAL_FORMAL_EVIDENCE_ELIGIBLE_AFTER_TERMINAL_SUCCESS';a.expires_at='2099-08-05T14:10:00.000Z';for(const k of ['authority_effective','single_run_database_execution_authorized','database_execution_workflow_authorized','workflow_dispatch_execution_authorized','final_formal_run_execution_authorized'])a.authorization_state[k]=true;Object.assign(a,{single_run_database_execution_authorized:true,database_execution_workflow_authorized:true,workflow_dispatch_execution_authorized:true,final_formal_run_execution_authorized:true,dual_run_ci_authorized:false,cross_run_comparator_authorized:false,final_ledger_settlement_authorized:false});return a}
function dbMocks(name,overrides={}){const state={facts:11,epochs:1,visibility:11,missing:0,identity:0,runtime:{},...overrides};return{pool:{query:async()=>({rows:[{database_name:name,user_name:'geox_mcft_cap08_runner_v1'}]})},adminPool:{query:async(sql,args)=>{sql=String(sql);if(sql.includes('to_regclass'))return{rows:[{relation:String(args[0]).split('.').pop()}]};if(sql.includes('LEFT JOIN public.twin_fact_visibility_index_v1'))return{rows:[{n:state.missing}]};if(sql.includes('strpos(record_json'))return{rows:[{n:state.identity}]};if(sql.includes('FROM public.twin_fact_visibility_index_v1 WHERE'))return{rows:[{n:state.visibility}]};if(sql.includes("FROM public.twin_fact_visibility_epoch_v1 WHERE status='ACTIVE'"))return{rows:[{n:state.epochs}]};if(sql.includes('FROM public.facts'))return{rows:[{n:state.facts}]};const m=sql.match(/FROM public\.([A-Za-z0-9_]+)/);if(m)return{rows:[{n:state.runtime[m[1]]||0}]};throw new Error(`UNEXPECTED_SQL:${sql}`)}}}}
async function main(){
 const base=String(process.env.MCFT_BASE_SHA||BASE).trim();assert.equal(base,BASE);assert.equal(git('merge-base',base,'HEAD'),base);assert.equal(git('rev-list','--count',`${base}..HEAD`),'1');assert.deepEqual(git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),CHANGED);
 const c=json(CANDIDATE),o=json(OBJECTS),b=json(BOUNDARY),i=json(ISSUANCE);for(const v of [c,o,b,i])assert.equal(v.semantic_digest,semantic(v));
 assert.equal(git('rev-parse',`HEAD:${CANDIDATE}`),'d046dcae07cc737515967e9f2960f59269bb3dde');assert.equal(git('rev-parse',`HEAD:${OBJECTS}`),'089d07234a6948de8eca2191fbd91ebcc4ccf7f0');
 assert.equal(c.record_status,'FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORITY_CANDIDATE_NOT_EFFECTIVE');assert.equal(c.exact_subject_sha,BASE);assert.equal(c.operational_run_instance_id,OP);assert.equal(c.logical_database_identity.identity_id,DBID);assert.equal(c.logical_database_identity.physical_name_template,'geox_mcft_cap08_s6_run_a_replacement_005_<github_run_id>');assert.ok(Object.values(c.authorization_state).every(v=>v===false));assert.equal(c.sequence_contract.run_b_remains_blocked,true);
 assert.equal(b.base_main_sha,BASE);assert.equal(b.changed_file_count,6);assert.deepEqual([...b.changed_files].sort(),CHANGED);assert.equal(b.object_set_count,51);assert.equal(i.activation.database_execution_authorized,false);assert.equal(i.identity.operational_run_instance_id,OP);assert.equal(i.identity.logical_database_identity,DBID);
 const sets=[o.exact_control_plane_object_set,o.exact_product_object_set,o.exact_port_bundle_object_set,o.exact_harness_object_set,o.protected_invariant_object_set];assert.equal(sets.reduce((n,s)=>n+Object.keys(s).length,0),51);for(const s of sets)for(const [p,sha] of Object.entries(s))assert.equal(git('rev-parse',`HEAD:${p}`),sha,`OBJECT_BLOB:${p}`);
 const gate=require(path.join(ROOT,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs'));assert.throws(()=>gate.validateExecutionAuthorityV1(c,{exactSubjectSha:BASE,runLabel:'RUN_A',operationalRunInstanceId:OP}),/record_status|strictly equal/);
 const e=effective(c);gate.validateExecutionAuthorityV1(e,{exactSubjectSha:BASE,runLabel:'RUN_A',operationalRunInstanceId:OP});
 const identity=require(path.join(ROOT,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs'));assert.equal(identity.materializePhysicalDatabaseNameV1(e,'30760000005'),DBNAME);assert.throws(()=>identity.materializePhysicalDatabaseNameV1(e,''),/GITHUB_RUN_ID_REQUIRED/);
 const indexText=text('scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/index_v1.cjs');assert.match(indexText,/validateFactoryAuthorityV1/);assert.match(indexText,/createFreshDatabasePortV1\(\{ pool, adminPool, authority \}\)/);assert.match(indexText,/createDirectMaterializerV1\(\{ root, pool, adminPool, shared, authority \}\)/);
 const directMod=require(path.join(ROOT,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/direct_materializer_v1.cjs'));let calls=0;const spec={exact_subject_sha:BASE,run_label:'RUN_A',operational_run_instance_id:OP,formal_run_id:'candidate_preflight_005',lineage_id:null,revision_id:null};const plan={strategy:'DIRECT_PRODUCT_SERVICE_ASSEMBLY',formal_run_id:spec.formal_run_id};const port=directMod.createDirectMaterializerV1({root:ROOT,pool:{},adminPool:{},shared:{},authority:e,runProductChainV1:async()=>{calls++;return{status:'PASS'}},buildMaterializationOutputV1:async x=>x.context});assert.equal((await port.executeDirectFormalRun({spec,plan})).status,'PASS');assert.equal(calls,1);const rejected=directMod.createDirectMaterializerV1({root:ROOT,pool:{},adminPool:{},shared:{},authority:c,runProductChainV1:async()=>{calls++;return{}},buildMaterializationOutputV1:async()=>({})});await assert.rejects(()=>rejected.executeDirectFormalRun({spec,plan}),/DATABASE_EXECUTION_AUTHORITY_REQUIRED/);assert.equal(calls,1);
 process.env.GITHUB_RUN_ID='30760000005';const freshMod=require(path.join(ROOT,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/fresh_database_v1.cjs'));let m=dbMocks(DBNAME);const fresh=await freshMod.createFreshDatabasePortV1({pool:m.pool,adminPool:m.adminPool,authority:e}).assertFreshDisposable({spec});assert.equal(fresh.database_name,DBNAME);m=dbMocks('geox_mcft_cap08_s6_run_a_30760000005');await assert.rejects(()=>freshMod.createFreshDatabasePortV1({pool:m.pool,adminPool:m.adminPool,authority:e}).assertFreshDisposable({spec}),/FRESH_DISPOSABLE_DATABASE_IDENTITY_MISMATCH/);
 const wf=text(WORKFLOW);assert.doesNotMatch(wf,/workflow_dispatch|postgres:|psql|DATABASE_URL/);assert.match(wf,/51-object set/);
 const result={schema_version:'geox_mcft_cap08_s6_materializer_bound_run_a_authority_candidate_result_v1',status:'PASS',base_main_sha:BASE,exact_head_sha:git('rev-parse','HEAD'),object_count:51,operational_run_instance_id:OP,logical_database_identity:DBID,candidate_runtime_gate_eligible:false,authority_bound_database_identity_preflight:'PASS',materializer_authority_binding_preflight:'PASS',database_execution_performed:false,workflow_dispatch_performed:false,run_b_dispatch_authorized:false};save(result);console.log(JSON.stringify(result,null,2));
}
main().catch(error=>{save({schema_version:'geox_mcft_cap08_s6_materializer_bound_run_a_authority_candidate_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1});
