// scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_04_S9_CLOSURE_ACTIVATION.cjs
// Purpose: validate the governance-only S9 closure activation freeze, exact boundaries, S8 effectiveness, pending claims, preserved nonclaims, and downstream blocks.
// Boundary: no Runtime source, persistence source, migration, route, scheduler, web, workflow, completion claim activation, S10 activation, or MCFT-CAP-05 authorization.
'use strict';
const cp=require('node:child_process'); const fs=require('node:fs'); const path=require('node:path');
const ROOT=path.resolve(__dirname,'../..'); const BASE='235c832d302a1917dbd557ba0adfe15587a44f50'; const S8='MCFT-CAP-04.MCFT-03-04-07-09-10.RESTART-BACKFILL-FAILURE-RECOVERY-V1'; const S9='MCFT-CAP-04.CLOSURE-CANDIDATE-V1'; const S10='MCFT-CAP-04.FINALIZATION-MAIN-VERIFICATION-V1'; const MODE=process.argv.includes('--postmerge')?'postmerge':'final';
const files=["docs/digital_twin/GEOX-DT-02-MCFT-IMPLEMENTATION-MAP.md","docs/digital_twin/GEOX-MCFT-VERTICAL-CAPABILITY-LINE-MATRIX.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-AUTHORIZATION-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-DELIVERY-SLICE-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-S8-RESTART-BACKFILL-RECOVERY-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE-STATUS.json","docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE.md","scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_04_S9_CLOSURE_ACTIVATION.cjs"]; const claims=["MCFT_CAP_04_COMPLETE","SUCCESSFUL_72_HOUR_FORECAST_RUNTIME_ESTABLISHED","EXACT_72_POINT_FORECAST_HORIZON_ESTABLISHED","FORECAST_T_PLUS_1_TO_T_PLUS_72_TIME_CONTRACT_ESTABLISHED","JOINT_FORECAST_FORCING_CYCLE_PAIR_SELECTION_ESTABLISHED","FORECAST_FUTURE_FORCING_TRACE_ESTABLISHED","FORECAST_NO_FUTURE_OBSERVATION_LEAKAGE_ESTABLISHED","FORECAST_ADDITIVE_UNCERTAINTY_PROPAGATION_ESTABLISHED","FORECAST_95_PERCENT_INTERVAL_TRACE_ESTABLISHED","FORECAST_PHYSICAL_BOUND_TRACE_ESTABLISHED","A1_COMPLETED_CANONICAL_PERSISTENCE_ESTABLISHED","A2_BLOCKED_FORECAST_DEGRADED_PATH_ESTABLISHED","A1_A2_CROSS_VARIANT_TERMINAL_UNIQUENESS_ESTABLISHED","THREE_FIXED_IRRIGATION_SCENARIOS_ESTABLISHED","NO_ACTION_SCENARIO_BASELINE_EQUIVALENCE_ESTABLISHED","IRRIGATE_NOW_15MM_SCENARIO_ESTABLISHED","IRRIGATE_NOW_25MM_SCENARIO_ESTABLISHED","SCENARIO_RESOURCE_AND_STRESS_SUMMARY_ESTABLISHED","SCENARIO_SET_CANONICAL_PERSISTENCE_ESTABLISHED","FORECAST_SCENARIO_IDEMPOTENCY_ESTABLISHED","MISSING_SCENARIO_RECOVERY_BARRIER_ESTABLISHED","TWENTY_FOUR_FORECAST_SCENARIO_TICKS_PERSISTED","FORECAST_SCENARIO_RESTART_BACKFILL_PROVEN","VERSIONED_CAP_04_RECORD_SET_COMPATIBILITY_ESTABLISHED"]; const nonclaims=["NO_MCFT_CAP_04_COMPLETE_CLAIM","NO_FORECAST_RESIDUAL","NO_FULL_MCFT_10_FIVE_SCENARIO_CLOSURE","NO_RECOMMENDATION","NO_POLICY_EVALUATION","NO_HUMAN_DECISION","NO_APPROVAL","NO_ACTION_PLAN","NO_AO_ACT","NO_DISPATCH","NO_EXECUTION_RECEIPT","NO_OUTCOME_EVIDENCE","NO_CALIBRATION_CANDIDATE","NO_SHADOW_EVALUATION","NO_MODEL_ACTIVATION","NO_ACTIVE_MODEL_PARAMETER_CHANGE","NO_CALIBRATED_FORECAST_PROBABILITY","NO_CALIBRATED_STRESS_PROBABILITY","NO_WEATHER_ENSEMBLE_UNCERTAINTY","NO_SCENARIO_ACTION_COMPLIANCE_PROBABILITY","NO_FIELD_CALIBRATED_SCENARIO_APPLICATION_EFFICIENCY","NO_FIELD_CALIBRATED_STRESS_THRESHOLD","NO_LATE_EVIDENCE_REVISION","NO_AUTOMATIC_RECOMPUTE_ON_LATE_EVIDENCE","NO_CONTINUOUS_RUNTIME","NO_CONTINUOUS_SCHEDULER","NO_SHADOW_ONLINE_CLAIM","NO_LIVE_FIELD_CLAIM","NO_MCFT_GATE_A_CLOSURE","NO_MCFT_GATE_B_CLOSURE","NO_MCFT_GATE_C_CLOSURE","NO_MINIMUM_COMPLETE_FIELD_TWIN_CLAIM"]; let pass=0,fail=0;
const check=(v,m)=>{if(v){pass++;console.log('PASS '+m)}else{fail++;console.error('FAIL '+m)}}; const git=a=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim(); const j=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8')); const exact=(a,b,m)=>check(JSON.stringify([...(a||[])].sort())===JSON.stringify([...b].sort()),m);
for(const f of files) check(fs.existsSync(path.join(ROOT,f)),'file exists '+f);
const auth=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-AUTHORIZATION-STATUS.json'); const d=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-DELIVERY-SLICE-STATUS.json'); const s8s=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-S8-RESTART-BACKFILL-RECOVERY-STATUS.json'); const c=j('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-CLOSURE-STATUS.json'); const s8=d.slices.find(x=>x.delivery_slice_id===S8); const s9=d.slices.find(x=>x.delivery_slice_id===S9); const s10=d.slices.find(x=>x.delivery_slice_id===S10);
check(auth.active_delivery_slice_id===S9,'auth active S9'); check(auth.runtime_source_authorized===false,'Runtime source unauthorized'); check(auth.s8_effectiveness?.merge_commit===BASE,'S8 merge exact'); check(auth.s8_effectiveness?.postmerge_workflow_run===29255291485,'S8 Gate run exact');
check(s8?.status==='MERGED_EFFECTIVE','S8 merged-effective'); check(s8?.effectiveness_condition_satisfied===true,'S8 effectiveness satisfied'); check(s8s.status==='MERGED_EFFECTIVE','S8 status artifact effective');
check(s9?.status==='ACTIVATION_CANDIDATE','S9 activation candidate'); check(s9?.baseline_main_commit===BASE,'S9 baseline exact'); check(s9?.runtime_source_authorized===false,'S9 governance only'); exact(s9?.pending_completion_claims,claims,'S9 pending claims exact'); exact(s9?.preserved_nonclaims,nonclaims,'S9 nonclaims exact'); exact(s9?.exact_activation_changed_file_boundary,files,'S9 activation boundary exact');
check(c.status==='ACTIVATION_CANDIDATE','closure status candidate'); check(c.closure_effective===false,'closure ineffective'); check(c.capability_status==='NOT_COMPLETE','capability not complete'); exact(c.pending_completion_claims,claims,'closure pending claims exact'); check(Array.isArray(c.effective_completion_claims)&&c.effective_completion_claims.length===0,'no effective claims'); exact(c.preserved_nonclaims,nonclaims,'closure nonclaims exact'); exact(c.exact_activation_changed_file_boundary,files,'closure activation boundary exact');
check(s10?.status==='BLOCKED','S10 blocked'); check(s10?.baseline_main_commit===null,'S10 baseline unset'); check(d.successor_authorized===false,'CAP05 unauthorized');
const tracked=git(['diff','--name-only',BASE]).split(/\r?\n/).filter(Boolean); const untracked=git(['ls-files','--others','--exclude-standard']).split(/\r?\n/).filter(Boolean); const changed=[...new Set([...tracked,...untracked])].sort(); exact(changed,files,'exact changed files');
for(const f of changed){check(!f.startsWith('apps/server/src/'),'no Runtime source '+f);check(!f.startsWith('apps/server/db/migrations/'),'no migration '+f);check(!f.startsWith('apps/web/'),'no web '+f);check(!f.startsWith('.github/workflows/'),'no workflow '+f)}
if(MODE==='postmerge'){check(git(['branch','--show-current'])==='main','postmerge on main');check(git(['rev-parse','HEAD'])===git(['rev-parse','origin/main']),'postmerge main equals origin/main')}
console.log('MCFT-CAP-04 S9 closure activation '+MODE+': '+pass+' PASS, '+fail+' FAIL'); if(fail) process.exit(1);
