// scripts/governance_acceptance/ACCEPTANCE_SOIL_WATER_POTENTIAL_SCHEMA_MIGRATION_V1.cjs
const fs=require('node:fs'); const path=require('node:path'); const {Pool}=require('pg');
const NAME='ACCEPTANCE_SOIL_WATER_POTENTIAL_SCHEMA_MIGRATION_V1';
function fail(m,d){ console.error(`[${NAME}] FAIL: ${m}`, d||''); process.exit(1);} function assert(c,m,d){ if(!c) fail(m,d); }
const migrationPath=path.join(process.cwd(),'apps/server/db/migrations/2026_06_21_soil_water_potential_foundation_v1.sql');
const required={soil_hydraulic_profile_index_v1:['profile_id','tenant_id','project_id','group_id','field_id','zone_id','layer_depth_cm','texture_class','theta_r','theta_s','alpha_per_kpa','n','m','parameter_source','calibration_status','confidence_level','confidence_score','evidence_refs_json','source_fact_id','created_at','updated_at'],soil_water_potential_estimate_index_v1:['estimate_id','tenant_id','project_id','group_id','field_id','zone_id','layer_depth_cm','source_window_id','source_profile_id','observed_theta','theta_unit','normalized_theta_m3_m3','matric_potential_kpa','matric_potential_class','available_water_fraction','root_zone_weight','input_status','blocking_reasons_json','hydraulic_profile_ref','data_quality_ref','evidence_refs_json','calculation_inputs_json','derivation_json','confidence_json','determinism_hash','source_fact_id','computed_at','updated_at']};
(async()=>{ assert(fs.existsSync(migrationPath),'migration file exists'); const sql=fs.readFileSync(migrationPath,'utf8');
for(const t of Object.keys(required)) assert(sql.includes(`CREATE TABLE IF NOT EXISTS public.${t}`),`migration creates ${t}`);
for(const idx of ['idx_soil_hydraulic_profile_index_v1_scope_latest','idx_soil_hydraulic_profile_index_v1_field','idx_soil_water_potential_estimate_index_v1_scope_latest','idx_soil_water_potential_estimate_index_v1_window','idx_soil_water_potential_estimate_index_v1_profile']) assert(sql.includes(idx),'required index missing from SQL '+idx);
const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(url,'DATABASE_URL/POSTGRES_URL/PG_URL required'); const pool=new Pool({connectionString:url}); const client=await pool.connect();
try{ await client.query('BEGIN'); await client.query('DROP TABLE IF EXISTS public.soil_water_potential_estimate_index_v1'); await client.query('DROP TABLE IF EXISTS public.soil_hydraulic_profile_index_v1'); await client.query(sql);
for(const [table,cols] of Object.entries(required)){ const q=await client.query(`SELECT column_name,udt_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1`,[table]); const by=new Map(q.rows.map(r=>[r.column_name,r])); for(const c of cols) assert(by.has(c),`missing column ${table}.${c}`,q.rows); for(const c of cols.filter(x=>x.endsWith('_json'))){ assert(by.get(c).udt_name==='jsonb',`${table}.${c} must be JSONB`,by.get(c)); } }
const iq=await client.query(`SELECT indexname FROM pg_indexes WHERE schemaname='public' AND indexname = ANY($1::text[])`,[['idx_soil_hydraulic_profile_index_v1_scope_latest','idx_soil_hydraulic_profile_index_v1_field','idx_soil_water_potential_estimate_index_v1_scope_latest','idx_soil_water_potential_estimate_index_v1_window','idx_soil_water_potential_estimate_index_v1_profile']]); assert(iq.rows.length===5,'required indexes exist',iq.rows);
await client.query(`INSERT INTO public.soil_hydraulic_profile_index_v1(profile_id,tenant_id,project_id,group_id,field_id,zone_id,layer_depth_cm,texture_class,theta_r,theta_s,alpha_per_kpa,n,m,parameter_source,calibration_status,confidence_level,confidence_score) VALUES('swp_schema_probe','t','p','g','f','z',30,'loam',0.08,0.43,0.035,1.56,0.358974,'MANUAL','UNVERIFIED','LOW',0.1)`);
await client.query('ROLLBACK'); const c=await pool.query(`SELECT to_regclass('public.soil_hydraulic_profile_index_v1') AS hp`); assert(c.rows[0].hp==null,'rollback leaves no committed probe schema writes',c.rows[0]);
} catch(e){ try{await client.query('ROLLBACK')}catch(_){} throw e; } finally{ client.release(); await pool.end(); }
console.log(`[${NAME}] PASS`);
})().catch(e=>fail(e.message,e.stack));
