'use strict';
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=process.cwd(),BASE=process.env.MCFT_BASE_SHA||'',EXPECTED_BASE='b31b024c17b617f0e1c36010c8c3926682bd6533';
const EA4='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-LIVE-SOURCE-EXACT-HEAD-QUALIFICATION-V1.json',CONFIG='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-HADS-BDLM4-SOLAR-DISCOVERY-V1.json',PROBE='scripts/runtime_acceptance/PROBE_MCFT_CAP_09_EA4_HADS_BDLM4_SOLAR_DISCOVERY.mjs',GATE='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_EA4_HADS_BDLM4_SOLAR_DISCOVERY.cjs',WF='.github/workflows/mcft-cap-09-ea4-hads-bdlm4-solar-discovery.yml';
const EXPECT=[CONFIG,PROBE,GATE,WF].sort(),OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA4_HADS_BDLM4_SOLAR_DISCOVERY_GOVERNANCE_RESULT.json'),PINS={ea4:'791e3d24bdc862641c77ddd26778495cb8e6a7dd',config:'d6b4d1703085bdddddb95b0d806d7a9b7e987883',probe:'5ba890c8fe4693b128625c874298965f8049291e'};
const git=(...args)=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8'}).trim(),blob=(ref,file)=>git('rev-parse',`${ref}:${file}`),read=(file)=>fs.readFileSync(path.join(ROOT,file),'utf8'),json=(file)=>JSON.parse(read(file)),req=(ok,code)=>{if(!ok)throw new Error(code)};
const result={schema_version:'geox_mcft_cap09_ea4_hads_bdlm4_solar_discovery_governance_v1',status:'FAIL',base_sha:BASE,database_write_count:0,formal_evidence_write_count:0,formal_window_started:false};
try{
 req(BASE===EXPECTED_BASE,`EA4HADS_BASE_MAIN_DRIFT:${BASE}`);const changed=git('diff','--name-only',`${BASE}...HEAD`).split(/\r?\n/).filter(Boolean).sort();Object.assign(result,{changed_files:changed,exact_file_count:changed.length});req(JSON.stringify(changed)===JSON.stringify(EXPECT),`EA4HADS_EXACT_FOUR_FILE_BOUNDARY_FAIL:${JSON.stringify(changed)}`);req(blob(BASE,EA4)===PINS.ea4,'EA4HADS_EA4_REJECTION_DRIFT');req(blob('HEAD',CONFIG)===PINS.config,'EA4HADS_CONFIG_BLOB_DRIFT');req(blob('HEAD',PROBE)===PINS.probe,'EA4HADS_PROBE_BLOB_DRIFT');
 const ea4=json(EA4),config=json(CONFIG),probe=read(PROBE),workflow=read(WF);req(ea4.live_qualification?.current_result==='REJECTED_EA4_KBS_RAW_HOURLY_FRESHNESS_AUTHORITY'&&ea4.authority_effect?.new_source_architecture_adjudication_required_before_ea5===true&&ea4.authority_effect?.ea5_candidate_development_authorized===false,'EA4HADS_PREDECESSOR_BOUNDARY_DRIFT');req(config.record_status==='SOURCE_DISCOVERY_ONLY_NOT_AUTHORITY'&&config.base_main_sha===BASE&&config.provider==='NOAA_NWS_HADS','EA4HADS_CONFIG_IDENTITY_DRIFT');const s=config.station_candidate;req(s.nwsl_id==='BDLM4'&&s.nesdis_id==='080010B4'&&s.rw_shef_code==='RW'&&s.rw_unit==='W_M2'&&s.rw_data_interval_minutes===60&&s.transmit_interval_minutes===60,'EA4HADS_STATION_OR_RW_METADATA_DRIFT');req(config.quality_boundary.provider_declares_values_provisional===true&&config.quality_boundary.provider_quality_checked_claimed===false&&config.quality_boundary.field_or_kbs_equivalence_claimed===false&&config.quality_boundary.source_authority_created===false,'EA4HADS_QUALITY_BOUNDARY_WEAKENED');for(const key of ['solar_source_authority_created','source_substitution_authorized','spatial_representativeness_authority_created','ea5_authorized','database_write_authorized','formal_evidence_write_authorized','formal_window_started','mcft_cap09_completed'])req(config.discovery_effect[key]===false,`EA4HADS_EFFECT_OVERCLAIM:${key}`);
 const compact=probe.replace(/\s+/g,'');for(const token of ['fetchRaw','retain(body,identity)','EA4HADS_RAW_RETENTION_DIGEST_MISMATCH','BDLM4','080010B4','RW','DATA VALUES ARE PROVISIONAL','haversineKm','raw_numeric_values_emitted:false','solar_qualified:false','source_authority_created:false','ea5_authorized:false'])req(compact.includes(token.replace(/\s+/g,'')),`EA4HADS_PROBE_TOKEN_MISSING:${token}`);req(probe.indexOf('decodedReceipt=retain')<probe.indexOf('const decodedHtml=decodedRaw.body.toString'),'EA4HADS_DECODE_BEFORE_RETENTION_FORBIDDEN');req(!/DATABASE_URL|POSTGRES(?:QL)?|NEON_DATABASE_URL|psql\b|INSERT\s+INTO|public\.facts/.test(probe),'EA4HADS_WRITE_SURFACE_FORBIDDEN');req(workflow.includes('persist-credentials: false')&&workflow.includes('node-version: 20.11.1'),'EA4HADS_WORKFLOW_NODE_OR_CREDENTIAL_DRIFT');req(workflow.includes('MCFT_BASE_SHA')&&workflow.includes('MCFT_SUBJECT_SHA'),'EA4HADS_WORKFLOW_EXACT_SHA_MISSING');req(!/DATABASE_URL|POSTGRES(?:QL)?|NEON_DATABASE_URL/.test(workflow),'EA4HADS_WORKFLOW_DATABASE_SECRET_FORBIDDEN');Object.assign(result,{status:'PASS',discovery_only:true,solar_source_authority_created:false,spatial_authority_created:false,ea5_authorized:false});
}catch(error){result.error=`${error.name||'Error'}:${error.message||String(error)}`;process.exitCode=1}fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');if(result.status==='PASS')console.log(JSON.stringify(result));else console.error(result.error);
