#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),P=require('node:child_process'),F=require('node:fs'),X=require('node:path');
const R=X.resolve(__dirname,'../..'),D='docs/digital_twin/mcft/cap_08',Q=X.join(R,'acceptance-output/MCFT_CAP_08_S6_RUN_A_QUALIFICATION_PORT_BINDING_CORRECTION_RESULT.json');
const p={i:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-V3-PORT-BINDING-INCOMPATIBILITY-V1.json`,c:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-PORT-BINDING-CORRECTION-V1.json`,b:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-PORT-BINDING-CORRECTION-BOUNDARY-V1.json`,v3:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-REPLACEMENT-EXECUTION-AUTHORITY-V3.json`,d:'scripts/runtime_acceptance/mcft_cap08_s6_run_a_qualification_ports/direct_materializer_v1.cjs',x:'scripts/runtime_acceptance/mcft_cap08_s6_run_a_qualification_ports/index_v1.cjs',old:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/direct_materializer_v1.cjs',ad:'scripts/runtime_acceptance/mcft_cap08_s6_run_a_qualification/qualification_materializer_adapter_v1.cjs',successor:`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-BOOTSTRAP-FRESHNESS-CORRECTION-BOUNDARY-V1.json`,fresh:'scripts/runtime_acceptance/mcft_cap08_s6_run_a_qualification_ports/fresh_database_v1.cjs',formalFresh:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/fresh_database_v1.cjs'};
const read=x=>JSON.parse(F.readFileSync(X.join(R,x),'utf8')),txt=x=>F.readFileSync(X.join(R,x),'utf8'),git=(...a)=>P.execFileSync('git',a,{cwd:R,encoding:'utf8'}).trim(),canon=v=>Array.isArray(v)?`[${v.map(canon).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`:JSON.stringify(v);
const sd=v=>{const x=structuredClone(v);delete x.semantic_digest;return`sha256:${C.createHash('sha256').update(canon(x)).digest('hex')}`},out=v=>{F.mkdirSync(X.dirname(Q),{recursive:true});F.writeFileSync(Q,JSON.stringify(v,null,2)+'\n')};
(async()=>{try{
 if(F.existsSync(X.join(R,p.successor))){
  const s=read(p.successor),base=s.base_main_sha;
  if(s.record_status==='RUN_A_QUALIFICATION_BOOTSTRAP_FRESHNESS_CORRECTION_BOUNDARY'&&git('merge-base',base,'HEAD')===base){
   A.equal(s.semantic_digest,sd(s));A.equal(git('diff','--check',`${base}...HEAD`),'');
   const ch=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();A.deepEqual(ch,[...s.changed_files].sort());A.equal(ch.length,8);
   A.equal(git('rev-parse',`HEAD:${p.fresh}`),'6850c56a45b123481e11f9335bbbb582aac09651');A.equal(git('rev-parse',`HEAD:${p.x}`),'257e8b8a0aabe05b92d94106dcb887a8de095d0e');A.equal(git('rev-parse',`HEAD:${p.formalFresh}`),'95d6d2e7179df06aa728df4a4fde0ab7fc2a788c');
   const r={schema_version:'geox_mcft_cap08_s6_run_a_qualification_port_binding_correction_result_v1',status:'PASS',classification:'SUCCESSOR_BOOTSTRAP_FRESHNESS_CORRECTION',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:8,qualification_port_bundle_blob_sha:'257e8b8a0aabe05b92d94106dcb887a8de095d0e',database_execution_performed:false,workflow_dispatch_performed:false,run_a_qualification_completed:false};out(r);console.log(JSON.stringify(r,null,2));return;
  }
 }
 const i=read(p.i),c=read(p.c),b=read(p.b),v3=read(p.v3),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha);
 A.equal(base,b.base_main_sha);A.equal(git('merge-base',base,'HEAD'),base);A.equal(git('diff','--check',`${base}...HEAD`),'');
 const ch=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();A.deepEqual(ch,[...b.changed_files].sort());A.equal(ch.length,7);for(const z of[i,c,b])A.equal(z.semantic_digest,sd(z));
 A.equal(v3.port_bundle_blob_sha,'2f574588ba3010a94e64f965bb17fc97b3b33c72');A.equal(i.disposition.v3_workflow_dispatch_authorized,false);A.equal(i.disposition.v3_operational_instance_reusable,false);
 A.equal(git('rev-parse',`${base}:${p.old}`),'69734776a265ef1a6a33fecdc0a50e5d2e366a32');A.equal(git('rev-parse',`${base}:${p.ad}`),'6142900b3e4de497b43b680e5b77f5ca40cb2633');
 A.equal(git('rev-parse',`HEAD:${p.d}`),c.correction.qualification_direct_materializer_blob_sha);A.equal(git('rev-parse',`HEAD:${p.x}`),c.correction.qualification_port_bundle_blob_sha);
 A.match(txt(p.old),/SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED/);A.match(txt(p.ad),/executeDirectFormalRun\(\{spec,plan\}\)/);A.match(txt(p.d),/SINGLE_DEVELOPMENT_QUALIFICATION_RUN_DATABASE_EXECUTION_AUTHORIZED/);A.doesNotMatch(txt(p.d),/SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED/);A.match(txt(p.x),/shared,authority\}/);
 for(const f of ch.filter(x=>x.endsWith('.cjs')))P.execFileSync(process.execPath,['--check',f],{cwd:R,stdio:'pipe'});
 const {createDirectQualificationMaterializerV1}=require(X.join(R,p.d)),a={record_status:'SINGLE_DEVELOPMENT_QUALIFICATION_RUN_DATABASE_EXECUTION_AUTHORIZED',authority_class:'DEVELOPMENT_QUALIFICATION_ONLY',evidence_class:'DEVELOPMENT_QUALIFICATION_ONLY',final_formal_run_execution_authorized:false,final_closure_eligible:false,hard_acceptance_eligible:false,exact_subject_sha:'a'.repeat(40),authorized_run_label:'RUN_A',operational_run_instance_id:'MCFT-CAP-08-S6-RUN-A-QUAL-MOCK-005'},s={exact_subject_sha:a.exact_subject_sha,run_label:'RUN_A',operational_run_instance_id:a.operational_run_instance_id,formal_run_id:'cap08_mock',lineage_id:null,revision_id:null},plan={strategy:'DIRECT_PRODUCT_SERVICE_ASSEMBLY',formal_run_id:s.formal_run_id};
 let n=0,m=0;const port=createDirectQualificationMaterializerV1({root:R,pool:{},adminPool:{},shared:{},authority:a,runProductChainV1:async()=>{n++;return{ok:true}},buildMaterializationOutputV1:z=>{m++;return{formal_run_id:z.spec.formal_run_id}}});A.equal((await port.executeDirectFormalRun({spec:s,plan})).formal_run_id,s.formal_run_id);A.equal(n,1);A.equal(m,1);
 const bad=createDirectQualificationMaterializerV1({root:R,pool:{},adminPool:{},shared:{},authority:{...a,record_status:'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED',final_formal_run_execution_authorized:true},runProductChainV1:async()=>{throw Error('MUST_NOT_RUN')},buildMaterializationOutputV1:()=>({})});await A.rejects(()=>bad.executeDirectFormalRun({spec:s,plan}));
 const r={schema_version:'geox_mcft_cap08_s6_run_a_qualification_port_binding_correction_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:7,v3_authority_rejected:true,qualification_port_bundle_blob_sha:c.correction.qualification_port_bundle_blob_sha,mock_materializer_contract_pass:true,final_formal_authority_fabrication_used:false,database_execution_performed:false,workflow_dispatch_performed:false,run_a_qualification_completed:false,hard_acceptance_eligible:false,mcft_cap_08_complete:false};out(r);console.log(JSON.stringify(r,null,2));
}catch(e){out({status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1}})();
