'use strict';
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=process.cwd(),BASE=process.env.MCFT_BASE_SHA||'',EXPECTED_BASE='b31b024c17b617f0e1c36010c8c3926682bd6533';
const EA1E='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA1E-KBS-TRANSIENT-ROLE-MAP-PROBE-V1.json',CFG='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-KBS-UNMAPPED-VARIATE-IDENTITY-DISCOVERY-V1.json',PROBE='scripts/runtime_acceptance/PROBE_MCFT_CAP_09_EA4_KBS_UNMAPPED_VARIATE_IDENTITY.mjs',GATE='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_EA4_KBS_UNMAPPED_VARIATE_IDENTITY.cjs',WF='.github/workflows/mcft-cap-09-ea4-kbs-unmapped-variate-identity.yml';
const EXPECT=[CFG,PROBE,GATE,WF].sort(),OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA4_KBS_UNMAPPED_VARIATE_IDENTITY_STATIC_RESULT.json');
const PINS={ea1e:'69835c9877474f4d46980487f6e5789add803df2',cfg:'0b21378b31178b30b82a3148981540a7e035dbea',probe:'ec4bacb70f7c84e2dc226810aa5cf8049f1bbe47'};
const git=(...a)=>execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim(),blob=(r,f)=>git('rev-parse',`${r}:${f}`),read=(f)=>fs.readFileSync(path.join(ROOT,f),'utf8'),json=(f)=>JSON.parse(read(f)),req=(ok,c)=>{if(!ok)throw new Error(c)};
const result={schema_version:'geox_mcft_cap09_ea4_kbs_unmapped_variate_identity_static_v1',status:'FAIL',base_sha:BASE,database_write_count:0,formal_evidence_write_count:0,formal_window_started:false};
try{
 req(BASE===EXPECTED_BASE,`EA4UV_BASE_DRIFT:${BASE}`);const changed=git('diff','--name-only',`${BASE}...HEAD`).split(/\r?\n/).filter(Boolean).sort();Object.assign(result,{changed_files:changed,exact_file_count:changed.length});req(JSON.stringify(changed)===JSON.stringify(EXPECT),`EA4UV_EXACT_FOUR_FILE_BOUNDARY:${JSON.stringify(changed)}`);
 req(blob(BASE,EA1E)===PINS.ea1e,'EA4UV_EA1E_BLOB_DRIFT');req(blob('HEAD',CFG)===PINS.cfg,'EA4UV_CONFIG_BLOB_DRIFT');req(blob('HEAD',PROBE)===PINS.probe,'EA4UV_PROBE_BLOB_DRIFT');const cfg=json(CFG),probe=read(PROBE),wf=read(WF);
 req(cfg.record_status==='DISCOVERY_ONLY_NOT_SOURCE_AUTHORITY'&&cfg.base_main_sha===BASE&&cfg.ea1e_authority_blob_sha===PINS.ea1e,'EA4UV_CONFIG_AUTHORITY_DRIFT');req(JSON.stringify(cfg.unmapped_high_frequency_endpoint_ids)===JSON.stringify([23,52]),'EA4UV_UNMAPPED_ENDPOINT_SET_DRIFT');req(JSON.stringify(cfg.resolved_endpoint_ids)===JSON.stringify([19,21,22,25,55,57]),'EA4UV_RESOLVED_ENDPOINT_SET_DRIFT');req(cfg.diagnostic_timezone?.name==='America/Detroit'&&cfg.diagnostic_timezone?.is_time_authority===false,'EA4UV_TIMEZONE_OVERCLAIM');
 req(cfg.matching_policy?.numeric_sensor_values_may_exist_only_in_process_memory===true&&cfg.matching_policy?.raw_json_body_may_not_be_persisted===true&&cfg.matching_policy?.rendered_dom_may_not_be_persisted===true,'EA4UV_DATA_MINIMIZATION_DRIFT');for(const k of ['solar_source_authority_created','rainfall_source_authority_created','timezone_authority_created','source_substitution_authorized','ea5_authorized','database_write_authorized','formal_evidence_write_authorized','formal_window_started','mcft_cap09_completed'])req(cfg.authority_effect?.[k]===false,`EA4UV_EFFECT_OVERCLAIM:${k}`);
 for(const tok of ['unmapped_high_frequency_endpoint_ids','PRECIPITATION_AGGREGATES','MAX_GUST_10M_LAST_HOUR','RAIN_SUM_LOCAL_CALENDAR_WINDOWS_MM_TO_INCH_V1','GUST_MAX_LAST_60M_MPS_TO_MPH_V1','raw_numeric_sensor_values_emitted:false','rendered_numeric_values_emitted:false','solar_excluded_from_current_high_frequency_endpoint_set','source_authority_created:false','ea5_authorized:false'])req(probe.replace(/\s+/g,'').includes(tok.replace(/\s+/g,'')),`EA4UV_PROBE_TOKEN_MISSING:${tok}`);
 req(!/DATABASE_URL|POSTGRES(?:QL)?|NEON_DATABASE_URL|INSERT\s+INTO|public\.facts|psql\b/.test(probe),'EA4UV_WRITE_SURFACE_FORBIDDEN');req(wf.includes('persist-credentials: false')&&wf.includes('playwright install --with-deps chromium')&&wf.includes('MCFT_BASE_SHA')&&wf.includes('MCFT_SUBJECT_SHA'),'EA4UV_WORKFLOW_BOUNDARY_DRIFT');req(!/DATABASE_URL|POSTGRES(?:QL)?|NEON_DATABASE_URL/.test(wf),'EA4UV_WORKFLOW_DB_SECRET_FORBIDDEN');
 Object.assign(result,{status:'PASS',source_authority_created:false,solar_source_authority_created:false,timezone_authority_created:false,source_substitution_authorized:false,ea5_authorized:false});
}catch(e){result.error=`${e.name||'Error'}:${e.message||String(e)}`;process.exitCode=1}fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');if(result.status==='PASS')console.log(JSON.stringify(result));else console.error(result.error);
