#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const cp=require('node:child_process');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const ROOT=path.resolve(__dirname,'../..'),CAP='docs/digital_twin/mcft/cap_08';
const B=`${CAP}/GEOX-MCFT-CAP-08-S6-SINGLE-RUN-DATABASE-EXECUTION-WORKFLOW-BOUNDARY-V1.json`,I=`${CAP}/GEOX-MCFT-CAP-08-S6-SINGLE-RUN-DATABASE-EXECUTION-WORKFLOW-IMPLEMENTATION-V1.json`,RUNTIME='.github/workflows/mcft-cap-08-s6-single-run-database-execution.yml',FOCUSED='.github/workflows/mcft-cap-08-s6-single-run-database-execution-workflow-implementation.yml',OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_SINGLE_RUN_DATABASE_EXECUTION_WORKFLOW_IMPLEMENTATION_RESULT.json');
const {validateExecutionAuthorityV1}=require('../runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs');
function read(p){return JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));}function text(p){return fs.readFileSync(path.join(ROOT,p),'utf8');}function git(...a){return cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();}function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v);}function sd(v){const x=structuredClone(v);delete x.semantic_digest;return`sha256:${crypto.createHash('sha256').update(canonical(x)).digest('hex')}`;}function write(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n');}function expectFail(fn,pattern){try{fn();}catch(e){assert.match(e instanceof Error?e.message:String(e),pattern);return;}throw new Error(`EXPECTED_FAILURE:${pattern.source}`);}
try{
 const b=read(B),i=read(I),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim();assert.equal(base,b.base_main_sha);assert.equal(git('merge-base',base,'HEAD'),base);assert.equal(git('diff','--check',`${base}...HEAD`),'');const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(changed,[...b.changed_files].sort());assert.equal(changed.length,8);assert.equal(b.semantic_digest,sd(b));assert.equal(i.semantic_digest,sd(i));
 const exact={
  [`${CAP}/GEOX-MCFT-CAP-08-S6-SINGLE-RUN-DATABASE-EXECUTION-WORKFLOW-IMPLEMENTATION-AUTHORITY-V1.json`]:'ad4d115b08cfdab3564f742f058e7b19382a65d4',
  [`${CAP}/GEOX-MCFT-CAP-08-S6-SINGLE-RUN-DATABASE-EXECUTION-HARNESS-EFFECTIVENESS-AUTHORITY-V1.json`]:'4eddc12057ecbdb338e4070a3149d22f2820f721',
  ['scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/harness_v1.cjs']:'24398eb6928b8d1972697576fa0ab619cef8028b'
 };for(const [p,blob] of Object.entries(exact))assert.equal(git('rev-parse',`HEAD:${p}`),blob,`AUTHORITY_BLOB_DRIFT:${p}`);
 const runtime=text(RUNTIME),focused=text(FOCUSED),entry=text('scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/workflow_entrypoint_v1.ts');
 assert.match(runtime,/on:\s*\n\s*workflow_dispatch:/);assert.doesNotMatch(runtime,/pull_request:/);assert.match(runtime,/authorize-before-database:/);assert.match(runtime,/execute-one-fresh-database:/);assert.ok(runtime.indexOf('authorize-before-database:')<runtime.indexOf('execute-one-fresh-database:'));assert.ok(runtime.indexOf('Gate exact execution authority before PostgreSQL scheduling')<runtime.indexOf('services:'));assert.match(runtime,/if: needs\.authorize-before-database\.outputs\.authorized == 'true'/);assert.match(runtime,/options: \[RUN_A, RUN_B\]/);assert.match(runtime,/ref: \$\{\{ needs\.authorize-before-database\.outputs\.exact_subject_sha \}\}/);assert.match(runtime,/ACCEPTANCE_MCFT_CAP_08_PLATFORM_SECURITY_BOOTSTRAP_DB\.ts/);assert.match(runtime,/workflow_entrypoint_v1\.ts/);assert.match(runtime,/Drop disposable database/);assert.doesNotMatch(runtime,/two_run|compareRuns|finalizeLedger|mcft_cap08_s6_two_run_compare/i);
 assert.match(focused,/pull_request:/);assert.doesNotMatch(focused,/services:\s*\n\s*postgres:/);assert.doesNotMatch(focused,/ACCEPTANCE_MCFT_CAP_08_PLATFORM_SECURITY_BOOTSTRAP_DB/);
 assert.match(entry,/executeSingleRunDatabaseHarnessV1/);assert.match(entry,/port_bundle_blob_sha/);assert.match(entry,/workflow_blob_sha/);assert.match(entry,/rev-parse/);assert.match(entry,/validateCreatedPortsV1/);
 const future=new Date(Date.now()+86400000).toISOString();const valid={record_status:'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED',single_run_database_execution_authorized:true,database_execution_workflow_authorized:true,workflow_dispatch_execution_authorized:true,dual_run_ci_authorized:false,cross_run_comparator_authorized:false,final_ledger_settlement_authorized:false,exact_subject_sha:'1'.repeat(40),authorized_run_label:'RUN_A',operational_run_instance_id:'run-a-instance-0001',port_bundle_path:'scripts/runtime_acceptance/example_port_bundle_v1.ts',port_bundle_blob_sha:'2'.repeat(40),workflow_blob_sha:'3'.repeat(40),expires_at:future};const input={exactSubjectSha:'1'.repeat(40),runLabel:'RUN_A',operationalRunInstanceId:'run-a-instance-0001'};const ok=validateExecutionAuthorityV1(valid,input);assert.equal(ok.module_path,valid.port_bundle_path);expectFail(()=>validateExecutionAuthorityV1({...valid,authorized_run_label:'RUN_B'},input),/EXECUTION_AUTHORITY_RUN_LABEL/);expectFail(()=>validateExecutionAuthorityV1({...valid,expires_at:'2020-01-01T00:00:00.000Z'},input),/EXECUTION_AUTHORITY_EXPIRED/);expectFail(()=>validateExecutionAuthorityV1({...valid,workflow_dispatch_execution_authorized:false},input),/false !== true/);expectFail(()=>validateExecutionAuthorityV1({...valid,port_bundle_path:'..\/escape.ts'},input),/PORT_BUNDLE_PATH_INVALID/);
 for(const file of ['scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs','scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/workflow_port_bundle_contract_v1.cjs'])cp.execFileSync('node',['--check',file],{cwd:ROOT,stdio:'pipe'});
 const result={schema_version:'geox_mcft_cap08_s6_single_run_database_execution_workflow_implementation_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:changed.length,runtime_trigger:'WORKFLOW_DISPATCH_ONLY',authorization_job_has_postgres_service:false,postgres_job_gated_by_exact_authority:true,exactly_one_run_label_required:true,exact_subject_checkout_required:true,authority_pinned_port_bundle_required:true,workflow_blob_pin_required:true,merged_harness_entrypoint_present:true,pull_request_database_execution:false,real_database_port_bundle_implemented:false,database_execution_authorized:false,run_a_executed:false,run_b_executed:false,dual_run_ci_authorized:false,cross_run_comparator_implemented:false,finalizer_present:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};write(result);console.log(JSON.stringify(result,null,2));
}catch(e){write({schema_version:'geox_mcft_cap08_s6_single_run_database_execution_workflow_implementation_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1;}
