// scripts/governance_acceptance/ACCEPTANCE_DT_02_RUNTIME_ARCHITECTURE_FREEZE.cjs
// Purpose: validate DT-02 architecture contracts, predecessor regressions, plain artifacts, and change scope.
// Boundary: governance-only; no Twin runtime capability is implemented or claimed.
'use strict';
const fs=require('node:fs'); const path=require('node:path'); const cp=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'); const BASE='9a31f046d717def94db30e156384b35267b503d4';
const F={freeze:'docs/digital_twin/GEOX-DT-02-RUNTIME-ARCHITECTURE-FREEZE.md',adrs:'docs/digital_twin/GEOX-DT-02-ARCHITECTURE-DECISION-REGISTER.json',layers:'docs/digital_twin/GEOX-DT-02-LAYER-DEPENDENCY-CONTRACT.json',objects:'docs/digital_twin/GEOX-DT-02-CANONICAL-OBJECT-SET.json',tx:'docs/digital_twin/GEOX-DT-02-ATOMIC-TRANSACTION-MATRIX.json',modes:'docs/digital_twin/GEOX-DT-02-RUNTIME-MODE-ADAPTER-MATRIX.json',api:'docs/digital_twin/GEOX-DT-02-API-ROUTE-COMPATIBILITY-MATRIX.json',legacy:'docs/digital_twin/GEOX-DT-02-LEGACY-MIGRATION-REGISTER.md',map:'docs/digital_twin/GEOX-DT-02-MCFT-IMPLEMENTATION-MAP.md',closure:'docs/digital_twin/GEOX-DT-02-CLOSURE-RECORD.md',matrix:'docs/digital_twin/GEOX-DIGITAL-TWIN-CAPABILITY-MATRIX.json',input:'docs/digital_twin/GEOX-DT-01-DT-02-INPUT-PACKET.md',reuse:'docs/digital_twin/GEOX-DT-01-REUSE-DECISION-REGISTER.md',audit:'scripts/governance_acceptance/AUDIT_DT_01_REPOSITORY_CAPABILITIES.cjs',dt01:'scripts/governance_acceptance/ACCEPTANCE_DT_01_EXISTING_CAPABILITY_RECONCILIATION.cjs',dt00:'scripts/governance_acceptance/ACCEPTANCE_DT_00_MAINLINE_GOVERNANCE_RESET.cjs',self:'scripts/governance_acceptance/ACCEPTANCE_DT_02_RUNTIME_ARCHITECTURE_FREEZE.cjs'};
const J=[F.adrs,F.layers,F.objects,F.tx,F.modes,F.api,F.matrix]; const fail=[]; const pass=[];
function ok(m){pass.push(m);console.log('PASS: '+m)} function bad(m){fail.push(m);console.error('FAIL: '+m)}
function a(p){return path.join(ROOT,p)} function r(p){return fs.readFileSync(a(p),'utf8')} function j(p){return JSON.parse(r(p))}
function has(t,s,m){t.includes(s)?ok(m||s):bad((m||s)+' missing')} function none(t,s,m){t.includes(s)?bad((m||s)+' forbidden'):ok(m||('excludes '+s))}
function nonempty(v){return typeof v==='string'&&v.trim().length>0} function arr(v){return Array.isArray(v)&&v.length>0}
for(const p of Object.values(F)){if(!fs.existsSync(a(p)))bad('required file missing '+p);else ok('file exists '+p)} if(fail.length)done();
const P={}; for(const p of J){try{const t=r(p);if(!t.trimStart().startsWith('{'))bad('not direct object JSON '+p);P[p]=JSON.parse(t);ok('plain JSON parses '+p)}catch(e){bad('JSON parse failed '+p+': '+e.message)}} if(fail.length)done();
const artifacts=[F.freeze,F.adrs,F.layers,F.objects,F.tx,F.modes,F.api,F.legacy,F.map,F.closure].map(r).join('\n');
for(const marker of ['GZIP_BASE64_JSON','encoded_json_artifact','payload_base64','base64_payload','content-encoding: gzip'])none(artifacts,marker,'plain-artifact policy '+marker);
const A=P[F.adrs], decisions=A.decisions||[], ids=decisions.map(x=>x.id), expected=Array.from({length:16},(_,i)=>'DT02-ADR-'+String(i+1).padStart(3,'0'));
if(A.phase!=='DT-02'||A.status!=='FROZEN'||decisions.length!==16||new Set(ids).size!==16||expected.some(x=>!ids.includes(x)))bad('ADR identity/phase/status invalid');else ok('DT02-ADR-001 through 016 present and FROZEN');
for(const d of decisions){if(d.status!=='FROZEN'||!nonempty(d.decision)||!nonempty(d.rationale)||!arr(d.rejected_alternatives)||!arr(d.downstream_owners))bad(d.id+' incomplete')}
if(!decisions.some(d=>d.status!=='FROZEN'||!nonempty(d.decision)||!nonempty(d.rationale)||!arr(d.rejected_alternatives)||!arr(d.downstream_owners)))ok('all ADR bodies complete');
const topics=new Set(decisions.flatMap(d=>d.input_packet_topics||[])); for(const x of ['canonical_atomicity','layers','canonical_index_persistence','tick_transaction','checkpoint_recovery','idempotency','late_evidence','forecast_storage','scenario_storage','model_governance','api_naming','legacy_compatibility','runtime_modes','write_authority'])if(!topics.has(x))bad('unresolved input topic '+x); if(!fail.some(x=>x.startsWith('unresolved input')))ok('DT-01 Input Packet closed');
const L=P[F.layers], layerNames=new Set((L.layers||[]).map(x=>x.name)); for(const x of ['domain','runtime','persistence','adapters','routes','projections','web'])if(!layerNames.has(x))bad('layer missing '+x); const domain=(L.layers||[]).find(x=>x.name==='domain'); for(const x of ['Postgres','Fastify','wall clock','random UUID','filesystem','network'])if(!(domain?.must_not_depend_on||[]).includes(x))bad('domain prohibition missing '+x); if(!fail.some(x=>x.startsWith('layer missing')||x.startsWith('domain prohibition')))ok('layer direction and domain purity frozen');
const O=P[F.objects], rows=O.objects||[], byO=new Map(rows.map(x=>[x.object_type,x]));
for(const x of ['twin_runtime_attempt_v1','twin_runtime_tick_v1','twin_evidence_window_v1','twin_state_transition_v1','twin_assimilation_update_v1','twin_state_estimate_v1','twin_forecast_run_v1','twin_scenario_set_v1','twin_forecast_residual_v1','twin_decision_record_v1','twin_action_feedback_v1','twin_calibration_candidate_v1','twin_shadow_evaluation_v1','twin_model_activation_v1','twin_runtime_config_v1','twin_runtime_checkpoint_v1','twin_runtime_health_v1','twin_runtime_lineage_v1','twin_revision_run_v1','twin_lineage_promotion_v1'])if(!byO.has(x))bad('object missing '+x);
const sf=new Set(O.shared_semantic_envelope?.required_fields||[]); if(sf.has('fact_id'))bad('fact_id in semantic envelope');else ok('fact_id separated from semantic identity'); for(const x of ['object_id','idempotency_key','determinism_hash'])if(!sf.has(x))bad('semantic identity missing '+x);
if(byO.has('twin_prior_state_v1'))bad('canonical prior object forbidden');else ok('prior is not independent canonical State'); if(byO.get('twin_runtime_attempt_v1')?.history_class!=='OPERATIONAL_AUDIT')bad('attempt must be OPERATIONAL_AUDIT');else ok('attempt is operational audit'); if(byO.get('twin_state_estimate_v1')?.history_class!=='CANONICAL_TWIN_HISTORY')bad('posterior not canonical State');else ok('posterior is canonical State'); if(!byO.has('twin_lineage_promotion_v1'))bad('promotion authority missing');else ok('promotion authority present');
for(const x of ['twin_state_transition_v1','twin_assimilation_update_v1','twin_state_estimate_v1'])if(byO.get(x)?.transaction_family!=='A_STATE_TICK_COMMIT')bad(x+' not atomic with State Tick');
const T=P[F.tx], tx=T.transactions||[], byT=new Map(tx.map(x=>[x.id,x])), txIds=['A_STATE_TICK_COMMIT','B_SCENARIO_COMMIT','C_FORECAST_RESIDUAL_COMMIT','D_MODEL_GOVERNANCE_STEP_COMMIT','E_REVISION_PROMOTION_COMMIT','F_OPERATIONAL_ATTEMPT_HEALTH','G_HUMAN_DECISION_LINK_COMMIT','H_ACTION_FEEDBACK_COMMIT']; if(T.transaction_count!==8||tx.length!==8||txIds.some(x=>!byT.has(x)))bad('eight transaction families incomplete');else ok('eight transaction families complete');
const tick=byT.get('A_STATE_TICK_COMMIT'); for(const x of ['twin_state_transition_v1','twin_assimilation_update_v1','twin_state_estimate_v1','twin_forecast_run_v1','twin_runtime_tick_v1','twin_runtime_checkpoint_v1'])if(!(tick?.canonical_appends||[]).includes(x))bad('tick append missing '+x); if(!(tick?.projection_writes||[]).some(x=>String(x).includes('checkpoint latest CAS')))bad('checkpoint CAS missing');
const att=byT.get('F_OPERATIONAL_ATTEMPT_HEALTH'); for(const x of ['twin_state_estimate_v1','twin_runtime_tick_v1','twin_runtime_checkpoint_v1'])if((att?.canonical_appends||[]).includes(x))bad('failed attempt appends '+x); const prom=byT.get('E_REVISION_PROMOTION_COMMIT'); if(!(prom?.canonical_appends||[]).includes('twin_lineage_promotion_v1'))bad('promotion fact missing'); for(const x of ['active lineage index CAS','checkpoint latest switch','current State switch','latest Forecast switch'])if(!(prom?.projection_writes||[]).includes(x))bad('promotion switch missing '+x);
const byA=new Map(decisions.map(x=>[x.id,x])); function adrHas(id,phrases,label){const t=JSON.stringify(byA.get(id));for(const p of phrases)if(!t.includes(p))bad(label+' missing '+p)}
adrHas('DT02-ADR-004',['prior is not canonical current State','posterior is canonical State','sensor reading is Evidence, never direct State','assimilation is not calibration'],'State invariant');
adrHas('DT02-ADR-003',['canonical facts never update','indexes may upsert and must be rebuildable','operational coordination is not canonical Twin history'],'Persistence invariant');
adrHas('DT02-ADR-006',['fencing_token','CAS-update','sequentially','Failed or blocked attempts never advance checkpoint'],'Recovery invariant');
adrHas('DT02-ADR-008',['candidate','twin_lineage_promotion_v1','atomically','Superseded history remains queryable'],'Revision invariant');
adrHas('DT02-ADR-009',['exactly 72','horizons 1 through 72','zero points','t0'],'Forecast invariant');
adrHas('DT02-ADR-010',['NO_ACTION','IRRIGATE_NOW_10MM','IRRIGATE_NOW_20MM','IRRIGATE_NOW_30MM','DELAY_24H_20MM','CUSTOM_OPERATOR_OPTION is deferred','Scenario is not Recommendation'],'Scenario invariant'); if(byO.get('twin_scenario_set_v1')?.transaction_family==='A_STATE_TICK_COMMIT')bad('Scenario transaction merged with State Tick');
const API=P[F.api]; if(API.frontend_canonical_family?.prefix!=='/operator/fields/:fieldId')bad('frontend prefix invalid'); if(API.server_canonical_read_family?.prefix!=='/api/v1/operator/fields/:fieldId/runtime')bad('server prefix invalid'); if(API.frontend_canonical_family?.forbidden_parallel_family!=='/operator/twin-runtime/fields/*')bad('parallel family prohibition missing'); const routes=API.server_canonical_read_family?.routes||[]; if(routes.length!==8||routes.some(x=>x.method!=='GET'))bad('Runtime route family not eight read-only GETs'); if(!arr(API.forbidden_generated_object_writes)||!arr(API.separately_governed_human_writes))bad('API write boundary incomplete');else ok('read API and human-write separation frozen');
const M=P[F.modes]; for(const x of ['REPLAY','SHADOW_ONLINE','CONTROLLED_FIELD','PRODUCTION'])if(!(M.modes||[]).some(y=>y.mode===x))bad('mode missing '+x); for(const x of ['domain model','canonical contracts','state-transition semantics','persistence semantics','revision chain'])if(!(M.shared_core||[]).includes(x))bad('shared core missing '+x); if(!fail.some(x=>x.startsWith('mode missing')||x.startsWith('shared core')))ok('shared core and mode adapters frozen');
const C=P[F.matrix]; if(C.schema_version!=='geox_digital_twin_capability_matrix_v3'||C.phase!=='DT-02'||C.current_claim!=='RUNTIME_ARCHITECTURE_FROZEN_NO_RUNTIME_IMPLEMENTATION')bad('Capability Matrix v3 phase/claim invalid'); for(const x of ['DT-00','DT-01','DT-02'])if(!(C.governance_lineage||[]).includes(x))bad('lineage missing '+x); if(C.predecessor_evidence?.dt01_audit_baseline!=='bce918d1eea423397bdd329148b7a2e7eb181b6c')bad('DT-01 baseline lost'); const byC=new Map((C.capabilities||[]).map(x=>[x.capability_id,x])); for(const x of ['DT-MATRIX-HOURLY-TICK','DT-MATRIX-PROPAGATION','DT-MATRIX-ASSIMILATION','DT-MATRIX-POSTERIOR','DT-MATRIX-CHECKPOINT','DT-MATRIX-RESTART','DT-MATRIX-LATE-REVISION','DT-MATRIX-72H-REGEN']){const q=byC.get(x);if(!q||q.current_status!=='MISSING'||(q.evidence_refs||[]).length||(q.reuse_decisions||[]).length)bad(x+' inflated')} if(byC.get('DT-MATRIX-LIVE-PRODUCTION-FIELD-TWIN')?.current_status!=='NOT_CLAIMED')bad('live production claim inflated');else ok('missing runtime capabilities and production nonclaim preserved');
const map=r(F.map); for(let i=0;i<=18;i++){const x='MCFT-'+String(i).padStart(2,'0');if(!map.includes(x))bad('implementation map missing '+x)} const reuse=r(F.reuse), targets=[]; for(const line of reuse.split(/\r?\n/)){if(!line.trim().startsWith('| DT01-CAP-'))continue;const c=line.split('|').map(x=>x.trim()).filter(Boolean);if(c.length>=5&&c[4].includes('DT-02')){const m=c[1].match(/`([^`]+)`/);if(m)targets.push(m[1])}} if(!targets.length)bad('no target=DT-02 rows parsed'); for(const x of targets)if(!map.includes('`'+x+'`'))bad('unresolved DT-01 component '+x); if(targets.length&&!targets.some(x=>!map.includes('`'+x+'`')))ok('DT-01 target=DT-02 decisions resolved '+targets.length);
const closure=r(F.closure); has(closure,'status: PENDING_ACCEPTANCE','closure pending final validation'); has(closure,'RUNTIME_ARCHITECTURE_FROZEN_NO_RUNTIME_IMPLEMENTATION','closure non-runtime claim'); has(closure,'MCFT-00 — Reality Binding Contract','next task fixed'); has(r(F.freeze),'No runtime capability is claimed by this document.','freeze nonclaim');
try{cp.execFileSync(process.execPath,[F.audit,'--check'],{cwd:ROOT,stdio:'inherit'});ok('DT-01 audit regression')}catch(e){bad('DT-01 audit regression failed: '+e.message)}
function run(label,script,env=process.env){try{cp.execFileSync(process.execPath,[script],{cwd:ROOT,env,stdio:'inherit'});ok(label)}catch(e){bad(label+' failed: '+e.message)}} run('DT-01 acceptance regression',F.dt01); run('DT-00 semantic regression',F.dt00,{...process.env,DT00_ACCEPTANCE_SKIP_GIT_SCOPE:'1'});
try{cp.execFileSync('git',['cat-file','-e',BASE+'^{commit}'],{cwd:ROOT,stdio:'ignore'});const out=cp.execFileSync('git',['diff','--name-only',BASE+'...HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),changed=out?out.split(/\r?\n/).filter(Boolean):[],allowed=new Set([F.self,F.dt01,F.dt00]),forbidden=changed.filter(x=>!(x.startsWith('docs/digital_twin/')||allowed.has(x)));if(!changed.length)bad('no DT-02 changes');if(forbidden.length)bad('forbidden changed files '+forbidden.join(', '));else ok('changed-file boundary '+changed.length+' files')}catch(e){bad('changed-file boundary failed: '+e.message)}
done(); function done(){console.log('\nDT-02 acceptance summary: '+pass.length+' PASS, '+fail.length+' FAIL');if(fail.length)process.exit(1);console.log('DT-02 RUNTIME ARCHITECTURE FREEZE: PASS')}
