#!/usr/bin/env node
// scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_07_SLICE_EXACT_SHA_ATTESTATION.cjs
// Purpose: derive the effective MCFT-CAP-07 delivery frontier from one exact main merge SHA without repository writeback.
// Boundary: read-only Git/GitHub/repository inspection and immutable artifact generation only.
'use strict';
const assert=require('node:assert/strict');const crypto=require('node:crypto');const fs=require('node:fs');const path=require('node:path');const cp=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..');const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_07_SLICE_EXACT_SHA_ATTESTATION.json');
const git=(...a)=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();
function canonical(v){if(Array.isArray(v))return `[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return `{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v);}
const digest=(v)=>`sha256:${crypto.createHash('sha256').update(canonical(v)).digest('hex')}`;
async function api(p){const r=await fetch(`https://api.github.com${p}`,{headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'geox-mcft-cap07-attestation-v1'}});if(!r.ok)throw new Error(`GITHUB_API:${r.status}:${p}:${(await r.text()).slice(0,300)}`);return r.json();}
function parseDecl(body){const m=String(body||'').match(/<!--\s*MCFT_CANDIDATE_DECLARATION_V2\s*\n([\s\S]*?)-->/);if(!m)throw new Error('CANDIDATE_DECLARATION_MISSING');const o={};for(const raw of m[1].split(/\r?\n/)){const l=raw.trim();if(!l)continue;const i=l.indexOf('=');if(i<1)throw new Error(`DECLARATION_LINE_INVALID:${l}`);o[l.slice(0,i).trim()]=l.slice(i+1).trim();}return o;}
(async()=>{try{
 const subject=process.env.GITHUB_SHA||git('rev-parse','HEAD');const parents=git('rev-list','--parents','-n','1',subject).split(/\s+/).slice(1);if(parents.length!==2)throw new Error(`MERGE_COMMIT_TWO_PARENTS_REQUIRED:${parents.length}`);const [baseHead,candidateHead]=parents;const subjectTree=git('rev-parse',`${subject}^{tree}`);const candidateTree=git('rev-parse',`${candidateHead}^{tree}`);if(subjectTree!==candidateTree)throw new Error('CANDIDATE_TO_MERGE_TREE_DELTA_NONZERO');const repo=process.env.GITHUB_REPOSITORY;if(!repo||!process.env.GITHUB_TOKEN)throw new Error('GITHUB_CONTEXT_REQUIRED');const pulls=await api(`/repos/${repo}/commits/${candidateHead}/pulls`);const pr=pulls.find(x=>x.merged_at&&x.merge_commit_sha===subject)||pulls.find(x=>x.head?.sha===candidateHead);if(!pr)throw new Error('SOURCE_PR_NOT_FOUND');const decl=parseDecl(pr.body);if(decl.capability_line!=='MCFT-CAP-07'||decl.candidate_head!==candidateHead||decl.base_head!==baseHead)throw new Error('DECLARATION_SHA_OR_CAPABILITY_MISMATCH');const status=JSON.parse(fs.readFileSync(path.join(ROOT,decl.status_file),'utf8'));const field=decl.candidate_field.split('.').reduce((x,k)=>x&&x[k],status);const expected=JSON.parse(decl.candidate_value);assert.deepEqual(field,expected);
 const checks=await api(`/repos/${repo}/commits/${candidateHead}/check-runs?per_page=100`);const required=[decl.focused_workflow,decl.standard_workflow,'mcft-candidate-integrity-enforce-current-pr','mcft-release-lane'];const resolved={};for(const token of required){const matches=checks.check_runs.filter(x=>String(x.name).includes(token));if(!matches.length||!matches.some(x=>x.conclusion==='success'))throw new Error(`REQUIRED_CHECK_NOT_PASS:${token}`);resolved[token]=matches.filter(x=>x.conclusion==='success').map(x=>({id:x.id,name:x.name,conclusion:x.conclusion}));}
 const probe='docs/digital_twin/mcft/cap_07/testing/GEOX-MCFT-CAP-07-S0-UNREGISTERED-PROBE.json';if(fs.existsSync(path.join(ROOT,probe)))throw new Error('NEGATIVE_PROBE_PRESENT_ON_MERGED_MAIN');const artifact={schema_version:'geox_mcft_cap_07_slice_exact_sha_attestation_v1',status:'PASS',capability_line_id:'MCFT-CAP-07',slice_id:decl.slice_id,subject_commit:subject,base_head:baseHead,candidate_head:candidateHead,candidate_to_merge_tree_delta:0,source_pr_number:pr.number,required_checks:resolved,focused_acceptance_result:'PASS',predecessor_artifact_validation:status.predecessor_effective_evidence_requirement||null,committed_candidate_state:{status_file:decl.status_file,candidate_field:decl.candidate_field,candidate_value:expected},effective_delivery_frontier_projection:{effective_status:status.effective_status_when_attested||status.effective_completion_state||'IMPLEMENTED',effective_next_slice:status.effective_next_slice_when_attested||null,effective_active_delivery_slice_id:status.effective_next_slice_when_attested||null},runtime_authority_delta:status.runtime_authority_delta||'ZERO',canonical_write_authority_delta:status.canonical_write_authority_delta||'ZERO',repository_write_performed:false,postmerge_ssot_writeback_performed:false,proof_only_pr_created:false,workflow_run_id:process.env.GITHUB_RUN_ID||null,workflow_job:process.env.GITHUB_JOB||null,generated_at:new Date().toISOString()};artifact.semantic_artifact_digest=digest(artifact);fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(artifact,null,2)+'\n');console.log(`PASS ${decl.slice_id} ${subject}`);
}catch(e){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify({schema_version:'geox_mcft_cap_07_slice_exact_sha_attestation_v1',status:'FAIL',error:String(e&&e.message||e),subject_commit:process.env.GITHUB_SHA||null},null,2)+'\n');console.error(e);process.exit(1);}})();
