#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),{execFileSync:E}=require('node:child_process');
const R=P.resolve(__dirname,'../..'),B='de5e1b6aaf8138ba703bc5d2ea584e2b8a35b690',S='ce9d6b4df8c708c0d4a99bb24846e1bc44b3cf59',CH='9cda46a71efbf99070bf2382f674bff5df3a6e31';
const OP='MCFT-CAP-08-S6-FORMAL-RUN-A-20260804-REPLACEMENT-011',DB='MCFT-CAP-08-S6-FORMAL-DB-A-20260804-REPLACEMENT-011';
const W='.github/workflows/mcft-cap-08-s6-merged-main-qualified-run-a-authority-effectiveness.yml',D='docs/digital_twin/mcft/cap_08/';
const CA=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-FORMAL-RUN-A-AUTHORITY-CANDIDATE-V1.json',O=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-RUN-A-AUTHORITY-OBJECT-SET-V1.json',EA=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-FORMAL-RUN-A-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',ER=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-RUN-A-AUTHORITY-EFFECTIVENESS-V1.json',EB=D+'GEOX-MCFT-CAP-08-S6-MERGED-MAIN-QUALIFIED-RUN-A-AUTHORITY-EFFECTIVENESS-BOUNDARY-V1.json',Q=D+'GEOX-MCFT-CAP-08-S6-EXACT-PATH-DEVELOPMENT-REHEARSAL-OBJECT-SET-V1.json';
const V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_MERGED_MAIN_QUALIFIED_RUN_A_AUTHORITY_EFFECTIVENESS_V1.cjs',OUT=P.join(R,'acceptance-output/MCFT_CAP_08_S6_MERGED_MAIN_QUALIFIED_RUN_A_AUTHORITY_EFFECTIVENESS_RESULT.json'),FILES=[W,EA,ER,EB,V].sort();
const g=(...x)=>E('git',x,{cwd:R,encoding:'utf8'}).trim(),t=x=>F.readFileSync(P.join(R,x),'utf8'),j=x=>JSON.parse(t(x));
const can=x=>Array.isArray(x)?'['+x.map(can).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+can(x[k])).join(',')+'}':JSON.stringify(x);
const sem=x=>{x=structuredClone(x);delete x.semantic_digest;return'sha256:'+C.createHash('sha256').update(can(x)).digest('hex')};
const save=x=>{F.mkdirSync(P.dirname(OUT),{recursive:true});F.writeFileSync(OUT,JSON.stringify(x,null,2)+'\n')};
try{
 const base=String(process.env.MCFT_BASE_SHA||B).trim();A.equal(base,B);A.equal(g('merge-base',B,'HEAD'),B);A.equal(g('rev-list','--count',B+'..HEAD'),'1');A.equal(g('diff','--check',B+'...HEAD'),'');
 A.deepEqual(g('diff','--name-only',B+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),FILES);A.equal(g('diff','--name-only',CH+'...'+B),'');
 const e=j(EA),r=j(ER),b=j(EB),c=j(CA),o=j(O),q=j(Q);for(const x of[e,r,b,c,o,q])A.equal(x.semantic_digest,sem(x),x.schema_version);
 const blobs={effective:g('rev-parse','HEAD:'+EA),record:g('rev-parse','HEAD:'+ER),boundary:g('rev-parse','HEAD:'+EB),candidate:g('rev-parse','HEAD:'+CA),objectSet:g('rev-parse','HEAD:'+O),qualified:g('rev-parse','HEAD:'+Q)};
 A.equal(blobs.effective,'fe55502277682e8a3e5cbf87ba97feb3f94988b0');A.equal(blobs.record,'3e3d3e3c307cadb140baa2fb9a235ee10e1855be');A.equal(blobs.boundary,'79feeabc5f2c6e0fd93689526e8c19f67142da3d');
 A.equal(blobs.candidate,'ea8bf226434dfe19edd7b6abc4f67abf08a0af92');A.equal(blobs.objectSet,'f33475ad41c49fa348d8e52b1e0e0e60dc2bf8bd');A.equal(g('rev-parse',CH+':'+CA),blobs.candidate);A.equal(g('rev-parse',B+':'+CA),blobs.candidate);
 A.equal(q.object_count,56);const sets=[q.exact_control_plane_object_set,q.exact_database_bootstrap_object_set,q.exact_product_object_set,q.exact_port_bundle_object_set,q.exact_harness_object_set,q.protected_invariant_object_set];A.equal(sets.reduce((n,x)=>n+Object.keys(x).length,0),56);
 for(const set of sets)for(const[p,sha]of Object.entries(set))for(const ref of[S,CH,B,'HEAD'])A.equal(g('rev-parse',ref+':'+p),sha,'EXECUTION_BLOB:'+ref+':'+p);
 A.equal(e.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED');A.equal(e.authority_class,'FINAL_FORMAL_RUN_ONLY');A.equal(e.evidence_class,'FINAL_FORMAL_EVIDENCE_ELIGIBLE_AFTER_TERMINAL_SUCCESS');A.equal(e.exact_subject_sha,S);A.equal(e.authorized_run_label,'RUN_A');A.equal(e.operational_run_instance_id,OP);A.equal(e.logical_database_identity.identity_id,DB);A.equal(e.logical_database_identity.reusable,false);A.equal(e.candidate_head_sha,CH);A.equal(e.candidate_merge_sha,B);A.equal(e.candidate_to_merge_file_delta,0);A.equal(e.candidate_authority_ref.blob_sha,blobs.candidate);A.equal(e.object_set_manifest_ref.blob_sha,blobs.objectSet);A.equal(e.object_set_manifest_ref.object_count,56);
 A.equal(e.single_use_contract.max_dispatch_count,1);A.equal(e.single_use_contract.github_run_attempt_required,1);A.equal(e.single_use_contract.rerun_authorized,false);A.equal(e.sequence_contract.run_b_remains_blocked,true);A.equal(e.database_execution_performed,false);A.equal(e.workflow_dispatch_performed,false);A.equal(e.formal_run_executed,false);
 A.equal(r.production_gate_eligible,true);A.equal(r.explicit_dispatch_approval_required,true);A.equal(r.database_execution_performed,false);A.equal(r.workflow_dispatch_performed,false);A.equal(r.effective_authority.blob_sha,blobs.effective);A.equal(r.candidate_to_merge_file_delta,0);A.equal(r.candidate_to_merge_execution_object_delta,0);
 A.equal(b.changed_file_count,5);A.deepEqual([...b.changed_files].sort(),FILES);A.equal(b.effective_authority_blob_sha,blobs.effective);A.equal(b.effectiveness_record_blob_sha,blobs.record);A.equal(b.production_gate_eligible,true);A.equal(b.explicit_dispatch_approval_required,true);A.equal(b.database_execution_performed,false);A.equal(b.workflow_dispatch_performed,false);
 const gate=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs')),input={exactSubjectSha:S,runLabel:'RUN_A',operationalRunInstanceId:OP};
 gate.validateExecutionAuthorityV1(e,input);A.throws(()=>gate.validateExecutionAuthorityV1(c,input),/SINGLE_RUN_DATABASE_EXECUTION_REQUIRED|EXECUTION_AUTHORITY_RECORD_STATUS/);
 const id=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs'));A.equal(id.materializePhysicalDatabaseNameV1(e,'30860000011'),'geox_mcft_cap08_s6_run_a_replacement_011_30860000011');
 const wf=t(W);A.doesNotMatch(wf,/workflow_dispatch:|postgres:|psql|DATABASE_URL/i);A.match(wf,/Validate REPLACEMENT-011 RUN_A authority effectiveness/);
 const result={schema_version:'geox_mcft_cap08_s6_merged_main_qualified_run_a_authority_effectiveness_result_v1',status:'PASS',base_main_sha:B,exact_head_sha:g('rev-parse','HEAD'),exact_subject_sha:S,candidate_head_sha:CH,candidate_merge_sha:B,candidate_to_merge_file_delta:0,candidate_to_merge_execution_object_delta:0,object_count:56,effective_authority_blob_sha:blobs.effective,operational_run_instance_id:OP,logical_database_identity:DB,production_gate_eligible:true,database_execution_performed:false,workflow_dispatch_performed:false,explicit_dispatch_approval_required:true,run_b_dispatch_authorized:false};save(result);console.log(JSON.stringify(result,null,2));
}catch(error){save({schema_version:'geox_mcft_cap08_s6_merged_main_qualified_run_a_authority_effectiveness_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1}
