#!/usr/bin/env node
'use strict';
const fs=require('fs');const path=require('path');const{execFileSync}=require('child_process');
const ROOT=path.resolve(__dirname,'../..');
const CONFIG_PATH=path.join(ROOT,'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-T4R1-PERSISTENT-LIFECYCLE-QUALIFICATION-V1.json');
const PROBE_PATH=path.join(ROOT,'scripts/runtime_acceptance/PROBE_MCFT_CAP_09_T4R1_PERSISTENT_LIFECYCLE_QUALIFICATION.mjs');
const OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_T4R1_PERSISTENT_LIFECYCLE_QUALIFICATION_GOVERNANCE_RESULT.json');
const BASE_SHA=String(process.env.MCFT_BASE_SHA||'').trim();const SUBJECT_SHA=String(process.env.MCFT_SUBJECT_SHA||'').trim();
const EXPECTED_BASE='60b15c11aaaf9772083af6451b24b7bfb1e68fc9';const DAY_MS=86400000;
const EXPECTED_FILES=['.github/workflows/mcft-cap-09-t4r1-crop-only-geometry.yml','.github/workflows/mcft-cap-09-t4r1-persistent-lifecycle-qualification.yml','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-T4R1-CROP-ONLY-GEOMETRY-AUTHORITY-V1.json','docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-T4R1-PERSISTENT-LIFECYCLE-QUALIFICATION-V1.json','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_T4R1_CROP_ONLY_GEOMETRY.cjs','scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_T4R1_PERSISTENT_LIFECYCLE_QUALIFICATION.cjs','scripts/runtime_acceptance/PROBE_MCFT_CAP_09_T4R1_CROP_ONLY_GEOMETRY.mjs','scripts/runtime_acceptance/PROBE_MCFT_CAP_09_T4R1_PERSISTENT_LIFECYCLE_QUALIFICATION.mjs'].sort();
const assert=(c,m)=>{if(!c)throw new Error(m)};const git=a=>execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();
function write(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n');console.log(JSON.stringify(v));}
try{
 assert(/^[0-9a-f]{40}$/.test(BASE_SHA),'T4R1_GOV_BASE_REQUIRED');assert(/^[0-9a-f]{40}$/.test(SUBJECT_SHA),'T4R1_GOV_SUBJECT_REQUIRED');assert(BASE_SHA===EXPECTED_BASE,`T4R1_GOV_EXACT_MAIN_DRIFT:${BASE_SHA}`);
 const changed=git(['diff','--name-only',`${BASE_SHA}..${SUBJECT_SHA}`]).split(/\r?\n/).filter(Boolean).sort();assert(JSON.stringify(changed)===JSON.stringify(EXPECTED_FILES),`T4R1_GOV_EXACT_EIGHT_FILE_BOUNDARY:${changed.join(',')}`);
 const x=JSON.parse(fs.readFileSync(CONFIG_PATH,'utf8'));assert(x.schema_version==='geox_mcft_cap09_t4r1_persistent_lifecycle_qualification_v1','T4R1_GOV_SCHEMA');assert(x.record_status==='EXACT_PROTECTED_MAIN_ADOPTION_CANDIDATE','T4R1_GOV_RECORD_STATUS');assert(x.frontier==='T4R1_CURRENT_SEASON_PERSISTENT_LIFECYCLE_QUALIFICATION','T4R1_GOV_FRONTIER');assert(x.exact_predecessor_sha===EXPECTED_BASE,'T4R1_GOV_PREDECESSOR');assert(x.effectiveness_rule.includes('AMENDMENT_16_IS_EFFECTIVE_ON_EXACT_PROTECTED_MAIN_BASE'),'T4R1_GOV_EFFECTIVENESS');
 const p=x.authority_predecessors;assert(git(['rev-parse',`${BASE_SHA}:${p.amendment_16_path}`])===p.amendment_16_blob_sha,'T4R1_GOV_AMENDMENT16_PIN');assert(git(['rev-parse',`${BASE_SHA}:${p.persistent_semantics_path}`])===p.persistent_semantics_blob_sha,'T4R1_GOV_SEMANTICS_PIN');assert(git(['rev-parse',`${BASE_SHA}:${p.ea1j_formal_crop_context_path}`])===p.ea1j_formal_crop_context_blob_sha,'T4R1_GOV_EA1J_PIN');
 const sem=JSON.parse(git(['show',`${BASE_SHA}:${p.persistent_semantics_path}`]));assert(sem.normative_principles?.season_lifecycle_is_persistent_state===true,'T4R1_GOV_PERSISTENT_STATE');assert(sem.normative_principles?.provider_silence_is_lifecycle_evidence===false,'T4R1_GOV_SILENCE_FORBIDDEN');assert(sem.horizon_policy?.horizon_may_only_truncate_persistence===true&&sem.horizon_policy?.horizon_may_create_active===false,'T4R1_GOV_HORIZON_ASYMMETRY');
 assert(x.candidate_scope?.treatment==='T4'&&x.candidate_scope?.replicate==='R1'&&x.candidate_scope?.provider_area_identity==='T4R1','T4R1_GOV_SCOPE');assert(x.candidate_scope?.crop==='corn'&&x.candidate_scope?.hybrid_product_code==='43-96P','T4R1_GOV_CROP');assert(x.establishment_source?.expected_observation_id===6974&&x.candidate_scope?.planting_local_date==='2026-05-27','T4R1_GOV_ESTABLISHMENT');
 const s=x.transition_sweep;assert(s?.provider==='KBS_AGLOG_CURRENT_OBSERVATION_INDEX_AND_DETAIL','T4R1_GOV_PROVIDER');assert(s?.detail_field_contract?.whole_page_body_semantic_classification_forbidden===true,'T4R1_GOV_WHOLE_BODY_FORBIDDEN');assert(s?.detail_field_contract?.index_detail_date_agreement_required===true&&s?.detail_field_contract?.index_detail_observation_type_agreement_required===true,'T4R1_GOV_DETAIL_CROSSCHECK');assert(s?.t4r1_applicability_rule?.parent_t4_in_detail_areas_requires_explicit_r1_in_comment===true,'T4R1_GOV_SCOPE_FAIL_CLOSED');assert(s?.provider_coverage_completeness_claimed===false&&s?.proved_no_termination_occurred_may_be_emitted===false,'T4R1_GOV_NONCLAIM');
 const end=Date.parse(x.candidate_scope.possible_planting_window_utc.end_exclusive);const horizon=new Date(end-1+x.horizon_policy.maximum_total_days*DAY_MS).toISOString();assert(x.horizon_policy.maximum_total_days===180&&horizon===x.horizon_policy.expected_horizon_end_utc,'T4R1_GOV_HORIZON');assert(x.horizon_policy.horizon_may_create_active===false&&x.horizon_policy.support_event_may_renew_horizon===false,'T4R1_GOV_HORIZON_GUARDS');
 const probe=fs.readFileSync(PROBE_PATH,'utf8');assert(probe.includes('extractObservationDetail')&&probe.includes('t4r1Applicability'),'T4R1_GOV_STRUCTURED_PROBE');assert(probe.includes('observationDate < targetDate')&&!probe.includes('observationDate <= targetDate'),'T4R1_GOV_COMPLETE_PLANTING_DAY_PAGINATION');assert(probe.includes('all replications in the order of')&&probe.includes('T4R1_PERSISTENT_R2_NEGATIVE_CONTROL_FAILED'),'T4R1_GOV_R1_PARSER_CONTROLS');assert(probe.includes('T4R1_PERSISTENT_EQUIPMENT_BRAND_NEGATIVE_CONTROL_FAILED')&&probe.includes('T4R1_PERSISTENT_HARVEST_POSITIVE_CONTROL_FAILED'),'T4R1_GOV_TERMINATION_PARSER_CONTROLS');assert(probe.includes('whole_page_body_semantic_classification_used: false'),'T4R1_GOV_WHOLE_PAGE_NONUSE');assert(probe.includes('proved_no_termination_occurred: false')&&probe.includes('provider_coverage_completeness_proven: false'),'T4R1_GOV_NONCLAIM_SOURCE');assert(!probe.includes('lter.kbs.msu.edu/datatables/694'),'T4R1_GOV_LTAR694_FORBIDDEN');
 const b=x.authority_boundary;assert(b.amendment_16_effective_on_exact_protected_main_base===true&&b.truthful_live_result_may_be_adopted_only_by_this_pr_merge===true,'T4R1_GOV_EXACT_MAIN_ADOPTION');assert(b.formal_site_rebind_authorized_before_this_pr_merge===false&&b.ea5e2_operational_activation_qualified===false,'T4R1_GOV_NO_OPERATIONAL_EFFECT');assert(b.runtime_write_count===0&&b.database_write_count===0&&b.scheduler_write_count===0&&b.formal_evidence_write_count===0&&b.formal_execution_count==='0/24','T4R1_GOV_ZERO_WRITES');
 write({schema_version:'geox_mcft_cap09_t4r1_persistent_lifecycle_qualification_governance_v1',status:'PASS',base_sha:BASE_SHA,subject_sha:SUBJECT_SHA,exact_protected_main_base:true,exact_eight_file_boundary:true,amendment_16_effective_and_pinned:true,structured_detail_contract:true,provider_completeness_claimed:false,horizon_end_utc:horizon,adoption_effect:'ELIGIBLE_ONLY_ON_THIS_PR_MERGE_IF_LIVE_OUTCOME_ACTIVE_CANDIDATE',formal_rebind_authorized:false,ea5e2_operational_activation_qualified:false,formal_execution_count:'0/24'});
}catch(e){write({schema_version:'geox_mcft_cap09_t4r1_persistent_lifecycle_qualification_governance_v1',status:'FAIL',base_sha:BASE_SHA||null,subject_sha:SUBJECT_SHA||null,authority_effect:'NONE',formal_rebind_authorized:false,ea5e2_operational_activation_qualified:false,formal_execution_count:'0/24',error:e instanceof Error?e.message:String(e)});process.exitCode=1;}
