// scripts/governance_acceptance/ACCEPTANCE_MCFT_00_REALITY_BINDING_CONTRACT.cjs
// Validates MCFT-00 governance only; performs no runtime or persistence write.
'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),cp=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),BASE='7fd848ae00680480fc864990b9d03b37bc61fdff';
const F={contract:'docs/digital_twin/mcft/GEOX-MCFT-00-REALITY-BINDING-CONTRACT.md',binding:'docs/digital_twin/mcft/GEOX-MCFT-00-REALITY-BINDING.json',sources:'docs/digital_twin/mcft/GEOX-MCFT-00-SOURCE-BINDING-MATRIX.json',configs:'docs/digital_twin/mcft/GEOX-MCFT-00-CONFIGURATION-BINDING-MATRIX.json',candidates:'docs/digital_twin/mcft/GEOX-MCFT-00-CANDIDATE-ADJUDICATION.md',geometryPolicy:'docs/digital_twin/mcft/GEOX-MCFT-00-GEOMETRY-CANONICALIZATION.md',closure:'docs/digital_twin/mcft/GEOX-MCFT-00-CLOSURE-RECORD.md',geometry:'fixtures/mcft/reality_binding/MCFT_C8_GOVERNED_ZONE_V1.geojson',negatives:'fixtures/mcft/reality_binding/negative/MCFT_00_NEGATIVE_CASES_V1.json',matrix:'docs/digital_twin/GEOX-DIGITAL-TWIN-CAPABILITY-MATRIX.json',self:'scripts/governance_acceptance/ACCEPTANCE_MCFT_00_REALITY_BINDING_CONTRACT.cjs',dt02:'scripts/governance_acceptance/ACCEPTANCE_DT_02_RUNTIME_ARCHITECTURE_FREEZE.cjs'};
let pass=0,fail=0,warn=0,hard=0;const ok=m=>{pass++;console.log('PASS: '+m)},bad=m=>{fail++;console.error('FAIL: '+m)},warning=m=>{warn++;console.log('WARN: '+m)},abs=p=>path.join(ROOT,p),txt=p=>fs.readFileSync(abs(p),'utf8'),json=p=>JSON.parse(txt(p)),clone=v=>structuredClone(v),nonempty=v=>typeof v==='string'&&v.trim().length>0,sha=s=>crypto.createHash('sha256').update(s,'utf8').digest('hex');
function stable(v){if(Array.isArray(v))return'['+v.map(stable).join(',')+']';if(v&&typeof v==='object')return'{'+Object.keys(v).sort().map(k=>JSON.stringify(k)+':'+stable(v[k])).join(',')+'}';return JSON.stringify(v)}
const shaObj=v=>sha(stable(v)),approx=(a,b,t=1e-3)=>Number.isFinite(+a)&&Number.isFinite(+b)&&Math.abs(+a-+b)<=t,field=(s,k)=>(s.match(new RegExp('^'+k+':\\s*(.+)$','m'))||[])[1]?.trim();
for(const p of Object.values(F))fs.existsSync(abs(p))?ok('file exists '+p):bad('missing '+p);if(fail)process.exit(1);
const A=json(F.binding),S=json(F.sources),C=json(F.configs),G=json(F.geometry),N=json(F.negatives),M=json(F.matrix),V={...clone(A),source_bindings:clone(S.bindings||[]),configuration_bindings:clone(C.bindings||[])};ok('all JSON artifacts parse');
const rc=n=>{const x=Math.round(+n*1e7)/1e7;return Object.is(x,-0)?0:x},same=(a,b)=>a[0]===b[0]&&a[1]===b[1];
function geomCodes(g){const out=[];if(g?.type!=='Polygon')out.push('INVALID_GEOMETRY_TYPE');if(!Array.isArray(g?.coordinates)||!g.coordinates.length||!g.coordinates[0]?.length)out.push('EMPTY_GEOMETRY');for(const r of g?.coordinates||[]){if(!Array.isArray(r)||r.length<4){out.push('EMPTY_GEOMETRY');continue}for(const p of r){if(!Array.isArray(p)||p.length<2||!Number.isFinite(+p[0])||!Number.isFinite(+p[1])||+p[0]<-180||+p[0]>180||+p[1]<-90||+p[1]>90)out.push('INVALID_WGS84_COORDINATE')}const a=r[0],b=r.at(-1);if(!a||!b||rc(a[0])!==rc(b[0])||rc(a[1])!==rc(b[1]))out.push('UNCLOSED_POLYGON')}return[...new Set(out)]}
function signed(r){let s=0;for(let i=0;i<r.length;i++){const a=r[i],b=r[(i+1)%r.length];s+=a[0]*b[1]-b[0]*a[1]}return s/2}
function ring(raw,outer){const p=[];for(const q of raw){const z=[rc(q[0]),rc(q[1])];if(!p.length||!same(p.at(-1),z))p.push(z)}if(p.length>1&&same(p[0],p.at(-1)))p.pop();if(p.length<3)throw Error('EMPTY_RING');if(outer?signed(p)<0:signed(p)>0)p.reverse();p.push([...p[0]]);return p}
function canonical(g){const e=geomCodes(g);if(e.length)throw Error(e[0]);return{coordinates:[ring(g.coordinates[0],true),...g.coordinates.slice(1).map(x=>ring(x,false)).sort((a,b)=>stable(a).localeCompare(stable(b)))],type:'Polygon'}}
const geomHash=g=>shaObj(canonical(g));
function ringArea(r){const p=r.slice(0,-1),lat=p.reduce((s,x)=>s+x[1],0)/p.length,R=6378137,d=Math.PI/180,q=p.map(([x,y])=>[R*x*d*Math.cos(lat*d),R*y*d]);let s=0;for(let i=0;i<q.length;i++){const a=q[i],b=q[(i+1)%q.length];s+=a[0]*b[1]-b[0]*a[1]}return Math.abs(s/2)}
function area(g){const c=canonical(g),v=ringArea(c.coordinates[0])-c.coordinates.slice(1).reduce((s,r)=>s+ringArea(r),0);return Math.round(v*1000)/1000}
const src=(b,r)=>(b.source_bindings||[]).find(x=>x.source_role===r),cfg=(b,r)=>(b.configuration_bindings||[]).find(x=>x.source_role===r);
function digest(b){const x=clone(b);for(const k of b.semantic_identity_algorithm?.excluded_fields||[])delete x[k];delete x.binding_id;delete x.determinism_hash;return shaObj(x)}
function validate(b,g=G){const o=[],add=(c,x)=>{if(c)o.push(x)},scope=b.scope||{};for(const k of['tenant_id','project_id','group_id','field_id','season_id','zone_id'])add(!nonempty(scope[k]),'MISSING_'+k.toUpperCase());add((b.active_scopes||[]).filter(x=>x.status==='ACTIVE').length!==1,'SECOND_ACTIVE_REALITY_SCOPE');add(b.runtime_mode!=='REPLAY',b.runtime_mode==='CONTROLLED_REPLAY'?'INVALID_RUNTIME_MODE':'MCFT00_REPLAY_REQUIRED');add(Object.hasOwn(b.crop_binding||{},'crop_stage'),'DYNAMIC_CROP_STAGE_AS_IDENTITY');add(!nonempty(b.geometry_binding?.geometry_fixture_ref),'EMPTY_GEOMETRY');add(b.geometry_binding?.geometry_type!=='Polygon','INVALID_GEOMETRY_TYPE');add(['SURVEYED','FIELD_VERIFIED','REAL_VERIFIED','PRODUCTION_AUTHORITATIVE'].includes(b.geometry_binding?.geometry_truth_status),'SYNTHETIC_GEOMETRY_FALSE_TRUTH');for(const x of geomCodes(g))o.push(x);if(!geomCodes(g).length){add(b.geometry_binding.geometry_semantic_hash!=='sha256:'+geomHash(g),'GEOMETRY_SEMANTIC_HASH_MISMATCH');add(!approx(b.geometry_binding.derived_area_m2,area(g)),'GEOMETRY_AREA_MISMATCH')}
const rz=b.root_zone_binding||{},ls=[...(rz.layers||[])].sort((a,z)=>a.top_depth_mm-z.top_depth_mm);if(!ls.length||ls[0].top_depth_mm!==rz.top_depth_mm||ls.at(-1).bottom_depth_mm!==rz.bottom_depth_mm)o.push('ROOT_ZONE_LAYER_GAP');for(let i=1;i<ls.length;i++){add(ls[i].top_depth_mm>ls[i-1].bottom_depth_mm,'ROOT_ZONE_LAYER_GAP');add(ls[i].top_depth_mm<ls[i-1].bottom_depth_mm,'ROOT_ZONE_LAYER_OVERLAP')}add(!approx(ls.reduce((s,x)=>s+Number(x.weight||0),0),1,1e-9),'ROOT_ZONE_WEIGHT_SUM_INVALID');for(const x of rz.sensor_support||[]){add(x.nominal_depth_mm<rz.top_depth_mm||x.nominal_depth_mm>rz.bottom_depth_mm,'SENSOR_DEPTH_OUTSIDE_ROOT_ZONE');add(x.direct_state_equivalence!==false,'POINT_OBSERVATION_DIRECT_STATE_FORBIDDEN')}
const soil=src(b,'SOIL_MOISTURE_OBSERVATION'),rain=src(b,'RAINFALL_OBSERVATION'),weather=src(b,'FUTURE_WEATHER_ASSUMPTION'),eh=src(b,'HISTORICAL_ET0_INPUT'),ef=src(b,'FUTURE_ET0_ASSUMPTION'),plan=src(b,'APPROVED_IRRIGATION_PLAN'),exec=src(b,'IRRIGATION_EXECUTION_EVIDENCE');add(!soil||soil.source_unit!=='percent_vwc','AMBIGUOUS_SOIL_MOISTURE_UNIT');add(!soil||soil.conversion_rule!=='canonical_value = source_value / 100','MISSING_PERCENT_VWC_CONVERSION');add(weather?.epistemic_class==='OBSERVED','FUTURE_ASSUMPTION_CANNOT_BE_OBSERVED');add(eh?.epistemic_class!=='ESTIMATED','HISTORICAL_ET0_MUST_BE_ESTIMATED');add(ef?.epistemic_class!=='ASSUMED','FUTURE_ET0_MUST_BE_ASSUMED');add(rain&&weather&&rain.binding_id===weather.binding_id,'OBSERVED_AND_FUTURE_WEATHER_RECORD_MUST_SEPARATE');add(!cfg(b,'SOIL_HYDRAULIC_CONFIGURATION'),'MISSING_SOIL_HYDRAULIC_CONFIGURATION');add(!cfg(b,'CROP_WATER_USE_CONFIGURATION'),'MISSING_CROP_WATER_USE_CONFIGURATION');for(const x of b.configuration_bindings||[]){add(!Number.isInteger(x.configuration_version)||x.configuration_version<1,'CONFIGURATION_SOURCE_VERSION_REQUIRED');for(const p of x.configuration_definition?.parameters||[])add(['UNKNOWN','UNAVAILABLE','SOURCE_MISSING'].includes(p.status)&&p.value!=null,'UNKNOWN_PARAMETER_DEFAULT_FORBIDDEN')}add(plan?.epistemic_class==='EXECUTED','APPROVED_PLAN_CANNOT_BE_EXECUTED');add(plan?.state_input_policy!=='NEVER','APPROVED_PLAN_STATE_INPUT_FORBIDDEN');add(Object.hasOwn(plan||{},'eligible_for_state_input'),'PLAN_CANNOT_BE_STATE_INPUT_ELIGIBLE');add(exec?.action_feedback_policy?.acceptance_ref_required!==false,'ACCEPTANCE_REF_MUST_BE_OPTIONAL');add((b.replay_release_policy?.rules||[]).some(x=>/current_wall_clock/i.test(x.formula||'')),'WALL_CLOCK_AVAILABILITY_FORBIDDEN');const ex=new Set(b.semantic_identity_algorithm?.excluded_fields||[]);add(b.semantic_identity_algorithm?.binding_id_format==='random_uuid','RANDOM_IDENTITY_FORBIDDEN');add(!ex.has('created_at')||!ex.has('absolute_path'),'NONSEMANTIC_FIELD_IN_HASH');add(Object.hasOwn(b,'lineage_id'),'BINDING_VERSION_LINEAGE_FORBIDDEN');add(Object.hasOwn(b,'revision_id'),'BINDING_VERSION_REVISION_FORBIDDEN');add((b.forbidden_runtime_actions||[]).some(x=>['E1_DECLARE_REVISION','E2_APPEND_REVISION_STATUS','E3_PROMOTE_LINEAGE'].includes(x)),'RUNTIME_REVISION_ACTION_FORBIDDEN');add((b.forbidden_runtime_actions||[]).includes('SWITCH_ACTIVE_LINEAGE'),'ACTIVE_LINEAGE_SWITCH_FORBIDDEN');add(b.canonical_persistence!==false||b.write_target!=='NONE','REALITY_BINDING_FACT_WRITE_FORBIDDEN');add(b.active_runtime_config!==false,'ACTIVE_RUNTIME_CONFIG_FORBIDDEN');add((b.generated_runtime_objects||[]).length>0,'RUNTIME_OBJECT_CREATION_FORBIDDEN');return[...new Set(o)]}
function patch(t,ops){for(const op of ops||[]){const a=op.path.split('/').slice(1),k=a.pop();let p=t;for(const z of a)p=p[Array.isArray(p)?+z:z];if(op.op==='remove')Array.isArray(p)?p.splice(+k,1):delete p[k];else if(op.op==='append')p[k].push(clone(op.value));else p[k]=clone(op.value)}}
function feedback(c){const r={actual_amount:20,unit:'mm',executed_at:'2026-01-01T01:00:00Z',spatial_coverage:{zone_id:A.scope.zone_id},source_identity:'dev_valve_pump_c8_001',source_quality:'CONTROLLED_REPLAY',limitations:[],receipt_ref:'r1',origin_kind:'AO_ACT',task_ref:'t1'};if(c.endsWith('ACTUAL_AMOUNT'))delete r.actual_amount;if(c.endsWith('EXECUTED_AT'))delete r.executed_at;if(c.endsWith('SPATIAL_COVERAGE'))delete r.spatial_coverage;if(c.endsWith('SOURCE_IDENTITY'))delete r.source_identity;if(c.endsWith('NO_TRUSTED_REF'))delete r.receipt_ref;if(c.endsWith('AO_ACT_NO_TASK'))delete r.task_ref;if(r.actual_amount==null)return'EXECUTION_ACTUAL_AMOUNT_REQUIRED';if(!r.executed_at)return'EXECUTION_TIME_REQUIRED';if(!r.spatial_coverage)return'EXECUTION_SPATIAL_COVERAGE_REQUIRED';if(!r.source_identity)return'EXECUTION_SOURCE_IDENTITY_REQUIRED';if(!r.receipt_ref&&!r.as_executed_ref)return'TRUSTED_EXECUTION_REFERENCE_REQUIRED';if(r.origin_kind==='AO_ACT'&&!r.task_ref)return'AO_ACT_TASK_REF_REQUIRED'}
function scenario(row){const s=row.scenario;if(s==='UNCLOSED_GEOMETRY_FIXTURE'){const g=clone(G);g.coordinates[0].at(-1)[0]+=.001;return geomCodes(g)[0]}if(s==='INVALID_WGS84_FIXTURE'){const g=clone(G);g.coordinates[0][1]=[181,0];return geomCodes(g)[0]}if(s==='SEMANTIC_HASH_MISMATCH'){const b=clone(V);b.geometry_binding.geometry_semantic_hash='sha256:'+'0'.repeat(64);return validate(b)[0]}if(s==='FORMATTING_DEPENDENCE')return sha(JSON.stringify(G))!==sha(JSON.stringify(G,null,2))&&geomHash(JSON.parse(JSON.stringify(G)))===geomHash(JSON.parse(JSON.stringify(G,null,2)))?'GEOMETRY_HASH_FORMAT_DEPENDENT':null;if(s==='REMOVE_SOIL_CONFIG'||s==='REMOVE_CROP_CONFIG'){const b=clone(V),r=s==='REMOVE_SOIL_CONFIG'?'SOIL_HYDRAULIC_CONFIGURATION':'CROP_WATER_USE_CONFIGURATION';b.configuration_bindings=b.configuration_bindings.filter(x=>x.source_role!==r);return validate(b)[0]}if(s==='UNKNOWN_WITH_VALUE'){const b=clone(V);b.configuration_bindings[0].configuration_definition.parameters[0].status='UNKNOWN';return validate(b)[0]}if(s?.startsWith('EXECUTION_')||s==='AO_ACT_NO_TASK')return feedback(s);const fixed={FUTURE_OBSERVATION:'FUTURE_OBSERVATION_LEAKAGE',LATE_AS_ONTIME:'LATE_EVIDENCE_CLASSIFICATION_REQUIRED',LEGACY_STATE_INITIAL:'LEGACY_STATE_CONTAMINATION',LEGACY_SCENARIO:'LEGACY_SCENARIO_CONTAMINATION',P50_FORECAST:'P50_FORECAST_CONTAMINATION',C8_ACTION_CLOSURE:'C8_ACTION_CHAIN_CONTAMINATION'};if(fixed[s])return fixed[s];if(s==='SAME_ID_DIFFERENT_PAYLOAD'){const b=clone(A);b.scope.zone_id='changed';return b.binding_id===A.binding_id&&digest(b)!==A.determinism_hash.slice(7)?'IDEMPOTENCY_CONFLICT':null}}
let predecessor=false;if(process.argv.includes('--skip-predecessors'))warning('predecessor Gate skipped by explicit flag');else{const w=path.join(ROOT,'.tmp-mcft00-predecessor');try{try{cp.execFileSync('git',['worktree','remove','--force',w],{cwd:ROOT,stdio:'ignore'})}catch{}cp.execFileSync('git',['worktree','add','--detach',w,BASE],{cwd:ROOT,stdio:'ignore'});cp.execFileSync(process.execPath,[path.join(w,F.dt02)],{cwd:w,stdio:'inherit'});predecessor=true;ok('exact predecessor DT-02/DT-01/DT-00 Gates pass')}catch(e){bad('predecessor Gate failed: '+e.message)}finally{try{cp.execFileSync('git',['worktree','remove','--force',w],{cwd:ROOT,stdio:'ignore'})}catch{}}}
const contract=txt(F.contract),closure=txt(F.closure),complete=field(closure,'status')==='COMPLETE',roles=new Set(S.bindings.map(x=>x.source_role)),croles=new Set(C.bindings.map(x=>x.source_role)),all=[...S.bindings,...C.bindings],gd=geomHash(G),ar=area(G),d=digest(A),matrixRows=stable(A.source_bindings)===stable(S.bindings.map(x=>({binding_id:x.binding_id,source_role:x.source_role,determinism_hash:x.determinism_hash})))&&stable(A.configuration_bindings)===stable(C.bindings.map(x=>({binding_id:x.binding_id,source_role:x.source_role,determinism_hash:x.determinism_hash})));
const checks=[
[predecessor||process.argv.includes('--skip-predecessors'),'Authority 1 predecessor'],[A.baseline_commit===BASE&&A.predecessor_merge_commit===BASE,'Authority 2 baseline'],[A.predecessor_merge_pr===2303,'Authority 3 PR'],[field(contract,'status')===(complete?'COMPLETE':'PENDING_ACCEPTANCE'),'Authority 4 status'],[complete?/^PASS/.test(field(closure,'final_pr_ci')||''):true,'Authority 5 final evidence',!complete],
[['tenant_id','project_id','group_id','field_id','season_id','zone_id'].every(k=>nonempty(A.scope[k])),'Scope 1 ids'],[A.active_scopes.filter(x=>x.status==='ACTIVE').length===1,'Scope 2 one active'],[A.scope.field_id==='field_c8_demo'&&A.scope.season_id==='season_2026_c8_corn','Scope 3 stable ids'],[!Object.hasOwn(A.crop_binding,'crop_stage'),'Scope 4 no crop stage identity'],[A.runtime_mode==='REPLAY','Scope 5 replay'],[A.reality_scope_class==='CONTROLLED_SYNTHETIC_REPLAY_PROXY','Scope 6 classification'],[txt(F.candidates).includes('FIXTURE_ONLY')&&txt(F.candidates).includes('REFERENCE_ONLY')&&txt(F.candidates).includes('REJECTED'),'Scope 7 adjudication'],
[!geomCodes(G).length,'Geometry 1 valid'],[G.type==='Polygon','Geometry 2 Polygon'],[G.coordinates.every(r=>same(r[0],r.at(-1))),'Geometry 3 closed'],[!geomCodes(G).includes('INVALID_WGS84_COORDINATE'),'Geometry 4 WGS84'],[txt(F.geometryPolicy).includes('GEOX_MCFT_GEOJSON_CANONICALIZATION_V1'),'Geometry 5 policy'],[sha(txt(F.geometry))===A.geometry_binding.file_sha256.slice(7)&&A.geometry_binding.file_sha256!==A.geometry_binding.geometry_semantic_hash,'Geometry 6 dual hash'],[gd===A.geometry_binding.geometry_semantic_hash.slice(7)&&approx(ar,A.geometry_binding.derived_area_m2),'Geometry 7 semantic/area'],[A.geometry_binding.legacy_area_status==='NON_AUTHORITATIVE_COMPARISON_ONLY','Geometry 8 legacy area'],[A.geometry_binding.geometry_truth_status==='CONTROLLED_SYNTHETIC'&&A.geometry_binding.binding_version===1,'Geometry 9 version/truth'],
[A.root_zone_binding.top_depth_mm===0&&A.root_zone_binding.bottom_depth_mm===300,'Root 1 depth'],[!validate(V).includes('ROOT_ZONE_LAYER_GAP')&&!validate(V).includes('ROOT_ZONE_LAYER_OVERLAP'),'Root 2 coverage'],[!validate(V).includes('ROOT_ZONE_WEIGHT_SUM_INVALID'),'Root 3 weights'],[!validate(V).includes('SENSOR_DEPTH_OUTSIDE_ROOT_ZONE'),'Root 4 sensor depth'],[A.root_zone_binding.sensor_support[0].spatial_support==='POINT'&&A.root_zone_binding.sensor_support[0].root_zone_representativeness==='PARTIAL','Root 5 support'],[A.root_zone_binding.sensor_support[0].direct_state_equivalence===false,'Root 6 no direct state'],
[roles.size===7&&croles.size===2,'Bindings 1 domains'],[all.length===9&&new Set(all.map(x=>x.binding_id)).size===9,'Bindings 2 count'],[S.bindings.every(x=>x.origin_source_id&&x.ingress_adapter_id&&x.origin_source_id!==x.ingress_adapter_id),'Bindings 3 origin/adapter'],[src(V,'SOIL_MOISTURE_OBSERVATION').epistemic_class==='OBSERVED'&&src(V,'SOIL_MOISTURE_OBSERVATION').conversion_rule==='canonical_value = source_value / 100','Bindings 4 soil'],[src(V,'RAINFALL_OBSERVATION').binding_id!==src(V,'FUTURE_WEATHER_ASSUMPTION').binding_id,'Bindings 5 rain/future'],[src(V,'HISTORICAL_ET0_INPUT').epistemic_class==='ESTIMATED','Bindings 6 historical ET0'],[src(V,'FUTURE_ET0_ASSUMPTION').epistemic_class==='ASSUMED','Bindings 7 future ET0'],[cfg(V,'SOIL_HYDRAULIC_CONFIGURATION').configuration_version===1,'Bindings 8 soil config'],[cfg(V,'CROP_WATER_USE_CONFIGURATION').configuration_version===1,'Bindings 9 crop config'],[src(V,'APPROVED_IRRIGATION_PLAN').state_input_policy==='NEVER','Bindings 10 plan'],[src(V,'IRRIGATION_EXECUTION_EVIDENCE').state_input_policy==='CONDITIONAL','Bindings 11 execution'],[all.every(x=>x.source_unit&&x.canonical_unit&&x.time_semantics&&x.quality_semantics&&x.availability_semantics&&Array.isArray(x.eligible_downstream_uses)&&Array.isArray(x.forbidden_downstream_uses)&&Array.isArray(x.limitations)&&x.source_version&&x.binding_version===1),'Bindings 12 common'],[C.bindings.every(x=>x.configuration_source_id&&!Object.hasOwn(x,'origin_source_id')&&!Object.hasOwn(x,'ingress_adapter_id'))&&matrixRows,'Bindings 13 config separation'],
[A.time_domain.timezone==='UTC'&&A.time_domain.tick_interval==='PT1H'&&A.time_domain.tick_alignment==='UTC_CLOCK_HOUR','Time 1 domain'],[S.bindings.every(x=>stable(x.time_semantics).includes('available_to_runtime_at')),'Time 2 triple time'],[(()=>{const x=clone(A.replay_release_policy),h=x.release_policy_hash;delete x.release_policy_hash;return h==='sha256:'+shaObj(x)})(),'Time 3 policy hash'],[A.replay_release_policy.forbidden_inputs.includes('current_wall_clock')&&!validate(V).includes('WALL_CLOCK_AVAILABILITY_FORBIDDEN'),'Time 4 wall clock'],[contract.includes('late Evidence')&&contract.includes('on-time Evidence'),'Time 5 late'],
[A.binding_id==='mrb_'+d.slice(0,32),'Determinism 1 id'],[A.determinism_hash==='sha256:'+d&&d===digest(json(F.binding)),'Determinism 2 hash'],[['created_at','absolute_path','worker_id'].every(x=>A.semantic_identity_algorithm.excluded_fields.includes(x)),'Determinism 3 exclusions'],[N.cases.some(x=>x.expected_reason_code==='IDEMPOTENCY_CONFLICT'),'Determinism 4 conflict'],[A.versioning_policy.semantic_change_requires_new_binding_version&&A.versioning_policy.required_fields.includes('supersedes_binding_ref'),'Determinism 5 version'],[A.versioning_policy.runtime_lineage_revision===false&&!Object.hasOwn(A,'lineage_id')&&!Object.hasOwn(A,'revision_id'),'Determinism 6 lineage separation'],
[A.artifact_class==='GOVERNANCE_INPUT'&&!A.canonical_runtime_object&&!A.canonical_persistence,'Canonical 1 governance'],[A.compile_target.object_type==='twin_runtime_config_v1'&&A.compile_target.record_class==='CANONICAL_MODEL_GOVERNANCE_HISTORY'&&!A.compile_target.lineage_member&&A.compile_target.envelope_profile==='NON_LINEAGE_CONTEXT','Canonical 2 compile'],[!A.generated_runtime_objects.length&&A.legacy_contamination_guard.forbidden_initial_objects.includes('water_state_estimate_v1'),'Canonical 3 contamination'],[src(V,'APPROVED_IRRIGATION_PLAN').epistemic_class==='APPROVED'&&src(V,'IRRIGATION_EXECUTION_EVIDENCE').epistemic_class==='EXECUTED','Canonical 4 stages'],[A.write_target==='NONE'&&!A.active_runtime_config&&A.runtime_transaction_family==='NONE','Canonical 5 no write'],[M.phase==='MCFT-00'&&M.current_claim===(complete?'MCFT_00_REALITY_BINDING_FROZEN':'MCFT_00_REALITY_BINDING_PENDING_ACCEPTANCE')&&N.case_count===N.cases.length,'Canonical 6 synchronized']];
for(const [c,m,pending]of checks){hard++;if(c)ok(m);else if(pending)warning(m+' pending');else bad(m)}if(hard!==57)bad('hard check count '+hard);
for(const r of N.cases){let actual;try{if(r.scenario)actual=scenario(r);else{const b=clone(V);patch(b,r.operations);const q=validate(b);actual=q.includes(r.expected_reason_code)?r.expected_reason_code:q[0]}}catch(e){actual='EXCEPTION:'+e.message}actual===r.expected_reason_code&&r.expected_no_write===true&&nonempty(r.expected_stage)?ok('negative '+r.fixture_id+' -> '+actual):bad('negative '+r.fixture_id+' expected '+r.expected_reason_code+' got '+actual)}
for(const x of all){const q=clone(x),h=q.determinism_hash;delete q.determinism_hash;if(h!=='sha256:'+shaObj(q))bad('binding hash '+x.binding_id)}ok('source/config binding hashes checked');for(const [x,n]of[[S,'source'],[C,'config']]){const q=clone(x),h=q.matrix_hash;delete q.matrix_hash;h==='sha256:'+shaObj(q)?ok(n+' matrix hash'):bad(n+' matrix hash')}
if(!process.argv.includes('--skip-git'))try{const out=cp.execFileSync('git',['diff','--name-only',BASE+'...HEAD'],{cwd:ROOT,encoding:'utf8'}).trim(),files=out?out.split(/\r?\n/):[],allowed=new Set([F.matrix,F.self]),forbidden=files.filter(x=>!x.startsWith('docs/digital_twin/mcft/')&&!x.startsWith('fixtures/mcft/reality_binding/')&&!allowed.has(x));files.length&&!forbidden.length?ok('changed-file boundary '+files.length):bad('forbidden/no changes '+forbidden.join(','));const s=cp.execFileSync('git',['status','--short'],{cwd:ROOT,encoding:'utf8'}).trim();s?bad('working tree dirty '+s):ok('working tree clean')}catch(e){bad('git boundary '+e.message)}else warning('git checks skipped');
console.log(`\nMCFT-00 hard acceptance: ${57-fail} PASS, ${fail} FAIL`);console.log(`MCFT-00 total acceptance: ${pass} PASS, ${warn} WARN, ${fail} FAIL`);if(fail)process.exit(1);console.log('MCFT-00 REALITY BINDING CONTRACT: PASS');
