#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),P=require('node:child_process'),F=require('node:fs'),O=require('node:os'),X=require('node:path');
const R=X.resolve(__dirname,'../..'),D='docs/digital_twin/mcft/cap_08';
const CP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-ENTRYPOINT-CORRECTION-V1.json`,BP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-ENTRYPOINT-CORRECTION-BOUNDARY-V1.json`,IP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-FAILED-ATTEMPT-001-V1.json`;
const EP='scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/qualification_workflow_entrypoint_v1.ts',W='.github/workflows/mcft-cap-08-s6-run-a-qualification-entrypoint-correction.yml',Q=X.join(R,'acceptance-output/MCFT_CAP_08_S6_RUN_A_QUALIFICATION_ENTRYPOINT_CORRECTION_RESULT.json');
const read=p=>JSON.parse(F.readFileSync(X.join(R,p),'utf8')),text=p=>F.readFileSync(X.join(R,p),'utf8'),git=(...a)=>P.execFileSync('git',a,{cwd:R,encoding:'utf8'}).trim();
const canon=v=>Array.isArray(v)?`[${v.map(canon).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`:JSON.stringify(v),sd=v=>{const x=structuredClone(v);delete x.semantic_digest;return`sha256:${C.createHash('sha256').update(canon(x)).digest('hex')}`},out=v=>{F.mkdirSync(X.dirname(Q),{recursive:true});F.writeFileSync(Q,JSON.stringify(v,null,2)+'\n')};
try{
 const c=read(CP),b=read(BP),i=read(IP),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim();A.equal(base,b.base_main_sha);A.equal(git('merge-base',base,'HEAD'),base);A.equal(git('diff','--check',`${base}...HEAD`),'');
 const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();A.deepEqual(changed,[...b.changed_files].sort());A.equal(changed.length,7);for(const v of[c,b,i])A.equal(v.semantic_digest,sd(v),'SEMANTIC_DIGEST');
 A.equal(git('rev-parse',`${base}:${EP}`),'2e10251c8bd1665beb245ef2a96a4d8d5d7a6dd0');A.notEqual(git('rev-parse',`HEAD:${EP}`),'2e10251c8bd1665beb245ef2a96a4d8d5d7a6dd0');
 const s=text(EP);A.match(s,/async function main\(\):Promise<void>/);A.match(s,/main\(\)\.catch/);A.match(s,/await createPortsV1/);A.match(s,/await executeRunAQualificationHarnessV1/);for(const x of[/import\.meta/,/pathToFileURL/,/fileURLToPath/,/createRequire/,/const imported=await import/])A.doesNotMatch(s,x);
 P.execFileSync('pnpm',['-w','exec','tsc','--pretty','false','--noEmit','--module','commonjs','--target','es2022','--moduleResolution','node','--esModuleInterop','--skipLibCheck',EP],{cwd:R,encoding:'utf8',stdio:'pipe'})
 A.equal(i.workflow_run.run_id,30437329843);A.equal(i.workflow_run.head_sha,base);A.equal(i.authority_job.job_id,90528039013);A.equal(i.authority_job.conclusion,'success');A.equal(i.execution_job.job_id,90528078435);A.equal(i.execution_job.conclusion,'failure');A.equal(i.execution_job.transform_error_count,3);A.equal(i.execution_job.failed_source_blob_sha,'2e10251c8bd1665beb245ef2a96a4d8d5d7a6dd0');
 A.equal(i.artifacts.normalized_authority.artifact_id,8717938467);A.equal(i.artifacts.normalized_authority.digest,'sha256:7df41142a061740463af43fcb66cbcd1c2e7ecf496dd7fb34ba6fb93020e142f');A.equal(i.artifacts.failed_qualification.artifact_id,8717952482);A.equal(i.artifacts.failed_qualification.digest,'sha256:404d3a31b2977d1237341e6a412c21cb4ccc3483c9c5a70e57b1e006e2acff38');A.equal(i.artifacts.failed_qualification.normalized_authority_only,true);
 A.equal(i.step_outcomes.fresh_database_bootstrap_completed,true);A.equal(i.step_outcomes.qualification_harness_entered,false);A.equal(i.step_outcomes.qualification_result_generated,false);A.equal(i.step_outcomes.disposable_database_drop_completed,true);A.equal(i.classification.operational_instance_reusable,false);A.equal(i.classification.rerun_jobs_authorized,false);
 A.equal(c.record_status,'RUN_A_QUALIFICATION_ENTRYPOINT_CORRECTION_IMPLEMENTED_NOT_EFFECTIVE');A.equal(c.correction.entrypoint_semantics_changed,false);A.equal(c.execution_constraints.database_execution_performed_in_pr,false);A.equal(c.execution_constraints.new_execution_authority_present,false);
 for(const [p,h] of[[c.preserved_frozen_objects.port_bundle_path,c.preserved_frozen_objects.port_bundle_blob_sha],[c.preserved_frozen_objects.qualification_workflow_path,c.preserved_frozen_objects.qualification_workflow_blob_sha],[c.preserved_frozen_objects.qualification_gate_path,c.preserved_frozen_objects.qualification_gate_blob_sha]])A.equal(git('rev-parse',`HEAD:${p}`),h,`FROZEN_BLOB_DRIFT:${p}`);
 const historical=text('scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_RUN_A_QUALIFICATION_CONTROL_PLANE.cjs');A.match(historical,/SUCCESSOR_ENTRYPOINT_CORRECTION/);A.match(historical,/GITHUB_EVENT_PATH/);
 const w=text(W);A.match(w,/pull_request:/);for(const x of[/workflow_dispatch:/,/services:\s*\n\s*postgres:/,/DATABASE_URL/])A.doesNotMatch(w,x);
 const z={schema_version:'geox_mcft_cap08_s6_run_a_qualification_entrypoint_correction_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:7,failed_run_id:i.workflow_run.run_id,failed_job_id:i.execution_job.job_id,failed_operational_instance_id:i.execution_identity.operational_run_instance_id,failed_instance_reusable:false,database_drop_completed:true,qualification_harness_entered:false,entrypoint_cjs_transform_pass:true,entrypoint_semantics_changed:false,port_bundle_blob_sha:c.preserved_frozen_objects.port_bundle_blob_sha,database_execution_performed_in_pr:false,new_execution_authority_present:false,run_a_qualification_completed:false,run_b_executed:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};out(z);console.log(JSON.stringify(z,null,2));
}catch(e){out({schema_version:'geox_mcft_cap08_s6_run_a_qualification_entrypoint_correction_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1}
