#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {ROOT,loadWitnessCatalogV1,git}=require('./mcft_cap08_s6_witness/catalog_v1.cjs');
const {loadProducerRegistryV1}=require('./mcft_cap08_s6_witness/registry_v1.cjs');
const {buildSyntheticPerRunSourceV1,syntheticContextV1}=require('./mcft_cap08_s6_witness/synthetic_fixture_v1.cjs');
const BOUNDARY='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-WITNESS-PRODUCER-BOUNDARY-V1.json';
const OUTPUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_WITNESS_PRODUCER_RESULT.json');
function readJson(p){return JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));}
function write(v){fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,`${JSON.stringify(v,null,2)}\n`);}
try{
 const local=process.env.MCFT_LOCAL_REPLAY==='1'; const boundary=readJson(BOUNDARY); const base=String(process.env.MCFT_BASE_SHA||boundary.base_main_sha).trim();
 if(!local){assert.equal(base,boundary.base_main_sha,'BASE_SHA_DRIFT');assert.equal(git('merge-base',base,'HEAD'),base,'BASE_NOT_ANCESTOR');assert.equal(git('diff','--check',`${base}...HEAD`),'','DIFF_CHECK_FAILED');const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(changed,[...boundary.changed_files].sort(),'CHANGED_FILE_BOUNDARY');}
 assert.equal(boundary.runtime_source_file_count,0);assert.equal(boundary.runtime_acceptance_file_count,0);assert.equal(boundary.database_migration_file_count,0);assert.equal(boundary.dual_run_workflow_file_count,0);assert.equal(boundary.finalizer_file_count,0);
 const catalog=loadWitnessCatalogV1({localReplay:local});const registry=loadProducerRegistryV1(catalog);
 const entries=Object.values(catalog.byContract);const perRun=entries.filter((c)=>c.phase==='PER_RUN');const deferred=entries.filter((c)=>c.phase!=='PER_RUN');assert.equal(perRun.length,22);assert.equal(deferred.length,3);assert.equal(Object.keys(registry).length,19);
 const active=Object.values(registry).filter((p)=>p.implementation_status==='IMPLEMENTED');const deferredModules=Object.values(registry).filter((p)=>p.implementation_status==='DEFERRED_BY_AUTHORITY');assert.equal(active.length,16);assert.equal(deferredModules.length,3);const perRunProducerIds=[...new Set(perRun.map((c)=>c.producer_id))].sort();const deferredProducerIds=[...new Set(deferred.map((c)=>c.producer_id))].sort();assert.deepEqual(active.map((p)=>p.producer_id).sort(),perRunProducerIds,'PER_RUN_PRODUCER_SET');assert.deepEqual(deferredModules.map((p)=>p.producer_id).sort(),deferredProducerIds,'DEFERRED_PRODUCER_SET');
 const witnesses=[];for(const contract of perRun){for(const run of ['RUN_A','RUN_B']){const context=syntheticContextV1(run);const source=buildSyntheticPerRunSourceV1(context);const w=registry[contract.producer_id].produce({catalog,proof_contract_id:contract.proof_contract_id,context,source});assert.equal(w.status,'CONTRACT_TEST_PASS',`CONTRACT_TEST:${contract.proof_contract_id}:${run}`);assert.equal(w.hard_acceptance_eligible,false);assert.equal(w.item_id,contract.item_id);assert.equal(w.requirement,contract.requirement);witnesses.push(w);}}
 assert.equal(witnesses.length,44);
 for(const contract of deferred){const phase=contract.phase;const context=syntheticContextV1('RUN_A',phase);const source=buildSyntheticPerRunSourceV1(context);const w=registry[contract.producer_id].produce({catalog,proof_contract_id:contract.proof_contract_id,context,source});assert.equal(w.status,'NOT_YET_ELIGIBLE');assert.equal(w.eligibility_reason,'DEFERRED_BY_AUTHORITY');assert.equal(w.hard_acceptance_eligible,false);}
 const sample=perRun[0];const wrongContext={...syntheticContextV1('RUN_A'),proof_phase:'CROSS_RUN',phase_instance:'RUN_A_RUN_B_PAIR'};const wrongSource=buildSyntheticPerRunSourceV1(wrongContext);const wrong=registry[sample.producer_id].produce({catalog,proof_contract_id:sample.proof_contract_id,context:wrongContext,source:wrongSource});assert.equal(wrong.status,'NOT_YET_ELIGIBLE');assert.equal(wrong.eligibility_reason,'PROOF_PHASE_MISMATCH');
 const failContext=syntheticContextV1('RUN_A');const bad=buildSyntheticPerRunSourceV1(failContext);bad.sequence.tick_ids=bad.sequence.tick_ids.slice(0,-1);const fail=registry[sample.producer_id].produce({catalog,proof_contract_id:sample.proof_contract_id,context:failContext,source:bad});assert.equal(fail.status,'CONTRACT_TEST_FAIL');assert.equal(fail.hard_acceptance_eligible,false);
 const missingContext={...syntheticContextV1('RUN_A'),artifact_digest:undefined};assert.throws(()=>registry[sample.producer_id].produce({catalog,proof_contract_id:sample.proof_contract_id,context:missingContext,source:buildSyntheticPerRunSourceV1({...syntheticContextV1('RUN_A')})}),/WITNESS_PROVENANCE_MISSING:artifact_digest/);const mismatchContext=syntheticContextV1('RUN_A');const mismatchSource=buildSyntheticPerRunSourceV1(mismatchContext);mismatchSource.provenance.artifact_digest='sha256:'+'0'.repeat(64);assert.throws(()=>registry[sample.producer_id].produce({catalog,proof_contract_id:sample.proof_contract_id,context:mismatchContext,source:mismatchSource}),/WITNESS_SOURCE_BINDING:artifact_digest/);
 const finalizerPaths=boundary.changed_files.filter((f)=>/final.*ledger.*settlement|ledger.*finalizer/i.test(f));assert.equal(finalizerPaths.length,0,'FINALIZER_FORBIDDEN');const producerDir=path.join(ROOT,'scripts/governance_acceptance/mcft_cap08_s6_witness');const producerFiles=fs.readdirSync(producerDir).filter((f)=>f.endsWith('_witness_v1.cjs'));const sourceText=producerFiles.map((f)=>fs.readFileSync(path.join(producerDir,f),'utf8')).join('\n');assert.equal((sourceText.match(/HA-\d{2}/g)||[]).length,0,'HANDWRITTEN_HA_ID');for(const item of catalog.ledger.items)assert.equal(sourceText.includes(item.requirement),false,`HANDWRITTEN_REQUIREMENT:${item.requirement}`);
 const result={schema_version:'geox_mcft_cap08_s6_witness_producer_result_v1',status:'PASS',subject_sha:local?'LOCAL_REPLAY':git('rev-parse','HEAD'),base_sha:local?'LOCAL_REPLAY':base,ledger_item_count:catalog.ledger.item_count,proof_contract_count:entries.length,producer_count:Object.keys(registry).length,implemented_per_run_producer_count:active.length,deferred_by_authority_producer_count:deferredModules.length,synthetic_per_run_contract_witness_count:witnesses.length,handwritten_ha_id_count:0,handwritten_requirement_count:0,wrong_phase_status:'NOT_YET_ELIGIBLE',pass_without_artifact_forbidden:true,source_binding_required:true,closure_manifest_ref_required:true,global_count_forbidden:true,finalizer_present:false,cross_run_comparator_implemented:false,merge_tree_witness_implemented:false,r2_retention_witness_implemented:false,dual_run_ci_authorized:false,final_formal_closure_run_authorized:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};write(result);console.log(JSON.stringify(result,null,2));
}catch(e){write({schema_version:'geox_mcft_cap08_s6_witness_producer_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1;}
