// scripts/governance_acceptance/ACCEPTANCE_ROOT_ZONE_IRRIGATION_SCENARIO_MODEL_BOUNDARY_V1.cjs
const fs = require("node:fs"); require("tsx/cjs");
const name = "ACCEPTANCE_ROOT_ZONE_IRRIGATION_SCENARIO_MODEL_BOUNDARY_V1";
const file = "apps/server/src/domain/soil_water/root_zone_irrigation_scenario_builder_v1.ts";
const forbiddenTokens = ['from "pg"','require("pg")','express','router','app.get','app.post','process.env','Date.now','new Date','randomUUID','recommendation','approval','operation_plan','ao_act','dispatch','roi_ledger','field_memory','INSERT INTO facts'];
function fail(m,d){console.error(`[${name}] FAIL: ${m}`); if(d) console.error(JSON.stringify(d,null,2)); process.exit(1)}
function assert(c,m,d){if(!c) fail(m,d)}
const text=fs.readFileSync(file,"utf8"); assert(text.startsWith(`// ${file}`),"builder must start with path comment"); for(const t of forbiddenTokens) assert(!text.includes(t),`forbidden token found: ${t}`);
const { buildRootZoneIrrigationScenarioSetV1 } = require(`${process.cwd()}/${file}`);
const scope={tenant_id:"tenant_a",project_id:"project_a",group_id:"group_a",field_id:"field_a",zone_id:"zone_a"}; const computed_at="2026-06-21T00:00:00.000Z";
function forecast(over={}){ const daily=[0,1,2,3,4,5,6].map(i=>({day_index:i,date:`2026-06-${21+i}`,precipitation_mm:0,effective_precipitation_mm:0,et0_mm:5,crop_coefficient:1,estimated_crop_et_mm:5,net_water_change_mm:i===0?-5:-5,projected_available_water_mm:45-(i*5),projected_available_water_fraction:(45-(i*5))/100,forecast_water_status:(45-(i*5))/100<0.25?"STRESS":"LIMITED_AVAILABLE",bound_applied:"NONE"})); return {forecast_id:"forecast_a",...scope,source_state_id:"state_a",source_state_ref:"state_a",weather_forecast_ref:"wx",baseline_mode:"NO_NEW_ACTION",horizon_days:7,root_zone_depth_cm:60,root_zone_available_water_capacity_mm:100,initial_available_water_fraction:0.5,initial_weighted_matric_potential_kpa:-50,daily_forecast:daily,min_available_water_fraction:0.15,max_available_water_fraction:0.45,first_stress_date:"2026-06-26",stress_day_count:2,limited_day_count:5,forecast_status:"ESTIMATED",blocking_reasons:[],calculation_inputs:{},derivation:{},confidence:{level:"HIGH",score:.9,basis:"test"},computed_at,determinism_hash:"forecast_hash",...over}; }
function build(over={}){return buildRootZoneIrrigationScenarioSetV1({...scope,sourceForecast:forecast(),application_efficiency:.8,computed_at,...over})}
const out=build(); assert(out.input_status==="COMPARABLE","valid scenario set returns COMPARABLE"); assert(JSON.stringify(out)===JSON.stringify(build()),"same input returns identical output"); assert(out.options.length===5,"exactly five fixed options");
const no=out.options.find(o=>o.option_id==="NO_ACTION"); assert(JSON.stringify(no.daily_projection.map(d=>d.projected_available_water_mm))===JSON.stringify(forecast().daily_forecast.map(d=>d.projected_available_water_mm)),"NO_ACTION reproduces baseline");
const i10=out.options.find(o=>o.option_id==="IRRIGATE_10MM_DAY0"), i20=out.options.find(o=>o.option_id==="IRRIGATE_20MM_DAY0"), del=out.options.find(o=>o.option_id==="DELAY_3_DAYS_THEN_IRRIGATE_20MM");
assert(i10.daily_projection[0].projected_available_water_fraction>i10.daily_projection[0].baseline_available_water_fraction,"IRRIGATE_10MM_DAY0 improves AWF vs baseline");
assert(i20.daily_projection[0].projected_available_water_fraction>i10.daily_projection[0].projected_available_water_fraction,"IRRIGATE_20MM_DAY0 improves AWF more than 10mm");
assert(del.irrigation_events[0].day_index===3 && del.daily_projection[3].delta_vs_baseline_fraction>0,"delayed option applies event on day 3");
assert(build({sourceForecast:forecast({root_zone_available_water_capacity_mm:50,daily_forecast:forecast().daily_forecast.map(d=>({...d,projected_available_water_mm:45,projected_available_water_fraction:.9,net_water_change_mm:0}))})}).options.find(o=>o.option_id==="IRRIGATE_30MM_DAY0").daily_projection[0].bound_applied==="UPPER_BOUND","upper bound is recorded");
assert(build({application_efficiency:0}).input_status==="INVALID_INPUT","invalid application_efficiency returns INVALID_INPUT"); assert(build({sourceForecast:forecast({zone_id:"other"})}).input_status==="INVALID_INPUT","source forecast scope mismatch returns INVALID_INPUT"); assert(build({sourceForecast:forecast({forecast_status:"UNKNOWN"})}).input_status==="INSUFFICIENT_FORECAST","forecast_status not ESTIMATED returns INSUFFICIENT_FORECAST"); assert(build({sourceForecast:forecast({daily_forecast:forecast().daily_forecast.slice(0,6)})}).input_status==="INSUFFICIENT_FORECAST","daily_forecast length not 7 returns INSUFFICIENT_FORECAST"); assert(build({sourceForecast:forecast({daily_forecast:forecast().daily_forecast.map((d,i)=>i===1?{...d,day_index:0}:d)})}).input_status==="INVALID_INPUT","duplicate day_index returns INVALID_INPUT"); assert(build({sourceForecast:forecast({daily_forecast:forecast().daily_forecast.map((d,i)=>i===1?{...d,date:"2026-06-21"}:d)})}).input_status==="INVALID_INPUT","duplicate date returns INVALID_INPUT"); assert(build({sourceForecast:forecast({determinism_hash:""})}).input_status==="INSUFFICIENT_FORECAST","missing source forecast determinism_hash returns INSUFFICIENT_FORECAST");
console.log(`[${name}] PASS`);
