#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),fs=require('node:fs'),p=require('node:path'),{execFileSync}=require('node:child_process');
const B='b3f095be7f808611f1388c3e31ecff29325a7f99',W='.github/workflows/mcft-cap-09-s2-database-evidence-ingress.yml',D='docs/digital_twin/mcft/cap_09/',T=D+'GEOX-MCFT-CAP-09-S2-DELIVERY-STATUS-V1.json',C=D+'GEOX-MCFT-CAP-09-S2-DATABASE-EVIDENCE-INGRESS-CONFIG-V1.json',N=D+'GEOX-MCFT-CAP-09-S2-DATABASE-EVIDENCE-INGRESS-CANDIDATE-V1.json',Y=D+'GEOX-MCFT-CAP-09-S2-DATABASE-EVIDENCE-INGRESS-CANDIDATE-BOUNDARY-V1.json',H=D+'GEOX-MCFT-CAP-09-S2-HARD-ACCEPTANCE-EVIDENCE-V1.json',P=D+'GEOX-MCFT-CAP-09-S2-PREDECESSOR-ATTESTATION-CONSUMPTION-V1.json',S='apps/server/src/runtime/twin_runtime/postgres_evidence_ingress_adapter_v1.ts',V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_DATABASE_EVIDENCE_INGRESS.cjs',X='scripts/runtime_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_DATABASE_EVIDENCE_INGRESS.ts';
const F=[W,S,C,N,Y,T,H,P,V,X].sort(),SN=F.filter(x=>x!==W).sort(),O='acceptance-output/MCFT_CAP_09_S2_DATABASE_EVIDENCE_INGRESS_RESULT.json';
const git=(...x)=>execFileSync('git',x,{encoding:'utf8'}).trim(),read=x=>fs.readFileSync(x,'utf8'),j=x=>JSON.parse(read(x)),ok=(v,m)=>{if(!v)throw Error(m)},same=(x,y,m)=>{try{a.deepEqual(x,y)}catch{throw Error(m)}};
function out(x){fs.mkdirSync(p.dirname(O),{recursive:true});fs.writeFileSync(O,JSON.stringify(x,null,2)+'\n')}
function art(n){const q=[p.resolve(process.env.MCFT_CAP09_S1_EFFECTIVE_ARTIFACT_DIR||'acceptance-input/cap09-s1-effective')];while(q.length){const d=q.pop();if(!fs.existsSync(d))continue;for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=p.join(d,e.name);if(e.isDirectory())q.push(f);else if(e.name===n)return f}}throw Error('ARTIFACT_MISSING:'+n)}
function dec(body){const m=['MCFT','CANDIDATE','DECLARATION','V2'].join('_'),o=`<!-- ${m}\n`,s=String(body||''),i=s.indexOf(o),e=s.indexOf('-->',i),r={};ok(i>=0&&e>i&&s.indexOf(o,i+1)<0,'DECLARATION');for(const l0 of s.slice(i+o.length,e).split(/\r?\n/)){const l=l0.trim(),k=l.indexOf('=');if(l){ok(k>0,'DECLARATION_LINE');r[l.slice(0,k)]=l.slice(k+1)}}return r}
async function api(n){ok(process.env.GITHUB_TOKEN&&process.env.GITHUB_REPOSITORY,'GITHUB_ENV');const r=await fetch(`https://api.github.com/repos/${process.env.GITHUB_REPOSITORY}/pulls/${n}`,{headers:{Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,Accept:'application/vnd.github+json','User-Agent':'geox-cap09-s2'}}),t=await r.text();ok(r.ok,'GITHUB_'+r.status);return JSON.parse(t)}
(async()=>{try{
 const base=process.env.MCFT_BASE_SHA,head=git('rev-parse','HEAD');ok(base===B,'BASE');same(git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),F,'FILES');if(process.env.MCFT_EVENT_NAME==='pull_request')ok(git('rev-list','--count',`${base}..HEAD`)==='1','COMMITS');
 const marker=['MCFT','CANDIDATE','DECLARATION','V2'].join('_');for(const f of F)ok(!read(f).includes(marker),'DECLARATION_IN_REPO:'+f);
 const old=JSON.parse(git('show',`${base}:${T}`)),st=j(T),cf=j(C),ca=j(N),bd=j(Y),ha=j(H),pr=j(P);ok(!old.s2_candidate_implemented&&st.s2_candidate_implemented,'SIGNAL');ok(st.candidate_declaration_present&&!st.externally_effective&&st.repository_evidence_envelope_bound&&st.real_postgresql_acceptance_required,'STATUS');
 for(const k of ['implementation_authorized','runtime_source_authorized','live_ingestion_authorized','background_scheduler_authorized','canonical_write_authorized','public_http_writer_authorized','model_activation_authorized','controlled_action_authorized'])ok(st[k]===false,'AUTH:'+k);
 ok(ca.base_main_sha===B&&ca.focused_workflow_blob_sha==='dbce1dc1187c1b7b8eb5dadc6efd25187b89eaf9'&&ca.repository_evidence_envelope==='FACTS_TYPE_PLUS_CANONICAL_REPLAY_PAYLOAD_V1'&&ca.window_rule==='OPEN_START_CLOSED_END_PT1H_V1'&&ca.real_postgresql_acceptance_mode==='REAL_POSTGRESQL_ISOLATED_FACTS_READBACK','CANDIDATE');
 ok(bd.changed_file_count===10&&bd.real_postgresql_acceptance_delta===1&&!bd.external_effectiveness,'BOUNDARY');same(bd.changed_files,F,'BOUNDARY_FILES');ok(cf.source_table==='facts'&&cf.read_only&&cf.scope_keys.length===6&&cf.boundary_fields.length===3&&cf.exclusion_reasons.length===7&&cf.future_forcing_policy==='ISSUED_INGESTED_AVAILABLE_BY_BOUNDARY_IS_ELIGIBLE','CONFIG');ok(ha.required_check_count===16&&!ha.future_evidence_leakage&&!ha.database_write_performed&&!ha.scheduler_loop_executed&&!ha.canonical_write_performed,'HARD');
 const att=JSON.parse(fs.readFileSync(art('MCFT_CAP_09_S1_EXACT_SHA_ATTESTATION.json'),'utf8')),loc=JSON.parse(fs.readFileSync(art('MCFT_CAP_09_S1_ATTESTATION_RETENTION_LOCATOR.json'),'utf8'));ok(att.status==='PASS'&&att.subject_sha==='843ed078d6d384e43e2c6bd2568d789dcd508934'&&att.semantic_artifact_digest==='sha256:0f67da5732f43a427d2518e320a617f3ad3872c6c34065060e432d92128404ef','S1');ok(loc.retention_level==='R2'&&loc.readback_verified&&loc.locked_version_delete_denied&&pr.subject_sha===att.subject_sha,'S1_R2');
 const src=read(S),rt=read(X),wf=read(W);for(const z of ['BEGIN TRANSACTION READ ONLY','FROM facts','FACTS_TYPE_PLUS_CANONICAL_REPLAY_PAYLOAD_V1','OPEN_START_CLOSED_END_PT1H_V1','EVIDENCE_IDENTITY_CONFLICT','outside_window_evidence_refs','out_of_order_evidence_refs'])ok(src.includes(z),'SOURCE:'+z);for(const z of ['REAL_POSTGRESQL_ISOLATED_FACTS_READBACK','future weather known at boundary must remain eligible','EVIDENCE_IDENTITY_CONFLICT:soil-0915'])ok(rt.includes(z),'RUNTIME:'+z);for(const z of ['image: postgres:16','Run real PostgreSQL Evidence ingress acceptance','MCFT_CAP_09_S2_POSTGRESQL_ACCEPTANCE_RESULT.json'])ok(wf.includes(z),'WORKFLOW:'+z);
 let d={mode:'MERGE_GROUP_POLICY'};if(process.env.MCFT_EVENT_NAME==='pull_request'){const n=Number(process.env.MCFT_PR_NUMBER),pull=await api(n),x=dec(pull.body);ok(pull.head.sha===head&&pull.base.sha===base,'PR');ok(x.capability_line==='MCFT-CAP-09'&&x.slice_id==='MCFT-CAP-09.S2'&&x.status_file===T&&x.candidate_field==='s2_candidate_implemented'&&x.candidate_value==='true'&&x.focused_workflow==='mcft-cap-09-s2-database-evidence-ingress'&&x.standard_workflow==='ci'&&x.candidate_head===head&&x.base_head===base,'DECLARATION_BINDING');const files=x.semantic_snapshot_files.split(','),blobs=x.semantic_snapshot_blobs.split(',');same(files,SN,'SNAP_FILES');same(blobs,files.map(f=>git('rev-parse',`HEAD:${f}`)),'SNAP_BLOBS');d={mode:'PR_BODY_VALIDATED',pr_number:n,semantic_snapshot_count:files.length}}
 const r={status:'PASS',change_class:'MCFT_CAP_09_S2_DATABASE_EVIDENCE_INGRESS_CANDIDATE',base_sha:base,head_sha:head,changed_files:F,exact_new_candidate_signal_count:1,repository_evidence_envelope_bound:true,database_read_adapter_implemented:true,real_postgresql_acceptance_required:true,database_write_performed:false,future_evidence_leakage_blocked:true,scheduler_loop_executed:false,canonical_write_performed:false,production_wiring_present:false,runtime_source_delta:1,runtime_executable_delta:1,migration_delta:0,external_effectiveness:false,declaration:d,first_legal_next_action:'PROTECTED_MERGE_THEN_EXACT_SHA_R2_ATTESTATION'};out(r);console.log(JSON.stringify(r,null,2));
}catch(e){const r={status:'FAIL',base_sha:process.env.MCFT_BASE_SHA||null,error:String(e.message||e)};out(r);console.error(JSON.stringify(r,null,2));process.exitCode=1}})();
