#!/usr/bin/env node
'use strict';
const {A,paths,text,json,sem,output,candidate}=require('./mcft_cap08_s6_final_replacement_authority_common_v1.cjs');
const {manifest,authority,issuance}=require('./mcft_cap08_s6_final_replacement_authority_checks_v1.cjs');
try{
 const b=json(paths.B),i=json(paths.I),m=json(paths.M),a=json(paths.A),z=json(paths.Z);A.equal(b.semantic_digest,sem(b),'BOUNDARY:DIGEST');const base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim();A.equal(base,b.base_main_sha);const h=candidate(base,b);
 const bv={changed_file_count:9,governance_file_count:8,workflow_file_count:1,runtime_source_file_count:0,migration_file_count:0,qualification_file_count:0,database_execution_workflow_file_count:0,database_execution_performed:false,workflow_dispatch_present:false,run_authority_candidate_record_count:2,executable_authority_record_count:0,authority_candidate_cardinality:1,authority_effectiveness_included:false,formal_database_execution_authorized_before_effectiveness:false,v10_identifier_assigned:false,qualification_v3_authorized:false,s6_candidate_implemented:false,stage_1a_end_to_end_closure_established:false};for(const[k,v]of Object.entries(bv))A.equal(b[k],v,`BOUNDARY:${k}`);
 const ref=manifest(base,h,m,paths.M);authority(a,{base,label:'RUN_A',op:'MCFT-CAP-08-S6-FORMAL-RUN-A-20260802-001',db:'MCFT-CAP-08-S6-FORMAL-DB-A-20260802-001',tpl:'geox_mcft_cap08_s6_run_a_<github_run_id>',pre:'AUTHORITY_EFFECTIVENESS_MERGED'},ref);authority(z,{base,label:'RUN_B',op:'MCFT-CAP-08-S6-FORMAL-RUN-B-20260802-002',db:'MCFT-CAP-08-S6-FORMAL-DB-B-20260802-002',tpl:'geox_mcft_cap08_s6_run_b_<github_run_id>',pre:'RUN_A_TERMINAL_SUCCESS'},ref);issuance(base,i,ref,a,z);A.notEqual(a.operational_run_instance_id,z.operational_run_instance_id);A.notEqual(a.logical_database_identity.identity_id,z.logical_database_identity.identity_id);
 const w=text(paths.W);A.match(w,/pull_request:/);A.doesNotMatch(w,/workflow_dispatch:|postgres|psql|DATABASE_URL|workflow_call:/i);A.match(w,/ACCEPTANCE_MCFT_CAP_08_S6_FINAL_REPLACEMENT_FORMAL_EXECUTION_AUTHORITY_V1\.cjs/);
 const r={schema_version:'geox_mcft_cap08_s6_final_replacement_formal_execution_authority_result_v1',status:'PASS',base_main_sha:base,exact_head_sha:h,changed_file_count:9,authority_candidate_cardinality:1,sibling_run_authority_candidate_count:2,executable_authority_record_count:0,run_a_operational_identity:a.operational_run_instance_id,run_b_operational_identity:z.operational_run_instance_id,one_shot_contract_present:true,no_rerun_contract_present:true,max_parallel_one:true,exact_product_and_port_blobs_pinned:true,generic_cap04_unchanged:true,corrected_t16_remained_non_latest:true,qualification_v3_authorized:false,authority_effective:false,runtime_gate_eligible_before_effectiveness:false,database_execution_performed:false,workflow_dispatch_performed:false,next_action_after_merge:'ESTABLISH_FINAL_REPLACEMENT_FORMAL_EXECUTION_AUTHORITY_EFFECTIVENESS'};output(r);console.log(JSON.stringify(r,null,2));
}catch(e){output({schema_version:'geox_mcft_cap08_s6_final_replacement_formal_execution_authority_result_v1',status:'FAIL',error:e?.stack||String(e)});console.error(e);process.exitCode=1}
