#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA1H_KBS_RAW_HOURLY_LIVE_PROBE_STATIC_RESULT.json'),BASE=process.env.MCFT_BASE_SHA||'HEAD^';
const CONFIG='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA1H-KBS-RAW-HOURLY-LIVE-PROBE-V1.json',PROBE='scripts/runtime_acceptance/PROBE_MCFT_CAP_09_EA1H_KBS_RAW_HOURLY_LIVE.mjs';
const EA1E='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA1E-KBS-TRANSIENT-ROLE-MAP-PROBE-V1.json',EA1E_BLOB='69835c9877474f4d46980487f6e5789add803df2';
const EA1F='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA1F-ENVIROWEATHER-API-DISCOVERY-V1.json',EA1F_BLOB='2366f581f30bae465d6591d71c81a7ad2a25ace7';
const FILES=['.github/workflows/mcft-cap-09-ea1h-kbs-raw-hourly-live-probe.yml',CONFIG,'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_EA1H_KBS_RAW_HOURLY_LIVE_PROBE.cjs',PROBE].sort();
const git=(args)=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8'}).trim(),read=(p)=>fs.readFileSync(path.join(ROOT,p),'utf8'),json=(p)=>JSON.parse(read(p));
function write(v){fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,`${JSON.stringify(v,null,2)}\n`);}
try{
 const changed=git(['diff','--name-only',`${BASE}...HEAD`]).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(changed,FILES,'EA1H_EXACT_FOUR_FILE_BOUNDARY_REQUIRED');assert.equal(changed.length,4,'EA1H_EXACT_FILE_COUNT_REQUIRED');
 assert(!changed.some(f=>/(^|\/)(apps|packages)\//.test(f)),'EA1H_RUNTIME_PRODUCT_SOURCE_DELTA_FORBIDDEN');assert(!changed.some(f=>/migration/i.test(f)),'EA1H_MIGRATION_DELTA_FORBIDDEN');assert(!changed.some(f=>/MCFT-CANDIDATE-AUTHORITY-REGISTRY|MCFT-DELIVERY-POLICY/.test(f)),'EA1H_DELIVERY_AUTHORITY_DELTA_FORBIDDEN');
 const ea1eBlob=git(['rev-parse',`${BASE}:${EA1E}`]),ea1fBlob=git(['rev-parse',`${BASE}:${EA1F}`]);assert.equal(ea1eBlob,EA1E_BLOB,'EA1H_EXACT_EA1E_BASE_AUTHORITY_REQUIRED');assert.equal(ea1fBlob,EA1F_BLOB,'EA1H_EXACT_EA1F_BASE_AUTHORITY_REQUIRED');
 const c=json(CONFIG),p=read(PROBE).replace(/\s+/g,''),packageJson=json('package.json'),signal=json('docs/digital_twin/mcft/MCFT-DELIVERY-CANDIDATE-SIGNAL-CONTRACT-V1.json');
 assert.equal(c.capability_line_id,'MCFT-CAP-09');assert.equal(c.slice_id,'MCFT-CAP-09.S6');assert.equal(c.base_main_sha,'c01b61bcd688632ea4a8bcc355cc2e3efdf98dfb');
 assert.equal(c.source.provider,'KBS_LTER');assert.equal(c.source.official_page,'https://lter.kbs.msu.edu/datatables/13');assert.equal(c.source.download_locator.required_resolved_path,'/datatables/13.csv');assert.equal(c.source.direct_bcse_g1r1_field_equivalence,false);assert.equal(c.source.direct_root_zone_equivalence,false);
 assert.equal(c.source.station_coordinates_authority.latitude,42.408537);assert.equal(c.source.station_coordinates_authority.longitude,-85.373637);assert.equal(c.source.near_station_elevation_authority.value_m,286.43);assert.equal(c.source.near_station_elevation_authority.exact_sensor_elevation_claimed,false);assert.equal(c.source.near_station_elevation_authority.may_be_used_as_formal_et0_pressure_input_without_later_adjudication,false);
 assert.equal(c.role_semantics.rainfall.provider_unit,'mm');assert.equal(c.role_semantics.solar_radiation.provider_unit_authority,'PENDING');assert.equal(c.role_semantics.solar_radiation.formal_canonicalization_allowed,false);assert.equal(c.role_semantics.wind_speed.provider_measurement_height_m,10);assert.equal(c.role_semantics.wind_speed.formal_wind_height_adjustment_authority,'PENDING_EA1I');
 assert.equal(c.role_semantics.relative_humidity.invalid_or_out_of_range_value_semantics,'MISSING_NOT_CLIPPED_NOT_IMPUTED');assert.equal(c.role_semantics.absolute_humidity_or_partial_pressure.formal_et0_use_allowed,false);assert.equal(c.role_semantics.barometric_pressure.formal_et0_use_allowed,false);
 assert.equal(c.et0_readiness.algorithm_id,'ASCE_STANDARDIZED_REFERENCE_ET_SHORT_HOURLY_V1');assert.equal(c.et0_readiness.status,'INCOMPLETE_PENDING_EA1I_HUMIDITY_AND_PRESSURE_OR_ELEVATION_AUTHORITY');assert.equal(c.et0_readiness.ea1h_may_claim_complete_et0_input_bundle,false);assert.equal(c.et0_readiness.pressure_or_elevation_path_per_amendment,true);assert.equal(c.et0_readiness.rh_sentinel_or_invalid_value_may_be_clipped,false);assert.equal(c.et0_readiness.rh_missing_interval_may_be_silently_imputed,false);assert.equal(c.et0_readiness.ah_may_be_relabelled_vapor_pressure_without_authority,false);assert.equal(c.et0_readiness.barometer_unit_may_be_guessed_from_values,false);
 assert.equal(c.freshness_and_continuity.latest_record_max_age_hours,6);assert.equal(c.freshness_and_continuity.recent_window_hours,30);for(const key of ['minimum_recent_distinct_hours','minimum_recent_numeric_rain_hours','minimum_recent_numeric_solar_hours','minimum_recent_numeric_wind_hours','minimum_recent_numeric_air_temperature_hours'])assert.equal(c.freshness_and_continuity[key],24,`EA1H_THRESHOLD_REQUIRED:${key}`);
 assert.equal(c.data_use_policy.provider_payload_may_be_committed,false);assert.equal(c.data_use_policy.provider_payload_may_be_uploaded_as_ci_artifact,false);assert.equal(c.data_use_policy.raw_numeric_values_may_be_emitted,false);assert.equal(c.qualification_effect.probe_may_establish,'KBS_RAW_HOURLY_MACHINE_FRESHNESS_AND_NON_CANONICAL_ROLE_CONTINUITY_ONLY');assert.equal(c.qualification_effect.et0_bundle_must_remain_incomplete,true);assert.equal(c.qualification_effect.formal_source_authority_created,false);assert.equal(c.qualification_effect.qualified_formal_site,false);assert.equal(c.qualification_effect.formal_window_started,false);
 assert.equal(packageJson.devDependencies['@playwright/test'],'^1.60.0','EA1H_PLAYWRIGHT_DEPENDENCY_REQUIRED');
 for(const marker of ["import{chromium}from'@playwright/test'","getByRole('link',{name:CONFIG.source.download_locator.anchor_text})",'ensureOfficialDownload','EA1H_COMPLETE_ET0_CLAIM_FORBIDDEN','EA1H_SOURCE_TOO_OLD:','EA1H_RECENT_RAIN_CONTINUITY_INSUFFICIENT:','EA1H_RECENT_SOLAR_ROLE_CONTINUITY_INSUFFICIENT:','EA1H_RECENT_WIND_ROLE_CONTINUITY_INSUFFICIENT:','EA1H_RECENT_AIR_ROLE_CONTINUITY_INSUFFICIENT:','complete_et0_input_bundle:\'INCOMPLETE_PENDING_EA1I_HUMIDITY_AND_PRESSURE_OR_ELEVATION_AUTHORITY\'','rh_invalid_values_clipped_or_imputed:false','ah_relabelled_as_vapor_pressure:false','barometer_unit_guessed:false','raw_provider_payload_persisted:false','database_write_count:0','formal_evidence_write_count:0','formal_window_started:false'])assert(p.includes(marker),`EA1H_PROBE_MARKER_REQUIRED:${marker}`);
 for(const forbidden of ['DATABASE_URL','INSERT INTO','public.facts','GEOX_MCFT_CAP09_S6_DATABASE_URL',"from'pg'",'from"pg"'])assert(!p.includes(forbidden.replace(/\s+/g,'')),`EA1H_DATABASE_OR_FORMAL_WRITE_FORBIDDEN:${forbidden}`);
 assert(!signal.explicit_candidate_status_values.includes(c.record_status),'EA1H_UNREGISTERED_CANDIDATE_STATUS_FORBIDDEN');
 write({schema_version:'geox_mcft_cap09_ea1h_kbs_raw_hourly_static_acceptance_v1',status:'PASS',base_sha:BASE,ea1e_blob_sha:ea1eBlob,ea1f_blob_sha:ea1fBlob,changed_files:changed,exact_file_count:changed.length,claim_scope:'MACHINE_FRESHNESS_AND_NON_CANONICAL_ROLE_CONTINUITY_ONLY',et0_bundle_required_incomplete:true,solar_unit_authority_pending:true,wind_height_adjustment_pending:true,humidity_authority_pending:true,pressure_or_elevation_authority_pending:true,runtime_product_source_delta:0,migration_delta:0,database_write_delta:0,formal_evidence_write_delta:0,formal_window_started:false});
}catch(e){write({schema_version:'geox_mcft_cap09_ea1h_kbs_raw_hourly_static_acceptance_v1',status:'FAIL',error:e?.message||String(e)});console.error(e);process.exitCode=1;}
