#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),c=require('node:child_process'),f=require('node:fs'),p=require('node:path');
const R=p.resolve(__dirname,'../..'),O=p.join(R,'acceptance-output/MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION_RESULT.json');
const B='d4d27418dfd76d080c8a82a698e6e497f1279b45',H='929d05b44cc705b31b2d28ca215d9f6aa45e503e',M='2a04103febcc39036a34193b46a0feb879d686e4';
const W='.github/workflows/mcft-cap-08-s2-pre-candidate-foundation.yml',A='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION.cjs',S='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S2-DELIVERY-STATUS-V1.json',G='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S2-PRE-CANDIDATE-ENTRY-GATES-V1.json';
const F=[
'.github/workflows/mcft-cap-07-s0-authorization.yml','.github/workflows/mcft-cap-07-s4-api.yml','.github/workflows/mcft-cap-07-s6-closure.yml','.github/workflows/mcft-cap-08-authority-reconciliation.yml','.github/workflows/mcft-cap-08-s1-base-runtime.yml',W,S,G,A,
'scripts/governance_acceptance/MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1.cjs','scripts/governance_acceptance/MCFT_SYNTHETIC_MERGE_ATTESTATION_HARNESS_V1.cjs','scripts/governance_acceptance/MCFT_ATTESTATION_RETENTION_LOCAL_BACKEND_V1.cjs'].sort();
const Z=F.filter(x=>![W,S,G,A].includes(x));
const git=x=>c.execFileSync('git',x,{cwd:R,encoding:'utf8'}).trim(),j=x=>JSON.parse(f.readFileSync(p.join(R,x),'utf8')),t=x=>f.readFileSync(p.join(R,x),'utf8');
function out(x){f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(x,null,2)+'\n')}
function files(b,h){const q=git(['diff','--name-only',`${b}...${h}`]);return q?q.split(/\r?\n/).filter(Boolean).sort():[]}
function history(){a.deepEqual(git(['rev-list','--parents','-n','1',M]).split(/\s+/),[M,B,H]);a.equal(git(['rev-parse',`${H}^{tree}`]),git(['rev-parse',`${M}^{tree}`]));a.equal(Number(git(['rev-list','--count',`${B}..${H}`])),1);a.deepEqual(files(B,H),F);return{base:B,candidate:H,merge:M,candidate_to_merge_tree_delta:0}}
function workflow(){const q=t(W);a.doesNotMatch(q,/^\s*workflow_dispatch\s*:/m);for(const x of['FOUNDATION_LIFECYCLE_MODE','WORKFLOW_LIFECYCLE_REMEDIATION_MODE','SUCCESSOR_REGRESSION_MODE','ACCEPTANCE_MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION.cjs'])a.ok(q.includes(x));return{workflow_dispatch:false,classifier:'DEDICATED_FAIL_CLOSED'}}
function mode(b,h){a.match(b,/^[0-9a-f]{40}$/);a.match(h,/^[0-9a-f]{40}$/);a.equal(git(['merge-base',b,h]),b);const q=files(b,h);if(b===B&&h===H)return['EXACT_FOUNDATION_MODE',q];if(b===M&&Number(git(['rev-list','--count',`${b}..${h}`]))===1&&JSON.stringify(q)===JSON.stringify([W,A].sort()))return['WORKFLOW_LIFECYCLE_REMEDIATION_MODE',q];git(['merge-base','--is-ancestor',M,b]);git(['merge-base','--is-ancestor',M,h]);a.ok(!q.includes(W)&&!q.includes(A));return['SUCCESSOR_REGRESSION_MODE',q]}
function frozen(){const d=[];for(const x of Z){const h=git(['rev-parse',`${M}:${x}`]),n=git(['rev-parse',`HEAD:${x}`]);if(h!==n)d.push({file:x,historical_blob:h,current_blob:n})}a.deepEqual(d,[]);return{file_count:Z.length,mismatches:d}}
function state(m){const s=j(S),g=j(G),x=Object.fromEntries(g.gates.map(y=>[y.gate_id,y.state]));a.equal(s.s2_candidate_implemented,false);a.equal(s.independent_review_satisfied,false);a.equal(s.independent_review_required_before_formal_s2_candidate,true);a.equal(s.production_runtime_source_authorized,false);a.equal(s.mcft_cap_09_authorized,false);a.equal(g.s2_candidate_transition_authorized,false);a.equal(g.production_runtime_source_authorized,false);a.equal(g.mcft_cap_09_authorized,false);
 if(m==='SUCCESSOR_REGRESSION_MODE'){a.equal(s.g1_state,'PASS_PRESENT_ON_MAIN');a.equal(s.g2_state,'PASS_PRESENT_ON_MAIN');a.equal(x['S2-G1-SYNTHETIC-MERGE-ATTESTATION'],'PASS_FOUNDATION_PRESENT_ON_MAIN');a.equal(x['S2-G2-REGISTRY-DRIVEN-LIFECYCLE'],'PASS_FOUNDATION_PRESENT_ON_MAIN')}
 else{a.equal(s.pre_candidate_foundation_merge_authorized_by_contract,true);a.equal(s.formal_candidate_creation_authorized,false);a.equal(x['S2-G1-SYNTHETIC-MERGE-ATTESTATION'],'PRODUCTION_LOGIC_LOCAL_BACKEND_HARNESS_IMPLEMENTED_PENDING_PROTECTED_MERGE');a.equal(x['S2-G2-REGISTRY-DRIVEN-LIFECYCLE'],'FAIL_CLOSED_LIFECYCLE_REMEDIATION_IMPLEMENTED_PENDING_PROTECTED_MERGE')}
 return{g1:x['S2-G1-SYNTHETIC-MERGE-ATTESTATION'],g2:x['S2-G2-REGISTRY-DRIVEN-LIFECYCLE'],s2_candidate_implemented:false,s3_authorized:false}}
try{const b=String(process.env.MCFT_BASE_SHA||''),h=String(process.env.MCFT_CANDIDATE_SHA||git(['rev-parse','HEAD']));a.equal(git(['rev-parse','HEAD']),h);a.equal(git(['diff','--check',`${b}...${h}`]),'');const[m,q]=mode(b,h),r={schema_version:'geox_mcft_cap08_s2_pre_candidate_foundation_lifecycle_result_v3',status:'PASS',classification:m,base_sha:b,candidate_sha:h,changed_file_count:q.length,changed_files:q,historical_foundation:history(),workflow_lifecycle:workflow(),regression:m==='EXACT_FOUNDATION_MODE'?{exact_historical_boundary:true}:{frozen_g1_g2:frozen(),machine_state:state(m)},g1_state:'PASS_PRESENT_ON_MAIN',g2_state:'PASS_PRESENT_ON_MAIN',formal_s2_candidate:false,s2_effective:false,s3_authorized:false};out(r);console.log(JSON.stringify(r))}catch(e){out({schema_version:'geox_mcft_cap08_s2_pre_candidate_foundation_lifecycle_result_v3',status:'FAIL',error:e.message});console.error(e);process.exitCode=1}
