#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),{execFileSync:E}=require('node:child_process');
const R=P.resolve(__dirname,'../..'),B='fd8ade2b8511daa5f4d44f3dcc78bc059b46e0c3',H='8457c8201ae21cd032f53e441aee349dcbe337dc',S='d91a1fb52cf4ea3f1f0650f664f4ce94667e1a59',I='MCFT-CAP-08-S6-FORMAL-RUN-A-20260802-REPLACEMENT-003';
const O=P.join(R,'acceptance-output/MCFT_CAP_08_S6_LOADER_CORRECTED_RUN_A_AUTHORITY_EFFECTIVENESS_RESULT.json');
const X={w:'.github/workflows/mcft-cap-08-s6-loader-corrected-run-a-authority-effectiveness.yml',e:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-LOADER-CORRECTED-FORMAL-RUN-A-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',s:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-LOADER-CORRECTED-RUN-A-AUTHORITY-EFFECTIVENESS-V1.json',b:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-LOADER-CORRECTED-RUN-A-AUTHORITY-EFFECTIVENESS-BOUNDARY-V1.json',v:'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_LOADER_CORRECTED_RUN_A_AUTHORITY_EFFECTIVENESS_V1.cjs',c:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-LOADER-CORRECTED-FORMAL-RUN-A-AUTHORITY-CANDIDATE-V1.json',m:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-LOADER-CORRECTED-RUN-A-AUTHORITY-OBJECT-SET-V1.json',o:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-PREHARNESS-CORRECTED-FORMAL-RUN-A-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',g:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs'};
const L=[X.w,X.e,X.s,X.b,X.v].sort(),G=(...a)=>E('git',a,{cwd:R,encoding:'utf8'}).trim(),J=p=>JSON.parse(F.readFileSync(P.join(R,p),'utf8'));
const K=v=>Array.isArray(v)?`[${v.map(K).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${K(v[k])}`).join(',')}}`:JSON.stringify(v);
const D=v=>{v=structuredClone(v);delete v.semantic_digest;return`sha256:${C.createHash('sha256').update(K(v)).digest('hex')}`},W=v=>{F.mkdirSync(P.dirname(O),{recursive:true});F.writeFileSync(O,JSON.stringify(v,null,2)+'\n')};
try{
 const q=String(process.env.MCFT_BASE_SHA||B).trim();A.equal(q,B);A.equal(G('merge-base',q,'HEAD'),q);A.equal(G('diff','--check',`${q}...HEAD`),'');A.equal(G('diff','--name-only',`${H}...${B}`),'');
 A.deepEqual(G('diff','--name-only',`${q}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),L);
 const e=J(X.e),s=J(X.s),b=J(X.b),c=J(X.c),m=J(X.m),o=J(X.o);
 A.equal(G('rev-parse',`HEAD:${X.c}`),'599c24febde0e3428ca15af393c76bb252a492a1');A.equal(G('rev-parse',`HEAD:${X.m}`),'078ef862e6d51a01cd4fe0173110ed6ff091e69e');A.equal(G('rev-parse',`HEAD:${X.o}`),'95b2f118cc0bc7b1c26bfff2c99410e312c587d9');
 A.equal(c.record_status,'FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORITY_CANDIDATE_NOT_EFFECTIVE');A.equal(c.semantic_digest,'sha256:502f0838709ba1054d517463dcc43d4790e8ccd1120b9061ccae2dff3bceaf70');A.equal(c.exact_subject_sha,S);A.equal(c.operational_run_instance_id,I);
 A.equal(m.record_status,'LOADER_CORRECTED_RUN_A_AUTHORITY_OBJECT_SET_FROZEN');A.equal(m.exact_subject_sha,S);A.equal(m.object_count,50);A.equal(m.semantic_digest,'sha256:0dd63283d64515a2ae24d9f29c070084e46e664bc2c22a321c7558979777338a');A.equal(m.exact_harness_object_set['scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/harness_v1.cjs'],'1833c793a10bba383f54200a35cb3f8912b60b94');A.equal(m.exact_harness_object_set['scripts/runtime_acceptance/mcft_cap08_s6_single_run_db/contract_loader_v1.cjs'],'27903ddc8566505053e3e6ccf4e8d08dfc576869');
 A.equal(o.authority_consumed,true);A.equal(o.single_run_database_execution_authorized,false);A.equal(o.consumption_evidence.github_workflow_run_id,30738876293);
 A.equal(e.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED');A.equal(e.exact_subject_sha,S);A.equal(e.authorized_run_label,'RUN_A');A.equal(e.operational_run_instance_id,I);A.equal(e.logical_database_identity.identity_id,'MCFT-CAP-08-S6-FORMAL-DB-A-20260802-REPLACEMENT-003');A.equal(e.candidate_authority_ref.blob_sha,'599c24febde0e3428ca15af393c76bb252a492a1');A.equal(e.object_set_manifest_ref.blob_sha,'078ef862e6d51a01cd4fe0173110ed6ff091e69e');A.equal(e.candidate_merge_sha,B);
 for(const k of ['single_run_database_execution_authorized','database_execution_workflow_authorized','workflow_dispatch_execution_authorized','final_formal_run_execution_authorized'])A.equal(e[k],true);
 for(const k of ['dual_run_ci_authorized','cross_run_comparator_authorized','final_ledger_settlement_authorized','database_execution_performed','workflow_dispatch_performed','formal_run_executed'])A.equal(e[k],false);
 A.equal(e.semantic_digest,D(e));const {validateExecutionAuthorityV1:V}=require(P.join(R,X.g));A.equal(V(e,{exactSubjectSha:S,runLabel:'RUN_A',operationalRunInstanceId:I}).module_path,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/index_v1.cjs');A.throws(()=>V(c,{exactSubjectSha:S,runLabel:'RUN_A',operationalRunInstanceId:I}));
 A.equal(s.base_main_sha,B);A.equal(s.candidate_to_merge_file_delta,0);A.equal(s.effective_authority.blob_sha,'01669ba4ef6c4193664eb952c40f2c6edcf25993');A.equal(s.effect.max_dispatch_count,1);A.equal(s.effect.rerun_authorized,false);A.equal(s.effect.run_b_dispatch_authorized,false);A.equal(s.semantic_digest,D(s));
 A.equal(b.base_main_sha,B);A.equal(b.changed_file_count,5);A.deepEqual([...b.changed_files].sort(),L);A.equal(b.database_execution_performed,false);A.equal(b.workflow_dispatch_performed,false);A.equal(b.run_b_dispatch_authorized,false);A.equal(b.semantic_digest,D(b));
 A.doesNotMatch(F.readFileSync(P.join(R,X.w),'utf8'),/workflow_dispatch:|postgres|psql|DATABASE_URL/i);
 const r={schema_version:'geox_mcft_cap08_s6_loader_corrected_run_a_authority_effectiveness_result_v1',status:'PASS',base_main_sha:q,exact_head_sha:G('rev-parse','HEAD'),candidate_to_merge_file_delta:0,corrected_subject_sha:S,operational_run_instance_id:I,runtime_gate_eligible_after_merge:true,production_gate_accepts_effective_authority:true,production_gate_rejects_candidate:true,prior_authority_consumed:true,run_b_dispatch_authorized:false,max_dispatch_count:1,rerun_authorized:false,database_execution_performed:false,workflow_dispatch_performed:false,formal_run_result_present:false,cross_run_comparator_authorized:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};W(r);console.log(JSON.stringify(r,null,2))
}catch(e){W({schema_version:'geox_mcft_cap08_s6_loader_corrected_run_a_authority_effectiveness_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});throw e}
