#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),cp=require('node:child_process'),fs=require('node:fs'),path=require('node:path');
const BASE='d46cb3c81c102a57b10a8ff2f1721e7420a82922',BASE_REGISTRY_BLOB='767d7a8c2ab65e4bd6fb212bb2c38a4bbc40ff25',TARGET_REGISTRY_BLOB='b161151a1cfaf67a742766aa8a2c93b0b2d89f48';
const S5_SUBJECT='afc882c49d6ec0a475552686200c369eb819b6cd',S5_RUN=31165105531,S5_ARTIFACT=8988635083,S5_DIGEST='sha256:bcb68915a3e01f5516da45d4e40271c5841eae23b3ce7c567357bed316e1ca43';
const REGISTRY='docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json',STATUS='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S6-DELIVERY-STATUS-V1.json',BOUNDARY='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S6-REGISTRY-REGISTRATION-BOUNDARY-V1.json',RECORD='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S6-REGISTRY-REGISTRATION-V1.json',OUTPUT='acceptance-output/MCFT_CAP_09_S6_REGISTRY_REGISTRATION_RESULT.json';
const FILES=[".github/workflows/mcft-cap-09-s2-registry-registration.yml",".github/workflows/mcft-cap-09-s6-registry-registration.yml","docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json","docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S6-DELIVERY-STATUS-V1.json","docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S6-REGISTRY-REGISTRATION-BOUNDARY-V1.json","docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S6-REGISTRY-REGISTRATION-V1.json","scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S2_REGISTRY_CROSS_LIFECYCLE_REPAIR.cjs","scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S6_REGISTRY_REGISTRATION.cjs","scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_classifier_v1.cjs","scripts/governance_acceptance/mcft_cap_09_registry_lifecycle_router_v1.cjs"];
const git=(...a)=>cp.execFileSync('git',a,{encoding:'utf8'}).trim(),json=p=>JSON.parse(fs.readFileSync(p,'utf8')),must=(v,c)=>{if(!v)throw Error(c)},same=(a,b,c)=>{try{assert.deepEqual(a,b)}catch{throw Error(c)}};
const write=v=>{fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,JSON.stringify(v,null,2)+'\n')};
function find(n){const root=path.resolve(process.env.MCFT_CAP09_S5_EFFECTIVE_ARTIFACT_DIR||'acceptance-input/cap09-s5-effective'),q=[root];while(q.length){const d=q.pop();if(!d||!fs.existsSync(d))continue;for(const e of fs.readdirSync(d,{withFileTypes:true})){const f=path.join(d,e.name);if(e.isDirectory())q.push(f);else if(e.name===n)return f}}throw Error('ARTIFACT_MISSING:'+n)}
function falseAuth(x,p){for(const k of ['implementation_authorized','runtime_source_authorized','live_ingestion_authorized','background_scheduler_authorized','canonical_write_authorized','public_http_writer_authorized','model_activation_authorized','controlled_action_authorized'])must(x[k]===false,p+':'+k)}
(async()=>{try{
 const base=process.env.MCFT_BASE_SHA,head=git('rev-parse','HEAD');must(base===BASE,'EXACT_S6_REGISTRATION_BASE_REQUIRED');must(git('rev-list','--count',base+'..HEAD')==='1','ONE_COMMIT_REQUIRED');same(git('diff','--name-only',base+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),FILES,'EXACT_TEN_FILE_S6_REGISTRATION_BOUNDARY_REQUIRED');must(!git('diff','--unified=0',base+'...HEAD').includes(['MCFT','CANDIDATE','DECLARATION','V2'].join('_')),'CANDIDATE_DECLARATION_FORBIDDEN');must(git('rev-parse',base+':'+REGISTRY)===BASE_REGISTRY_BLOB,'BASE_REGISTRY_BLOB');must(git('rev-parse','HEAD:'+REGISTRY)===TARGET_REGISTRY_BLOB,'TARGET_REGISTRY_BLOB');must(!FILES.some(f=>f.startsWith('apps/')||f.startsWith('packages/')||f.includes('/migrations/')),'RUNTIME_FORBIDDEN');must(cp.spawnSync('git',['merge-base','--is-ancestor',S5_SUBJECT,base]).status===0,'S5_ANCESTRY');
 const att=json(find('MCFT_CAP_09_S5_EXACT_SHA_ATTESTATION.json')),loc=json(find('MCFT_CAP_09_S5_ATTESTATION_RETENTION_LOCATOR.json'));must(att.status==='PASS'&&att.subject_sha===S5_SUBJECT&&att.semantic_artifact_digest===S5_DIGEST,'S5_ATTESTATION');must(att.effective_authority?.s5_shadow_online_canonical_integration_effective===true&&att.effective_authority?.effective_next_slice==='S6'&&att.effective_authority?.s6_registry_registration_authorized===true&&att.effective_authority?.s6_authorized_scope==='FORMAL_24_HOUR_STAGE_1B_CLOSURE_ONLY','S6_AUTHORITY');falseAuth(att.effective_authority,'S5_AUTH');must(loc.semantic_artifact_digest===S5_DIGEST&&loc.retention_level==='R2'&&loc.readback_verified===true&&loc.locked_version_delete_denied===true&&Date.parse(loc.retain_until)>=Date.now()+729*86400000,'S5_R2');
 const before=JSON.parse(git('show',base+':'+REGISTRY)),after=json(REGISTRY);must(after.authority_set_revision==='1.13'&&after.authority_set_change_id==='MCFT-CAP-09.S6-TRANSITION-REGISTRATION','REGISTRY_REV');for(const id of ['MCFT-CAP-06','MCFT-CAP-07','MCFT-CAP-08'])same(after.capabilities.find(x=>x.capability_line===id),before.capabilities.find(x=>x.capability_line===id),'PREDECESSOR_DRIFT:'+id);const b=before.capabilities.find(x=>x.capability_line==='MCFT-CAP-09'),a=after.capabilities.find(x=>x.capability_line==='MCFT-CAP-09');same(a.authoritative_candidate_status_paths,[...b.authoritative_candidate_status_paths,STATUS],'STATUS_APPEND');same(a.candidate_transition_fields,[...b.candidate_transition_fields,{status_file:STATUS,field_path:'s6_candidate_implemented',allowed_candidate_values:[true],focused_workflow:'mcft-cap-09-s6-formal-24-hour-stage-1b-closure',standard_workflow:'ci',predecessor_effective_evidence_required:true}],'RULE_APPEND');same(a.deferred_status_paths,[],'DEFERRED_EMPTY');must(a.deferred_transition_registration_required===false,'DEFERRED_COMPLETE');falseAuth(a,'REGISTRY_AUTH');
 const st=json(STATUS),bd=json(BOUNDARY),rc=json(RECORD);must(st.status==='REGISTRY_REGISTERED_NOT_CANDIDATE'&&st.s6_registry_registration_implemented===true&&st.s6_candidate_implemented===false&&st.candidate_declaration_present===false&&st.externally_effective===false,'STATUS_NONCANDIDATE');must(st.authorized_s6_scope==='FORMAL_24_HOUR_STAGE_1B_CLOSURE_ONLY'&&st.s5_effective_subject_sha===S5_SUBJECT&&st.s5_exact_sha_r2_run_id===S5_RUN&&st.s5_exact_sha_artifact_id===S5_ARTIFACT&&st.s5_semantic_artifact_digest===S5_DIGEST,'STATUS_BINDING');falseAuth(st,'STATUS_AUTH');must(bd.base_main_sha===BASE&&bd.changed_file_count===10&&bd.candidate_transition===false&&bd.runtime_source_delta===0,'BOUNDARY');same(bd.changed_files.sort(),FILES,'BOUNDARY_FILES');must(rc.base_registry_blob_sha===BASE_REGISTRY_BLOB&&rc.target_registry_blob_sha===TARGET_REGISTRY_BLOB&&rc.candidate_transition_performed===false&&rc.same_pr_registry_registration_cannot_authorize_candidate===true,'RECORD');
 if(process.env.MCFT_EVENT_NAME==='pull_request'){const r=await fetch('https://api.github.com/repos/'+process.env.GITHUB_REPOSITORY+'/pulls/'+process.env.MCFT_PR_NUMBER,{headers:{Authorization:'Bearer '+process.env.GITHUB_TOKEN,Accept:'application/vnd.github+json','User-Agent':'geox-cap09-s6-registry'}}),p=await r.json();must(r.ok&&p.head.sha===head&&p.base.sha===base,'PR_BINDING');must(!String(p.body||'').includes('<!-- '+['MCFT','CANDIDATE','DECLARATION','V2'].join('_')),'PR_DECLARATION_FORBIDDEN')}
 write({schema_version:'geox_mcft_cap09_s6_registry_registration_result_v1',status:'PASS',base_sha:base,head_sha:head,changed_files:FILES,s5_effective_subject_sha:S5_SUBJECT,s5_exact_sha_r2_run_id:S5_RUN,s5_exact_sha_artifact_id:S5_ARTIFACT,s5_semantic_artifact_digest:S5_DIGEST,target_authority_set_revision:'1.13',target_registry_blob_sha:TARGET_REGISTRY_BLOB,s6_status_path_registered:true,s6_transition_rule_registered:true,candidate_transition:false,runtime_source_delta:0,externally_effective:false,first_legal_next_action:'MCFT_CAP_09_S6_FORMAL_24_HOUR_STAGE_1B_CLOSURE_CANDIDATE'});
}catch(e){write({status:'FAIL',error:String(e.message||e)});console.error(e);process.exitCode=1}})();
