#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'); const crypto=require('node:crypto'); const fs=require('node:fs'); const path=require('node:path');
const { ROOT, readJson, git, gitBlob, materialize, writeReview }=require('./mcft_cap08_s6_materialize_ha_mapping_review.cjs');
const { validateMapping }=require('./mcft_cap08_s6_ha_mapping_validation.cjs'); const { validateWitnessContracts }=require('./mcft_cap08_s6_witness_contract_validation.cjs');
const BOUNDARY='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-HA-MAPPING-BOUNDARY-V1.json';
const OUTPUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_LEDGER_COVERAGE_RESULT.json');
function sha256File(p){return `sha256:${crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex')}`;}
function write(v){fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,`${JSON.stringify(v,null,2)}\n`);}
try{
 const local=process.env.MCFT_LOCAL_REPLAY==='1'; const boundary=readJson(BOUNDARY); const base=String(process.env.MCFT_BASE_SHA||boundary.base_main_sha).trim();
 if(!local){assert.equal(base,boundary.base_main_sha,'BASE_SHA_DRIFT');assert.equal(git('merge-base',base,'HEAD'),base,'BASE_NOT_ANCESTOR');assert.equal(git('diff','--check',`${base}...HEAD`),'','DIFF_CHECK_FAILED');const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(changed,[...boundary.changed_files].sort(),'CHANGED_FILE_BOUNDARY');}
 const forbiddenPrefixes=['apps/','packages/','db/','migrations/','scripts/runtime_acceptance/']; for(const f of boundary.changed_files) assert.equal(forbiddenPrefixes.some((p)=>f.startsWith(p)),false,`FORBIDDEN_CHANGED_FILE:${f}`);
 assert.equal(boundary.changed_file_count,16); assert.equal(boundary.runtime_source_file_count,0); assert.equal(boundary.runtime_acceptance_file_count,0); assert.equal(boundary.database_migration_file_count,0); assert.equal(boundary.witness_producer_file_count,0); assert.equal(boundary.dual_run_workflow_file_count,0); assert.equal(boundary.candidate_declaration_present,false);
 const options={strictAuthorityBlobs:!local}; const mapping=validateMapping(options); const witness=validateWitnessContracts(options);
 const review1=materialize(options); const review2=materialize(options); assert.deepEqual(review2,review1,'MATERIALIZATION_NOT_REPRODUCIBLE'); writeReview(review1);
 const staticFiles=boundary.changed_files.filter((f)=>/HA-MAPPING-RULES|HA-PROOF-CONTRACTS/.test(f)); const staticText=staticFiles.map((f)=>fs.readFileSync(path.join(ROOT,f),'utf8')).join('\n');
 const itemLiteralCount=(staticText.match(/"item_id"\s*:/g)||[]).length; const requirementLiteralCount=(staticText.match(/"requirement"\s*:/g)||[]).length; assert.equal(itemLiteralCount,0); assert.equal(requirementLiteralCount,0);
 const result={schema_version:'geox_mcft_cap08_s6_ledger_coverage_result_v2',status:'PASS',subject_sha:local?'LOCAL_REPLAY':git('rev-parse','HEAD'),base_sha:local?'LOCAL_REPLAY':base,changed_file_count:boundary.changed_file_count,item_count:review1.item_count,rule_count:mapping.rule_count,proof_contract_count:mapping.proof_contract_count,expected_phase_witness_instance_count:witness.expected_phase_witness_instance_count,static_item_id_literal_count:itemLiteralCount,static_requirement_literal_count:requirementLiteralCount,ordinary_assimilation_tick_count:mapping.ordinary_assimilation_tick_count,dynamics_only_tick_count:mapping.dynamics_only_tick_count,ha24_split:mapping.ha24_split,canonical_operational_identity_separated:witness.canonical_operational_identity_separated,mapping_review_json_digest:sha256File(path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_HA_MAPPING_REVIEW.json')),mapping_review_markdown_digest:sha256File(path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_HA_MAPPING_REVIEW.md')),mapping_human_review_complete:false,mapping_frozen:false,witness_implementation_authorized:false,dual_run_ci_authorized:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false}; write(result); console.log(JSON.stringify(result,null,2));
}catch(e){write({schema_version:'geox_mcft_cap08_s6_ledger_coverage_result_v2',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1;}
