#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),P=require('node:child_process'),F=require('node:fs'),O=require('node:os'),X=require('node:path');
const R=X.resolve(__dirname,'../..'),D='docs/digital_twin/mcft/cap_08';
const AP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-HARNESS-DEPENDENCY-CORRECTION-EFFECTIVENESS-AUTHORITY-V1.json`;
const BP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-HARNESS-DEPENDENCY-CORRECTION-EFFECTIVENESS-BOUNDARY-V1.json`;
const GP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-HARNESS-DEPENDENCY-REPLACEMENT-AUTHORITY-ISSUANCE-GATE-V1.json`;
const W='.github/workflows/mcft-cap-08-s6-run-a-qualification-harness-dependency-correction-effectiveness.yml',ORIGINAL='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_RUN_A_QUALIFICATION_HARNESS_DEPENDENCY_CORRECTION.cjs';
const Q=X.join(R,'acceptance-output/MCFT_CAP_08_S6_RUN_A_QUALIFICATION_HARNESS_DEPENDENCY_CORRECTION_EFFECTIVENESS_RESULT.json');
const read=p=>JSON.parse(F.readFileSync(X.join(R,p),'utf8')),text=p=>F.readFileSync(X.join(R,p),'utf8'),git=(...a)=>P.execFileSync('git',a,{cwd:R,encoding:'utf8'}).trim();
const canon=v=>Array.isArray(v)?`[${v.map(canon).join(',')}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canon(v[k])}`).join(',')}}`:JSON.stringify(v);
function sd(v){const x=structuredClone(v);delete x.semantic_digest;return`sha256:${C.createHash('sha256').update(canon(x)).digest('hex')}`;}
function out(v){F.mkdirSync(X.dirname(Q),{recursive:true});F.writeFileSync(Q,JSON.stringify(v,null,2)+'\n');}
try{
 const a=read(AP),b=read(BP),g=read(GP),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim();
 A.equal(base,b.base_main_sha);A.equal(git('merge-base',base,'HEAD'),base);A.equal(git('diff','--check',`${base}...HEAD`),'');
 const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();A.deepEqual(changed,[...b.changed_files].sort());A.equal(changed.length,5);
 for(const v of[a,b,g])A.equal(v.semantic_digest,sd(v),'SEMANTIC_DIGEST');
 const s=a.implementation_subject;A.equal(s.pull_request_number,2718);A.equal(s.candidate_head_sha,'164516b90c11e6b52e47c7b0355509e9cdfa2eb9');A.equal(s.candidate_tree_sha,'d0aa1d49ae0bce2d50bebd689996e0ace5ac3723');A.equal(s.merge_commit_sha,'51da0e8a26abdf2f667f63d0be21f7d8815bbcac');A.equal(s.merge_tree_sha,'d0aa1d49ae0bce2d50bebd689996e0ace5ac3723');A.equal(s.candidate_to_merge_file_delta,0);A.equal(s.candidate_to_merge_tree_equal,true);
 A.equal(git('rev-parse','164516b90c11e6b52e47c7b0355509e9cdfa2eb9^{tree}'),'d0aa1d49ae0bce2d50bebd689996e0ace5ac3723');A.equal(git('rev-parse','51da0e8a26abdf2f667f63d0be21f7d8815bbcac^{tree}'),'d0aa1d49ae0bce2d50bebd689996e0ace5ac3723');A.equal(git('diff','--name-only','164516b90c11e6b52e47c7b0355509e9cdfa2eb9','51da0e8a26abdf2f667f63d0be21f7d8815bbcac'),'');
 for(const [p,h] of Object.entries(a.implementation_object_set))A.equal(git('rev-parse',`51da0e8a26abdf2f667f63d0be21f7d8815bbcac:${p}`),h,`IMPLEMENTATION_BLOB_DRIFT:${p}`);
 const e=a.exact_head_evidence;A.equal(e.focused_workflow_run_id,30562644342);A.equal(e.focused_artifact_id,8767522230);A.equal(e.focused_artifact_digest,'sha256:055d0aa6edc228286b5f6126f4937dafea7aecce4f8ea9be52aef532c11d596a');A.equal(e.historical_successor_workflow_run_id,30562644244);A.equal(e.standard_ci_run_id,30562644289);A.equal(e.standard_ci_status,'PASS');A.equal(e.required_workflow_count,9);A.equal(e.required_workflow_success_count,9);
 const v=a.verified_result;A.equal(v.failed_workflow_run_id,30559432869);A.equal(v.failed_execution_job_id,90928367259);A.equal(v.failed_operational_instance_id,'MCFT-CAP-08-S6-RUN-A-QUAL-20260730-003');A.equal(v.failed_database_name,'geox_mcft_cap08_s6_run_a_qual_003');A.equal(v.database_bootstrap_completed,true);A.equal(v.database_drop_completed,true);A.equal(v.qualification_harness_function_entered,false);A.equal(v.qualification_result_generated,false);A.equal(v.dependency_correction_mock_replay_pass,true);A.equal(v.canonical_receipt_count,153);A.equal(v.recovery_vector_count,7);A.equal(v.cap07_surface_count,10);A.equal(v.corrected_harness_blob_sha,'5789bdf3f9881420aa7d91f0a0a64338dc493278');
 const ef=a.effect;A.equal(ef.harness_dependency_correction_effective,true);A.equal(ef.failed_operational_instance_reusable,false);A.equal(ef.failed_database_identity_reusable,false);A.equal(ef.replacement_authority_may_be_issued_separately,true);A.equal(ef.replacement_authority_subject_must_equal_this_effectiveness_merge_sha,true);A.equal(ef.actual_execution_authority_present,false);A.equal(ef.database_execution_authorized,false);A.equal(ef.run_a_qualification_completed,false);
 A.equal(g.record_status,'RUN_A_QUALIFICATION_REPLACEMENT_AUTHORITY_ISSUANCE_AUTHORIZED');const ic=g.issuance_constraints;A.equal(ic.authorized_run_label,'RUN_A');A.equal(ic.execution_subject_selector,'THIS_EFFECTIVENESS_MERGE_SHA');A.deepEqual(ic.retired_operational_run_instance_ids,['MCFT-CAP-08-S6-RUN-A-QUAL-20260729-001','MCFT-CAP-08-S6-RUN-A-QUAL-20260729-002','MCFT-CAP-08-S6-RUN-A-QUAL-20260730-003']);A.equal(ic.replacement_operational_instance_must_differ,true);A.equal(ic.replacement_database_name_must_differ,true);A.equal(ic.maximum_authority_lifetime_hours,24);A.equal(ic.corrected_harness_blob_sha,'5789bdf3f9881420aa7d91f0a0a64338dc493278');
 A.equal(g.execution_constraints.actual_execution_authority_present,false);A.equal(g.execution_constraints.workflow_dispatch_execution_authorized,false);A.equal(g.execution_constraints.database_execution_performed,false);
 const workflow=text(W);A.match(workflow,/pull_request:/);for(const x of[/workflow_dispatch:/,/services:\s*\n\s*postgres:/,/DATABASE_URL/])A.doesNotMatch(workflow,x);
 const tmp=F.mkdtempSync(X.join(O.tmpdir(),'mcft-cap08-harness-dependency-effect-'));
 try{git('worktree','add','--detach',tmp,'51da0e8a26abdf2f667f63d0be21f7d8815bbcac');P.execFileSync(process.execPath,[ORIGINAL],{cwd:tmp,env:{...process.env,MCFT_BASE_SHA:'51f6d20c11832aff4b679b78bb920d66b478a8fb',GITHUB_EVENT_PATH:''},stdio:'pipe'});}finally{try{git('worktree','remove','--force',tmp)}catch{}}
 const z={schema_version:'geox_mcft_cap08_s6_run_a_qualification_harness_dependency_correction_effectiveness_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:5,implementation_subject_sha:'51da0e8a26abdf2f667f63d0be21f7d8815bbcac',implementation_candidate_sha:'164516b90c11e6b52e47c7b0355509e9cdfa2eb9',implementation_tree_sha:'d0aa1d49ae0bce2d50bebd689996e0ace5ac3723',implementation_blob_count:11,focused_workflow_run_id:30562644342,focused_artifact_id:8767522230,standard_ci_run_id:30562644289,failed_operational_instance_id:'MCFT-CAP-08-S6-RUN-A-QUAL-20260730-003',failed_instance_reusable:false,database_drop_completed:true,harness_dependency_correction_effective:true,corrected_harness_blob_sha:'5789bdf3f9881420aa7d91f0a0a64338dc493278',mock_qualification_replay_pass:true,replacement_authority_may_be_issued_separately:true,actual_execution_authority_present:false,database_execution_performed:false,run_a_qualification_completed:false,run_b_executed:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};out(z);console.log(JSON.stringify(z,null,2));
}catch(error){out({schema_version:'geox_mcft_cap08_s6_run_a_qualification_harness_dependency_correction_effectiveness_result_v1',status:'FAIL',error:error instanceof Error?error.stack||error.message:String(error)});console.error(error);process.exitCode=1;}
