#!/usr/bin/env node
'use strict'; const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto'); const R=path.resolve(__dirname,'../..'); const read=p=>fs.readFileSync(path.join(R,p),'utf8'),json=p=>JSON.parse(read(p)); const checks=[]; const check=(n,f)=>{f();checks.push({name:n,status:'PASS'})};
try{const a=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-CURRENT-AUTHORITY-V1.json'); const r=json('docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json'); const cap=r.capabilities.find(x=>x.capability_line==='MCFT-CAP-08');
check('CURRENT_AUTHORITY_CONDITIONAL',()=>{assert.equal(a.record_status,'COMMITTED_CONDITIONAL_AUTHORITY');assert.equal(a.status,'AUTHORIZATION_CANDIDATE_NOT_EFFECTIVE');assert.equal(a.slice_id,'MCFT-CAP-08.S0');for(const k of ['implementation_authorized','runtime_source_authorized','bounded_replay_runner_authorized','bounded_canonical_transaction_authorized','production_runtime_source_authorized_when_attested','postmerge_ssot_writeback_allowed','mcft_cap_09_authorized'])assert.equal(a[k],false,k);});
check('PR0_BASE_AND_PREDECESSOR',()=>{assert.equal(a.pr_0_protected_merge_sha,'ade35875ff6f5ef92ec76f04ab9fc302c57f700e');const p=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-PREDECESSOR-CONSUMPTION-V1.json');assert.equal(p.closure_subject_sha,'81579b7f67a3dcd3cf557abbf29c9462d8b7736b');});
check('REGISTRY_S1_SUCCESSOR_ONLY',()=>{assert.ok(cap);assert.ok(cap.authoritative_candidate_status_paths.some(x=>x.endsWith('S1-DELIVERY-STATUS-V1.json')));const rule=cap.candidate_transition_fields.find(x=>x.field_path==='s1_candidate_implemented');assert.deepEqual(rule.allowed_candidate_values,[true]);assert.equal(rule.focused_workflow,'mcft-cap-08-s1-base-runtime');});
check('MASTER_AUTHORITY_REPLACEMENT',()=>{const m=read('docs/digital_twin/GEOX-DIGITAL-TWIN-MASTER-TASK-LINE.md');assert.match(m,/MCFT-CAP-08 Stage-1A authority reconciliation/);assert.match(m,/B00 plus T00–T23/);assert.match(m,/NO_ACTION[\s\S]*IRRIGATE_NOW_15MM[\s\S]*IRRIGATE_NOW_25MM/);});
check('CAP04_TASKBOOK_BYTE_UNCHANGED',()=>{const out=require('child_process').execFileSync('git',['diff','--name-only','ade35875ff6f5ef92ec76f04ab9fc302c57f700e...HEAD'],{cwd:R,encoding:'utf8'});assert.ok(!out.split(/\r?\n/).includes('docs/digital_twin/mcft/cap_04/GEOX-MCFT-CAP-04-TASK.md'));});
check('S0_CONTRACT_CARDINALITIES',()=>{const c=json('docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-24-TICK-RUN-CONTRACT-V1.json');assert.equal(c.tick_ids.length,24);assert.equal(c.due_obligations.length,25);assert.equal(c.residual_cardinality,24);assert.equal(c.calibration_window.length,16);assert.equal(c.holdout_window.length,8);});
const result={schema_version:'geox_mcft_cap08_authority_reconciliation_result_v1',status:'PASS',check_count:checks.length,checks,runtime_domain_code_delta:0,business_schema_migration_delta:0,canonical_runtime_data_delta:0};fs.mkdirSync(path.join(R,'acceptance-output'),{recursive:true});fs.writeFileSync(path.join(R,'acceptance-output/MCFT_CAP_08_AUTHORITY_RECONCILIATION_RESULT.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result));}catch(e){console.error(e);process.exitCode=1;}
