#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),{execFileSync:E}=require('node:child_process');
const R=P.resolve(__dirname,'../..'),B='4639b12baa6f87fbb5ea093faf5e6936638693e0',S='ce9d6b4df8c708c0d4a99bb24846e1bc44b3cf59',OP='MCFT-CAP-08-S6-FORMAL-RUN-B-20260804-REPLACEMENT-001',DB='MCFT-CAP-08-S6-FORMAL-DB-B-20260804-REPLACEMENT-001';
const W='.github/workflows/mcft-cap-08-s6-formal-run-b-authority-candidate.yml',D='docs/digital_twin/mcft/cap_08/',CA='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-CANDIDATE-V1.json',O='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-OBJECT-SET-V1.json',I='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-ISSUANCE-V1.json',BD='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-BOUNDARY-V1.json',Q=D+'GEOX-MCFT-CAP-08-S6-EXACT-PATH-DEVELOPMENT-REHEARSAL-OBJECT-SET-V1.json',RA=D+'GEOX-MCFT-CAP-08-S6-REPLACEMENT-011-FORMAL-RUN-A-SUCCESS-V1.json',RC=D+'GEOX-MCFT-CAP-08-S6-REPLACEMENT-011-RUN-A-AUTHORITY-CONSUMPTION-V1.json',OLD=D+'GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_FORMAL_RUN_B_AUTHORITY_CANDIDATE_V1.cjs',OUT=P.join(R,'acceptance-output/MCFT_CAP_08_S6_FORMAL_RUN_B_AUTHORITY_CANDIDATE_RESULT.json');
const CH=[W,CA,O,I,BD,V].sort(),MX=["CJS_MODULE_LOADING","PORT_EXPORT_IMPORT_BINDING","FRESH_BOOTSTRAP_FACTS","AUTHORITY_ARGUMENT_TRANSPORT","PHYSICAL_DATABASE_IDENTITY","T16_S4_T17_INTERLEAVE","T17_GUARD_ACL","EXECUTION_PHASE_ORDER","STATE_PROJECTION_CANONICAL_PAYLOAD","CANONICAL_RECEIPT_CARDINALITY_153","OPERATIONAL_EVENT_CARDINALITY_224","FVO10_CANONICAL_ALIAS","FVO17_CORRECTED_FORECAST_BINDING","EXACT_WITNESS_PRODUCERS_22","RESTART_READ_CONTINUITY","DATABASE_CLEAN_DROP"];
const g=(...x)=>E('git',x,{cwd:R,encoding:'utf8'}).trim(),t=x=>F.readFileSync(P.join(R,x),'utf8'),j=x=>JSON.parse(t(x));
const can=x=>Array.isArray(x)?'['+x.map(can).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+can(x[k])).join(',')+'}':JSON.stringify(x);
const sem=x=>{x=structuredClone(x);delete x.semantic_digest;return'sha256:'+C.createHash('sha256').update(can(x)).digest('hex')};
const save=x=>{F.mkdirSync(P.dirname(OUT),{recursive:true});F.writeFileSync(OUT,JSON.stringify(x,null,2)+'\n')};
try{
 const base=String(process.env.MCFT_BASE_SHA||B).trim();A.equal(base,B);A.equal(g('merge-base',B,'HEAD'),B);A.equal(g('rev-list','--count',B+'..HEAD'),'1');A.equal(g('diff','--check',B+'...HEAD'),'');A.deepEqual(g('diff','--name-only',B+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),CH);
 const c=j(CA),o=j(O),i=j(I),b=j(BD),q=j(Q),ra=j(RA),rc=j(RC),old=j(OLD);for(const x of[c,o,i,b,q,ra,rc,old])A.equal(x.semantic_digest,sem(x),x.schema_version);
 const blobs={candidate:g('rev-parse','HEAD:'+CA),objectSet:g('rev-parse','HEAD:'+O),issuance:g('rev-parse','HEAD:'+I),boundary:g('rev-parse','HEAD:'+BD),qualified:g('rev-parse','HEAD:'+Q),runA:g('rev-parse','HEAD:'+RA),consumed:g('rev-parse','HEAD:'+RC),oldRunB:g('rev-parse','HEAD:'+OLD)};
 A.equal(blobs.qualified,'dca4c8b35e2b9c4635f2b1b2e82fff23a8247c0e');A.equal(blobs.runA,'aec6a5d6ad91687c7f404f1638eecb0600c25df4');A.equal(blobs.consumed,'13480ddf62fafc9b408988d89c4f8038c7f16eff');A.equal(blobs.oldRunB,'8cbb319aa24c919cddb5a82f62c3fcdcb41e050f');
 A.equal(q.record_status,'EXACT_PATH_DEVELOPMENT_REHEARSAL_OBJECT_SET_FROZEN');A.equal(q.object_count,56);const sets=[q.exact_control_plane_object_set,q.exact_database_bootstrap_object_set,q.exact_product_object_set,q.exact_port_bundle_object_set,q.exact_harness_object_set,q.protected_invariant_object_set];A.equal(sets.reduce((n,x)=>n+Object.keys(x).length,0),56);for(const set of sets)for(const[p,sha]of Object.entries(set))for(const ref of[S,B,'HEAD'])A.equal(g('rev-parse',ref+':'+p),sha,'EXECUTION_BLOB:'+ref+':'+p);
 A.equal(ra.record_status,'FORMAL_RUN_A_TERMINAL_SUCCESS_ESTABLISHED');A.equal(ra.formal_workflow.workflow_run_id,30845476698);A.equal(ra.formal_workflow.workflow_run_attempt,1);A.equal(ra.formal_workflow.conclusion,'success');A.equal(ra.terminal_invariants.per_run_witness_pass_count,22);A.equal(ra.terminal_invariants.database_drop_completed,true);A.equal(ra.authority_consumed,true);A.equal(ra.run_b_authorized,false);
 A.equal(rc.record_status,'SINGLE_FINAL_FORMAL_RUN_A_AUTHORITY_CONSUMED_TERMINAL_SUCCESS');A.equal(rc.dispatch_count_consumed,1);A.equal(rc.maximum_dispatch_count,1);A.equal(rc.rerun_authorized,false);A.equal(rc.run_b_dispatch_authorized,false);
 A.equal(old.record_status,'SINGLE_FINAL_FORMAL_RUN_AUTHORITY_RETIRED_OBSOLETE_SUBJECT');A.equal(old.authorized_run_label,'RUN_B');A.equal(old.operational_run_instance_id,'MCFT-CAP-08-S6-FORMAL-RUN-B-20260802-002');A.equal(old.workflow_dispatch_execution_authorized,false);A.equal(old.logical_database_identity.reusable,false);
 A.equal(c.record_status,'FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORITY_CANDIDATE_NOT_EFFECTIVE');A.equal(c.base_governance_main_sha,B);A.equal(c.exact_subject_sha,S);A.equal(c.authorized_run_label,'RUN_B');A.equal(c.operational_run_instance_id,OP);A.equal(c.logical_database_identity.identity_id,DB);A.equal(c.logical_database_identity.physical_name_template,'geox_mcft_cap08_s6_run_b_replacement_001_<github_run_id>');A.equal(c.formal_run_a_predecessor.success_record_blob_sha,blobs.runA);A.equal(c.formal_run_a_predecessor.consumption_record_blob_sha,blobs.consumed);A.equal(c.formal_run_a_predecessor.terminal_success,true);A.equal(c.formal_run_a_predecessor.authority_consumed,true);A.ok(Object.values(c.authorization_state).every(x=>x===false));
 A.equal(c.object_set_manifest_ref.blob_sha,blobs.objectSet);A.equal(c.object_set_manifest_ref.object_count,56);A.equal(o.record_status,'FORMAL_RUN_B_AUTHORITY_OBJECT_SET_FROZEN');A.equal(o.object_count,56);A.equal(o.qualified_execution_manifest_ref.blob_sha,blobs.qualified);A.equal(o.formal_run_a_terminal_success_predecessor.success_record_blob_sha,blobs.runA);A.deepEqual(o.required_regression_matrix,MX);A.equal(i.candidate.blob_sha,blobs.candidate);A.equal(i.object_set.blob_sha,blobs.objectSet);A.equal(i.activation.authority_effective,false);A.equal(b.changed_file_count,6);A.deepEqual([...b.changed_files].sort(),CH);A.equal(b.candidate_authority_blob_sha,blobs.candidate);A.equal(b.object_set_blob_sha,blobs.objectSet);
 const gate=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs')),input={exactSubjectSha:S,runLabel:'RUN_B',operationalRunInstanceId:OP};A.throws(()=>gate.validateExecutionAuthorityV1(c,input),/SINGLE_RUN_DATABASE_EXECUTION_REQUIRED|EXECUTION_AUTHORITY_RECORD_STATUS/);const e=structuredClone(c);Object.assign(e,{record_status:'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED',evidence_class:'FINAL_FORMAL_EVIDENCE_ELIGIBLE_AFTER_TERMINAL_SUCCESS',expires_at:'2099-08-08T01:55:00.000Z',single_run_database_execution_authorized:true,database_execution_workflow_authorized:true,workflow_dispatch_execution_authorized:true,final_formal_run_execution_authorized:true,hard_acceptance_eligible:true,s6_candidate_evidence_eligible:true,dual_run_ci_authorized:false,cross_run_comparator_authorized:false,final_ledger_settlement_authorized:false});gate.validateExecutionAuthorityV1(e,input);
 const id=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs'));A.equal(id.materializePhysicalDatabaseNameV1(e,'30850000012'),'geox_mcft_cap08_s6_run_b_replacement_001_30850000012');const wf=t(W);A.doesNotMatch(wf,/workflow_dispatch:|postgres:|psql|DATABASE_URL/i);A.match(wf,/Validate fresh non-effective Formal RUN_B authority candidate/);
 const r={schema_version:'geox_mcft_cap08_s6_formal_run_b_authority_candidate_result_v1',status:'PASS',base_governance_main_sha:B,exact_head_sha:g('rev-parse','HEAD'),exact_subject_sha:S,object_count:56,formal_run_a_workflow_run_id:30845476698,operational_run_instance_id:OP,logical_database_identity:DB,candidate_runtime_gate_eligible:false,database_execution_performed:false,workflow_dispatch_performed:false,cross_run_comparator_authorized:false};save(r);console.log(JSON.stringify(r,null,2));
}catch(error){save({schema_version:'geox_mcft_cap08_s6_formal_run_b_authority_candidate_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1}
