#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),F=require('node:fs'),P=require('node:path'),{execFileSync:E}=require('node:child_process');
const R=P.resolve(__dirname,'../..'),B='07426c05c39b792738803d04af48582d3f81c204',S='ce9d6b4df8c708c0d4a99bb24846e1bc44b3cf59',CH='4b134fae539d7caa81a9a7ebd6d031395170a71c',OP='MCFT-CAP-08-S6-FORMAL-RUN-B-20260804-REPLACEMENT-001',DB='MCFT-CAP-08-S6-FORMAL-DB-B-20260804-REPLACEMENT-001';
const W='.github/workflows/mcft-cap-08-s6-formal-run-b-authority-effectiveness.yml',D='docs/digital_twin/mcft/cap_08/',CA=D+'GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-CANDIDATE-V1.json',O=D+'GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-OBJECT-SET-V1.json',EA='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-REPLACEMENT-001-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',ER='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-EFFECTIVENESS-V1.json',EB='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-AUTHORITY-EFFECTIVENESS-BOUNDARY-V1.json',Q=D+'GEOX-MCFT-CAP-08-S6-EXACT-PATH-DEVELOPMENT-REHEARSAL-OBJECT-SET-V1.json',RA=D+'GEOX-MCFT-CAP-08-S6-REPLACEMENT-011-FORMAL-RUN-A-SUCCESS-V1.json',RC=D+'GEOX-MCFT-CAP-08-S6-REPLACEMENT-011-RUN-A-AUTHORITY-CONSUMPTION-V1.json',OLD=D+'GEOX-MCFT-CAP-08-S6-FORMAL-RUN-B-EXECUTION-AUTHORITY-EFFECTIVE-V1.json';
const V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_FORMAL_RUN_B_AUTHORITY_EFFECTIVENESS_V1.cjs',OUT=P.join(R,'acceptance-output/MCFT_CAP_08_S6_FORMAL_RUN_B_AUTHORITY_EFFECTIVENESS_RESULT.json'),FILES=[W,EA,ER,EB,V].sort();
const g=(...x)=>E('git',x,{cwd:R,encoding:'utf8'}).trim(),t=x=>F.readFileSync(P.join(R,x),'utf8'),j=x=>JSON.parse(t(x));const can=x=>Array.isArray(x)?'['+x.map(can).join(',')+']':x&&typeof x==='object'?'{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+can(x[k])).join(',')+'}':JSON.stringify(x);const sem=x=>{x=structuredClone(x);delete x.semantic_digest;return'sha256:'+C.createHash('sha256').update(can(x)).digest('hex')};const save=x=>{F.mkdirSync(P.dirname(OUT),{recursive:true});F.writeFileSync(OUT,JSON.stringify(x,null,2)+'\n')};
try{
 const base=String(process.env.MCFT_BASE_SHA||B).trim();A.equal(base,B);A.equal(g('merge-base',B,'HEAD'),B);A.equal(g('rev-list','--count',B+'..HEAD'),'1');A.equal(g('diff','--check',B+'...HEAD'),'');A.deepEqual(g('diff','--name-only',B+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),FILES);A.equal(g('diff','--name-only',CH+'...'+B),'');
 const e=j(EA),r=j(ER),b=j(EB),c=j(CA),o=j(O),q=j(Q),ra=j(RA),rc=j(RC),old=j(OLD);for(const x of[e,r,b,c,o,q,ra,rc,old])A.equal(x.semantic_digest,sem(x),x.schema_version);
 const blobs={effective:g('rev-parse','HEAD:'+EA),record:g('rev-parse','HEAD:'+ER),boundary:g('rev-parse','HEAD:'+EB),candidate:g('rev-parse','HEAD:'+CA),objectSet:g('rev-parse','HEAD:'+O),qualified:g('rev-parse','HEAD:'+Q),runA:g('rev-parse','HEAD:'+RA),consumed:g('rev-parse','HEAD:'+RC),old:g('rev-parse','HEAD:'+OLD)};
 A.equal(blobs.effective,'eba4c307795b3b86bd108c547119d817d28fe47e');A.equal(blobs.record,'c1658686780d65e694b6d4de7f9ae507902e836e');A.equal(blobs.boundary,'431e791129f9e9f4bf28eeec5154a3d3e63e5f75');A.equal(blobs.candidate,'1691a163a7fc29c1a0186cd638b77e02182b913a');A.equal(blobs.objectSet,'977e8742d3bc9a0a4259f9795b24266dbf944b97');A.equal(blobs.qualified,'dca4c8b35e2b9c4635f2b1b2e82fff23a8247c0e');A.equal(blobs.runA,'aec6a5d6ad91687c7f404f1638eecb0600c25df4');A.equal(blobs.consumed,'13480ddf62fafc9b408988d89c4f8038c7f16eff');A.equal(blobs.old,'8cbb319aa24c919cddb5a82f62c3fcdcb41e050f');A.equal(g('rev-parse',B+':'+OLD),blobs.old);A.equal(g('rev-parse','HEAD:'+OLD),blobs.old);A.equal(g('rev-parse',CH+':'+CA),blobs.candidate);A.equal(g('rev-parse',B+':'+CA),blobs.candidate);
 A.equal(old.record_status,'SINGLE_FINAL_FORMAL_RUN_AUTHORITY_RETIRED_OBSOLETE_SUBJECT');A.equal(old.workflow_dispatch_execution_authorized,false);A.equal(old.logical_database_identity.reusable,false);
 A.equal(q.object_count,56);const sets=[q.exact_control_plane_object_set,q.exact_database_bootstrap_object_set,q.exact_product_object_set,q.exact_port_bundle_object_set,q.exact_harness_object_set,q.protected_invariant_object_set];A.equal(sets.reduce((n,x)=>n+Object.keys(x).length,0),56);for(const set of sets)for(const[p,sha]of Object.entries(set))for(const ref of[S,CH,B,'HEAD'])A.equal(g('rev-parse',ref+':'+p),sha,'EXECUTION_BLOB:'+ref+':'+p);
 A.equal(ra.record_status,'FORMAL_RUN_A_TERMINAL_SUCCESS_ESTABLISHED');A.equal(ra.formal_workflow.workflow_run_id,30845476698);A.equal(ra.formal_workflow.conclusion,'success');A.equal(ra.authority_consumed,true);A.equal(rc.record_status,'SINGLE_FINAL_FORMAL_RUN_A_AUTHORITY_CONSUMED_TERMINAL_SUCCESS');A.equal(rc.dispatch_count_consumed,1);A.equal(rc.rerun_authorized,false);
 A.equal(e.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED');A.equal(e.exact_subject_sha,S);A.equal(e.authorized_run_label,'RUN_B');A.equal(e.operational_run_instance_id,OP);A.equal(e.logical_database_identity.identity_id,DB);A.equal(e.logical_database_identity.reusable,false);A.equal(e.candidate_head_sha,CH);A.equal(e.candidate_merge_sha,B);A.equal(e.candidate_authority_ref.blob_sha,blobs.candidate);A.equal(e.object_set_manifest_ref.blob_sha,blobs.objectSet);A.equal(e.retired_run_b_predecessor.blob_sha,blobs.old);A.equal(e.retired_run_b_predecessor.preserved_unchanged,true);
 A.equal(e.single_use_contract.max_dispatch_count,1);A.equal(e.single_use_contract.github_run_attempt_required,1);A.equal(e.single_use_contract.rerun_authorized,false);A.equal(e.database_execution_performed,false);A.equal(e.workflow_dispatch_performed,false);A.equal(e.formal_run_executed,false);A.equal(e.cross_run_comparator_authorized,false);
 A.equal(r.production_gate_eligible,true);A.equal(r.explicit_dispatch_approval_required,true);A.equal(r.effective_authority.blob_sha,blobs.effective);A.equal(r.retired_run_b_predecessor.blob_sha,blobs.old);A.equal(r.retired_run_b_predecessor.preserved_unchanged,true);A.equal(b.new_file_count,5);A.equal(b.modified_file_count,0);A.deepEqual([...b.changed_files].sort(),FILES);A.equal(b.retired_run_b_authority_blob_sha,blobs.old);A.equal(b.retired_run_b_authority_preserved_unchanged,true);
 const gate=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs')),input={exactSubjectSha:S,runLabel:'RUN_B',operationalRunInstanceId:OP};gate.validateExecutionAuthorityV1(e,input);A.throws(()=>gate.validateExecutionAuthorityV1(c,input),/SINGLE_RUN_DATABASE_EXECUTION_REQUIRED|EXECUTION_AUTHORITY_RECORD_STATUS/);const id=require(P.join(R,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs'));A.equal(id.materializePhysicalDatabaseNameV1(e,'30880000012'),'geox_mcft_cap08_s6_run_b_replacement_001_30880000012');const wf=t(W);A.doesNotMatch(wf,/workflow_dispatch:|postgres:|psql|DATABASE_URL/i);A.match(wf,/Validate Formal RUN_B authority effectiveness/);
 const result={schema_version:'geox_mcft_cap08_s6_formal_run_b_authority_effectiveness_result_v1',status:'PASS',base_main_sha:B,exact_head_sha:g('rev-parse','HEAD'),exact_subject_sha:S,candidate_head_sha:CH,candidate_merge_sha:B,candidate_to_merge_file_delta:0,candidate_to_merge_execution_object_delta:0,object_count:56,effective_authority_blob_sha:blobs.effective,retired_run_b_authority_blob_sha:blobs.old,retired_run_b_authority_preserved_unchanged:true,operational_run_instance_id:OP,logical_database_identity:DB,production_gate_eligible:true,database_execution_performed:false,workflow_dispatch_performed:false,explicit_dispatch_approval_required:true,cross_run_comparator_authorized:false};save(result);console.log(JSON.stringify(result,null,2));
}catch(error){save({schema_version:'geox_mcft_cap08_s6_formal_run_b_authority_effectiveness_result_v1',status:'FAIL',error:error instanceof Error?error.message:String(error)});console.error(error);process.exitCode=1}
