#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),f=require('node:fs'),p=require('node:path'),{execFileSync}=require('node:child_process'),crypto=require('node:crypto');
const R=p.resolve(__dirname,'../..'),B='6fe62442022351aa7aad5f9eaab552020130512b',C='a665193c7934f7725bd6ceff613110c0d265a1c3',S='81ba6d7c845518a570052d80627bc1696a561e1a',ID='MCFT-CAP-08-S6-FORMAL-RUN-A-20260802-REPLACEMENT-006',DBID='MCFT-CAP-08-S6-FORMAL-DB-A-20260802-REPLACEMENT-006',O=p.join(R,'acceptance-output/MCFT_CAP_08_S6_T17_INTERLEAVE_CORRECTED_RUN_A_AUTHORITY_EFFECTIVENESS_RESULT.json');
const P={workflow:'.github/workflows/mcft-cap-08-s6-t17-interleave-corrected-run-a-authority-effectiveness.yml',effective:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-T17-INTERLEAVE-CORRECTED-FORMAL-RUN-A-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',settlement:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-T17-INTERLEAVE-CORRECTED-RUN-A-AUTHORITY-EFFECTIVENESS-V1.json',boundary:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-T17-INTERLEAVE-CORRECTED-RUN-A-AUTHORITY-EFFECTIVENESS-BOUNDARY-V1.json',validator:'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_T17_INTERLEAVE_CORRECTED_RUN_A_AUTHORITY_EFFECTIVENESS_V1.cjs',candidate:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-T17-INTERLEAVE-CORRECTED-FORMAL-RUN-A-AUTHORITY-CANDIDATE-V1.json',manifest:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-T17-INTERLEAVE-CORRECTED-RUN-A-AUTHORITY-OBJECT-SET-V1.json',consumed:'docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-MATERIALIZER-BOUND-FORMAL-RUN-A-EXECUTION-AUTHORITY-EFFECTIVE-V1.json',gate:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/execution_authority_gate_v1.cjs',identity:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_workflow/database_identity_v1.cjs',chain:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/product_chain_v1.cjs',loader:'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/product_loader_v1.cjs'};
const F=[P.workflow,P.effective,P.settlement,P.boundary,P.validator].sort(),g=(...x)=>execFileSync('git',x,{cwd:R,encoding:'utf8'}).trim(),j=x=>JSON.parse(f.readFileSync(p.join(R,x),'utf8'));
function c(v){if(Array.isArray(v))return`[${v.map(c).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${c(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function d(v){const q=structuredClone(v);delete q.semantic_digest;return`sha256:${crypto.createHash('sha256').update(c(q)).digest('hex')}`}
function save(v){f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(v,null,2)+'\n')}
try{
 const b=String(process.env.MCFT_BASE_SHA||B).trim();a.equal(b,B);a.equal(g('merge-base',b,'HEAD'),b);a.equal(g('rev-list','--count',`${b}..HEAD`),'1');a.equal(g('diff','--check',`${b}...HEAD`),'');a.equal(g('diff','--name-only',`${C}...${B}`),'','CANDIDATE_TO_MERGE_FILE_DELTA');a.deepEqual(g('diff','--name-only',`${b}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),F);
 const e=j(P.effective),s=j(P.settlement),z=j(P.boundary),q=j(P.candidate),m=j(P.manifest),old=j(P.consumed);
 a.equal(g('rev-parse',`HEAD:${P.candidate}`),'21f37b1a49e6914534348b8246ab77b522b7e8a0');a.equal(g('rev-parse',`HEAD:${P.manifest}`),'71efd18a8f4d1a333056827964a5520b88818ecd');a.equal(g('rev-parse',`HEAD:${P.consumed}`),'df9eb95baa45328230019df012aa698312432f03');
 a.equal(q.record_status,'FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORITY_CANDIDATE_NOT_EFFECTIVE');a.equal(q.semantic_digest,'sha256:1476451d161d6fa1910da59d09eb39fe009a7a00ed0bc2c97711818e97c61aa2');a.equal(q.exact_subject_sha,S);a.equal(q.operational_run_instance_id,ID);a.equal(q.logical_database_identity.identity_id,DBID);
 a.equal(m.exact_subject_sha,S);a.equal(m.semantic_digest,'sha256:1aef9863615af9c5ac196e810d19e83b6f9f071463b66dffe39e7ca9368a29f5');a.equal(m.object_count,51);a.equal(m.correction_provenance.t17_product_bridge_wired,true);a.equal(m.correction_provenance.s4_executes_after_t16_before_t17,true);a.equal(old.authority_consumed,true);a.equal(old.workflow_dispatch_execution_authorized,false);
 a.equal(g('rev-parse',`HEAD:${P.chain}`),'fe3472b1ac2e0f6e91800172315060d7a4456b0b');a.equal(g('rev-parse',`HEAD:${P.loader}`),'9ede26f14b97677cfa926f67a18aa8b9bc1b5a29');
 const loaderText=f.readFileSync(p.join(R,P.loader),'utf8');for(const required of ['cap08_t17_corrected_handoff_service_v1.ts','cap08_t17_transition_persistence_adapter_v1.ts','cap08_t17_transition_tick_service_v1.ts'])a.ok(loaderText.includes(required),`T17_PRODUCT_LOADER:${required}`);
 const chainText=f.readFileSync(p.join(R,P.chain),'utf8');a.equal(chainText.includes('correctedT17Handoff'),false);for(const required of ['Cap08S4T17CorrectedHandoffServiceV1','Cap08S4T17TransitionPersistenceAdapterV1','Cap08S4T17TransitionTickServiceV1','Cap08S4T17ExplicitRoutingTickServiceV1','S6_T17_AUTHORITY_BOUND_TRANSITION_REQUIRED'])a.ok(chainText.includes(required),`T17_PRODUCT_CHAIN:${required}`);
 a.equal(e.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED');a.equal(e.exact_subject_sha,S);a.equal(e.authorized_run_label,'RUN_A');a.equal(e.operational_run_instance_id,ID);a.equal(e.logical_database_identity.identity_id,DBID);a.equal(e.logical_database_identity.physical_name_template,'geox_mcft_cap08_s6_run_a_replacement_006_<github_run_id>');
 a.equal(e.candidate_authority_ref.blob_sha,'21f37b1a49e6914534348b8246ab77b522b7e8a0');a.equal(e.candidate_authority_ref.preserved_semantic_digest,'sha256:1476451d161d6fa1910da59d09eb39fe009a7a00ed0bc2c97711818e97c61aa2');a.equal(e.candidate_merge_sha,B);a.equal(e.object_set_manifest_ref.blob_sha,'71efd18a8f4d1a333056827964a5520b88818ecd');a.equal(e.single_run_database_execution_authorized,true);a.equal(e.database_execution_workflow_authorized,true);a.equal(e.workflow_dispatch_execution_authorized,true);a.equal(e.final_formal_run_execution_authorized,true);a.equal(e.dual_run_ci_authorized,false);a.equal(e.cross_run_comparator_authorized,false);a.equal(e.final_ledger_settlement_authorized,false);a.equal(e.database_execution_performed,false);a.equal(e.workflow_dispatch_performed,false);a.equal(e.semantic_digest,d(e));
 const {validateExecutionAuthorityV1}=require(p.join(R,P.gate));const ok=validateExecutionAuthorityV1(e,{exactSubjectSha:S,runLabel:'RUN_A',operationalRunInstanceId:ID});a.equal(ok.module_path,'scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/index_v1.cjs');a.throws(()=>validateExecutionAuthorityV1(q,{exactSubjectSha:S,runLabel:'RUN_A',operationalRunInstanceId:ID}));
 const {materializePhysicalDatabaseNameV1}=require(p.join(R,P.identity));a.equal(materializePhysicalDatabaseNameV1(e,'30760000006'),'geox_mcft_cap08_s6_run_a_replacement_006_30760000006');
 a.equal(s.candidate_to_merge_file_delta,0);a.equal(s.effective_authority.blob_sha,'6ecbf4db4a0115de50c1817367416cf1385afb63');a.equal(s.effect.max_dispatch_count,1);a.equal(s.effect.rerun_authorized,false);a.equal(s.effect.run_b_dispatch_authorized,false);a.equal(s.semantic_digest,d(s));a.deepEqual([...z.changed_files].sort(),F);a.equal(z.semantic_digest,d(z));
 a.doesNotMatch(f.readFileSync(p.join(R,P.workflow),'utf8'),/workflow_dispatch:|postgres:|psql|DATABASE_URL/i);
 const r={schema_version:'geox_mcft_cap08_s6_t17_interleave_corrected_run_a_authority_effectiveness_result_v1',status:'PASS',base_main_sha:b,exact_head_sha:g('rev-parse','HEAD'),candidate_to_merge_file_delta:0,exact_subject_sha:S,operational_run_instance_id:ID,logical_database_identity:DBID,object_count:51,runtime_gate_eligible_after_merge:true,production_gate_accepts_effective_authority:true,production_gate_rejects_candidate:true,t17_product_bridge_frozen:true,s4_t16_t17_sequence_frozen:true,authority_bound_database_identity:true,replacement_005_consumed:true,run_b_dispatch_authorized:false,max_dispatch_count:1,rerun_authorized:false,database_execution_performed:false,workflow_dispatch_performed:false,formal_run_result_present:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};save(r);console.log(JSON.stringify(r,null,2));
}catch(e){save({schema_version:'geox_mcft_cap08_s6_t17_interleave_corrected_run_a_authority_effectiveness_result_v1',status:'FAIL',error:e.message||String(e)});throw e}
