#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),https=require('node:https');
const ROOT=path.resolve(__dirname,'../..'),SUBJECT=process.env.MCFT_SUBJECT_SHA,TOKEN=process.env.GITHUB_TOKEN,REPO=process.env.GITHUB_REPOSITORY;
const WORKFLOW='mcft-cap-08-s6-final-closure.yml';
const STATUS='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-DELIVERY-STATUS-V1.json';
const EVIDENCE='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FINAL-CLOSURE-EVIDENCE-V1.json';
const LEDGER='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-HARD-ACCEPTANCE-LEDGER-V1.json';
const BOUNDARY='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-CANDIDATE-BOUNDARY-V1.json';
const load=p=>JSON.parse(fs.readFileSync(path.resolve(ROOT,p),'utf8'));
const git=(...a)=>cp.execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v);}
const digest=v=>`sha256:${crypto.createHash('sha256').update(Buffer.from(canonical(v))).digest('hex')}`;
function api(endpoint){return new Promise((resolve,reject)=>{const req=https.request({hostname:'api.github.com',path:`/repos/${REPO}${endpoint}`,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${TOKEN}`,'X-GitHub-Api-Version':'2022-11-28','User-Agent':'mcft-cap08-s6-exact-sha-attestation'}},res=>{let body='';res.setEncoding('utf8');res.on('data',c=>body+=c);res.on('end',()=>{if(res.statusCode<200||res.statusCode>=300)return reject(new Error(`GITHUB_API_${res.statusCode}:${endpoint}:${body.slice(0,300)}`));resolve(body?JSON.parse(body):{});});});req.on('error',reject);req.end();});}
function declaration(body){const m=String(body||'').match(/<!-- MCFT_CANDIDATE_DECLARATION_V2\n([\s\S]*?)\n-->/);if(!m)throw new Error('CANDIDATE_DECLARATION_V2_MISSING');const out={};for(const line of m[1].split(/\r?\n/)){const i=line.indexOf('=');if(i>0)out[line.slice(0,i).trim()]=line.slice(i+1).trim();}return out;}
async function main(){
 assert.match(SUBJECT||'',/^[0-9a-f]{40}$/);assert.equal(git('rev-parse','HEAD'),SUBJECT);
 const parents=git('rev-list','--parents','-n','1',SUBJECT).split(/\s+/);assert.equal(parents.length,3,`PROTECTED_MERGE_COMMIT_REQUIRED:${parents.length-1}`);
 const base=parents[1],candidate=parents[2],candidateTree=git('rev-parse',`${candidate}^{tree}`),mergeTree=git('rev-parse',`${SUBJECT}^{tree}`);assert.equal(candidateTree,mergeTree,'CANDIDATE_TO_MERGE_TREE_DELTA_NONZERO');
 const status=load(STATUS),evidence=load(EVIDENCE),ledger=load(LEDGER),boundary=load(BOUNDARY);
 assert.equal(boundary.base_main_sha,base);const actual=git('diff','--name-only',`${base}...${candidate}`).split(/\r?\n/).filter(Boolean).sort();assert.deepEqual(actual,boundary.changed_files);assert.equal(actual.length,8);
 assert.equal(status.s6_candidate_implemented,true);assert.equal(status.externally_effective,false);assert.equal(status.required_closure_retention_level,'R2');assert.equal(status.required_closure_retention_days,730);assert.equal(status.candidate_hard_acceptance_pass_count,24);assert.equal(status.mcft_cap_08_complete,false);assert.equal(status.mcft_cap_09_authorized,false);
 assert.equal(evidence.candidate_resolution.hard_acceptance_pass_count,24);assert.equal(evidence.formal_comparator.semantic_equivalence,true);assert.equal(evidence.formal_comparator.difference_count,0);assert.equal(ledger.candidate_pass_count,24);assert.equal(ledger.items.length,24);assert.equal(ledger.effective_resolution_complete,false);
 const pulls=await api(`/commits/${SUBJECT}/pulls`);const pr=pulls.find(x=>x.merge_commit_sha===SUBJECT&&x.head?.sha===candidate&&x.base?.sha===base);if(!pr)throw new Error('MERGED_CANDIDATE_PR_NOT_FOUND');const d=declaration(pr.body);
 assert.equal(d.capability_line,'MCFT-CAP-08');assert.equal(d.slice_id,'MCFT-CAP-08.S6');assert.equal(d.status_file,STATUS);assert.equal(d.candidate_field,'s6_candidate_implemented');assert.equal(d.candidate_value,'true');assert.equal(d.focused_workflow,'mcft-cap-08-s6-final-closure');assert.equal(d.standard_workflow,'ci');assert.equal(d.candidate_head,candidate);assert.equal(d.base_head,base);
 const snapshotFiles=d.semantic_snapshot_files.split(','),snapshotBlobs=d.semantic_snapshot_blobs.split(',');assert.equal(snapshotFiles.length,4);assert.equal(snapshotFiles.length,snapshotBlobs.length);for(let i=0;i<snapshotFiles.length;i++){assert.equal(git('rev-parse',`${candidate}:${snapshotFiles[i]}`),snapshotBlobs[i],`CANDIDATE_SNAPSHOT_DRIFT:${snapshotFiles[i]}`);assert.equal(git('rev-parse',`${SUBJECT}:${snapshotFiles[i]}`),snapshotBlobs[i],`MERGE_SNAPSHOT_DRIFT:${snapshotFiles[i]}`);}
 const runData=await api(`/actions/workflows/${WORKFLOW}/runs?event=pull_request&head_sha=${candidate}&per_page=100`);const runs=runData.workflow_runs.filter(r=>r.head_sha===candidate&&r.run_attempt===1&&r.status==='completed'&&r.conclusion==='success');assert.equal(runs.length,1,`UNIQUE_FOCUSED_CANDIDATE_RUN_REQUIRED:${runs.length}`);const run=runs[0];
 const jobs=await api(`/actions/runs/${run.id}/jobs?per_page=100`);const q=jobs.jobs.filter(j=>j.name==='qualify-s6-final-closure-candidate');assert.equal(q.length,1);assert.equal(q[0].conclusion,'success');
 const arts=await api(`/actions/runs/${run.id}/artifacts?per_page=100`);const expectedName=`mcft-cap-08-s6-final-closure-${candidate}`;const matches=arts.artifacts.filter(a=>a.name===expectedName&&a.expired===false);assert.equal(matches.length,1,`UNIQUE_FOCUSED_ARTIFACT_REQUIRED:${matches.length}`);const focused=matches[0];assert.match(focused.digest||'',/^sha256:[0-9a-f]{64}$/);
 const artifact={schema_version:'geox_mcft_cap08_s6_exact_sha_r2_attestation_v1',status:'PASS',capability_line_id:'MCFT-CAP-08',slice_id:'MCFT-CAP-08.S6',subject_commit:SUBJECT,subject_sha:SUBJECT,merge_commit_sha:SUBJECT,candidate_pr_number:pr.number,candidate_head_sha:candidate,candidate_tree_sha:candidateTree,merge_tree_sha:mergeTree,candidate_to_merge_tree_delta:0,candidate_focused_workflow_run_id:run.id,candidate_focused_workflow_run_attempt:run.run_attempt,candidate_focused_artifact_id:focused.id,candidate_focused_artifact_digest:focused.digest,formal_evidence:{exact_execution_subject_sha:evidence.exact_execution_subject_sha,run_a_workflow_run_id:evidence.formal_runs.run_a.workflow_run_id,run_a_artifact_id:evidence.formal_runs.run_a.artifact_id,run_a_formal_artifact_digest:evidence.formal_runs.run_a.formal_artifact_digest,run_b_workflow_run_id:evidence.formal_runs.run_b.workflow_run_id,run_b_artifact_id:evidence.formal_runs.run_b.artifact_id,run_b_formal_artifact_digest:evidence.formal_runs.run_b.formal_artifact_digest,comparator_workflow_run_id:evidence.formal_comparator.workflow_run_id,comparator_artifact_id:evidence.formal_comparator.artifact_id,comparator_artifact_digest:evidence.formal_comparator.github_artifact_digest,semantic_digest_a:evidence.formal_comparator.semantic_digest_a,semantic_digest_b:evidence.formal_comparator.semantic_digest_b,semantic_equivalence:true,difference_count:0,independent_database_instances:true},hard_acceptance_resolution:{item_count:24,candidate_resolved_item_count:24,effective_resolved_item_count:24,failed_item_count:0,all_items_pass:true},zero_write_acceptance_result:{product_observation_write_delta:0,canonical_fact_write_delta:0,projection_write_delta:0,production_runtime_source_authorized:false},retention_contract:{level:'R2',days:730,upload_readback_required:true,locked_version_delete_denied_required:true,retention_execution_follows_this_canonical_artifact:true},effective_delivery_frontier_projection:{effective_status:'MCFT_CAP_08_COMPLETE',effective_next_slice:null,mcft_cap_09_authorized:false},capability_complete:true,completion_level:'STAGE_1A_REPLAY_BACKED_CLOSURE_COMPLETE',postmerge_ssot_writeback:false,nonclaims:['NO_720_TICK_LONG_HORIZON_QUALIFICATION','NO_LIVE_SENSOR_RUNTIME','NO_SHADOW_ONLINE','NO_BACKGROUND_SCHEDULER','NO_AUTOMATIC_RECOMMENDATION','NO_AUTOMATIC_APPROVAL','NO_AO_ACT','NO_DISPATCH','NO_MODEL_ACTIVATION','NO_CAUSAL_ACTION_EFFECT_PROOF','NO_ROI_PROOF','NO_MULTI_FIELD_SCALE','NO_PRODUCTIZATION_COMPLETE','NO_MCFT_CAP_09_AUTHORITY']};artifact.semantic_artifact_digest=digest(artifact);
 fs.mkdirSync(path.join(ROOT,'acceptance-output'),{recursive:true});fs.writeFileSync(path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_EXACT_SHA_ATTESTATION.json'),JSON.stringify(artifact,null,2)+'\n');console.log(JSON.stringify({status:'PASS',subject_commit:SUBJECT,candidate_head_sha:candidate,candidate_to_merge_tree_delta:0,hard_acceptance_pass_count:24,focused_run_id:run.id,focused_artifact_id:focused.id}));
}
main().catch(e=>{console.error(e);process.exit(1);});
