// scripts/governance_acceptance/ACCEPTANCE_ROOT_ZONE_SOIL_WATER_STATE_SCHEMA_MIGRATION_V1.cjs
const fs=require("node:fs"); const {Pool}=require("pg");
const name="ACCEPTANCE_ROOT_ZONE_SOIL_WATER_STATE_SCHEMA_MIGRATION_V1"; const migration="apps/server/db/migrations/2026_06_21_root_zone_soil_water_state_v1.sql"; const probe="h32_root_zone_soil_water_state_acceptance_schema_probe";
function fail(m,d){console.error(`[${name}] FAIL: ${m}`); if(d) console.error(d); process.exit(1)} function assert(c,m,d){if(!c) fail(m,d)}
(async()=>{ const sql=fs.readFileSync(migration,"utf8"); assert(fs.existsSync(migration),"migration file exists"); assert(!/DROP\s+TABLE/i.test(sql),"No DROP TABLE"); assert(!/TRUNCATE/i.test(sql),"No production table truncation");
const url=process.env.DATABASE_URL||process.env.POSTGRES_URL||process.env.PG_URL; assert(url,"DATABASE_URL/POSTGRES_URL/PG_URL required"); const pool=new Pool({connectionString:url}); const client=await pool.connect();
try{ await client.query("BEGIN"); await client.query(sql); await client.query(sql); const reg=await client.query("SELECT to_regclass('public.root_zone_soil_water_state_index_v1')::text name"); assert(reg.rows[0].name,"table exists after migration inside transaction");
const cols=(await client.query("SELECT column_name,data_type FROM information_schema.columns WHERE table_schema='public' AND table_name='root_zone_soil_water_state_index_v1'")).rows; const map=Object.fromEntries(cols.map(r=>[r.column_name,r.data_type]));
for(const c of ['state_id','tenant_id','project_id','group_id','field_id','zone_id','root_zone_depth_cm','layer_estimate_refs_json','layer_count','estimated_layer_count','blocked_layer_count','weighted_matric_potential_kpa','root_zone_available_water_fraction','root_zone_water_potential_class','worst_layer_class','stress_layer_count','limited_layer_count','input_status','blocking_reasons_json','calculation_inputs_json','derivation_json','confidence_json','determinism_hash','source_fact_id','computed_at','updated_at']) assert(map[c],`required column exists: ${c}`);
for(const c of ['layer_estimate_refs_json','blocking_reasons_json','calculation_inputs_json','derivation_json','confidence_json']) assert(map[c]==='jsonb',`JSONB column is JSONB: ${c}`);
const indexes=(await client.query("SELECT indexname FROM pg_indexes WHERE schemaname='public' AND tablename='root_zone_soil_water_state_index_v1'")).rows.map(r=>r.indexname); for(const idx of ['idx_root_zone_soil_water_state_index_v1_scope_latest','idx_root_zone_soil_water_state_index_v1_field_latest']) assert(indexes.includes(idx),`required index exists: ${idx}`);
await client.query(`INSERT INTO public.root_zone_soil_water_state_index_v1 (state_id,tenant_id,project_id,group_id,field_id,zone_id,root_zone_depth_cm,layer_count,estimated_layer_count,blocked_layer_count,root_zone_water_potential_class,worst_layer_class,stress_layer_count,limited_layer_count,input_status,determinism_hash,computed_at) VALUES ($1,'t','p','g','f','z',60,0,0,0,'UNKNOWN','UNKNOWN',0,0,'INSUFFICIENT_LAYER_ESTIMATES','hash','2026-06-21T00:00:00Z')`,[probe]);
assert((await client.query("SELECT COUNT(*)::int count FROM public.root_zone_soil_water_state_index_v1 WHERE state_id=$1",[probe])).rows[0].count===1,"probe row can be inserted"); await client.query("ROLLBACK");
const absent=await pool.query("SELECT to_regclass('public.root_zone_soil_water_state_index_v1')::text name"); if(absent.rows[0].name){ const count=await pool.query("SELECT COUNT(*)::int count FROM public.root_zone_soil_water_state_index_v1 WHERE state_id=$1",[probe]); assert(count.rows[0].count===0,"rollback removes probe row"); }
console.log(`[${name}] PASS`);
} catch(e){ try{await client.query("ROLLBACK")}catch{} fail(e.message,e.stack)} finally{client.release(); await pool.end()}})();
