'use strict';
const fs=require('node:fs'),path=require('node:path'),{execFileSync}=require('node:child_process');
const ROOT=process.cwd(),BASE=process.env.MCFT_BASE_SHA||'',EXPECTED_BASE='b31b024c17b617f0e1c36010c8c3926682bd6533';
const CONFIG='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-RAIN-SOLAR-SOURCE-DISCOVERY-V1.json',PROBE='scripts/runtime_acceptance/PROBE_MCFT_CAP_09_EA4_RAIN_SOLAR_SOURCE_DISCOVERY.mjs',GATE='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_EA4_RAIN_SOLAR_SOURCE_DISCOVERY.cjs',WF='.github/workflows/mcft-cap-09-ea4-rain-solar-source-discovery.yml',EA4='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-EA4-LIVE-SOURCE-EXACT-HEAD-QUALIFICATION-V1.json';
const EXPECT=[CONFIG,PROBE,GATE,WF].sort(),OUT=path.join(ROOT,'acceptance-output/MCFT_CAP_09_EA4_RAIN_SOLAR_SOURCE_DISCOVERY_STATIC_RESULT.json');
const PINS={ea4_rejection:'791e3d24bdc862641c77ddd26778495cb8e6a7dd',config:'44f07c223519e8e22531906733ff34c8614aaa79',probe:'326b003874a33927e5ed8f93397860adde8ae744'};
const git=(...args)=>execFileSync('git',args,{cwd:ROOT,encoding:'utf8'}).trim(),blob=(ref,file)=>git('rev-parse',`${ref}:${file}`),read=(file)=>fs.readFileSync(path.join(ROOT,file),'utf8'),json=(file)=>JSON.parse(read(file)),req=(ok,code)=>{if(!ok)throw new Error(code)};
const result={schema_version:'geox_mcft_cap09_ea4_rain_solar_source_discovery_static_acceptance_v1',status:'FAIL',base_sha:BASE,database_write_count:0,formal_evidence_write_count:0,formal_window_started:false};
try{
  req(BASE===EXPECTED_BASE,`EA4RS_BASE_MAIN_DRIFT:${BASE}`);const changed=git('diff','--name-only',`${BASE}...HEAD`).split(/\r?\n/).filter(Boolean).sort();Object.assign(result,{changed_files:changed,exact_file_count:changed.length});req(JSON.stringify(changed)===JSON.stringify(EXPECT),`EA4RS_EXACT_FOUR_FILE_BOUNDARY_FAIL:${JSON.stringify(changed)}`);
  req(blob(BASE,EA4)===PINS.ea4_rejection,'EA4RS_EA4_REJECTION_AUTHORITY_DRIFT');req(blob('HEAD',CONFIG)===PINS.config,'EA4RS_CONFIG_BLOB_DRIFT');req(blob('HEAD',PROBE)===PINS.probe,'EA4RS_PROBE_BLOB_DRIFT');
  const ea4=json(EA4),config=json(CONFIG),probe=read(PROBE),workflow=read(WF);req(ea4.live_qualification?.current_result==='REJECTED_EA4_KBS_RAW_HOURLY_FRESHNESS_AUTHORITY','EA4RS_REJECTION_PREDECESSOR_REQUIRED');req(ea4.authority_effect?.new_source_architecture_adjudication_required_before_ea5===true,'EA4RS_SOURCE_ARCHITECTURE_DISCOVERY_NOT_AUTHORIZED');req(ea4.authority_effect?.ea5_candidate_development_authorized===false,'EA4RS_EA5_MUST_REMAIN_BLOCKED');
  req(config.record_status==='SOURCE_DISCOVERY_ONLY_NOT_AUTHORITY'&&config.base_main_sha===BASE,'EA4RS_CONFIG_STATUS_OR_BASE_DRIFT');req(config.provider==='MSU_ENVIROWEATHER'&&config.target_station_slug==='kbs','EA4RS_PROVIDER_OR_STATION_DRIFT');req(config.source_page==='https://enviroweather.msu.edu/crops/potato/dailyheatandmoisture','EA4RS_SOURCE_PAGE_DRIFT');req(config.target_capabilities.interval_or_daily_rainfall===true&&config.target_capabilities.observed_solar_radiation_or_solar_flux===true,'EA4RS_TARGET_CAPABILITIES_DRIFT');
  req(config.interaction_policy.select_target_station===true&&config.interaction_policy.submit_model===true&&config.interaction_policy.export_csv_click_authorized===false&&config.interaction_policy.login_authorized===false,'EA4RS_INTERACTION_POLICY_DRIFT');req(config.interaction_policy.query_values_may_be_emitted===false&&config.interaction_policy.raw_numeric_observation_values_may_be_emitted===false&&config.interaction_policy.raw_json_or_csv_body_may_be_persisted===false&&config.interaction_policy.rendered_dom_may_be_persisted===false,'EA4RS_DISCOVERY_PRIVACY_BOUNDARY_WEAKENED');for(const key of ['creates_formal_source_authority','creates_source_substitution_authority','qualifies_rainfall','qualifies_solar_radiation','database_write_authorized','formal_evidence_write_authorized','formal_window_started','ea5_authorized','mcft_cap09_completed'])req(config.discovery_effect[key]===false,`EA4RS_DISCOVERY_EFFECT_OVERCLAIM:${key}`);
  const compact=probe.replace(/\s+/g,'');for(const token of ['chromium.launch','selectTargetStation','submitModel','primitive_summaries','<embedded_json>','<embedded_html_table>','query_value_presence','directRunUrl','direct_query_fallback_used','query_values_emitted:false','raw_numeric_observation_values_emitted:false','raw_response_body_persisted:false','export_csv_clicked:false','rainfall_qualified:false','solar_radiation_qualified:false'])req(compact.includes(token.replace(/\s+/g,'')),`EA4RS_PROBE_REQUIRED_TOKEN_MISSING:${token}`);req(!/DATABASE_URL|POSTGRES(?:QL)?|NEON_DATABASE_URL|psql\b|INSERT\s+INTO|public\.facts/.test(probe),'EA4RS_DATABASE_OR_FACTS_WRITE_SURFACE_FORBIDDEN');req(!/page\.on\(['\"]download|saveAs\(|createWriteStream\(/.test(probe),'EA4RS_DOWNLOAD_PERSISTENCE_FORBIDDEN');
  req(workflow.includes('persist-credentials: false')&&workflow.includes('playwright install --with-deps chromium'),'EA4RS_WORKFLOW_CREDENTIAL_OR_CHROMIUM_DRIFT');req(workflow.includes('MCFT_BASE_SHA')&&workflow.includes('MCFT_SUBJECT_SHA'),'EA4RS_WORKFLOW_EXACT_SHA_MISSING');req(!/DATABASE_URL|POSTGRES(?:QL)?|NEON_DATABASE_URL/.test(workflow),'EA4RS_WORKFLOW_DATABASE_SECRET_FORBIDDEN');
  Object.assign(result,{status:'PASS',ea4_rejection_authority_blob:PINS.ea4_rejection,discovery_creates_formal_source_authority:false,rainfall_qualified:false,solar_radiation_qualified:false,ea5_authorized:false});
}catch(error){result.error=`${error.name||'Error'}:${error.message||String(error)}`;process.exitCode=1}fs.mkdirSync(path.dirname(OUT),{recursive:true});fs.writeFileSync(OUT,JSON.stringify(result,null,2)+'\n');if(result.status==='PASS')console.log(JSON.stringify(result));else console.error(result.error);
