#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),c=require('node:crypto'),x=require('node:child_process'),f=require('node:fs'),p=require('node:path');
const R=p.resolve(__dirname,'../..'),BASE='208ad8ec34cde4e129e66805d47a994141303d24',D='docs/digital_twin/mcft/cap_08/',O=p.join(R,'acceptance-output/MCFT_CAP_08_S6_CTO_DUAL_ACCOUNT_VERIFICATION_DEFERRAL_RESULT.json'),TEXT='CTO裁决：搁置双账户的验证。';
const P={w:'.github/workflows/mcft-cap-08-s6-pre-candidate-governance.yml',g:'docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json',b:D+'GEOX-MCFT-CAP-08-S6-CTO-DUAL-ACCOUNT-VERIFICATION-DEFERRAL-BOUNDARY-V1.json',r:D+'GEOX-MCFT-CAP-08-S6-CTO-DUAL-ACCOUNT-VERIFICATION-DEFERRAL-V1.json',c:D+'GEOX-MCFT-CAP-08-S6-CONTRACT-V1.json',s:D+'GEOX-MCFT-CAP-08-S6-DELIVERY-STATUS-V1.json',v:D+'GEOX-MCFT-CAP-08-S6-REVIEW-POLICY-V1.json',d:D+'GEOX-MCFT-CAP-08-S6-WORKFLOW-DECLARATION-V1.json',q:'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_CTO_DUAL_ACCOUNT_VERIFICATION_DEFERRAL_V1.cjs'};
const git=(...z)=>x.execFileSync('git',z,{cwd:R,encoding:'utf8'}).trim(),j=z=>JSON.parse(f.readFileSync(p.join(R,z),'utf8')),out=z=>{f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(z,null,2)+'\n')};
function k(z){if(Array.isArray(z))return'['+z.map(k).join(',')+']';if(z&&typeof z==='object')return'{'+Object.keys(z).sort().map(y=>JSON.stringify(y)+':'+k(z[y])).join(',')+'}';return JSON.stringify(z)}function h(z){z=structuredClone(z);delete z.semantic_digest;return'sha256:'+c.createHash('sha256').update(k(z)).digest('hex')}
function rule(z){const q=z.capabilities.find(y=>y.capability_line==='MCFT-CAP-08');a.ok(q);const n=q.candidate_transition_fields.filter(y=>y.status_file===P.s&&y.field_path==='s6_candidate_implemented');a.equal(n.length,1);return n[0]}
function norm(z,base){z=structuredClone(z);delete z.authority_set_revision;delete z.authority_set_change_id;const q=rule(z);if(!base){a.equal(q.independent_review_required,false);a.equal(q.independent_review_requirement_state,'SUSPENDED_BY_CTO_RULING');a.equal(q.verified_second_github_account_required,false);a.equal(q.cto_ruling_ref,P.r);q.independent_review_required=true;delete q.independent_review_requirement_state;delete q.verified_second_github_account_required;delete q.cto_ruling_ref}return z}
try{const base=String(process.env.MCFT_BASE_SHA||BASE).trim();a.equal(base,BASE);a.equal(git('merge-base',base,'HEAD'),base);a.equal(git('diff','--check',base+'...HEAD'),'');const files=git('diff','--name-only',base+'...HEAD').split(/\r?\n/).filter(Boolean).sort(),expected=Object.values(P).sort();a.deepEqual(files,expected);
 const [b,r,m,s,v,d,g]=[P.b,P.r,P.c,P.s,P.v,P.d,P.g].map(j),bg=JSON.parse(git('show',base+':'+P.g)),wt=f.readFileSync(p.join(R,P.w),'utf8');
 a.equal(b.base_main_sha,base);a.equal(b.changed_file_count,9);a.deepEqual([...b.changed_files].sort(),expected);for(const z of ['runtime_source_file_count','runtime_acceptance_file_count','migration_file_count','database_execution_workflow_file_count'])a.equal(b[z],0);for(const z of ['database_execution_performed','workflow_dispatch_performed','candidate_declaration_present','candidate_signal_changed','technical_gate_relaxation','s6_candidate_implemented','mcft_cap_08_complete','mcft_cap_09_authorized'])a.equal(b[z],false);a.equal(b.dual_account_verification_suspended,true);a.equal(b.semantic_digest,h(b));a.equal(b.semantic_digest,'sha256:a5268bead767ac582de13dba81f6c3f2c571dfbac0e3bd31e7d16f1e24dd6f99');
 a.equal(r.ruling_authority,'CTO');a.equal(r.ruling_text_zh,TEXT);a.equal(r.effect.independent_review_requirement_state,'SUSPENDED_BY_CTO_RULING');for(const z of ['verified_second_github_account_required','candidate_merge_blocked_by_dual_account_verification','exact_sha_attestation_blocked_by_dual_account_verification','independent_review_satisfied','independent_review_performed','independent_review_waived'])a.equal(r.effect[z],false);a.equal(r.effect.reactivation_requires_separate_cto_ruling,true);a.equal(r.technical_gate_relaxation,false);a.equal(r.semantic_digest,h(r));a.equal(r.semantic_digest,'sha256:2f0e0f8424562ae5017bad355a1942b15c14b5590a0450132d35830f25a010ab');
 for(const z of [v,m.review_contract,s,d])a.equal(z.cto_ruling_text_zh,TEXT);for(const z of [v,m.review_contract,s]){a.equal(z.independent_review_required,false);a.equal(z.verified_second_github_account_required,false);a.equal(z.technical_gate_relaxation,false)}for(const z of ['independent_review_satisfied','independent_review_performed','independent_review_waived'])a.equal(v[z],false);a.equal(v.required_before_candidate_merge,false);a.equal(v.required_before_exact_sha_attestation,false);a.equal(v.reactivation_requires_separate_cto_ruling,true);
 a.equal(m.semantic_digest,h(m));a.equal(m.semantic_digest,'sha256:94c4deee52099563abce6442ddde37103f4efead6bd97ac7bba6b3251549147f');a.equal(m.formal_run_contract.run_count,2);a.equal(m.formal_run_contract.fresh_database_per_run,true);a.equal(m.hard_acceptance_contract.ledger_item_count,24);a.equal(m.read_model_contract.cap07_get_surface_count,10);a.equal(m.read_model_contract.product_read_write_delta,0);a.equal(m.determinism_contract.candidate_merge_tree_equality_required,true);a.equal(m.retention_contract.level,'R2');a.equal(m.retention_contract.days,730);a.equal(m.retention_contract.upload_readback_required,true);a.equal(m.retention_contract.locked_version_delete_denied_required,true);
 a.equal(s.independent_review_verification_suspended,true);a.equal(s.candidate_merge_requires_independent_review,false);a.equal(s.exact_sha_attestation_requires_independent_review,false);a.equal(s.required_closure_retention_level,'R2');a.equal(s.required_closure_retention_days,730);a.equal(s.formal_run_count_expected,2);a.equal(s.fresh_database_count_expected,2);a.equal(s.hard_acceptance_item_count_expected,24);a.equal(s.cap07_get_surface_count_expected,10);a.equal(s.s6_candidate_implemented,false);a.equal(s.mcft_cap_08_complete,false);a.equal(s.mcft_cap_09_authorized,false);
 for(const z of [d.candidate_workflow,d.exact_sha_workflow]){a.equal(z.requires_exact_head_independent_approval,false);a.equal(z.dual_account_verification_suspended_by_cto,true);a.equal(z.technical_gate_relaxation,false)}a.equal(d.exact_sha_workflow.requires_candidate_merge_tree_equality,true);a.equal(d.exact_sha_workflow.runs_two_fresh_databases_on_exact_merge_sha,true);a.equal(d.exact_sha_workflow.retention_days,730);
 a.equal(g.registry_revision,'1.1');a.equal(g.authority_set_revision,'1.5');a.equal(g.authority_set_change_id,'MCFT-CAP-08.S6-CTO-DUAL-ACCOUNT-VERIFICATION-DEFERRAL');a.deepEqual(norm(g,false),norm(bg,true));a.match(wt,/mode=cto-deferral/);a.match(wt,/ACCEPTANCE_MCFT_CAP_08_S6_CTO_DUAL_ACCOUNT_VERIFICATION_DEFERRAL_V1\.cjs/);a.doesNotMatch(wt,/workflow_dispatch:|postgres|psql|DATABASE_URL/i);a.equal(files.some(z=>z.startsWith('apps/server/')||z.startsWith('apps/web/')||/migration|scheduler|model_activation/i.test(z)),false);const marker=['MCFT','CANDIDATE','DECLARATION','V2'].join('_');a.equal(files.filter(z=>z!==P.q).map(z=>f.readFileSync(p.join(R,z),'utf8')).join('\n').includes(marker),false);
 const result={schema_version:'geox_mcft_cap08_s6_cto_dual_account_verification_deferral_result_v1',status:'PASS',base_main_sha:base,exact_head_sha:git('rev-parse','HEAD'),changed_file_count:files.length,cto_ruling_text_zh:TEXT,independent_review_requirement_state:'SUSPENDED_BY_CTO_RULING',independent_review_satisfied:false,independent_review_performed:false,independent_review_waived:false,verified_second_github_account_required:false,candidate_merge_blocked_by_dual_account_verification:false,exact_sha_attestation_blocked_by_dual_account_verification:false,technical_gate_relaxation:false,r2_retention_days:730,formal_run_count:2,hard_acceptance_item_count:24,cap07_get_surface_count:10,database_execution_performed:false,workflow_dispatch_performed:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};out(result);console.log(JSON.stringify(result,null,2))}catch(e){out({schema_version:'geox_mcft_cap08_s6_cto_dual_account_verification_deferral_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});throw e}
