#!/usr/bin/env node
'use strict';
const A=require('node:assert/strict'),C=require('node:crypto'),P=require('node:child_process'),F=require('node:fs'),X=require('node:path');
const R=X.resolve(__dirname,'../..'),D='docs/digital_twin/mcft/cap_08',AP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-EXECUTION-AUTHORITY-V1.json`,BP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-EXECUTION-AUTHORITY-BOUNDARY-V1.json`,GP=`${D}/GEOX-MCFT-CAP-08-S6-RUN-A-QUALIFICATION-AUTHORITY-ISSUANCE-GATE-V1.json`,W='.github/workflows/mcft-cap-08-s6-run-a-qualification-execution-authority.yml',Q=X.join(R,'acceptance-output/MCFT_CAP_08_S6_RUN_A_QUALIFICATION_EXECUTION_AUTHORITY_RESULT.json');
const r=p=>JSON.parse(F.readFileSync(X.join(R,p),'utf8')),t=p=>F.readFileSync(X.join(R,p),'utf8'),git=(...a)=>P.execFileSync('git',a,{cwd:R,encoding:'utf8'}).trim(),c=v=>Array.isArray(v)?`[${v.map(c)}]`:v&&typeof v==='object'?`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${c(v[k])}`)}}`:JSON.stringify(v),sd=v=>{v=structuredClone(v);delete v.semantic_digest;return`sha256:${C.createHash('sha256').update(c(v)).digest('hex')}`},out=v=>{F.mkdirSync(X.dirname(Q),{recursive:true});F.writeFileSync(Q,JSON.stringify(v,null,2)+'\n')};
try{
 const a=r(AP),b=r(BP),g=r(GP),base=String(process.env.MCFT_BASE_SHA||b.base_main_sha).trim(),eq=(k,v)=>A.equal(a[k],v,k);
 A.equal(base,b.base_main_sha);A.equal(git('merge-base',base,'HEAD'),base);A.equal(git('diff','--check',`${base}...HEAD`),'');
 const changed=git('diff','--name-only',`${base}...HEAD`).split(/\r?\n/).filter(Boolean).sort();A.deepEqual(changed,[...b.changed_files].sort());A.equal(changed.length,4);for(const v of[a,b])A.equal(v.semantic_digest,sd(v),'SEMANTIC_DIGEST');
 A.equal(g.record_status,'RUN_A_QUALIFICATION_AUTHORITY_ISSUANCE_AUTHORIZED');eq('record_status','SINGLE_DEVELOPMENT_QUALIFICATION_RUN_DATABASE_EXECUTION_AUTHORIZED');eq('authority_class','DEVELOPMENT_QUALIFICATION_ONLY');eq('evidence_class','DEVELOPMENT_QUALIFICATION_ONLY');
 for(const k of['single_run_database_execution_authorized','database_execution_workflow_authorized','workflow_dispatch_execution_authorized'])eq(k,true);
 for(const k of['final_formal_run_execution_authorized','final_closure_eligible','hard_acceptance_eligible','s6_candidate_evidence_eligible','cross_run_comparison_eligible','ledger_settlement_eligible','dual_run_ci_authorized','cross_run_comparator_authorized','final_ledger_settlement_authorized'])eq(k,false);
 eq('exact_subject_sha',base);eq('authorized_run_label','RUN_A');eq('operational_run_instance_id','MCFT-CAP-08-S6-RUN-A-QUAL-20260729-001');eq('port_bundle_path','scripts/runtime_acceptance/mcft_cap08_s6_single_run_ports/index_v1.cjs');eq('port_bundle_blob_sha','2f574588ba3010a94e64f965bb17fc97b3b33c72');eq('qualification_workflow_blob_sha','2478bf7fd75fbf89179f6bafbeda41499c89b55c');eq('qualification_gate_blob_sha','101ab0177db548f66493ee3aae75d3a9cf6b7080');
 A.deepEqual(a.database_identity,{database_name:'geox_mcft_cap08_s6_run_a_qual_001',fresh_disposable_required:true,drop_after_run_required:true,identity_frozen:true});const issued=Date.parse(a.issued_at),expires=Date.parse(a.expires_at);A.ok(expires>issued&&expires-issued<=86400000&&expires>Date.now(),'AUTHORITY_TIME_INVALID');
 for(const [p,h] of[[a.port_bundle_path,a.port_bundle_blob_sha],[a.qualification_workflow_path,a.qualification_workflow_blob_sha],[a.qualification_gate_path,a.qualification_gate_blob_sha]])A.equal(git('rev-parse',`${base}:${p}`),h,`BLOB_DRIFT:${p}`);
 const v=require(X.join(R,a.qualification_gate_path)).validateQualificationAuthorityV1(a,{exactSubjectSha:base,runLabel:'RUN_A',operationalRunInstanceId:a.operational_run_instance_id});A.equal(v.module_path,a.port_bundle_path);
 const w=t(W);A.match(w,/pull_request:/);for(const x of[/workflow_dispatch:/,/services:\s*\n\s*postgres:/,/DATABASE_URL/])A.doesNotMatch(w,x);for(const k of['database_execution_performed','workflow_dispatch_performed','run_a_executed','run_b_executed'])A.equal(b[k],false,k);
 const z={schema_version:'geox_mcft_cap08_s6_run_a_qualification_execution_authority_result_v1',status:'PASS',subject_sha:git('rev-parse','HEAD'),base_sha:base,changed_file_count:4,authority_status:a.record_status,authority_class:a.authority_class,evidence_class:a.evidence_class,exact_subject_sha:a.exact_subject_sha,run_label:a.authorized_run_label,operational_run_instance_id:a.operational_run_instance_id,database_name:a.database_identity.database_name,port_bundle_blob_sha:a.port_bundle_blob_sha,qualification_workflow_blob_sha:a.qualification_workflow_blob_sha,qualification_gate_blob_sha:a.qualification_gate_blob_sha,expires_at:a.expires_at,database_execution_performed:false,workflow_dispatch_performed:false,run_a_executed:false,run_b_executed:false,hard_acceptance_eligible:false,s6_candidate_implemented:false,mcft_cap_08_complete:false,mcft_cap_09_authorized:false};out(z);console.log(JSON.stringify(z,null,2));
}catch(e){out({schema_version:'geox_mcft_cap08_s6_run_a_qualification_execution_authority_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1}
