#!/usr/bin/env node
'use strict';
const assert=require('node:assert/strict'),crypto=require('node:crypto'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{execFileSync,spawnSync}=require('node:child_process');
const ROOT=path.resolve(__dirname,'../..'),BASE='596510a233e9c3727ae46405b471acbb29d4984f',SUBJECT='ce9d6b4df8c708c0d4a99bb24846e1bc44b3cf59';
const CANDIDATE='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-CANDIDATE-V1.json',OBJECTS='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-OBJECT-SET-V1.json',ISSUANCE='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-ISSUANCE-V1.json',SUPERSESSION='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-SUPERSESSION-V1.json',BOUNDARY='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-REPLACEMENT-001-AUTHORITY-BOUNDARY-V1.json',WORKFLOW='.github/workflows/mcft-cap-08-s6-formal-cross-run-comparator-replacement-001-authority-candidate.yml',VALIDATOR='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_08_S6_FORMAL_CROSS_RUN_COMPARATOR_REPLACEMENT_001_AUTHORITY_CANDIDATE_V1.cjs';
const WRAPPER='scripts/runtime_acceptance/mcft_cap08_s6_formal_comparator/formal_semantic_comparator_v1.cjs',CONTROL='scripts/runtime_acceptance/mcft_cap08_s6_formal_comparator/formal_comparator_execution_control_v1.cjs',PREDECESSOR='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S6-FORMAL-CROSS-RUN-COMPARATOR-AUTHORITY-CANDIDATE-V1.json';
const CHANGED=[CANDIDATE,OBJECTS,ISSUANCE,SUPERSESSION,BOUNDARY,WORKFLOW,VALIDATOR].sort();
const A_DIR=process.env.MCFT_RUN_A_ARTIFACT_DIR||path.join(ROOT,'acceptance-input/formal-run-a'),B_DIR=process.env.MCFT_RUN_B_ARTIFACT_DIR||path.join(ROOT,'acceptance-input/formal-run-b'),AUDIT=process.env.MCFT_COMPARATOR_REPLACEMENT_INPUT_AUDIT||path.join(ROOT,'acceptance-input/FORMAL_COMPARATOR_REPLACEMENT_001_CANDIDATE_INPUT_AUDIT.json'),OUTPUT=path.join(ROOT,'acceptance-output/MCFT_CAP_08_S6_FORMAL_COMPARATOR_REPLACEMENT_001_AUTHORITY_CANDIDATE_RESULT.json');
const git=(...a)=>execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim(),read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),'utf8'));
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v)}
function semanticDigest(v){const c=structuredClone(v);delete c.semantic_digest;return`sha256:${crypto.createHash('sha256').update(canonical(c)).digest('hex')}`}
function save(v){fs.mkdirSync(path.dirname(OUTPUT),{recursive:true});fs.writeFileSync(OUTPUT,`${JSON.stringify(v,null,2)}\n`)}
try{
 const base=String(process.env.MCFT_BASE_SHA||BASE).trim();assert.equal(base,BASE,'BASE_MAIN_SHA');assert.equal(git('merge-base',BASE,'HEAD'),BASE,'BASE_NOT_ANCESTOR');assert.equal(git('rev-list','--count',`${BASE}..HEAD`),'1','COMMIT_COUNT');assert.equal(git('diff','--check',`${BASE}...HEAD`),'','DIFF_CHECK');assert.deepEqual(git('diff','--name-only',`${BASE}...HEAD`).split(/\r?\n/).filter(Boolean).sort(),CHANGED,'BOUNDARY');
 const candidate=read(CANDIDATE),objects=read(OBJECTS),issuance=read(ISSUANCE),supersession=read(SUPERSESSION),boundary=read(BOUNDARY),predecessor=read(PREDECESSOR);
 for(const r of [candidate,objects,issuance,supersession,boundary])assert.equal(r.semantic_digest,semanticDigest(r),`SEMANTIC_DIGEST:${r.schema_version}`);
 assert.equal(git('rev-parse',`HEAD:${CANDIDATE}`),'dffb2a6df42c4a0860f461761f1cf3e2d360c8ac');assert.equal(git('rev-parse',`HEAD:${OBJECTS}`),'57d7817bc60074baee4ca3bd71c21e9bb5dab3b2');assert.equal(git('rev-parse',`HEAD:${ISSUANCE}`),'7742c7a18c9a2d79136092456f1fdb360380b060');assert.equal(git('rev-parse',`HEAD:${SUPERSESSION}`),'1cb00a089a2e9085bf941d15df8b4add66a699d5');assert.equal(git('rev-parse',`HEAD:${BOUNDARY}`),'37f7667ff84871815426b0af22316ad00c42c839');assert.equal(git('rev-parse',`HEAD:${WORKFLOW}`),'27e669bc7be9dc1c529755eadce465e41d60db5c');
 assert.equal(candidate.record_status,'FORMAL_CROSS_RUN_COMPARATOR_REPLACEMENT_001_AUTHORITY_CANDIDATE_NOT_EFFECTIVE');assert.equal(candidate.exact_subject_sha,SUBJECT);assert.equal(candidate.authority_effective,false);assert.equal(candidate.comparator_execution_authorized,false);assert.equal(candidate.maximum_execution_count,1);assert.equal(candidate.required_execution_attempt,1);assert.equal(candidate.rerun_authorized,false);assert.equal(candidate.duplicate_execution_authorized,false);assert.equal(candidate.authority_reuse_authorized,false);assert.equal(candidate.formal_comparator_executed,false);assert.equal(candidate.formal_comparator_evidence_created,false);
 assert.equal(candidate.execution_workflow.blob_sha,'b11d60820f35ee39ac2df2a4372cbce7df8cf876');assert.equal(candidate.execution_control.blob_sha,'f6e1673681f734474340c1a1ffab79be60892a7a');assert.equal(candidate.execution_workflow.merge_sha,BASE);assert.equal(candidate.execution_workflow.qualification_workflow_run_id,30884238735);assert.equal(candidate.execution_workflow.qualification_artifact_id,8882436260);assert.equal(candidate.object_set_manifest_ref.blob_sha,'57d7817bc60074baee4ca3bd71c21e9bb5dab3b2');
 assert.equal(objects.object_count,12);for(const item of objects.objects){assert.equal(git('rev-parse',`${BASE}:${item.path}`),item.blob_sha,`BASE_OBJECT:${item.role}`);assert.equal(git('rev-parse',`HEAD:${item.path}`),item.blob_sha,`HEAD_OBJECT:${item.role}`)}
 assert.equal(predecessor.authority_effective,false);assert.equal(predecessor.comparator_execution_authorized,false);assert.equal(predecessor.execution_workflow,undefined,'PREDECESSOR_WORKFLOW_MUST_BE_ABSENT');assert.equal(supersession.predecessor.candidate_blob_sha,'235a1312af7951022a212159cd40e884cda8fbd9');assert.equal(supersession.defect.class,'INCOMPLETE_EXECUTION_CONTROL_PLANE_OBJECT_SET');assert.equal(supersession.replacement.candidate_blob_sha,'dffb2a6df42c4a0860f461761f1cf3e2d360c8ac');assert.equal(supersession.replacement.authority_effective,false);
 assert.equal(issuance.candidate.blob_sha,'dffb2a6df42c4a0860f461761f1cf3e2d360c8ac');assert.equal(issuance.object_set.blob_sha,'57d7817bc60074baee4ca3bd71c21e9bb5dab3b2');assert.equal(issuance.activation.authority_effective,false);assert.equal(issuance.activation.comparator_execution_authorized,false);assert.equal(boundary.changed_file_count,7);assert.deepEqual([...boundary.changed_files].sort(),CHANGED);assert.equal(boundary.workflow_dispatch_in_pr,false);assert.equal(boundary.replacement_authority_effective,false);assert.equal(boundary.formal_comparator_execution_performed,false);
 const audit=JSON.parse(fs.readFileSync(path.resolve(AUDIT),'utf8'));assert.equal(audit.status,'PASS');assert.equal(audit.exact_subject_sha,SUBJECT);
 assert.deepEqual([audit.run_a.workflow_run_id,audit.run_a.workflow_run_attempt,audit.run_a.event,audit.run_a.conclusion,audit.run_a.artifact_id,audit.run_a.artifact_digest],[30845476698,1,'workflow_dispatch','success',8868535301,'sha256:4d59d3aa0373bee0c9eb33ab78dd427eb324d4d259e0786aa9c4dea9effdaf2f']);
 assert.deepEqual([audit.run_b.workflow_run_id,audit.run_b.workflow_run_attempt,audit.run_b.event,audit.run_b.conclusion,audit.run_b.artifact_id,audit.run_b.artifact_digest],[30877450717,1,'workflow_dispatch','success',8880057024,'sha256:33e8b0333e1cd22bcd3002540ef5c12b72a8c545e58eb8ca185bf49edc6ae9cc']);
 assert.deepEqual([audit.implementation.workflow_run_id,audit.implementation.workflow_run_attempt,audit.implementation.event,audit.implementation.conclusion,audit.implementation.head_sha,audit.implementation.artifact_id,audit.implementation.artifact_digest],[30881117123,1,'pull_request','success','7a38276fcc1e4beb455db51b6d31d5c022bac37c',8881320548,'sha256:1593ef3f5f7b7a1217f26fb3126899d31ff0cee1416306b43e48897b0480639a']);
 assert.deepEqual([audit.execution_workflow.workflow_run_id,audit.execution_workflow.workflow_run_attempt,audit.execution_workflow.event,audit.execution_workflow.conclusion,audit.execution_workflow.head_sha,audit.execution_workflow.artifact_id,audit.execution_workflow.artifact_digest],[30884238735,1,'pull_request','success','bae50ddb9c6dde81289020d499999bc9d27515d3',8882436260,'sha256:83183392b756e97d7aea6df82b3e9dd4aceaf20341e14f6ead3184d9f9126555']);
 const jobMap=Object.fromEntries(audit.execution_workflow.jobs.map(x=>[x.name,x.conclusion]));assert.equal(jobMap['static-qualification'],'success');assert.equal(jobMap['execute-formal-comparator-once'],'skipped');
 const mod=require(path.join(ROOT,WRAPPER)),a=JSON.parse(fs.readFileSync(path.join(A_DIR,candidate.inputs.run_a.bundle_file),'utf8')),b=JSON.parse(fs.readFileSync(path.join(B_DIR,candidate.inputs.run_b.bundle_file),'utf8'));mod.assertFormalBundleV1(a,'RUN_A');mod.assertFormalBundleV1(b,'RUN_B');assert.notEqual(a.spec.operational_run_instance_id,b.spec.operational_run_instance_id);assert.notEqual(a.fresh_database.database_name,b.fresh_database.database_name);
 const da=mod.digestV1(mod.semanticProjectionV1(a)),db=mod.digestV1(mod.semanticProjectionV1(b)),diff=mod.semanticDifferencesV1(mod.semanticProjectionV1(a),mod.semanticProjectionV1(b));assert.equal(da,'sha256:32c93d4f5ecd1fc50ff94418407767b48b057d77c81bf93dfe3fccf58f0df2f8');assert.equal(db,da);assert.equal(diff.difference_count,0);
 const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'mcft-comparator-replacement-001-')),out=path.join(tmp,'formal.json');
 const wrapperRun=spawnSync(process.execPath,[path.join(ROOT,WRAPPER)],{encoding:'utf8',env:{...process.env,MCFT_CAP08_FORMAL_RUN_A_BUNDLE:path.join(A_DIR,candidate.inputs.run_a.bundle_file),MCFT_CAP08_FORMAL_RUN_B_BUNDLE:path.join(B_DIR,candidate.inputs.run_b.bundle_file),MCFT_CAP08_FORMAL_COMPARATOR_AUTHORITY:path.join(ROOT,CANDIDATE),MCFT_CAP08_FORMAL_COMPARATOR_INPUT_AUDIT:path.resolve(AUDIT),MCFT_CAP08_FORMAL_COMPARATOR_OUTPUT:out}});assert.notEqual(wrapperRun.status,0,'CANDIDATE_MUST_NOT_EXECUTE_WRAPPER');assert.equal(fs.existsSync(out),false,'NO_FORMAL_OUTPUT');
 const gateRun=spawnSync(process.execPath,[path.join(ROOT,CONTROL),'gate'],{encoding:'utf8',env:{...process.env,GITHUB_EVENT_NAME:'workflow_dispatch',GITHUB_RUN_ATTEMPT:'1',MCFT_EXECUTION_AUTHORITY_PATH:path.join(ROOT,CANDIDATE),MCFT_EXACT_SUBJECT_SHA:SUBJECT,MCFT_COMPARATOR_EXECUTION_ID:candidate.comparator_execution_id}});assert.notEqual(gateRun.status,0,'CANDIDATE_MUST_NOT_PASS_EXECUTION_GATE');
 const result={schema_version:'geox_mcft_cap08_s6_formal_comparator_replacement_001_authority_candidate_result_v1',status:'PASS',evidence_class:'NON_EFFECTIVE_REPLACEMENT_AUTHORITY_CANDIDATE_EVIDENCE',base_main_sha:BASE,exact_head_sha:git('rev-parse','HEAD'),exact_subject_sha:SUBJECT,authority_id:candidate.authority_id,object_count:12,semantic_digest_a:da,semantic_digest_b:db,difference_count:0,predecessor_superseded:true,authority_effective:false,comparator_execution_authorized:false,formal_comparator_executed:false,next_legal_action:'ESTABLISH_REPLACEMENT_001_FORMAL_CROSS_RUN_COMPARATOR_AUTHORITY_EFFECTIVENESS'};save(result);console.log(JSON.stringify(result,null,2));
}catch(e){save({schema_version:'geox_mcft_cap08_s6_formal_comparator_replacement_001_authority_candidate_result_v1',status:'FAIL',error:e instanceof Error?e.message:String(e)});console.error(e);process.exitCode=1}
