#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),c=require('node:child_process'),f=require('node:fs'),o=require('node:os'),p=require('node:path');
const R=p.resolve(__dirname,'../..'),O=p.join(R,'acceptance-output/MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION_RESULT.json');
const A='docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json',S='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S2-DELIVERY-STATUS-V1.json',G='docs/digital_twin/mcft/cap_08/GEOX-MCFT-CAP-08-S2-PRE-CANDIDATE-ENTRY-GATES-V1.json';
const Q='scripts/governance_acceptance/',V=Q+'MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1.cjs',H=Q+'MCFT_SYNTHETIC_MERGE_ATTESTATION_HARNESS_V1.cjs',L=Q+'MCFT_ATTESTATION_RETENTION_LOCAL_BACKEND_V1.cjs',P=Q+'mcft_attestation_retention_store_v1.cjs',C='docs/digital_twin/mcft/cap_07/GEOX-MCFT-CAP-07-ATTESTATION-RETENTION-STORE-CONTRACT-V1.json';
const W=[['.github/workflows/mcft-cap-07-s0-authorization.yml','mcft-cap-07-s0-authorization',0],['.github/workflows/mcft-cap-07-s4-api.yml','mcft-cap-07-s4-api',1],['.github/workflows/mcft-cap-07-s6-closure.yml','mcft-cap-07-s6-closure',1],['.github/workflows/mcft-cap-08-authority-reconciliation.yml','mcft-cap-08-authority-reconciliation',1],['.github/workflows/mcft-cap-08-s1-base-runtime.yml','mcft-cap-08-s1-base-runtime',1]];
const F=['.github/workflows/mcft-cap-08-s2-pre-candidate-foundation.yml',...W.map(x=>x[0]),S,G,Q+'ACCEPTANCE_MCFT_CAP_08_S2_PRE_CANDIDATE_FOUNDATION.cjs',V,H,L].sort();
const g=(r,x,z={})=>c.execFileSync('git',x,{cwd:r,encoding:'utf8',...z}).trim(),j=x=>JSON.parse(f.readFileSync(p.join(R,x),'utf8')),t=x=>f.readFileSync(p.join(R,x),'utf8');
function out(x){f.mkdirSync(p.dirname(O),{recursive:true});f.writeFileSync(O,JSON.stringify(x,null,2)+'\n')}
function cp(src,dst,mode=0o755){const q=p.join(dst,src);f.mkdirSync(p.dirname(q),{recursive:true});f.copyFileSync(p.join(R,src),q);f.chmodSync(q,mode)}
function contracts(){const r=j(A),s=j(S),x=j(G),cap=r.capabilities.find(y=>y.capability_line==='MCFT-CAP-08'),rule=cap.candidate_transition_fields.find(y=>y.status_file===S&&y.field_path==='s2_candidate_implemented');a.deepEqual(rule.allowed_candidate_values,[true]);
 for(const y of [s.s2_candidate_implemented,s.implementation_authorized,s.formal_candidate_creation_authorized,x.formal_candidate_creation_authorized,x.s2_candidate_transition_authorized])a.equal(y,false);
 for(const y of [s.pre_candidate_foundation_merge_authorized_by_contract,s.independent_review_deferred,s.independent_review_required_before_formal_s2_candidate,x.entry_gate_policy.independent_review_deferred,x.entry_gate_policy.independent_review_required_before_formal_s2_candidate])a.equal(y,true);
 for(const y of [s.independent_review_satisfied,s.independent_review_required_for_foundation_merge,x.entry_gate_policy.independent_review_satisfied,x.entry_gate_policy.independent_review_required_for_foundation_merge])a.equal(y,false);
 const m=x.completion_authority_contract.negative_database_matrix;a.equal(m.length,14);const z=Object.fromEntries(m.map(y=>[y.case_id,y]));a.deepEqual([z.N8.mutation,z.N8.expected_error],['PHASE_CONTRACT_DIGEST_MISMATCH_ONLY','CAP08_COMPLETION_CONTRACT_DIGEST_MISMATCH']);a.deepEqual([z.N9.mutation,z.N9.expected_error],['PHASE_SOURCE_DIGEST_MISMATCH_ONLY','CAP08_COMPLETION_SOURCE_DIGEST_MISMATCH']);a.deepEqual([z.N10.mutation,z.N10.expected_error],['PHASE_CONTRACT_AND_SOURCE_DIGEST_MISMATCH','CAP08_COMPLETION_CONTRACT_DIGEST_MISMATCH']);a.deepEqual(x.completion_authority_contract.digest_error_precedence,['CAP08_COMPLETION_CONTRACT_DIGEST_MISMATCH','CAP08_COMPLETION_SOURCE_DIGEST_MISMATCH']);a.equal(x.completion_authority_contract.implementation_state,'NOT_IMPLEMENTED');a.equal(x.completion_authority_contract.database_acceptance_state,'NOT_EXECUTED');a.equal(x.delivery_profile.pre_candidate_harness.remote_s3_backend_exercised,false);a.equal(x.delivery_profile.pre_candidate_harness.retention_command,`node ${L}`);return{negative_case_count:14}}
function boundary(){const b=String(process.env.MCFT_BASE_SHA||'');a.match(b,/^[0-9a-f]{40}$/);a.equal(g(R,['merge-base',b,'HEAD']),b);const q=g(R,['diff','--name-only',`${b}...HEAD`]).split(/\r?\n/).filter(Boolean).sort();a.deepEqual(q,F);return{base_sha:b,changed_files:q}}
function workflows(){for(const[x,n,svc]of W){const s=t(x);a.doesNotMatch(s,/\n\s*workflow_dispatch\s*:/);a.match(s,/resolve-applicability:/);a.match(s,/not-applicable:/);a.ok(s.includes(`MCFT_EXPECTED_FOCUSED_WORKFLOW: ${n}`));a.match(s,/if: needs\.resolve-applicability\.outputs\.disposition == 'APPLICABLE'/);if(svc)a.ok(s.indexOf('services:')>s.indexOf('resolve-applicability:'))}return{remediated_workflows:W.map(x=>x[1])}}
function resolver(){const q=JSON.parse(c.execFileSync(process.execPath,[p.join(R,V),'--self-test'],{cwd:R,encoding:'utf8'}));a.equal(q.status,'PASS');a.equal(q.scenario_count,9);return q}
function fixture(root){for(const x of[H,L,P,C])cp(x,root,x.endsWith('.json')?0o644:0o755);f.mkdirSync(p.join(root,'scripts/fixture'),{recursive:true});f.mkdirSync(p.join(root,'config'),{recursive:true});
 f.writeFileSync(p.join(root,'scripts/fixture/candidate.cjs'),`const a=require('node:assert/strict'),c=require('node:child_process');a.equal(process.env.MCFT_ATTESTATION_CONTEXT,'CANDIDATE');a.equal(c.execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),process.env.MCFT_CANDIDATE_SHA);console.log('PASS')\n`);
 f.writeFileSync(p.join(root,'scripts/fixture/merge.cjs'),`const a=require('node:assert/strict'),c=require('node:child_process');const g=(...x)=>c.execFileSync('git',x,{encoding:'utf8'}).trim();a.equal(process.env.MCFT_ATTESTATION_CONTEXT,'MERGE');a.equal(g('rev-parse','HEAD'),process.env.MCFT_SYNTHETIC_MERGE_SHA);a.equal(g('rev-parse','HEAD^{tree}'),g('rev-parse',process.env.MCFT_CANDIDATE_SHA+'^{tree}'));console.log('PASS')\n`);
 f.writeFileSync(p.join(root,'scripts/fixture/finalizer.cjs'),`const c=require('node:crypto'),f=require('node:fs');function k(v){if(Array.isArray(v))return '['+v.map(k).join(',')+']';if(v&&typeof v==='object')return '{'+Object.keys(v).sort().map(x=>JSON.stringify(x)+':'+k(v[x])).join(',')+'}';return JSON.stringify(v)}const x={status:'PASS',capability_line_id:'MCFT-CAP-08',slice_id:'MCFT-CAP-08.S2',subject_commit:process.env.MCFT_SUBJECT_SHA};x.semantic_artifact_digest='sha256:'+c.createHash('sha256').update(Buffer.from(k(x))).digest('hex');f.mkdirSync('acceptance-output',{recursive:true});f.writeFileSync('acceptance-output/canonical.json',JSON.stringify(x,null,2)+'\\n')\n`);
 const prof={schema_version:'geox_mcft_synthetic_merge_attestation_profile_v1',profile_id:'S2-FOUNDATION-SELFTEST',require_single_candidate_commit:true,commands:{candidate_boundary:['node','scripts/fixture/candidate.cjs'],merge_attestation:['node','scripts/fixture/merge.cjs'],finalizer:['node','scripts/fixture/finalizer.cjs'],archive:['bash','-lc',"rm -rf acceptance-output/archive-input acceptance-output/a.tar acceptance-output/a.tar.gz; mkdir -p acceptance-output/archive-input; cp acceptance-output/canonical.json acceptance-output/archive-input/canonical-artifact.json; tar --sort=name --mtime='UTC 1970-01-01' --owner=0 --group=0 --numeric-owner -cf acceptance-output/a.tar -C acceptance-output/archive-input canonical-artifact.json; gzip -n -f acceptance-output/a.tar"],retention:['node',L]},artifact:{canonical_path:'acceptance-output/canonical.json',archive_path:'acceptance-output/a.tar.gz',retention_locator_path:'acceptance-output/locator.json',required_fields:['subject_commit','semantic_artifact_digest']},retention:{level:'R1',days:180,bucket:'mcft-local',region:'us-east-1',repository_owner:'mcft',repository_name:'GEOX',artifact_name:'s2-foundation',workflow_run_id:'1',job_id:'foundation'}};f.writeFileSync(p.join(root,'config/profile.json'),JSON.stringify(prof,null,2)+'\n')}
function harness(){const r=f.mkdtempSync(p.join(o.tmpdir(),'s2-foundation-'));try{g(r,['init','-b','main']);g(r,['config','user.name','MCFT']);g(r,['config','user.email','mcft@example.invalid']);fixture(r);f.writeFileSync(p.join(r,'base.txt'),'base\n');g(r,['add','.']);g(r,['commit','-m','base']);const b=g(r,['rev-parse','HEAD']);g(r,['checkout','-b','candidate']);f.writeFileSync(p.join(r,'candidate.txt'),'candidate\n');g(r,['add','.']);g(r,['commit','-m','candidate']);const h=g(r,['rev-parse','HEAD']);c.execFileSync(process.execPath,[p.join(r,H),'--profile','config/profile.json','--output','acceptance-output/harness.json'],{cwd:r,env:{...process.env,MCFT_BASE_SHA:b,MCFT_CANDIDATE_SHA:h},stdio:'pipe'});const q=JSON.parse(f.readFileSync(p.join(r,'acceptance-output/harness.json')));a.equal(q.status,'PASS');a.equal(q.candidate_to_merge_tree_delta,0);a.equal(q.base_to_merge_commit_count,2);a.equal(q.retention_readback.readback_verified,true);a.equal(q.retention_readback.locked_version_delete_denied,true);a.equal(q.remote_object_store_exercised,false);return{status:'PASS',archive_digest:q.deterministic_archive_digest,retention_scope:q.retention_backend_scope}}finally{f.rmSync(r,{recursive:true,force:true})}}
function history(){const b='f182dd58f48fe4a6bed9957bf93adf7628b3a72a',h='e51d9e0aaf15b4da9f92fce06c23e33ed09586d5',m='f39b7df37571156f23cfb9153bad024fdb723261';a.deepEqual(g(R,['rev-list','--parents','-n','1',m]).split(/\s+/),[m,b,h]);a.equal(g(R,['rev-parse',`${h}^{tree}`]),g(R,['rev-parse',`${m}^{tree}`]));return{base:b,candidate:h,merge:m,tree_delta:0}}
try{const x={schema_version:'geox_mcft_cap08_s2_pre_candidate_foundation_result_v2',status:'PASS',classification:'PRE_CANDIDATE_FOUNDATION_ONLY',...boundary(),contracts:contracts(),workflows:workflows(),resolver:resolver(),synthetic_merge_harness:harness(),historical_s1:history(),g1:'PASS',g2:'PASS',g3_contract:'FROZEN',g3_implementation:'NOT_IMPLEMENTED',g3_database_acceptance:'NOT_EXECUTED',formal_s2_candidate:false,s2_effective:false,s3_authorized:false,independent_review_satisfied:false,independent_review_deferred:true};out(x);console.log(JSON.stringify(x))}catch(e){const x={schema_version:'geox_mcft_cap08_s2_pre_candidate_foundation_result_v2',status:'FAIL',error:e.message};out(x);console.error(e);process.exitCode=1}
