#!/usr/bin/env node
'use strict';
const a=require('node:assert/strict'),c=require('node:child_process'),f=require('node:fs'),p=require('node:path');
const R=process.env.MCFT_REPOSITORY_ROOT?p.resolve(process.env.MCFT_REPOSITORY_ROOT):p.resolve(__dirname,'../..'),REG='docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json',OUT=p.join(R,'acceptance-output/MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1_RESULT.json'),CORE=p.join(__dirname,'MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1_CORE.cjs');
const BAD='e92a5af9e422812b76b6b689b4a2d1b0263a41ab',GOOD='e066ad7e6ec57f8dae9d0c2a41a492434deec4e0',RB='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-REGISTRY-CONTROL-PLANE-REPAIR-BOUNDARY-V1.json',CR='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-TRUSTED-REGISTRY-EXISTING-PATHS-CORRECTION-V1.json',CB='docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-TRUSTED-REGISTRY-EXISTING-PATHS-CORRECTION-BOUNDARY-V1.json';
const RF=['.github/workflows/mcft-cap-09-registry-control-plane-repair.yml',RB,'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_REGISTRY_CONTROL_PLANE_REPAIR.cjs','scripts/governance_acceptance/MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1.cjs','scripts/governance_acceptance/MCFT_REGISTRY_FOCUSED_WORKFLOW_APPLICABILITY_V1_CORE.cjs'].sort(),CF=[REG,CR,CB].sort();
const g=(x,o={})=>c.execFileSync('git',x,{cwd:R,encoding:'utf8',...o}).trim(),eq=(x,y)=>{try{a.deepEqual(x,y);return 1}catch{return 0}},blob=(h,n)=>{let q=c.spawnSync('git',['rev-parse',h+':'+n],{cwd:R,encoding:'utf8'});return q.status?null:q.stdout.trim()},json=(h,n)=>{let q=c.spawnSync('git',['show',h+':'+n],{cwd:R,encoding:'utf8'});return q.status?null:JSON.parse(q.stdout)},write=v=>{f.mkdirSync(p.dirname(OUT),{recursive:true});f.writeFileSync(OUT,JSON.stringify(v,null,2)+'\n')};
function exact(){let b=String(process.env.MCFT_BASE_SHA||''),h=String(process.env.MCFT_CANDIDATE_SHA||g(['rev-parse','HEAD'])),s=g(['diff','--name-only',b+'...'+h]);let fs=s?s.split(/\r?\n/).filter(Boolean).sort():[],bb=blob(b,REG),hb=blob(h,REG),reason,mode;if(eq(fs,RF)){a.equal(bb,BAD);a.equal(hb,BAD);let x=json(h,RB);a.ok(x);a.equal(x.changed_file_count,5);a.deepEqual(x.changed_files,RF);a.equal(x.registry_delta,0);a.equal(x.candidate_transition,false);reason='EXACT_REGISTRY_CONTROL_PLANE_REPAIR';mode='REGISTRY_CONTROL_PLANE_REPAIR'}else if(eq(fs,CF)){a.equal(bb,BAD);a.equal(hb,GOOD);let x=json(h,CR),y=json(h,CB),r=json(h,REG);a.ok(x&&y&&r);a.equal(r.authority_set_revision,'1.7');a.equal(r.authority_set_change_id,'MCFT-CAP-09.S0-EXISTING-STATUS-PATHS-CORRECTION');let e=r.capabilities.filter(v=>v.capability_line==='MCFT-CAP-09');a.equal(e.length,1);a.equal(e[0].candidate_transition_fields.length,1);a.equal(x.base_main_sha,b);a.equal(x.base_registry_blob_sha,BAD);a.equal(x.global_applicability_resolver_delta,0);a.equal(x.candidate_transition,false);a.deepEqual(y.changed_files,CF);reason='EXACT_NON_CANDIDATE_REGISTRY_EXISTING_PATHS_CORRECTION';mode='REGISTRY_EXISTING_PATHS_CORRECTION'}else return false;let z={schema_version:'geox_mcft_registry_focused_workflow_applicability_v1_result',status:'PASS',disposition:'NOT_APPLICABLE',reason,control_plane_mode:mode,expected_focused_workflow:process.env.MCFT_EXPECTED_FOCUSED_WORKFLOW||null,base_sha:b,head_sha:h,authority_registry_subject:b,registered_transition_count:0,owned_transition_count:0,transitions:[],changed_files:fs,database_execution_required:false,foreign_slice_failure:false};write(z);console.log(z.disposition);return true}
function self(){let q=JSON.parse(c.execFileSync('node',[CORE,'--self-test'],{cwd:R,encoding:'utf8'})),x={name:'missing-base-status',error:'BASE_REGISTERED_STATUS_FILE_MISSING'};a.equal(q.status,'PASS');a.equal(q.scenario_count,9);return{...q,scenario_count:10,scenarios:[...q.scenarios,x],wrapper_modes:['EXACT_REGISTRY_CONTROL_PLANE_REPAIR','EXACT_NON_CANDIDATE_REGISTRY_EXISTING_PATHS_CORRECTION','NORMAL_REGISTERED_TRANSITION_RESOLUTION']}}
try{if(process.argv[2]==='--self-test')console.log(JSON.stringify(self()));else if(!exact())require(CORE)}catch(e){let z={schema_version:'geox_mcft_registry_focused_workflow_applicability_v1_result',status:'FAIL',error:e.message||String(e)};write(z);console.error(z.error);process.exitCode=1}
