#!/usr/bin/env node
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {execFileSync}=require('node:child_process');
const ROOT=process.cwd();
const W='.github/workflows/mcft-cap-09-trusted-registry-bootstrap.yml';
const V='scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_TRUSTED_REGISTRY_BOOTSTRAP.cjs';
const BW='.github/workflows/mcft-cap-09-s1-trusted-lifecycle-builder.yml';
const BS='scripts/governance_acceptance/mcft_cap09_s1_trusted_lifecycle_builder.cjs';
const BASE='e444cd4a8a88b34356852abceccaf7babc7be901';
const git=(...a)=>execFileSync('git',a,{cwd:ROOT,encoding:'utf8'}).trim();
const read=f=>fs.readFileSync(path.join(ROOT,f),'utf8');
const write=(f,s)=>fs.writeFileSync(path.join(ROOT,f),s);
if(git('rev-parse',`${BASE}:${W}`)!=='b3d456f2e4b7b7f38d30bc75a9f8ea183b0fb58c')throw Error('WORKFLOW_BASE_BLOB');
if(git('rev-parse',`${BASE}:${V}`)!=='a46f30e6695444f85628a1720f0765a3e1c99329')throw Error('VALIDATOR_BASE_BLOB');
let w=read(W);
const triggerAnchor="      - 'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_TRUSTED_REGISTRY_BOOTSTRAP.cjs'\n";
const triggerInsert="      - '.github/workflows/mcft-cap-09-s1-registry-registration.yml'\n      - 'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S1-DELIVERY-STATUS-V1.json'\n      - 'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S1-REGISTRY-REGISTRATION-V1.json'\n      - 'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S1-REGISTRY-REGISTRATION-BOUNDARY-V1.json'\n      - 'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S1_REGISTRY_REGISTRATION.cjs'\n";
if(!w.includes(triggerAnchor)||w.includes('GEOX-MCFT-CAP-09-S1-REGISTRY-REGISTRATION-V1.json'))throw Error('WORKFLOW_TRIGGER_ANCHOR');
w=w.replace(triggerAnchor,triggerAnchor+triggerInsert);
const blockAnchor="          # Delivery Status is a non-authority tracking projection; Current Authority.status is the sole Registry transition.\n";
const s1Block="          s1_registration_files=\"$(printf '%s\\n' \\\n            '.github/workflows/mcft-cap-09-s1-registry-registration.yml' \\\n            'docs/digital_twin/mcft/MCFT-CANDIDATE-AUTHORITY-REGISTRY-V1.json' \\\n            'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S1-DELIVERY-STATUS-V1.json' \\\n            'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S1-REGISTRY-REGISTRATION-V1.json' \\\n            'docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-S1-REGISTRY-REGISTRATION-BOUNDARY-V1.json' \\\n            'scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S1_REGISTRY_REGISTRATION.cjs' | sort)\"\n";
if(!w.includes(blockAnchor))throw Error('WORKFLOW_BLOCK_ANCHOR');
w=w.replace(blockAnchor,s1Block+blockAnchor);
const ifAnchor="          elif [[ \"$files\" == \"$candidate_files\" ]]; then\n            mode='candidate-signal'\n";
const ifReplace="          elif [[ \"$files\" == \"$s1_registration_files\" ]]; then\n            mode='s1-registry-registration'\n"+ifAnchor;
if(!w.includes(ifAnchor))throw Error('WORKFLOW_IF_ANCHOR');w=w.replace(ifAnchor,ifReplace);
const caseAnchor="            candidate-signal)\n              node scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_TRUSTED_REGISTRY_BOOTSTRAP.cjs --candidate-signal\n              ;;\n";
const caseReplace="            s1-registry-registration)\n              node scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_S1_REGISTRY_REGISTRATION.cjs\n              ;;\n"+caseAnchor;
if(!w.includes(caseAnchor))throw Error('WORKFLOW_CASE_ANCHOR');w=w.replace(caseAnchor,caseReplace);
write(W,w);
let v=read(V);
v=v.replace("const REPAIR_BASE='b165c1d36732a332f70fca375893188142f5992e';","const REPAIR_BASE='e444cd4a8a88b34356852abceccaf7babc7be901';");
const tokensOld='["mode=\'workflow-repair\'","mode=\'registry-existing-paths-correction\'","mode=\'candidate-signal\'","mode=\'bootstrap\'","mode=\'unsupported\'","Delivery Status is a non-authority tracking projection","if: steps.lifecycle.outputs.mode == \'bootstrap\'","--registry-existing-paths-correction","--candidate-signal"]';
const tokensNew='["mode=\'workflow-repair\'","mode=\'registry-existing-paths-correction\'","mode=\'s1-registry-registration\'","mode=\'candidate-signal\'","mode=\'bootstrap\'","mode=\'unsupported\'","Delivery Status is a non-authority tracking projection","GEOX-MCFT-CAP-09-S1-REGISTRY-REGISTRATION-V1.json","ACCEPTANCE_MCFT_CAP_09_S1_REGISTRY_REGISTRATION.cjs","if: steps.lifecycle.outputs.mode == \'bootstrap\'","--registry-existing-paths-correction","--candidate-signal"]';
if(!v.includes(tokensOld))throw Error('VALIDATOR_TOKEN_ANCHOR');v=v.replace(tokensOld,tokensNew);
v=v.replace("change_class:'MCFT_CAP_09_TRUSTED_REGISTRY_TRACKING_PROJECTION_COMPATIBILITY_REPAIR'","change_class:'MCFT_CAP_09_TRUSTED_REGISTRY_S1_REGISTRATION_LIFECYCLE_REPAIR'");
v=v.replace("first_legal_next_action:'MERGE_REPAIR_THEN_REBUILD_MCFT_CAP_09_S0_AUTHORIZATION_CANDIDATE'","first_legal_next_action:'MERGE_REPAIR_THEN_REBUILD_MCFT_CAP_09_S1_REGISTRY_REGISTRATION'");
write(V,v);
fs.rmSync(path.join(ROOT,BW));fs.rmSync(path.join(ROOT,BS));
console.log(JSON.stringify({status:'PASS',files:[W,V]},null,2));
