// scripts/governance_acceptance/P12_01_PERSISTENCE_EXECUTION_AUTHORITY_CONTRACT_ACCEPTANCE.cjs
'use strict';
require('./P12_ACCEPTANCE_HELPERS.cjs').run('P12_01_PERSISTENCE_EXECUTION_AUTHORITY_CONTRACT_ACCEPTANCE');
