// scripts/governance_acceptance/P14_07_CALIBRATION_REVIEW_PROMOTION_GATE_ACCEPTANCE.cjs
'use strict';
require('./P14_ACCEPTANCE_HELPERS.cjs').run('P14_07_CALIBRATION_REVIEW_PROMOTION_GATE_ACCEPTANCE');
