// scripts/governance_acceptance/P14_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const{spawnSync}=require('node:child_process');
const ROOT=process.cwd();const RUNNER='scripts/twin_kernel/P14_07_CALIBRATION_REVIEW_PROMOTION_GATE_V0.cjs';
const PRIOR=['00_POST_P13_BASELINE_FREEZE_INHERITANCE_AUDIT','01_CALIBRATION_REVIEW_GATE_CONTRACT_ACCEPTANCE','02_CALIBRATION_REVIEW_PACKET_SCHEMA_ACCEPTANCE','03_CALIBRATION_REVIEW_DECISION_SCHEMA_ACCEPTANCE','04_MODEL_VERSION_PROPOSAL_SCHEMA_ACCEPTANCE','05_MODEL_VERSION_PROMOTION_GATE_CONTRACT_ACCEPTANCE','06_GOVERNED_MODEL_VERSION_PROMOTION_RECORD_SCHEMA_ACCEPTANCE','07_CALIBRATION_REVIEW_PROMOTION_GATE_ACCEPTANCE','08_REJECTED_CALIBRATION_ACCEPTANCE','09_NEGATIVE_AUTHORIZATION_CANDIDATE_BOUNDARY_ACCEPTANCE','10_CALIBRATION_REVIEW_IDEMPOTENCY_ACCEPTANCE','11_CHANGED_REVIEW_CONFLICT_ACCEPTANCE'].map(x=>'scripts/governance_acceptance/P14_'+x+'.cjs');
function abs(f){return path.resolve(ROOT,f)}function read(f){return fs.readFileSync(abs(f),'utf8')}function json(f){return JSON.parse(read(f))}function exists(f){return fs.existsSync(abs(f))}function tmp(n){return path.join(fs.mkdtempSync(path.join(os.tmpdir(),'geox-p14-')),n)}
function node(args){const r=spawnSync(process.execPath,args,{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});if(r.status!==0)throw new Error(args.join(' ')+'_FAILED:'+r.stderr);return JSON.parse(r.stdout)}
function sh(args){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function diff(){const r=sh(['git','diff','--name-only','p13_continuous_twin_runtime_loop_manual_registry_runner_v0...HEAD']);return r.status===0?r.stdout.split(/\r?\n/).filter(Boolean):[]}
function A(){const list=[];return{list,ok(n,v,d={}){list.push({name:n,passed:v===true,details:d});if(v!==true){let e=new Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function surf(a){const allowed=f=>f.startsWith('docs/tasks/P14-')||f.startsWith('docs/twin_kernel/fixtures/p14_calibration/')||f.startsWith('scripts/governance_acceptance/P14_')||['scripts/governance_acceptance/P14_ACCEPTANCE_HELPERS.cjs',RUNNER,'README_MIGRATION.md','docs/twin_kernel/CALIBRATION_REVIEW_GATE_CONTRACT_V0.json','docs/twin_kernel/CALIBRATION_REVIEW_PACKET_SCHEMA_V0.json','docs/twin_kernel/CALIBRATION_REVIEW_DECISION_SCHEMA_V0.json','docs/twin_kernel/MODEL_VERSION_PROPOSAL_SCHEMA_V0.json','docs/twin_kernel/MODEL_VERSION_PROMOTION_GATE_CONTRACT_V0.json','docs/twin_kernel/GOVERNED_MODEL_VERSION_PROMOTION_RECORD_SCHEMA_V0.json','docs/twin_kernel/P14_CALIBRATION_REVIEW_MODEL_VERSION_PROMOTION_COMPLETION_REVIEW_V0.json'].includes(f);const bad=diff().filter(f=>!allowed(f));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function c00(a){a.ok('p13_tag_exists',sh(['git','rev-parse','p13_continuous_twin_runtime_loop_manual_registry_runner_v0']).status===0);a.ok('p13_readme',read('README_MIGRATION.md').includes('P13 Continuous Twin Runtime Loop / Manual Registry Runner v0 Freeze Closure'));a.ok('p13_acceptance_exists',exists('scripts/governance_acceptance/P13_07_MANUAL_TWIN_RUNTIME_LOOP_RUNNER_ACCEPTANCE.cjs')&&exists('scripts/governance_acceptance/P13_11_COMPLETION_REVIEW_ACCEPTANCE.cjs'));return{baseline_tag:'p13_continuous_twin_runtime_loop_manual_registry_runner_v0',baseline_commit:'61072729'}}
function c01(a){const c=json('docs/twin_kernel/CALIBRATION_REVIEW_GATE_CONTRACT_V0.json');a.ok('gate_contract',c.input_candidate_type==='field_learning_candidate_v1'&&c.human_review_required&&c.automatic_review_allowed===false&&c.accepted_decision_allowed&&c.rejected_decision_allowed&&c.automatic_model_update_allowed===false&&c.field_memory_write_allowed===false,{c});return c}
function c02(a){const s=json('docs/twin_kernel/CALIBRATION_REVIEW_PACKET_SCHEMA_V0.json');for(const f of ['calibration_candidate_id','candidate_target_object_type','source_runtime_case_id','source_runtime_run_id','forecast_error_ref','candidate_hash','model_version_set','proposed_adjustment_summary','evidence_refs','review_required'])a.ok('packet_'+f,s.required_fields.includes(f));a.ok('packet_review_required',s.review_required===true);return{review_required:true}}
function c03(a){const s=json('docs/twin_kernel/CALIBRATION_REVIEW_DECISION_SCHEMA_V0.json');a.ok('decision_schema',s.allowed_decisions.includes('accepted')&&s.allowed_decisions.includes('rejected')&&s.forbidden_decisions.includes('auto_accepted')&&s.forbidden_decisions.includes('auto_rejected')&&s.forbidden_decisions.includes('implicit_acceptance')&&s.required_fields.includes('review_actor')&&s.required_fields.includes('reviewer_ref')&&s.required_fields.includes('review_reason')&&s.review_idempotency_key_is_deterministic===true,{s});return{accepted_allowed:true,rejected_allowed:true,review_idempotency_key_deterministic:true}}
function c04(a){const s=json('docs/twin_kernel/MODEL_VERSION_PROPOSAL_SCHEMA_V0.json');a.ok('proposal_schema',s.required_fields.includes('source_calibration_review_decision_id')&&s.required_fields.includes('source_calibration_candidate_id')&&s.required_fields.includes('proposal_model_version_id')&&s.proposal_is_not_active_model&&s.runtime_model_registry_mutation_allowed===false&&s.production_model_activation_allowed===false&&s.runtime_model_update_count===0&&s.active_model_assignment_count===0&&s.model_registry_write_count===0,{s});return s}
function c05(a){const c=json('docs/twin_kernel/MODEL_VERSION_PROMOTION_GATE_CONTRACT_V0.json');a.ok('promotion_gate',c.promotion_authorization_required&&c.promotion_record_allowed&&c.automatic_promotion_allowed===false&&c.active_model_assignment_allowed===false&&c.runtime_registry_mutation_allowed===false&&c.production_activation_allowed===false,{c});return c}
function c06(a){const s=json('docs/twin_kernel/GOVERNED_MODEL_VERSION_PROMOTION_RECORD_SCHEMA_V0.json');a.ok('promotion_record_schema',s.required_fields.includes('promotion_record_id')&&s.required_fields.includes('source_model_version_proposal_id')&&s.required_fields.includes('source_calibration_review_decision_id')&&s.required_fields.includes('promotion_authorization_ref')&&s.required_fields.includes('promotion_decision')&&s.governed_model_version_promotion_record_emitted&&s.persisted_promotion_record_count===0&&s.active_model_assignment_created===false&&s.active_model_assignment_count===0&&s.runtime_model_registry_mutated===false&&s.model_registry_write_count===0&&s.production_model_activation_allowed===false,{s});return s}
function accepted(){return node([RUNNER,'--review','accepted','--promotion-authorized','--state-file',tmp('accepted.json')])}
function c07(a){const r=accepted();a.ok('accepted_path',r.calibration_candidate_count===1&&r.calibration_review_packet_created&&r.review_decision==='accepted'&&r.model_version_proposal_created&&r.promotion_gate_decision_created&&r.governed_model_version_promotion_record_emitted&&r.persisted_promotion_record_count===0&&r.active_model_assignment_created===false&&r.active_model_assignment_count===0&&r.runtime_model_registry_mutated===false&&r.model_registry_write_count===0&&r.production_model_activation_allowed===false&&r.runtime_model_update_count===0&&r.field_memory_write_count===0&&r.recommendation_created===false&&r.ao_act_task_created===false&&r.dashboard_authority===false&&r.state_file_must_be_os_temp&&r.repo_write_allowed===false&&r.db_write_allowed===false&&r.fixture_mutation_allowed===false,{r});return r}
function c08(a){const r=node([RUNNER,'--review','rejected','--state-file',tmp('rejected.json')]);a.ok('rejected_path',r.review_decision==='rejected'&&r.calibration_review_packet_created&&r.model_version_proposal_created===false&&r.promotion_gate_decision_created===false&&r.governed_model_version_promotion_record_emitted===false&&r.persisted_promotion_record_count===0&&r.active_model_assignment_created===false&&r.runtime_model_update_count===0,{r});return r}
function c09(a){const mr=node([RUNNER,'--missing-review','--state-file',tmp('mr.json')]);const ma=node([RUNNER,'--review','accepted','--missing-authorization','--state-file',tmp('ma.json')]);const wc=node([RUNNER,'--wrong-candidate-type','--state-file',tmp('wc.json')]);const ap=node([RUNNER,'--auto-promotion-request','--state-file',tmp('ap.json')]);a.ok('negative_boundary',mr.missing_review_blocked&&ma.missing_authorization_blocked&&wc.wrong_candidate_type_blocked&&ap.auto_promotion_blocked&&ma.model_version_proposal_created===false&&ma.governed_model_version_promotion_record_emitted===false&&ma.persisted_promotion_record_count===0&&ma.active_model_assignment_created===false&&ma.runtime_model_registry_mutated===false,{mr,ma,wc,ap});return{missing_review_blocked:true,missing_authorization_blocked:true,wrong_candidate_type_blocked:true,auto_promotion_blocked:true,model_version_proposal_created:false,governed_model_version_promotion_record_emitted:false,persisted_promotion_record_count:0,active_model_assignment_created:false,runtime_model_registry_mutated:false}}
function c10(a){const st=tmp('idem.json');const f=node([RUNNER,'--review','accepted','--promotion-authorized','--state-file',st]);const s=node([RUNNER,'--review','accepted','--promotion-authorized','--state-file',st]);a.ok('idempotent',f.first_review_created_count===1&&s.second_review_created_count===0&&s.same_review_idempotency_key_reused&&s.same_model_version_proposal_id_reused&&s.same_promotion_record_id_reused&&s.duplicate_promotion_record_created_count===0&&f.proposal_model_version_id===s.proposal_model_version_id&&f.promotion_record_id===s.promotion_record_id,{f,s});return{first_review_created_count:1,second_review_created_count:0,same_review_idempotency_key_reused:true,same_model_version_proposal_id_reused:true,same_promotion_record_id_reused:true,duplicate_promotion_record_created_count:0}}
function c11(a){const st=tmp('conflict.json');const f=node([RUNNER,'--review','accepted','--promotion-authorized','--state-file',st]);const c=node([RUNNER,'--changed-review-conflict','--state-file',st]);a.ok('changed_conflict',f.review_decision==='accepted'&&c.same_candidate_changed_review_conflict_requires_review&&c.changed_review_does_not_overwrite_existing_decision&&c.existing_review_decision_unchanged&&c.existing_review_decision==='accepted'&&c.duplicate_model_version_proposal_created===false&&c.duplicate_promotion_record_created===false&&c.active_model_assignment_created===false,{f,c});return{same_candidate_changed_review_conflict_requires_review:true,changed_review_does_not_overwrite_existing_decision:true,existing_review_decision_unchanged:true,duplicate_model_version_proposal_created:false,duplicate_promotion_record_created:false,active_model_assignment_created:false}}
function runScript(f){const r=spawnSync(process.execPath,[f],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let p=null;try{p=JSON.parse(r.stdout||r.stderr)}catch{}return{script:f,status:r.status,ok:r.status===0&&p&&p.ok===true&&p.failed_assertion_count===0,parsed:p}}
function c12(a){const prior=PRIOR.map(runScript);a.ok('all_prior_p14_acceptance_passed',prior.every(r=>r.ok),{prior});const s=json('docs/twin_kernel/P14_CALIBRATION_REVIEW_MODEL_VERSION_PROMOTION_COMPLETION_REVIEW_V0.json').completion_scope;a.ok('completion_scope',s.accepted_calibration_path_passed&&s.rejected_calibration_path_passed&&s.negative_authorization_boundary_passed&&s.calibration_review_idempotency_passed&&s.changed_review_conflict_passed&&s.governed_model_version_promotion_record_emitted&&s.persisted_promotion_record_count===0&&s.missing_review_blocked&&s.missing_authorization_blocked&&s.wrong_candidate_type_blocked&&s.auto_promotion_blocked&&s.same_candidate_changed_review_conflict_requires_review&&s.changed_review_does_not_overwrite_existing_decision&&s.existing_review_decision_unchanged&&s.promotion_is_not_production_model_activation&&s.active_model_assignment_created===false&&s.runtime_model_registry_mutated===false&&s.model_registry_write_count===0&&s.production_model_activation_allowed===false&&s.runtime_model_update_count===0&&s.field_memory_write_count===0&&s.recommendation_created===false&&s.ao_act_task_created===false&&s.dashboard_authority===false,{s});return{all_prior_p14_acceptance_passed:true,...s,readme_p14_snapshot_present:read('README_MIGRATION.md').includes('P14 Calibration Review / Model Version Promotion Gate v0 Freeze Closure')}}
function run(name){const a=A();const map={P14_00_POST_P13_BASELINE_FREEZE_INHERITANCE_AUDIT:c00,P14_01_CALIBRATION_REVIEW_GATE_CONTRACT_ACCEPTANCE:c01,P14_02_CALIBRATION_REVIEW_PACKET_SCHEMA_ACCEPTANCE:c02,P14_03_CALIBRATION_REVIEW_DECISION_SCHEMA_ACCEPTANCE:c03,P14_04_MODEL_VERSION_PROPOSAL_SCHEMA_ACCEPTANCE:c04,P14_05_MODEL_VERSION_PROMOTION_GATE_CONTRACT_ACCEPTANCE:c05,P14_06_GOVERNED_MODEL_VERSION_PROMOTION_RECORD_SCHEMA_ACCEPTANCE:c06,P14_07_CALIBRATION_REVIEW_PROMOTION_GATE_ACCEPTANCE:c07,P14_08_REJECTED_CALIBRATION_ACCEPTANCE:c08,P14_09_NEGATIVE_AUTHORIZATION_CANDIDATE_BOUNDARY_ACCEPTANCE:c09,P14_10_CALIBRATION_REVIEW_IDEMPOTENCY_ACCEPTANCE:c10,P14_11_CHANGED_REVIEW_CONFLICT_ACCEPTANCE:c11,P14_12_COMPLETION_REVIEW_ACCEPTANCE:c12};try{a.ok('known_acceptance_entrypoint',typeof map[name]==='function',{name});const res=map[name](a);const surface=surf(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...res,...surface,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}
module.exports={run};
