// scripts/governance_acceptance/P14_01_CALIBRATION_REVIEW_GATE_CONTRACT_ACCEPTANCE.cjs
'use strict';
require('./P14_ACCEPTANCE_HELPERS.cjs').run('P14_01_CALIBRATION_REVIEW_GATE_CONTRACT_ACCEPTANCE');
