// scripts/governance_acceptance/P14_02_CALIBRATION_REVIEW_PACKET_SCHEMA_ACCEPTANCE.cjs
'use strict';
require('./P14_ACCEPTANCE_HELPERS.cjs').run('P14_02_CALIBRATION_REVIEW_PACKET_SCHEMA_ACCEPTANCE');
