// scripts/governance_acceptance/P14_05_MODEL_VERSION_PROMOTION_GATE_CONTRACT_ACCEPTANCE.cjs
'use strict';
require('./P14_ACCEPTANCE_HELPERS.cjs').run('P14_05_MODEL_VERSION_PROMOTION_GATE_CONTRACT_ACCEPTANCE');
