// scripts/governance_acceptance/P14_06_GOVERNED_MODEL_VERSION_PROMOTION_RECORD_SCHEMA_ACCEPTANCE.cjs
'use strict';
require('./P14_ACCEPTANCE_HELPERS.cjs').run('P14_06_GOVERNED_MODEL_VERSION_PROMOTION_RECORD_SCHEMA_ACCEPTANCE');
