// scripts/governance_acceptance/P14_09_NEGATIVE_AUTHORIZATION_CANDIDATE_BOUNDARY_ACCEPTANCE.cjs
'use strict';
require('./P14_ACCEPTANCE_HELPERS.cjs').run('P14_09_NEGATIVE_AUTHORIZATION_CANDIDATE_BOUNDARY_ACCEPTANCE');
