// scripts/governance_acceptance/P15_04_TWIN_USE_ELIGIBILITY_POLICY_CONTRACT_ACCEPTANCE.cjs
'use strict';
require('./P15_ACCEPTANCE_HELPERS.cjs').run('P15_04_TWIN_USE_ELIGIBILITY_POLICY_CONTRACT_ACCEPTANCE');
