// scripts/governance_acceptance/P15_02_TWIN_CONFIDENCE_COMPONENT_SCHEMA_ACCEPTANCE.cjs
'use strict';
require('./P15_ACCEPTANCE_HELPERS.cjs').run('P15_02_TWIN_CONFIDENCE_COMPONENT_SCHEMA_ACCEPTANCE');
