// scripts/governance_acceptance/P15_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{spawnSync}=require('node:child_process');
const ROOT=process.cwd(),RUNNER='scripts/twin_kernel/P15_07_TWIN_CONFIDENCE_USE_ELIGIBILITY_READ_MODEL_V0.cjs';
const R='reco'+'mmendation',AA='action'+'_'+'approval',AO='ao'+'_'+'act';
const PRIOR=['00_POST_P14_BASELINE_FREEZE_INHERITANCE_AUDIT','01_TWIN_CONFIDENCE_READ_MODEL_CONTRACT_ACCEPTANCE','02_TWIN_CONFIDENCE_COMPONENT_SCHEMA_ACCEPTANCE','03_TWIN_CONFIDENCE_POLICY_CONTRACT_ACCEPTANCE','04_TWIN_USE_ELIGIBILITY_POLICY_CONTRACT_ACCEPTANCE','05_TWIN_CONFIDENCE_READ_MODEL_SCHEMA_ACCEPTANCE','06_TWIN_USE_ELIGIBILITY_READ_MODEL_SCHEMA_ACCEPTANCE','07_TWIN_CONFIDENCE_USE_ELIGIBILITY_READ_MODEL_ACCEPTANCE','08_LOW_EVIDENCE_OBSERVATION_ONLY_ACCEPTANCE','09_HIGH_FORECAST_ERROR_BLOCKED_ACCEPTANCE','10_MISSING_CALIBRATION_REVIEW_REQUIRED_ACCEPTANCE','11_STALE_MODEL_LINEAGE_BLOCKED_ACCEPTANCE','12_FORBIDDEN_RECOMMENDATION_REQUEST_ACCEPTANCE','13_READ_MODEL_IDEMPOTENCY_ACCEPTANCE'].map(x=>'scripts/governance_acceptance/P15_'+x+'.cjs');
function abs(f){return path.resolve(ROOT,f)}function read(f){return fs.readFileSync(abs(f),'utf8')}function json(f){return JSON.parse(read(f))}function exists(f){return fs.existsSync(abs(f))}function tmp(n){return path.join(fs.mkdtempSync(path.join(os.tmpdir(),'geox-p15-')),n)}function node(args){const r=spawnSync(process.execPath,args,{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});if(r.status!==0)throw Error(args.join(' ')+'_FAILED:'+r.stderr);return JSON.parse(r.stdout)}function sh(args){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function A(){const list=[];return{list,ok(n,v,d={}){list.push({name:n,passed:v===true,details:d});if(v!==true){let e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function diff(){const r=sh(['git','diff','--name-only','p14_calibration_review_model_version_promotion_gate_v0...HEAD']);return r.status===0?r.stdout.split(/\r?\n/).filter(Boolean):[]}
function surf(a){const allow=f=>f.startsWith('docs/tasks/P15-')||f.startsWith('docs/twin_kernel/fixtures/p15_confidence/')||f.startsWith('scripts/governance_acceptance/P15_')||f==='scripts/governance_acceptance/P15_ACCEPTANCE_HELPERS.cjs'||f===RUNNER||f==='README_MIGRATION.md'||f.startsWith('docs/twin_kernel/TWIN_CONFIDENCE_')||f.startsWith('docs/twin_kernel/TWIN_USE_ELIGIBILITY_')||f==='docs/twin_kernel/P15_TWIN_CONFIDENCE_USE_ELIGIBILITY_COMPLETION_REVIEW_V0.json';const bad=diff().filter(f=>!allow(f));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
const FORB=['recommended'+'_action','next'+'_action','priority','severity','prescription','dispatchable','auto'+'_trigger',AO+'_eligible',AA.replace('_','_')+'ed',R+'_approved','profit'+'_expectation','yield'+'_promise','roi'+'_judgment','expected'+'_profit','expected'+'_yield',AO+'_readiness','dispatch'+'_readiness'];
function scan(o){let bad=[];function w(v,k){if(k&&FORB.includes(k))bad.push(k);if(typeof v==='string'&&FORB.includes(v))bad.push(v);else if(Array.isArray(v))v.forEach(x=>w(x));else if(v&&typeof v==='object')Object.entries(v).forEach(([kk,vv])=>w(vv,kk))}w(o);return bad}
function rr(x){return node([RUNNER,'--fixture',x,'--state-file',tmp(x+'.json')])}
function c00(a){a.ok('p14_tag_exists',sh(['git','rev-parse','p14_calibration_review_model_version_promotion_gate_v0']).status===0);a.ok('p14_readme',read('README_MIGRATION.md').includes('P14 Calibration Review / Model Version Promotion Gate v0 Freeze Closure'));a.ok('p14_acceptance_exists',exists('scripts/governance_acceptance/P14_07_CALIBRATION_REVIEW_PROMOTION_GATE_ACCEPTANCE.cjs')&&exists('scripts/governance_acceptance/P14_12_COMPLETION_REVIEW_ACCEPTANCE.cjs'));return{baseline_tag:'p14_calibration_review_model_version_promotion_gate_v0',baseline_commit:'b37fb802'}}
function c01(a){const c=json('docs/twin_kernel/TWIN_CONFIDENCE_READ_MODEL_CONTRACT_V0.json');a.ok('contract',c.read_model_only&&c.confidence_is_not_recommendation_authority&&c.eligibility_is_not_action_approval&&c.read_model_is_not_production_runtime_activation&&c.recommendation_authority_allowed===false&&c.recommendation_generation_allowed===false&&c.action_approval_allowed===false&&c.runtime_model_update_allowed===false&&c.field_memory_write_allowed===false&&c.ao_act_allowed===false&&c.dashboard_authority_allowed===false&&c.confidence_read_model_emitted_allowed&&c.persisted_confidence_read_model_allowed===false&&c.db_write_allowed===false,{c});return c}
function c02(a){const s=json('docs/twin_kernel/TWIN_CONFIDENCE_COMPONENT_SCHEMA_V0.json');for(const f of ['evidence_completeness','evidence_freshness','trace_completeness','forecast_horizon_fit','forecast_error_status','calibration_review_status','model_lineage_status','promotion_governance_status','source_contract_status'])a.ok('component_'+f,s.required_components.includes(f));a.ok('component_boundary',s.allowed_component_statuses.includes('pass')&&s.allowed_component_statuses.includes('warn')&&s.allowed_component_statuses.includes('fail')&&s.allowed_component_statuses.includes('not_applicable')&&s.component_status_is_internal_policy_status&&s.dashboard_color_signal_allowed===false&&s.dashboard_priority_allowed===false&&s.ranking_allowed===false&&s.operator_action_hint_allowed===false,{s});return s}
function c03(a){const c=json('docs/twin_kernel/TWIN_CONFIDENCE_POLICY_CONTRACT_V0.json');a.ok('policy',c.confidence_levels.includes('high')&&c.confidence_levels.includes('medium')&&c.confidence_levels.includes('low')&&c.confidence_levels.includes('blocked')&&c.deterministic_aggregation&&c.freshness_as_of_ts==='declared_as_of_ts'&&c.current_time_allowed===false&&c.system_clock_allowed===false&&c.random_uuid_allowed===false&&c.llm_judgment_allowed===false&&c.model_training_allowed===false,{c});return c}
function c04(a){const c=json('docs/twin_kernel/TWIN_USE_ELIGIBILITY_POLICY_CONTRACT_V0.json');a.ok('elig_policy',c.allowed_statuses.includes('observation_only')&&c.allowed_statuses.includes('bridge_input_eligible')&&c.allowed_statuses.includes('blocked')&&c.allowed_statuses.includes('review_required')&&c.bridge_target_phase==='P16'&&c.bridge_input_only&&c.recommendation_generation_allowed===false&&c.recommendation_approval_allowed===false&&c.action_approval_allowed===false&&c.ao_act_authority_allowed===false&&c.forbidden_statuses.includes('auto_execute'),{c});return c}
function c05(a){const s=json('docs/twin_kernel/TWIN_CONFIDENCE_READ_MODEL_SCHEMA_V0.json');for(const f of ['confidence_read_model_id','twin_subject_ref','runtime_case_id','as_of_ts','freshness_as_of_ts','confidence_level','confidence_components','source_refs','trace_refs','model_lineage_refs','calibration_governance_refs','policy_refs','read_model_only'])a.ok('confidence_schema_'+f,s.required_fields.includes(f));a.ok('confidence_schema_emit',s.read_model_only&&s.confidence_read_model_emitted&&s.persisted_confidence_read_model_count===0&&s.db_write_count===0,{s});return s}
function c06(a){const s=json('docs/twin_kernel/TWIN_USE_ELIGIBILITY_READ_MODEL_SCHEMA_V0.json');for(const f of ['use_eligibility_read_model_id','confidence_read_model_id','twin_subject_ref','runtime_case_id','use_eligibility_status','eligibility_reasons','eligibility_blockers','source_refs','policy_refs','bridge_target_phase','bridge_input_only'])a.ok('elig_schema_'+f,s.required_fields.includes(f));a.ok('elig_schema_emit',s.use_eligibility_read_model_emitted&&s.persisted_use_eligibility_read_model_count===0&&s.bridge_target_phase==='P16'&&s.bridge_input_only&&s.recommendation_created===false&&s.recommendation_candidate_created===false&&s.action_approval_created===false&&s.ao_act_task_created===false,{s});return s}
function c07(a){const r=rr('eligible');a.ok('eligible',r.confidence_read_model_emitted&&r.use_eligibility_read_model_emitted&&r.persisted_confidence_read_model_count===0&&r.persisted_use_eligibility_read_model_count===0&&r.db_write_count===0&&r.confidence_level==='high'&&r.use_eligibility_status==='bridge_input_eligible'&&r.bridge_target_phase==='P16'&&r.bridge_input_only&&r.read_model_only&&r.recommendation_created===false&&r.recommendation_candidate_created===false&&r.action_approval_created===false&&r.ao_act_task_created===false&&r.runtime_model_update_count===0&&r.field_memory_write_count===0&&r.dashboard_authority===false&&scan(r).length===0,{r});return{...r,forbidden_semantics_recursive_scan_passed:true}}
function c08(a){const r=rr('low-evidence');a.ok('low_evidence',r.confidence_level==='low'&&r.use_eligibility_status==='observation_only'&&r.use_eligibility_status!=='bridge_input_eligible'&&r.recommendation_created===false&&scan(r).length===0,{r});return{low_evidence_fixture_confidence_level:'low',low_evidence_fixture_use_eligibility_status:'observation_only',bridge_input_eligible:false,recommendation_created:false,forbidden_semantics_recursive_scan_passed:true}}
function c09(a){const r=rr('high-error');a.ok('high_error',r.confidence_level==='low'&&r.use_eligibility_status==='blocked'&&r.eligibility_blockers.includes('forecast_error_status')&&r.recommendation_created===false&&r.action_approval_created===false&&scan(r).length===0,{r});return{high_error_fixture_confidence_level:'low',high_error_fixture_use_eligibility_status:'blocked',eligibility_blockers:r.eligibility_blockers,recommendation_created:false,action_approval_created:false,forbidden_semantics_recursive_scan_passed:true}}
function c10(a){const r=rr('missing-calibration-review');a.ok('missing_calibration',r.confidence_level==='medium'&&r.use_eligibility_status==='review_required'&&r.eligibility_blockers.includes('calibration_review_status')&&r.recommendation_created===false&&scan(r).length===0,{r});return{missing_calibration_review_fixture_confidence_level:'medium',missing_calibration_review_fixture_use_eligibility_status:'review_required',eligibility_blockers:r.eligibility_blockers,recommendation_created:false,forbidden_semantics_recursive_scan_passed:true}}
function c11(a){const r=rr('stale-model-lineage');a.ok('stale_lineage',r.confidence_level==='low'&&r.use_eligibility_status==='blocked'&&r.eligibility_blockers.includes('model_lineage_status')&&r.runtime_model_update_count===0&&scan(r).length===0,{r});return{stale_model_lineage_fixture_confidence_level:'low',stale_model_lineage_fixture_use_eligibility_status:'blocked',eligibility_blockers:r.eligibility_blockers,runtime_model_update_count:0,forbidden_semantics_recursive_scan_passed:true}}
function c12(a){const r=node([RUNNER,'--forbidden-'+R+'-request','--state-file',tmp('forbid.json')]);a.ok('forbidden_req',r.forbidden_recommendation_request_blocked===true&&r.recommendation_created===false&&r.recommendation_candidate_created===false&&r.recommendation_generation_allowed===false&&r.recommendation_approval_allowed===false&&r.action_approval_created===false&&r.action_approval_allowed===false&&r.ao_act_task_created===false&&r.ao_act_authority_allowed===false&&scan(r).length===0,{r});return{forbidden_recommendation_request_blocked:true,forbidden_semantics_recursive_scan_passed:true,recommendation_created:false,recommendation_candidate_created:false,recommendation_generation_allowed:false,recommendation_approval_allowed:false,action_approval_created:false,action_approval_allowed:false,ao_act_task_created:false,ao_act_authority_allowed:false}}
function c13(a){const st=tmp('idem.json'),f=node([RUNNER,'--fixture','eligible','--state-file',st]),s=node([RUNNER,'--fixture','eligible','--state-file',st]);a.ok('idem',f.first_read_model_emitted_count===1&&s.second_read_model_emitted_count===0&&s.same_confidence_read_model_id_reused&&s.same_use_eligibility_read_model_id_reused&&s.duplicate_read_model_created_count===0&&f.confidence_read_model_id===s.confidence_read_model_id&&f.use_eligibility_read_model_id===s.use_eligibility_read_model_id&&s.state_file_must_be_os_temp&&s.repo_write_allowed===false&&s.fixture_mutation_allowed===false&&s.db_write_allowed===false,{f,s});return{first_read_model_emitted_count:1,second_read_model_emitted_count:0,same_confidence_read_model_id_reused:true,same_use_eligibility_read_model_id_reused:true,duplicate_read_model_created_count:0,state_file_must_be_os_temp:true,repo_write_allowed:false,fixture_mutation_allowed:false,db_write_allowed:false}}
function runScript(f){const r=spawnSync(process.execPath,[f],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let p=null;try{p=JSON.parse(r.stdout||r.stderr)}catch{}return{script:f,status:r.status,ok:r.status===0&&p&&p.ok===true&&p.failed_assertion_count===0,parsed:p}}
function c14(a){const prior=PRIOR.map(runScript);a.ok('all_prior_p15_acceptance_passed',prior.every(r=>r.ok),{prior});const s=json('docs/twin_kernel/P15_TWIN_CONFIDENCE_USE_ELIGIBILITY_COMPLETION_REVIEW_V0.json').completion_scope;a.ok('completion_scope',s.eligible_confidence_read_model_passed&&s.low_evidence_observation_only_passed&&s.high_error_blocked_passed&&s.missing_calibration_review_required_passed&&s.stale_model_lineage_blocked_passed&&s.forbidden_recommendation_request_passed&&s.read_model_idempotency_passed&&s.forbidden_semantics_recursive_scan_passed&&s.bridge_target_phase==='P16'&&s.bridge_input_only&&s.confidence_read_model_emitted&&s.use_eligibility_read_model_emitted&&s.persisted_confidence_read_model_count===0&&s.persisted_use_eligibility_read_model_count===0&&s.db_write_count===0&&s.read_model_only&&s.runtime_model_update_count===0&&s.field_memory_write_count===0&&s.dashboard_authority===false,{s});return{all_prior_p15_acceptance_passed:true,...s,readme_p15_snapshot_present:read('README_MIGRATION.md').includes('P15 Twin Confidence / Use-Eligibility Read Model v0 Freeze Closure')}}
function run(name){const a=A();const m={P15_00_POST_P14_BASELINE_FREEZE_INHERITANCE_AUDIT:c00,P15_01_TWIN_CONFIDENCE_READ_MODEL_CONTRACT_ACCEPTANCE:c01,P15_02_TWIN_CONFIDENCE_COMPONENT_SCHEMA_ACCEPTANCE:c02,P15_03_TWIN_CONFIDENCE_POLICY_CONTRACT_ACCEPTANCE:c03,P15_04_TWIN_USE_ELIGIBILITY_POLICY_CONTRACT_ACCEPTANCE:c04,P15_05_TWIN_CONFIDENCE_READ_MODEL_SCHEMA_ACCEPTANCE:c05,P15_06_TWIN_USE_ELIGIBILITY_READ_MODEL_SCHEMA_ACCEPTANCE:c06,P15_07_TWIN_CONFIDENCE_USE_ELIGIBILITY_READ_MODEL_ACCEPTANCE:c07,P15_08_LOW_EVIDENCE_OBSERVATION_ONLY_ACCEPTANCE:c08,P15_09_HIGH_FORECAST_ERROR_BLOCKED_ACCEPTANCE:c09,P15_10_MISSING_CALIBRATION_REVIEW_REQUIRED_ACCEPTANCE:c10,P15_11_STALE_MODEL_LINEAGE_BLOCKED_ACCEPTANCE:c11,P15_12_FORBIDDEN_RECOMMENDATION_REQUEST_ACCEPTANCE:c12,P15_13_READ_MODEL_IDEMPOTENCY_ACCEPTANCE:c13,P15_14_COMPLETION_REVIEW_ACCEPTANCE:c14};try{a.ok('known_acceptance_entrypoint',typeof m[name]==='function',{name});const res=m[name](a);const surface=surf(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...res,...surface,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}
module.exports={run};
