// scripts/governance_acceptance/P18_06_P17_DRAFT_BOUNDARY_NON_BYPASS_ACCEPTANCE.cjs
'use strict';
const {spawnSync}=require('node:child_process');
const path=require('node:path');
const ROOT=process.cwd();
const RUNNER='scripts/twin_kernel/P18_08_RECOMMENDATION_APPROVAL_GOVERNANCE_GATE_V0.cjs';
function runFixture(name){const r=spawnSync(process.execPath,[RUNNER,'--fixture',name],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});if(r.status!==0)throw Error(name+'_RUNNER_FAILED:'+r.stderr);return JSON.parse(r.stdout)}
function gitDiff(){const r=spawnSync('git',['diff','--name-only','p17_recommendation_candidate_review_draft_governance_gate_v0...HEAD'],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});return r.status===0?r.stdout.split(/\r?\n/).filter(Boolean):[]}
function allowedSurface(f){return f.startsWith('docs/tasks/P18-')||f.startsWith('docs/twin_kernel/fixtures/p18_recommendation_approval/')||f.startsWith('scripts/governance_acceptance/P18_')||f==='scripts/governance_acceptance/P18_ACCEPTANCE_HELPERS.cjs'||f===RUNNER||f==='README_MIGRATION.md'||f.startsWith('docs/twin_kernel/RECOMMENDATION_APPROVAL_')||f.startsWith('docs/twin_kernel/APPROVED_RECOMMENDATION_')||f==='docs/twin_kernel/RECOMMENDATION_APPROVAL_BOUNDARY_POLICY_V0.json'||f==='docs/twin_kernel/RECOMMENDATION_APPROVAL_CONFLICT_POLICY_V0.json'||f==='docs/twin_kernel/P18_RECOMMENDATION_APPROVAL_GOVERNANCE_COMPLETION_REVIEW_V0.json'}
const assertions=[];function ok(name,value,details){assertions.push({name,passed:value===true,details:details||{}});if(value!==true){const e=Error('ASSERTION_FAILED:'+name);e.details=details||{};throw e}}
try{const malformed=runFixture('malformed');const blocked=runFixture('blocked-source');const wrong=runFixture('wrong-source-phase');const actionPayload=runFixture('forbidden-action-payload');const agronomic=runFixture('agronomic-prescription');const operatorBoundary=runFixture('operator-boundary');const contentBoundary=runFixture('content-boundary');ok('malformed_draft_blocked',malformed.malformed_draft_blocked===true,{malformed});ok('blocked_source_draft_blocked',blocked.blocked_source_draft_blocked===true,{blocked});ok('wrong_source_phase_blocked',wrong.wrong_source_phase_blocked===true,{wrong});ok('draft_with_action_payload_blocked',actionPayload.draft_with_action_payload_blocked===true&&actionPayload.forbidden_action_payload_blocked===true,{actionPayload});ok('draft_with_agronomic_prescription_blocked',agronomic.draft_with_agronomic_prescription_blocked===true,{agronomic});ok('draft_with_operator_instruction_blocked',operatorBoundary.draft_with_operator_instruction_blocked===true,{operatorBoundary});ok('draft_with_recommendation_body_blocked',contentBoundary.draft_with_recommendation_body_blocked===true,{contentBoundary});for(const r of [malformed,blocked,wrong,actionPayload,agronomic,operatorBoundary,contentBoundary]){ok('approved_record_not_emitted_for_blocked_input',r.approved_record_emitted_for_blocked_inputs===false&&r.blocked_inputs_approval_packet_emitted===false&&r.blocked_inputs_approved_record_emitted===false,{result:r});ok('blocked_input_creates_no_runtime_effect',r.recommendation_body_created===false&&r.recommendation_content_created===false&&r.action_plan_created===false&&r.action_approval_created===false&&r.ao_act_task_created===false,{result:r})}const bad=gitDiff().filter(f=>!allowedSurface(f));ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});const failed=assertions.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:'P18_06_P17_DRAFT_BOUNDARY_NON_BYPASS_ACCEPTANCE',malformed_draft_blocked:true,blocked_source_draft_blocked:true,wrong_source_phase_blocked:true,draft_with_action_payload_blocked:true,draft_with_agronomic_prescription_blocked:true,draft_with_operator_instruction_blocked:true,draft_with_recommendation_body_blocked:true,approved_record_emitted_for_blocked_inputs:false,recommendation_body_created:false,recommendation_content_created:false,action_plan_created:false,action_approval_created:false,ao_act_task_created:false,server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length,assertion_count:assertions.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:'P18_06_P17_DRAFT_BOUNDARY_NON_BYPASS_ACCEPTANCE',error:e.message,details:e.details||null,assertions},null,2));process.exit(1)}
