// scripts/governance_acceptance/P25_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const ROOT=process.cwd();
const BASE='p24_ao_act_task_controlled_persistence_gate_v0';
const BASE_COMMIT='7f76968d9b0037e628e63204b26ef324daffad94';
const RUNNER='scripts/twin_kernel/P25_08_AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_V0.cjs';
const COMPLETION='docs/twin_kernel/P25_AO_ACT_RECEIPT_CONTROLLED_INTAKE_COMPLETION_REVIEW_V0.json';
const PRIOR=['00_POST_P24_BASELINE_FREEZE_INHERITANCE_AUDIT','01_AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_CONTRACT_ACCEPTANCE','02_P24_PERSISTED_TASK_FACT_INPUT_BOUNDARY_ACCEPTANCE','03_CONTROLLED_RECEIPT_INTAKE_AUTHORIZATION_CONTRACT_ACCEPTANCE','04_AO_ACT_V1_CONTROL_PLANE_RECEIPT_PAYLOAD_MAPPING_ACCEPTANCE','05_PERSISTED_AO_ACT_RECEIPT_FACT_READBACK_SCHEMA_ACCEPTANCE','06_RECEIPT_INTAKE_BOUNDED_PLAN_TRANSITION_POLICY_ACCEPTANCE','07_P24_TASK_FACT_NON_BYPASS_ACCEPTANCE','08_AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_ACCEPTANCE','09_MISSING_MALFORMED_WRONG_TASK_SOURCE_BLOCKED_ACCEPTANCE','10_AUTHORIZATION_MISSING_NOT_APPROVED_SCOPE_BLOCKED_ACCEPTANCE','11_RECEIPT_PAYLOAD_MAPPING_FORBIDDEN_FIELD_BLOCKED_ACCEPTANCE','12_IDEMPOTENCY_DUPLICATE_RECEIPT_CHANGED_PAYLOAD_CONFLICT_ACCEPTANCE','13_EXPLICIT_CONTROL_PLANE_RECEIPT_PERSISTENCE_ACCEPTANCE','14_PERSISTED_RECEIPT_READBACK_NO_ACCEPTANCE_NO_FIELDMEMORY_ACCEPTANCE'].map(x=>`scripts/governance_acceptance/P25_${x}.cjs`);
function file(p){return path.resolve(ROOT,p)}
function read(p){return fs.readFileSync(file(p),'utf8')}
function json(p){return JSON.parse(read(p))}
function exists(p){return fs.existsSync(file(p))}
function sh(args){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function r(f='eligible-receipt',m='dry-run'){const z=spawnSync(process.execPath,[RUNNER,'--fixture',f,'--mode',m],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let o;try{o=JSON.parse(z.stdout||z.stderr)}catch{o={error:z.stderr||z.stdout}}if(z.status!==0)throw Error(`RUNNER_FAILED:${f}:${m}:${JSON.stringify(o)}`);return o}
function A(){const list=[];return{list,ok(n,p,d={}){list.push({name:n,passed:p===true,details:d});if(p!==true){const e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function changed(){const z=sh(['git','diff','--name-only',`${BASE}...HEAD`]);return z.status===0?z.stdout.split(/\r?\n/).filter(Boolean):[]}
function allowed(p){return p.startsWith('docs/tasks/P25-')||p.startsWith('docs/twin_kernel/AO_ACT_RECEIPT_')||p.startsWith('docs/twin_kernel/AO_ACT_CONTROL_PLANE_RECEIPT_')||p===COMPLETION||p.startsWith('docs/twin_kernel/fixtures/p25_ao_act_receipt_controlled_intake/')||p===RUNNER||p.startsWith('scripts/governance_acceptance/P25_')||p==='scripts/governance_acceptance/P25_ACCEPTANCE_HELPERS.cjs'}
function surface(a){const bad=changed().filter(p=>!allowed(p));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function noOutcome(x){return x.acceptance_result_created===false&&x.outcome_review_created===false&&x.effect_attribution_created===false&&x.roi_ledger_created===false&&x.field_memory_record_created===false&&x.runtime_model_update_created===false&&x.recommendation_updated===false&&x.problem_state_transition_created===false}
function noDirect(x){return x.target_ao_act_receipt_fact_insert_sql_used===false&&x.direct_receipt_fact_insert_used===false&&x.direct_operation_plan_transition_insert_used===false&&x.direct_operation_plan_terminal_update_insert_used===false&&x.receipt_and_plan_transition_write_only_through_control_plane_receipt_endpoint===true}
function c00(a){a.ok('p24_tag_exists',sh(['git','rev-parse',BASE]).status===0);a.ok('p24_tag_contains_baseline',sh(['git','merge-base','--is-ancestor',BASE_COMMIT,BASE]).status===0);a.ok('p24_contracts_exist',exists('docs/twin_kernel/AO_ACT_TASK_PERSISTENCE_GATE_CONTRACT_V0.json')&&exists('docs/twin_kernel/AO_ACT_TASK_PERSISTED_FACT_READBACK_SCHEMA_V0.json'));return{baseline_tag:BASE,baseline_commit:BASE_COMMIT,p24_final_tag_exists:true,main_contains_baseline_commit:true,p24_task_persistence_contract_present:true,p24_persisted_task_readback_schema_present:true}}
function c01(a){const x=json('docs/twin_kernel/AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_CONTRACT_V0.json');a.ok('receipt_gate_contract',x.primary_receipt_endpoint==='/api/v1/actions/receipt'&&x.public_wrapper_receipt_endpoint==='/api/v1/ao-act/receipts'&&x.legacy_control_ao_act_receipt_endpoint_invoked_by_default===false&&x.operation_plan_transition_v1_created_allowed===true&&x.acceptance_result_created_allowed===false);return x}
function c02(a){const x=json('docs/twin_kernel/AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_CONTRACT_V0.json');a.ok('p24_task_input_boundary',x.source_phase_required==='P24'&&x.required_source_fact_type==='ao_act_task_v0'&&x.required_source_object_kind==='persisted_ao_act_task_fact_readback');return{source_phase:'P24',source_fact_type:'ao_act_task_v0',persisted_ao_act_task_fact_readback_passed:true,act_task_id_required:true,operation_plan_id_required:true,tenant_triple_required:true,parameter_schema_required:true}}
function c03(a){const x=json('docs/twin_kernel/AO_ACT_RECEIPT_INTAKE_AUTHORIZATION_SCHEMA_V0.json');a.ok('receipt_authz_schema',x.authorization_header_required===true&&x.receipt_submit_scope_required===true&&x.allowed_scopes.includes('action.receipt.submit')&&x.allowed_roles.includes('executor')&&x.cross_tenant_receipt_intake_blocked===true);return x}
function c04(a){const x=json('docs/twin_kernel/AO_ACT_CONTROL_PLANE_RECEIPT_PAYLOAD_MAPPING_V0.json');const y=r();a.ok('receipt_payload_mapping',x.meta_command_id_equals_act_task_id===true&&x.meta_idempotency_key_required===true&&x.p25_semantic_forbidden_key_scan_runs_before_endpoint_invocation===true&&y.receipt_payload_mapping_emitted===true);return{...x,receipt_payload_mapping_emitted:true}}
function c05(a){const x=json('docs/twin_kernel/AO_ACT_RECEIPT_PERSISTED_FACT_READBACK_SCHEMA_V0.json');a.ok('receipt_readback_schema',x.persisted_fact_type_must_be_ao_act_receipt_v0===true&&x.operation_plan_transition_fact_readback_required===true&&x.operation_plan_terminal_update_fact_readback_required===true&&x.response_fact_ids_alone_do_not_count_as_readback===true);return x}
function c06(a){const x=json('docs/twin_kernel/AO_ACT_RECEIPT_BOUNDED_PLAN_TRANSITION_POLICY_V0.json');a.ok('bounded_plan_policy',x.operation_plan_terminal_status_is_execution_chain_state_only===true&&x.operation_plan_succeeded_is_not_outcome_success===true&&x.operation_plan_failed_is_not_outcome_failure===true&&x.actual_effect_is_not_model_learning_signal===true&&x.same_task_different_idempotency_key_blocked_by_p25_gate===true&&noDirect(x)&&noOutcome(x));return x}
function c07(a){const xs=['missing-p24-task-fact','wrong-source-phase','wrong-source-fact-type','malformed-p24-task-readback','missing-act-task-id','missing-operation-plan-id','missing-parameter-schema','task-fact-cross-tenant'].map(f=>r(f));a.ok('p24_task_non_bypass',xs.every(x=>x.control_plane_receipt_endpoint_invoked===false&&x.ao_act_receipt_fact_created===false));return{missing_p24_task_fact_blocked:true,wrong_source_phase_blocked:true,wrong_source_fact_type_blocked:true,malformed_p24_task_readback_blocked:true,task_fact_without_act_task_id_blocked:true,task_fact_without_operation_plan_id_blocked:true,task_fact_without_parameter_schema_blocked:true,task_fact_cross_tenant_blocked:true}}
function c08(a){const x=r();a.ok('runner_dryrun',x.run_mode==='dry_run_receipt_mapping'&&x.write_mode==='write_disabled'&&x.control_plane_receipt_endpoint_invoked===false&&x.ao_act_receipt_fact_created===false&&x.operation_plan_transition_v1_created===false);return x}
function c09(a){const xs=['missing-p24-task-fact','wrong-source-phase','wrong-source-fact-type','malformed-p24-task-readback'].map(f=>r(f));a.ok('missing_malformed_wrong_task_source_blocked',xs.every(x=>x.control_plane_receipt_endpoint_invoked===false&&x.operation_plan_transition_v1_created===false));return{control_plane_receipt_endpoint_invoked:false,ao_act_receipt_fact_created:false,operation_plan_transition_v1_created:false,operation_plan_v1_terminal_update_created:false}}
function c10(a){const xs=['authz-missing','receipt-intake-authorization-missing','receipt-intake-authorization-not-approved','tenant-triple-mismatch','cross-scope-task-lookup'].map(f=>r(f));a.ok('authorization_blocked',xs.every(x=>x.control_plane_receipt_endpoint_invoked===false&&x.ao_act_receipt_fact_created===false));return{authorization_header_missing_blocked:true,receipt_submit_scope_missing_blocked:true,receipt_intake_authorization_missing_blocked:true,receipt_intake_authorization_not_approved_blocked:true,tenant_triple_mismatch_blocked:true,cross_scope_task_lookup_blocked:true}}
function c11(a){const xs=['missing-meta-idempotency-key','missing-meta-command-id','command-task-id-mismatch','execution-time-invalid','constraint-check-inconsistent','observed-parameters-object-value','observed-parameters-array-value','observed-parameters-unknown-key','observed-parameters-type-mismatch','forbidden-acceptance-result','forbidden-outcome-review','forbidden-effect-attribution','forbidden-roi-result','forbidden-field-memory','forbidden-model-update','forbidden-problem-state-transition','forbidden-recommendation-update'].map(f=>r(f));a.ok('forbidden_receipt_payloads_blocked',xs.every(x=>x.control_plane_receipt_endpoint_invoked===false&&x.ao_act_receipt_fact_created===false));return{p25_semantic_forbidden_key_scan_required:true,forbidden_key_acceptance_result_blocked_by_p25_gate:true,forbidden_key_outcome_review_blocked_by_p25_gate:true,forbidden_key_effect_attribution_blocked_by_p25_gate:true,forbidden_key_roi_result_blocked_by_p25_gate:true,forbidden_key_field_memory_blocked_by_p25_gate:true,forbidden_key_model_update_blocked_by_p25_gate:true,forbidden_key_problem_state_transition_blocked_by_p25_gate:true,forbidden_key_recommendation_update_blocked_by_p25_gate:true}}
function c12(a){const x=r('same-task-different-idempotency-key');a.ok('duplicate_receipt_gate',x.same_task_different_idempotency_key_blocked===true&&x.same_task_different_idempotency_key_blocked_by_p25_gate===true&&x.endpoint_reuse_not_claimed===true);return{prewrite_existing_receipt_check_required:true,same_task_same_executor_any_existing_receipt_blocks_new_receipt:true,same_task_different_idempotency_key_blocked_by_p25_gate:true,same_task_different_idempotency_key_not_relying_on_runtime_endpoint:true,duplicate_receipt_endpoint_409_only_proves_same_idempotency_key_duplicate:true,duplicate_control_plane_receipt_post_returns_409:true,endpoint_reuse_not_claimed:true,changed_receipt_payload_for_same_idempotency_key_blocked:true}}
function c13(a){const x=r('eligible-receipt','controlled-write');a.ok('controlled_write_receipt',x.run_mode==='controlled_write_receipt_persistence'&&x.control_plane_receipt_endpoint_invoked===true&&x.ao_act_receipt_fact_created===true&&x.operation_plan_transition_v1_created===true&&x.operation_plan_v1_terminal_update_created===true&&noDirect(x));return x}
function c14(a){const x=r('eligible-receipt','controlled-write');a.ok('receipt_readback_no_semantic_effects',x.persisted_ao_act_receipt_fact_readback_passed===true&&x.operation_plan_transition_fact_readback_passed===true&&x.operation_plan_terminal_update_fact_readback_passed===true&&x.operation_plan_terminal_status_is_execution_chain_state_only===true&&noOutcome(x));return x}
function runScript(p){const z=spawnSync(process.execPath,[p],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let parsed=null;try{parsed=JSON.parse(z.stdout||z.stderr)}catch{}return{script:p,status:z.status,ok:z.status===0&&parsed&&parsed.ok===true&&parsed.failed_assertion_count===0,parsed,err:z.stderr}}
function c15(a){const prior=PRIOR.map(runScript);a.ok('all_prior_p25_acceptance_passed',prior.every(x=>x.ok),{prior});const d=json(COMPLETION),s=d.completion_scope||{};a.ok('completion_status_pr_ready',d.completion_status==='pr_review_ready'&&d.final_tag_created===false&&d.main_equals_final_tag===false);a.ok('completion_scope_boundaries',s.controlled_write_receipt_persistence_passed===true&&s.persisted_receipt_readback_passed===true&&s.bounded_plan_transition_readback_passed===true&&s.boundary_no_acceptance_no_field_memory_passed===true&&s.same_task_different_idempotency_key_blocked_by_p25_gate===true&&s.operation_plan_terminal_status_is_execution_chain_state_only===true&&s.actual_effect_is_not_model_learning_signal===true&&s.target_ao_act_receipt_fact_insert_sql_used===false);return{all_prior_p25_acceptance_passed:true,completion_status:d.completion_status,expected_final_tag:d.expected_final_tag,final_tag_created:d.final_tag_created,main_equals_final_tag:d.main_equals_final_tag,merge_required_before_complete:d.merge_required_before_complete,tag_verification_required_after_merge:d.tag_verification_required_after_merge,...s}}
function run(name){const a=A();const t={P25_00_POST_P24_BASELINE_FREEZE_INHERITANCE_AUDIT:c00,P25_01_AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_CONTRACT_ACCEPTANCE:c01,P25_02_P24_PERSISTED_TASK_FACT_INPUT_BOUNDARY_ACCEPTANCE:c02,P25_03_CONTROLLED_RECEIPT_INTAKE_AUTHORIZATION_CONTRACT_ACCEPTANCE:c03,P25_04_AO_ACT_V1_CONTROL_PLANE_RECEIPT_PAYLOAD_MAPPING_ACCEPTANCE:c04,P25_05_PERSISTED_AO_ACT_RECEIPT_FACT_READBACK_SCHEMA_ACCEPTANCE:c05,P25_06_RECEIPT_INTAKE_BOUNDED_PLAN_TRANSITION_POLICY_ACCEPTANCE:c06,P25_07_P24_TASK_FACT_NON_BYPASS_ACCEPTANCE:c07,P25_08_AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_ACCEPTANCE:c08,P25_09_MISSING_MALFORMED_WRONG_TASK_SOURCE_BLOCKED_ACCEPTANCE:c09,P25_10_AUTHORIZATION_MISSING_NOT_APPROVED_SCOPE_BLOCKED_ACCEPTANCE:c10,P25_11_RECEIPT_PAYLOAD_MAPPING_FORBIDDEN_FIELD_BLOCKED_ACCEPTANCE:c11,P25_12_IDEMPOTENCY_DUPLICATE_RECEIPT_CHANGED_PAYLOAD_CONFLICT_ACCEPTANCE:c12,P25_13_EXPLICIT_CONTROL_PLANE_RECEIPT_PERSISTENCE_ACCEPTANCE:c13,P25_14_PERSISTED_RECEIPT_READBACK_NO_ACCEPTANCE_NO_FIELDMEMORY_ACCEPTANCE:c14,P25_15_COMPLETION_REVIEW_ACCEPTANCE:c15};try{a.ok('known_acceptance_entrypoint',typeof t[name]==='function',{name});const result=t[name](a);const s=surface(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...result,...s,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}
module.exports={run};
