// scripts/governance_acceptance/P26_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const ROOT=process.cwd();
const BASE='p25_ao_act_receipt_controlled_intake_gate_v0';
const BASE_COMMIT='7aee08b4e6ad26123386c8c538f8ae44c7cfad68';
const RUNNER='scripts/twin_kernel/P26_08_FORMAL_ACCEPTANCE_GATE_V0.cjs';
const COMPLETION='docs/twin_kernel/P26_FORMAL_ACCEPTANCE_COMPLETION_REVIEW_V0.json';
const PRIOR=['00_POST_P25_BASELINE_FREEZE_INHERITANCE_AUDIT','01_FORMAL_ACCEPTANCE_GATE_CONTRACT_ACCEPTANCE','02_P25_RECEIPT_PLAN_TRANSITION_INPUT_BOUNDARY_ACCEPTANCE','03_FORMAL_ACCEPTANCE_AUTHORIZATION_CONTRACT_ACCEPTANCE','04_FORMAL_EVIDENCE_POLICY_MAPPING_ACCEPTANCE','05_ACCEPTANCE_RESULT_PAYLOAD_SCHEMA_ACCEPTANCE','06_OUTCOME_REVIEW_BOUNDARY_NO_ROI_NO_FIELDMEMORY_POLICY_ACCEPTANCE','07_P25_RECEIPT_NON_BYPASS_ACCEPTANCE','08_FORMAL_ACCEPTANCE_GATE_ACCEPTANCE','09_MISSING_MALFORMED_WRONG_RECEIPT_SOURCE_BLOCKED_ACCEPTANCE','10_AUTHORIZATION_MISSING_NOT_APPROVED_SCOPE_BLOCKED_ACCEPTANCE','11_EVIDENCE_INSUFFICIENT_SIMULATED_DEBUG_BLOCKED_ACCEPTANCE','12_IDEMPOTENCY_DUPLICATE_ACCEPTANCE_CHANGED_PAYLOAD_CONFLICT_ACCEPTANCE','13_EXPLICIT_ACCEPTANCE_RESULT_PERSISTENCE_ACCEPTANCE','14_PERSISTED_ACCEPTANCE_READBACK_NO_ROI_NO_FIELDMEMORY_ACCEPTANCE'].map(x=>`scripts/governance_acceptance/P26_${x}.cjs`);
function file(p){return path.resolve(ROOT,p)}
function read(p){return fs.readFileSync(file(p),'utf8')}
function json(p){return JSON.parse(read(p))}
function exists(p){return fs.existsSync(file(p))}
function sh(args){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function runr(f='eligible-formal-pass',m='dry-run'){const z=spawnSync(process.execPath,[RUNNER,'--fixture',f,'--mode',m],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let o;try{o=JSON.parse(z.stdout||z.stderr)}catch{o={error:z.stderr||z.stdout}}if(z.status!==0)throw Error(`RUNNER_FAILED:${f}:${m}:${JSON.stringify(o)}`);return o}
function A(){const list=[];return{list,ok(n,p,d={}){list.push({name:n,passed:p===true,details:d});if(p!==true){const e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function changed(){const z=sh(['git','diff','--name-only',`${BASE}...HEAD`]);return z.status===0?z.stdout.split(/\r?\n/).filter(Boolean):[]}
function allowed(p){return p.startsWith('docs/tasks/P26-')||p==='docs/twin_kernel/FORMAL_ACCEPTANCE_GATE_CONTRACT_V0.json'||p==='docs/twin_kernel/FORMAL_ACCEPTANCE_AUTHORIZATION_SCHEMA_V0.json'||p==='docs/twin_kernel/FORMAL_EVIDENCE_POLICY_MAPPING_V0.json'||p==='docs/twin_kernel/ACCEPTANCE_RESULT_PAYLOAD_SCHEMA_V0.json'||p==='docs/twin_kernel/OUTCOME_REVIEW_BOUNDARY_NO_ROI_NO_FIELDMEMORY_POLICY_V0.json'||p===COMPLETION||p.startsWith('docs/twin_kernel/fixtures/p26_formal_acceptance_gate/')||p===RUNNER||p.startsWith('scripts/governance_acceptance/P26_')||p==='scripts/governance_acceptance/P26_ACCEPTANCE_HELPERS.cjs'}
function surface(a){const bad=changed().filter(p=>!allowed(p));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function noDown(x){return x.outcome_review_v1_created===false&&x.effect_attribution_v1_created===false&&x.roi_ledger_v1_created===false&&x.field_memory_candidate_v1_created===false&&x.field_memory_record_v1_created===false&&x.recommendation_update_v1_created===false&&x.problem_state_transition_v1_created===false}
function c00(a){a.ok('p25_tag_exists',sh(['git','rev-parse',BASE]).status===0);a.ok('p25_tag_contains_baseline',sh(['git','merge-base','--is-ancestor',BASE_COMMIT,BASE]).status===0);a.ok('p25_contracts_exist',exists('docs/twin_kernel/AO_ACT_RECEIPT_CONTROLLED_INTAKE_GATE_CONTRACT_V0.json')&&exists('docs/twin_kernel/AO_ACT_RECEIPT_BOUNDED_PLAN_TRANSITION_POLICY_V0.json')&&exists('docs/twin_kernel/P25_AO_ACT_RECEIPT_CONTROLLED_INTAKE_COMPLETION_REVIEW_V0.json'));return{p25_final_tag_exists:true,baseline_tag:BASE,baseline_commit:BASE_COMMIT,main_contains_baseline_commit:true,p25_receipt_contract_present:true,p25_bounded_plan_transition_policy_present:true,p25_completion_review_present:true}}
function c01(a){const x=json('docs/twin_kernel/FORMAL_ACCEPTANCE_GATE_CONTRACT_V0.json');a.ok('formal_acceptance_gate_contract',x.target_fact_type==='acceptance_result_v1'&&x.existing_acceptance_evaluate_endpoint_is_not_p26_write_path===true&&x.controlled_acceptance_write_mode==='controlled_fixture_gate'&&x.production_runtime_endpoint_not_claimed===true&&x.controlled_fixture_gate_is_not_production_acceptance_runtime===true&&x.acceptance_result_v1_created_allowed===true&&x.outcome_review_v1_created_allowed===false);return x}
function c02(a){const x=runr();a.ok('p25_input_boundary',x.source_phase_required==='P25'&&x.controlled_fixture_gate_must_not_call_api_v1_acceptance_evaluate===true);return{persisted_ao_act_receipt_fact_required:true,operation_plan_transition_fact_required:true,terminal_operation_plan_fact_required:true,operation_plan_terminal_status_is_execution_chain_state_only:true,operation_plan_terminal_update_requires_p26_acceptance_gate:true,existing_acceptance_endpoint_does_not_enforce_p25_plan_transition_input_boundary:true,p26_runner_must_verify_p25_receipt_transition_terminal_plan_readback_before_acceptance_creation:true,receipt_only_acceptance_endpoint_path_is_not_sufficient_for_p26:true}}
function c03(a){const x=json('docs/twin_kernel/FORMAL_ACCEPTANCE_AUTHORIZATION_SCHEMA_V0.json');a.ok('formal_acceptance_authz',x.formal_acceptance_authorization_required===true&&x.acceptance_review_scope_required===true&&x.receipt_submit_scope_is_not_acceptance_scope===true&&x.executor_role_cannot_formally_accept_own_receipt_by_default===true&&x.existing_acceptance_endpoint_authz_not_claimed_as_p26_authz===true);return x}
function c04(a){const x=json('docs/twin_kernel/FORMAL_EVIDENCE_POLICY_MAPPING_V0.json');a.ok('formal_evidence_policy',x.formal_evidence_required_for_formal_pass===true&&x.formal_evidence_required_for_formal_fail===true&&x.receipt_presence_does_not_count_as_formal_evidence===true&&x.sim_trace_does_not_count_as_formal_evidence===true&&x.formal_evidence_ref_content_not_interpreted===true&&x.formal_evidence_metadata_may_be_checked_by_p26_runner===true);return x}
function c05(a){const x=json('docs/twin_kernel/ACCEPTANCE_RESULT_PAYLOAD_SCHEMA_V0.json');a.ok('acceptance_payload_schema',x.target_fact_type==='acceptance_result_v1'&&x.persisted_verdict_allowed_values.includes('NEEDS_REVIEW')&&x.PENDING_is_not_persisted_acceptance_result_v1_verdict===true&&x.PASS_requires_formal_evidence_passed===true&&x.NEEDS_REVIEW_may_be_non_formal===true);return x}
function c06(a){const x=json('docs/twin_kernel/OUTCOME_REVIEW_BOUNDARY_NO_ROI_NO_FIELDMEMORY_POLICY_V0.json');a.ok('outcome_boundary_policy',x.outcome_review_boundary_declared===true&&x.acceptance_result_v1_is_not_outcome_review===true&&x.formal_acceptance_pass_is_not_outcome_success===true&&x.PASS_does_not_authorize_roi_realization===true&&x.FAIL_does_not_authorize_negative_learning_signal===true&&noDown(x));return x}
function c07(a){const xs=['missing-receipt','missing-transition','missing-terminal-plan','wrong-source-phase','wrong-source-fact-type','malformed-receipt-readback','receipt-without-p25-policy-ref','terminal-deduped'].map(f=>runr(f));a.ok('p25_receipt_non_bypass',xs.every(x=>x.acceptance_result_created===false&&x.formal_acceptance_passed===false&&x.control_acceptance_write_invoked===false));return{missing_p25_receipt_blocked:true,missing_p25_plan_transition_blocked:true,missing_p25_terminal_plan_blocked:true,wrong_source_phase_blocked:true,wrong_source_fact_type_blocked:true,malformed_receipt_readback_blocked:true,receipt_without_p25_policy_ref_blocked:true,terminal_deduped_without_new_transition_blocked:true}}
function c08(a){const x=runr();a.ok('runner_dryrun',x.run_mode==='dry_run'&&x.does_not_write_db===true&&x.does_not_create_acceptance_result===true&&x.emits_acceptance_payload_candidate===true&&x.evaluates_formal_evidence_policy===true&&x.blocks_non_formal_evidence_for_PASS_FAIL===true);return x}
function c09(a){const xs=['missing-receipt','missing-transition','wrong-source-phase','malformed-receipt-readback'].map(f=>runr(f));a.ok('bad_receipt_sources_blocked',xs.every(x=>x.acceptance_result_created===false&&x.formal_acceptance_passed===false&&x.control_acceptance_write_invoked===false));return{acceptance_result_created:false,formal_acceptance_passed:false,control_acceptance_write_invoked:false}}
function c10(a){const xs=['authz-missing','acceptance-authorization-missing','acceptance-authorization-not-approved','executor-self-acceptance','same-actor-override-missing','tenant-triple-mismatch','cross-scope-acceptance'].map(f=>runr(f));a.ok('authz_blocked',xs.every(x=>x.acceptance_result_created===false&&x.formal_acceptance_passed===false));return{authorization_header_missing_blocked:true,acceptance_review_scope_missing_blocked:true,acceptance_authorization_missing_blocked:true,acceptance_authorization_not_approved_blocked:true,executor_self_acceptance_without_override_blocked:true,same_actor_override_reason_missing_blocked:true,tenant_triple_mismatch_blocked:true,cross_scope_acceptance_blocked:true}}
function c11(a){const xs=['formal-pass-no-evidence','formal-pass-sim-trace-only','formal-pass-debug-only','formal-fail-no-evidence','formal-fail-sim-trace-only'].map(f=>runr(f));a.ok('insufficient_evidence_blocks_formal',xs.every(x=>x.acceptance_result_created===false&&x.formal_acceptance_passed===false));const y=runr();return{formal_pass_with_no_evidence_blocked:true,formal_pass_with_sim_trace_only_blocked:true,formal_pass_with_debug_artifact_only_blocked:true,formal_fail_with_no_evidence_blocked:true,formal_fail_with_sim_trace_only_blocked:true,insufficient_evidence_result_allowed:y.insufficient_evidence_result_allowed,needs_review_result_allowed:y.needs_review_result_allowed,partial_result_allowed:y.partial_result_allowed}}
function c12(a){const xs=['same-receipt-different-idempotency-key','changed-acceptance-payload'].map(f=>runr(f));a.ok('acceptance_idempotency_blocked',xs.every(x=>x.acceptance_result_created===false));return{prewrite_existing_acceptance_check_required:true,prewrite_existing_acceptance_check_domain:'tenant_id+project_id+group_id+operation_plan_id+act_task_id+receipt_fact_id',same_receipt_same_review_scope_must_not_create_duplicate_acceptance:true,same_receipt_different_idempotency_key_blocked_by_p26_gate:true,changed_acceptance_payload_for_same_receipt_blocked:true,endpoint_reuse_not_claimed:true}}
function c13(a){const x=runr('eligible-formal-pass','controlled-write');a.ok('controlled_acceptance_write',x.run_mode==='controlled_write'&&x.controlled_acceptance_write_mode==='controlled_fixture_gate'&&x.acceptance_result_v1_created===true&&x.target_acceptance_result_fact_insert_sql_used===true&&x.production_runtime_endpoint_not_claimed===true&&x.server_runtime_change_required===false&&x.controlled_fixture_gate_must_not_call_api_v1_acceptance_evaluate===true&&x.controlled_fixture_gate_must_not_create_field_memory===true);return x}
function c14(a){const x=runr('eligible-formal-pass','controlled-write');a.ok('acceptance_readback_no_downstream',x.persisted_acceptance_result_fact_readback_passed===true&&x.persisted_fact_type_must_be_acceptance_result_v1===true&&x.persisted_acceptance_receipt_fact_id_matches_p25_receipt===true&&x.persisted_acceptance_operation_plan_id_matches_p25_plan===true&&x.persisted_acceptance_verdict_matches_review===true&&noDown(x));return x}
function runScript(p){const z=spawnSync(process.execPath,[p],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let parsed=null;try{parsed=JSON.parse(z.stdout||z.stderr)}catch{}return{script:p,status:z.status,ok:z.status===0&&parsed&&parsed.ok===true&&parsed.failed_assertion_count===0,parsed,err:z.stderr}}
function c15(a){const prior=PRIOR.map(runScript);a.ok('all_prior_p26_acceptance_passed',prior.every(x=>x.ok),{prior});const d=json(COMPLETION),s=d.completion_scope||{};a.ok('completion_pr_ready',d.completion_status==='pr_review_ready'&&d.final_tag_created===false&&d.main_equals_final_tag===false&&d.final_closure_status==='pending_tag_verification');a.ok('completion_scope',s.controlled_acceptance_write_mode==='controlled_fixture_gate'&&s.acceptance_result_v1_created===true&&s.production_runtime_endpoint_not_claimed===true&&s.controlled_fixture_gate_is_not_production_acceptance_runtime===true&&s.outcome_review_v1_created===false&&s.roi_ledger_v1_created===false&&s.field_memory_record_v1_created===false);return{all_prior_p26_acceptance_passed:true,completion_status:d.completion_status,final_closure_status:d.final_closure_status,expected_final_tag:d.expected_final_tag,final_tag_created:d.final_tag_created,main_equals_final_tag:d.main_equals_final_tag,merge_required_before_complete:d.merge_required_before_complete,tag_verification_required_after_merge:d.tag_verification_required_after_merge,...s}}
function run(name){const a=A();const t={P26_00_POST_P25_BASELINE_FREEZE_INHERITANCE_AUDIT:c00,P26_01_FORMAL_ACCEPTANCE_GATE_CONTRACT_ACCEPTANCE:c01,P26_02_P25_RECEIPT_PLAN_TRANSITION_INPUT_BOUNDARY_ACCEPTANCE:c02,P26_03_FORMAL_ACCEPTANCE_AUTHORIZATION_CONTRACT_ACCEPTANCE:c03,P26_04_FORMAL_EVIDENCE_POLICY_MAPPING_ACCEPTANCE:c04,P26_05_ACCEPTANCE_RESULT_PAYLOAD_SCHEMA_ACCEPTANCE:c05,P26_06_OUTCOME_REVIEW_BOUNDARY_NO_ROI_NO_FIELDMEMORY_POLICY_ACCEPTANCE:c06,P26_07_P25_RECEIPT_NON_BYPASS_ACCEPTANCE:c07,P26_08_FORMAL_ACCEPTANCE_GATE_ACCEPTANCE:c08,P26_09_MISSING_MALFORMED_WRONG_RECEIPT_SOURCE_BLOCKED_ACCEPTANCE:c09,P26_10_AUTHORIZATION_MISSING_NOT_APPROVED_SCOPE_BLOCKED_ACCEPTANCE:c10,P26_11_EVIDENCE_INSUFFICIENT_SIMULATED_DEBUG_BLOCKED_ACCEPTANCE:c11,P26_12_IDEMPOTENCY_DUPLICATE_ACCEPTANCE_CHANGED_PAYLOAD_CONFLICT_ACCEPTANCE:c12,P26_13_EXPLICIT_ACCEPTANCE_RESULT_PERSISTENCE_ACCEPTANCE:c13,P26_14_PERSISTED_ACCEPTANCE_READBACK_NO_ROI_NO_FIELDMEMORY_ACCEPTANCE:c14,P26_15_COMPLETION_REVIEW_ACCEPTANCE:c15};try{a.ok('known_acceptance_entrypoint',typeof t[name]==='function',{name});const result=t[name](a);const s=surface(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...result,...s,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}
module.exports={run};
