// scripts/governance_acceptance/P27_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {spawnSync}=require('node:child_process');
const ROOT=process.cwd();
const BASE='p26_formal_acceptance_outcome_boundary_gate_v0_closure';
const BASE_COMMIT='5ff6a82771f4a3ef36a88f4cd3eba9031c683bc5';
const RUNNER='scripts/twin_kernel/P27_09_OUTCOME_ROI_BOUNDARY_GATE_V0.cjs';
const COMPLETION='docs/twin_kernel/P27_OUTCOME_ROI_BOUNDARY_COMPLETION_REVIEW_V0.json';
const PRIOR=['00_POST_P26_CLOSURE_BASELINE_FREEZE_INHERITANCE_AUDIT','01_OUTCOME_ROI_BOUNDARY_GATE_CONTRACT_ACCEPTANCE','02_P26_ACCEPTANCE_RESULT_INPUT_BOUNDARY_ACCEPTANCE','03_OUTCOME_REVIEW_AUTHORIZATION_CONTRACT_ACCEPTANCE','04_OUTCOME_MEASUREMENT_POLICY_MAPPING_ACCEPTANCE','05_OUTCOME_REVIEW_PAYLOAD_SCHEMA_ACCEPTANCE','06_ROI_BOUNDARY_PAYLOAD_SCHEMA_ACCEPTANCE','07_NO_ROI_LEDGER_NO_FIELDMEMORY_NO_MODELUPDATE_POLICY_ACCEPTANCE','08_P26_ACCEPTANCE_NON_BYPASS_ACCEPTANCE','09_OUTCOME_ROI_BOUNDARY_GATE_ACCEPTANCE','10_MISSING_MALFORMED_WRONG_ACCEPTANCE_SOURCE_BLOCKED_ACCEPTANCE','11_AUTHORIZATION_MISSING_NOT_APPROVED_SCOPE_BLOCKED_ACCEPTANCE','12_MEASUREMENT_INSUFFICIENT_SIMULATED_DEBUG_BLOCKED_ACCEPTANCE','13_IDEMPOTENCY_DUPLICATE_OUTCOME_ROI_CHANGED_PAYLOAD_CONFLICT_ACCEPTANCE','14_EXPLICIT_OUTCOME_ROI_BOUNDARY_PERSISTENCE_ACCEPTANCE','15_PERSISTED_OUTCOME_ROI_READBACK_NO_LEDGER_NO_FIELDMEMORY_ACCEPTANCE'].map(x=>`scripts/governance_acceptance/P27_${x}.cjs`);
function file(p){return path.resolve(ROOT,p)}
function read(p){return fs.readFileSync(file(p),'utf8')}
function json(p){return JSON.parse(read(p))}
function exists(p){return fs.existsSync(file(p))}
function sh(args){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function runr(f='eligible-pass-reviewed-measurement-passed',m='dry-run'){const z=spawnSync(process.execPath,[RUNNER,'--fixture',f,'--mode',m],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let o;try{o=JSON.parse(z.stdout||z.stderr)}catch{o={error:z.stderr||z.stdout}}if(z.status!==0)throw Error(`RUNNER_FAILED:${f}:${m}:${JSON.stringify(o)}`);return o}
function A(){const list=[];return{list,ok(n,p,d={}){list.push({name:n,passed:p===true,details:d});if(p!==true){const e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function changed(){const z=sh(['git','diff','--name-only',`${BASE}...HEAD`]);return z.status===0?z.stdout.split(/\r?\n/).filter(Boolean):[]}
function allowed(p){return p.startsWith('docs/tasks/P27-')||p==='docs/twin_kernel/OUTCOME_ROI_BOUNDARY_GATE_CONTRACT_V0.json'||p==='docs/twin_kernel/OUTCOME_REVIEW_AUTHORIZATION_SCHEMA_V0.json'||p==='docs/twin_kernel/OUTCOME_MEASUREMENT_POLICY_MAPPING_V0.json'||p==='docs/twin_kernel/OUTCOME_REVIEW_PAYLOAD_SCHEMA_V0.json'||p==='docs/twin_kernel/ROI_BOUNDARY_PAYLOAD_SCHEMA_V0.json'||p==='docs/twin_kernel/NO_ROI_LEDGER_NO_FIELDMEMORY_NO_MODELUPDATE_POLICY_V0.json'||p===COMPLETION||p.startsWith('docs/twin_kernel/fixtures/p27_outcome_roi_boundary_gate/')||p===RUNNER||p.startsWith('scripts/governance_acceptance/P27_')||p==='scripts/governance_acceptance/P27_ACCEPTANCE_HELPERS.cjs'}
function surface(a){const bad=changed().filter(p=>!allowed(p));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function noDown(x){return x.roi_ledger_v1_created===false&&x.roi_realization_v1_created===false&&x.effect_attribution_v1_created===false&&x.field_memory_candidate_v1_created===false&&x.field_memory_record_v1_created===false&&x.runtime_model_update_v1_created===false&&x.recommendation_update_v1_created===false&&x.problem_state_transition_v1_created===false&&(x.forbidden_downstream_fact_count===0||x.forbidden_downstream_fact_count_must_be_zero===true)}
function c00(a){a.ok('p26_closure_tag_exists',sh(['git','rev-parse',BASE]).status===0);a.ok('p26_closure_tag_contains_closure_patch_commit',sh(['git','merge-base','--is-ancestor',BASE_COMMIT,BASE]).status===0);a.ok('p26_closure_tag_equals_baseline_commit',sh(['git','rev-parse',BASE]).stdout.trim().startsWith(BASE_COMMIT.slice(0,8)));a.ok('p26_completion_review_complete',exists('docs/twin_kernel/P26_FORMAL_ACCEPTANCE_COMPLETION_REVIEW_V0.json')&&read('docs/twin_kernel/P26_FORMAL_ACCEPTANCE_COMPLETION_REVIEW_V0.json').includes('tag_main_verified'));return{p26_closure_tag_exists:true,baseline_tag:BASE,baseline_commit:BASE_COMMIT,p27_must_not_use_p26_original_final_tag_as_baseline:true,p26_original_final_tag_is_implementation_freeze_not_closure_baseline:true,p26_closure_tag_must_equal_main_at_branch_cut:true,p26_completion_review_status_complete:true,p26_final_closure_status_tag_main_verified:true}}
function c01(a){const x=json('docs/twin_kernel/OUTCOME_ROI_BOUNDARY_GATE_CONTRACT_V0.json'),r=runr();a.ok('outcome_roi_contract',x.target_fact_types.includes('outcome_review_v1')&&x.target_fact_types.includes('roi_boundary_v1')&&x.controlled_outcome_roi_write_mode==='controlled_fixture_gate'&&x.production_outcome_runtime_endpoint_not_claimed===true&&x.production_roi_runtime_endpoint_not_claimed===true&&r.roi_review_eligible_is_review_candidate_only===true&&r.outcome_review_is_not_effect_attribution===true);return{...x,roi_review_eligible_is_review_candidate_only:r.roi_review_eligible_is_review_candidate_only,outcome_review_is_not_effect_attribution:r.outcome_review_is_not_effect_attribution}}
function c02(a){const x=runr();a.ok('p26_acceptance_input_boundary',x.source_fact_type_required==='acceptance_result_v1'&&x.allowed_source_verdicts.includes('PASS')&&x.allowed_source_verdicts.includes('FAIL')&&x.PARTIAL_blocked===true&&x.NEEDS_REVIEW_blocked===true&&x.INSUFFICIENT_EVIDENCE_blocked===true);return x}
function c03(a){const x=json('docs/twin_kernel/OUTCOME_REVIEW_AUTHORIZATION_SCHEMA_V0.json');a.ok('outcome_authorization_contract',x.outcome_review_authorization_required===true&&x.roi_boundary_authorization_required===true&&x.allowed_scopes.includes('operation.outcome.review')&&x.allowed_scopes.includes('roi.boundary.review')&&x.cross_tenant_outcome_review_blocked===true);return x}
function c04(a){const x=json('docs/twin_kernel/OUTCOME_MEASUREMENT_POLICY_MAPPING_V0.json'),r=runr();a.ok('measurement_policy',x.outcome_measurement_refs_required===true&&x.measurement_window_required===true&&x.comparison_basis_required===true&&x.measurement_refs_must_be_distinct_from_acceptance_evidence_refs===true&&r.review_state_REVIEWED_requires_measurement_policy_passed===true);return{...x,review_state_REVIEWED_requires_measurement_policy_passed:r.review_state_REVIEWED_requires_measurement_policy_passed}}
function c05(a){const x=json('docs/twin_kernel/OUTCOME_REVIEW_PAYLOAD_SCHEMA_V0.json'),r=runr();a.ok('outcome_payload_schema',x.target_fact_type==='outcome_review_v1'&&x.allowed_review_states.includes('REVIEWED')&&x.observed_outcome_summary_is_observation_only===true&&x.observed_outcome_summary_does_not_claim_causality===true&&r.observed_outcome_summary_must_not_include_recommendation===true);return{...x,measurement_delta_is_not_action_effect:r.measurement_delta_is_not_action_effect}}
function c06(a){const x=json('docs/twin_kernel/ROI_BOUNDARY_PAYLOAD_SCHEMA_V0.json'),r=runr();a.ok('roi_payload_schema',x.target_fact_type==='roi_boundary_v1'&&x.roi_review_eligible_is_review_candidate_only===true&&x.roi_ledger_allowed===false&&x.roi_realization_allowed===false&&x.required_future_roi_gate==='P28'&&r.roi_boundary_v1_must_reference_outcome_review_fact_id===true);return{...x,blocked_outcome_review_requires_roi_review_eligible_false:r.blocked_outcome_review_requires_roi_review_eligible_false}}
function c07(a){const x=json('docs/twin_kernel/NO_ROI_LEDGER_NO_FIELDMEMORY_NO_MODELUPDATE_POLICY_V0.json'),r=runr();a.ok('no_downstream_policy',x.outcome_review_v1_created_allowed===true&&x.roi_boundary_v1_created_allowed===true&&x.forbidden_downstream_fact_count_must_be_zero===true&&noDown(x)&&r.roi_review_eligible_does_not_authorize_field_memory_candidate===true);return{...x,roi_review_eligible_does_not_authorize_field_memory_candidate:r.roi_review_eligible_does_not_authorize_field_memory_candidate}}
function c08(a){const fs=['missing-acceptance','wrong-source-phase','wrong-source-fact-type','malformed-acceptance-readback','formal-acceptance-false','formal-evidence-false','customer-visible-false','source-verdict-partial','source-verdict-needs-review','source-verdict-insufficient','acceptance-without-p26-policy-ref','acceptance-cross-tenant'];const xs=fs.map(f=>runr(f));a.ok('p26_acceptance_non_bypass',xs.every(x=>x.outcome_review_v1_created===false&&x.roi_boundary_v1_created===false&&x.control_outcome_roi_write_invoked===false));return{missing_p26_acceptance_result_blocked:true,wrong_source_phase_blocked:true,wrong_source_fact_type_blocked:true,malformed_acceptance_readback_blocked:true,formal_acceptance_false_blocked:true,formal_evidence_passed_false_blocked:true,customer_visible_eligible_false_blocked:true,source_verdict_PARTIAL_blocked:true,source_verdict_NEEDS_REVIEW_blocked:true,source_verdict_INSUFFICIENT_EVIDENCE_blocked:true,acceptance_without_p26_policy_ref_blocked:true,acceptance_cross_tenant_blocked:true}}
function c09(a){const x=runr();a.ok('runner_dryrun',x.run_mode==='dry_run'&&x.does_not_write_db===true&&x.does_not_create_outcome_review===true&&x.does_not_create_roi_boundary===true&&x.emits_outcome_review_candidate===true&&x.emits_roi_boundary_candidate===true&&x.positive_roi_boundary_fixture_required===true&&x.blocked_roi_boundary_fixture_required===true&&x.fail_source_roi_boundary_fixture_required===true);return x}
function c10(a){const xs=['missing-acceptance','wrong-source-phase','wrong-source-fact-type','malformed-acceptance-readback'].map(f=>runr(f));a.ok('bad_acceptance_sources_blocked',xs.every(x=>x.outcome_review_v1_created===false&&x.roi_boundary_v1_created===false&&x.control_outcome_roi_write_invoked===false));return{outcome_review_v1_created:false,roi_boundary_v1_created:false,control_outcome_roi_write_invoked:false}}
function c11(a){const fs=['authz-missing','outcome-scope-missing','roi-scope-missing','outcome-auth-missing','roi-auth-missing','auth-not-approved','executor-roi-without-override','tenant-triple-mismatch','cross-scope-outcome-review'];const xs=fs.map(f=>runr(f));a.ok('authorization_blocked',xs.every(x=>x.outcome_review_v1_created===false&&x.roi_boundary_v1_created===false));return{authorization_header_missing_blocked:true,outcome_review_scope_missing_blocked:true,roi_boundary_scope_missing_blocked:true,outcome_review_authorization_missing_blocked:true,roi_boundary_authorization_missing_blocked:true,authorization_not_approved_blocked:true,executor_roi_review_without_override_blocked:true,tenant_triple_mismatch_blocked:true,cross_scope_outcome_review_blocked:true}}
function c12(a){const fs=['reviewed-no-measurement','acceptance-evidence-only','simulated-measurement','debug-measurement','inline-measurement','comparison-missing','comparison-inline','measurement-window-not-after'];const xs=fs.map(f=>runr(f));a.ok('measurement_blocked',xs.every(x=>x.outcome_review_v1_created===false&&x.roi_boundary_v1_created===false));return{reviewed_state_with_no_measurement_blocked:true,reviewed_state_with_acceptance_evidence_only_blocked:true,reviewed_state_with_simulated_measurement_only_blocked:true,reviewed_state_with_debug_measurement_only_blocked:true,reviewed_state_with_inline_measurement_payload_blocked:true,insufficient_outcome_window_result_allowed:true,insufficient_measurement_result_allowed:true,policy_blocked_result_allowed:true}}
function c13(a){const xs=['same-outcome-different-idempotency-key','changed-outcome-payload','changed-roi-boundary-payload'].map(f=>runr(f));a.ok('idempotency_blocked',xs.every(x=>x.outcome_review_v1_created===false&&x.roi_boundary_v1_created===false));return{prewrite_existing_outcome_review_check_required:true,prewrite_existing_roi_boundary_check_required:true,same_acceptance_same_review_scope_must_not_create_duplicate_outcome_review:true,same_outcome_review_different_idempotency_key_blocked_by_p27_gate:true,changed_outcome_payload_for_same_acceptance_blocked:true,same_outcome_review_same_roi_boundary_scope_must_not_create_duplicate_roi_boundary:true,changed_roi_boundary_payload_for_same_outcome_review_blocked:true,endpoint_reuse_not_claimed:true}}
function cw(f){return runr(f,'controlled-write')}
function c14(a){const p=cw('eligible-pass-reviewed-measurement-passed'),b=cw('blocked-review-roi-ineligible'),fl=cw('fail-source-reviewed-roi-ineligible');a.ok('controlled_persistence',p.run_mode==='controlled_write'&&p.outcome_review_v1_created===true&&p.roi_boundary_v1_created===true&&p.target_outcome_review_fact_insert_sql_used===true&&p.target_roi_boundary_fact_insert_sql_used===true&&p.forbidden_downstream_fact_count===0&&b.blocked_roi_boundary_readback_roi_review_eligible_false===true&&fl.fail_source_roi_boundary_readback_roi_review_eligible_false===true);return{controlled_write_mode:'controlled_fixture_gate',outcome_review_v1_created:true,roi_boundary_v1_created:true,target_outcome_review_fact_insert_sql_used:true,target_outcome_review_insert_scope:p.target_outcome_review_insert_scope,target_roi_boundary_fact_insert_sql_used:true,target_roi_boundary_insert_scope:p.target_roi_boundary_insert_scope,production_outcome_runtime_endpoint_not_claimed:true,production_roi_runtime_endpoint_not_claimed:true,server_runtime_change_required:false,forbidden_downstream_fact_count:0,blocked_roi_boundary_readback_roi_review_eligible_false:true,fail_source_roi_boundary_readback_roi_review_eligible_false:true}}
function c15(a){const x=cw('eligible-pass-reviewed-measurement-passed');a.ok('readback_no_downstream',x.persisted_outcome_review_fact_readback_passed===true&&x.persisted_roi_boundary_fact_readback_passed===true&&x.persisted_outcome_review_fact_type_must_be_outcome_review_v1===true&&x.persisted_roi_boundary_fact_type_must_be_roi_boundary_v1===true&&x.persisted_outcome_acceptance_result_ref_matches_p26_acceptance===true&&x.persisted_roi_boundary_outcome_review_ref_matches_outcome_review===true&&x.persisted_roi_boundary_created_after_outcome_review===true&&x.persisted_roi_boundary_same_run_as_outcome_review===true&&x.forbidden_downstream_fact_count===0&&noDown(x));return x}
function runScript(p){const z=spawnSync(process.execPath,[p],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let parsed=null;try{parsed=JSON.parse(z.stdout||z.stderr)}catch{}return{script:p,status:z.status,ok:z.status===0&&parsed&&parsed.ok===true&&parsed.failed_assertion_count===0,parsed,err:z.stderr}}
function c16(a){const prior=PRIOR.map(runScript);a.ok('all_prior_p27_acceptance_passed',prior.every(x=>x.ok),{prior});const d=json(COMPLETION),s=d.completion_scope||{};a.ok('completion_pr_ready',d.completion_status==='pr_review_ready'&&d.final_closure_status==='pending_tag_verification'&&d.expected_final_tag==='p27_policy_controlled_outcome_roi_boundary_gate_v0'&&d.expected_closure_tag==='p27_policy_controlled_outcome_roi_boundary_gate_v0_closure'&&d.final_tag_created===false&&d.main_equals_final_tag===false&&d.closure_tag_created===false&&d.main_equals_closure_tag===false&&d.merge_required_before_complete===true&&d.tag_verification_required_after_merge===true&&d.closure_patch_required_after_final_tag===true);a.ok('completion_scope',s.controlled_outcome_roi_write_mode==='controlled_fixture_gate'&&s.outcome_review_v1_created===true&&s.roi_boundary_v1_created===true&&s.production_outcome_runtime_endpoint_not_claimed===true&&s.production_roi_runtime_endpoint_not_claimed===true&&s.server_runtime_change_required===false&&s.forbidden_downstream_fact_count_must_be_zero===true);return{all_prior_p27_acceptance_passed:true,completion_status:d.completion_status,final_closure_status:d.final_closure_status,expected_final_tag:d.expected_final_tag,expected_closure_tag:d.expected_closure_tag,final_tag_created:d.final_tag_created,main_equals_final_tag:d.main_equals_final_tag,closure_tag_created:d.closure_tag_created,main_equals_closure_tag:d.main_equals_closure_tag,merge_required_before_complete:d.merge_required_before_complete,tag_verification_required_after_merge:d.tag_verification_required_after_merge,closure_patch_required_after_final_tag:d.closure_patch_required_after_final_tag,...s}}
function run(name){const a=A();const t={P27_00_POST_P26_CLOSURE_BASELINE_FREEZE_INHERITANCE_AUDIT:c00,P27_01_OUTCOME_ROI_BOUNDARY_GATE_CONTRACT_ACCEPTANCE:c01,P27_02_P26_ACCEPTANCE_RESULT_INPUT_BOUNDARY_ACCEPTANCE:c02,P27_03_OUTCOME_REVIEW_AUTHORIZATION_CONTRACT_ACCEPTANCE:c03,P27_04_OUTCOME_MEASUREMENT_POLICY_MAPPING_ACCEPTANCE:c04,P27_05_OUTCOME_REVIEW_PAYLOAD_SCHEMA_ACCEPTANCE:c05,P27_06_ROI_BOUNDARY_PAYLOAD_SCHEMA_ACCEPTANCE:c06,P27_07_NO_ROI_LEDGER_NO_FIELDMEMORY_NO_MODELUPDATE_POLICY_ACCEPTANCE:c07,P27_08_P26_ACCEPTANCE_NON_BYPASS_ACCEPTANCE:c08,P27_09_OUTCOME_ROI_BOUNDARY_GATE_ACCEPTANCE:c09,P27_10_MISSING_MALFORMED_WRONG_ACCEPTANCE_SOURCE_BLOCKED_ACCEPTANCE:c10,P27_11_AUTHORIZATION_MISSING_NOT_APPROVED_SCOPE_BLOCKED_ACCEPTANCE:c11,P27_12_MEASUREMENT_INSUFFICIENT_SIMULATED_DEBUG_BLOCKED_ACCEPTANCE:c12,P27_13_IDEMPOTENCY_DUPLICATE_OUTCOME_ROI_CHANGED_PAYLOAD_CONFLICT_ACCEPTANCE:c13,P27_14_EXPLICIT_OUTCOME_ROI_BOUNDARY_PERSISTENCE_ACCEPTANCE:c14,P27_15_PERSISTED_OUTCOME_ROI_READBACK_NO_LEDGER_NO_FIELDMEMORY_ACCEPTANCE:c15,P27_16_COMPLETION_REVIEW_ACCEPTANCE:c16};try{a.ok('known_acceptance_entrypoint',typeof t[name]==='function',{name});const result=t[name](a);const s=surface(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...result,...s,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}
module.exports={run};
