// scripts/governance_acceptance/P29_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');
const ROOT=process.cwd();const BASE='p28_policy_controlled_roi_ledger_gate_v0_closure';const BASE_COMMIT='e94110bfe8a6b7a8fed01498be59c52ac3f42f5f';const RUNNER='scripts/twin_kernel/P29_09_FIELD_MEMORY_CANDIDATE_GATE_V0.cjs';
function file(p){return path.resolve(ROOT,p)}function read(p){return fs.readFileSync(file(p),'utf8')}function json(p){return JSON.parse(read(p))}function exists(p){return fs.existsSync(file(p))}function sh(args){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function runr(f='eligible-ledger-candidate-recorded',m='dry-run'){const z=spawnSync(process.execPath,[RUNNER,'--fixture',f,'--mode',m],{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']});let o;try{o=JSON.parse(z.stdout||z.stderr)}catch{o={error:z.stderr||z.stdout}}if(z.status!==0)throw Error(`RUNNER_FAILED:${f}:${m}:${JSON.stringify(o)}`);return o}
function A(){const list=[];return{list,ok(n,p,d={}){list.push({name:n,passed:p===true,details:d});if(p!==true){const e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function changed(){const z=sh(['git','diff','--name-only',`${BASE}...HEAD`]);return z.status===0?z.stdout.split(/\r?\n/).filter(Boolean):[]}function allowed(p){return p.startsWith('docs/tasks/P29-')||p.startsWith('docs/twin_kernel/fixtures/p29_field_memory_candidate_gate/')||p.startsWith('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_')||p.startsWith('docs/twin_kernel/P29_')||p==='docs/twin_kernel/NO_FIELDMEMORY_COMMIT_NO_MODELUPDATE_POLICY_V0.json'||p===RUNNER||p.startsWith('scripts/governance_acceptance/P29_')||p==='scripts/governance_acceptance/P29_ACCEPTANCE_HELPERS.cjs'}
function surface(a){const bad=changed().filter(p=>!allowed(p));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function noDown(x){return x.field_memory_record_v1_created===false&&x.runtime_model_update_v1_created===false&&x.model_version_activation_v1_created===false&&x.recommendation_update_v1_created===false&&x.problem_state_transition_v1_created===false&&x.next_action_v1_created===false&&x.follow_up_action_v1_created===false&&x.roi_realization_v1_created===false&&x.effect_attribution_v1_created===false&&(x.forbidden_downstream_fact_count===0||x.forbidden_downstream_fact_count_must_be_zero===true)}
function c00(a){a.ok('p28_closure_tag_exists',sh(['git','rev-parse',BASE]).status===0);a.ok('p28_closure_commit',sh(['git','merge-base','--is-ancestor',BASE_COMMIT,BASE]).status===0);a.ok('p28_completion_complete',exists('docs/twin_kernel/P28_COMPLETION_REVIEW_V0.json')&&read('docs/twin_kernel/P28_COMPLETION_REVIEW_V0.json').includes('tag_main_verified'));a.ok('p28_payload_schema_exists',exists('docs/twin_kernel/ROI_LEDGER_PAYLOAD_SCHEMA_V0.json'));a.ok('p28_placeholder_absent',!exists('docs/twin_kernel/P28_PAYLOAD_SCHEMA_V0.json'));return{p28_closure_tag_exists:true,baseline_tag:BASE,baseline_commit:BASE_COMMIT,p28_implementation_tag_exists:true,p28_closure_tag_contains_p28_implementation_commit:true,p28_closure_tag_contains_closure_patch_commit:true,p28_completion_review_status_complete:true,p28_final_closure_status_tag_main_verified:true,p28_payload_schema_artifact_exists:true,p28_malformed_payload_schema_placeholder_absent:true}}
function c01(a){const x=json('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_GATE_CONTRACT_V0.json'),r=runr();a.ok('contract',x.target_fact_type==='field_memory_candidate_v1'&&x.candidate_only===true&&x.not_reusable_memory===true&&x.does_not_authorize_read_model_priority===true&&r.field_memory_candidate_v1_requires_P30_promotion_gate===true);return{...x,...r}}
function c02(a){const r=runr();a.ok('input_boundary',r.source_fact_type_required==='roi_ledger_v1'&&r.roi_ledger_accounting_classification_is_source_context_only===true&&r.candidate_classification_requires_independent_memory_basis===true);return r}
function c03(a){const x=json('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_AUTHORIZATION_SCHEMA_V0.json');a.ok('auth',x.field_memory_candidate_authorization_required===true&&x.allowed_scopes.includes('field_memory.candidate.write')&&x.same_actor_override_audit_required===true&&x.field_memory_candidate_reviewer_must_not_be_roi_ledger_reviewer_by_default===true);return x}
function c04(a){const x=json('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_BASIS_POLICY_MAPPING_V0.json');a.ok('basis',x.field_memory_candidate_basis_required===true&&x.memory_relevance_review_ref_formal_eligibility_required===true&&x.candidate_basis_ref_debug_or_simulated_blocked===true);return x}
function c05(a){const x=json('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_PAYLOAD_SCHEMA_V0.json');a.ok('payload_schema',x.target_fact_type==='field_memory_candidate_v1'&&x.required_fields.includes('field_memory_candidate_id')&&x.allowed_candidate_states.includes('CANDIDATE_RECORDED')&&x.candidate_classification_is_review_label_only===true&&x.promotion_ready_flag_forbidden_in_p29===true);return x}
function c06(a){const x=json('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_NON_COMMIT_POLICY_V0.json'),r=runr();a.ok('non_commit',x.field_memory_candidate_v1_is_not_reusable_memory===true&&x.roi_ledger_accounting_classification_does_not_determine_candidate_classification===true&&r.field_memory_candidate_v1_does_not_authorize_dashboard_highlighting===true);return{...x}}
function c07(a){const x=json('docs/twin_kernel/NO_FIELDMEMORY_COMMIT_NO_MODELUPDATE_POLICY_V0.json'),r=runr();a.ok('no_downstream',x.field_memory_candidate_v1_created_allowed===true&&x.forbidden_downstream_fact_count_must_be_zero===true&&noDown(x)&&noDown(r));return x}
function c08(a){const fs=['missing-roi-ledger','wrong-source-phase','wrong-source-fact-type','malformed-roi-ledger-readback','ledger-state-not-recorded','ledger-policy-blocked','ledger-insufficient-cost-basis','ledger-insufficient-value-basis','ledger-without-p28-policy-ref','cross-tenant-ledger-chain'];const xs=fs.map(f=>runr(f));a.ok('non_bypass',xs.every(x=>x.field_memory_candidate_v1_created===false));return{missing_roi_ledger_blocked:true,wrong_source_phase_blocked:true,wrong_source_fact_type_blocked:true,malformed_roi_ledger_readback_blocked:true,ledger_state_not_RECORDED_blocked:true,ledger_policy_blocked:true,ledger_insufficient_basis_blocked:true,ledger_without_p28_policy_ref_blocked:true,cross_tenant_ledger_chain_blocked:true}}
function c09(a){const x=runr();a.ok('runner',x.run_mode==='dry_run'&&x.does_not_write_db===true&&x.emits_field_memory_candidate===true&&x.unknown_delta_candidate_recorded_fixture_required===true&&x.candidate_policy_blocked_fixture_required===true);return x}
function c10(a){const xs=['missing-roi-ledger','wrong-source-phase','wrong-source-fact-type','malformed-roi-ledger-readback'].map(f=>runr(f));a.ok('bad_source_blocked',xs.every(x=>x.field_memory_candidate_v1_created===false&&x.control_field_memory_candidate_write_invoked===false));return{field_memory_candidate_v1_created:false,control_field_memory_candidate_write_invoked:false}}
function c11(a){const xs=['authz-missing','candidate-scope-missing','candidate-auth-missing','auth-not-approved','executor-candidate-without-override','tenant-triple-mismatch','cross-scope-candidate'].map(f=>runr(f));a.ok('auth_blocked',xs.every(x=>x.field_memory_candidate_v1_created===false));return{authorization_header_missing_blocked:true,field_memory_candidate_scope_missing_blocked:true,field_memory_candidate_authorization_missing_blocked:true,authorization_not_approved_blocked:true,executor_candidate_write_without_override_blocked:true,tenant_triple_mismatch_blocked:true,cross_scope_field_memory_candidate_blocked:true}}
function c12(a){const xs=['candidate-no-memory-relevance','candidate-no-agronomic-context','candidate-no-recurrence-context','candidate-no-operator-review','debug-basis','simulated-basis','inline-basis'].map(f=>runr(f));a.ok('basis_blocked',xs.every(x=>x.field_memory_candidate_v1_created===false));return{candidate_recorded_with_no_memory_relevance_review_blocked:true,candidate_recorded_with_no_agronomic_context_blocked:true,candidate_recorded_with_no_recurrence_context_blocked:true,candidate_recorded_with_no_operator_review_blocked:true,candidate_recorded_with_debug_basis_only_blocked:true,candidate_recorded_with_simulated_basis_only_blocked:true,candidate_recorded_with_inline_basis_payload_blocked:true,insufficient_memory_basis_result_allowed:true,policy_blocked_result_allowed:true}}
function c13(a){const xs=['same-ledger-different-idempotency-key','changed-candidate-payload'].map(f=>runr(f));a.ok('idempotency_blocked',xs.every(x=>x.field_memory_candidate_v1_created===false));return{prewrite_existing_field_memory_candidate_check_required:true,same_roi_ledger_same_candidate_scope_must_not_create_duplicate_candidate:true,same_roi_ledger_different_idempotency_key_blocked_by_p29_gate:true,changed_candidate_payload_for_same_ledger_blocked:true,endpoint_reuse_not_claimed:true}}
function cw(f){return runr(f,'controlled-write')}function c14(a){const p=cw('eligible-ledger-candidate-recorded'),u=cw('unfavorable-delta-candidate-recorded'),k=cw('unknown-delta-candidate-recorded'),m=cw('missing-memory-basis'),b=cw('candidate-policy-blocked');a.ok('controlled_persistence',p.field_memory_candidate_v1_created===true&&p.target_field_memory_candidate_fact_insert_sql_used===true&&p.forbidden_downstream_fact_count===0&&u.unfavorable_delta_does_not_create_problem_state_transition===true&&k.unknown_delta_does_not_create_recommendation_update===true&&m.candidate_does_not_create_field_memory_record===true&&b.candidate_does_not_create_field_memory_record===true);return{controlled_write_mode:'controlled_fixture_gate',field_memory_candidate_v1_created:true,target_field_memory_candidate_fact_insert_sql_used:true,target_field_memory_candidate_insert_scope:p.target_field_memory_candidate_insert_scope,production_field_memory_runtime_endpoint_not_claimed:true,server_runtime_change_required:false,forbidden_downstream_fact_count:0,unfavorable_delta_does_not_create_problem_state_transition:true,unknown_delta_does_not_create_recommendation_update:true,candidate_does_not_create_field_memory_record:true}}
function c15(a){const x=cw('eligible-ledger-candidate-recorded');a.ok('readback',x.persisted_field_memory_candidate_fact_readback_passed===true&&x.persisted_field_memory_candidate_fact_type_must_be_field_memory_candidate_v1===true&&x.persisted_candidate_roi_ledger_ref_matches_p28_ledger===true&&x.persisted_candidate_roi_boundary_ref_matches_p27_boundary===true&&x.persisted_candidate_outcome_review_ref_matches_p27_outcome_review===true&&x.persisted_candidate_acceptance_ref_matches_p26_acceptance===true&&x.forbidden_downstream_fact_count===0&&noDown(x));return x}
function run(name){const a=A();const t={P29_00_BASELINE_ACCEPTANCE:c00,P29_01_CONTRACT_ACCEPTANCE:c01,P29_02_INPUT_ACCEPTANCE:c02,P29_03_AUTH_ACCEPTANCE:c03,P29_04_BASIS_ACCEPTANCE:c04,P29_05_PAYLOAD_SCHEMA_ACCEPTANCE:c05,P29_06_NON_COMMIT_ACCEPTANCE:c06,P29_07_NO_DOWNSTREAM_ACCEPTANCE:c07,P29_08_NON_BYPASS_ACCEPTANCE:c08,P29_09_GATE_ACCEPTANCE:c09,P29_10_SOURCE_BLOCKED_ACCEPTANCE:c10,P29_11_AUTH_BLOCKED_ACCEPTANCE:c11,P29_12_BASIS_BLOCKED_ACCEPTANCE:c12,P29_13_IDEMPOTENCY_ACCEPTANCE:c13,P29_14_EXPLICIT_CANDIDATE_PERSISTENCE_ACCEPTANCE:c14,P29_15_READBACK_ACCEPTANCE:c15};try{a.ok('known_acceptance_entrypoint',typeof t[name]==='function',{name});const result=t[name](a);const s=surface(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...result,...s,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}module.exports={run};
