// scripts/governance_acceptance/P30_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');const path=require('node:path');const {spawnSync}=require('node:child_process');
const ROOT=process.cwd();const BASE='p29_policy_controlled_field_memory_candidate_gate_v0_closure';const BASE_COMMIT='99bab9088290acf9acd624eb64609f9375b52cfb';const RUNNER='scripts/twin_kernel/P30_09_FIELD_MEMORY_RECORD_GATE_V0.cjs';
function file(p){return path.resolve(ROOT,p)}function read(p){return fs.readFileSync(file(p),'utf8')}function json(p){return JSON.parse(read(p))}function exists(p){return fs.existsSync(file(p))}function sh(argr){return spawnSync(args[0],args.slice(1),{cwd:ROOT,encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function runr(f='eligible-candidate-record-committed',m='dry-run'){const z=spawnSync(process.execPath,[RUNNER','--fixture',f,'--mode',m],{cwd:ROOT,encoding:'utf8'});let o;try{o=JSON.parse(z.stdout||z.stderr)}catch{o={error:z.stderr||z.stdout}}if(z.status!==0)throw Error('RUNNER_FAILED:'+f+':'+m+':'+JSON.stringify(o));return o}
function A(){const list=[];return{list,ok(n,p,d={}){list.push({name:n,passed:p===true,details:d});if(p!==true){const e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function changed(){const z=sh(['git','diff','--name-only',BASE+'...HEAD']);return z.status===0?z.stdout.split(/\r\?\n/).filter(Boolean):[]}function allowed(p){return p.startsWith('docs/tasks/P30-')||p.startsWith('docs/twin_kernel/fixtures/p30_field_memory_record_gate/')||p.startsWith('docs/twin_kernel/FIELD_MEMORY_RECORD_')||p.startsWith('docs/twin_kernel/P30_')||p==='docs/twin_kernel/NO_MODELUPDATE_NO_RECOMMENDATION_NO_ACTION_POLICY_V0.json'||p===RUNNER||p.startsWith('scripts/governance_acceptance/P30_')||p==='scripts/governance_acceptance/P30_ACCEPTANCE_HELPERS.cjs'}function surface(a){const bad=changed().filter(p=>!allowed(p));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function noDown(x){return x.runtime_model_update_v1_created===false&&x.model_version_activation_v1_created===false&&x.recommendation_update_v1_created===false&&x.problem_state_transition_v1_created===false&&x.next_action_v1_created===false&&x.follow_up_action_v1_created===false&&x.operator_instruction_v1_created===false&&x.roi_realization_v1_created===false&&x.effect_attribution_v1_created===false&&(x.forbidden_downstream_fact_count===0||x.forbidden_downstream_fact_count_must_be_zero===true)}
function c00(a){const d=exists('docs/twin_kernel/P29_FIELD_MEMORY_CANDIDATE_COMPLETION_REVIEW_V0.json')?json('docs/twin_kernel/P29_FIELD_MEMORY_CANDIDATE_COMPLETION_REVIEW_V0.json'):{};a.ok('p29_closure_tag_exists',sh(['git','rev-parse',BASE]).status===0);a.ok('p29_closure_commit',sh(['git','merge-base','--is-ancestor',BASE_COMMIT,BASE]).status===0);a.ok('p29_completion_complete',d.completion_status==='complete'&&d.final_closure_status==='tag_main_verified');a.ok('p29_candidate_schema_exists',exists('docs/twin_kernel/FIELD_MEMORY_CANDIDATE_PAYLOAD_SCHEMA_V0.json'));return{p29_closure_tag_exists:true,baseline_tag:BASE,baseline_commit:BASE_COMMIT,p29_completion_review_status_complete:true,p29_final_closure_status_tag_main_verified:true,p29_field_memory_candidate_schema_artifact_exists:true,p29_completion_review_closure_commit_pending_warning:d.closure_commit==='pending_merge_commit',p29_completion_review_closure_commit_must_equal_baseline_commit:false}}
function c01(a){const x=json('docs/twin_kernel/FIELD_MEMORY_RECORD_GATE_CONTRACT_V0.json'),r=runr();a.ok('contract',x.target_fact_type==='field_memory_record_v1'&&x.record_only===true&&x.not_learning===true&&r.field_memory_record_v1_requires_separate_model_update_gate===true);return{...x,...r}}
function c02(a){const r=runr();a.ok('input',r.source_fact_type_required==='field_memory_candidate_v1'&&r.target_fact_type==='field_memory_record_v1');return r}
function c03(a){const x=json('docs/twin_kernel/FIELD_MEMORY_RECORD_AUTHORIZATION_SCHEMA_V0.json');a.ok('auth',x.field_memory_record_authorization_required===true&&x.allowed_scopes.includes('field_memory.record.promote')&&x.same_actor_override_audit_required===true);return x}
function c04(a){const x=json('docs/twin_kernel/FIELD_MEMORY_RECORD_PROMOTION_BASIS_POLICY_MAPPING_V0.json');a.ok('basis',x.field_memory_promotion_basis_required===true&&x.promotion_review_ref_required===true&&x.inline_promotion_basis_payload_blocked===true);return x}
function c05(a){const x=json('docs/twin_kernel/FIELD_MEMORY_RECORD_PAYLOAD_SCHEMA_V0.json');a.ok('payload_schema',x.target_payload_allowed_record_states.length===1&&x.target_payload_allowed_record_states[0]==='RECORD_COMMITTED'&&x.gate_result_allowed_states.includes('PROMOTION_BLOCKED')&&x.PROMOTION_BLOCKED_must_not_be_persisted_as_field_memory_record_v1===true&&x.record_scope_required===true&&x.reuse_boundary_does_not_authorize_runtime_use===true&&x.record_summary_is_not_general_rule===true);return x}
function c06(a){const x=json('docs/twin_kernel/FIELD_MEMORY_RECORD_NON_LEARNING_POLICY_V0.json'),r=runr();a.ok('non_learning',x.field_memory_record_v1_is_not_model_update===true&&x.PROMOTION_BLOCKED_must_not_create_field_memory_record_v1===true&&r.record_summary_is_not_recommendation===true);return x}
function c07(a){const x=json('docs/twin_kernel/NO_MODELUPDATE_NO_RECOMMENDATION_NO_ACTION_POLICY_V0.json'),r=runr();a.ok('no_downstream',x.forbidden_downstream_fact_count_must_be_zero===true&&noDown(x)&&noDown(r));return x}
function c08(a){const fs=['missing-field-memory-candidate','wrong-source-phase','wrong-source-fact-type','malformed-candidate-readback','candidate-state-not-recorded','candidate-insufficient-basis-blocked','candidate-policy-blocked','candidate-without-p29-policy-ref','cross-tenant-candidate-chain','candidate-source-refs-mismatch'];const xs=fs.map(f=>runr(f));a.ok('non_bypass',xs.every(x=>x.field_memory_record_v1_created===false));return{missing_field_memory_candidate_blocked:true,wrong_source_phase_blocked:true,wrong_source_fact_type_blocked:true,malformed_candidate_readback_blocked:true,candidate_state_not_CANDIDATE_RECORDED_blocked:true,candidate_insufficient_memory_basis_blocked:true,candidate_policy_blocked:true,candidate_without_p29_policy_ref_blocked:true,cross_tenant_candidate_chain_blocked:true,candidate_source_refs_mismatch_blocked:true}}
function c09(a){const x=run();a.ok('runner',x.run_mode==='dry_run'&&x.does_not_write_db===true&&x.emits_field_memory_record===true);return x}
function c10(a){const xs=['missing-field-memory-candidate','wrong-source-phase','wrong-source-fact-type','malformed-candidate-readback'].map(f=>run(f));a.ok('bad_source_blocked',xs.every(x=>x.field_memory_record_v1_created===false&&x.control_field_memory_record_write_invoked===false));return{field_memory_record_v1_created:false,control_field_memory_record_write_invoked:false}}
function c11(a){const xs=['authz-missing','record-scope-missing','record-auth-missing','auth-not-approved','candidate-reviewer-promote-without-override','executor-record-without-override','tenant-triple-mismatch','cross-scope-record'].map(f=>runn(f));a.ok('auth_blocked',xs.every(x=>x.field_memory_record_v1_created===false));return{authorization_header_missing_blocked:true,field_memory_record_scope_missing_blocked:true,field_memory_record_authorization_missing_blocked:true,authorization_not_approved_blocked:true,candidate_reviewer_promote_without_override_blocked:true,executor_record_write_without_override_blocked:true,tenant_triple_mismatch_blocked:true,cross_scope_field_memory_record_blocked:true}}
function c12(a){const xs=['record-no-promotion-review','record-no-memory-record-policy','record-no-agronomic-approval','record-no-operator-ack','record-no-reuse-boundary','debug-basis','simulated-basis','inline-basis','missing-promotion-basis','promotion-policy-blocked'].map(f=>run(f));a.ok('basis_blocked',xs.every(x=>x.field_memory_record_v1_created===false));return{record_commit_with_no_promotion_review_blocked:true,record_commit_with_no_memory_record_policy_blocked:true,record_commit_with_no_agronomic_reviewer_approval_blocked:true,record_commit_with_no_operator_context_ack_blocked:true,record_commit_with_no_reuse_boundary_review_blocked:true,record_commit_with_debug_basis_only_blocked:true,record_commit_with_simulated_basis_only_blocked:true,record_commit_with_inline_basis_payload_blocked:true,insufficient_promotion_basis_result_allowed:true,promotion_policy_blocked_result_allowed:true,insufficient_or_blocked_result_must_not_create_record:true}}
function c13(a){const xs=['same-candidate-different-idempotency-key','changed-record-payload'].map(f=>runœ(f));a.ok('idempotency_blocked',xs.every(x=>x.field_memory_record_v1_created===false));return{prewrite_existing_field_memory_record_check_required:true,same_candidate_same_record_scope_must_not_create_duplicate_record:true,same_candidate_different_idempotency_key_blocked_by_p30_gate:true,changed_record_payload_for_same_candidate_blocked:true,endpoint_reuse_not_claimed:true}}
function cw(f){return runr(f,'controlled-write')}function c14(a){const p=cw('eligible-candidate-record-committed'),c=cw('cautionary-candidate-record-committed'),ac=cw('accounting-candidate-record-committed');a.ok('controlled_persistence',p.field_memory_record_v1_created===true&&p.target_field_memory_record_fact_insert_sql_used===true&&p.forbidden_downstream_fact_count===0&&c.record_does_not_create_problem_state_transition===true&&ac.record_does_not_create_recommendation_update===true);return{controlled_write_mode:'controlled_fixture_gate',field_memory_record_v1_created:true,target_field_memory_record_fact_insert_sql_used:true,target_field_memory_record_insert_scope:p.target_field_memory_record_insert_scope,production_field_memory_runtime_endpoint_not_claimed:true,server_runtime_change_required:false,forbidden_downstream_fact_count:0,record_does_not_create_runtime_model_update:true,record_does_not_create_model_version_activation:true,record_does_not_create_recommendation_update:true,record_does_not_create_problem_state_transition:true,record_does_not_create_next_action:true,record_does_not_create_operator_instruction:true}}
function c15(a){const x=cw('eligible-candidate-record-committed');a.ok('readback',x.persisted_field_memory_record_fact_readback_passed===true&&x.persisted_field_memory_record_fact_type_must_be_field_memory_record_v1===true&&x.persisted_record_candidate_ref_matches_p29_candidate===true&&x.persisted_record_roi_ledger_ref_matches_p28_ledger===true&&x.persisted_record_roi_boundary_ref_matches_p27_boundary===true&&x.persisted_record_outcome_review_ref_matches_p27_outcome_review===true&&x.persisted_record_acceptance_ref_matches_p26_acceptance===true&&x.forbidden_downstream_fact_count===0&&noDown(x));return x}
function run(name){const a=A();const t={P30_00_BASELINE_ACCEPTANCE:c00,P30_01_CONTRACT_ACCEPTANCE:c01,P30_02_INPUT_ACCEPTANCE:c02,P30_03_AUTH_ACCEPTANCE:c03,P30_04_BASIS_ACCEPTANCE:c04,P30_05_PAYLOAD_SCHEMA_ACCEPTANCE:c05,P30_06_NON_LEARNING_ACCEPTANCE:c06,P30_07_NO_DOWNSTREAM_ACCEPTANCE:c07,P30_08_NON_BYPASS_ACCEPTANCE:c08,P30_09_GATE_ACCEPTANCE:c09,P30_10_SOURCE_BLOCKED_ACCEPTANCE:c10,P30_11_AUTH_BLOCKED_ACCEPTANCE:c11,P30_12_BASIS_BLOCKED_ACCEPTANCE:c12,P30_13_IDEMPOTENCY_ACCEPTANCE:c13,P30_14_EXPLICIT_RECORD_PERSISTENCE_ACCEPTANCE:c14,P30_15_READBACK_ACCEPTANCE:c15};try{a.ok('known_acceptance_entrypoint',typeof t[name]==='function',{name});const result=t[name](a);const s=surface(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...result,...s,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,acssertions:a.list},null,2));process.exit(1)}}module.exports={run};
