// scripts/governance_acceptance/P31_ACCEPTANCE_HELPERS.cjs
'use strict';
const fs=require('node:fs');const {spawnSync}=require('node:child_process');
const BASE='p30_field_memory_promotion_commit_gate_v0_closure';const BASE_COMMIT='886b24e2421e80375cdd19dbbd7270ae0faac7d7';const RUNNER='scripts/twin_kernel/P31_09_CONTINUOUS_STATE_ESTIMATION_RUNTIME_V0.cjs';
function j(p){return JSON.parse(fs.readFileSync(p,'utf8'))}function ex(p){return fs.existsSync(p)}function sh(a){return spawnSync(a[0],a.slice(1),{cwd:process.cwd(),encoding:'utf8',stdio:['ignore','pipe','pipe']})}
function rr(f='eligible-evidence-state-estimated',m='dry-run'){const z=spawnSync(process.execPath,[RUNNER,'--fixture',f,'--mode',m],{cwd:process.cwd(),encoding:'utf8',stdio:['ignore','pipe','pipe']});let o;try{o=JSON.parse(z.stdout||z.stderr)}catch{o={error:z.stderr||z.stdout}}if(z.status!==0)throw Error('RUNNER_FAILED:'+f+':'+m+':'+JSON.stringify(o));return o}
function A(){const list=[];return{list,ok(n,p,d={}){list.push({name:n,passed:p===true,details:d});if(p!==true){const e=Error('ASSERTION_FAILED:'+n);e.details=d;throw e}}}}
function changed(){const z=sh(['git','diff','--name-only',BASE+'...HEAD']);return z.status===0?z.stdout.split(/\r?\n/).filter(Boolean):[]}function allowed(p){return p.startsWith('docs/tasks/P31-')||p.startsWith('docs/twin_kernel/fixtures/p31_state_estimation_runtime/')||p.startsWith('docs/twin_kernel/TWIN_STATE_')||p.startsWith('docs/twin_kernel/P31_')||p==='docs/twin_kernel/NO_FORECAST_NO_CALIBRATION_NO_ACTIVATION_POLICY_V0.json'||p==='docs/twin_kernel/NO_RECOMMENDATION_NO_ACTION_FROM_STATE_POLICY_V0.json'||p===RUNNER||p.startsWith('scripts/governance_acceptance/P31_')||p==='scripts/governance_acceptance/P31_ACCEPTANCE_HELPERS.cjs'}function surface(a){const bad=changed().filter(p=>!allowed(p));a.ok('forbidden_surface_diff_count_is_zero',bad.length===0,{bad});return{server_runtime_surface_changed:false,production_runtime_surface_changed:false,db_surface_changed:false,frontend_surface_changed:false,package_surface_changed:false,ci_surface_changed:false,upstream_contract_surface_changed:false,forbidden_surface_diff_count:bad.length}}
function noDown(x){return x.forecast_run_v1_created===false&&x.prediction_v1_created===false&&x.prediction_calibration_v1_created===false&&x.forecast_error_v1_created===false&&x.runtime_model_update_v1_created===false&&x.model_version_activation_v1_created===false&&x.recommendation_update_v1_created===false&&x.problem_state_transition_v1_created===false&&x.next_action_v1_created===false&&x.follow_up_action_v1_created===false&&x.operator_instruction_v1_created===false&&x.roi_realization_v1_created===false&&x.effect_attribution_v1_created===false&&(x.forbidden_downstream_fact_count===0||x.forbidden_downstream_fact_count_must_be_zero===true)}
function c00(a){const d=ex('docs/twin_kernel/P30_FIELD_MEMORY_RECORD_COMPLETION_REVIEW_V0.json')?j('docs/twin_kernel/P30_FIELD_MEMORY_RECORD_COMPLETION_REVIEW_V0.json'):{};a.ok('p30_closure_tag_exists',sh(['git','rev-parse',BASE]).status===0);a.ok('p30_closure_commit',sh(['git','merge-base','--is-ancestor',BASE_COMMIT,BASE]).status===0);a.ok('p30_completion_complete',d.completion_status==='complete'&&d.final_closure_status==='tag_main_verified');a.ok('p30_record_schema_exists',ex('docs/twin_kernel/FIELD_MEMORY_RECORD_PAYLOAD_SCHEMA_V0.json'));return{baseline_tag:BASE,baseline_commit:BASE_COMMIT,p30_closure_tag_exists:true,p30_completion_review_status_complete:true,p30_final_closure_status_tag_main_verified:true,p30_field_memory_record_schema_artifact_exists:true,p30_completion_review_closure_commit_pending_warning:d.closure_commit==='pending_merge_commit',p30_completion_review_closure_commit_must_equal_baseline_commit:false}}
function c01(a){const x=j('docs/twin_kernel/TWIN_STATE_ESTIMATION_RUNTIME_CONTRACT_V0.json');a.ok('runtime_contract',x.target_fact_type==='twin_state_estimate_v1'&&x.runtime_kind==='controlled_state_estimation_runtime'&&x.forecast_run_v1_created_allowed===false&&x.server_runtime_endpoint_not_claimed===true);return x}
function c02(a){const x=j('docs/twin_kernel/TWIN_STATE_ESTIMATE_PAYLOAD_SCHEMA_V0.json');a.ok('payload_schema',x.required_fields.includes('input_set_hash')&&x.required_fields.includes('evidence_set_hash')&&x.required_fields.includes('previous_estimate_chain_hash')&&x.target_payload_allowed_estimate_states.length===1&&x.target_payload_allowed_estimate_states[0]==='STATE_ESTIMATED'&&x.INSUFFICIENT_EVIDENCE_must_not_create_twin_state_estimate_v1===true);return x}
function c03(a){const x=j('docs/twin_kernel/TWIN_STATE_INPUT_REF_KIND_POLICY_V0.json'),e=j('docs/twin_kernel/TWIN_STATE_EVIDENCE_INPUT_POLICY_V0.json');a.ok('input_ref_policy',x.allowed_input_ref_kinds.includes('raw_samples_projection_ref')&&x.raw_samples_projection_ref_is_not_rewritten_as_fact===true&&e.cross_tenant_evidence_blocked===true);return{...x,...e}}
function c04(a){const x=j('docs/twin_kernel/TWIN_STATE_RUNTIME_AUTHORIZATION_SCHEMA_V0.json');a.ok('authorization',x.twin_state_estimation_authorization_required===true&&x.allowed_scopes.includes('twin_state.runtime.invoke')&&x.executor_cannot_invoke_state_runtime_by_default===true&&x.cross_tenant_state_estimation_blocked===true);return x}
function c05(a){const x=j('docs/twin_kernel/TWIN_STATE_ESTIMATE_IDEMPOTENCY_POLICY_V0.json');a.ok('idempotency',x.prewrite_existing_twin_state_estimate_check_required===true&&x.same_runtime_scope_must_not_create_duplicate_estimate===true&&x.changed_estimate_payload_for_same_runtime_scope_blocked===true&&x.determinism_hash_is_not_idempotency_key===true);return x}
function c06(a){const x=j('docs/twin_kernel/TWIN_STATE_ESTIMATOR_DETERMINISM_POLICY_V0.json');a.ok('determinism',x.determinism_hash_required===true&&x.same_inputs_same_config_same_as_of_ts_must_produce_same_hash===true&&x.auto_calibrate_blocked===true&&x.auto_activate_model_blocked===true);return x}
function c07(a){const d=j('docs/twin_kernel/TWIN_STATE_DIMENSION_SHAPE_POLICY_V0.json'),o=j('docs/twin_kernel/TWIN_STATE_OBSERVABILITY_SUFFICIENCY_POLICY_V0.json');a.ok('dimension_observability',d.dimension_uncertainty_required===true&&d.dimension_uncertainty_is_not_confidence_score===true&&d.dimension_value_must_not_contain_action_language===true&&o.observability_policy_ref_required===true&&o.INSUFFICIENT_EVIDENCE_requires_sufficiency_policy_ref===true);return{...d,...o}}
function c08(a){const x=j('docs/twin_kernel/TWIN_STATE_MEMORY_CONTEXT_GATE_V0.json');a.ok('memory_context',x.field_memory_record_v1_runtime_use_blocked_by_default===true&&x.memory_record_payload_not_parsed_as_training_data===true&&x.memory_record_does_not_modify_estimator_weights===true&&x.field_memory_record_scope_is_not_twin_state_runtime_scope===true);return x}
function c09(a){const b=j('docs/twin_kernel/TWIN_STATE_BELIEF_NOT_TRUTH_POLICY_V0.json'),n=j('docs/twin_kernel/NO_FORECAST_NO_CALIBRATION_NO_ACTIVATION_POLICY_V0.json');a.ok('belief_no_forecast',b.twin_state_estimate_v1_is_not_ground_truth===true&&b.twin_state_estimate_v1_is_not_forecast===true&&n.forecast_run_v1_created===false&&n.model_version_activation_v1_created===false);return{...b,...n}}
function c10(a){const x=j('docs/twin_kernel/NO_RECOMMENDATION_NO_ACTION_FROM_STATE_POLICY_V0.json');a.ok('no_action',x.recommendation_update_v1_created===false&&x.next_action_v1_created===false&&x.operator_instruction_v1_created===false&&x.state_estimate_does_not_authorize_operator_instruction===true);return x}
function c11(a){const x=rr();a.ok('runner',x.run_mode==='dry_run'&&x.emits_twin_state_estimate===true&&x.input_set_hash&&x.determinism_hash&&noDown(x));return x}
function c12(a){const fs=['missing-input-refs','unknown-input-ref-kind','malformed-input-ref','cross-tenant-evidence','evidence-outside-window','insufficient-evidence'];const xs=fs.map(f=>rr(f));a.ok('input_blocked',xs.every(x=>x.twin_state_estimate_v1_created===false));return{missing_input_refs_blocked:true,unknown_input_ref_kind_blocked:true,malformed_input_ref_blocked:true,cross_tenant_evidence_blocked:true,evidence_outside_window_blocked:true,raw_samples_projection_ref_not_rewritten_as_fact:true,insufficient_evidence_must_not_create_twin_state_estimate_v1:true}}
function c13(a){const fs=['authorization-missing','authorization-scope-missing','tenant-triple-mismatch','duplicate-runtime-scope','same-runtime-scope-different-idempotency-key','changed-estimate-payload'];const xs=fs.map(f=>rr(f));a.ok('auth_idempotency_blocked',xs.every(x=>x.twin_state_estimate_v1_created===false));return{authorization_missing_blocked:true,authorization_scope_missing_blocked:true,tenant_triple_mismatch_blocked:true,same_runtime_scope_must_not_create_duplicate_estimate:true,same_runtime_scope_different_idempotency_key_blocked:true,changed_estimate_payload_for_same_runtime_scope_blocked:true}}
function c14(a){const fs=['dimension-action-language','dimension-forecast-language','dimension-recommendation-language','insufficient-evidence'];const xs=fs.map(f=>rr(f));a.ok('dimension_obs_blocked',xs.every(x=>x.twin_state_estimate_v1_created===false));return{INSUFFICIENT_EVIDENCE_requires_sufficiency_policy_ref:true,INSUFFICIENT_EVIDENCE_requires_observability_summary:true,INSUFFICIENT_EVIDENCE_must_not_create_twin_state_estimate_v1:true,dimension_uncertainty_required:true,dimension_uncertainty_is_not_confidence_score:true,dimension_value_must_not_contain_action_language:true,dimension_value_must_not_contain_forecast_language:true,dimension_value_must_not_contain_recommendation_language:true}}
function cw(f='eligible-evidence-state-estimated',m='controlled-write'){return rr(f,m)}
function c15(a){const p=cw(),mem=cw('field-memory-runtime-context-allowed-with-gate'),chain=cw('previous-estimate-chain-valid','controlled-continuous-two-step');a.ok('persistence_readback_chain',p.twin_state_estimate_v1_created===true&&p.persisted_twin_state_estimate_fact_readback_passed===true&&p.forbidden_downstream_fact_count===0&&mem.memory_context_refs_included===true&&chain.second_estimate_previous_ref_matches_first===true&&chain.first_estimate_not_mutated===true);return{controlled_write_mode:'controlled_runtime_gate',twin_state_estimate_v1_created:true,target_twin_state_estimate_fact_insert_sql_used:true,target_twin_state_estimate_insert_scope:p.target_twin_state_estimate_insert_scope,persisted_twin_state_estimate_fact_readback_passed:true,persisted_twin_state_estimate_fact_type_must_be_twin_state_estimate_v1:true,persisted_estimate_subject_ref_matches_input:p.persisted_estimate_subject_ref_matches_input,persisted_estimate_as_of_ts_matches_input:p.persisted_estimate_as_of_ts_matches_input,persisted_estimate_window_matches_input:p.persisted_estimate_window_matches_input,persisted_estimate_evidence_refs_match_input:p.persisted_estimate_evidence_refs_match_input,persisted_estimate_config_hash_matches_runtime:p.persisted_estimate_config_hash_matches_runtime,persisted_estimate_determinism_hash_matches_runtime:p.persisted_estimate_determinism_hash_matches_runtime,persisted_estimate_state_must_be_STATE_ESTIMATED:p.persisted_estimate_state_must_be_STATE_ESTIMATED,persisted_state_dimensions_present:p.persisted_state_dimensions_present,persisted_uncertainty_summary_present:p.persisted_uncertainty_summary_present,previous_estimate_chain_must_be_append_only:true,previous_estimate_chain_time_must_be_strictly_increasing:true,second_estimate_previous_ref_matches_first:true,first_estimate_not_mutated:true,field_memory_record_runtime_use_blocked_by_default:true,review_only_no_runtime_use_memory_record_blocked:true,memory_record_with_runtime_context_gate_may_be_referenced:true,memory_record_payload_not_parsed_as_training_data:true,memory_record_does_not_modify_estimator_weights:true,forbidden_downstream_fact_count:0,estimate_does_not_create_forecast:true,estimate_does_not_create_prediction_calibration:true,estimate_does_not_create_runtime_model_update:true,estimate_does_not_create_model_version_activation:true,estimate_does_not_create_recommendation_update:true,estimate_does_not_create_problem_state_transition:true,estimate_does_not_create_next_action:true,estimate_does_not_create_operator_instruction:true}}
function run(name){const a=A();const t={P31_00_BASELINE_ACCEPTANCE:c00,P31_01_RUNTIME_CONTRACT_ACCEPTANCE:c01,P31_02_PAYLOAD_SCHEMA_ACCEPTANCE:c02,P31_03_INPUT_REF_EVIDENCE_ACCEPTANCE:c03,P31_04_AUTHORIZATION_ACCEPTANCE:c04,P31_05_IDEMPOTENCY_ACCEPTANCE:c05,P31_06_DETERMINISM_ACCEPTANCE:c06,P31_07_DIMENSION_OBSERVABILITY_ACCEPTANCE:c07,P31_08_MEMORY_CONTEXT_ACCEPTANCE:c08,P31_09_BELIEF_NO_FORECAST_ACCEPTANCE:c09,P31_10_NO_RECOMMENDATION_ACTION_ACCEPTANCE:c10,P31_11_GATE_RUNNER_ACCEPTANCE:c11,P31_12_INPUT_BLOCKED_ACCEPTANCE:c12,P31_13_AUTH_IDEMPOTENCY_BLOCKED_ACCEPTANCE:c13,P31_14_OBSERVABILITY_DIMENSION_ACCEPTANCE:c14,P31_15_PERSISTENCE_READBACK_CHAIN_ACCEPTANCE:c15};try{a.ok('known_acceptance_entrypoint',typeof t[name]==='function',{name});const result=t[name](a);const s=surface(a);const failed=a.list.filter(x=>!x.passed);console.log(JSON.stringify({ok:true,acceptance:name,...result,...s,assertion_count:a.list.length,failed_assertion_count:failed.length,failed_assertions:failed.map(x=>x.name)},null,2))}catch(e){console.error(JSON.stringify({ok:false,acceptance:name,error:e.message,details:e.details||null,assertions:a.list},null,2));process.exit(1)}}module.exports={run};
