#!/usr/bin/env node
"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),cp=require("node:child_process"),os=require("node:os"),crypto=require("node:crypto");
const ROOT=path.resolve(__dirname,"../.."),C="docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-FROZEN-V13-REQUALIFICATION-CONTRACT-V1.json",BASE="7555e38f80872cebc3d5c73c95983a31fee3cab0",FROZEN="3d5fd13c8f5babd2edc5107206f43a5e5d12eb4a",HISTORY="5e162fceb5758aa3eaf7894a474a5886fa069057",Q="docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-QUALIFICATION-CONTROL-PLANE-V1.json",E="docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-QUALIFICATION-EVIDENCE-REGISTRY-V1.json",M="scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_V13_RUNTIME_HARNESS_RESOLVER_MIGRATION_V1.cjs",D="scripts/governance_acceptance/VERIFY_MCFT_CAP_09_AM22_GFS_DIAGNOSTIC_SUCCESSOR_V1.cjs",P="scripts/governance_acceptance/PREFLIGHT_MCFT_CAP_09_ALL_BLOCKERS_V1.cjs";
const EXPECTED={"contract_id": "MCFT_CAP09_FROZEN_V13_REQUALIFICATION_V1", "adopted_base_sha": "7555e38f80872cebc3d5c73c95983a31fee3cab0", "frozen_runtime_sha": "3d5fd13c8f5babd2edc5107206f43a5e5d12eb4a", "historical_migration_subject_sha": "5e162fceb5758aa3eaf7894a474a5886fa069057", "historical_migration_proof_scope": "BF1D_ONLY_NOT_CURRENT_RUNTIME_QUALIFICATION", "historical_assertions_preserved": true, "current_runtime_resolver": "V13_RUNTIME_SEMANTIC_CLOSURE", "runtime_path_count": 108, "legacy_path_count": 125, "harness_path_count": 21, "historical_harness_addition": "scripts/runtime_acceptance/ACCEPTANCE_MCFT_CAP_09_V13_HOLISTIC_SCHEMA_POSTGRES.ts", "isolated_checks": ["V13_AUTONOMOUS_FORCING_FOUNDATION", "V13_HOLISTIC_SCHEMA", "V13_NEXT_TICK_VIABILITY", "EA5C1_DURABLE_RAW_RESTRICTED_INGRESS"], "isolated_workflow": ".github/workflows/mcft-cap-09-frozen-v13-isolated-requalification-v1.yml", "exact_successor_paths": [".github/workflows/mcft-cap-09-frozen-v13-isolated-requalification-v1.yml", ".github/workflows/mcft-cap-09-qualification-control-plane-v1.yml", "docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-FROZEN-V13-REQUALIFICATION-CONTRACT-V1.json", "docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-QUALIFICATION-CONTROL-PLANE-V1.json", "docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-QUALIFICATION-EVIDENCE-REGISTRY-V1.json", "scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_V1.cjs", "scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_V13_RUNTIME_HARNESS_RESOLVER_MIGRATION_V1.cjs", "scripts/governance_acceptance/PREFLIGHT_MCFT_CAP_09_ALL_BLOCKERS_V1.cjs", "scripts/governance_acceptance/RECORD_MCFT_CAP_09_FROZEN_V13_ISOLATED_EVIDENCE_V1.cjs", "scripts/governance_acceptance/VERIFY_MCFT_CAP_09_AM22_GFS_DIAGNOSTIC_SUCCESSOR_V1.cjs", "scripts/governance_acceptance/VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs"], "stages": ["SUCCESSOR_SUBJECT_PRE_MERGE", "POST_MERGE_V13_QUALIFICATION"], "production_runtime_mutation_authorized": false, "historical_evidence_promoted_to_current": false, "production_tests_authorized": false, "formal_v5_arm_authorized": false, "a0_authorized": false, "o00_authorized": false};
const SUCCESSOR_CHECK={"check_id": "FROZEN_V13_REQUALIFICATION_SUCCESSOR_ENGINEERING_ONLY", "owner": "MCFT_CAP09_FROZEN_RUNTIME_QUALIFICATION", "generation_scope": ["V13", "FORMAL_V5"], "authority_refs": ["docs/digital_twin/mcft/cap_09/GEOX-MCFT-CAP-09-FROZEN-V13-REQUALIFICATION-CONTRACT-V1.json"], "resolver_ids": ["FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1"], "historical_evidence_policy": "IMMUTABLE_PREDECESSOR_REPLAY_NO_LIVE_SUCCESS_REUSE", "execution_workflow": ".github/workflows/mcft-cap-09-frozen-v13-isolated-requalification-v1.yml", "execution_workflow_status": "ISOLATED_QUALIFICATION_ONLY", "fail_policy": "FAIL_CLOSED_EXACT_PATHS_FROZEN_RUNTIME_AND_NO_PRODUCTION_EFFECTS", "carry_forward_policy": "NONE", "requalification_triggers": ["FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1"], "applicable_stages": ["SUCCESSOR_SUBJECT_PRE_MERGE", "POST_MERGE_V13_QUALIFICATION"], "carry_forward_evidence_id": null, "diagnostic_command": "node scripts/governance_acceptance/VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs"};
const git=(...args)=>cp.execFileSync("git",args,{cwd:ROOT,encoding:"utf8",stdio:["ignore","pipe","pipe"],maxBuffer:16*1024*1024}).trim();
const read=p=>JSON.parse(fs.readFileSync(path.join(ROOT,p),"utf8"));
const hash=x=>crypto.createHash("sha256").update(x).digest("hex");
function ancestor(a,b){return cp.spawnSync("git",["merge-base","--is-ancestor",a,b],{cwd:ROOT}).status===0;}
function replay(sha,script,args=[]){const temp=fs.mkdtempSync(path.join(os.tmpdir(),"frozen-v13-replay-")),dir=path.join(temp,"checkout");let attached=false;try{git("worktree","add","--detach",dir,sha);attached=true;return JSON.parse(cp.execFileSync(process.execPath,[script,...args],{cwd:dir,encoding:"utf8",timeout:180000,maxBuffer:8*1024*1024}));}finally{if(attached)git("worktree","remove","--force",dir);fs.rmSync(temp,{recursive:true,force:true});}}
function validatePartition(runtime,legacy,harness,frozenDigest,currentDigest){
 assert.equal(runtime.length,108,"FROZEN_RUNTIME_COUNT");assert.equal(legacy.length,125,"CURRENT_LEGACY_COUNT");assert.equal(harness.length,21,"CURRENT_HARNESS_COUNT");
 const added=[M,".github/workflows/mcft-cap-09-post-merge-v13-control-plane-v1.yml",".github/workflows/mcft-cap-09-qualification-control-plane-v1.yml","scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_CHECK_APPLICABILITY_V1.cjs"];
 const historicalHarness=harness.filter(x=>!added.includes(x));assert.equal(historicalHarness.length,17,"EXACT_CURRENT_LEGACY_HARNESS_COUNT");
 assert(historicalHarness.includes(EXPECTED.historical_harness_addition),"SCHEMA_HARNESS_CLASSIFICATION_REQUIRED");
 assert.equal(runtime.some(x=>harness.includes(x)),false,"RUNTIME_HARNESS_OVERLAP");
 assert.deepEqual([...new Set([...runtime,...historicalHarness])].sort(),[...legacy].sort(),"EXACT_PARTITION_REQUIRED");
 assert(runtime.every(x=>!x.startsWith("scripts/")&&!x.startsWith(".github/")),"HARNESS_IN_RUNTIME_FORBIDDEN");
 assert.equal(frozenDigest,currentDigest,"FROZEN_RUNTIME_DIGEST_DRIFT");
}
function verifyMigration(){
 assert.deepEqual(read(C),EXPECTED,"QUALIFICATION_CONTRACT_CHANGED");assert(ancestor(FROZEN,"HEAD"));assert(ancestor(BASE,"HEAD"));
 const planner=require("./PLAN_MCFT_CAP_09_CHECK_APPLICABILITY_V1.cjs"),a=read(Q),r=planner.resolveDependencyResolvers(ROOT,a);assert.deepEqual(r.errors,[]);
 const ids=["V13_RUNTIME_SEMANTIC_CLOSURE","V13_AUTONOMOUS_FORCING_IMPORT_CLOSURE","V13_QUALIFICATION_HARNESS_CLOSURE"];
 for(const id of ids)assert.deepEqual(r.resolved[id].missing,[]);
 const [runtime,legacy,harness]=ids.map(id=>r.resolved[id].paths);
 const old=JSON.parse(git("show",BASE+":"+Q));for(const id of ids)assert.deepEqual(a.dependency_resolvers[id],old.dependency_resolvers[id],"RESOLVER_SCOPE_CHANGED");
 const frozen=planner.dependencyDigestForPaths(ROOT,FROZEN,runtime,false),current=planner.dependencyDigestForPaths(ROOT,git("rev-parse","HEAD"),runtime,true);assert.deepEqual(frozen.missing,[]);assert.deepEqual(current.missing,[]);
 validatePartition(runtime,legacy,harness,frozen.digest,current.digest);
 const history=replay(HISTORY,M);assert.equal(history.status,"PASS");assert.equal(history.legacy_path_count,124);assert.equal(history.runtime_path_count,108);assert.equal(history.current_harness_path_count,17);
 return {status:"PASS",historical_migration_replayed_at:HISTORY,historical_proof_not_promoted:true,frozen_runtime_sha:FROZEN,runtime_path_digest:current.digest,runtime_path_count:108,current_legacy_path_count:125,current_harness_path_count:21,exact_partition_proven:true,production_runtime_mutation:false,provider_request_count:0,formal_v5_arm:false,a0_bootstrap:false,o00_started:false};
}
function verifySuccessor(){
 assert.deepEqual(read(C),EXPECTED);assert(ancestor(BASE,"origin/main"),"BASE_NOT_ADOPTED");
 assert.deepEqual(git("status","--porcelain").split(/\r?\n/).filter(x=>x&&!x.startsWith("?? acceptance-output/")),[],"DIRTY_SOURCE");
 const changes=git("diff","--name-status",BASE,"HEAD").split(/\r?\n/).filter(Boolean).map(x=>{const [status,p]=x.split("\t");return {status,p};});
 assert.deepEqual(changes.map(x=>x.p).sort(),EXPECTED.exact_successor_paths,"EXACT_QUALIFICATION_PATHS_REQUIRED");
 for(const x of changes)assert.equal(x.status,[Q,E,M,D,P,".github/workflows/mcft-cap-09-qualification-control-plane-v1.yml"].includes(x.p)?"M":"A");
 const oldDiag=git("show",BASE+":"+D)+"\n",route=' if(fs.existsSync(path.join(ROOT,"scripts/governance_acceptance/VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs")))return require("./VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs").verifySuccessor();\n';
 assert.equal(fs.readFileSync(path.join(ROOT,D),"utf8"),oldDiag.replace("function verifyDiagnosticSuccessor(){","function verifyDiagnosticSuccessor(){\n"+route),"PREDECESSOR_ASSERTIONS_CHANGED");
 const oldMigration=git("show",BASE+":"+M)+"\n",migrationRoute='if (fs.existsSync(path.join(ROOT, "'+C+'"))) { write(require("./VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs").verifyMigration()); } else try {';
 assert.equal(fs.readFileSync(path.join(ROOT,M),"utf8"),oldMigration.replace("\ntry {","\n"+migrationRoute),"HISTORICAL_ASSERTIONS_CHANGED");
 const oldPreflight=git("show",BASE+":"+P)+"\n";
 const registrationRoute="  const registrationInvocation = registry.frozen_v13_requalification_v1\n    ? { status: 0, stdout: JSON.stringify(require(\"./VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs\").replayHistoricalRegistration()) }\n    : cp.spawnSync(";
 assert.equal(fs.readFileSync(path.join(ROOT,P),"utf8"),oldPreflight.replace("  const valid = adjudications.filter((row) => row.valid);","  const frozenSection = registry.frozen_v13_requalification_v1;\n  if (frozenSection && fs.existsSync(path.join(ROOT, \"scripts/governance_acceptance/VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs\"))) {\n    const fresh = require(\"./VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs\").resolveFreshEvidence(decision, frozenSection, stage, head);\n    if (fresh.status === \"PASS\") return fresh;\n    if (fresh.reason_code !== \"NO_VALID_REQUALIFICATION_EVIDENCE\") return fresh;\n  }\n"+"  const valid = adjudications.filter((row) => row.valid);").replace("  const registrationInvocation = cp.spawnSync(",registrationRoute),"EXISTING_EVIDENCE_VALIDATION_CHANGED");
 const oldWorkflow=git("show",BASE+":"+".github/workflows/mcft-cap-09-qualification-control-plane-v1.yml")+"\n";
 assert.equal(fs.readFileSync(path.join(ROOT,".github/workflows/mcft-cap-09-qualification-control-plane-v1.yml"),"utf8"),oldWorkflow.replace("          const v13Checks = [","          const frozenVerifierPath = 'scripts/governance_acceptance/VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs';\n          const frozenVerifier = fs.existsSync(frozenVerifierPath) ? require(process.cwd() + '/' + frozenVerifierPath) : null;\n          if (frozenVerifier) frozenVerifier.verifySuccessor();\n          const expectedQualificationWorkflow = (id, historicalWorkflow) =>\n            frozenVerifier && frozenVerifier.EXPECTED.isolated_checks.includes(id) && frozenVerifier.EXPECTED.stages.includes(plan.stage)\n              ? frozenVerifier.EXPECTED.isolated_workflow : historicalWorkflow;\n          const v13Checks = [").replace("if (row.execution_workflow !== workflow) throw new Error(`${id}_WORKFLOW_MISMATCH`);","if (row.execution_workflow !== expectedQualificationWorkflow(id, workflow)) throw new Error(`${id}_WORKFLOW_MISMATCH`);").replace("if (ea5c1.execution_workflow !== '.github/workflows/mcft-cap-09-ea5c1-durable-raw-restricted-ingress.yml')","if (ea5c1.execution_workflow !== expectedQualificationWorkflow('EA5C1_DURABLE_RAW_RESTRICTED_INGRESS', '.github/workflows/mcft-cap-09-ea5c1-durable-raw-restricted-ingress.yml'))"),"QCP_WORKFLOW_EXISTING_ASSERTIONS_CHANGED");
 const before=JSON.parse(git("show",BASE+":"+Q)),after=read(Q);assert.equal(after.checks.length,46);assert.deepEqual(after.checks.at(-1),SUCCESSOR_CHECK);assert.deepEqual(after.dependency_resolvers.FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1,{kind:"EXACT_PATH_SET",paths:EXPECTED.exact_successor_paths});
 for(const row of after.checks.slice(0,-1)){const prior=before.checks.find(x=>x.check_id===row.check_id);const expected=structuredClone(prior);
  if(EXPECTED.isolated_checks.includes(row.check_id))expected.execution_workflows_by_stage={...expected.execution_workflows_by_stage,...Object.fromEntries(EXPECTED.stages.map(s=>[s,EXPECTED.isolated_workflow]))};
  if(row.check_id==="V13_RUNTIME_HARNESS_RESOLVER_MIGRATION"){expected.historical_evidence_policy="IMMUTABLE_5E162_HISTORICAL_REPLAY_AND_CURRENT_3D5FD13_FROZEN_PARTITION_NO_BF1D_PROMOTION";expected.fail_policy="FAIL_CLOSED_HISTORICAL_ASSERTIONS_AND_EXACT_CURRENT_FROZEN_RUNTIME_PARTITION";expected.authority_refs.push(C);expected.diagnostic_command="node scripts/governance_acceptance/VERIFY_MCFT_CAP_09_FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1.cjs --migration";}
  assert.deepEqual(row,expected,"UNAUTHORIZED_QCP_CHECK_CHANGE:"+row.check_id);
 }
 const stripped=structuredClone(after);stripped.checks=before.checks;delete stripped.dependency_resolvers.FROZEN_V13_REQUALIFICATION_SUCCESSOR_V1;assert.deepEqual(stripped,before,"QCP_RESOLVERS_CHANGED");
 const registry=read(E),priorRegistry=JSON.parse(git("show",BASE+":"+E));delete registry.frozen_v13_requalification_v1;assert.deepEqual(registry,priorRegistry,"HISTORICAL_REGISTRY_CHANGED");
 const predecessor=replay(BASE,D);assert.equal(predecessor.status,"PASS");const migration=verifyMigration();
 return {status:"PASS",baseline:BASE,changedPaths:[...new Set([...predecessor.changedPaths,...EXPECTED.exact_successor_paths])],migration,qualification_scope:predecessor.qualification_scope,frozen_requalification_scope:"FROZEN_RUNTIME_ISOLATED_REQUALIFICATION_ONLY",production_runtime_start_authorized:false,formal_v5_arm_authorized:false,a0_authorized:false,o00_authorized:false};
}
function resolveFreshEvidence(decision,section,stage,head){
 if(!EXPECTED.isolated_checks.includes(decision.check_id))return {status:"FAIL",reason_code:"NO_VALID_REQUALIFICATION_EVIDENCE"};
 if(section.contract_ref!==C||!Array.isArray(section.entries))return {status:"FAIL",reason_code:"FROZEN_REQUALIFICATION_SECTION_INVALID"};
 const matches=section.entries.filter(e=>e.check_id===decision.check_id&&e.stage===stage);if(!matches.length)return {status:"FAIL",reason_code:"NO_VALID_REQUALIFICATION_EVIDENCE"};
 try{assert.deepEqual(read(C),EXPECTED);assert.equal(matches.length,1,"FRESH_EVIDENCE_AMBIGUOUS");const e=matches[0],s=e.run_snapshot;
 const bindingFields=["evidence_id","check_id","stage","subject_sha","dependency_digest","run_snapshot","job_name","contract_ref"];
 assert.equal(e.immutable_binding_sha256,hash(JSON.stringify(bindingFields.map(k=>e[k]??null))),"FRESH_EVIDENCE_BINDING_MISMATCH");
 assert.equal(e.contract_ref,C);assert.equal(e.dependency_digest,decision.dependency_digest);assert(ancestor(e.subject_sha,head));
 assert.equal(s.head_sha,e.subject_sha);assert.equal(s.base_sha,BASE);assert.equal(s.event,"pull_request");assert.equal(s.workflow_path,EXPECTED.isolated_workflow);assert.equal(s.conclusion,"success");assert(Number.isSafeInteger(s.run_id)&&s.run_id>0);assert.equal(e.job_name,decision.check_id);assert(EXPECTED.stages.includes(stage));
 assert.equal(decision.execution_workflow,EXPECTED.isolated_workflow);assert(ancestor(BASE,e.subject_sha));
 const runtime=require("./PLAN_MCFT_CAP_09_CHECK_APPLICABILITY_V1.cjs").resolveDependencyResolvers(ROOT,read(Q)).resolved.V13_RUNTIME_SEMANTIC_CLOSURE.paths;
 assert.equal(git("diff","--name-only",FROZEN,head,"--",...runtime),"","FRESH_RUNTIME_DRIFT");
 return {status:"PASS",reason_code:"FROZEN_RUNTIME_EXACT_ISOLATED_RUN_AND_BINDING_VALID",evidence_id:e.evidence_id,run_id:s.run_id,subject_sha:e.subject_sha,dependency_digest:e.dependency_digest,candidates:[]};
 }catch{return {status:"FAIL",reason_code:"FROZEN_REQUALIFICATION_EVIDENCE_INVALID",candidates:[]};}
}
function replayHistoricalRegistration(){verifySuccessor();return replay(BASE,"scripts/governance_acceptance/ACCEPTANCE_MCFT_CAP_09_AM19_HISTORICAL_LOGICAL_SUCCESSOR_VERIFIED_DELIVERY_REGISTRATION_V1.cjs",["--require-qcp-registered"]);}
module.exports={replayHistoricalRegistration,EXPECTED,validatePartition,verifyMigration,verifySuccessor,resolveFreshEvidence};
if(require.main===module)console.log(JSON.stringify(process.argv.includes("--migration")?verifyMigration():verifySuccessor(),null,2));
