'use strict';
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const path=require('node:path');
const {validateRepoRelativeModulePathV1}=require('./workflow_port_bundle_contract_v1.cjs');
function canonical(v){if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;if(v&&typeof v==='object')return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;return JSON.stringify(v);}
function digest(v){return`sha256:${crypto.createHash('sha256').update(canonical(v)).digest('hex')}`;}
function validateExecutionAuthorityV1(authority,input){assert.ok(authority&&typeof authority==='object'&&!Array.isArray(authority),'EXECUTION_AUTHORITY_OBJECT_REQUIRED');assert.equal(authority.record_status,'SINGLE_FINAL_FORMAL_RUN_DATABASE_EXECUTION_AUTHORIZED');assert.equal(authority.single_run_database_execution_authorized,true);assert.equal(authority.database_execution_workflow_authorized,true);assert.equal(authority.workflow_dispatch_execution_authorized,true);assert.equal(authority.dual_run_ci_authorized,false);assert.equal(authority.cross_run_comparator_authorized,false);assert.equal(authority.final_ledger_settlement_authorized,false);assert.equal(authority.exact_subject_sha,input.exactSubjectSha,'EXECUTION_AUTHORITY_SUBJECT');assert.match(input.exactSubjectSha,/^[0-9a-f]{40}$/);assert.ok(['RUN_A','RUN_B'].includes(input.runLabel),'RUN_LABEL');assert.equal(authority.authorized_run_label,input.runLabel,'EXECUTION_AUTHORITY_RUN_LABEL');assert.equal(authority.operational_run_instance_id,input.operationalRunInstanceId,'EXECUTION_AUTHORITY_INSTANCE');assert.match(input.operationalRunInstanceId,/^[A-Za-z0-9._:-]{8,128}$/);const modulePath=validateRepoRelativeModulePathV1(authority.port_bundle_path);assert.match(authority.port_bundle_blob_sha,/^[0-9a-f]{40}$/,'PORT_BUNDLE_BLOB_SHA');assert.match(authority.workflow_blob_sha,/^[0-9a-f]{40}$/,'WORKFLOW_BLOB_SHA');assert.match(authority.expires_at,/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/,'AUTHORITY_EXPIRY');assert.ok(Date.parse(authority.expires_at)>Date.now(),'EXECUTION_AUTHORITY_EXPIRED');return{authority,module_path:modulePath,authority_digest:digest(authority)};}
function gateFromEnvironmentV1({root=path.resolve(__dirname,'../../..'),writeOutput=true}={}){const authorityPath=String(process.env.MCFT_CAP08_EXECUTION_AUTHORITY_PATH||'').trim();const exactSubjectSha=String(process.env.MCFT_CAP08_EXACT_SUBJECT_SHA||'').trim();const runLabel=String(process.env.MCFT_CAP08_RUN_LABEL||'').trim();const operationalRunInstanceId=String(process.env.MCFT_CAP08_OPERATIONAL_RUN_INSTANCE_ID||'').trim();assert.match(authorityPath,/^docs\/digital_twin\/mcft\/cap_08\/[A-Za-z0-9_.-]+\.json$/,'EXECUTION_AUTHORITY_PATH');const absolute=path.join(root,authorityPath);const authority=JSON.parse(fs.readFileSync(absolute,'utf8'));const result=validateExecutionAuthorityV1(authority,{exactSubjectSha,runLabel,operationalRunInstanceId});const normalizedPath=path.join(root,'acceptance-output/MCFT_CAP_08_S6_NORMALIZED_EXECUTION_AUTHORITY.json');fs.mkdirSync(path.dirname(normalizedPath),{recursive:true});fs.writeFileSync(normalizedPath,JSON.stringify(result.authority,null,2)+'\n');if(writeOutput&&process.env.GITHUB_OUTPUT){fs.appendFileSync(process.env.GITHUB_OUTPUT,[`authorized=true`,`exact_subject_sha=${exactSubjectSha}`,`run_label=${runLabel}`,`operational_run_instance_id=${operationalRunInstanceId}`,`authority_path=${authorityPath}`,`authority_digest=${result.authority_digest}`,`port_bundle_path=${result.module_path}`,`port_bundle_blob_sha=${authority.port_bundle_blob_sha}`,`workflow_blob_sha=${authority.workflow_blob_sha}`].join('\n')+'\n');}return{...result,normalized_path:normalizedPath};}
if(require.main===module){try{const result=gateFromEnvironmentV1();console.log(JSON.stringify({status:'AUTHORIZED',authority_digest:result.authority_digest,module_path:result.module_path},null,2));}catch(error){console.error(error);process.exitCode=1;}}
module.exports={canonical,digest,validateExecutionAuthorityV1,gateFromEnvironmentV1};
