// apps/server/src/projections/root_zone_irrigation_scenario_set_v1.ts
// Purpose: project deterministic root-zone irrigation scenario sets into a scoped read index.
// Boundary: projection table helper only; no domain calculation, routes, actions, or customer exposure.

import type { Pool, PoolClient } from "pg";
import type { RootZoneIrrigationScenarioSetPayloadV1 } from "../domain/soil_water/root_zone_irrigation_scenario_builder_v1.js";

type DbConn = Pool | PoolClient;
export const ROOT_ZONE_IRRIGATION_SCENARIO_SET_INDEX_V1_TABLE = "root_zone_irrigation_scenario_set_index_v1";
export type RootZoneIrrigationScenarioSetFactV1 = { type: "root_zone_irrigation_scenario_set_v1"; payload: RootZoneIrrigationScenarioSetPayloadV1 };
export type RootZoneIrrigationScenarioSetIndexV1 = RootZoneIrrigationScenarioSetPayloadV1 & { source_fact_id: string | null; updated_at?: string };
const text = (v: unknown) => String(v ?? "").trim();
const textNull = (v: unknown) => text(v) || null;
const num = (v: unknown) => { const n = typeof v === "number" ? v : Number(v); return Number.isFinite(n) ? n : 0; };
const iso = (v: unknown) => v instanceof Date ? v.toISOString() : text(v);
function arr(v: unknown): unknown[] { if (Array.isArray(v)) return v; if (typeof v !== "string" || !v.trim()) return []; try { const p = JSON.parse(v); return Array.isArray(p) ? p : []; } catch { return []; } }
function obj(v: unknown): Record<string, unknown> { if (v && typeof v === "object" && !Array.isArray(v)) return v as Record<string, unknown>; if (typeof v !== "string" || !v.trim()) return {}; try { const p = JSON.parse(v); return p && typeof p === "object" && !Array.isArray(p) ? p : {}; } catch { return {}; } }
const jsonArr = (v: unknown) => JSON.stringify(arr(v));
const jsonObj = (v: unknown) => JSON.stringify(obj(v));

export function mapRootZoneIrrigationScenarioSetRowV1(row: Record<string, unknown>): RootZoneIrrigationScenarioSetIndexV1 {
  return { scenario_set_id: text(row.scenario_set_id), tenant_id: text(row.tenant_id), project_id: text(row.project_id), group_id: text(row.group_id), field_id: text(row.field_id), zone_id: text(row.zone_id), source_forecast_id: text(row.source_forecast_id), source_forecast_ref: text(row.source_forecast_ref), baseline_mode: "FORECAST_BASELINE", comparison_mode: "HYPOTHETICAL_IRRIGATION_OPTIONS", horizon_days: num(row.horizon_days), root_zone_depth_cm: num(row.root_zone_depth_cm), root_zone_available_water_capacity_mm: num(row.root_zone_available_water_capacity_mm), baseline_summary: obj(row.baseline_summary_json) as RootZoneIrrigationScenarioSetPayloadV1["baseline_summary"], options: arr(row.options_json) as RootZoneIrrigationScenarioSetPayloadV1["options"], input_status: text(row.input_status) as RootZoneIrrigationScenarioSetPayloadV1["input_status"], blocking_reasons: arr(row.blocking_reasons_json).map(String), calculation_inputs: obj(row.calculation_inputs_json), derivation: obj(row.derivation_json), confidence: obj(row.confidence_json) as RootZoneIrrigationScenarioSetPayloadV1["confidence"], determinism_hash: text(row.determinism_hash), source_fact_id: textNull(row.source_fact_id), computed_at: iso(row.computed_at), updated_at: row.updated_at == null ? undefined : iso(row.updated_at) };
}
export async function ensureRootZoneIrrigationScenarioSetIndexV1(pool: DbConn): Promise<void> {
  await pool.query(`CREATE TABLE IF NOT EXISTS public.root_zone_irrigation_scenario_set_index_v1 (scenario_set_id text PRIMARY KEY, tenant_id text NOT NULL, project_id text NOT NULL, group_id text NOT NULL, field_id text NOT NULL, zone_id text NOT NULL, source_forecast_id text NOT NULL, source_forecast_ref text NOT NULL, baseline_mode text NOT NULL, comparison_mode text NOT NULL, horizon_days integer NOT NULL, root_zone_depth_cm double precision NOT NULL, root_zone_available_water_capacity_mm double precision NOT NULL, baseline_summary_json jsonb NOT NULL DEFAULT '{}'::jsonb, options_json jsonb NOT NULL DEFAULT '[]'::jsonb, input_status text NOT NULL, blocking_reasons_json jsonb NOT NULL DEFAULT '[]'::jsonb, calculation_inputs_json jsonb NOT NULL DEFAULT '{}'::jsonb, derivation_json jsonb NOT NULL DEFAULT '{}'::jsonb, confidence_json jsonb NOT NULL DEFAULT '{}'::jsonb, determinism_hash text NOT NULL, source_fact_id text, computed_at timestamptz NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_root_zone_irrigation_scenario_set_index_v1_scope_latest ON public.root_zone_irrigation_scenario_set_index_v1 (tenant_id, project_id, group_id, field_id, zone_id, computed_at DESC)`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_root_zone_irrigation_scenario_set_index_v1_field_latest ON public.root_zone_irrigation_scenario_set_index_v1 (tenant_id, project_id, group_id, field_id, computed_at DESC)`);
  await pool.query(`CREATE INDEX IF NOT EXISTS idx_root_zone_irrigation_scenario_set_index_v1_source_forecast ON public.root_zone_irrigation_scenario_set_index_v1 (source_forecast_id)`);
}
export async function upsertRootZoneIrrigationScenarioSetIndexV1(pool: DbConn, payload: RootZoneIrrigationScenarioSetPayloadV1, sourceFactId: string | null): Promise<RootZoneIrrigationScenarioSetIndexV1> {
  await ensureRootZoneIrrigationScenarioSetIndexV1(pool);
  const r = await pool.query(`INSERT INTO public.root_zone_irrigation_scenario_set_index_v1 (scenario_set_id, tenant_id, project_id, group_id, field_id, zone_id, source_forecast_id, source_forecast_ref, baseline_mode, comparison_mode, horizon_days, root_zone_depth_cm, root_zone_available_water_capacity_mm, baseline_summary_json, options_json, input_status, blocking_reasons_json, calculation_inputs_json, derivation_json, confidence_json, determinism_hash, source_fact_id, computed_at, updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14::jsonb,$15::jsonb,$16,$17::jsonb,$18::jsonb,$19::jsonb,$20::jsonb,$21,$22,$23,now()) ON CONFLICT (scenario_set_id) DO UPDATE SET tenant_id=EXCLUDED.tenant_id, project_id=EXCLUDED.project_id, group_id=EXCLUDED.group_id, field_id=EXCLUDED.field_id, zone_id=EXCLUDED.zone_id, source_forecast_id=EXCLUDED.source_forecast_id, source_forecast_ref=EXCLUDED.source_forecast_ref, baseline_mode=EXCLUDED.baseline_mode, comparison_mode=EXCLUDED.comparison_mode, horizon_days=EXCLUDED.horizon_days, root_zone_depth_cm=EXCLUDED.root_zone_depth_cm, root_zone_available_water_capacity_mm=EXCLUDED.root_zone_available_water_capacity_mm, baseline_summary_json=EXCLUDED.baseline_summary_json, options_json=EXCLUDED.options_json, input_status=EXCLUDED.input_status, blocking_reasons_json=EXCLUDED.blocking_reasons_json, calculation_inputs_json=EXCLUDED.calculation_inputs_json, derivation_json=EXCLUDED.derivation_json, confidence_json=EXCLUDED.confidence_json, determinism_hash=EXCLUDED.determinism_hash, source_fact_id=EXCLUDED.source_fact_id, computed_at=EXCLUDED.computed_at, updated_at=now() RETURNING *`, [payload.scenario_set_id, payload.tenant_id, payload.project_id, payload.group_id, payload.field_id, payload.zone_id, payload.source_forecast_id, payload.source_forecast_ref, payload.baseline_mode, payload.comparison_mode, payload.horizon_days, payload.root_zone_depth_cm, payload.root_zone_available_water_capacity_mm, jsonObj(payload.baseline_summary), jsonArr(payload.options), payload.input_status, jsonArr(payload.blocking_reasons), jsonObj(payload.calculation_inputs), jsonObj(payload.derivation), jsonObj(payload.confidence), payload.determinism_hash, sourceFactId, payload.computed_at]);
  return mapRootZoneIrrigationScenarioSetRowV1(r.rows[0] as Record<string, unknown>);
}
