// apps/server/src/projections/soil_water_potential_estimate_v1.ts
// Purpose: build and project H31 deterministic soil water potential estimates from sensing windows and hydraulic profiles.
// Boundary: Estimate-layer source-index only; no forecast, scenario, recommendation, approval, operation plan, dispatch, ROI, or customer exposure.

import type { Pool, PoolClient } from "pg";
import { createHash, randomUUID } from "node:crypto";
import type { SoilMoistureSensingWindowIndexV1 } from "./soil_moisture_sensing_window_v1.js";
import type { SoilHydraulicProfileIndexV1 } from "./soil_hydraulic_profile_v1.js";
import { ensureSoilHydraulicProfileIndexV1 } from "./soil_hydraulic_profile_v1.js";
import { estimateVanGenuchtenMatricPotentialV1 } from "../domain/soil_water/van_genuchten_v1.js";

export const SOIL_WATER_POTENTIAL_ESTIMATE_INDEX_V1_TABLE = "soil_water_potential_estimate_index_v1";
export const SOIL_WATER_POTENTIAL_MODEL_VERSION_V1 = "van_genuchten_soil_water_potential_v1";
export type SoilWaterPotentialClassV1 = "SATURATED_OR_NEAR_SATURATED" | "READILY_AVAILABLE" | "LIMITED_AVAILABLE" | "STRESS" | "UNKNOWN";
export type SoilWaterPotentialInputStatusV1 = "ESTIMATED" | "INSUFFICIENT_PROFILE" | "INVALID_INPUT" | "BLOCKED_BY_DATA_QUALITY" | "UNKNOWN";
export type SoilWaterPotentialEstimatePayloadV1 = { estimate_id: string; tenant_id: string; project_id: string; group_id: string; field_id: string; zone_id: string; layer_depth_cm: number; source_window_id: string | null; source_profile_id: string | null; observed_theta: number | null; theta_unit: "m3_m3" | "percent"; normalized_theta_m3_m3: number | null; matric_potential_kpa: number | null; matric_potential_class: SoilWaterPotentialClassV1; available_water_fraction: number | null; root_zone_weight: number; input_status: SoilWaterPotentialInputStatusV1; blocking_reasons: string[]; hydraulic_profile_ref: string | null; data_quality_ref: string | null; evidence_refs: string[]; calculation_inputs: Record<string, unknown>; derivation: Record<string, unknown>; confidence: { level: "LOW" | "MEDIUM" | "HIGH"; score: number; basis: string }; computed_at: string; determinism_hash: string; };
export type SoilWaterPotentialEstimateFactV1 = { type: "soil_water_potential_estimate_v1"; payload: SoilWaterPotentialEstimatePayloadV1 };
export type SoilWaterPotentialEstimateIndexV1 = SoilWaterPotentialEstimatePayloadV1 & { source_fact_id: string | null; updated_at?: string };
type DbConn = Pool | PoolClient;
function text(v: unknown): string | null { const s = String(v ?? "").trim(); return s || null; }
function num(v: unknown): number | null { if (v == null || v === "") return null; const n = typeof v === "number" ? v : Number(v); return Number.isFinite(n) ? n : null; }
function round6(v: number): number { return Math.round(v * 1_000_000) / 1_000_000; }
function iso(v: unknown): string { const s = text(v); if (!s) return ""; const ms = Date.parse(s); return Number.isFinite(ms) ? new Date(ms).toISOString() : s; }
function parseObj(v: unknown): Record<string, unknown> { if (v && typeof v === "object" && !Array.isArray(v)) return v as Record<string, unknown>; if (typeof v === "string" && v) { try { const p = JSON.parse(v); return p && typeof p === "object" && !Array.isArray(p) ? p : {}; } catch { return {}; } } return {}; }
function parseArr(v: unknown): string[] { if (Array.isArray(v)) return v.map(String).filter(Boolean); if (typeof v === "string" && v) { try { const p = JSON.parse(v); return Array.isArray(p) ? p.map(String).filter(Boolean) : []; } catch { return []; } } return []; }
function stableJson(value: unknown): string { if (Array.isArray(value)) return `[${value.map(stableJson).join(",")}]`; if (value && typeof value === "object") return `{${Object.keys(value as Record<string, unknown>).sort().map((k) => `${JSON.stringify(k)}:${stableJson((value as Record<string, unknown>)[k])}`).join(",")}}`; return JSON.stringify(value); }
function hash(input: Record<string, unknown>): string { return createHash("sha256").update(stableJson(input)).digest("hex"); }
export function classifySoilWaterPotentialV1(v: number | null): SoilWaterPotentialClassV1 { if (v == null || !Number.isFinite(v)) return "UNKNOWN"; if (v >= -10) return "SATURATED_OR_NEAR_SATURATED"; if (v >= -60) return "READILY_AVAILABLE"; if (v >= -200) return "LIMITED_AVAILABLE"; return "STRESS"; }
function metricUnit(metric: unknown): "m3_m3" | "percent" { const m = String(metric ?? "").toLowerCase(); return m.includes("percent") || m.includes("pct") || m.includes("%") ? "percent" : "m3_m3"; }
function estimateId(determinismHash: string): string { return `swp_${determinismHash.slice(0, 24)}`; }
function empty(input: any, status: SoilWaterPotentialInputStatusV1, reasons: string[], thetaUnit: "m3_m3" | "percent", observed: number | null, normalized: number | null, h: string): SoilWaterPotentialEstimatePayloadV1 { return { estimate_id: estimateId(h), tenant_id: input.tenant_id, project_id: input.project_id, group_id: input.group_id, field_id: input.field_id, zone_id: input.zone_id, layer_depth_cm: input.layer_depth_cm, source_window_id: text(input.sensingWindow?.window_id), source_profile_id: text(input.hydraulicProfile?.profile_id), observed_theta: observed, theta_unit: thetaUnit, normalized_theta_m3_m3: normalized, matric_potential_kpa: null, matric_potential_class: "UNKNOWN", available_water_fraction: null, root_zone_weight: 1, input_status: status, blocking_reasons: reasons, hydraulic_profile_ref: text(input.hydraulicProfile?.profile_id), data_quality_ref: text(input.sensingWindow?.quality_status), evidence_refs: [text(input.sensingWindow?.window_id), text(input.hydraulicProfile?.profile_id)].filter((x): x is string => Boolean(x)), calculation_inputs: { observed_theta: observed, theta_unit: thetaUnit, normalized_theta_m3_m3: normalized }, derivation: { model_version: SOIL_WATER_POTENTIAL_MODEL_VERSION_V1, thresholds: { SATURATED_OR_NEAR_SATURATED: "matric_potential_kpa >= -10", READILY_AVAILABLE: "-60 <= matric_potential_kpa < -10", LIMITED_AVAILABLE: "-200 <= matric_potential_kpa < -60", STRESS: "matric_potential_kpa < -200", UNKNOWN: "matric_potential_kpa is null" } }, confidence: { level: "LOW", score: 0.1, basis: reasons.join(",") || "unknown" }, computed_at: iso(input.computed_at), determinism_hash: h }; }
export function buildSoilWaterPotentialEstimateV1(input: { tenant_id: string; project_id: string; group_id: string; field_id: string; zone_id: string; layer_depth_cm: number; sensingWindow: SoilMoistureSensingWindowIndexV1 | null; hydraulicProfile: SoilHydraulicProfileIndexV1 | null; computed_at: string; }): SoilWaterPotentialEstimatePayloadV1 {
  const unit = metricUnit(input.sensingWindow?.metric); const observed = num(input.sensingWindow?.summary?.last_value); const normalized = observed == null ? null : round6(unit === "percent" ? observed / 100 : observed);
  const profile = input.hydraulicProfile; const m = profile?.m ?? (profile?.n ? 1 - 1 / profile.n : null);
  const hashInput = { tenant_id: input.tenant_id, project_id: input.project_id, group_id: input.group_id, field_id: input.field_id, zone_id: input.zone_id, layer_depth_cm: input.layer_depth_cm, source_window_id: text(input.sensingWindow?.window_id), source_profile_id: text(profile?.profile_id), normalized_theta_m3_m3: normalized, theta_r: profile?.theta_r ?? null, theta_s: profile?.theta_s ?? null, alpha_per_kpa: profile?.alpha_per_kpa ?? null, n: profile?.n ?? null, m, model_version: SOIL_WATER_POTENTIAL_MODEL_VERSION_V1 };
  const h = hash(hashInput);
  if (!profile) return empty(input, "INSUFFICIENT_PROFILE", ["HYDRAULIC_PROFILE_MISSING"], unit, observed, normalized, h);
  if (input.sensingWindow?.quality_status !== "PASS") return empty(input, "BLOCKED_BY_DATA_QUALITY", ["SENSING_WINDOW_QUALITY_NOT_PASS"], unit, observed, normalized, h);
  if (normalized == null) return empty(input, "INVALID_INPUT", ["SENSING_WINDOW_LAST_VALUE_NOT_FINITE"], unit, observed, normalized, h);
  const result = estimateVanGenuchtenMatricPotentialV1({ theta: normalized, theta_r: profile.theta_r, theta_s: profile.theta_s, alpha_per_kpa: profile.alpha_per_kpa, n: profile.n, m: m ?? undefined });
  if (!result.ok) return empty(input, "INVALID_INPUT", result.blocking_reasons, unit, observed, normalized, h);
  return { ...empty(input, "ESTIMATED", [], unit, observed, normalized, h), matric_potential_kpa: result.matric_potential_kpa, matric_potential_class: classifySoilWaterPotentialV1(result.matric_potential_kpa), available_water_fraction: result.available_water_fraction, calculation_inputs: { observed_theta: observed, theta_unit: unit, normalized_theta_m3_m3: normalized, theta_r: profile.theta_r, theta_s: profile.theta_s, alpha_per_kpa: profile.alpha_per_kpa, n: profile.n, m }, derivation: { model_version: SOIL_WATER_POTENTIAL_MODEL_VERSION_V1, deterministic: true, effective_saturation: result.effective_saturation, thresholds: { SATURATED_OR_NEAR_SATURATED: "matric_potential_kpa >= -10", READILY_AVAILABLE: "-60 <= matric_potential_kpa < -10", LIMITED_AVAILABLE: "-200 <= matric_potential_kpa < -60", STRESS: "matric_potential_kpa < -200", UNKNOWN: "matric_potential_kpa is null" } }, confidence: { level: profile.confidence_level, score: profile.confidence_score, basis: `hydraulic_profile_${profile.calibration_status.toLowerCase()}_and_passed_sensing_window` } };
}
export function mapSoilWaterPotentialEstimateIndexV1Row(row: any): SoilWaterPotentialEstimateIndexV1 { return { estimate_id:String(row.estimate_id??""), tenant_id:String(row.tenant_id??""), project_id:String(row.project_id??""), group_id:String(row.group_id??""), field_id:String(row.field_id??""), zone_id:String(row.zone_id??""), layer_depth_cm:num(row.layer_depth_cm)??0, source_window_id:text(row.source_window_id), source_profile_id:text(row.source_profile_id), observed_theta:num(row.observed_theta), theta_unit: metricUnit(row.theta_unit), normalized_theta_m3_m3:num(row.normalized_theta_m3_m3), matric_potential_kpa:num(row.matric_potential_kpa), matric_potential_class:String(row.matric_potential_class??"UNKNOWN") as SoilWaterPotentialClassV1, available_water_fraction:num(row.available_water_fraction), root_zone_weight:num(row.root_zone_weight)??1, input_status:String(row.input_status??"UNKNOWN") as SoilWaterPotentialInputStatusV1, blocking_reasons:parseArr(row.blocking_reasons_json), hydraulic_profile_ref:text(row.hydraulic_profile_ref), data_quality_ref:text(row.data_quality_ref), evidence_refs:parseArr(row.evidence_refs_json), calculation_inputs:parseObj(row.calculation_inputs_json), derivation:parseObj(row.derivation_json), confidence:parseObj(row.confidence_json) as SoilWaterPotentialEstimatePayloadV1["confidence"], determinism_hash:String(row.determinism_hash??""), source_fact_id:text(row.source_fact_id), computed_at:iso(row.computed_at), updated_at: row.updated_at ? iso(row.updated_at) : undefined }; }
export async function ensureSoilWaterPotentialEstimateIndexV1(pool: DbConn): Promise<void> { await ensureSoilHydraulicProfileIndexV1(pool); await pool.query(`CREATE TABLE IF NOT EXISTS public.soil_water_potential_estimate_index_v1 (estimate_id text PRIMARY KEY, tenant_id text NOT NULL, project_id text NOT NULL, group_id text NOT NULL, field_id text NOT NULL, zone_id text NOT NULL, layer_depth_cm double precision NOT NULL, source_window_id text, source_profile_id text, observed_theta double precision, theta_unit text NOT NULL, normalized_theta_m3_m3 double precision, matric_potential_kpa double precision, matric_potential_class text NOT NULL, available_water_fraction double precision, root_zone_weight double precision NOT NULL, input_status text NOT NULL, blocking_reasons_json jsonb NOT NULL DEFAULT '[]'::jsonb, hydraulic_profile_ref text, data_quality_ref text, evidence_refs_json jsonb NOT NULL DEFAULT '[]'::jsonb, calculation_inputs_json jsonb NOT NULL DEFAULT '{}'::jsonb, derivation_json jsonb NOT NULL DEFAULT '{}'::jsonb, confidence_json jsonb NOT NULL DEFAULT '{}'::jsonb, determinism_hash text NOT NULL, source_fact_id text, computed_at timestamptz NOT NULL, updated_at timestamptz NOT NULL DEFAULT now())`); await pool.query(`CREATE INDEX IF NOT EXISTS idx_soil_water_potential_estimate_index_v1_scope_latest ON public.soil_water_potential_estimate_index_v1 (tenant_id, project_id, group_id, field_id, computed_at DESC)`); await pool.query(`CREATE INDEX IF NOT EXISTS idx_soil_water_potential_estimate_index_v1_window ON public.soil_water_potential_estimate_index_v1 (source_window_id)`); await pool.query(`CREATE INDEX IF NOT EXISTS idx_soil_water_potential_estimate_index_v1_profile ON public.soil_water_potential_estimate_index_v1 (source_profile_id)`); }
export async function appendSoilWaterPotentialEstimateFactV1(pool: DbConn, payload: SoilWaterPotentialEstimatePayloadV1): Promise<{ fact_id: string; payload: SoilWaterPotentialEstimatePayloadV1 }> { const factId = "soil_water_potential_estimate_fact_" + randomUUID(); await pool.query(`INSERT INTO facts (fact_id, occurred_at, source, record_json) VALUES ($1,$2,$3,$4::jsonb) ON CONFLICT (fact_id) DO NOTHING`, [factId, payload.computed_at, "soil_water_potential_estimate_v1", JSON.stringify({ type: "soil_water_potential_estimate_v1", payload })]); return { fact_id: factId, payload }; }
export async function upsertSoilWaterPotentialEstimateIndexV1(pool: DbConn, payload: SoilWaterPotentialEstimatePayloadV1, sourceFactId: string | null): Promise<SoilWaterPotentialEstimateIndexV1> { await ensureSoilWaterPotentialEstimateIndexV1(pool); await pool.query(`INSERT INTO public.soil_water_potential_estimate_index_v1 (estimate_id,tenant_id,project_id,group_id,field_id,zone_id,layer_depth_cm,source_window_id,source_profile_id,observed_theta,theta_unit,normalized_theta_m3_m3,matric_potential_kpa,matric_potential_class,available_water_fraction,root_zone_weight,input_status,blocking_reasons_json,hydraulic_profile_ref,data_quality_ref,evidence_refs_json,calculation_inputs_json,derivation_json,confidence_json,determinism_hash,source_fact_id,computed_at,updated_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18::jsonb,$19,$20,$21::jsonb,$22::jsonb,$23::jsonb,$24::jsonb,$25,$26,$27,now()) ON CONFLICT (estimate_id) DO UPDATE SET tenant_id=EXCLUDED.tenant_id,project_id=EXCLUDED.project_id,group_id=EXCLUDED.group_id,field_id=EXCLUDED.field_id,zone_id=EXCLUDED.zone_id,layer_depth_cm=EXCLUDED.layer_depth_cm,source_window_id=EXCLUDED.source_window_id,source_profile_id=EXCLUDED.source_profile_id,observed_theta=EXCLUDED.observed_theta,theta_unit=EXCLUDED.theta_unit,normalized_theta_m3_m3=EXCLUDED.normalized_theta_m3_m3,matric_potential_kpa=EXCLUDED.matric_potential_kpa,matric_potential_class=EXCLUDED.matric_potential_class,available_water_fraction=EXCLUDED.available_water_fraction,root_zone_weight=EXCLUDED.root_zone_weight,input_status=EXCLUDED.input_status,blocking_reasons_json=EXCLUDED.blocking_reasons_json,hydraulic_profile_ref=EXCLUDED.hydraulic_profile_ref,data_quality_ref=EXCLUDED.data_quality_ref,evidence_refs_json=EXCLUDED.evidence_refs_json,calculation_inputs_json=EXCLUDED.calculation_inputs_json,derivation_json=EXCLUDED.derivation_json,confidence_json=EXCLUDED.confidence_json,determinism_hash=EXCLUDED.determinism_hash,source_fact_id=EXCLUDED.source_fact_id,computed_at=EXCLUDED.computed_at,updated_at=now()`, [payload.estimate_id,payload.tenant_id,payload.project_id,payload.group_id,payload.field_id,payload.zone_id,payload.layer_depth_cm,payload.source_window_id,payload.source_profile_id,payload.observed_theta,payload.theta_unit,payload.normalized_theta_m3_m3,payload.matric_potential_kpa,payload.matric_potential_class,payload.available_water_fraction,payload.root_zone_weight,payload.input_status,JSON.stringify(payload.blocking_reasons),payload.hydraulic_profile_ref,payload.data_quality_ref,JSON.stringify(payload.evidence_refs),JSON.stringify(payload.calculation_inputs),JSON.stringify(payload.derivation),JSON.stringify(payload.confidence),payload.determinism_hash,sourceFactId,payload.computed_at]); return { ...payload, source_fact_id: sourceFactId }; }
export async function ingestSoilWaterPotentialEstimateV1(pool: DbConn, payload: SoilWaterPotentialEstimatePayloadV1): Promise<SoilWaterPotentialEstimateIndexV1> { const appended = await appendSoilWaterPotentialEstimateFactV1(pool, payload); return upsertSoilWaterPotentialEstimateIndexV1(pool, appended.payload, appended.fact_id); }
