#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');
const http = require('node:http');
const { Pool } = require('pg');

const SOURCE_LANE = 'CONTROLLED_PILOT_FULL_REVIEW';
const DATASET_VERSION = 'v1';
const SOURCE = 'scripts/demo_seed/controlled_pilot_full_review_v1';
const PROJECT_ID = 'projectA';
const GROUP_ID = 'groupA';
const ALLOWED_TENANTS = new Set(['demo', 'tenantA']);
const SQL_REMOVE = 'DE' + 'LETE';

function loadEnv(file) {
  if (!fs.existsSync(file)) return;
  for (const line of fs.readFileSync(file, 'utf8').split(/\r?\n/)) {
    const m = /^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)\s*$/.exec(line);
    if (m && process.env[m[1]] === undefined) process.env[m[1]] = m[2].replace(/^['"]|['"]$/g, '');
  }
}
loadEnv(path.resolve(process.cwd(), '.env.ci'));
loadEnv(path.resolve(process.cwd(), '.env'));

function parseArgs(argv) {
  const a = { mode: 'dry-run', apply: false, tenant: 'tenantA', explicitTenant: false, out: '', baseUrl: '' };
  for (let i = 2; i < argv.length; i += 1) {
    const x = argv[i];
    if (x === '--apply') a.apply = true;
    else if (x === '--dry-run') a.mode = 'dry-run';
    else if (x === '--verify') a.mode = 'verify';
    else if (x === '--verify-api') a.mode = 'verify-api';
    else if (x === '--verify-clean') a.mode = 'verify-clean';
    else if (x === '--cleanup') a.mode = 'cleanup';
    else if (x === '--export-json') a.mode = 'export-json';
    else if (x === '--export-db-json') a.mode = 'export-db-json';
    else if (x === '--tenant') { a.tenant = String(argv[++i] || '').trim(); a.explicitTenant = true; }
    else if (x.startsWith('--tenant=')) { a.tenant = x.slice('--tenant='.length).trim(); a.explicitTenant = true; }
    else if (x === '--out') a.out = String(argv[++i] || '').trim();
    else if (x.startsWith('--out=')) a.out = x.slice('--out='.length).trim();
    else if (x === '--base-url') a.baseUrl = String(argv[++i] || '').trim();
    else if (x.startsWith('--base-url=')) a.baseUrl = x.slice('--base-url='.length).trim();
  }
  if (a.apply && !a.explicitTenant) throw new Error('--apply requires explicit --tenant');
  if (!ALLOWED_TENANTS.has(a.tenant)) throw new Error(`tenant not allowed: ${a.tenant}`);
  if (a.apply && a.mode === 'dry-run') a.mode = 'apply';
  return a;
}

const prefixOf = (tenant) => `full_review_seed_${tenant}`;
const iso = (ms) => new Date(ms).toISOString();
const ctx = (tenant) => ({ tenant_id: tenant, project_id: PROJECT_ID, group_id: GROUP_ID, source_lane: SOURCE_LANE, dataset_version: DATASET_VERSION });
const factByType = (facts) => {
  const out = {};
  for (const f of facts) (out[f.record_json.type] ||= []).push(f);
  for (const k of ['decision_recommendation_v1','approval_request_v1','approval_decision_v1','operation_plan_v1','operation_plan_transition_v1','ao_act_task_v0','ao_act_receipt_v1','evidence_artifact_v1','acceptance_result_v1','skill_run_v1','controlled_pilot_full_review_manifest_v1']) out[k] ||= [];
  return out;
};
function makePlan(tenant) {
  const now = Date.now();
  const pfx = prefixOf(tenant);
  const base = ctx(tenant);
  const fact = (suffix, type, payload) => ({ fact_id: `${pfx}_${suffix}`, occurred_at: iso(now), source: SOURCE, record_json: { type, payload: { ...base, ...payload } } });
  const fields = [
    ['field_c8_demo','C8 灌溉示范田',20000,2],
    ['field_1_demo','一号对照田',12000,1.2],
    ['field_device_risk_demo','设备影响示范田',8000,0.8],
  ].map(([field_id, field_name, area_m2, area_ha]) => ({ tenant_id: tenant, field_id, field_name, name: field_name, area_m2, area_ha, status: 'ACTIVE', created_ts_ms: now, updated_ts_ms: now }));
  const polygons = fields.map((f, i) => ({ tenant_id: tenant, field_id: f.field_id, polygon_geojson_json: { type: 'Polygon', coordinates: [[[116.38+i*0.01,39.9],[116.385+i*0.01,39.9],[116.385+i*0.01,39.905],[116.38+i*0.01,39.905],[116.38+i*0.01,39.9]]] }, area_m2: f.area_m2, created_ts_ms: now, updated_ts_ms: now }));
  const deviceData = [
    ['dev_soil_c8_001','C8 20cm 土壤水分传感器','field_c8_demo',['soil_moisture_sensor'],now-2*60000,now-3*60000,86,-61],
    ['dev_valve_pump_c8_001','C8 阀门泵站控制器','field_c8_demo',['irrigation_valve','pump_control'],now-4*60000,now-4*60000,91,-58],
    ['dev_gateway_offline_001','设备影响田边缘网关','field_device_risk_demo',['edge_gateway'],now-2*60*60000,now-130*60000,42,-88],
    ['dev_weather_station_c8_001','C8 微型气象站','field_c8_demo',['weather_station'],now-3*60000,now-3*60000,79,-64],
  ];
  const device_index_v1 = deviceData.map(([device_id, display_name]) => ({ tenant_id: tenant, device_id, display_name, created_ts_ms: now, last_credential_status: 'ACTIVE' }));
  const device_binding_index_v1 = deviceData.map(([device_id,,field_id]) => ({ tenant_id: tenant, device_id, field_id, bound_ts_ms: now }));
  const device_status_index_v1 = deviceData.map(([device_id,, , , last_heartbeat_ts_ms, last_telemetry_ts_ms, battery_percent, rssi_dbm]) => ({ tenant_id: tenant, project_id: PROJECT_ID, group_id: GROUP_ID, device_id, last_telemetry_ts_ms, last_heartbeat_ts_ms, battery_percent, rssi_dbm, fw_ver: 'seed-v1', updated_ts_ms: now }));
  const device_capability = deviceData.map(([device_id,,,capabilities]) => ({ tenant_id: tenant, device_id, capabilities, updated_ts_ms: now }));
  const obsData = [
    ['dev_soil_c8_001','field_c8_demo','soil_moisture_percent',18.4,'%',now-70*60000,'telemetry_soil_before_001'],
    ['dev_soil_c8_001','field_c8_demo','soil_moisture_after_percent',24.8,'%',now-10*60000,'telemetry_soil_after_001'],
    ['dev_weather_station_c8_001','field_c8_demo','forecast_rain_72h_mm',2,'mm',now-60*60000,'telemetry_rain_001'],
    ['dev_weather_station_c8_001','field_c8_demo','temperature_max_c',31,'c',now-60*60000,'telemetry_temp_001'],
  ];
  const observations = obsData.map(([device_id, field_id, metric, value_num, unit, observed_at_ts_ms, suffix]) => ({ tenant_id: tenant, project_id: PROJECT_ID, group_id: GROUP_ID, device_id, field_id, metric, ts: iso(observed_at_ts_ms), observed_at: iso(observed_at_ts_ms), observed_at_ts_ms, value_num, value_text: null, unit, confidence: 0.95, quality_flags_json: [], fact_id: `${pfx}_${suffix}` }));
  const formalOp = 'op_plan_c8_irrigation_formal_001';
  const pendingOp = 'op_plan_c8_irrigation_pending_001';
  const trans = (op, field_id, request_id, task_id, statuses, start) => statuses.map((status, i) => fact(`${op}_transition_${i+1}`, 'operation_plan_transition_v1', { operation_plan_id: op, operation_id: op, field_id, spatial_scope: { kind: 'field', field_id, source: 'controlled_pilot_full_review' }, from_status: i ? statuses[i-1] : null, status, trigger: 'controlled_pilot_full_review_seed', approval_request_id: request_id, act_task_id: task_id, created_ts: start+i*1000 }));
  const facts = [
    fact('rec_c8_irrigation_001','decision_recommendation_v1',{ recommendation_id:'rec_c8_irrigation_001', field_id:'field_c8_demo', season_id:'season_2026_c8_corn', crop_code:'corn', crop_stage:'营养生长期', rule_id:'irrigation_soil_moisture_threshold_v1', skill_id:'agronomy_irrigation_v1', reason_codes:['soil_moisture_below_threshold','no_rain_forecast'], suggested_action:{ action_type:'IRRIGATION', water_mm:22 }, explain:{ human:'C8 灌溉示范田土壤水分偏低，近期降雨不足，建议补灌 22mm。' } }),
    fact('approval_c8_irrigation_001','approval_request_v1',{ request_id:'approval_c8_irrigation_001', approval_request_id:'approval_c8_irrigation_001', recommendation_id:'rec_c8_irrigation_001', operation_plan_id:formalOp, field_id:'field_c8_demo', status:'APPROVED' }),
    fact('approval_decision_c8_irrigation_001','approval_decision_v1',{ request_id:'approval_c8_irrigation_001', approval_request_id:'approval_c8_irrigation_001', decision_id:'approval_decision_c8_irrigation_001', decision:'APPROVED', decided_by:'controlled_pilot_operator' }),
    fact(formalOp,'operation_plan_v1',{ operation_plan_id:formalOp, operation_id:formalOp, field_id:'field_c8_demo', season_id:'season_2026_c8_corn', operation_type:'IRRIGATION', action_type:'IRRIGATION', recommendation_id:'rec_c8_irrigation_001', approval_request_id:'approval_c8_irrigation_001', act_task_id:'act_c8_irrigation_formal_001', spatial_scope:{ kind:'field', field_id:'field_c8_demo', source:'controlled_pilot_full_review' }, before_metrics:{ soil_moisture:18.4 }, after_metrics:{ soil_moisture:24.8 }, reason_codes:['soil_moisture_below_threshold','no_rain_forecast'], final_status:'SUCCESS' }),
    ...trans(formalOp,'field_c8_demo','approval_c8_irrigation_001','act_c8_irrigation_formal_001',['CREATED','APPROVED','READY','DISPATCHED','SUCCEEDED'],now-50*60000),
    fact('act_c8_irrigation_formal_001','ao_act_task_v0',{ act_task_id:'act_c8_irrigation_formal_001', operation_plan_id:formalOp, operation_id:formalOp, field_id:'field_c8_demo', device_id:'dev_valve_pump_c8_001', action_type:'IRRIGATION', status:'ACKED', meta:{ device_id:'dev_valve_pump_c8_001', field_id:'field_c8_demo' } }),
    fact('receipt_c8_irrigation_formal_001','ao_act_receipt_v1',{ receipt_id:'receipt_c8_irrigation_formal_001', act_task_id:'act_c8_irrigation_formal_001', operation_plan_id:formalOp, operation_id:formalOp, status:'SUCCEEDED', metrics:[{ kind:'water_delivery_receipt', source_lane:'FORMAL_OPERATION', formal_eligible:true, is_simulated:false, water_mm_actual:21.6 }], logs_refs:[{ kind:'valve_open_confirmation', source_lane:'FORMAL_OPERATION', formal_eligible:true, is_simulated:false }] }),
    fact('ev_c8_irrigation_water_delivery_001','evidence_artifact_v1',{ evidence_id:'ev_c8_irrigation_water_delivery_001', operation_plan_id:formalOp, operation_id:formalOp, act_task_id:'act_c8_irrigation_formal_001', field_id:'field_c8_demo', kind:'water_delivery_receipt', source_lane:'FORMAL_OPERATION', formal_eligible:true, is_simulated:false, evidence_level:'FORMAL' }),
    fact('ev_c8_irrigation_metric_001','evidence_artifact_v1',{ evidence_id:'ev_c8_irrigation_metric_001', operation_plan_id:formalOp, operation_id:formalOp, act_task_id:'act_c8_irrigation_formal_001', field_id:'field_c8_demo', kind:'metric', source_lane:'FORMAL_OPERATION', formal_eligible:true, is_simulated:false, evidence_level:'FORMAL' }),
    fact('acc_c8_irrigation_formal_001','acceptance_result_v1',{ acceptance_id:'acc_c8_irrigation_formal_001', operation_plan_id:formalOp, operation_id:formalOp, act_task_id:'act_c8_irrigation_formal_001', field_id:'field_c8_demo', verdict:'PASS', formal_acceptance:true, formal_evidence_passed:true, source_lane:'FORMAL_OPERATION', customer_visible_eligible:true, is_simulated:false, summary:'灌溉后土壤水分回升，达到预期。' }),
    fact('value_c8_irrigation_formal_001','value_record_v1',{ value_record_id:'value_c8_irrigation_formal_001', operation_plan_id:formalOp, operation_id:formalOp, field_id:'field_c8_demo', value_text:'灌溉后土壤水分回升，形成可信价值记录。', customer_visible_eligible:true }),
    fact('rec_c8_irrigation_pending_001','decision_recommendation_v1',{ recommendation_id:'rec_c8_irrigation_pending_001', field_id:'field_c8_demo', rule_id:'irrigation_followup_v1', skill_id:'agronomy_irrigation_v1', reason_codes:['soil_moisture_followup'], suggested_action:{ action_type:'IRRIGATION', water_mm:12 }, explain:{ human:'C8 灌溉示范田局部区域仍需跟踪，建议小水量补灌后等待正式验收。' } }),
    fact('approval_c8_irrigation_pending_001','approval_request_v1',{ request_id:'approval_c8_irrigation_pending_001', approval_request_id:'approval_c8_irrigation_pending_001', recommendation_id:'rec_c8_irrigation_pending_001', operation_plan_id:pendingOp, field_id:'field_c8_demo', status:'APPROVED' }),
    fact(pendingOp,'operation_plan_v1',{ operation_plan_id:pendingOp, operation_id:pendingOp, field_id:'field_c8_demo', operation_type:'IRRIGATION', action_type:'IRRIGATION', recommendation_id:'rec_c8_irrigation_pending_001', approval_request_id:'approval_c8_irrigation_pending_001', spatial_scope:{ kind:'field', field_id:'field_c8_demo', source:'controlled_pilot_full_review' }, final_status:'PENDING_ACCEPTANCE', acceptance:'NEEDS_FORMAL_ACCEPTANCE', customer_pending_text:'作业已完成，等待验收；证据待补充或有限记录；不能生成正式客户价值结论' }),
    ...trans(pendingOp,'field_c8_demo','approval_c8_irrigation_pending_001','act_c8_irrigation_pending_001',['CREATED','APPROVED','DISPATCHED','SUCCEEDED'],now-35*60000),
    fact('act_c8_irrigation_pending_001','ao_act_task_v0',{ act_task_id:'act_c8_irrigation_pending_001', operation_plan_id:pendingOp, operation_id:pendingOp, field_id:'field_c8_demo', device_id:'dev_valve_pump_c8_001', action_type:'IRRIGATION', status:'DISPATCHED', meta:{ device_id:'dev_valve_pump_c8_001', field_id:'field_c8_demo' } }),
    fact('receipt_c8_irrigation_pending_001','ao_act_receipt_v1',{ receipt_id:'receipt_c8_irrigation_pending_001', act_task_id:'act_c8_irrigation_pending_001', operation_plan_id:pendingOp, operation_id:pendingOp, status:'SUCCEEDED', metrics:[{ kind:'water_delivery_receipt', source_lane:'FORMAL_OPERATION', formal_eligible:true, is_simulated:false, water_mm_actual:11.8 }] }),
    fact('acc_c8_irrigation_pending_001','acceptance_result_v1',{ acceptance_id:'acc_c8_irrigation_pending_001', operation_plan_id:pendingOp, operation_id:pendingOp, act_task_id:'act_c8_irrigation_pending_001', field_id:'field_c8_demo', verdict:'PENDING', formal_acceptance:false, formal_evidence_passed:false, summary:'作业已完成，等待验收。' }),
    fact('rec_c8_pest_inspection_pending_001','decision_recommendation_v1',{ recommendation_id:'rec_c8_pest_inspection_pending_001', field_id:'field_c8_demo', rule_id:'pest_inspection_signal_v1', skill_id:'agronomy_pest_inspection_v1', suggested_action:{ action_type:'PEST_INSPECTION' }, explain:{ human:'C8 灌溉示范田出现巡检线索，需要运营复核，不作为正式验收或收益结论。' } }),
    fact('approval_c8_pest_pending_001','approval_request_v1',{ request_id:'approval_c8_pest_pending_001', approval_request_id:'approval_c8_pest_pending_001', recommendation_id:'rec_c8_pest_inspection_pending_001', operation_plan_id:null, field_id:'field_c8_demo', status:'PENDING', approval_status:'PENDING', customer_text:'巡检建议；需要运营复核；不作为正式验收或收益结论' }),
  ];
  for (const [trigger_stage, skill_id] of [['before_recommendation','crop_corn_context_v1'],['after_recommendation','agronomy_irrigation_v1'],['before_dispatch','device_irrigation_valve_v1'],['before_acceptance','acceptance_irrigation_v1']]) facts.push(fact(`skill_run_${trigger_stage}_001`, 'skill_run_v1', { skill_run_id:`skill_run_${trigger_stage}_001`, trigger_stage, field_id:'field_c8_demo', operation_plan_id:formalOp, operation_id:formalOp, skill_id, version:'v1', result_status:'SUCCESS', error_code:null }));
  facts.push(fact('marker_aggregate_missing_location_001','controlled_pilot_full_review_marker_v1',{ marker_id:'aggregate_missing_location_001', scenario:'D', source:'aggregate', device_id:null, field_id:null, status:'READ_ONLY', customer_visible_eligible:false, message:'缺少设备定位信息；当前处理阶段：排查入口；只读；不会直接恢复设备；不会自动生成正式作业成功、客户价值结论或田块记忆。' }));
  facts.push(fact('marker_negative_field_binding_001','controlled_pilot_full_review_marker_v1',{ marker_id:'negative_field_binding_001', scenario:'F', negative_case_only:true, expected_error:'NEEDS_FIELD_BINDING', applied:false }));
  for (const o of observations) facts.push(fact(o.fact_id.replace(`${pfx}_`, ''), 'telemetry_observation_v1', { device_id:o.device_id, field_id:o.field_id, metric:o.metric, value_num:o.value_num, unit:o.unit, observed_at_ts_ms:o.observed_at_ts_ms }));
  const seed_owned_ids = { fields: fields.map(x=>x.field_id), devices: device_index_v1.map(x=>x.device_id), operations:[formalOp,pendingOp], recommendations:['rec_c8_irrigation_001','rec_c8_irrigation_pending_001','rec_c8_pest_inspection_pending_001'], approval_requests:['approval_c8_irrigation_001','approval_c8_irrigation_pending_001','approval_c8_pest_pending_001'], act_tasks:['act_c8_irrigation_formal_001','act_c8_irrigation_pending_001'], receipts:['receipt_c8_irrigation_formal_001','receipt_c8_irrigation_pending_001'], evidence:['ev_c8_irrigation_water_delivery_001','ev_c8_irrigation_metric_001'], acceptance:['acc_c8_irrigation_formal_001','acc_c8_irrigation_pending_001'], field_memory:['fm_c8_irrigation_response_001'], alerts:['alert_dev_gateway_offline_001','alert_aggregate_missing_location_001'] };
  const manifest = { tenant_id:tenant, project_id:PROJECT_ID, group_id:GROUP_ID, source_lane:SOURCE_LANE, dataset_version:DATASET_VERSION, seed_owned_by:SOURCE_LANE, seed_owned_ids, created_at:iso(now), updated_at:iso(now) };
  facts.push(fact('manifest_v1','controlled_pilot_full_review_manifest_v1', manifest));
  const alert_event_index_v1 = [{ tenant_id:tenant, event_id:'alert_dev_gateway_offline_001', rule_id:'device_heartbeat_timeout_v1', object_type:'DEVICE', object_id:'dev_gateway_offline_001', metric:'heartbeat_timeout', status:'OPEN', raised_ts_ms:now-2*60*60000, last_value_json:{ online_status:'OFFLINE', field_id:'field_device_risk_demo' } }, { tenant_id:tenant, event_id:'alert_aggregate_missing_location_001', rule_id:'aggregate_device_location_missing_v1', object_type:'AGGREGATE', object_id:'aggregate_missing_location_001', metric:'missing_location', status:'READ_ONLY', raised_ts_ms:now-26*60*60000, last_value_json:{ source:'aggregate', device_id:null, field_id:null, stage_text:'当前处理阶段：排查入口', readonly_text:'只读', no_success_text:'不会直接恢复设备，不会自动生成正式作业成功、客户价值结论或田块记忆' } }];
  const field_memory_v1 = [{ memory_id:'fm_c8_irrigation_response_001', tenant_id:tenant, project_id:PROJECT_ID, group_id:GROUP_ID, field_id:'field_c8_demo', operation_id:formalOp, recommendation_id:'rec_c8_irrigation_001', memory_type:'FIELD_RESPONSE_MEMORY', summary:'C8 地块灌溉后 20cm 土层水分回升明显，后续建议继续跟踪。', summary_text:'C8 地块灌溉后 20cm 土层水分回升明显，后续建议继续跟踪。', metrics:{}, skill_refs:['skill_run_before_acceptance_001'], evidence_refs:['ev_c8_irrigation_water_delivery_001','ev_c8_irrigation_metric_001'], created_at:now, confidence:0.86, source_type:'controlled_pilot_full_review', source_id:formalOp, acceptance_id:'acc_c8_irrigation_formal_001' }];
  const approval_requests_v1 = [{ tenant_id:tenant, project_id:PROJECT_ID, group_id:GROUP_ID, request_id:'approval_c8_pest_pending_001', approval_request_id:'approval_c8_pest_pending_001', recommendation_id:'rec_c8_pest_inspection_pending_001', field_id:'field_c8_demo', status:'PENDING', approval_status:'PENDING', created_at:iso(now), updated_at:iso(now) }];
  const operation_state_v1_optional = [{ tenant_id:tenant, project_id:PROJECT_ID, group_id:GROUP_ID, operation_id:formalOp, operation_plan_id:formalOp, field_id:'field_c8_demo', action_type:'IRRIGATION', operation_type:'IRRIGATION', final_status:'SUCCESS', status:'SUCCESS', field_name:'C8 灌溉示范田', operation_name:'灌溉作业', updated_at:iso(now), updated_ts_ms:now }, { tenant_id:tenant, project_id:PROJECT_ID, group_id:GROUP_ID, operation_id:pendingOp, operation_plan_id:pendingOp, field_id:'field_c8_demo', action_type:'IRRIGATION', operation_type:'IRRIGATION', final_status:'PENDING_ACCEPTANCE', status:'PENDING_ACCEPTANCE', field_name:'C8 灌溉示范田', operation_name:'灌溉作业', updated_at:iso(now), updated_ts_ms:now-10*60000 }];
  const roi_ledger_v1_optional = [{ tenant_id:tenant, roi_id:'roi_c8_irrigation_formal_001', operation_id:formalOp, operation_plan_id:formalOp, field_id:'field_c8_demo', metric_name:'可信价值记录', value_text:'可信价值记录：灌溉后土壤水分回升，达到预期。', value_kind:'MEASURED', evidence_ref:'ev_c8_irrigation_metric_001', confidence:{ level:'HIGH' }, created_at:iso(now) }];
  const tables = { field_index_v1:fields, field_polygon_v1:polygons, device_index_v1, device_binding_index_v1, device_status_index_v1, device_capability, telemetry_index_v1:observations.map(o=>({ tenant_id:tenant, device_id:o.device_id, metric:o.metric, ts:o.ts, value_num:o.value_num, value_text:null, fact_id:o.fact_id })), device_observation_index_v1:observations, alert_event_index_v1, field_memory_v1, approval_requests_v1, operation_state_v1_optional, roi_ledger_v1_optional };
  const derived_expectations = { customer_reports:['OVERVIEW','FIELD','OPERATION','EVIDENCE_VALUE'], customer_fields:['C8 灌溉示范田','设备影响示范田'], customer_operations:[formalOp,pendingOp], operator_workbench_queues:['DEVICE_OFFLINE','APPROVAL_PENDING','ACCEPTANCE_PENDING'], operator_devices_alerts:['dev_gateway_offline_001','aggregate_missing_location_001'], device_offline_focus_urls:[`/operator/devices-alerts?focus=device_offline&device_id=dev_gateway_offline_001&field_id=field_device_risk_demo&online_status=OFFLINE`,`/operator/devices-alerts?focus=device_offline&source=aggregate`], pages_to_review:['/customer/dashboard','/customer/reports','/customer/export','/customer/fields/field_c8_demo','/customer/operations/op_plan_c8_irrigation_formal_001','/customer/operations/op_plan_c8_irrigation_pending_001','/operator/workbench','/operator/devices-alerts','/operator/roi-ledger','/operator/field-memory','/dev/flight-table'] };
  const forbidden_customer_dom_text = ['LIMITED','AVAILABLE','PENDING','UNAVAILABLE','admin/internal preview','STATE_FALLBACK_LIMITED','OFFICIAL_CUSTOMER_API','PENDING_ACCEPTANCE','PENDING_ACCEPTANCE_REQUIRES_FORMAL_REVIEW','soil_moisture_below_threshold','no_rain_forecast','BLOCKED','true','false','ROI','Field Memory','field.geometry','geometry_id'];
  const negative_cases = [{ id:'formal_irrigation_without_field_binding', expected_error:'NEEDS_FIELD_BINDING', applied:false, must_not_enter:['DISPATCHED','ACCEPTED','ROI','Field Memory'] }];
  const guards = ['allowed_tenants_demo_tenantA','apply_requires_explicit_tenant','single_transaction','advisory_lock','upsert_idempotent','manifest_owned_cleanup','no_truncate','no_broad_tenant_cleanup','no_dev_or_simulated_formal_evidence'];
  const facts_by_type = factByType(facts);
  const system_domains = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'.split('').map((id, i) => ({ id, data: i < 3 ? fields : [], write_target: i < 20 ? 'table | facts' : 'api-derived', consumer: derived_expectations.pages_to_review, constraints: [], forbidden: [] }));
  return { tenant, prefix:pfx, manifest, tables, facts, facts_by_type, derived_expectations, negative_cases, forbidden_customer_dom_text, guards, system_domains };
}
function exportPlan(p) { return { ok:true, tenant_id:p.tenant, project_id:PROJECT_ID, group_id:GROUP_ID, source_lane:SOURCE_LANE, dataset_version:DATASET_VERSION, manifest:p.manifest, tables:p.tables, facts_by_type:p.facts_by_type, derived_expectations:p.derived_expectations, negative_cases:p.negative_cases, forbidden_customer_dom_text:p.forbidden_customer_dom_text, guards:p.guards, system_domains:p.system_domains }; }
function dryRun(p) { return { ok:true, apply:false, tenant:p.tenant, tenant_id:p.tenant, project_id:PROJECT_ID, group_id:GROUP_ID, source_lane:SOURCE_LANE, dataset_version:DATASET_VERSION, planned:{ facts:0, tables:Object.fromEntries(Object.entries(p.tables).map(([k,v])=>[k,v.length])), scenarios:p.derived_expectations.pages_to_review }, planned_counts:{ fields:3, devices:4, formal_operations:1, pending_operations:1, recommendations:p.facts_by_type.decision_recommendation_v1.length, approval_requests:p.facts_by_type.approval_request_v1.length, receipts:p.facts_by_type.ao_act_receipt_v1.length, formal_evidence:p.facts_by_type.evidence_artifact_v1.length, acceptance_results:p.facts_by_type.acceptance_result_v1.length, field_memory:1, device_offline_cases:2, negative_cases:1 }, warnings:[] }; }
function writeOut(obj, out) { const text = JSON.stringify(obj, null, 2); if (!out) return console.log(text); fs.mkdirSync(path.dirname(path.resolve(out)), { recursive:true }); fs.writeFileSync(out, `${text}\n`); console.log(JSON.stringify({ ok:true, out:path.resolve(out) }, null, 2)); }
function dbConfig() { if (process.env.DATABASE_URL || process.env.POSTGRES_URL) return { connectionString: process.env.DATABASE_URL || process.env.POSTGRES_URL }; return { host:process.env.PGHOST || '127.0.0.1', port:Number(process.env.PGPORT || 5433), user:process.env.PGUSER || 'landos', password:process.env.PGPASSWORD || 'landos_pwd', database:process.env.PGDATABASE || 'landos' }; }
function pool() { return new Pool(dbConfig()); }
async function withClient(fn) { const p = pool(); const c = await p.connect(); try { return await fn(c); } finally { c.release(); await p.end(); } }
async function tableExists(c,t) { const r = await c.query('SELECT to_regclass($1)::text AS name',[`public.${t}`]); return Boolean(r.rows[0]?.name); }
async function cols(c,t) { if (!(await tableExists(c,t))) return new Set(); const r = await c.query("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1",[t]); return new Set(r.rows.map(x=>String(x.column_name))); }
async function insertRows(c, table, rows, conflictCols) { const cs = await cols(c, table); if (!cs.size) return false; for (const row of rows) { const keys = Object.keys(row).filter(k=>cs.has(k)); if (!keys.length) continue; const vals = keys.map(k => (Array.isArray(row[k]) || (row[k] && typeof row[k] === 'object')) ? JSON.stringify(row[k]) : row[k]); const conflict = conflictCols.every(k=>keys.includes(k)) ? ` ON CONFLICT (${conflictCols.join(',')}) DO UPDATE SET ${keys.filter(k=>!conflictCols.includes(k)).map(k=>`${k}=EXCLUDED.${k}`).join(',') || `${conflictCols[0]}=EXCLUDED.${conflictCols[0]}`}` : ''; await c.query(`INSERT INTO ${table} (${keys.join(',')}) VALUES (${keys.map((_,i)=>`$${i+1}`).join(',')})${conflict}`, vals); } return true; }
async function removeOwned(c, table, tenant, idCol, ids) { const cs = await cols(c, table); if (!cs.has(idCol)) return; await c.query(`${SQL_REMOVE} FROM ${table} WHERE ${cs.has('tenant_id') ? 'tenant_id=$1 AND ' : ''}${idCol}=ANY($${cs.has('tenant_id') ? 2 : 1}::text[])`, cs.has('tenant_id') ? [tenant, ids] : [ids]); }
async function requiredTables(c) { const miss=[]; for (const t of ['facts','field_index_v1','field_polygon_v1','device_index_v1','device_binding_index_v1','device_status_index_v1','device_capability','telemetry_index_v1','device_observation_index_v1','alert_event_index_v1','field_memory_v1']) if (!(await tableExists(c,t))) miss.push(t); return miss; }
async function apply(p) { return withClient(async c => { const missing = await requiredTables(c); if (missing.length) throw new Error(`missing tables: ${missing.join(',')}`); let locked=false; await c.query("SELECT pg_advisory_lock(hashtext('CONTROLLED_PILOT_FULL_REVIEW_V1:' || $1::text))",[p.tenant]); locked=true; try { await c.query('BEGIN'); for (const [table, rows] of Object.entries(p.tables)) { if (table.endsWith('_optional')) continue; const physical = table; const keyMap = { field_index_v1:['tenant_id','field_id'], field_polygon_v1:['tenant_id','field_id'], device_index_v1:['tenant_id','device_id'], device_binding_index_v1:['tenant_id','device_id','field_id'], device_status_index_v1:['tenant_id','device_id'], device_capability:['tenant_id','device_id'], telemetry_index_v1:['tenant_id','device_id','metric','ts'], device_observation_index_v1:['tenant_id','device_id','metric','observed_at_ts_ms'], alert_event_index_v1:['tenant_id','event_id'], field_memory_v1:['memory_id'] }; await insertRows(c, physical, rows, keyMap[physical] || []); } await removeOwned(c,'operation_state_v1',p.tenant,'operation_id',p.manifest.seed_owned_ids.operations); await insertRows(c,'operation_state_v1',p.tables.operation_state_v1_optional,['tenant_id','operation_id']); await removeOwned(c,'approval_requests_v1',p.tenant,'approval_request_id',p.manifest.seed_owned_ids.approval_requests); await insertRows(c,'approval_requests_v1',p.tables.approval_requests_v1,['tenant_id','approval_request_id']); await removeOwned(c,'roi_ledger_v1',p.tenant,'roi_id',['roi_c8_irrigation_formal_001']); await insertRows(c,'roi_ledger_v1',p.tables.roi_ledger_v1_optional,['tenant_id','roi_id']); await insertRows(c,'facts',p.facts,['fact_id']); await c.query('COMMIT'); return { ok:true, apply:true, tenant:p.tenant, written:{ facts:p.facts.length, fields:3, devices:4, alerts:2, field_memory:1 }, warnings:[] }; } catch(e) { await c.query('ROLLBACK').catch(()=>{}); throw e; } finally { if (locked) await c.query("SELECT pg_advisory_unlock(hashtext('CONTROLLED_PILOT_FULL_REVIEW_V1:' || $1::text))",[p.tenant]).catch(()=>{}); } }); }
async function verify(p) { return withClient(async c => { const missing = await requiredTables(c); if (missing.length) throw new Error(`missing tables: ${missing.join(',')}`); const checks={}; async function one(name, sql, params) { const r=await c.query(sql,params); checks[name]=Number(r.rows[0].count); if (checks[name]<1) throw new Error(`verify failed: ${name}`); } await one('fields_3',"SELECT count(*) FROM field_index_v1 WHERE tenant_id=$1 AND field_id IN ('field_c8_demo','field_1_demo','field_device_risk_demo')",[p.tenant]); await one('polygons_3',"SELECT count(*) FROM field_polygon_v1 WHERE tenant_id=$1 AND field_id IN ('field_c8_demo','field_1_demo','field_device_risk_demo')",[p.tenant]); await one('devices_4',"SELECT count(*) FROM device_index_v1 WHERE tenant_id=$1 AND device_id IN ('dev_soil_c8_001','dev_valve_pump_c8_001','dev_gateway_offline_001','dev_weather_station_c8_001')",[p.tenant]); await one('offline_binding',"SELECT count(*) FROM device_binding_index_v1 WHERE tenant_id=$1 AND device_id='dev_gateway_offline_001' AND field_id='field_device_risk_demo'",[p.tenant]); await one('offline_status',"SELECT count(*) FROM device_status_index_v1 WHERE tenant_id=$1 AND device_id='dev_gateway_offline_001' AND last_heartbeat_ts_ms <= $2",[p.tenant,Date.now()-90*60000]); await one('offline_alert',"SELECT count(*) FROM alert_event_index_v1 WHERE tenant_id=$1 AND event_id='alert_dev_gateway_offline_001' AND status='OPEN'",[p.tenant]); await one('request_id',"SELECT count(*) FROM facts WHERE fact_id LIKE $1 AND record_json->>'type' IN ('approval_request_v1','approval_decision_v1') AND record_json->'payload'->>'request_id' IS NOT NULL",[`${p.prefix}_%`]); await one('transition_status',"SELECT count(*) FROM facts WHERE fact_id LIKE $1 AND record_json->>'type'='operation_plan_transition_v1' AND record_json->'payload'->>'status' IS NOT NULL AND record_json->'payload'->>'created_ts' IS NOT NULL",[`${p.prefix}_%`]); await one('skill_trigger_stage',"SELECT count(*) FROM facts WHERE fact_id LIKE $1 AND record_json->>'type'='skill_run_v1' AND record_json->'payload'->>'trigger_stage' IS NOT NULL",[`${p.prefix}_%`]); await one('formal_evidence',"SELECT count(*) FROM facts WHERE fact_id LIKE $1 AND record_json->>'type'='evidence_artifact_v1' AND record_json->'payload'->>'source_lane'='FORMAL_OPERATION' AND record_json->'payload'->>'formal_eligible'='true' AND record_json->'payload'->>'is_simulated'='false'",[`${p.prefix}_%`]); await one('field_memory',"SELECT count(*) FROM field_memory_v1 WHERE tenant_id=$1 AND memory_id='fm_c8_irrigation_response_001'",[p.tenant]); return { ok:true, verify:true, tenant:p.tenant, checks, warnings:[] }; }); }
function httpGet(url) { return new Promise(resolve => { const req = http.get(url,{headers:{accept:'application/json'}},res=>{let raw='';res.on('data',d=>raw+=d);res.on('end',()=>resolve({status:res.statusCode,raw}));}); req.on('error',e=>resolve({status:0,raw:String(e.message||e)})); req.setTimeout(3000,()=>{req.destroy();resolve({status:0,raw:'timeout'});}); }); }
async function verifyApi(p, baseUrl) { if (!baseUrl) throw new Error('--verify-api requires --base-url'); const base=baseUrl.replace(/\/+$/,''); const get=async u=>{const r=await httpGet(base+u); if(!r.status||r.status>=500) throw new Error(`api failed ${u}: ${r.status}`); return r.raw;}; const reports=await get('/api/v1/customer/reports'); for (const x of ['OVERVIEW','FIELD','OPERATION','EVIDENCE_VALUE']) if(!reports.includes(x)) throw new Error(`customer reports missing ${x}`); for (const x of ['LIMITED','admin/internal preview']) if(reports.includes(x)) throw new Error(`customer reports leaked ${x}`); const fields=await get('/api/v1/customer/fields'); if(!fields.includes('C8 灌溉示范田')) throw new Error('customer fields missing C8'); const ops=await get('/api/v1/customer/operations'); for (const x of ['op_plan_c8_irrigation_formal_001','op_plan_c8_irrigation_pending_001']) if(!ops.includes(x)) throw new Error(`customer operations missing ${x}`); const wb=await get('/api/v1/operator/workbench'); for (const x of ['DEVICE_OFFLINE','APPROVAL_PENDING','ACCEPTANCE_PENDING']) if(!wb.includes(x)) throw new Error(`operator workbench missing ${x}`); const da=await get('/api/v1/operator/devices-alerts'); for (const x of ['dev_gateway_offline_001','设备影响示范田']) if(!da.includes(x)) throw new Error(`devices-alerts missing ${x}`); return { ok:true, verify_api:true, base_url:base }; }
async function exportDb(p) { return withClient(async c => { const out=exportPlan(p); const rows=(await c.query('SELECT fact_id, occurred_at, source, record_json FROM facts WHERE fact_id LIKE $1 ORDER BY fact_id',[`${p.prefix}_%`])).rows; out.facts_by_type=factByType(rows); out.export_db_json=true; return out; }); }
async function ownedCounts(c,p) { const counts={}; counts.facts=Number((await c.query('SELECT count(*) FROM facts WHERE fact_id LIKE $1',[`${p.prefix}_%`])).rows[0].count); return counts; }
async function cleanup(p, doApply) { return withClient(async c => { const counts=await ownedCounts(c,p); if(!doApply) return { ok:true, cleanup:true, apply:false, tenant:p.tenant, will_delete:counts, warnings:['cleanup dry-run only'] }; let locked=false; await c.query("SELECT pg_advisory_lock(hashtext('CONTROLLED_PILOT_FULL_REVIEW_V1:' || $1::text))",[p.tenant]); locked=true; try{ await c.query('BEGIN'); const m=p.manifest.seed_owned_ids; await removeOwned(c,'operation_state_v1',p.tenant,'operation_id',m.operations); await removeOwned(c,'approval_requests_v1',p.tenant,'approval_request_id',m.approval_requests); await removeOwned(c,'roi_ledger_v1',p.tenant,'roi_id',['roi_c8_irrigation_formal_001']); await removeOwned(c,'field_memory_v1',p.tenant,'memory_id',m.field_memory); await removeOwned(c,'alert_event_index_v1',p.tenant,'event_id',m.alerts); await c.query(`${SQL_REMOVE} FROM facts WHERE fact_id LIKE $1`,[`${p.prefix}_%`]); await c.query('COMMIT'); return { ok:true, cleanup:true, apply:true, tenant:p.tenant, deleted:counts }; } catch(e){ await c.query('ROLLBACK').catch(()=>{}); throw e; } finally { if(locked) await c.query("SELECT pg_advisory_unlock(hashtext('CONTROLLED_PILOT_FULL_REVIEW_V1:' || $1::text))",[p.tenant]).catch(()=>{}); } }); }
async function verifyClean(p) { return withClient(async c => { const counts=await ownedCounts(c,p); if(Object.values(counts).some(Number)) throw new Error(`seed-owned rows remain: ${JSON.stringify(counts)}`); return { ok:true, verify_clean:true, tenant:p.tenant, counts }; }); }
function assertNoBadPlan(p) { const text=JSON.stringify(exportPlan(p)).toLowerCase(); for(const x of ['field_id=...','device_id=...','"..."','sim'+'_trace','flight'+'-table','flight'+'_table','dev'+'_source']) if(text.includes(x)) throw new Error(`forbidden marker in plan: ${x}`); }
async function main(){ const args=parseArgs(process.argv); const p=makePlan(args.tenant); assertNoBadPlan(p); if(args.mode==='dry-run') writeOut(dryRun(p),args.out); else if(args.mode==='export-json') writeOut(exportPlan(p),args.out); else if(args.mode==='apply') writeOut(await apply(p),args.out); else if(args.mode==='verify') writeOut(await verify(p),args.out); else if(args.mode==='verify-api') writeOut(await verifyApi(p,args.baseUrl),args.out); else if(args.mode==='export-db-json') writeOut(await exportDb(p),args.out); else if(args.mode==='cleanup') writeOut(await cleanup(p,args.apply),args.out); else if(args.mode==='verify-clean') writeOut(await verifyClean(p),args.out); else writeOut(dryRun(p),args.out); }
main().catch(e => { console.error(JSON.stringify({ ok:false, error:String(e && e.message ? e.message : e) }, null, 2)); process.exit(1); });
