import { randomUUID } from "node:crypto";
import type { Pool } from "pg";

export type FailSafeTriggerTypeV1 = "DEVICE_OFFLINE"|"DEVICE_STATUS_UNKNOWN"|"APPROVAL_MISSING"|"APPROVAL_NOT_APPROVED"|"RECEIPT_TIMEOUT"|"EXECUTION_FAILED"|"ACCEPTANCE_FAILED"|"ACCEPTANCE_INCONCLUSIVE"|"SKILL_BOUNDARY_VIOLATION"|"TENANT_SCOPE_VIOLATION"|"FIELD_SCOPE_VIOLATION"|"MANUAL_REQUEST";
export type FailSafeSeverityV1 = "LOW"|"MEDIUM"|"HIGH"|"CRITICAL";

export async function createFailSafeEventV1(pool: Pool, input: any){
  const q=await pool.query(`SELECT fail_safe_event_id FROM fail_safe_event_v1 WHERE tenant_id=$1 AND project_id=$2 AND group_id=$3 AND trigger_type=$4 AND COALESCE(act_task_id,'')=COALESCE($5,'') AND COALESCE(device_id,'')=COALESCE($6,'') AND status='OPEN' LIMIT 1`,[input.tenant_id,input.project_id,input.group_id,input.trigger_type,input.act_task_id??null,input.device_id??null]);
  if(q.rows?.length) return {fail_safe_event_id:q.rows[0].fail_safe_event_id,idempotent:true};
  const id=`fs_${randomUUID().replace(/-/g,'')}`;
  await pool.query(`INSERT INTO fail_safe_event_v1 (fail_safe_event_id,tenant_id,project_id,group_id,field_id,device_id,act_task_id,prescription_id,approval_request_id,trigger_type,severity,status,reason_code,reason_detail,blocked_action,requires_manual_takeover,source,evidence_refs,metadata,created_at)
  VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,'OPEN',$12,$13,$14,TRUE,$15,$16::jsonb,$17::jsonb,$18)`,[id,input.tenant_id,input.project_id,input.group_id,input.field_id??null,input.device_id??null,input.act_task_id??null,input.prescription_id??null,input.approval_request_id??null,input.trigger_type,input.severity??'HIGH',input.reason_code,input.reason_detail??null,input.blocked_action??null,input.source??'api/fail-safe',JSON.stringify(input.evidence_refs??[]),JSON.stringify(input.metadata??{}),Date.now()]);
  return {fail_safe_event_id:id,idempotent:false};
}
export async function findOpenFailSafeForTaskV1(pool:Pool,input:any){const r=await pool.query(`SELECT * FROM fail_safe_event_v1 WHERE tenant_id=$1 AND project_id=$2 AND group_id=$3 AND act_task_id=$4 AND status='OPEN' ORDER BY created_at DESC LIMIT 1`,[input.tenant_id,input.project_id,input.group_id,input.act_task_id]);return r.rows?.[0]??null;}
export async function findOpenFailSafeForDeviceV1(pool:Pool,input:any){const r=await pool.query(`SELECT * FROM fail_safe_event_v1 WHERE tenant_id=$1 AND project_id=$2 AND group_id=$3 AND device_id=$4 AND status='OPEN' ORDER BY created_at DESC LIMIT 1`,[input.tenant_id,input.project_id,input.group_id,input.device_id]);return r.rows?.[0]??null;}
export async function requireNoOpenFailSafeForTaskV1(pool:Pool,input:any){const hit=await findOpenFailSafeForTaskV1(pool,input);if(hit)return{ok:false,error:'FAIL_SAFE_OPEN',fail_safe_event_id:hit.fail_safe_event_id};return{ok:true};}
export async function createManualTakeoverV1(pool:Pool,input:any){const q=await pool.query(`SELECT takeover_id FROM manual_takeover_v1 WHERE fail_safe_event_id=$1 AND status IN ('REQUESTED','ACKED','IN_PROGRESS') LIMIT 1`,[input.fail_safe_event_id]);if(q.rows?.length)return{takeover_id:q.rows[0].takeover_id,idempotent:true};const id=`mt_${randomUUID().replace(/-/g,'')}`;await pool.query(`INSERT INTO manual_takeover_v1 (takeover_id,tenant_id,project_id,group_id,fail_safe_event_id,field_id,device_id,act_task_id,requested_by_actor_id,requested_by_token_id,status,reason_code,note,created_at,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'REQUESTED',$11,$12,$13,$14::jsonb)`,[id,input.tenant_id,input.project_id,input.group_id,input.fail_safe_event_id,input.field_id??null,input.device_id??null,input.act_task_id??null,input.requested_by_actor_id??null,input.requested_by_token_id??null,input.reason_code??'MANUAL_REQUEST',input.note??null,Date.now(),JSON.stringify(input.metadata??{})]);return{takeover_id:id,idempotent:false};}
export async function acknowledgeManualTakeoverV1(pool:Pool,input:any){await pool.query(`UPDATE manual_takeover_v1 SET status='ACKED',acknowledged_at=$1 WHERE takeover_id=$2 AND tenant_id=$3 AND project_id=$4 AND group_id=$5`,[Date.now(),input.takeover_id,input.tenant_id,input.project_id,input.group_id]);}
export async function completeManualTakeoverV1(pool:Pool,input:any){await pool.query(`UPDATE manual_takeover_v1 SET status='COMPLETED',completed_at=$1,completed_by_actor_id=$2,completed_by_token_id=$3,completion_note=$4 WHERE takeover_id=$5 AND tenant_id=$6 AND project_id=$7 AND group_id=$8`,[Date.now(),input.completed_by_actor_id??null,input.completed_by_token_id??null,input.completion_note??null,input.takeover_id,input.tenant_id,input.project_id,input.group_id]);}
export async function resolveFailSafeEventV1(pool:Pool,input:any){await pool.query(`UPDATE fail_safe_event_v1 SET status='RESOLVED',resolved_at=$1,resolved_by_actor_id=$2,resolved_by_token_id=$3,resolution_note=$4 WHERE fail_safe_event_id=$5 AND tenant_id=$6 AND project_id=$7 AND group_id=$8`,[Date.now(),input.resolved_by_actor_id??null,input.resolved_by_token_id??null,input.resolution_note??null,input.fail_safe_event_id,input.tenant_id,input.project_id,input.group_id]);}
export async function evaluateDeviceDispatchSafetyV1(pool:Pool,input:any){const offlineAfter=Number(process.env.GEOX_FAIL_SAFE_DEVICE_OFFLINE_AFTER_MS??(5*60*1000));const r=await pool.query(`SELECT status,last_heartbeat_ts_ms FROM device_status_index_v1 WHERE tenant_id=$1 AND project_id=$2 AND group_id=$3 AND device_id=$4 LIMIT 1`,[input.tenant_id,input.project_id,input.group_id,input.device_id]);if(!r.rows?.length)return{safe:false,reason_code:'DEVICE_STATUS_UNKNOWN'};const row:any=r.rows[0];const hb=Number(row.last_heartbeat_ts_ms??0);if(!hb)return{safe:false,reason_code:'DEVICE_STATUS_UNKNOWN'};if(String(row.status??'').toUpperCase()==='OFFLINE')return{safe:false,reason_code:'DEVICE_OFFLINE'};if(Date.now()-hb>offlineAfter)return{safe:false,reason_code:'DEVICE_OFFLINE'};return{safe:true};}
